M	n.
M-1	n.
M1	n.
M2	n.
M3	n.
Ma	n.
Ma	conj.
Maa	n.
Maad	p. p.
Maa"lin	n.
Maalox	n.
Ma'am	n.
Ma"a*ra shell`	n.
Maat	a.
Mab	prop. n.
Mab"ble	v. t.
Mab"by	n.
Ma*bo"lo	n.
Mac	prop. n.
Mac	n.
macabre	adj.
Macaca	prop. n.
Macaca mulatta	n.
Macaca radiata	n.
Macaca sylvana	n.
Ma*ca"co	n.
Ma*ca"cus	n.
macadam	n.
macadam	adj.
macadamia	n.
macadamia nut	n.
Mac*ad`am*i*za"tion	n.
Mac*ad"am*ize	v. t.
Mac*ad"am road`	n.
Ma*ca"o	n.
Ma*ca"o	prop. n.
Ma`caque"	n.
Mac`a*ran"ga gum`	n.
Mac"a*rize	v. t.
Mac`a*ro"ni	n.
Mac`a*ro"ni*an	a.
Mac`a*ron"ic	n.
Mac`a*roon"	n.
Ma*cart"ney	n.
Ma*cas`sar oil"	n.
Ma*ca"u	prop. n.
Ma*cau"co	n.
Ma`ca*va"hu	n.
Ma*caw"	n.
Mac`ca*be"an	prop. a.
Mac"ca*bees	n. pl.
Mac"ca*boy	n.
maccaroni wheat	n.
Mac"co	n.
Mace	n.
Mace	n.
Mace	n.
Mace	prop. n.
macebearer	n.
Ma`c<eacute/`doine"	n.
Macedon	prop. n.
Mac`e*do"ni*an	a.
Mac`e*do"ni*an	n.
Mac`e*do"ni*an*ism	n.
Ma"cer	n.
Mac"er*ate	v. t.
Mac"er*a`ter	n.
Mac`er*a"tion	n.
mac`er*a"tive	a.
Machaeranthera	n.
Ma*chae"ro*dus	n.
Ma*che"te	n.
Mach`i*a*vel"ian	a.
Mach`i*a*vel"ian	n.
Mach"i*a*vel*ism	n.
Ma*chic"o*la`ted	a.
Mach`i*co*la"tion	n.
Ma`chi`cou`lis"	n.
mach"i*lid	n.
Machilidae	prop. n.
Ma*chin"al	a.
Mach"i*nate	v. i.
Mach"i*nate	v. t.
Mach`i*na"tion	n.
Mach"i*na`tor	n.
Ma*chine"	n.
Ma*chine"	v. t.
machine bolt	n.
machine code	n.
machine-controlled	adj.
machine gun	n.
machine-gun	a.
machine gunner	n.
machine language	n.
machinelike	adj.
machine-made	adj.
machine-oriented language	n.
machine pistol	n.
Ma*chin"er	n.
ma*chin"e-read"a*ble	a.
Ma*chin"er*y	n.
machine screw	n.
machine shop	n.
machine tool	n.
ma*chine" trans*la"tion	n.
Ma*chin"ing	a.
Ma*chin"ist	n.
machismo	n.
machmeter	n.
mach number	n.
Ma"cho	n.
ma"cho	a.
MACHO	n.
Mac"i*len*cy	n.
Mac"i*lent	a.
Mac"in*tosh	n.
mack	n.
Mackenzie	peop. n.
Mack"er*el	n.
Mack`er*el	n.
mackerel scad	n.
mackerel sky	n.
Mack"i*naw blan"ket	n.
Mac"kle	n.
Mac"kle	v. t. & i.
Ma"cle	n.
Macleaya	prop. n.
Ma"cled	a.
Maclura	prop. n.
Ma*clu"re*a	n.
Ma*clu"rin	n.
macon	n.
Ma*coun"	prop. n.
Macowanites	prop. n.
Macowanites americanus	prop. n.
Mac"ra*me	n.
Mac"ra*me lace"	a.
macrencephaly	n.
macro	n.
macro	a.
Mac"ro-	pref.
Mac`ro*bi*ot"ic	a.
macrobiotic diet	n.
Mac`ro*bi*ot"ics	n.
mac`ro*ce*phal"ic	a.
macrocephaly	n.
Macrocheira	peop. n.
Mac`ro-chem"is*try	n.
Mac`ro*chi"res	n. pl.
Macroclemys	n.
Mac"ro*cosm	n.
Mac`ro*cos"mic	a.
Mac`ro*cys"tis	n.
macro lens	n.
macrocyte	n.
macrocytosis	n.
Mac`ro*dac"tyl	n.
Mac`ro*dac*tyl"ic	a.
Mac`ro*di*ag"o*nal	n.
Mac"ro*dome	n.
Mac"ro*dont	a.
Mac"ro*far`ad	n.
macroglia	n.
Mac`ro*glos"si*a	n.
Mac`rog*nath"ic	a.
Mac"ro*graph	n.
Ma*crog"ra*phy	n.
Ma*crol"o*gy	n.
Ma*crom"e*ter	n.
mac`ro*mol"e*cule	n.
mac`ro*mo*lec"u*lar	n.
Ma"cron	n.
Mac`ro*pet"al*ous	a.
mac"ro*phage	n.
Ma*croph"yl*lous	a.
Mac`ro*pin"a*coid	n.
Mac"ro*pod	n.
Ma*crop"o*dal	a.
Mac`ro*po"di*an	n.
Ma*crop"o*dous	a.
Mac"ro*prism	n.
Ma*crop"te*res	n. pl.
Ma*crop"ter*ous	a.
Mac"ro*pus	n.
Mac`ro*pyr"a*mid	n.
Mac`ro*scop"ic	a.
Mac`ro*spo*ran"gi*um	n.
Mac"ro*spore	n.
Mac`ro*spor"ic	a.
Mac"ro*tone	n.
Ma*cro"tous	a.
ma*cro"tus	n.
Ma*crou"ra	n. pl.
Macrouridae	prop. n.
Mac`ro*zo"o*spore	n.
Ma*cru"ra	n. pl.
Ma*cru"ral	a.
Ma*cru"ran	n.
Macruridae	prop. n.
Ma*cru"roid	a.
Ma*cru"rous	a.
Mac*ta"tion	n.
Mac"tra	n.
Mac"u*la	n.
macula lutea	n.
Mac"u*late	v. t.
Mac"u*late	a.
Mac"u*la`ted	a.
Mac"u*la"tion	n.
Mac"u*la*to*ry	a.
Mac"u*la*ture	n.
Mac"ule	n.
Mac"ule	v. t.
Mac"u*lose`	a.
macumba	n.
macumba	n.
Mad	p. p.
Mad	a.
Mad	v. t.
Mad	v. i.
Mad	n.
Madagascan	prop. a.
Madagascan	prop. n.
Mad`a*gas"car	prop. n.
madagascar cat	n.
madagascar jasmine	n.
madagascar pepper	n.
madagascar periwinkle	n.
madagascar plum	n.
madake	n.
Mad"am	n.
Ma`dame"	n.
Mad"-ap`ple	n.
Mad"brain`	a.
Mad"brained`	a.
Mad"cap`	a.
Mad"cap`	n.
Mad"den	v. t.
Mad"den	v. i.
maddened	adj.
maddening	adj.
Mad"der	n.
madder family	n.
Mad"der*wort`	n.
Mad"ding	a.
Mad"dish	a.
mad-dog skullcap	n.
Made	n.
Made	imp. & p. p.
Made	a.
Mad"e*cass	prop. n.
Mad`e*cas"see	prop. a.
Mad`e*fac"tion	n.
Mad"e*fy	v. t.
Mad`e*gas"sy	n. & a.
Ma*dei"ra	n.
Ma*dei"ra vine	n.
Madeira wood	n.
made-to-order	adj.
made-up	adj.
Madge	n.
Mad"-head`ed	a.
Mad"house`	n.
Ma"di*a	n.
madia oil	n.
madia oil plant	n.
Mad"id	a.
Mad`is*te"ri*um	n.
Mad"joun	n.
Mad"ly	adv.
Mad"man	n.
Mad"nep	n.
Mad"ness	n.
Ma*don"na	n.
madonna lily	n.
Ma"do*qua	n.
Ma`drague"	n.
ma*dras"	n.
Ma"dre*perl	n.
Mad`re*po"ra	n.
Mad`re*po*ra"ri*a	n. pl.
Mad"re*pore	n.
madriporian coral	n.
Mad`re*po"ri*an	a.
Mad`re*po"ri*form	a.
Mad"re*po*rite	n.
Ma*drier"	n.
Mad"ri*gal	n.
Mad"ri*gal*er	n.
Mad"ri*gal*ist	n.
Mad`ri*le"ni*an	a.
Ma*dri"na	n.
ma*dro"na	n.
madrilene	n.
madwoman	n.
Mad"wort`	n.
Maeandra	n.
Mae West	prop. n.
Maeg"bote`	n.
Mael"strom	n.
Mae"nad	n.
Ma`es*to"so	a. & adv.
Maes"tricht mon"i*tor	n.
Mafa	prop. n.
Maf"fi*a	n.
maffick	v. i.
Maf`fi*o"so	n.
Maf"fle	v. i.
Maf"fler	n.
Maf"i*a	n.
mag	n.
Magadhan	prop. n.
Mag`a*zine"	n.
Mag`a*zine"	v. t.
Magazine camera	n.
Mag`a*zine" rack`	n.
Mag`a*zin"ing	n.
Mag`a*zin"ist	n.
Mag"bote`	n.
Mag"da*la	a.
Mag"da*len	n.
Mag*da"le*on	n.
Mag"de*burg	n.
Mage	n.
Mag`el*lan"ic	a.
Mag`el*lan"ic cloud	n.
Magen David	n.
ma*gen"ta	n.
Magged	a.
Mag`gio"re	a.
Mag"got	n.
Mag"got*i*ness	n.
Mag"got*ish	a.
Mag"got-pie`	n.
Mag"got*y	a.
Magh	n.
Ma"ghet	n.
Ma"gi	n. pl.
Ma"gi*an	a.
Ma"gi*an	n.
Mag"ic	n.
Mag"ic	a.
Mag"ic*al*ly	adv.
magic bullet	n.
Ma*gi"cian	n.
magic lantern	n.
magic spell	n.
magic trick	n.
Ma*gilp"	n.
Maginot line	prop. n.
Ma*gis"ter	n.
Mag`is*te"ri*al	a.
Mag`is*te`ri*al"i*ty	n.
Mag`is*te"ri*al*ly	adv.
Mag`is*te"ri*al*ness	n.
Mag"is*ter*y	n.
Mag"is*tra*cy	n.
Mag"is*tral	a.
Mag"is*tral	n.
Mag`is*tral"i*ty	n.
Mag"is*tral*ly	adv.
Mag"is*trate	n.
Mag`is*trat"ic	a.
Mag"is*tra`ture	n.
Mag"ma	n.
Mag"na Car"ta	n.
Magna Mater	prop. n.
Mag`na*nim"i*ty	n.
Mag*nan"i*mous	a.
Mag*nan"i*mous*ly	adv.
Mag"nase black`	n.
Mag*ne"si*a	n.
Mag*ne"sian	a.
Mag*ne"sic	a.
Mag"ne*site	n.
Mag*ne"si*um	n.
magnesium hydroxide	n.
magnesium oxide	n.
Mag"net	n.
Mag*net"ic	a.
Mag*net"ic	n.
Mag*net"ic*al*ly	adv.
Mag*net"ic*al*ness	n.
magnetic bottle	n.
magnetic compass	n.
magnetic declination	n.
magnetic dip	n.
magnetic dipole	n.
magnetic dipole moment	n.
magnetic disc	n.
magnetic equator	n.
magnetic field	n.
magnetic field strength	n.
magnetic flux	n.
magnetic flux density	n.
magnetic force	n.
magnetic head	n.
Mag`ne*ti"cian	n.
magnetic inclination	n.
magnetic induction	n.
magnetic intensity	n.
magnetic iron-ore	n.
magnetic levitation	n.
magnetic line of force	n.
magnetic meridian	n.
magnetic mine	n.
magnetic moment	n.
magnetic monopole	n.
magnetic north	n.
Mag*net"ic*ness	n.
magnetic pole	n.
magnetic recorder	n.
magnetic resonance	n.
mag*net"ic res"on*ance im"ag*ing	n.
Mag*net"ics	n.
magnetic storm	n.
magnetic tape	n.
magnetic variation	n.
Mag`net*if"er*ous	a.
Mag"net*ism	n.
Mag"net*ist	n.
Mag"net*ite	n.
Mag"net*i`za*ble	a.
Mag`net*i*za"tion	n.
Mag"net*ize	v. t.
Mag`net*i*zee"	n.
Mag"net*i`zer	n.
mag*ne"to	n.
Mag"net*o-	pref.
Mag`net*o-e*lec"tric	a.
Mag`net*o-e`lec*tric"i*ty	n.
Mag*net"o*graph	n.
mag*net"o*hy`dro*dy*nam"ics	n.
Mag`net*om"e*ter	n.
Mag`net*o*met"ric	a.
Mag`net*o*mo"tive	a.
magnetomotive force	n.
Mag`net*o*mo"tor	n.
mag"net*on	n.
mag*net"o*sphere	n.
Mag`net*o*ther"a*py	n.
mag"ne*tron	n.
Mag"ni*fi`a*ble	a.
Mag*nif"ic	a.
Mag*nif"i*cat	n.
Mag*nif"i*cate	v. t.
Mag`ni*fi*ca"tion	n.
Mag*nif"i*cence	n.
Mag*nif"i*cent	a.
Mag*nif"i*cent*ly	adv.
Mag*nif"i*co	n.
magnified	adj.
Mag"ni*fi`er	n.
Mag"ni*fy	v. t.
Mag"ni*fy	v. i.
magnifying glass	n.
Mag*nil"o*quence	n.
Mag*nil"o*quent	a.
Mag*nil"o*quous	a.
Mag"ni*tude	n.
Mag*no"li*a	n.
Magnoliaceae	n.
Mag*no`li*a"ceous	a.
Magnolia State	prop. n.
Magnoliidae	n.
Magnoliophyta	n.
magnoliopsid	n.
Magnoliopsida	n.
Mag"num	n.
mag"num	a.
mag"num o"pus	n.
magnus hitch	n.
mag tape	n.
Mag"ot	n.
Mag"ot-pie`	n.
Mag"pie	n.
Ma`gua*ri"	n.
Mag"uey	n.
magus	n.
Mag"yar	prop. n.
Mag"yar	prop. a.
Ma"ha	n.
Ma"ha	prop. n.
Ma*ha*ba"ra*ta	n.
Ma*ha"led	n.
maharaja	n.
maharani	n.
Ma`ha*rif"	n.
Ma*har"mah	n.
Ma*hat"ma	n.
Ma*hat"ma Ghandi	prop. n.
Mahayana	n.
Mahayanist	n.
Mah"di	n.
Mah"di*ism	n.
Mah"dism	n.
Mahican	prop. n.
mahimahi	n.
mahjong	n.
mahl"stick`	n.
Ma"hoe	n.
Ma*hog"a*ny	n.
Ma*ho"li	n.
Ma*hom"ed*an	n.
Ma*hom"et	prop. n.
Ma*hom"et*an*ism	prop. n.
Ma*hom"et*an*ize	v. t.
Ma*hom"et*ism	n.
Ma*hom"et*ist	n.
Ma*hom"et*ry	n.
Ma*hone"	n.
ma*ho"ni*a	n.
Mahonia	prop. n.
ma*hon" stock`	n.
Ma"ho*ri	n.
Ma`hound	n.
Ma*hout"	n.
Ma*ho"vo	n.
Mah*rat"i	n.
Mah*rat"ta	n.
Ma*hu"met*an	n.
Mah"wa tree`	n.
Ma"ian	n.
Maid	n.
Mai*dan"	n.
Maid"en	n.
Maid"en	a.
Maid"en	v. t.
maiden aunt	n.
maiden blue-eyed mary	n.
maid"en*hair`	n.
maidenhair berry	n.
maidenhair fern	n.
maidenhair spleenwort	n.
maidenhair tree	n.
Maid"en*head	n.
Maid"en*hood	n.
Maid"en*like`	a.
Maid"en*li*ness	n.
Maid"en*ly	a.
Maid"en*ly	adv.
maiden over	n.
maiden pink	n.
Maid"en*ship	n.
Maid"hood	n.
Maid`ma"ri*an	n.
Maid"pale`	a.
Maid"serv`ant	n.
Maid's" hair`	a.
maieutic method	n.
Ma*ieu"tics	n.
Mai"ger	n.
Mai"gre	a.
Mai"hem	n.
Mai*kel"	n.
Mai*kong"	n.
Mail	n.
Mail	n.
Mail	n.
Mail	v. t.
Mail	n.
Mail	v. t.
Mail"a*ble	a.
mail"bag`	n.
mail"boat`	n.
mail"box`	n.
mail call	n.
mail car	n.
mail carrier	n.
Mail"clad`	a.
mail clerk	n.
Mailed	a.
Mailed	a.
mail fraud	n.
Mail"ing	n.
mail"ing	n.
mailing address	n.
mailing list	n.
maillot	n.
mail"man`	n.
mail-order buying	n.
mail pouch	n.
Mail"-shell`	n.
mail slot	n.
mailsorter	n.
mail train	n.
Maim	v. t.
Maim	n.
Maim"ed*ly	adv.
maim"ed*ness	n.
main	n.
Main	n.
Main	a.
Main	adv.
main course	n.
main deck	n.
Maine	prop. n.
maine lobster	n.
main entry word	n.
main file	n.
main"frame`	n.
Main`-gauche"	n.
Main"-ham`per	n.
Main"land`	n.
mainland China	n.
main line	n.
main"line`	v. t.
Main"ly	adv.
Main"ly	adv.
Main"mast`	n.
main office	n.
main memory	n.
Main"or	n.
Main"per*na*ble	a.
Main"per*nor	n.
Main"pin	n.
Main"prise	n.
Main"prise	v. t.
main road	n.
main rotor	n.
mains	n.
mains	n.
Main"sail`	n.
main" se`quence	n.
main"sheet`	n.
main"spring`	n.
Main"stay`	n.
main"stream`	n.
main"stream`	v. t.
main"streamed`	adj.
main street	n.
Main"swear`	v. i.
Main*tain	v. t.
Main*tain"a*ble	a.
Main*tain"er	n.
Main*tain"or	n.
Main"te*nance	n.
maintenance man	n.
maintenance staff	n.
main"top`	n.
main-topmast	n.
main-topsail	n.
Main" yard`	a.
Mais"ter	n.
Mais"ter	a.
Mais"tre	n.
Mais"tress	n.
Mai"thes	n.
mai`tre d'ho*tel"	n.
maize	n.
majagua	n.
maja squinado	n.
Maj`es*tat"ic	a.
Ma*jes"tic	a.
Ma*jes"tic*al	a.
Ma*jes"tic*ness	n.
Maj"es*ty	n.
Majidae	prop. n.
Ma*jol"i*ca	n.
Ma"jor	a.
Ma"jor	n.
Majorana	prop. n.
Ma`jo`rat"	n.
Ma"jor*ate	n.
Ma"jor*ate	v. t.
Ma`jor*a"tion	n.
major axis	n.
Ma*jor"can	prop. a.
major diatonic scale	n.
Ma`jor-do"mo	n.
major form class	n.
Ma"jor gen"er*al	n.
majority leader	n.
majority rule	n.
major league	n. 
major-league	a.
major-league club	n.
major leaguer	n.
major power	n.
major premise	n.
Ma"jor*ship	n.
majors	n. pl.
major suit	n.
major term	n.
Maj"oun	n.
Ma*jus"cu*lae	n. pl.
Ma*jus"cule	n.
mak"a*ble	a.
Makalu	prop. n.
mak"a*ron	n.
make	n.
make	v. t.
Make	v. i.
Make	n.
Make and break	n.
make"-be*lief`	n.
make" be*lieve`	v. i.
make"-be*lieve`	n.
Make"-be*lieve`	a.
Mak"ed	p. p.
Make"-game`	n.
make known	v. t.
Make"less	a.
Make"-peace`	n.
Mak"er	n.
makeready	n.
make"shift`	n.
make"up`	n.
make water	v. i.
Make"weight`	n.
make-work	n.
Ma"ki	n.
Mak"ing	n.
Mak"ing-i`ron	n.
Mak"ing-up`	n.
mako	n.
makomako	n.
mako shark	n.
Maksutov telescope	n.
Mal-	n. pl.
Mal"a*bar`	n.
malabar kino	n.
Malacanthidae	prop. n.
Mal`a*ca*tune"	n.
Ma*lac"ca	n.
malacca cane	n.
Mal"a*chite	n.
Mal`a*cis"sant	a.
Mal`a*cis*sa"tion	n.
Mal`a*cob*del"la	n.
Mal"a*co*derm	n.
Mal"a*co*lite	n.
Mal`a*col"o*gist	n.
Mal`a*col"o*gy	n.
Mal`a*cop"o*da	prop. n. pl.
Mal`a*cop`ter*yg"i*an	n.
Mal`a*cop`te*ryg"i*i	prop. n. pl.
Mal`a*cop`ter*yg"i*ous	a.
Mal`a*cos"te*on	n.
Mal`a*cos"to*mous	a.
Mal`a*cos"tra*ca	prop. n. pl.
Mal`a*cos"tra*can	n.
Mal`a*cos`tra*col"o*gy	n.
Mal`a*cos"tra*cous	a.
Mal`a*co*toon"	n.
Mal`a*co*zo"a	n. pl.
Mal`a*co*zo"ic	a.
Mal`ad*dress"	n.
Mal`ad*just"ment	n.
Mal`ad*min`is*tra"tion	n.
Mal`a*droit"	a.
mal"a*dy	n.
Mal"a*ga	n.
Mal`a*gash"	n.
Mal`a*gas"y	n. sing. & pl.
Malagasy Republic	prop. n.
Ma`laise"	n.
Ma*lam"ate	n.
Ma*lam"bo	n.
Mal`am*eth"ane	n.
Ma*lam"ic	a.
Ma*lam"ide	n.
mal"an*ders	n. pl.
mal"a*pert	a.
mal"a*prop*ism	n.
mal*ap"ro*pos`	a. & adv.
Mal*ap`te*ru"rus	prop. n.
Malapterurus electricus	prop. n.
Ma"lar	a.
ma"lar	n.
malar bone	n.
ma*la"ri*a	n.
Ma*la"ri*al	a.
malaria mosquito	n.
Malaria parasite	n.
Mal`as*sim`i*la"tion	n.
Ma"late	n.
malawi kwacha	n.
Ma"lax	v. t.
Mal`ax*a"tion	n.
mal"ax*a`tor	n.
Malaxis	prop. n.
Malaxis-unifolia	n.
Ma*lay"	prop. n.
Ma*lay"	prop. a.
Malaya	prop. n.
Ma"la*ya"lam	prop. n.
Malayan tapir	n.
Malay Archipelago	prop. n.
Malayo-Polynesian	adj.
Malay Peninsula	prop. n.
Malaysia	prop. n.
Malaysian	adj.
Mal"brouck	n.
Malcolmia	prop. n.
Malcolm Little	prop. n.
Malcolm stock	n.
Malcolm X	prop. n.
mal*con`for*ma"tion	n.
mal"con*tent`	a.
Mal"con*tent`	n.
mal`con*tent"ed	a.
mal*da"ni*an	n.
mal de mer	n.
Maldive Islands	prop. n.
Maldivian	n.
Maldon	prop. n.
Male-	a.
Male	n.
Male	a.
Male	n.
Male`ad*min`is*tra"tion	n.
Ma*le"ate	n.
male"ber`ry	n.
male body	n.
Male*branch"ism	n.
male chauvinism	n.
male chauvinist	n.
Male*con`for*ma"tion	n.
Male"con*tent`	a.
Mal`e*di"cen*cy	n.
Mal`e*di"cent	a.
Mal"e*dict	a.
Mal`e*dic"tion	n.
Mal`e*fac"tion	n.
Mal`e*fac"tor	n.
Mal`e*fac"tress	n.
Male*fea"sance	n.
male fern	n.
Ma*lef"ic	a.
Mal"e*fice	n.
Ma*lef"i*cence	n.
Ma*lef"i*cent	a.
Mal`e*fi"cial	a.
Mal`e*fi"ci*ate	v. t.
Mal`e*fi`ci*a"tion	n.
Mal`e*fi"cience	n.
Mal`e*fi"cient	a.
Male`for*ma"tion	n.
Ma*le"ic	a.
maleic acid	n.
Ma*len"gine	n.
Ma"le*o	n.
Male-o"dor	n.
male orchis	n.
male orgasm	n.
male plug	n.
Male*prac"tice	n.
Male"-spir`it*ed	a.
Mal"et	n.
Male*treat"	v. t.
Ma*lev"o*lence	n.
Ma*lev"o*lent	a.
Ma*lev"o*lent*ly	adv.
Ma*lev"o*lous	a.
Mal*ex`e*cu"tion	n.
Ma*le"yl	n.
Mal*fea"sance	n.
malfeasant	n.
Mal`for*ma"tion	n.
Mal*gra"cious	a.
Mal"gre	prep.
malheur wire lettuce	n.
Malian	prop. a.
Malian	prop. n.
Mali franc	prop. n.
Ma"lic	a.
mal"ice	n.
Mal"ice	v. t.
Mal"i*cho	n.
Ma*li"cious	a.
malicious mischief	n. 
ma*lign"	a.
Ma*lign"	v. t.
Ma*lign"	v. i.
Ma*lig"nance	n.
ma*lig"nant	a.
Ma*lig"nant	n.
malignant anemia	n.
malignant melanoma	n.
malignant neoplasm	n.
malignant tumor	n.
ma*lig"nant*ly	adv.
maligned	adj.
ma*lign"er	n.
ma*lig"ni*fy	v. t.
Ma*lig"ni*ty	n.
Ma*lign"ly	adv.
Ma*lin"ger	v. i.
Ma*lin"ger*er	n.
Ma*lin"ger*y	n.
Mal"i*son	n.
Mal"kin	n.
Mall	n.
Mall	v. t.
Mall	n.
Mall	n.
Mal"lard	n.
Mal"le*a*bil"i*ty	n.
Mal"le*a*ble	a.
Mal"le*a*ble*ize	v. t.
Mal"le*a*ble*ness	n.
Mal"le*al	a.
Mal"le*ate	v. t.
Mal`le*a"tion	n.
mal"le*cho	n.
mal"lee	n.
mal*lee" bird`	n.
mallee hen	n.
Mal"le*mock	n.
Mal"len*ders	n. pl.
Mal*le"o*lar	a.
Mal*le"*o*lus	n.
Mal"let	n.
Mal"le*us	n.
Mal*loph"a*ga	n. pl.
Mal*lo"tus	n.
Mal"low	n.
mallow family	n.
mal"low*wort`	n.
Malm	n.
mal"ma	n.
Mal"mag	n.
Malm"sey	n.
malnourished	adj.
mal`nu*tri"tion	n.
Mal*ob`ser*va"tion	n.
mal*o"dor	n.
mal*o"dor*ous	a.
mal*o"dor*ous*ness	n.
mal"o*nate	a.
Ma*lon"ic	a.
Mal"o*nyl	n.
malonylurea	n.
malope	n.
Malopterurus	prop. n.
Malopterurus electricus	prop. n.
Malosma	prop. n.
Mal"pais`	n.
Mal*pi"ghi*a	n.
Mal*pi`ghi*a"ceous	a.
Malpighia glabra	prop. n.
Mal*pi"ghi*an	a.
malpighian body	n. 
malpighian corpuscle	n.
malpighian layer	n.
malposed tooth	n.
Mal`po*si"tion	n.
Mal*prac"tice	n.
Malt	n.
Malt	a.
Malt	v. t.
Malt	v. i.
Malta	n.
malta fever	n.
Mal"ta*lent	n.
malt"ase	n.
malt"ed	n.
malted milk	n.
Mal*tese"	prop. a.
maltese cat	n.
maltese cross	n.
Maltese dog	n.
maltese pound	n.
Mal"tha	n.
Malthus	prop. n.
Mal*thu"sian	a.
Mal*thu"sian	n.
Mal*thu"sian*ism	n.
malthusian theory	n.
Malt"in	n.
Malt"ing	n.
malt liquor	n.
Malt"man	n.
mal"to*bi"ose	a.
Mal*ton"ic	a.
Malt"ose`	n.
mal*treat"	v. t.
mal*treat"ment	n.
Malt"ster	n.
malt sugar	n.
malt whiskey	n.
malt"worm`	n.
malt"y	a.
Ma"lum	n.
Malva	prop. n.
Malvaceae	prop. n.
Mal*va"ceous	a.
Malvales	n.
Malva neglecta	prop. n.
malvasia	n.
Malvastrum	n.
Malva sylvestris	prop. n.
Malvaviscus	n.
Mal`ver*sa"tion	n.
Mal"ve*sie	n.
Mam	n.
Ma*ma"	n.
Mam"a*luke	n.
mama's boy	n.
Mam"e*lon	n.
Mam`e*lu"co	n.
Mam"e*luke	n.
Mam"il*la`ted	a.
Mam*ma"	n.
Mam"ma	n.
Mam"mal	n.
Mam*ma"li*a	n. pl.
Mam*ma"li*an	a.
Mam`ma*lif"er*ous	a.
Mam`ma*log"ic*al	a.
Mam*mal"o*gist	n.
Mam*mal"o*gy	n.
Mam"ma*ry	a.
mammary gland	n.
mama's boy	n.
Mammea	n.
Mammea americana	n.
Mam*mee"	n.
mammee apple	n.
Mam"mer	v. i.
Mam"met	n.
Mam"met*ry	n.
Mam"mi*fer	n.
Mam*mif"er*ous	a.
Mam"mi*form	a.
Mam*mil"la	n.
Mam"mil*la*ry	a.
Mam"mil*late	a.
Mam*mil"li*form	a.
Mam"mil*loid	a.
Mam"mock	n.
Mam"mock	v. t.
Mam"mo*dis	n.
Mam*mol"o*gy	n.
Mam"mon	n.
Mam"mon*ish	a.
Mam"mon*ism	n.
Mam"mon*ist	n.
Mam"mon*ite	n.
Mam`mon*i*za"tion	n.
Mam"mon*ize	v. t.
Mam*mose"	a.
Mam"moth	n.
Mam"moth	a.
mam"mo*thrept	n.
Mammuthus	prop. n.
Mammuthus primigenius	prop. n.
Mammutidae	prop. n.
mam"my	n.
mamoncillo	n.
Mam"zer	n.
Man	n.
Man	v. t.
Man"a*ble	a.
Man"ace	n. & v.
Man"a*cle	n.
Man"a*cle	v. t.
Man"age	n.
Man"age	v. t.
Man"age	v. i.
Man`age*a*bil"i*ty	n.
Man"age*a*ble	a.
managed economy	n.
Man"age*less	a.
Man"age*ment	n.
management consultant	n.
management personnel	n. pl.
Man"a*ger	n.
manageress	n.
Man`a*ge"ri*al	a.
Man"a*ger*ship	n.
Man"age*ry	n.
managing director	n.
managing editor	n.
Man"a*kin	n.
Man"a*kin	n.
Manannan	prop. n.
man and wife	n.
man-at-arms	n.
man`a*tee"	n.
Ma*na"tion	n.
Man"bird`	n.
Man"bote`	n.
Man"ca	n.
Manche	n.
Manchester terrier	prop. n.
Man"chet	n.
Man`chi*neel"	n.
Man*chu"	a.
Man"ci*pate	v. t.
Man`ci*pa"tion	n.
Man"ci*ple	n.
Man*co"na bark`	n.
-man`cy	n.
Man*da"mus	n.
Man`da*rin"	n.
Man`da*rin"ate	n.
mandarin duck	n.
Man`da*rin"ic	a.
Man`da*rin"ing	n.
Man`da*rin"ism	n.
man`da*rin" or"ange	n.
Man"da*ta*ry	n.
Man"date	n.
Man*da"tor	n.
Man"da*to*ry	a.
Man"da*to*ry	n.
Man"del*ate	n.
Man*del"ic	a.
Man"der	v. t. & i.
Man"der*il	n.
Man"di*ble	n.
Man*dib"u*lar	a.
mandibular joint	n.
Man*dib"u*late	a.
Man*dib"u*late	n.
Man`di*bu"li*form	a.
Man*dib`u*lo*hy"oid	a.
man"dil	n.
Man*dil"ion	n.
Man*din"gos	n. pl.
Man"di*oc	n.
Man"dle*stone`	n.
Mand"ment	n.
Man*do"la	n.
Man"do*lin	n.
Man"dore	n.
Man*drag"o*ra	n.
Man*drag"o*rite	n.
man"drake	n.
mandrake root	n.
Man"drel	n.
mandril	n.
man"drill	n.
Manduca	prop. n.
Man"du*ca*ble	a.
Man"du*cate	v. t.
Man`du*ca"tion	n.
Man"du*ca*to*ry	a.
Man*du"cus	n.
Mane	n.
maned sheep	n.
maned wolf	n.
Man"-eat`er	n.
man-eating shark	n.
Maned	a.
Ma*nege"	n.
Ma"neh	n.
Mane"less	a.
Man"e*quin	n.
Ma*ne"ri*al	a.
Ma"nes	n. pl.
Mane"sheet`	n.
Ma*neu"ver	n.
Ma*neu"ver	v. i.
Ma*neu"ver	v. t.
Ma*neu"ver*er	n.
man Friday	prop. n.
Man"ful	a.
Man"ga*bey	n.
Man"gan	n.
Man"ga*nate	n.
Man`ga*ne"sate	n.
Man`ga*nese"	n.
manganese bronze	n.
Man`ga*nese" steel	a.
Man`ga*ne"sic	a.
Man`ga*ne"sious	a.
Man`ga*ne"si*um	n.
Man`ga*ne"sous	a.
Man`gan"ic	a.
manganic acid	n.
Man`ga*nif"er*ous	a.
Man"ga*nite	n.
Man*ga"ni*um	n.
Man"ga*nous	a.
Mang"corn`	n.
Mange	n.
Man"gel-wur`zel	n.
man"ger	n.
mangey	adj.
Mangifera	prop. n.
man"gi*ly	adv.
man"gi*ness	n.
Man"gle	v. t.
man"gle	n.
Man"gle	v. t.
Man"gler	n.
Man"gler	n.
Man"go	n.
mango tree	n.
Man"gold*wur`zel	n.
Man"go*nel	n.
Man"go*nism	n.
Man"go*nist	n.
Man"go*nize	v. t.
Man"go*steen	n.
Man"grove	n.
mangrove family	n.
mangrove snapper	n.
Mangue	n.
man"gy	a.
Man*ha"den	n.
Man*han"dle	v. t.
Manhattan Project	prop. n.
Man"head	n.
Man`h<egrave/s" proc"ess	n.
Man"hood	n.
man hour	n.
man"hunt`	n.
Ma"ni*a	n.
Man"i*a*ble	a.
Ma"ni*ac	a.
ma"ni*ac	n.
Ma*ni"a*cal	a.
Man"ic	a.
Man"i*cate	a.
manic-depressive	n.
manic-depressive psychosis	n.
manic disorder	n.
Man`i*chae"an	n.
Man`i*chae"an	a.
Man"i*chae*ism	n.
Man"i*che*ist	n.
Man"i*chord	adj.
manicotti	n.
Man"i*cure	v. t. & i.
man"i*cure	n.
man"i*cure	n.
man"i*cur`ist	n.
ma"nid	n.
ma`nie"	n.
Man"i*fest	a.
Man"i*fest	n.
Man"i*fest	v. t.
Man"i*fest`a*ble	a.
Man`i*fes*ta"tion	n.
manifest destiny	n.
Man"i*fest`i*ble	a.
Man"i*fest*ly	adv.
Man"i*fest*ness	n.
Man`i*fes"to	n.
Man"i*fold	a.
Man"i*fold	n.
Man"i*fold	v. t.
Man"i*fold`ed	a.
Man"i*fold`ly	adv.
Man"i*fold`ness	n.
Man"i*form	a.
ma*ni"glion	n.
Man"i*hoc	n.
Man"i*kin	n.
Ma*nil"a	a.
manila bay	n.
manila bean	n.
manila grass	n.
Manila hemp	n.
manila maguey	n.
manila paper	n.
manila tamarind	n.
Ma*nil"io	n.
manilla	n.
Manilkara	prop. n.
Ma*nil"la	n.
Ma*nil"la	a.
Ma*nille"	n.
man in the street	n.
Ma"ni*oc	n.
Man"i*ple	n.
Ma*nip"u*lar	a.
Ma*nip"u*late	v. t.
Ma*nip"u*late	v. i.
Ma*nip`u*la"tion	n.
ma*nip"u*la*tive	a.
ma*nip"u*la*tive	n.
Ma*nip"u*la`tor	n.
Ma*nip"u*la*to*ry	a.
Ma"nis	n.
Man"i*to	n.
Man"i*trunk	n.
man jack	n.
man`kind"	n.
Man"kind`	a.
Manks	prop. a.
Man"less	a.
Man"less*ly	adv.
Man"like`	a.
Man"li*ness	n.
Man"ling	n.
Man"ly	a.
Man"ly	adv.
man-made	adj.
man-made fiber	n.
Man"na	n.
manna ash	n.
Man"na croup`	n.
manna gum	n.
manna lichen	n.
manned	adj.
mannequin	n.
Man"ner	n.
M<aum/n"ner*chor`	n.
Man"nered	a.
Man"ner*ism	n.
Man"ner*ist	n.
Man"ner*li*ness	n.
Man"ner*ly	a.
Man"ner*ly	adv.
manner name	n.
manner of speaking	n.
Mann"heim gold"	n.
Man"nish	a.
Man"ni*tan	n.
Man"ni*tate	n.
Man"nite	n.
Man*nit"ic	a.
man"ni*tol	n.
Man"ni*tose`	n.
Ma"no	n.
Ma*noeu"vre	n. & v.
man of action	n.
man of affairs	n.
man of deeds	n.
man of letters	n.
man of means	n.
man of science	n.
man-of-the-earth	n.
man of the world	n.
Man`-of-war"	n
man-of-war bird	n.
Man"o*graph	n.
Ma*nom"e*ter	n.
Man`o*met"ric	a.
Man"or	n.
manor hall	n.
Ma*no"ri*al	a.
Man"o*scope	n.
Ma*nos"co*py	n.
Ma*no"ver*y	n.
Man"quell`er	n.
Man"red	n.
Man"rope`	n.
Man"sard roof"	n.
Man"serv`ant	n.
Man"sion	n.
Man"sion	v. i.
Man"sion*a*ry	a.
mansion house	n.
Man"sion*ry	n.
man-sized	adj.
Man"slaugh`ter	n.
Man"slay`er	n.
Man"steal`er	n.
Man"steal`ing	n.
Man"suete	a.
Man"sue*tude	n.
Man"swear`	v. i.
Man"ta	n.
manta ray	n.
Mant*choo"	a. & n.
Man`teau"	n.
Manteidae	prop. n.
Man"tel	n.
Man"tel*et	n.
Man`tel*let"ta	n.
Man"tel*piece`	n.
Man"tel*shelf`	n.
Man"tel*tree`	n.
Man"tic	a.
mantichora	n.
mantid	n.
Mantidae	prop. n.
mantiger	n.
Man*til"la	n.
Mantinea	prop. n.
Man"tis	n.
mantis crab	n.
mantis prawn	n.
man*tis"pid	n.
Mantispidae	prop. n.
man*tis*sa	n.
man"tle	n.
Man"tle	v. t.
Man"tle	v. i.
man"tled	adj.
mantled ground squirrel	n.
man"tle*piece	n.
Man"tlet	n.
Man"tling	n.
Man"to	n.
Man*tol"o*gist	n.
Man*tol"o*gy	n.
Mantoux test	prop. n.
Man"tra	n.
Man"trap`	n.
Man"tu*a	n.
Man"tu*a*mak`er	n.
Man"tu*an	a.
Ma"nu	n.
Man"u*al	a.
Man"u*al	n.
manual alphabet	n.
manual dexterity	n.
Man"u*al*ist	n.
manual labor	n.
manual laborer	n.
man"u*al*ly	adv.
Man"u*a*ry	a.
Ma*nu"bi*al	a.
Ma*nu"bri*al	a.
Ma*nu"bri*um	n.
Man"u*code	n.
Man`u*du"cent	n.
Man`u*duc"tion	n.
Man`u*duc"tor	n.
Man`u*fac"to*ry	n.
Man`u*fac"to*ry	a.
Man`u*fac"tur*al	a.
Man`u*fac"ture	n.
Man`u*fac"ture	v. t.
Man`u*fac"ture	v. i.
manufactured	adj.
Man`u*fac"tur*er	n.
Man`u*fac"tur*ing	a.
manufacturing business	n.
manufacturing plant	n.
ma"nul	n.
Man"u*mise`	v. t.
Man`u*mis"sion	n.
Man`u*mit"	v. t.
Man"u*mo`tive	a.
Man"u*mo`tor	n.
Ma*nur"a*ble	a.
Ma*nur"age	n.
Ma*nur"ance	n.
Ma*nure"	v. t.
ma*nure"	n.
Ma*nure"ment	n.
Ma*nur"er	n.
Ma*nu"ri*al	a.
Ma*nur"ing	n.
Ma"nus	n.
Man"u*script	a.
Man"u*script	n.
Man"u*script`al	a.
Man`u*ten"en*cy	n.
Man"way`	n.
Manx	a.
Manx cat	prop. n.
Manx shearwater	prop. n.
Manx	prop. n.
Ma"ny	n.
Ma"ny	a. & pron.
Ma"ny	n.
Ma"ny-mind`ed	a.
Ma"ny*plies	n.
Ma"ny-sid`ed	a.
ma"ny*ways`	adv.
man`za*nil"la	n.
man`za*ni"ta	n.
Mao	prop. n.
Maoism	prop. n.
Maoist	prop. n.
Ma"o*ri	prop. n.
maori hen	n.
Mao Tsetung	prop. n.
Map	n.
Map	v. t.
Ma*pach"	n.
mapinguari	n.
Ma"ple	n.
maple-leaf begonia	n.
maple-leaved bayur	n.
maple family	n.
Map"like`	a.
map" mak*er	n.
map"mak*ing	n.
map"per*y	n.
map"ping	n.
Ma"qui	n.
Maquis	prop. n.
Mar	n.
Mar	v. t.
Mar	n.
Ma"ra	n.
Ma"ra	n.
Ma"ra	n.
Mar`a*bou"	n.
Marabout"	n.
Mar"a*can	n.
Ma*rai"	n.
Mar`a*nath"a	n.
marang tree	n.
Ma*ran"ta	prop. n.
Marantaceae	prop. n.
marasca	n.
marasca cherry	n.
Ma`ra*schi"no	n.
ma`ra*schi"no cher"ry	n.
Marasmius	prop. n.
ma*ras"mus	n.
Ma*ra"thi	prop. n.
marathon	n.
Marattia	prop. n.
Marattiaceae	prop. n.
Marattiales	prop. n.
ma*raud"	v. i.
Ma*raud"	n.
Ma*raud`er	n.
Mar`a*ve"di	n.
maravilla	n.
Mar"ble	n.
Mar"ble	a.
Mar"ble	v. t.
Mar"bled	a.
marble cake	n.
Mar"ble-edged`	a.
Mar"ble*ize	v. t.
marbleizing	n.
Mar"bler	n.
marbles	n.
marblewood	n.
Mar"bling	n.
Mar"bly	a.
Mar*bri"nus	n.
Marc	n.
Marc	n.
Mar"can*tant	n.
Mar"ca*site	n.
Mar`ca*sit"ic	a.
Mar*cas"sin	n.
Mar*ca"to	a.
Mar"cel*ine	n.
Marcel Proust	n.
Mar*ces"cent	a.
Mar*ces"ci*ble	a.
March	n.
March	n.
March	v. i.
March	v. i.
March	v. t.
March	n.
marchand de vin	n.
Marchantia	prop. n.
Marchantiaceae	prop. n.
Marchantiales	prop. n.
march equinox	n.
March"er	n.
March"er	n.
Mar"chet	n.
March"ing	a. & n.
Mar"chion*ess	n.
March"-mad`	a.
March"man	n.
March"pane`	n.
March"-ward`	n.
Mar"cian	a.
Mar"cid	a.
Mar*cid"i*ty	n.
Mar"cion*ite	n.
Mar`co*brun"ner	n.
Mar*co"ni	prop. a.
Mar*co"ni*gram	n.
Mar*co"ni*graph	n.
marconi rig	n.
Mar*co"ni's law	prop. n.
Mar*co"nism	n.
Mar*co"ni system	n.
Mar"cor	n.
Mar*co"sian	n.
Mar"di` gras"	n.
Mare	n.
Mare	n.
Mare"chal Niel"	n.
mare liberum	n.
Ma*re"na	n.
mare nostrum	n.
Mare"schal	n.
mare's"-nest`	n.
Mare's"-tail`	n.
Mar"ga*rate	n.
Mar*gar"ic	a.
Mar"ga*rin	n.
Mar"ga*rine	n.
Mar`ga*ri*ta"ceous	a.
Mar"ga*rite	n.
Mar`ga*rit"ic	a.
Mar`ga*ri*tif"er*ous	a.
Mar*gar"o*dite	n.
Mar"ga*rone	n.
Mar"ga*rous	a.
Mar"ga*ry*ize	v. t.
Mar"gate fish"	n.
Marge	n.
Mar"gent	n.
Mar"gent	v. t.
Mar"gin	n.
Mar"gin	v. t.
margin account	n.
Mar"gin*al	a.
marginal cost	n.
Mar`gi*na"li*a	n. pl.
marginality	n.
Mar"gin*al*ly	adv.
Mar"gin*ate	a.
Mar"gin*ate	v. t.
Mar"gin*a`ted	a.
Mar"gined	a.
margin call	n.
Mar`gi*nel"la	prop. n.
Mar"gin*i*ci`dal	a.
Mar*go"sa	n.
Mar"gra*vate	n.
Mar"grave	n.
Mar"gra*vine	n.
Mar"gue*rite	n.
maria	n. pl.
Ma"ri*an	a.
Mar"ie	interj.
Mar"i*et	n.
Ma*rig"e*nous	a.
Mar"i*gold	n.
marijuana	n.
Mar`i*ki"na	n.
Ma*rim"ba	n.
Mar`i*mon"da	n.
Mar`i*nade"	n.
marinara	n.
marinara	a.
Mar"i*nate	v. t.
Ma*rine"	a.
Ma*rine"	n.
Ma*rined"	a.
ma*rine" mine`	n.
Mar"i*ner	n.
Mar"i*ner*ship	n.
Ma*ri"nism	n.
Mar`i*no*ra"ma	n.
Ma`ri*ol"a*ter	n.
Ma`ri*ol"a*try	n.
Mar`i*o*nette"	n.
Ma`ri*otte's law`	n.
Mar"ish	n.
Mar"ish	a.
Mar"i*tal	a.
Mar"i*ta`ted	a.
Ma*rit"i*mal	a.
Mar"i*time	a.
Maritime provinces	prop. n.
Mar"jo*ram	n.
Mark	n.
Mark	n.
Mark	n.
Mark	v. t.
Mark	v. i.
Mark"a*ble	a.
Marked	a.
Mar*kee"	n.
Mark"er	n.
Mar"ket	n.
Mar"ket	v. i.
Mar"ket	v. t.
Mar"ket*a*ble	a.
Mar"ket*a*ble*ness	n.
Mar"ket*er	n.
marketplace	n.
Mar"ket*ing	n.
Mar"ket*stead	n.
Mark"hoor`	n.
Mark"ing	n.
Mar"kis	n.
Mar"kis*esse	n.
Mark"man	n.
Mark"ov chain	n.
Mark"ov pro`cess	n.
Marks"man	n.
Marks"man*ship	n.
markup	n.
markweed	n.
Marl	v. t.
Marl	n.
Marl	v. t.
Mar*la"ceous	a.
Mar"lin	n.
Mar"line	n.
Mar"line	v. t.
Marl"ite	n.
Mar*lit"ic	a.
Marl"pit`	n.
Marl"stone`	n.
Marl"y	a.
Mar"ma*lade	n.
Mar"ma*let`	n.
Mar"ma*tite	n.
Mar"mo*lite	n.
Mar`mo*ra"ceous	a.
Mar"mo*rate	a.
Mar`mo*ra"tion	n.
Mar`mo*ra`tum o"pus	a.
Mar`mo*ro"sis	n.
Mar"mose`	n.
Mar"mo*set`	n.
mar"mot	n.
Mar"mottes oil`	n.
Maroc	prop. n.
Maroc	prop. a.
marocain	n.
Ma*rone"	n.
Mar"o*nite	n.
Ma*roon"	n.
Ma*roon"	v. t.
Ma*roon"	a.
Ma*roon"	n.
Mar"plot`	n.
Marque	n.
Mar*quee"	n.
Mar"quess	n.
mar"que*te*rie	n.
Mar"quis	n.
Mar"quis*ate	n.
Mar"quis*dom	n.
Mar`quise"	n.
Mar"quis*ship	n.
Mar"ram	n.
Mar"rer	n.
Mar"ri*a*ble	a.
Mar"riage	n.
Mar`riage*a*bil"i*ty	n.
Mar"riage*a*ble	a.
Mar"ried	a.
Mar"ri*er	n.
Mar*ron"	n.
Mar*roon"	n. & a.
Mar"rot	n.
Mar"row	n.
Mar"row	v. t.
Mar"row*bone`	n.
Mar"row*fat	n.
Mar"row*ish	a.
Mar"row*less	a.
Mar"row*y	a.
Mar*ru"bi*um	n.
Marruecos	prop. n.
Mar"ry	v. t.
Mar"ry	v. i.
Mar"ry	interj.
Mars	prop. n.
Mar*sa"la	n.
Mars*de"ni*a	prop. n.
Mar`sei`llais"	a. m.
Mar`sei`llais"	n. m.
Mar*seilles"	n.
Marsh	n.
Mar"shal	n.
Mar"shal	v. t.
Mar"shal*er	n.
Mar"shal*ing	n.
Mar"shal*sea	n.
Mar"shal*ship	n.
Marsh"bank`er	n.
marsh"i*ness	n.
marsh mar"i*gold	a.
Marsileaceae	prop. n.
Mar"si*po*branch`	n.
Mar"si*po*bran"chi*a	n. pl.
Mar*su"pi*al	a.
mar*su"pi*al	n.
Mar*su`pi*a"li*a	prop. n. pl.
mar*su`pi*a"li*an	n.
mar*su"pi*ate	a.
mar*su"pi*on	n.
mar"su*pite	n.
mar*su"pi*um	n.
Mart	n.
Mart	v. t.
Mart	v. t.
Mart	n.
mar"ta*gon	n.
mar"tel	v. i.
mar`tel` de fer"	n.
Mar*tel"lo tow`er	n.
mar"ten	n.
mar"tern	n.
mar"-text`	n.
Martes	prop. n.
Mar"tial	a.
Mar"tial*ism	n.
Mar"tial*ist	n.
Mar"tial*ize	v. t.
Mar"tial*ly	adv.
Mar"tial*ness	n.
Mar"tian	prop. a.
Mar"tian	prop. n.
Mar"tin	n.
Mar"tin	n.
Mar"ti*net`	n.
Mar"ti*net`	n.
Mar`ti*ne"ta	n.
Mar"ti*net`ism	n.
Mar"tin*gale	n.
Mar"tin*mas	n.
Mar"tite	n.
Mar"tle*mas	n.
Mart"let	n.
Martyniaceae	prop. n.
Mar"tyr	n.
Mar"tyr	v. t.
Mar"tyr*dom	n.
Mar`tyr*i*za"tion	n.
Mar"tyr*ize	v. t.
Mar"tyr*ly	adv.
Mar"tyr*o*loge	n.
Mar`tyr*o*log"ic	a.
Mar`tyr*ol"o*gist	n.
Mar`tyr*ol"o*gy	n.
Mar"tyr*ship	n.
Mar"vel	n.
marvel of Peru	n.
Mar"vel	v. i.
Mar"vel	v. t.
marvellous	adj.
Mar"vel*ous	a.
Mar"vel*ous*ly	adv.
Mar"vel*ous*ness	n.
Mar"ver	n.
Marx"ism	prop. n.
Marx"ism-Len"in*ism	prop. n.
Marx"ist	prop. n.
Marx"ist	prop. a.
Marxist-Leninist	adj.
Mar"y	n.
Ma"ry	interj.
Ma"ry-bud`	n.
Ma`ry*ol"a*try	n.
Ma"ry*sole	n.
mar"zi*pan`	n.
Masai	prop. n.
Mas*ca"gnin	n.
mascara	n.
Mas"cle	n.
Mas"cled	a.
Mas"cot	n.
Mas"cu*late	v. t.
mas"cu*line	a.
Mas`cu*lin"i*ty	n.
Mase	n. & v.
Mas"e*lyn	n.
mase	v. i.
ma"ser	n.
MASH	n.
Mash	n.
Mash	n.
Mash	v. t.
mashed potato	n.
mashed potatoes	n. pl.
Mash"er	n.
Mash"ie	n.
Mash"lin	n.
Mash"y	a.
masjid	n.
Mask	n.
Mask	v. t.
Mask	v. i.
Masked	a.
Mask"er	n.
Mask"er	v. t.
Mask"er*y	n.
Mas"ki*nonge	n.
Mask" shell`	n.
Mas"lin	n.
Mas"lin	a.
Ma"son	n.
Ma"son	v. t.
Ma*son"ic	prop. a.
Masonite	prop. n.
Ma"son*ry	n.
Ma*soo"la boat`	n.
Mas"o*ret	n.
Mas`o*ret"ic	a.
Mas"o*rite	n.
Masque	n.
Mas`quer*ade"	n.
Mas`quer*ade"	v. i.
Mas`quer*ade"	v. t.
Mas`quer*ad"er	n.
Mass	n.
Mass	v. i.
Mass	n.
Mass	v. t.
Mas"sa*cre	n.
Mas"sa*cre	v. t.
Mas"sa*crer	n.
Mas"sage	n.
Mas"sage	v. t.
Mas"sag*ist	n.
Mas`sa*sau"ga	n.
Mass<eacute/	n.
Mass"er	n.
Mas"se*ter	n.
Mas`se*ter"ic	a.
Mas"se*ter`ine	a.
Mas`seur"	n.
Mas`seuse"	n.
mas"si*cot	n.
massif	n.
mass"i*ness	n.
mass"ive	a.
Mass"ive*ly	adv.
Mass"ive*ness	n.
Mas*soo"la boat`	n.
Mas"so*ret	n.
mass-produce	v. t.
mass-produced	adj.
mass spectrometer	n.
mass-spectrometric	adj.
mass spectrometry	n.
Mass"y	a.
Mast	n.
Mast	n.
Mast	v. t.
Mas"ta*ba	n.
Mas"tax	n.
Mast"ed	a.
Mast"er	n.
Mas"ter	n.
Mas"ter	v. t.
Mas"ter	v. i.
master-at-arms	n.
Mas"ter*dom	n.
mastered	adj.
Mas"ter*ful	a.
Mas"ter*ful*ly	adv.
Mas"ter*hood	n.
Mas"ter*less	a.
Mas"ter*li*ness	n.
Mas"ter*ly	a.
Mas"ter*ly	adv.
Mas"ter*ous	a.
Mas"ter*piece`	n.
Mas"ter*ship	n.
Mas"ter*sing`er	n.
Mas"ter vi"bra*tor	n.
Mas"ter*y	n.
Mast"ful	a.
Mast"head`	n.
Mast"head"	v. t.
Mast"house`	n.
Mas"tic	n.
Mas"ti*ca*ble	a.
Mas`ti*ca"dor	n.
Mas"ti*cate	v. t.
Mas"ti*ca`ter	n.
Mas`ti*ca"tion	n.
Mas"ti*ca`tor	n.
Mas"ti*ca*to*ry	a.
Mas"ti*ca*to*ry	n.
Mas"tich	n.
Mas"ti*cin	n.
Mas"ti*cot	n.
Mas"tiff	n.
Mas"ti*go*phor`a	prop. n.
mas"ti*go*pod	n.
Mas`ti*gop"o*da	prop. n. pl.
Mas"ti*gure	n.
Mast"ing	n.
Mas*ti"tis	n.
Mast"less	a.
Mast"less	a.
Mast"lin	n.
Mas"to*don	n.
Mas`to*don*sau"rus	n.
Mas`to*don"tic	a.
Mas`to*dyn"i*a	n.
Mas"toid	a.
Mas*toid"al	a.
Mas`toid*i*tis	n.
Mas*tol"o*gy	n.
Mastotermes	prop. n.
Mastotermitidae	prop. n.
Mas"tress	n.
masturbate	v. i.
mas`tur*ba"tion	n.
Mast"y	a.
Ma*su"la boat`	n.
Mat	a.
Mat	n.
Mat	v. t.
Mat	v. i.
Mat`a*be"le	prop. n. pl.
Ma`ta*chin"	n.
Mat"a*co	n.
Mat"a*dor	n.
Mat`a*gasse"	n.
Ma`ta*jue"lo	n.
Ma`ta*jue"lo blan"co	n.
Ma*tan"za	n.
Match	n.
Match	n.
Match	v. t.
Match	v. i.
Match"a*ble	a.
matchboard	n.
matchbook	n.
match"box`	n.
match"bush`	n.
Match"-cloth`	n.
Match"-coat`	n.
Match"er	n.
Match game	n.
matching	adj.
Match"less	a.
Match"lock`	n.
Match"mak`er	n.
Match"mak`ing	n.
Match"mak`ing	a.
Match play	n.
Ma"te	n.
Mate	n.
Mate	a.
Mate	v. t.
Mate	n.
Mate	v. t.
Mate	v. i.
mated	adj.
Mate`las`s<eacute/"	a.
Mate`las`s<eacute/"	n.
Mate"less	a.
Mat"e*lote	n.
Ma`te*ol"o*gy	n.
Ma`te*o*tech"ny	n.
Ma"ter	n.
Ma*te"ri*al	a.
Ma*te"ri*al	n.
Ma*te"ri*al	v. t.
Ma*te"ri*al*ism	n.
Ma*te"ri*al*ist	n.
Ma*te`ri*al*is"tic	a.
Ma*te`ri*al"i*ty	n.
Ma*te`ri*al*i*za"tion	n.
Ma*te"ri*al*ize	v. t.
Ma*te"ri*al*ize	v. i.
Ma*te"ri*al*ly	adv.
Ma*te"ri*al*ness	n.
Ma*te"ri*a med"i*ca	n.
Ma*te"ri*ate	a.
Ma*te`ri*a"tion	n.
Ma`t<eacute/`ri`el"	n.
Ma*te"ri*ous	a.
Ma*ter"nal	a.
maternalistic	adj.
Ma*ter"nal*ly	adv.
Ma*ter"ni*ty	n.
ma*ter"ni*ty	a.
ma*ter"ni*ty ward`	n.
matey	adj.
Mat"fel*on	n.
Math	n.
Math`e*mat"ic	a.
Math`e*mat"ic*al	a.
Math`e*ma*ti"cian	n.
Math`e*mat"ics	n.
Math"er	n.
Math"es	n.
Ma*the"sis	n.
Math"u*rin	n.
Ma*ti"co	n.
Mat"ie	n.
M<acir/`tin"	n.
Mat"in	n.
mat"in	a.
mat"in*al	a.
mat`i*n<eacute/e"	n.
ma*trass"	n.
Mat"ress	n.
ma"tri*arch	n.
ma`tri*ar"chal	a.
Ma"tri*ar"chate	n.
matric	n.
Matricaria	prop. n.
Ma"trice	n.
matricentric	adj.
Mat"ri*ci`dal	a.
Mat"ri*cide	n.
Ma*tric"u*late	v. t.
Ma*tric"u*late	v. i.
Ma*tric"u*late	a.
Ma*tric`u*la"tion	n.
matrilineage	n.
matrilineal	adj.
Mat"ri*moine	n.
Mat`ri*mo"ni*al	a.
Mat`ri*mo"ni*al*ly	adv.
Mat`ri*mo"ni*ous	a.
Mat"ri*mo*ny	n.
matrisib	n.
ma"trix	n.
Ma"tron	n.
Mat"ron*age	n.
Mat"ron*al	a.
Ma"tron*hood	n.
Mat"ron*ize	v. t.
Ma"tron*like`	a.
Ma"tron*ly	a.
Mat`ro*nym"ic	n.
Ma*tross"	n.
Matt	n.
Mat`ta*ges"	n.
Mat"ta*more`	n.
Matte	n.
matte	a.
Mat"ted	a.
Mat"ted	a.
Mat"ter	n.
Mat"ter	v. i.
Mat"ter	v. t.
Matterhorn	prop. n.
Mat"ter*less	a.
Mat"ter-of-fact"	a.
Mat"ter*y	a.
Matteuccia	prop. n.
Matthew	prop. n.
Matthiola	prop. n.
Mat"ting	n.
Mat"ting	n.
Mat"tock	n.
Mat"toid	n.
Mat*toir"	n.
Mat`to*wac"ca	n.
Mat"tress	n.
Mat"u*rant	n.
Mat"u*rate	v. t.
Mat"u*rate	v. i.
Mat`u*ra"tion	n.
Mat"u*ra*tive	a.
Mat"u*ra*tive	n.
Ma*ture"	a.
Ma*ture"	v. t.
Ma*ture"	v. i.
matured	adj.
Ma*ture"ly	adv.
maturement	n.
Ma*ture"ness	n.
Ma*tur"er	n.
Mat`u*res"cent	a.
Ma*tur"ing	a.
Ma*tu"ri*ty	n.
Mat`u*ti"nal	a.
Ma*tu"ti*na*ry	a.
Mat"u*tine	a.
Mat"weed`	n.
Mat"y	n.
matz"o	n.
Mau*ca"co	n.
Maud	n.
Mau"dle	v. t.
Maud"lin	a.
Maud"lin	n.
Maud"lin*ism	n.
Maud"lin*wort`	n.
Mau"ger	prep.
Mau"gre	v. t.
Mau"kin	n.
Maul	n.
Maul	v. t.
Maule	n.
Maul"ing	n.
maul"stick`	n.
Mau"met	n.
Maunch	v. t.
Maunch	n.
Maund	n.
Maund	n.
Maund	v. i.
Maund"er	v. t.
Maund"er	n.
Maund"er*er	n.
Maun"dril	n.
Maun"dy	n.
Maundy coins	a.
Mau*resque"	a. & n.
Maur"ist	n.
Mauritius	prop. n.
Mau`so*le"an	a.
Mau`so*le"um	n.
Mau"ther	n.
Mauv`an"i*line	n.
Mauve	n.
mauve"<ium/ne	n.
Mauv"ine	a.
Mav"er*ick	n.
Mav"er*ick	v. t.
Maverick brand	n.
Ma*vour"nin	n.
Maw	n.
Maw	n.
Maw	n.
Mawk	n.
Maw"kin	n.
Mawk"ing*ly	adv.
Mawk"ish	a.
Mawk"ish*ly	adv.
Mawk"ish*ness	n.
Mawks	n.
Mawk"y	a.
Maw"met	n.
Maw"met*ry	n.
Maw"mish	a.
Maw"seed`	n.
Maw"worm`	n.
Max*il"la	n.
Max"il*lar	a.
Max*il"li*form	a.
Max*il"li*ped	n.
Max*il`lo-man*dib"u*lar	a.
Max*il`lo-pal"a*tine	a.
Max*il`lo*tur`bi*nal	a.
Max"im	n.
Max"im gun`	n.
maximisation	n.
Max`i*mi*za"tion	n.
Max"i*mize	v. t.
maximizing	adj.
Max"i*mum	n.
Max"i*mum	a.
maxwell	n.
May	v.
May	n.
May	n.
Ma"ya	n.
Ma"ya	prop. n.
Mayaca	prop. n.
Ma"yan	a.
Mayan arch	n.
May"be	adv.
May"be	a.
May"be	n.
May"bird`	n.
May"bloom`	n.
May"bush`	n.
May"duke`	n.
May"fish`	n.
May"flow`er	n.
May"hap	adv.
mayhaw	n.
may"hem	n.
May"ing	n.
May laws	n.
may"or	n.
May"or*al	n.
may"or*al	a.
May"or*al*ty	n.
May"or*ess	n.
May"or*ship	n.
May"pole`	n.
May"pop	n.
May"weed`	n.
Ma*za"ma	n.
Maz"ard	n.
Maz"ard	n.
Maz"ard	v. t.
Maz`a*rine"	a.
Maz`a*rine"	n.
Maz`a*rine"	n.
Maz"de*an	a.
Maz"de*ism	n.
Maze	n.
Maze	v. t.
Maze	v. i.
Maz"ed*ness	n.
Maze"ful	a.
Maz"er	n.
Ma"zi*ly	adv.
Ma"zi*ness	n.
Maz`o*log"ic*al	a.
Ma*zol"o*gist	n.
Ma*zol"o*gy	n.
Ma*zour"ka	n.
Ma"zy	a.
McCarthyism	prop. n.
McKinley	prop. n.
MDMA	n.
Me	pron.
Me	pers. pron.
Meach	v. i.
Mea"cock	n.
Mead	n.
Mead	n.
Mead"ow	n.
Mead"ow	a.
meadowgrass	n.
meadowlark	n.
Mead"ow*sweet`	n.
Mead"ow*y	a.
Mea"ger	a.
Mea"ger	v. t.
meagerly	adj.
Mea"ger*ly	adv.
Mea"ger*ness	n.
Mea"gre	n.
Meak	n.
Meak"ing	n.
Meal	n.
Meal	n.
Meal	n.
Meal	v. t.
Meal"ies	n. pl.
Meal"i*ness	n.
Meal"-mouthed`	a.
meals on wheels	n.
Meal"time`	n.
Meal"y	a.
meal"y*bug`	n.
Meal"y-mouthed`	a.
Mean	v. t.
Mean	v. i.
Mean	a.
Mean	a.
Mean	n.
Me*an"der	n.
Me*an"der	v. t.
Me*an"der	v. i.
Me*an"dri*an	a.
Me`an*dri"na	n.
Me*an"drous	a.
Mean"ing	n.
meaningful	adj.
meaningfulness	n.
meaningless	adj.
Mean"ly	adv.
Mean"ly	adv.
Mean"ness	n.
mean"spir`it*ed	a.
Meant	imp. & p. p.
Mean"time`	n.
Mean"time`	adv.
Mear	n.
Mease	n.
Mea"sel*ry	n.
Mea"sle	n.
Mea"sle	n.
Mea"sled	a.
Mea"sles	n.
Mea"sles	n.
mea"sly	a.
measurability	n.
Meas"ur*a*ble	a.
meas"ure	n.
Meas"ure	v. t.
Meas"ure	v. i.
Meas"ured	a.
Meas"ure*less	a.
Meas"ure*ment	n.
Meas"ur*er	n.
Meas"ur*ing	a.
Meat	n.
Meat	v. t.
Me*a"tal	a.
Meat"ed	a.
Meath	n.
Meat"i*ness	n.
Meat"less	a.
Me*at"o*scope	n.
Me*at"o*tome	n.
Me*a"tus	n. sing. & pl.
Meat"y	a.
Meaw	n.
Meaw	v. i.
Meawl	v. i.
Mea"zel	n.
Meaz"ling	a.
Me"bles	n. pl.
Me*ca"te	n.
Mec`ca*wee"	prop. a.
Me*chan"ic	n.
Me*chan"ic	a.
Me*chan"ic*al	a.
Me*chan"ic*al	n.
Me*chan"ic*al*ize	v. t.
Me*chan"ic*al*ly	adv.
Me*chan"ic*al*ness	n.
Mech`a*ni"cian	n.
Me*chan`i*co-chem"ic*al	a.
Me*chan"ics	n.
mechanisation	n.
Mech"an*ism	n.
mech"an*ism of ac"tion	n.
Mech"an*ist	n.
mechanization	n.
Mech"an*ize	v. t.
Mech"an*o*graph	n.
Mech`an*o*graph`ic	a.
Mech`an*og"ra*phist	n.
Mech`an*og"ra*phy	n.
Mech"an*ur`gy	n.
Mech"i*tar*ist	n.
Mech"lin	n.
Me*cho"a*can	n.
Meck*e"li*an	a.
Mec"o*nate	n.
Me*con"ic	a.
Me*con"i*dine	n.
Mec`o*nid"i*um	n.
Mec"o*nin	n.
Mec`o*nin"ic	a.
Me*co"ni*um	n.
Med"al	n.
Med"al	v. t.
Med"al*et	n.
Med"al*ist	n.
Me*dal"lic	a.
Me*dal"lion	n.
Med"al play`	n.
Med"dle`	v. i.
Med"dle	v. t.
Med"dler	n.
Med"dle*some	a.
Med"dling	a.
Med"dling*ly	adv.
Mede	prop. n.
Mede	n.
med"fly	n. sing. & pl.
Me"di*a	n.
Me"di*a*cy	n.
Me`di*ae"val	a.
Me`di*ae"val*ism	n.
Me`di*ae"val*ist	n.
Me`di*ae"val*ly	adv.
Me`di*ae"vals	n. pl.
Me"di*al	a.
Me"di*al	n.
Me"di*a*lu"na	n.
Me"di*an	a.
Me"di*an	n.
Me"di*ant	n.
Me`di*as*ti"nal	a.
Me`di*as"tine	n.
Me"di*ate	a.
Me"di*ate	v. i.
Me"di*ate	v. t.
Me"di*ate*ly	adv.
Me"di*ate*ness	n.
Me`di*a"tion	n.
Me"di*a*tive	a.
Me`di*at`i*za"tion	n.
Me"di*a*tize	v. t.
Me"di*a`tor	n.
Me`di*a*to"ri*al	a.
Me"di*a`tor*ship	n.
Me"di*a*to*ry	a.
Me`di*a"tress	n.
Med"ic	n.
Med"ic	n.
Med"ic	a.
Med"i*ca*ble	a.
medicaid	n.
Med"ic*al	a.
Med"ic*al*ly	adv.
Med"i*ca*ment	n.
Med`ica*men"tal	a.
Med"i*cas`ter	n.
Med"i*cate	v. t.
Med`i*ca"tion	a.
Med`i*ce"an	prop. a.
Me*dic"i*na*ble	a.
Me*dic"i*nal	a.
Me*dic"i*nal*ly	adv.
Med"i*cine	n.
Med"i*cine	v. t.
medick	n.
medico	n.
Med`i*co-le"gal	a.
Med`i*com"mis*sure	n.
Med`i*cor"nu	n.
Med"ics	n.
Me*di"e*ty	n.
Me`di*e"val	peop. n.
Me*di"no	n.
Me"di*o`cral	a.
me`di*o"cre	a.
Me"di*o`cre	n.
Me"di*o`crist	n.
Me`di*oc"ri*ty	n.
Me`di*o*sta*pe"di*al	a.
Me`di*ox"u*mous	a.
Med"i*tance	n.
Med"i*tate	v. i.
Med"i*tate	v. t.
Med`i*ta"tion	n.
Med"i*ta`tist	n.
Med"i*ta*tive	a.
Med`i*ter*ra"ne*an	a.
Med`i*ter*ra"ne*an fruit" fly	n.
Med`i*ter*ra"ne*ous	a.
Me"di*um	n.
Me"di*um	a.
Me"di*um-sized`	a.
Me"di*us	n.
Me*dji"di*e	n.
Med"lar	n.
Med"le	v. t.
Med"ley	n.
Med"ley	a.
Med"ly	v. t.
M<eacute/`doc"	n.
Med"re*gal	n.
Med"rick	n.
Me*dul"la	n.
Me*dul"lar	a.
Med"ul*la*ry	a.
Me*dul"la*ted	a.
Me*dul"lin	n.
Me*du"sa	n.
Me*du"si*an	n.
Me*du"si*form	a.
Me*du"soid	a.
Meech	v. i.
Meed	n.
Meed	v. t.
Meed"ful	a.
Meed"ful*ly	adv.
Meek	a.
Meek	v. t.
Meek"ly	adv.
Meek"ness	n.
Meer	a.
Meer	n.
Meer	n.
Meer"kat	n.
Meer"schaum	n.
Meet	v. t.
Meet	v. t.
Meet	n.
Meet	a.
Meet	adv.
Meet"en	v. t.
Meet"er	n.
Meeth	n.
Meet"ing	n.
Meet"ing*house`	n.
Meet"ly	adv.
Meet"ness	n.
Meg-	a.
Me*gac"e*ros	n.
Meg"a*chile	n.
Meg"a*cosm	n.
Meg`a*cou`lomb"	n.
Meg"a*derm	n.
Meg"a*dyne	n.
Meg"a*far`ad	n.
meg`a*kar"y*o*cyte	n.
megakaryocytic	adj.
Meg"a*lerg	n.
Meg`a*le"sian	a.
Meg`a*leth"o*scope	n.
Meg"a*lith	n.
megalithic	adj.
Meg"a*lo-	prop. n.
Meg`a*lo*ce*pha"li*a	n.
Meg"a*lo*cyte	n.
Meg`a*lo*ma"ni*a	n.
megalomaniacal	adj.
Megalonychidae	prop. n.
Meg`a*lon"yx	n.
Meg`a*loph"o*nous	a.
Meg`a*lop"o*lis	n.
Meg"a*lops	n.
meg`a*lop"sy*chy	n.
Meg"a*lo*saur`	n.
Me*gam"e*ter	n.
Meg"a*me`ter	n.
Meg`am`p<egrave/re"	n.
Meg"a*phone	n.
Me*gaph"y*ton	n.
Meg"a*pode	n.
Me*gap"o*lis	n.
Me*ga"ri*an	a.
Meg"a*scope	n.
Meg`a*scop"ic	a.
Meg"a*seme	a.
Me"gass"	n.
Meg"as*thene	n.
Meg`as*then"ic	a.
Meg"a*stome	n.
Meg"a*there	n.
Meg`a*the"roid	n.
Meg`a*volt"	n.
Meg`a*we"ber	n.
Meg"erg`	n.
Me*gilp"	n.
MEGO	n.
Meg"ohm"	n.
Me"grim	n.
Me"grim	n.
Mei*bo"mi*an	a.
Meine	v. t.
Mein"e	n.
Mei"o*cene	a.
Mei"o*nite	n.
Mei*o"sis	n.
Mei`o*stem"o*nous	a.
mei*ot"ic	a.
-meister	suff.
Meis"ter*sing`er	n.
Mekh"i*tar*ist	n.
Me*lac"o*nite	n.
Me*la"da	n.
Me*lae"na	n.
Mel"ain	n.
Me*lai"no*type	n.
Me"lam	n.
mel"a*mine	n.
melamine resin	n.
Mel"am*pode	n.
Melampsoraceae	prop. n.
Mel`am*py"rin	n.
Mel`a*nae"mi*a	n.
Me*lan"a*gogue	n.
Mel`an*cho"li*a	n.
Mel`an*cho"li*an	n.
Mel"an*chol`ic	a.
Mel"an*chol`ic	n.
Mel"an*chol`i*ly	adv.
Mel"an*chol`i*ness	n.
Mel`an*cho"li*ous	a.
Mel"an*chol*ist	n.
Mel"an*cho*lize	v. i.
Mel"an*cho*lize	v. t.
Mel"an*chol*y	n.
Mel"an*chol*y	a.
Mel`an*co`ni*a"ce*ae	n. pl.
Mel`an*co`ni*a"les	n. pl.
Mel`a*ne"sian	prop. a.
M<eacute/`lange"	n.
Me*la"ni*an	n.
Me*lan"ic	a.
Me*lan"i*line	n.
Mel"a*nin	n.
Mel"a*nism	n.
Mel"a*nism	n.
Mel`a*nis"tic	a.
Mel"a*nite	n.
Mel`a*noch"ro*i	n. pl.
Mel`a*no*chro"ic	a.
Mel`a*no*chro"ite	n.
Mel`a*noc"o*mous	a.
Mel`a*no"ma	n.
Mel`a*nor*rhoe"a	n.
Me*lan"o*scope	n.
Mel`a*no"sis	n.
Mel`a*not"ic	a.
Me*lan"o*type	n.
Me*lan"ter*ite	n.
Mel"a*nure	n.
Mel`a*nu"ric	a.
Mel"a*phyre	n.
Me*las"ma	n.
Me*las"ses	n.
Me*las"sic	a.
Me*las"to*ma	n.
Mel`a*sto*ma"ceous	a.
mel`a*tonin	n.
Mel"chite	n.
Meld	v. t. & i.
meld	n.
Meleagrididae	prop. n.
Mel`e*a"grine	a.
Mel`e*a"gris	prop. n.
M<ecir/`l<eacute/e"	n.
Me*le"na	n.
Mel"ene	n.
Mel"e*nite	n.
Mel"e*tin	n.
Me*lez"i*tose`	n.
Me`li*a"ceous	a.
Mel`i*be"an	a.
Mel"ic	a.
Mel"ic grass`	n.
Me*lic"ra*to*ry	n.
Mel"i*lite	n.
Mel"i*lot	n.
Mel`i*lot"ic	a.
Melinae	n.
M<eacute/"lin*ite	n.
Mel"io*rate	v. t.
Mel"io*rate	v. i.
Mel"io*ra`ter	n.
Mel`io*ra"tion	n.
Mel"io*ra`tor	n.
Mel"io*rism	n.
Mel*ior"i*ty	n.
Me*liph"a*gan	a.
Me*liph"a*gan	n.
Me*liph"a*gous	a.
Me*lis"ma	n.
Me*lis"sa	n.
Me*lis"sic	a.
Me*lis"syl	n.
Me*lis"sy*lene	n.
Mel"i*tose`	n.
Mell	v. i. & t.
Mell	n.
Mell	n.
Mel"late	n.
Mel"lay	n.
Mel"lic	a.
Mel*lif"er*ous	a.
Mel*lif"ic	a.
Mel`li*fi*ca"tion	n.
Mel*lif"lu*ence	n.
Mel*lif"lu*ent	a.
Mel*lif"lu*ent*ly	adv.
Mel*lif"lu*ous	a.
Mel*lig"e*nous	a.
Mel*li"go	n.
Mel*lil"o*quent	a.
Mel*liph"a*gan	n.
Mel*liph"a*gous	a.
Mel"li*tate	n.
Mel"lite	n.
Mel*lit"ic	a.
Mel"lone	n.
Mel"lon*ide	n.
Mel"low	a.
Mel"low	v. t.
Mel"low	v. i.
mellowed	adj.
mellowing	adj.
mellowing	n.
Mel"low*ly	adv.
Mel"low*ness	n.
Mel"low*y	a.
Mel*lu"co	n.
Mel"ne	n.
Mel`o*co*ton"	n.
Me*lo"de*on	n.
Me*lod"ic	a.
Me*lod"ics	n.
Me*lo"di*o*graph	n.
Me*lo"di*ous	a.
Mel"o*dist	n.
Mel"o*dize	v. t.
Mel"o*dize	v. i.
Mel`o*dra"ma	n.
Mel`o*dra*mat"ic	a.
Mel`o*dram"a*tist	n.
Mel"o*drame	n.
Mel"o*dy	n.
Mel"o*e	n.
meloid	n.
Meloidae	prop. n.
Melolonthidae	prop. n.
Mel`o*lon*thid"i*an	n.
Mel"on	n.
Mel`o*pi*a"no	n.
Mel`o*plas"tic	a.
Mel"o*plas`ty	n.
Mel`o*p<oe/"ia	n.
melosa	n.
Melospiza	prop. n.
Mel"o*type	n.
Mel*pom"e*ne	n.
Mel"rose	n.
Melt	n.
Melt	v. t.
Melt	v. i.
Melt"a*ble	a.
Melt"er	n.
Melt"ing	n.
Melt"ing	a.
Melt"ing pot	n.
Mel"ton	n.
Me*lun"geon	n.
Melursus	prop. n.
Melville	prop. n.
mem	n.
Mem"ber	v. t.
Mem"ber	n.
Mem"bered	a.
Mem"ber*ship	n.
Mem"bral	a.
Mem`bra*na"ceous	a.
Mem"brane	n.
Mem*bra"ne*ous	a.
Mem`bra*nif"er*ous	a.
Mem*bra"ni*form	a.
Mem`bra*nol"o*gy	n.
Mem"bra*nous	a.
Me*men"to	n.
Me*men"to mo"ri	n.
Mem"non	n.
Mem"oir	n.
Mem"oir*ist	n.
mem`o*ra*bil"i*a	n. pl.
Mem`o*ra*bil"i*ty	n.
Mem"o*ra*ble	a.
Mem`o*ran"dum	n.
Mem"o*rate	v. t.
Mem"o*ra*tive	a.
Me*mo"ri*a	n.
Me*mo"ri*al	a.
Me*mo"ri*al	n.
Me*mo"ri*al Day	v. t.
Me*mo"ri*al*ist	n.
Me*mo"ri*al*ize	v. t.
Me*mo"ri*al*i`zer	n.
Memorial rose	n.
Me*mor"i*ter	adv.
Mem"o*rize	v. t.
memorizer	n.
Mem"o*ry	n.
Mem"phi*an	prop. a.
Mem"phi*an	prop. n.
mem"sa`hib	n.
Men	n.
Men	pron.
Me*nac"can*ite	n.
Men"ace	n.
Men"ace	v. t.
Men"ace	v. i.
Men"a*cer	n.
Men"a*cing*ly	adv.
m<eacute/`nage"	n.
m<eacute/`nage"	n.
m<eacute/`nage <agrave/` trois"	n.
Men*ag"er*ie	n.
Men"a*gogue	n.
Me*na"ion	n.
Men"ald	a.
Mend	v. t.
Mend	v. i.
Mend"a*ble	a.
Men*da"cious	a.
Men*dac"i*ty	n.
Mendel	prop. n.
men*de*le"vi*um	a.
Men*de"li*an	prop. a.
Mendelian character	n.
Men"di*ant	n.
Men"di*can*cy	n.
Men"di*cant	a.
Men"di*cant	n.
Men"di*cate	v. t. & i.
Men`di*ca"tion	n.
Men*dic"i*ty	n.
Men"di*nant	n.
Mend"ment	n.
Men"dole	n.
Men"dre*gal	n.
Mends	n.
Menge	v. i.
men*ha"den	n.
Men"hir	n.
Men"ial	a.
Men"ial	n.
M<eacute/`ni<egrave/re's" dis*ease"	n.
me*nin"ge*al	a.
Me*nin"ges	n. pl.
Men`in*gi"tis	n.
Me*nis"cal	a.
Me*nis"coid	a.
Me*nis"cus	n.
Men`i*sper*ma"ceous	a.
Men`i*sper"mic	a.
Men`i*sper"mine	n.
Men"i*ver	n.
Men"non*ist	n.
men"o*branch	n.
Men`o*lo"gi*um	n.
Men"o*pause	n.
Men`o*po"ma	n.
Men`or*rha"gi*a	n.
Me*nos"ta*sis	n.
Men`os*ta"tion	n.
Men"ow	n.
Men"-pleas`er	n.
Men"sal	a.
Men"sal	a.
Mense	n.
Mense	v. t.
Men"ses	n. pl.
Men"stru*al	a.
Men"stru*ant	a.
Men"stru*ate	a.
Men"stru*ate	v. i.
menstruating	adj.
Men`stru*a"tion	n.
Men"strue	n.
Men"stru*ous	a.
Men"stru*um	n.
Men`su*ra*bil"i*ty	n.
Men"su*ra*ble	a.
Men"su*ra*ble*ness	n.
Men"su*ral	a.
Men"su*rate	v. t.
Men`su*ra"tion	n.
-ment	p. p.
Men"ta*gra	n.
Men"tal	a.
Men"tal	n.
Men"tal	a.
mentalism	n.
men`tal*is"tic	a.
Men*tal"i*ty	n.
Men"tal*ly	adv.
men*ta"tion	n.
Men"tha	n.
Men"thene	n.
men"thol	n.
Men"thyl	n.
Menticirrhus	prop. n.
Men`ti*cul"tur*al	a.
Men"tion	n.
Men"tion	v. t.
Men"tion*a*ble	a.
Men`to*meck*e"li*an	a.
Men"tor	n.
Men*to"ri*al	a.
men"tum	n.
Mentzelia	prop. n.
men"u	n.
Menurae	prop. n.
Menuridae	prop. n.
Me"nuse	v. i.
Menyanthes	prop. n.
Menziesia	prop. n.
Me*ow"	v. i. & n.
mepacrine	n.
meperidine	n.
Meph`is*to*phe"le*an	prop. a.
Meph*is*toph"e*les	a.
Mephitinae	prop. n.
Me*phi"tis	n.
Meph"i*tism	n.
Me*ra"cious	a.
Mer"ca*ble	a.
merbromine	n.
Mer"can*tile	a.
Mer*cap"tal	n.
Mer*cap"tan	n.
Mer*cap"tide	n.
Mer"cat	n.
Mer`ca*tan"te	n.
Mer*ca"tor's chart"	n.
Merce	v. t.
Mer`ce*na"ri*a	n.
Mer`ce*na"ri*an	n.
Mer"ce*na`ri*ly	adv.
Mer"ce*na*ri*ness	n.
Mer"ce*na*ry	a.
Mer"ce*na*ry	n.
Mer"cer	n.
Mer"cer*ize	v. t.
Mer"cer*ship	n.
Mer"cer*y	n.
Mer"chand	v. i.
Mer"chan*di`sa*ble	a.
Mer"chan*dise	n.
Mer"chan*dise	v. i.
Mer"chan*dise	v. t.
Mer"chan*di`ser	n.
mer"chan*dis`ing	n.
Mer"chand*ry	n.
Mer"chant	n.
Mer"chant	a.
Mer"chant	v. i.
Mer"chant*a*ble	a.
Mer"chant*ly	a.
Mer"chant*man	n.
mer"chant ma*rine"	n.
mer"chant*ry	n.
Mer"ci*a*ble	a.
Mer"ci*ful	a.
Mer"ci*fy	v. t.
Mer"ci*less	a.
Mer`cur*am*mo"ni*um	n.
Mer*cu"ri*al	a.
Mer*cu"ri*al	n.
mer*cu"ri*al*ism	n.
Mer*cu"ri*al*ist	n.
Mer*cu"ri*al*ize	v. t.
Mer*cu"ri*al*ize	v. i.
Mer*cu"ri*al*ly	adv.
Mer*cu"ric	a.
Mer*cu`ri*fi*ca"tion	n.
Mer*cu"ri*fy	v. t.
Mer"cu*rism	n.
Mer*cu"rous	a.
Mer"cu*ry	n.
Mer"cu*ry	v. t.
mercury bichloride	n.
mer"cu*ry ful"mi*nate	n.
Mer"cy	n.
Merd	n.
-mere	n.
Mere	n.
Mere	v. t.
Mere	n.
Mere	a.
Mere"ly	adv.
Me*ren"chy*ma	n.
Meres"man	n.
Mere"stead	n.
Mere"stone`	n.
Mer`e*tri"cious	a.
mer`e*tri"cious*ness	n.
Mer*gan"ser	n.
merge	v. t.
Merge	v. i.
merged	adj.
Mer"ger	n.
merging	adj.
merging	n.
Mergus	prop. n.
Mer"i*carp	n.
Mer"ide	n.
Me*rid"i*an	a.
Me*rid"i*an	n.
Me*rid"i*o*nal	a.
Me*rid`i*o*nal"i*ty	n.
Me*rid"i*o*nal*ly	adv.
Mer"ils	n.
Me`ringue"	n.
Me*ri"no	a.
Me*ri"no	n.
Mer`is*mat"ic	a.
Mer"i*stem	n.
Mer"it	n.
Mer"it	v. t.
Mer"it	v. i.
Mer"it*a*ble	a.
Mer"it*ed*ly	adv.
Mer"i*thal	n.
Mer"it*mon`ger	n.
meritocracy	n.
meritocratic	adj.
Mer`i*to"ri*ous	a.
Mer"i*to*ry	a.
Mer"i*tot	n.
Merk	n.
Merk	n.
Merke	a.
mer"kin	n.
Merl	n.
Mer"lin	n.
Mer"ling	n.
Mer"lon	n.
Mer"luce	n.
Mer"maid	n.
Mer"man	n.
Me"ro	n.
Mer"o*blast	n.
Mer`o*blas"tic	a.
Me"ro*cele	n.
Mer`o*is"tic	a.
Me*rop"i*dan	n.
Me*rop"o*dite	n.
Mer*or`gan*i*za"tion	n.
Me"ros	n.
Me"ros	n.
Mer"o*some	n.
Mer`o*stom"a*ta	prop. n. pl.
M<eacute/`rou"	n.
Mer`o*vin"gi*an	a.
Mer`o*zo"ite	n.
Mer"ri*ly	adv.
Mer"ri*make`	n.
Mer"ri*make`	v. i.
Mer"ri*ment	n.
Mer"ri*ness	n.
Mer"ry	a.
Mer"ry	n.
Mer"ry-an"drew	n.
Mer"ry-go`-round"	n.
Mer"ry*make`	n.
Mer"ry*make`	v. i.
Mer"ry*mak`er	n.
Mer"ry*mak`ing	a.
Mer"ry*mak`ing	n.
Mer"ry*meet`ing	n.
Mer"ry*thought`	n.
Mer"sion	n.
Me*ru"li*dan	n.
Me"rus	n.
Mer"vaille`	n.
Mes-	n.
Mes*ac"o*nate	n.
Mes`a*con"ic	a.
mes"ad	adv.
mes"al	a.
M<eacute/`sal`li`ance"	n.
mes"al*ly	adv.
Mes`a*m<oe/"boid	n.
Mes`a*ra"ic	a.
Mes`a*ti*ce*phal"ic	a.
Mes`a*ti*ceph"a*lous	a.
Mes*cal"	n.
Mes`dames"	n.
Me*seems"	v. impers.
Me"sel	n.
Me"sel*ry	n.
Me*sem`bry*an"the*mum	n.
Mes`en*ce*phal"ic	a.
Mes`en*ceph"a*lon	n.
Mes*en"chy*ma	n.
Mes`en*ter"ic	a.
Mes*en"te*ron	n.
Mes"en*ter*y	n.
Mes`e*ra"ic	a.
Mes*eth"moid	a.
Mesh	n.
Mesh	v. t.
Mesh	v. i.
Meshed	a.
Mesh"y	a.
Mes"i*ad	adv.
Me"sial	a.
Me"sial*ly	adv.
Mes"i*tyl	n.
Me*sit"y*le*nate	n.
Me*sit"y*lene	n.
Me*sit"y*lol	n.
Mes"lin	n.
Mes`mer*ee"	n.
Mes*mer"ic	a.
Mes"mer*ism	n.
Mes"mer*ist	n.
Mes`mer*i*za"tion	n.
Mes"mer*ize	v. t.
Mes"mer*i`zer	n.
Mesne	a.
Mes"o-	n.
Mes"o*blast	n.
Mes`o*blas"tic	a.
Mes`o*bran"chi*al	a.
Mes`o*bron"chi*um	n.
Mes`o*cae"cum	n.
Mes"o*carp	n.
Mes`o*ce*phal"ic	a.
Mes`o*ceph"a*lon	n.
Mes`o*ceph"a*lous	a.
Mes`o*coe"le	n.
Mes`o*co"lon	n.
Mes`o*cor"a*coid	n.
Mes`o*cu*ne"i*form	n.
Mes"o*derm	n.
Mes`o*der"mal	a.
Mes`o*der"mic	a.
Mes"o*dont	a.
Mes`o*gas"ter	n.
Mes`o*gas"tric	a.
Mes`o*gas"tri*um	n.
Mes`o*gl<oe/"a	n.
Me*sog"na*thous	a.
Mes`o*he"par	n.
Mes`o*hip"pus	n.
Mes"o*labe	n.
Mes"ole	n.
Mes"o*lite	n.
Mes`o*log"a*rithm	n.
Mes`o*me"tri*um	n.
Mes`o*my*ce"tes	n. pl.
Mes`o*my*o"di*an	n.
Mes`o*my"o*dous	a.
Mes"on	n.
me*son"ic	a.
Mes`o*na"sal	a.
Mes`o*neph"ric	a.
Mes`o*neph"ros	n.
Mes`o*no"tum	n.
Mes`o*phl<oe/"um	n.
Me*soph"ry*on	n.
Mes`o*phyl"lum	n.
Mes"o*plast	n.
Mes`o*po"di*al	a.
Mes`o*po`di*a"le	n.
Mes`o*po"di*um	n.
Me*sop`te*ryg"i*um	n.
Me*sor"chi*um	n.
Mes`o*rec"tum	n.
Mes"o*rhine	a.
Mes`o*sau"ri*a	n.
Mes`o*scap"u*la	n.
Mes`o*scap"u*lar	a.
Mes`o*scu"tum	n.
Mes"o*seme	a.
Mes`o*sid"er*ite	n.
Mes"o*sperm	n.
Mes"o*state	n.
Mes`o*ster"nal	a.
Mes`o*ster"num	n.
mes`o*tar*tar"ic	a.
Mes`o*the"ca	n.
Mes`o*the"li*um	n.
Mes`o*tho*rac"ic	a.
Mes`o*tho"rax	n.
Mes`o*tho"ri*um	n.
Mes"o*tro`chal	a.
Mes"o*type	n.
Mes`o*va"ri*um	n.
Mes*ox"a*late	n.
Mes`ox*al"ic	a.
Mes`o*zo"a	n. pl.
Mes`o*zo"ic	a.
Mes`o*zo"ic	n.
Mes*prise"	n.
Mes*qui"te	n.
Mes*qui"te bean	n.
Mess	n.
Mess	v. i.
Mess	v. t.
Mes"sage	n.
Mes"sage	v. t.
Mes"sage	n.
Mes"sa*ger	n.
Mes"sage stick	n.
Mes"set	n.
Mes*si"ad	n.
Mes*si"ah	n.
Mes*si"ah*ship	n.
Mes`si*an"ic	a.
Mes*si"as	n.
Mes`si`dor"	n.
Mes"sieurs	n. pl.
Mes`si*nese"	a.
Mess"mate`	n.
Mes"suage	n.
mess up	v. t.
mess-up	n.
Mest	a.
Mes*tee"	n.
Mes"ter	n.
Mes*ti"no	n.
Mes*ti"zo	n.
Mest"ling	n.
Me*sym"ni*cum	n.
Met	imp. & p. p.
Met	imp. & p. p.
Met	p. p.
Met"a-	n.
Me*tab"o*la	n.
Me*tab"o*la	n. pl.
Met`a*bo"li*an	n.
Met`a*bol"ic	a.
Met`a*bol"i*sis	n.
Me*tab"o*lism	n.
Me*tab"o*lite	n.
Me*tab"o*lize	v. t. & i.
Met`a*bran"chi*al	a.
Met`a*car"pal	a.
Met`a*car"pus	n.
Met`a*cen"ter	n.
Me*tac"e*tone	n.
Met`a*chlo"ral	n.
Me*tach"ro*nism	n.
Met`a*chro"sis	n.
Met`a*cin"na*bar*ite	n.
Met"a*cism	n.
Met`a*cro"le*in	n.
Met`a*cro"mi*on	n.
Met`a*dis*coid"al	a.
Met`a*gas"tric	a.
Met"age	n.
Met`a*gen"e*sis	n.
Met`a*ge*net"ic	a.
Met`a*gen"ic	a.
Me*tag"na*thous	a.
Met`a*gram"ma*tism	n.
Met`a*graph"ic	a.
Me*tag"ra*phy	n.
Met"al	n.
Met"al	v. t.
Met`al*am*mo"ni*um	n.
metalanguage	n.
Met`al*bu"min	n.
Me*tal"de*hyde	n.
Met`a*lep"sis	n.
Met"a*lep`sy	n.
Met`a*lep"tic	a.
Met`a*lep"tic*al	a.
Me*tal"lic	a.
Me*tal"lic*al	a.
Me*tal"lic*ly	adv.
Me*tal`li*fac"ture	n.
Met`al*lif"er*ous	a.
Me*tal"li*form	a.
Met"al*line	a.
Met"al*line	n.
Met"al*list	n.
Met`al*li*za"tion	n.
Met"al*lize	v. t.
Me*tal"lo*chrome	n.
Me*tal"lo*chro`my	n.
Me*tal"lo*graph	n.
Me*tal`lo*graph"ic	a.
Met`al*log"ra*phist	n.
Met`al*log"ra*phy	n.
Met"al*loid	n.
Met"al*loid	a.
Met`al*loid"al	a.
Me*tal"lo*phone	n.
Met`al*lor*gan"ic	a.
Me*tal`lo*ther"a*py	n.
Met`al*lur"gic	a.
Met"al*lur`gist	n.
Met"al*lur`gy	n.
Met"al*man	n.
Met`a*log"ic*al	a.
met`al*or*gan"ic	a.
Met"a*mer	n.
Met"a*mere	n.
Met`a*mer"ic	a.
Met`a*mer"ic*al*ly	adv.
Me*tam"er*ism	n.
Met`a*mor"phic	a.
Met`a*mor"phism	n.
Met`a*mor"phist	n.
Met`a*mor"phize	v. t.
Met`a*mor"phose	v. t.
Met`a*mor"phose	n.
Met`a*mor"pho*ser	n.
Met`a*mor"pho*sic	a.
Met`a*mor"pho*sis	n.
Met`a*nau"pli*us	n.
Met`a*ne*phrit"ic	a.
Met`a*neph"ros	n.
Met`a*no"tum	n.
Met`an*ti*mo"nate	n.
Met`an*ti*mon"ic	a.
Met`a*pec"tic	a.
Met`a*pec"tin	n.
Met`a*pep"tone	n.
met"a*phor`	n.
Met`a*phor"ic	a.
Met"a*phor*ist	n.
Met`a*phos"phate	n.
met`a*phos*phor"ic	a.
Met"a*phrase	n.
met"a*phrased	a.
Me*taph"ra*sis	n.
Met"a*phrast	n.
Met`a*phras"tic	a.
Met`a*phys"ic	n.
Met`a*phys"ic	a.
Met`a*phys"ic*al	a.
Met`a*phys"ic*al*ly	adv.
Met`a*phy*si"cian	n.
Met`a*phys"ics	n.
Me*taph"y*sis	n.
Met"a*plasm	n.
Met"a*plast	n.
Met"a*pode	n.
Met`a*po"di*al	a.
Met`a*po`di*a"le	n.
Met`a*po"di*um	n.
Met`a*poph"y*sis	n.
Me*tap`te*ryg"i*um	n.
Met`a*sil"i*cate	n.
Met`a*si*lic"ic	a.
Met`a*so"ma*tism	n.
Met"a*some	n.
Met`a*stan"nate	n.
Met`a*stan"nic	a.
Me*tas"ta*sis	n.
metastasize	v.
Met`a*stat"ic	a.
Met`a*ster"nal	a.
Met`a*ster"num	n.
Me*tas"to*ma	n.
Met`a*tar"sal	a.
Met"a*tarse	n.
Met`a*tar"sus	n.
me*ta"te	n.
Metatheria	prop. n.
metatherian	n.
Me*tath"e*sis	n.
Met`a*thet"ic	a.
Met`a*tho*rac"ic	a.
Met`a*tho"rax	n.
Met`a*ti*tan"ic	a.
Met`a*tung"state	n.
Met`a*tung"stic	a.
Met`a*van"a*date	n.
Met`a*va*nad"ic	a.
Met`a*xy"lene	n.
M<eacute/`ta`yage"	n.
M<eacute/`ta`yer"	n.
Met`a*zo"a	n. pl.
Met`a*zo"an	n.
Met`a*zo"ic	a.
Met`a*zo"on	n.
Mete	n.
Mete	v. t. & i.
Mete	v. i. & t.
Mete	v. t.
Mete	v. i.
Mete	n.
Mete"corn`	n.
Mete"ly	a.
Met`em*pir"ic	a.
Met*em*pir"i*cism	n.
Met`em*pir"ics	n.
Me*temp"sy*chose	v. t.
Me*temp`sy*cho"sis	n.
Met`emp*to"sis	n.
Met`en*ceph"a*lon	n.
Met`en*so`ma*to"sis	n.
Me"te*or	n.
Me`te*or"ic	a.
Me`te*or"ic*al	a.
Me"te*or*ism	n.
Me"te*or*ite	n.
Me"te*or*ize	v. i.
Me`te*or"o*graph	n.
Me`te*or`o*graph"ic	a.
Me`te*or*og"ra*phy	n.
Me"te*or*oid	n.
Me`te*or*oid"al	a.
Me`te*or"o*lite	n.
Me`te*or`o*log"ic	a.
Me`te*or*ol"o*gist	n.
Me`te*or*ol"o*gy	n.
Me`te*or"o*man`cy	n.
Me`te*or*om"e*ter	n.
Me`te*or"o*scope	n.
Me*te"o*rous	a.
-me"ter	n.
Me"ter	n.
Me"ter	n.
Me"ter*age	n.
Me"ter*gram`	n.
Mete"wand`	n.
Mete"yard`	n.
Meth	n.
Met`haem*o*glo"bin	n.
methadon	n.
Meth"al	n.
methanal	n.
Meth"ane	n.
methanogen	n.
methanol	n.
Meth`a*nom"e*ter	n.
Me*theg"lin	n.
Meth"ene	n.
Meth"e*nyl	n.
Meth"ide	n.
Me*thinks"	v. impers.
Me*thi"on*ate	n.
Meth`i*on"ic	a.
Meth"od	n.
Me*thod"ic	a.
Me*thod"ios	n.
Meth"o*dism	n.
Meth"o*dist	n.
Meth"o*dist	a.
Meth`o*dis"tic	a.
Meth`od*i*za"tion	n.
Meth"od*ize	v. t.
Meth"od*i`zer	n.
Meth`od*o*log"ic*al	a.
Meth`od*ol"o*gy	n.
Meth"ol	n.
Me*thought"	imp.
Meth*ox"yl	n.
Meth"yl	n.
Meth"yl*al	n.
Meth`yl*am"ine	n.
Meth"yl*ate	n.
Meth"yl*ate	v. t.
Meth"yl*a`ted	a.
Meth"yl*ene	n.
methylenedioxymethamphetamine	n.
Me*thyl"ic	a.
Me*thys"ti*cin	n.
Met"ic	n.
meticulosity	n.
Me*tic"u*lous	a.
M<eacute/`tier"	n.
M<eacute/`tif"	n. m.
M<eacute/`tis"	n. m.
Met"o*che	n.
Me"tol	n.
Me*ton"ic	a.
Met`o*nym"ic	a.
Me*ton"y*my	n.
Met"o*pe	n.
Me*top"ic	a.
Met"o*po*man`cy	n.
Met`o*po*scop"ic	a.
Met`o*pos"co*pist	n.
Met`o*pos"co*py	n.
Me*tos"te*on	n.
Me"tre	n.
Met"ric	a.
Met"ric*al	a.
Met"ric*al*ly	adv.
met`ri*ca"tion	n.
Me*tri"cian	n.
Met"ric sys"tem	n.
Met"ric ton	n.
Met"ri*fy	v. i.
Me"trist	n.
Me*tri"tis	n.
Met"ro*chrome	n.
Met"ro*graph	n.
Met`ro*log"ic*al	a.
Me*trol"o*gy	n.
Met`ro*ma"ni*a	n.
Met`ro*ma"ni*ac	n.
Me*trom"e*ter	n.
Met"ro*nome	n.
Me*tron"o*my	n.
Met`ro*nym"ic	a.
Met"ro*pole	n.
Me*trop"o*lis	n.
Met`ro*pol"i*tan	a.
Met`ro*pol"i*tan	n.
Met`ro*pol"i*tan*ate	n.
Me*trop"o*lite	n.
Met`ro*po*lit"ic*al	a.
Met`ror*rha"gi*a	n.
Met"ro*scope	n.
Met`ro*si*de"ros	n.
Met"ro*tome	n.
Me*trot"o*my	n.
-me*try	imp.
Met"tle	n.
Met"tled	a.
Met"tle*some	a.
Me"um	n.
Meuse	prop. n.
Meuse-Argonne	prop. n.
Meute	n.
Meve	v. t. & i.
Mew	n.
Mew	v. t.
Mew	v. i.
Mew	n.
Mew	v. t.
Mew	v. i.
Mew	n.
Mewl	v. i.
Mewl"er	n.
Mews	n. sing. & pl.
Mex*al"	n.
Mex"i*can	prop. a.
Mex"i*can*ize	prop. v. t.
Mex"i*can*ize	prop. v. i.
Meyn"e	n.
Mez*cal"	n.
Me*ze"re*on	n.
Mez*qui"ta	n.
Me*zu"za	n.
Mez"za ma*jol"i*ca	n.
Mez"za vo"ce	a.
Mez"zo-re*lie"vo	n.
Mez"zo-ri*lie"vo	n.
Mez"zo-so*pra"no	a.
Mez"zo*tint	n.
Mez"zo*tint	v. t.
Mez"zo*tint`er	n.
Mez`zo*tin"to	n.
Mez`zo*tin"to	v. t.
Mho	n.
Mhom"e*ter	n.
Mhorr	n.
Mi	n.
Mi*a"mis	n. pl.
Mi*ar"gy*rite	n.
Mi"as	n.
Mi*asc"ite	n.
Mi"asm	n.
Mi*as"ma	n.
Mi*as"mal	a.
Mi`as*mat"ic	a.
Mi*as"ma*tist	n.
Mi`as*mol"o*gy	n.
Mi*aul"	v. i.
Mi*aul"	n.
Mi"ca	n.
Mi*ca`ce*o-cal*ca"re*ous	a.
Mi*ca"ceous	a.
mice	n.
Mi*cel"la	n.
Mich	v. i.
Mich"ael*mas	n.
Michelangelesque	prop. adj.
Michelangelo	prop. n.
Mich"er	n.
Mich"er*y	prop. n.
Michigander	n.
Mich"ing	a.
Mick	n.
Mic"kle	a.
Mic"macs	n. pl.
Mi"co	n.
Mi`cra*cous"tic	a.
Mi*cras"ter	n.
Mi`cren*ceph"a*lous	n.
Mi`cro*a*nal"y*sis	n.
Mi`cro*bac*te"ri*a	n. pl.
Mi`cro*bar"o*graph	n.
Mi"crobe	n.
mi*cro"bi*al	a.
Mi*crob"ic	a.
Mi*crob"i*cide	n.
Mi`cro*bi*ol"o*gy	n.
Mi`cro*ce*phal"ic	a.
mi`cro*chem"ic*al	a.
mi`cro*chem"is*try	n.
Mi`cro*chro*nom"e*ter	n.
Mi"cro*cline	n.
Mi`cro*coc"cal	a.
Mi`cro*coc"cus	n.
microcomputer	n.
Mi"cro*cosm	n.
Mi`cro*cos"mic	a.
Mi`cro*cos*mog"ra*phy	n.
Mi`cro*cou`lomb"	n.
Mi`cro*cous"tic	a.
Mi`cro*cous"tic	n.
Mi`cro*crith"	n.
Mi`cro*crys"tal*line	a.
Mi"cro*cyte	n.
Mic"ro*dont	a.
Mi`cro*far"ad	n.
Mic"ro*film	n.
Mic"ro*film	v. t.
Mi"cro*form	n.
Mi`cro-ge`o*log"ic*al	a.
Mi`cro-ge*ol"o*gy	n.
Mi"cro*graph	n.
Mi`cro*graph"ic	a.
Mi*crog"ra*phy	n.
Mi*crohm"	n.
Mi`cro*lep`i*dop"te*ra	n. pl.
Mi`cro*les"tes	n.
Mi"cro*lite	n.
Mi"cro*lith	n.
Mi`cro*lith"ic	a.
Mi`cro*log"ic	a.
Mi*crol"o*gy	n.
micromercurialism	n.
Mi"cro*mere	n.
micrometeorite	n.
micrometeoritic	adj.
Mi*crom"e*ter	n.
Mi`cro*met"ric	a.
Mi*crom"e*try	n.
Mi`cro*mil"li*me`ter	n.
Micromyx	prop. n.
mic"ron	n.
Mi"cro*ne"sian	a.
Mi`cro*ne"sians	n. pl.
Mi`cro*nom"e*ter	n.
Mi`cro*or"gan*ism	n.
Mi`cro*pan"to*graph	n.
Mi`cro*par"a*site	n.
Mi`cro*peg"ma*tite	n.
mi"cro*phone	n.
mi`cro*phon"ic	a.
mi`cro*phon"ics	n.
mi*croph"o*nous	a.
mi`cro*pho"to*graph	n.
Mi`cro*pho*tog"ra*phy	n.
Mi`croph*thal"mi*a	n.
Mi*croph"yl*lous	a.
Mi*croph"y*tal	a.
Mi"cro*phyte	n.
Mi"cro*pyle	n.
Mi*cros"co*pal	a.
Mi"cro*scope	n.
Mi`cro*sco"pi*al	a.
Mi`cro*scop"ic	a.
Mi`cro*scop"ic*al*ly	adv.
Mi*cros"co*pist	n.
Mi*cros"co*py	n.
Mi"cro*seism	n.
Mi`cro*seis"mo*graph	n.
Mi`cro*seis*mol"o*gy	n.
Mi`cro*seis*mom"e*ter	n.
Mi"cro*seme	a.
microsome	n.
Microsorium	prop. n.
Mi`cro*spec"tro*scope	n.
Mi`cro*spo*ran"gi*um	n.
Mi"cro*spore	n.
Mi`cro*spor"ic	a.
Mi"cro*sthene	n.
Mi`cro*sthen"ic	a.
Mi`cro*ta*sim"e*ter	n.
Mi"cro*tome	n.
Mi`cro*tom"ic	a.
Mi*crot"o*mist	n.
Mi*crot"o*my	n.
Mi`cro*volt"	n.
Mi`cro*we"ber	n.
Mi`cro*zo"a	n. pl.
Mi`cro*zo"o*spore	n.
Mi"cro*zyme	n.
Micruroides	prop. n.
Micrurus	prop. n.
micturate	v. i.
Mic`tu*ri"tion	n.
Mid	a.
Mid	n.
Mid	prep.
Mi"da	n.
mid*air"	n.
Mi"das	n.
Mi"das's ear"	n.
Mid"day`	n.
Mid"day`	a.
Mid"den	n.
Mid"den crow"	a.
Mid"dest	n.
Mid"ding	n.
Mid"dle	a.
Mid"dle	n.
Mid"dle-age`	a.
Mid"dle-earth`	n.
Mid"dle-ground`	n.
middle-level	adj.
Mid"dle*man	n.
Mid"dle*most`	a.
middle-of-the-road	adj.
Mid"dler	n.
Mid"dling	a.
Mid"dlings	n. pl.
Mid"dy	n.
mid-eighties	n.
Mid"feath`er	n.
mid-February	n.
midfield	n.
mid-fifties	n.
mid-forties	n.
Mid"gard	n.
Midge	n.
Midg"et	n.
Mid"gut`	n.
Mid"heav`en	n.
midiron	n.
mid-January	n.
mid-July	n.
mid-June	n.
Mid"land	a.
Mid"land	n.
Mid"main`	n.
mid-March	n.
mid-May	n.
Mid"most`	a.
Mid"night`	n.
Mid"night`	a.
Mid"night` sun	n.
mid-November	n.
mid-October	n.
mid-off	n.
mid-on	n.
Mid*rash"	n.
Mid"rib`	n.
Mid"riff	n.
Mid" sea"	n.
mid-September	n.
mid-seventies	n.
Mid"ship`	a.
Mid"ship`man	n.
Mid"ships`	adv.
Mid"ships`	n. pl.
mid-sixties	n.
Midst	n.
Midst	prep.
Midst	adv.
midstream	n.
Mid"sum`mer	n.
midsummer-men	n.
midterm	n.
mid-thirties	n.
mid-twenties	n.
Mid"ward	a.
Mid"ward	adv.
Mid"way`	n.
Mid"way`	a.
Mid"way`	adv.
Mid"week`	n.
midweekly	adj.
Midwest	n.
midwestern	adj.
Mid"wife`	n.
Mid"wife`	v. t.
Mid"wife`	v. i.
Mid"wife`ry	n.
Mid"win`ter	n.
Mid"wive`	v. t.
Mien	n.
mierkat	n.
Miff	n.
Miff	v. t.
Might	imp.
Might	n.
Might"ful	a.
Might"i*ly	adv.
Might"i*ness	n.
Might"less	a.
Might"y	a.
Might"y	n.
Might"y	adv.
Mign"iard	a.
Mign"iard*ise	n.
Mi"gnon	a.
Mi"gnon	v. t.
Mi`gnon*ette"	n.
mi*graine"	n.
Mi"grant	a.
Mi"grant	n.
Mi"grate	v. i.
Mi*gra"tion	n.
Mi"gra*to*ry	a.
Mi*ka"do	n.
mike	n.
Mik"maks	n.
mil	n.
mil	n.
Mi*la"dy	n.
Mil"age	n.
Mil`an*ese"	prop. a.
Milch	a.
Mild	a.
Mild"en	v. t.
Mil"dew	n.
Mil"dew	v. t.
Mil"dew	v. i.
Mild"ly	adv.
Mild"ness	n.
Mile	n.
Mile"age	n.
mileometer	n.
Mile"post`	n.
Mi*le"sian	a.
Mi*le"sian	n.
Mile"stone`	n.
Mil"foil	n.
Mil`i*a"ri*a	n.
Mil"ia*ry	a.
Mil"ia*ry	n.
Mi`lice"	n.
Mi`lieu"	n.
Mil"i*o`la	n.
Mil"i*o*lite	n.
Mil"i*o*lite	a.
Mil`i*o*lit"ic	a.
Mil"i*tan*cy	n.
Mil"i*tant	a.
Mil"i*tar	a.
Mil"i*ta*ri*ly	adv.
militarisation	n.
Mil"i*ta*rism	n.
Mil"i*ta*rist	n.
militaristic	adj.
militarization	n.
militarize	v. t. & i.
militarized	adj.
Mil"i*ta*ry	a.
Mil"i*ta*ry	n.
Mil"i*tate	v. i.
mil"i*tate a*gainst"	v. t.
Mi*li"tia	n.
Mi*li"tia*man	n.
Mi*li"ti*ate	v. i.
Milk	n.
Milk	v. t.
Milk	v. i.
milkcap	n.
Milk"en	a.
Milk"er	n.
Milk"ful	a.
Milk"i*ly	adv.
Milk"i*ness	n.
Milk"-liv`ered	a.
Milk"maid`	n.
Milk"man	n.
milk"shake`	n.
Milk sickness	n.
Milk" vetch`	n.
Milk"weed`	n.
Milk"wort`	n.
Milk"y	a.
Mill	n.
Mill	n.
Mill	v. t.
Mill	v. i.
Mill	v. t.
Mill"board`	n.
Mill"-cake`	n.
Mill"dam`	n.
Milled	a.
Mil`le*fi*o"re glass`	a.
Mil`le*na"ri*an	n.
Mil`le*na"ri*an*ism	n.
Mil"le*na*ry	a.
Mil"le*na*ry	n.
Mil*len"ni*al	a.
Mil*len"ni*al*ist	n.
Mil*len"ni*an*ism	n.
Mil"len*nist	n.
Mil*len"ni*um	n.
mil*len"ni*um bug`	n.
Mil"le*ped	n.
Mil*le*po"ra	n.
Mil"le*pore	n.
Mil"le*po*rite	n.
Mill"er	n.
Mil"ler*ite	n.
Mil"ler*ite	n.
Mil*les"i*mal	a.
mil"let	n.
mill-girl	n.
Mil"li-	n.
Mil`li*am`p<egrave/re"	n.
Mil`liard"	n.
Mil"li*a*ry	a.
Mil"li*a*ry	n.
Mil`lier"	n.
Mil"li*fold`	a.
Mil"li*gram	n.
Mil"li*li`ter	n.
Mil"li*me`ter	n.
Mil"li*mi`cron	n.
milline	n.
Mil"li*ner	n.
Mil"li*ner*y	n.
Mil`li*net"	n.
Mill"ing	n.
Mil"lion	n.
Mil`lion*aire"	n.
Mil`lion*air"ess	n.
Mil"lion*a*ry	a.
Mil"lioned	a.
Mil`lion`naire"	n.
Mil"lionth	a.
Mil"lionth	n.
Mil"li*ped	n.
Mil"li*stere	n.
Mil`li*we"ber	n.
millpond	n.
millrace	n.
Mill"rea`	n.
Mill"rind`	n.
millrun	n.
Mill"-sixpence	n.
Mill"stone`	n.
millwheel	n.
Mill"work`	n.
Mill"wright`	n.
milometer	n.
Mi*lord"	n.
Milquetoast	n.
Mil"reis`	n.
Milt	n.
Milt	n.
Milt	v. t.
Milt"er	n.
Mil*to"ni*an	prop. a.
Mil*ton"ic	prop. a.
Milt"waste`	a.
Mil"vine	n.
Mil"vus	n.
Mime	n.
Mime	v. i.
mimeo	n.
mimeo	v. t.
Mim"e*o*graph	n.
mimeograph	v. t.
mim"er	n.
Mi*me"sis	n.
Mim"e*tene	n.
Mi*met"ic	n.
Mim"e*tite	n.
Mim"ic	a.
Mim"ic	n.
Mim"ic	v. t.
Mim"ic*al*ly	adv.
Mim"ick*er	n.
Mim"ic*ry	n.
Mimir	prop. n.
Mi*mog"ra*pher	n.
Mi*mo"sa	n.
Mimosaceae	prop. n.
Mimosoideae	prop. n.
Mi`mo*tan"nic	a.
Mimus	prop. n.
min.	n.
Min	prop. n.
mi"na	n.
Mi"na	n.
Min"a*ble	a.
Mi*na"cious	a.
Mi*nac"i*ty	n.
Min"a*ret	n.
Min*ar"gent	n.
Min`a*to"ri*al*ly	adv.
Min"a*to*ry	a.
Mi*naul"	n.
Mince	v. t.
Mince	v. i.
Mince	n.
Mince"-meat`	n.
Mince" pie`	n.
Min"cing	a.
Min"cing*ly	adv.
Mind	n.
Mind	v. t.
Mind	v. i.
mind-altering	adj.
mind-bending	adj.
mind-blowing	adj.
mind-boggling	adj.
Mind"ed	a.
Minden	prop. n.
Mind"er	n.
Mind"ful	a.
Mind"ing	n.
Mind"less	a.
Mine	n.
Mine	pron. & a.
Mine	v. i.
Mine	v. t.
Mine	n.
mined	adj.
minefield	n.
minelayer	n.
minelaying	n.
Min"er	n.
Min"er*al	n.
Min"er*al	a.
Min"er*al*ist	n.
Min`er*al*i*za"tion	n.
Min"er*al*ize	v. t.
Min"er*al*ize	v. i.
mineralized	adj.
Min"er*al*i`zer	n.
Min`er*al*og"ic*al	a.
Min`er*al*og"ic*al*ly	adv.
Min`er*al"o*gist	n.
Min`er*al"o*gize	v. i.
Min`er*al"o*gy	n.
Mi*ner"va	n.
minesweeper	n.
minesweeping	n.
Mi*nette"	n.
Min"e*ver	n.
Minge	v. t.
Minge	n.
minginess	n.
Min"gle	v. t.
Min"gle	v. i.
Min"gle	n.
Min"gle*a*ble	a.
Min"gled*ly	adv.
Min"gle-man`gle	v. t.
Min"gle-man`gle	n.
Min"gle*ment	n.
Min"gler	n.
Min"gling*ly	adv.
Min`*a"ceous	a.
Min"iard	a.
Min"iard*ize	v. t.
Min"i*ate	v. t.
Min"i*ate	a.
Min"i*a*ture	n.
Min"i*a*ture	a.
Min"i*a*ture	v. t.
miniaturisation	n.
miniaturise	v. t.
Min"i*a*tur`ist	n.
miniaturization	n.
miniaturize	v. t.
Min"i*bus	n.
minicomputer	n.
Min"ie ball`	v. t.
Min"i*kin	n.
Min"i*kin	a.
Min"im	n.
Min"im	a.
Min"i*mal	a.
Min"i*ment	n.
minimisation	n.
Min`i*mi*za"tion	n.
min"i*mize	v. t.
minimized	adj.
Min"i*mum	n.
Min"i*mus	n.
Min"ing	n.
Min"ing	a.
Min"ion	n.
Min"ion	n.
Min"ion	a.
Min`ion*ette"	a.
Min"ion*ette	n.
Min"ion*ing	n.
Min"ion*ize	v. t.
Min"ion*like`	a. & adv.
Min"ion*ship	n.
Min"ious	a.
Min"ish	v. t.
Min"ish*ment	n.
Min"is*ter	n.
Min"is*ter	v. t.
Min"is*ter	v. i.
Min`is*te"ri*al	a.
Min`is*te"ri*al*ist	n.
Min`is*te"ri*al*ly	adv.
Min"is*ter*y	n.
Min"is*tra*cy	n.
Min"is*tral	a.
Min"is*trant	a.
Min`is*tra"tion	n.
Min"is*tra*tive	a.
Min"is*tress	n.
Min"is*try	n.
Min"is*try*ship	n.
min"i*um	n.
Min"i*ver	n.
Min"i*vet	n.
Mink	n.
Min"ne*sing`er	n.
Minnesotan	prop. n.
minniebush	n.
Min"now	n.
Min"ny	n.
Mi"no bird"	a.
Mi"nor	n.
Mi`no*rat"	n.
Mi"nor*ate	v. t.
Mi`nor*a"tion	n.
Mi"nor*ess	n.
Mi"nor*ite	n.
Mi*nor"i*ty	n.
minor league	n.
minor-league	a.
minors	n.
Mi"nos	prop. n.
Min"o*taur	n.
Min"ow	n.
Min"ster	n.
Min"strel	n.
Min"strel*sy	n.
Mint	n.
Mint	n.
Mint	v. t.
mint	a.
Mint"age	n.
Mint"er	n.
Mint"man	n.
Mint"-mas`ter	n.
Mint sauce	n.
min"u*end	n.
Min"u*et	n.
Min"um	n.
Mi"nus	a.
mi"nus	n.
minuscular	adj.
Mi*nus"cule	n.
minuscule	adj.
Min"u*ta*ry	a.
Min"ute	n.
Min"ute	a.
Min"ute	v. t.
Mi*nute"	a.
Mi*nute"-jack`	n.
Mi*nute"ly	adv.
Min"ute*ly	a.
Min"ute*ly	adv.
Min"ute*man	n.
Mi*nute"ness	n.
Mi*nu"ti*a	n.
Minx	n.
Minx	n.
Min"y	a.
Min*yan"	n.
Mi"o*cene	prop. a.
Mi`o*hip"pus	n.
Miq"ue*let	n.
Mir	n.
Mir	n.
Mi"ra	n.
Mi*rab"i*la*ry	n.
mi*ra"bi*le dic"tu	adv.
Mi*rab"i*lis	prop. n.
Mi*rab"i*lite	n.
Mi"ra*ble	a.
Mir"a*cle	n.
Mir"a*cle	v. t.
Mi*rac"u*lize	v. t.
Mi*rac"u*lous	a.
Mir`a*dor"	n.
Mi`rage"	n.
Mir"bane	n.
Mire	n.
Mire	n.
Mire	v. t.
Mire	v. i.
Mi*rif"ic	a.
Mi*rif"i*cent	a.
Mir"i*ness	n.
Mirk	a.
Mirk	n.
Mirk"some	a.
Mirk"y	a.
Mir"li*ton	n.
Mirounga	prop. n.
Mir"ror	n.
Mir"ror	v. t.
mirrored	adj.
mirrorlike	adj.
Mir"ror*scope	n.
Mirth	n.
Mirth"ful	a.
Mirth"less	a.
Mir"y	a.
Mir"ya*chit`	n.
Mir"za	n.
Mis-	a. & adv.
Mis*ac`cep*ta"tion	n.
Mis`ac*compt"	v. t.
Mis`ad*just"	v. t.
Mis`ad*just"ment	n.
Mis`ad*ven"ture	n.
Mis`ad*ven"tured	a.
Mis`ad*ven"tur*ous	a.
Mis`ad*vert"ence	n.
Mis`ad*vice"	n.
Mis`ad*vise"	v. t.
Mis`ad*vised"	a.
mis`af*fect"	v. t.
mis`af*fect"ed	a.
mis`af*fec"tion	n.
mis`af*firm"	v. t.
mis*aimed"	a.
mis`a*ligned"	a.
mis`align"ment	n.
mis*al`le*ga"tion	n.
mis`al*lege"	v. t.
Mis`al*li"ance	n.
Mis`al*lied"	a.
Mis`al*lot"ment	n.
Mis*al"ter	v. t.
mis"an*drist	n.
mis"an*dry	n.
mis"an*thrope	n.
Mis`an*throp"ic	a.
Mis*an"thro*pist	n.
Mis*an"thro*pos	n.
Mis*an"thro*py	n.
Mis*ap`pli*ca"tion	n.
Mis`ap*ply"	v. t.
Mis`ap*pre"ci*a`ted	a.
Mis*ap`pre*hend"	v. t.
Mis*ap`pre*hen"sion	n.
Mis*ap`pre*hen"sive*ly	adv.
Mis`ap*pro"pri*ate	v. t.
mis`ap*pro"pri*a*ted	adj.
Mis`ap*pro`pri*a"tion	n.
Mis`ar*range"	v. t.
Mis`ar*range"ment	n.
Mis`ar*cribe"	v. t.
Mis`as*say"	v. t.
Mis`as*sign"	v. t.
Mis`at*tend"	v. t.
Mis`a*ven"ture	n.
Mis`a*vize"	v. t.
Mis*bear"	v. t.
Mis`be*come"	v. t.
Mis`be*com"ing	a.
Mis*bede"	v. t.
Mis`be*fit"ting	a.
Mis`be*got"	p. a.
Mis`be*have"	v. t. & i.
Mis`be*haved"	a.
Mis`be*hav"ior	n.
Mis`be*lief"	n.
Mis`be*lieve"	v. i.
Mis`be*liev"er	n.
Mis`be*seem"	v. t.
Mis`be*stow"	v. t.
Mis`be*stow"al	n.
Mis`bi*leve"	n.
Mis*bode"	imp.
Mis*bo"den	p. p.
Mis"born`	a.
Mis*cal"cu*late	v. t. & i.
mis*cal`cu*la"tion	n.
Mis*call"	v. t.
Mis*car"riage	n.
Mis*car"riage*a*ble	a.
Mis*car"ry	v. i.
Mis*cast"	v. t.
Mis*cast"	n.
miscegenate	v.
Mis`ce*ge*na"tion	n.
Mis`cel*la*na"ri*an	a.
Mis"cel*lane	n.
Mis"cel*la"ne*a	n. pl.
Mis`cel*la"ne*ous	a.
Mis"cel*la*nist	n.
Mis"cel*la*ny	n.
Mis"cel*la*ny	a.
Mis*cen"sure	v. t.
Mis*chance"	n.
Mis*chance"	v. i.
Mis*chance"ful	a.
Mis*char"ac*ter*ize	v. t.
Mis*charge"	v. t.
Mis"chief	n.
Mis"chief	v. t.
Mis"chief*a*ble	a.
Mis"chief*ful	a.
Mis"chief-mak`er	n.
Mis"chief-mak`ing	a.
Mis"chie*vous	a.
Misch"na	n.
Misch"nic	a.
Mis*choose"	v. t.
Mis*choose"	v. i.
Mis*chris"ten	v. t.
Mis`ci*bil"i*ty	n.
Mis"ci*ble	a.
Mis`ci*ta"tion	n.
Mis*cite"	v. t.
Mis*claim"	n.
Mis*cog"ni*zant	a.
Mis*cog"nize	v. t.
Mis*col`lo*ca"tion	n.
Mis*col"or	v. t.
Mis*com"fort	n.
Mis*com`pre*hend"	v. t.
Mis*com`pu*ta"tion	n.
Mis`com*pute"	v. t.
Mis`con*ceit"	n.
Mis`con*ceive"	v. t. & i.
Mis`con*ceiv"er	n.
Mis`con*cep"tion	n.
Mis`con*clu"sion	n.
Mis*con"duct	n.
Mis`con*duct"	v. t.
Mis`con*duct"	v. i.
Mis*con"fi*dent	a.
Mis`con*jec"ture	n.
Mis`con*jec"ture	v. t. & i.
Mis*con"se*crate	v. t.
Mis*con`se*cra"tion	n.
Mis*con"se*quence	n.
Mis*con"stru*a*ble	a.
Mis`con*struct"	v. t.
Mis`con*struc"tion	n.
Mis*con"strue	v. t.
Mis*con"stru*er	n.
Mis`con*tent"	a.
Mis`con*tin"u*ance	n.
Mis*copy"	v. t.
Mis*copy"	n.
Mis`cor*rect"	v. t.
Mis*coun"sel	v. t.
Mis*count"	v. t. & i.
Mis*count"	n.
Mis*cov"et	v. t.
Mis"cre*ance	n.
Mis"cre*ant	n.
Mis"cre*ant	a.
Mis`cre*ate"	a.
Mis`cre*ate"	v. t.
Mis`cre*at"ed	a.
Mis`cre*a"tive	a.
Mis*cre"dent	n.
Mis`cre*du"li*ty	n.
Mis*cue"	n.
Mis*date"	v. t.
misdating	n.
Mis*deal"	v. t. & i.
Mis*deal"	n.
Mis*deed"	n.
Mis*deem"	v. t.
Mis`de*mean"	v. t.
Mis`de*mean"ant	n.
Mis`de*mean"or	n.
Mis*dempt"	p. p.
Mis`de*part"	v. t.
Mis`de*rive"	v. t.
Mis`de*scribe"	v. t.
Mis`de*sert"	n.
Mis`de*vo"tion	n.
Mis*di"et	n.
Mis*di"et	v. t.
Mis*dight"	a.
Mis`di*rect"	v. t.
Mis`di*rec"tion	n.
Mis*dis`po*si"tion	n.
Mis`dis*tin"guish	v. t.
Mis`di*vide"	v. t.
Mis`di*vi"sion	n.
Mis*do"	v. t.
Mis*do"	v. i.
Mis*do"er	n.
Mis*do"ing	n.
Mis*doubt"	v. t. & i.
Mis*doubt"	n.
Mis*doubt"ful	a
Mis*dread"	n.
Mise	n.
Mis*ease"	n.
Mis*eased"	a.
Mis*eas"y	a.
Mis`e*di"tion	n.
Mis*ed"u*cate	v. t.
Mis`em*ploy"	v. t.
Mis`em*ploy"ment	n.
Mis*en"ter	v. t.
Mis`en*treat"	v. t.
Mis*en"try	n.
Mi"ser	n.
Mis"er*a*ble	a.
Mis"er*a*ble	n.
Mis"er*a*ble*ness	n.
Mis"er*a*bly	adv.
Mis`er*a"tion	n.
Mis`e*re"re	n.
Mis"er*i*corde"	n.
Mis`e*ri*cor"di*a	n.
Mi"ser*ly	a.
Mi"ser*y	n.
Mis`es*teem"	n.
Mis*es"ti*mate	v. t.
Mis*ex`pla*na"tion	n.
Mis*ex`pli*ca"tion	n.
Mis*ex`po*si"tion	n.
Mis`ex*pound"	v. t.
Mis`ex*pres"sion	n.
Mis*faith"	n.
Mis*fall"	v. t.
Mis*fare"	v. i.
Mis*fash"ion	v. t.
Mis*fea"sance	n.
Mis*fea"ture	n.
Mis*feel"ing	a.
Mis*feign"	v. i.
Mis*fit"	n.
Mis*form"	v. t.
Mis`for*ma"tion	n.
Mis*for"tu*nate	a.
Mis*for"tune	n.
Mis*for"tune	v. i.
Mis*for"tuned	a.
Mis*frame"	v. t.
Mis*get"	v. t.
Mis*gie"	v. t.
Mis*give"	v. t.
Mis*give"	v. i.
mis*giv"ing	n.
Mis*go"	v. i.
Mis*got"ten	a.
Mis*gov"ern	v. t.
Mis*gov"ern*ance	n.
Mis*gov"erned	a.
Mis*gov"ern*ment	n.
Mis*gra"cious	a.
Mis*graff"	v. t.
Mis*graft"	v. t.
Mis*ground"	v. t.
Mis*growth"	n.
Mis*guess"	v. t. & i.
Mis*guid"ance	n.
Mis*guide"	v. t.
Mis*guide"	n.
Mis*guid"ing	a.
Mis*gye"	v. t.
Mis*han"dle	v. t.
Mis*hap"	n.
Mis*hap"	v. i.
Mis*hap"pen	v. i.
Mis*hap"py	a.
Mish*cup"	n.
Mis*hear"	v. t. & i.
Mish"mash`	n.
Mish"na	n.
Mish"nic	a.
Mis`im*ag`i*na"tion	n.
Mis`im*prove"	v. t.
Mis`im*prove"ment	n.
Mis"in*cline"	v. t.
Mis`in*fer"	v. t.
Mis`in*form"	v. t.
Mis`in*form"	v. i.
Mis`in*form"ant	n.
Mis*in`for*ma"tion	n.
Mis`in*form"er	n.
Mis`in*struct"	v. t.
Mis`in*struc"tion	n.
Mis`in*tel"li*gence	n.
Mis`in*tend"	v. t.
Mis`in*ter"pret	v. t.
Mis`in*ter"pret*a*ble	a.
Mis`in*ter"pre*ta"tion	n.
Mis`in*ter"pret*er	n.
Mis*join"	v. t.
Mis*join"der	n.
Mis*judge"	v. t. & i.
Mis*judg"ment	n.
Mis*keep"	v. t.
Mis*ken"	v. t.
Mis"kin	n.
Mis*kin"dle	v. t.
Mis*know"	v. t.
Mis`lac*ta"tion	n.
Mis*lay"	v. t.
Mis*lay"er	n.
Mi"sle	v. i.
Mi"sle	n.
Mis*lead"	v. t.
Mis*lead"er	n.
Mis*lead"ing	a.
Mis*learn"	v. t.
Mis*led"	imp. & p. p.
Mis"len	n.
Mis"le*toe	n.
Mis*light"	v. t.
Mis*like"	v. t. & i.
Mis*like"	n.
Mis*lik"er	n.
Mis*lik"ing	n.
Mis"lin	n. & a.
Mis*live"	v. i.
Mis*lodge"	v. t.
Mis*luck"	n.
Mis"ly	a.
Mis*make"	v. t.
Mis*man"age	v. t. & i.
Mis*man"age*ment	n.
Mis*man"a*ger	n.
Mis*mark"	v. t.
Mis*match"	v. t.
mis*matched"	adj.
Mis*mate"	v. t.
Mis*meas"ure	v. t.
Mis*meas"ure*ment	n.
Mis*me"ter	v. t.
Mis*name"	v. t.
Mis*no"mer	n.
Mis*no"mer	v. t.
Mis*num"ber	v. t.
Mis*nur"ture	v. t.
Mis`o*be"di*ence	n.
Mis`ob*serve"	v. t.
Mis`ob*serv"er	n.
Mi*sog"a*mist	n.
Mi*sog"a*my	n.
misogynic	adj.
misogynism	n.
Mi*sog"y*nist	n.
Mi*sog"y*nous	a.
Mi*sog"y*ny	n.
Mi*sol"o*gy	n.
Mis`o*pin"ion	n.
Mis*or"der	v. t.
Mis*or"der	n.
Mis*or"der*ly	a.
Mis*or`di*na"tion	n.
Mis"o*the`ism	n.
Mis*paint"	v. t.
Mis*pas"sion	n.
Mis*pay"	v. t.
Mis*pell"	v. t.
Mis*pense"	n.
Mis`per*cep"tion	n.
Mis`per*suade"	v. t.
Mis`per*sua"sion	n.
Mis*pick"el	n.
Mis*place"	v. t.
Mis*place"ment	n.
Mis*plead"	v. i.
Mis*plead"ing	n.
Mis*point"	v. t.
Mis*pol"i*cy	n.
Mis*prac"tice	n.
Mis*praise"	v. t.
Mis*print"	v. t.
mis"print	n.
Mis*prise"	v. t.
Mis*prise"	v. t.
Mis*pri"sion	n.
Mis*prize"	v. t.
Mis`pro*ceed"ing	n.
Mis`pro*fess"	v. i.
Mis`pro*fess"	v. t.
Mis`pro*nounce"	v. t. & i.
Mis`pro*nun`ci*a"tion	n.
Mis`pro*por"tion	v. t.
mis`pro*por"tion	n.
Mis*proud"	a.
Mis*punc"tu*ate	v. t.
Mis`quo*ta"tion	n.
Mis*quote"	v. t. & i.
Mis*raise"	v. t.
Mis*rate"	v. t.
Mis*read"	v. t.
Mis`re*ceive"	v. t.
Mis`re*cit"al	n.
Mis`re*cite"	v. t. & i.
Mis*reck"on	v. t. & i.
Mis*reck"on*ing	n.
Mis*rec`ol*lect"	v. t. & i.
Mis*rec`ol*lec"tion	n.
Mis`re*form"	v. t.
Mis`re*gard"	n.
Mis*reg"u*late	v. t.
Mis`re*hearse"	v. t.
Mis`re*late"	v. t.
Mis`re*la"tion	n.
Mis`re*li"gion	n.
Mis`re*mem"ber	v. t. & i.
Mis*ren"der	v. t.
Mis`re*peat"	v. t.
Mis`re*port"	v. t. & i.
Mis`re*port"	n.
Mis*rep`re*sent"	v. t.
Mis*rep`re*sent"	v. i.
Mis*rep`re*sen*ta"tion	n.
Mis*rep`re*sent"a*tive	a.
Mis*rep`re*sent"er	n.
Mis`re*pute"	v. t.
Mis*rule"	v. t. & i.
Mis*rule"	n.
Mis*rul"y	a.
Miss	n.
Miss	v. t.
Miss	v. i.
Miss	n.
Mis"sa	n.
Mis"sal	n.
Mis"sal	a.
Mis*say"	v. t.
Mis*say"	v. i.
Mis*seek"	v. t.
Mis*seem"	v. i.
Mis"sel	n.
Mis"sel*dine	n.
Mis"sel*toe	n.
Mis*sem"blance	n.
Mis*send"	v. t.
Mis*serve"	v. t. & i.
Mis*set"	v. t.
Mis*shape"	v. t.
Mis*shap"en	a.
Mis*sheathed"	a.
Mis*sif"i*cate	v. i.
Mis"sile	a.
Mis"sile	n.
Miss"ing	a.
Miss"ing*ly	adv.
Mis"sion	n.
Mis"sion	v. t.
Mis"sion*ary	n.
Mis"sion*a*ry	a.
Mis"sion*er	n.
Mis"sis	n.
Miss"ish	a.
Mississippian	prop. n.
Mis*sit"	v. t.
Mis"sive	a.
Mis"sive	n.
Mis*sound"	v. t.
Missourian	prop. n.
Mis*speak"	v. i.
Mis*speak"	v. t.
Mis*speech"	n.
Mis*spell"	v. t.
Mis*spell"ing	n.
Mis*spend"	v. t.
Mis*spend"er	n.
mis*spense"	n.
Mis*spent"	imp. & p. p.
Mis*state"	v. t.
Mis*state"ment	n.
Mis*stayed"	a.
Mis*step"	n.
Mis*step"	v. i.
Mis`suc*cess"	n.
Mis`sug*ges"tion	n.
Mis`sum*ma"tion	n.
Mis*swear"	v. i.
Mis"sy	n.
Mis"sy	n.
mist	n.
Mist	v. t.
Mist	v. i.
Mis*tak"a*ble	a.
Mis*take"	v. t.
Mis*take"	v. i.
Mis*take"	n.
Mis*tak"en	p.a.
Mis*tak"en*ly	adv.
Mis*tak"en*ness	n.
Mis*tak"er	n.
Mis*tak"ing	n.
Mis*tak"ing*ly	adv.
Mis*taught"	a.
Mis*teach"	v. t.
Mis*tell"	v. t.
Mis*tem"per	v. t.
Mis"ter	n.
Mis"ter	v. t.
Mis"ter	n.
Mis"ter	v. i.
Mis*term"	v. t.
Mis"ter*y	n.
Mist"ful	a.
Mis*think"	v. i.
Mis*think"	v. t.
Mis*thought"	n.
Mis*thrive"	v. i.
Mis*throw"	v. t.
Mis"tic	n.
Mis*tide"	v. i.
Mis`ti`gris"	n.
Mist"i*head	n.
Mist"i*ly	adv.
Mis*time"	v. t.
mistiming	n.
Mist"i*ness	n.
Mis"tion	n.
Mis*ti"tle	v. t.
Mis"tle	v. i.
Mis"tle*toe	n.
Mis"to*nusk	n.
Mis*took"	imp. & obs. p. p.
Mis`tra*di"tion	n.
Mis*train"	v. t.
Mis"tral	n.
Mis`trans*late"	v. t.
Mis`trans*la"tion	n.
Mis`trans*port"	v. t.
Mis*tread"ing	n.
Mis*treat"	v. t.
mistreated	adj.
Mis*treat"ment	n.
Mis"tress	n.
Mis"tress	v. i.
Mis"tress*ship	n.
Mis*tri"al	n.
Mis*trist"	v. t.
Mis*trow"	v. i.
Mis*trust"	n.
Mis*trust"	v. t.
Mis*trust"er	n.
Mis*trust"ful	a.
Mis*trust"ing*ly	adv.
Mis*trust"less	a.
Mis*tune"	v. t.
Mis*tu"ra	n.
Mis*turn"	v. t.
Mis*tu"tor	v. t.
Mist"y	a.
Mis*un`der*stand"	v. t.
Mis*un`der*stand"er	n.
Mis*un`der*stand"ing	n.
Mi`su*ra"to	a.
Mis*us"age	n.
Mis*use"	v. t.
Mis*use"	n.
Mis*use"ment	n.
Mis*us"er	n.
Mis*val"ue	v. t.
Mis*vouch"	v. t.
Mis*wan"der	v. i.
Mis*way"	n.
Mis*wear"	v. t.
Mis*wed"	v. t.
Mis*ween"	v. i.
Mis*wend"	v. i.
Mis*word"	v. t.
Mis*word"	n.
Mis*wor"ship	n.
Mis*wor"ship	v. t.
Mis*wor"ship*er	n.
Mis*write"	v. t.
Mis*wrought"	a.
Mi"sy	n.
Mis*yoke"	v. t.
Mis*zeal"ous	a.
Mite	n.
Mitella	prop. n.
Mi"ter	n.
Mi"ter	v. t.
Mi"ter	v. i.
Mi"ter*wort`	n.
Mith"ic	a.
Mi"thra	prop. n.
mithraic	adj.
Mithraicism	prop. n.
Mithraism	prop. n.
Mithraist	prop. n.
Mith"ri*date	n.
Mith`ri*dat"ic	a.
Mit"i*ga*ble	a.
Mit"i*gant	a.
Mit"i*gate	v. t.
mitigated	adj.
mitigating	adj.
Mit`i*ga"tion	n.
Mit"i*ga*tive	a.
Mit"i*ga`tor	n.
Mit"i*ga*to*ry	a.
Mit"ing	n.
Mi"tis cast`ing	n.
Mi*to"sis	n.
Mi*tot"ic	a.
Mi`traille"	n.
Mi`tra`illeur"	n.
Mi`tra`illeuse"	n.
Mi"tral	a.
Mi"tre	n. & v.
mitrewort	n.
Mit"ri*form	a.
Mitt	n.
Mit"ten	n.
Mit"tened	a.
Mit"tent	a.
Mit"ti*mus	n.
Mit"tler's green`	n.
Mi"tu	n.
Mit"y	a.
Mix	v. t.
Mix	v. i.
Mix"a*ble	a.
Mixed	a.
Mix"ed*ly	adv.
Mix"en	n.
Mix"er	n.
Mix*og"a*mous	a.
Mix`o*lyd"i*an mode`	a.
Mix"tion	n.
Mixt"ly	adv.
Mix"ture	n.
mix up	n.
mix-up	n.
mizenmast	n.
Miz"maze`	n.
Miz"zen	a.
Miz"zen	n.
Miz"zen*mast	n.
Miz"zle	v. i.
Miz"zle	n.
Miz"zy	n.
ml	n.
mm	n.
mM	a.
Mn	n.
M'-Naught"	v. t.
Mne*mon"ic	a.
mnemonic	n.
Mne`mo*ni"cian	n.
Mne*mon"ics	n.
Mne*mos"y*ne	n.
mnemotechnical	adj.
Mne"mo*tech`ny	n.
Mniaceae	prop. n.
Mnium	prop. n.
Mo	a., adv., & n.
Mo	n.
Mo"ab*ite	n.
Mo"ab*i`tess	n.
Mo"ab*ite stone	a.
Moan	v. i.
Moan	v. t.
Moan	n.
Moan"ful	a.
Moat	n.
Moat	v. t.
Moate	v. i.
Mob	n.
Mob	v. t.
Mob	n.
Mob	v. t.
Mob"bish	a.
Mob"cap`	n.
Mo"bile	a.
Mo"bile	n.
Mo"bile	n.
mobilise	n.
mobilisation	n.
Mo*bil"i*ty	n.
Mob`i*li*za"tion	n.
Mob"i*lize	v. t.
Mo"bi*us strip`	n.
Mo"ble	v. t.
Mo"bles	n. pl.
Mob*oc"ra*cy	n.
Mob"o*crat	n.
Mob`o*crat"ic	a.
mocassin	n.
moc"ca*sin	n.
Moc"ca*sined	a.
Mo"cha	n.
Moche	n.
Moche	a.
Moch"el	a. & adv.
Mo*chi"la	n.
Mock	v. t.
Mock	v. i.
Mock	n.
Mock	a.
Mock"a*ble	a.
Mock"a*do	n.
Mock"a*dour	n.
Mock"age	n.
Mock"bird`	n.
Mock"er	n.
mockernut	n.
Mock"er*y	n.
Mock"ing	a.
mockingbird	n.
Mock"ing*ly	adv.
Mock"ing*stock`	n.
Mock"ish	a.
Moc"kle	a.
Mo"co	n.
Mo"dal	a.
Mo"dal	n.
mo"dal aux*il"iar*y	n.
Mo"dal*ist	n.
Mo*dal"i*ty	n.
mo"dal log"ic	n.
Mo"dal*ly	adv.
Mode	n.
Mod"el	n.
Mod"el	a.
Mod"el	v. t.
Mod"el	v. i.
modeled	adj.
Mod"el*er	n.
Mod"el*ing	n.
Mod"el*ize	v. t.
mo"dem	n.
Mod"e*na	n.
Mod`e*nese"	a.
Mo"der	n.
Mod"er	v. t.
Mod"er*a*ble	a.
Mod"er*ance	n.
Mod"er*ate	a.
Mod"er*ate	n.
Mod"er*ate	v. t.
Mod"er*ate	v. i.
moderated	adj.
Mod"er*ate*ly	adv.
Mod"er*ate*ness	n.
moderating	adj.
Mod`er*a"tion	n.
Mod"er*a*tism	n.
Mod`e*ra"to	a. & adv.
Mod"er*a`tor	n.
Mod"er*a`tor*ship	n.
Mod"er*a`tress	n.
Mod"er*a`trix	n.
Mod"ern	a.
Mod"ern	n.
modernisation	n.
Mod"ern*ism	n.
Mod"ern*ist	n.
modernistic	adj.
Mo*der"ni*ty	n.
Mod`ern*i*za"tion	n.
Mod"ern*ize	v. t.
Mod"ern*i`zer	n.
Mod"ern*ly	adv.
Mod"ern*ness	n.
Mod"est	a.
Mod"est*ly	adv.
Mod"es*ty	n.
Mo*dic"i*ty	n.
Mod"i*cum	n.
Mod`i*fi`a*bil"i*ty	n.
Mod"i*fi`a*ble	a.
Mo*dif"i*ca*ble	a.
Mod"i*fi*cate	v. t.
Mod`i*fi*ca"tion	n.
Mod"i*fi*ca*tive	n.
Mod"i*fi*ca`to*ry	a.
Mod"i*fi`er	n.
Mod"i*fy	v. t.
Mo*dil"lion	n.
Mo*di"o*lar	a.
Mo*di"o*lus	n.
Mod"ish	a.
Mod"ist	n.
Mo`diste"	n.
Mo"di*us	n.
Mo"docs	n. pl.
Mod"u*lar	a.
Mod"u*late	v. t.
Mod"u*late	v. i.
modulated	adj.
Mod`u*la"tion	n.
Mod"u*la`tor	n.
mod"u*la`tor-de`mod"u*la`tor	n.
Mod"ule	n.
Mod"ule	v. t.
Mod"u*lus	n.
Mo"dus	n.
Mo"dus op`er*an"di	a.
Moe	n.
Moe	v. i.
Moe	a., adv., & n.
Moe"bles	n. pl.
Mo"el*line	n.
Mo"el*lon	n.
Moe`so*goth"ic	a.
Moe`so*goth"ic	n.
Moeve	v. t. & i.
Moff	n.
Mog	v. t.
Mogen David	n.
Mog"gan	n.
Mo*ghul"	n.
Mo*gul"	n.
Mo*ghul"	prop. a.
Mo*ghul" empire	prop. a.
Mo"ha	n.
Mo"hair`	n.
Mohammed	n.
Mo*ham"med*an	a.
Mo*ham"med*an	n.
Mo*ham"med*an cal"en*dar	prop. n.
Mo*ham"med*an*ism	prop. n.
Mo*ham"med*an*ize	prop. v. t.
Mohammedan year	prop. n.
Mo"hawk	prop. n.
Mo*hi"cans	prop. n. pl.
Mo"ho	n.
Mo"ho	n.
Mo"hock	n.
Mo*ho"li	n.
Mohorovicic discontinuity	n.
Mohr	n.
Mo"hur	n.
Mo*hur"rum	n.
Moi"der	v. i.
Moi"dore	n.
Moi"e*ty	n.
Moil	v. t.
Moil	v. i.
Moil	n.
Moile	n.
Moi"neau	n.
Moi"ra	n.
Moire	n.
Moi`r<eacute/"	n.
Moi`r<eacute/"	a.
Moi*r<eacute/"	v. t.
Moi`r<eacute/" m<eacute/`tal`lique"	a.
Moist	v. t.
Mois"ten	v. t.
Mois"ten*er	n.
Moist"ful	a.
Moist"less	a.
Moist"ness	n.
Mois"ture	n.
Mois"ture*less	a.
Moist"y	a.
Moi"ther	v. t.
Moi"ther	v. i.
Mo*jar"ra	n.
Mok"a*dour	n.
Moke	n.
Moke	n.
Mo"ky	a.
mol	n.
Mo"la	n.
molal	adj.
molality	n.
mo"lar	a.
mo"lar	a.
Mo"lar	a.
Mo"lar	n.
Mo"la*ry	a.
Mo*lasse"	n.
Mo*las"ses	n.
Mold	n.
Mold	n.
Mold	v. t.
Mold	n.
Mold	v. t.
Mold	v. i.
Mold	n.
Mold	v. t.
Mold"a*ble	a.
Mold"board`	n.
Mold"er	n.
Mold"er	v. i.
Mold"er	v. t.
Mold"er*y	a.
Mold"i*ness	n.
Mold"ing	n.
Mold"ing	p. a.
Mold"warp	n.
Mold"y	a.
Mole	n.
Mole	n.
Mole	n.
Mole	n.
mole	n.
Mole	v. t.
Mole"but	n.
Mole"cast`	n.
Mo"lech	prop. n.
Mo*lec"u*lar	a.
mo*lec"u*lar form"u*la	n.
Mo*lec`u*lar"i*ty	n.
Mo*lec"u*lar*ly	adv.
Mol"e*cule	n.
Mole"-eyed`	a.
Mole"hill`	n.
mMo*len`di*na"ceous	a.
mole"skin`	n.
Mo*lest"	v. t.
Mo*lest"	n.
Mol`es*ta"tion	n.
molested	adj.
Mo*lest"er	n.
Mo*lest"ful	a.
Mo*les"tie	n.
Mole"warp`	n.
Mo*lim"i*nous	a.
Mo"line	n.
Mo"lin*ism	n.
Mo"lin*ist	n.
Moll	a.
Mol"lah	n.
Mol"le	a.
Mol"le*bart	n.
Mol"le*moke`	n.
Mol"lient	a.
Mol"lient*ly	adv.
Mol"li*fi`a*ble	a.
Mol`li*fi*ca"tion	n.
Mol"li*fi`er	n.
Mol"li*fy	v. t.
Mol"li*net	n.
Mol`li*pi*lose"	a.
Mol*li"ti*es	n.
Mol"li*tude	n.
Mol"lusc	n.
Mol*lus"ca	prop. n. pl.
Mol*lus"can	a.
Mol*lus"coid	a.
Mol`lus*coid"al	a.
Mol`lus*coi"de*a	n. pl.
Mol*lus"cous	a.
Mol*lus"cum	n.
Mol"lusk	n.
Mol"ly	n.
Mol"ly	n.
mollycoddle	n.
mollycoddle	v. t.
Mol"ly-mawk`	n.
Mo"loch	prop. n.
Mol`o*ka"ne	n. pl.
Mo*losse"	n.
Mo*los"ses	n.
Mo*los"sine	n.
Mo*los"sus	n.
Molotov	n.
Molotov cocktail	n.
Molt	imp.
Molt	v. i.
Molt	v. t.
Molt	n.
Molt"a*ble	a.
Mol"ten	a.
molting	n.
Mol"to	adv.
Mo"ly	n.
Mo*lyb"date	n.
Mol`yb*de"na	n.
Mo*lyb"de*nite	n.
Mo*lyb"de*nous	a.
Mol`yb*de"num	n.
Mo*lyb"dic	a.
Mo*lyb"dite	n.
Mo*lyb"dous	a.
Mome	n.
Mo"ment	n.
Mo*men"tal	a.
Mo*men"tal*ly	adv.
Mo`men*ta"ne*ous	a.
Mo"men*ta*ri*ly	adv.
Mo"men*ta*ri*ness	n.
Mo"men*ta*ry	a.
Mo"ment*ly	adv.
Mo*men"tous	a.
mo*men"tous*ness	n.
Mo*men"tum	n.
Mom"i*er	n.
Mom"mer*y	n.
Momordica	prop. n.
Momos	prop. n.
Mo"mot	n.
Momotus	prop. n.
Mo"mus	prop. n.
Mon	n.
Mon-	n.
Mon"a*chal	a.
Mon"a*chism	n.
mon*ac"id	a.
mon*ac"id	n.
Mon"ad	n.
Mon`a*da"ri*a	n. pl.
Mon`a*del"phi*a	n. pl.
Mon`a*del"phi*an	a.
Mo*nad"ic	a.
Mo*nad"i*form	a.
Mon`ad*ol"o*gy	n.
Mo*nal"	n.
Mon*am"ide	n.
Mon*am"ine	n.
Mo*nan"der	n.
Mo*nan"dri*a	n. pl.
Mo*nan"dri*an	a.
Mo*nan"dric	a.
Mo*nan"drous	a.
Mo*nan"dry	n.
Mo*nan"thous	a.
Mon"arch	n.
Mon"arch	a.
Mo*nar"chal	a.
mon"arch but"ter*fly	n.
Mon"arch*ess	n.
Mo*nar"chi*al	a.
Mo*nar"chi*an	n.
Mo*nar"chic	a.
Mon"arch*ism	n.
Mon"arch*ist	n.
Mon"arch*ize	v. i.
Mon"arch*ize	v. t.
Mon"arch*i`zer	n.
Mo*nar"cho	n.
Mon"arch*y	n.
monarda	n.
Mo"nas	n.
Mon`as*te"ri*al	a.
Mon"as*te*ry	n.
Mo*nas"tic	n.
Mo*nas"tic	a.
Mo*nas"tic*al*ly	adv.
Mo*nas"ti*cism	n.
Mo*nas"ti*con	n.
Mon`a*tom"ic	adv.
mon*au"ral	a.
Mo*nax"i*al	a.
Mon"a*zite	n.
Mon"day	n.
Mon"day's Child	n.
Monde	n.
Mone	n.
Mone	n.
Mo*ne"cian	a.
Mon*em"bry*o*ny	n.
Mo"ner	n.
Mo*ne"ra	n. pl.
Mo*ne"ral	a.
Mo*ne"ran	a.
Mo*ne"ron	n.
Mo*ner"u*la	n.
Mo*ne"sia	n.
Mo*ne"sin	n.
Mo*nest"	v. t.
mon*es"trous	a.
mon"e*tar*ism	n.
mon"e*tar*ist	n.
Mon"e*ta*ry	a.
Mon"eth	n.
monetisation	n.
mon`e*ti*za"tion	n.
Mon"e*tize	v. t.
Mon"ey	n.
Mon"ey	v. t.
Mon"ey*age	n.
moneybag	n.
Mon"eyed	adv.
Mon"ey*er	n.
moneylender	n.
Mon"ey*less	a.
Mon"ey-mak`er	n.
Mon"ey-mak`ing	n.
Mon"ey-mak`ing	a.
moneyman	n.
money-spinner	n.
Mon"ey*wort`	n.
Mong"corn`	n.
Mon"ger	n.
Mon"ger	v. t.
Mon"gol	n.
Mon*go"li*an	a.
Mon*gol"ic	a.
Mon"go*loid	a.
Mon"go*loid	n.
Mon"gols	n. pl.
Mon"goose	n.
Mon"grel	n.
Mon"grel	a.
Mon"grel*ize	v. t. & i.
'Mongst	prep.
monicker	n.
Mon"ied	a.
Mo*nif"i*er	n.
Mo*nil`i*a"les	n. pl.
moniliasis	n.
Mo*nil"i*form	a.
Mon"i*ment	n.
Mon"ish	v. t.
Mon"ish*er	n.
Mon"ish*ment	n.
Mon"ism	n.
Mon"ist	n.
Mo*nis"tic	a.
Mo*ni"tion	n.
Mon"i*tive	a.
Mon"i*tor	n.
Mon`i*to"ri*al	a.
Mon`i*to"ri*al*ly	adv.
Monitor nozzle	n.
Mon"i*to*ry	a.
Mon"i*to*ry	n.
Mon"i*tress	n.
Monk	n.
Monk"er*y	n.
Mon"key	n.
Mon"key	v. t. & i.
Mon"key-bread`	n.
Mon"key-cup`	n.
monkeypod	n.
Mon"key-pot`	n.
Mon"key's puz"zle	n.
monkeywrench	n.
Monk"fish	n.
Monk"flow`er	n.
Monk"hood	n.
Monk"ing	a.
Monk"ish	a.
Monk"ly	a.
Monks"hood`	n.
Monk's" seam`	n.
Mon`o*ba"sic	a.
mon`o*car*bon"ic	a.
Mon`o*car"di*an	a.
Mon"o*carp	n.
Mon`o*car"pel*la*ry	a.
Mon`o*car"pic	a.
Mon`o*ceph"a*lous	a.
Mo*noc"e*ros	n.
Mon`o*chla*myd"e*ous	a.
Mon"o*chord	n.
Mon`o*chro*mat"ic	a.
Mon"o*chrome	n.
Mon`o*chro"mic	a.
Mon"o*chro`my	n.
Mon`o*chron"ic	a.
Mon`o*cil"i*a`ted	a.
Mon"o*cle	n.
Mon`o*cli"nal	a.
Mon"o*cline	n.
Mon`o*clin"ic	a.
Mo*noc"li*nous	a.
Mon`o*con"dy*la	n. pl.
Mon"o*co*tyl	n.
Mon"o*co*tyle	a.
Mon`o*cot`y*le"don	n.
Monocotyledonae	prop. n.
Mon`o*cot`y*le"don*ous	a.
Mo*noc"ra*cy	n.
Mon"o*crat	n.
Mon`o*crot"ic	a.
Mo*noc"ro*tism	n.
Mo*noc"u*lar	a.
mon"o*cule	n.
mo*noc"u*lous	a.
mon`o*cys"tic	a.
Mon`o*dac"tyl*ous	a.
Mon"o*delph	n.
Mon`o*del"phi*a	n. pl.
Mon`o*del"phic	a.
Mo*nod"ic	a.
Mon`o*di*met"ric	a.
Mon"o*dist	n.
Mon"o*dra`ma	n.
Mon`o*dra*mat"ic	a.
Mon"o*dy	n.
Mon`o*dy*nam"ic	a.
Mon`o*dy"na*mism	n.
Mo*noe"ci*a	n. pl.
Mo*noe"cian	a.
Mo*noe"cious	a.
Mo*noe"cism	n.
Mon"o*gam	n.
Mon`o*ga"mi*a	n. pl.
Mon`o*ga"mi*an	a.
Mo*nog"a*mist	n.
Mo*nog"a*mous	a.
monogamousness	n.
Mo*nog"a*my	n.
Mon`o*gas"tric	a.
Mon`o*gen"e*sis	n.
Mon`o*ge*net"ic	a.
Mon`o*gen"ic	a.
Mo*nog"e*nism	n.
Mo*nog"e*nist	n.
Mon`o*ge*nis"tic	a.
Mo*nog"e*nous	a.
Mo*nog"e*ny	n.
Mon`o*go*neu"tic	a.
Mon"o*gram	n.
mon"o*gram	v. t.
Mon"o*gram`mal	a.
Mon`o*gram*mat"ic	a.
Mon`o*gram"mic	a.
Mon"o*gram`mous	a.
Mon"o*graph	n.
Mo*nog"ra*pher	n.
Mon`o*graph"ic	a.
Mo*nog"ra*phist	n.
Mo*nog"ra*phous	a.
Mo*nog"ra*phy	n.
Mon"o*gyn	n.
Mon`o*gyn"i*a	n. pl.
Mon`o*gyn"i*an	a.
Mo*nog"y*nous	a.
Mo*nog"y*ny	n.
Mon`o*hem"er*ous	a.
Mo*noi"cous	a.
Mo*nol"a*try	n.
mon`o*lin"gual	adj.
Mon"o*lith	n.
Mon"o*lith`al	a.
Mon`o*lith"ic	a.
Mo*nol"o*gist	n.
Mon"o*logue	n.
Mo*nol"o*gy	n.
Mon`o*ma"chi*a	n.
Mo*nom"a*chist	n.
Mon"o*mane	n.
Mon`o*ma"ni*a	n.
Mon`oma"ni*ac	n.
Mon`oma"ni*ac	a.
Mon"ome	n.
mon"o*mer	n.
mon`o*mer"ic	a.
Mo*nom"er*ous	a.
Mon`o*me*tal"lic	a.
Mon`o*met"al*lism	n.
Mon`o*met"al*list	n.
Mo*nom"e*ter	n.
Mon`o*met"ric	a.
Mo*no"mi*al	n.
Mo*no"mi*al	a.
Mon`o*mor"phic	a.
Mo*nom"pha*lus	n.
Mo*no"my*a	n. pl.
Mon`o*my"a*ri*an	a.
Mon`o*no"mi*al	n. & a.
Mon`o*ou"si*an	a.
Mo*nop"a*thy	n.
Mon`o*per"son*al	a.
Mon`o*pet"al*ous	a.
Mo*noph"a*nous	a.
Mon`o*phon"ic	a.
Mon"oph*thong	n.
Mon`oph*thon"gal	a.
Mon`o*phy*let"ic	a.
Mo*noph"yl*lous	a.
Mon`o*phy"o*dont	a.
Mo*noph"y*site	n.
Mon`o*phy*sit"ic*al	a.
Mon"o*plast	n.
Mon`o*plas"tic	a.
Mon`ople"gi*a	n.
Mon`op*neu"mo*na	n. pl.
Mon"o*pode	n.
Mon`o*po"di*al	a.
Mon`o*po"di*um	n.
Mo*nop"o*dy	n.
Mo*nop"o*ler	n.
Mo*nop"o*list	n.
Mo*nop`o*lis"tic	a.
Mo*nop"o*lite	n.
Mo*nop"o*lize	v. t.
Mo*nop"o*li`zer	n.
Mo*nop"o*ly	n.
Mon`o*pol"y*logue	n.
Mon`o*psy"chism	n.
mo*nop"ter*al	a.
Mo*nop"ter*on	n.
Mon"op*tote	n.
Mon`o*py*re"nous	a.
Mon`or*gan"ic	a.
Mon`o*rhi"na	n. pl.
Mon"o*rhyme	n.
Mon`o*sac"cha*ride	n.
Mon`o*sep"al*ous	a.
monosodium glutamate	n.
Mon"o*sperm	n.
Mon`o*sper"mal	a.
Mon`o*spher"ic*al	a.
Mon"o*stich	n.
Mo*nos"ti*chous	a.
Mo*nos"tro*phe	n.
Mon`o*stroph"ic	a.
Mon`o*sul"phide	n.
Mon`o*sul"phu*ret	n.
Mon`o*syl*lab"ic	a.
Mon`o*syl"la*bism	n.
Mon"o*syl`la*ble	n.
Mon"o*syl`la*bled	a.
Mon`o*sym*met"ric	a.
Mon`o*tes"sa*ron	n.
Mon`o*thal"a*ma	n. pl.
Mon`o*thal"a*man	n.
Mon`o*thal"a*mous	a.
Mon`o*thal"mic	a.
Mon`o*the"cal	a.
Mon"o*the*ism	n.
Mon"o*the*ist	n.
Mon`o*the*is"tic	a.
Mo*noth"e*lism	n.
Mo*noth"e*lite	n.
Mon`o*the*lit"ic	prop. a.
Mo*not"o*cous	a.
Mo*not"o*mous	a.
Mon"o*tone	n.
Mon`o*ton"ic	a.
Mo*not"o*nist	n.
Mo*not"o*nous	a.
Mo*not"o*ny	n.
Mon`o*trem"a*ta	n. pl.
Mon`o*trem"a*tous	a.
Mon"o*treme	n.
Mon`o*tri"glyph	n.
Mo*not"ro*pa	n.
Monotropaceae	prop. n.
Mon"o*type	a.
Mon"o*type	a.
monovular	adj.
Mo*nox"ide	n.
Mo*nox"y*lon	n.
Mo*nox"y*lous	a.
Mon`o*zo"a	n. pl.
Mon*roe" doc"trine	n.
Mon"sel's salt`	n.
Mon`si*gno"re	n.
mon*soon"	n.
Mon"ster	n.
Mon"ster	a.
Mon"ster	v. t.
monstera	n.
mon"strance	n.
Mon*stra"tion	n.
Mon*stros"i*ty	n.
Mon"strous	a.
Mon"strous	adv.
Mon"strous*ly	adv.
Mon"strous*ness	n.
Mon`stru*os"i*ty	n.
Mon"stru*ous	a.
Mont	n.
Mon"taigne	n.
Mon*tan"ic	a.
Mon"ta*nist	n.
Mon"tant	n.
Mont" de pi`<eacute/`t<eacute/"	n.
Mon"te	n.
Monte`-ac"id	n.
Mon*teith"	n.
Mon*teith"	n.
Monte"-jus"	n.
Mon"tem	n.
Mon*te"ro	n.
Mon`tes*so"ri Meth"od	n.
Mont`gol"fier	n.
Month	n.
Month"ling	n.
Month"ly	a.
Month"ly	n.
Month"ly	adv.
Mon"ti*cle	n.
Mon*tic"u*late	a.
Mon"ti*cule	n.
Mon*tic"u*lous	a.
Mon"ti*form	a.
Mon*tig"e*nous	a.
Mon`toir"	n.
Mon"ton	n.
Mon"tre	n.
Mon*tross"	n.
Mon"true	n.
Mon"u*ment	n.
Mon`u*men"tal	a.
Mon`u*men"tal*ly	adv.
Mon*u"re*id	n.
Moo	a., adv., & n.
Moo	v. i.
Moo	n.
mooch	v. t.
moo-cow	n.
Mood	n.
Mood	n.
Moo"der	n.
Mood"i*ly	adv.
Mood"i*ness	n.
Moo"dir	n.
Mood"ish	a.
Mood"ish*ly	adv.
Mood"y	a.
Moo"lah	n.
Mool"ley	n.
moo"la	n.
Moon	n.
Moon	v. t.
Moon	v. i.
Moon"beam`	n.
Moon"blind`	a.
Moon"blink`	n.
Moon"calf`	n.
Moon"-cul"mi*na`ting	a.
Mooned	a.
Moon"er	n.
Moon"er*y	n.
Moon"et	n.
Moon"-eye`	n.
Moon"-eyed`	a.
Moon"-faced`	a.
Moon"fish`	n.
Moon"flow`er	n.
Moong	n.
Moon"glade`	n.
moo"nie	n.
Moo"nie	prop. n.
Moon"ish	a.
Moon"less	a.
Moon`light`	n.
Moon"light`	v. i.
Moon"light`er	n.
Moon"ling	n.
Moon"lit`	a.
Moon"rak`er	n.
Moon"rise`	n.
moon-round	adj.
Moon"sail`	n.
Moon"seed`	n.
Moon"set`	n.
Moon"shee	n.
Moon"shine`	n.
Moon"shine`	a.
Moon"shin`er	n.
Moon"shin`ing	n.
Moon"shin`y	a.
Moon" shot`	n.
moon-splashed	adj.
Moon"stone`	n.
Moon"strick`en	a.
Moon"struck`	a.
moonwalk	n.
Moon"wort`	n.
Moon"y	a.
Moon"y	prop. n.
Moor	n.
Moor	n.
Moor	v. t.
Moor	v. i.
Moor"age	n.
Moor"ball`	n.
Moor"band`	n.
Moor"ess	n.
moorfowl	n.
moorgame	n.
moorhen	n.
Moor"ing	n.
Moor"ish	a.
Moor"ish	a.
Moor"land	n.
Moor"pan`	n.
Moor"stone`	n.
Moo"ruk	n.
Moor"y	a.
Moor"y	n.
moose	n.
Moose"wood`	n.
moot	v.
moot	n.
Moot	v. t.
Moot	v. i.
Moot	n.
Moot	a.
Moot"a*ble	a.
Moot"er	n.
Moot"-hall`	n.
Moot"-hill`	n.
Moot"man	n.
Mop	n.
Mop	v. i.
Mop	n.
Mop	v. t.
Mop"board`	n.
Mope	v. i.
Mope	v. t.
Mope	n.
Mope"-eyed`	a.
Mope"ful	a.
mop-headed	adj.
Mop"ish	a.
Mop"lah	n.
Mop"pet	n.
Mop"sey	n.
Mop"si*cal	a.
Mop"stick`	n.
mo"pus	n.
Mo*quette"	n.
Mor"a	n.
Mo"ra	n.
Mo"ra	n.
Mo*raine"	n.
Mo*rain"ic	a.
Mor"al	a.
Mor"al	n.
Mor"al	v. i.
Mo`rale"	n.
Mor"al*er	n.
Mor"al*ism	n.
moralise	v.
Mor"al*ist	n.
moralistic	adj.
Mo*ral"i*ty	n.
Mor`al*i*za"tion	n.
Mor"al*ize	v. t.
Mor"al*ize	v. i.
Mor"al*i`zer	n.
Mor"al*ly	adv.
morals	n.
Mo*rass"	n.
mo*rass"y	a.
Mo"rate	n.
Mo*ra"tion	n.
Mor`a*to"ri*um	n.
Mor"a*to*ry	a.
Mo*ra"vi*an	a.
Mo*ra"vi*an	n.
Mo*ra"vi*an*ism	n.
Mor"ay	n.
Mor"bid	a.
Mor`bi*dez"za	n.
Mor*bid"i*ty	n.
Mor"bid*ly	adv.
Mor"bid*ness	n.
Mor*bif"ic	a.
Mor*bil"lous	a.
Mor*bose"	a.
Mor*bos"i*ty	n.
Mor`ceau"	n.
Mor*da"cious	a.
Mor*dac"i*ty	n.
Mor"dant	a.
Mor"dant	n.
Mor"dant	v. t.
Mor"dant*ly	adv.
Mor*den"te	n.
Mor"di*can*cy	n.
Mor"di*cant	a.
Mor`di*ca"tion	n.
Mor"di*ca*tive	a.
More	n.
More	n.
More	a., compar.
More	n.
More	adv.
More	v. t.
mo*reen"	n.
mor"el	n.
mor"el	n.
more"land	n.
Mo*relle"	n.
Mo*rel"lo	n.
Mo*ren"do	a. & n.
More"ness	n.
More*o"ver	adv.
More"pork`	n.
Mo"res	n. pl.
Mo*resk"	a. & n.
Mo*resque"	a.
Mor"gan	n.
Morgan	prop. n.
Mor`ga*nat"ic	a.
Mor"gay	n.
Mor"glay	n.
Morgue	n.
Mo"ri*a	n.
Mo"ri*an	n.
Mor"i*bund	a.
Mor"i*bund	n.
Mo"ric	a.
Mor"ice	n.
Mo*rig"er*ate	a.
Mo*rig`er*a"tion	n.
Mo*rig"er*ous	a.
Mor"il	n.
Mo"rin	n.
Mo*rin"da	n.
mo*rin"din	n.
Mor"i*nel`	n.
Mo*rin"ga	prop. n.
Mo*rin"gic	a.
Mo`rin*tan"nic	a.
Mo"ri*on	n.
Mo"ri*on	n.
Mo"ri*o*plas`ty	n.
Mo*ris"co	a.
Mo*ris"co	n.
Mo"risk	n.
Mor"kin	n.
Mor"land	n.
Mor"ling	n.
Mor"mal	n.
Mor"mo	n.
Mor"mon	prop. n.
Mor"mon	prop. n.
Mor"mon	n.
Mor"mon	a.
Mor"mon*dom	n.
Mor"mon*ism	n.
Mor"mon*ite	n.
Morn	n.
Mor"ne	a.
Morne	n.
Mor`n<eacute/"	a.
Morn"ing	n.
Morn"ing	a.
Morn"ing-glo`ry	n.
Morn"ing*tide`	n.
Morn"ward	adv.
Mo"ro	n.
Mo"ro	prop. n.
Mo*roc"can	a.
Mo*roc"co	n.
Mo*rol"o*gy	n.
Mo"ron	n.
Mo*ron"	n.
Mo*rone"	n.
moronic	adj.
Mo"ros	n. pl.
Mo`ro*sau"rus	n.
Mo*rose"	a.
Mo*rose"ly	adv.
Mo*rose"ness	n.
Mo*ro"sis	n.
Mo*ros"i*ty	n.
Mo"ro*soph	n.
Mo*ro"sous	a.
Mo*rox"ite	n.
Mo*rox"y*late	n.
Mor`ox*yl"ic	a.
Mor"phe*an	a.
morph	n.
morph	v. i. & t.
mor"pheme	n.
mor*phem"ic	a.
mor*phem"ics	n.
Mor"pheus	n.
Mor"phew	n.
Mor"phew	v. t.
Mor"phi*a	n.
Mor"phine	n.
morph"ing	n.
mor"phin*ism	n.
mor"pho	n.
mor`pho*gen"e*sis	n.
Mor`pho*log"ic	a.
Mor*phol"o*gist	n.
Mor*phol"o*gy	n.
Mor"phon	n.
Mor*phon"o*my	n.
Mor"pho*phy`ly	n.
Mor*pho"sis	n.
Mor*phot"ic	a.
-mor"phous	n.
Mor"rice	n.
Mor"rice	a.
Mor"ri*cer	n.
Mor"ri*mal	n. & a.
Mor"ris	n.
Mor"ris	n.
Mor"ris-chair`	n.
Mor"ris-pike`	n.
Mor"ro	n.
Mor"rot	n.
Mor"row	n.
Morse	n.
Morse	n.
Morse" al"pha*bet	n.
Mor"sing horn`	n.
Mor"sure	n.
Mort	n.
Mort	n.
Mort	n.
Mort	n.
Mort	n.
Mor"tal	a.
Mor"tal	n.
Mor*tal"i*ty	n.
Mor"tal*ize	v. t.
Mor"tal*ly	adv.
Mor"tal*ness	n.
Mor"tar	n.
Mor"tar	n.
Mor"tar	v. t.
Mor"tar	n.
mortarboard	n.
Mort"gage	n.
Mort"gage	v. t.
mortgaged	adj.
Mort`ga*gee"	n.
Mort"gage*or	n.
Mort"ga*ger	n.
Mor"tif"er*ous	a.
Mor`ti*fi*ca"tion	n.
Mor"ti*fied	imp. & p. p.
mor"ti*fied	a.
Mor"ti*fied*ness	n.
Mor"ti*fi`er	n.
Mor"ti*fy	v. t.
Mor"ti*fy	v. i.
Mor"ti*fy`ing	a.
Mor"ti*fy`ing*ly	adv.
Mor"tise	n.
Mor"tise	v. t.
Mort"ling	n.
Mort"main`	n.
Mort"mal	n.
Mort"pay`	n.
Mor"tress	n.
Mor"tu*a*ry	n.
Mor"tu*a*ry	a.
Mor"u*la	n.
Mor`u*la"tion	n.
Mo"rus	n.
Mor"we	n.
Mor"wen*ing	n.
Mos	n.
Mo*sa"ic	n.
Mo*sa"ic	a.
Mo*sa"ic	prop. a.
Mo*sa"ic*al	a.
Mo*sa"ic*al*ly	adv.
Mo"sa*ism	n.
Mos"a*saur	n.
Mos`a*sau"ri*a	n. pl.
Mos`a*sau"rus	n.
Mos"cha*tel`	n.
Mos"chine	a.
Mos"el	n. & v.
Mo*selle"	n.
Mo"ses	n.
Mo"sey	v. i.
Mosk	n.
Mos"lem	n.
Mos"lem	a.
Mos"lings	n. pl.
Mos`o*sau"rus	n.
Mosque	n.
Mos*qui"to	n.
mosquitofish	n.
Moss	n.
Moss	v. t.
Moss"back`	n.
Moss"bank`er	n.
moss"-grown`	a.
Moss"i*ness	n.
Moss"troop`er	n.
Moss"y	a.
Most	a.
Most	adv.
Mos`ta*hi"ba	n.
Mos"te	imp.
Most-favored-nation clause	n.
Most"ly	adv.
Mos"tra	n.
Most"what`	adv.
Mot	v.
Mot	n.
Mot"a*cil	n.
Mo*ta"tion	n.
Mote	v.
Mote	n.
Mote	n.
Mote	n.
Mot"ed	a.
Mo*tet"	n.
Moth	n.
Moth	n.
moth"ball`	n.
moth"ball`	v. t.
Moth"-eat`	v. t.
Moth"-eat`en	a.
Moth"en	a.
Moth"er	n.
Moth"er	a.
Moth"er	v. t.
Moth"er	n.
Moth"er	v. i.
moth"er	n.
moth"er*board`	n.
Moth"ered	a.
moth"er*fuck`er	n.
Mother Goose	n.
Moth"er*hood	n.
Moth"er*ing	n.
Moth"er-in-law`	n.
Moth"er*land`	n.
Moth"er*less	a.
motherlike	adj.
Moth"er*li*ness	n.
Moth"er*ly	a.
Moth"er*ly	adv.
Moth"er-na`ked	a.
Moth"er-of-pearl`	n.
mother-of-thousands	n.
Moth"er-of-thyme`	n.
Moth"er's Day	n.
Moth"er*y	a.
Moth"y	a.
Mo"tif	n.
Mo*tif"ic	a.
Mo"tile	a.
Mo"tile	n.
Mo*til"i*ty	n.
Mo"tion	n.
Mo"tion	v. i.
Mo"tion	v. t.
motional	adj.
Mo"tion*er	n.
Mo"tion*ist	n.
Mo"tion*less	a.
Mo"tion pic"ture	v. t.
motivated	adj.
motivating	adj.
motivation	n.
Mo"tive	n.
Mo"tive	a.
Mo"tive	v. t.
Mo"tive*less	a.
Mo*tiv"i*ty	n.
Mo*ti"vo	n.
Mot"ley	a.
Mot"ley	n.
mot"ley col*lec"tion	n.
Mot"ley-mind`ed	a.
Mot"mot	n.
Mo"to	n.
Mo"to*graph	n.
Mo"ton	n.
Mo"tor	n.
Mo"tor	a.
motorboat	n.
motorbus	n.
motorcade	n.
Motor car	n.
Mo"tor*bike`	n.
motorcoach	n.
mo"tor*cy`cle	n.
motorcycle	v. i.
motorcycling	n.
mo"tor*cyc`list	n.
mo`tor-driv`en	a.
motored	adj.
Motor generator	n.
Mo"tor*ing	a.
motorisation	n.
Mo"tor*ise	v. t.
motorization	n.
Mo"tor*ize	v. t.
motorized	adj.
motorless	adj.
Mo"tor*man	n.
Mo"tor*mouth	n.
Mo`tor*path"ic	a.
Mo*tor"pa*thy	n.
Motte	n.
Mot"tle	v. t.
Mot"tle	n.
Mot"tled	a.
mottling	n.
Mot"to	n.
Mot"toed	a.
Mot"ty	a.
Mou`choir"	n.
Mou*ez"zin	n.
Mouf"lon	n.
Mought	imp.
Mouil*la"tion	n.
Mouil`l<eacute/"	a.
Mould	n.
Moule	v. i.
Mou*line"	n.
Moult	v. & n.
Moult"en	a.
Moun	v.
Mounch	v. t.
Mound	n.
Mound	n.
Mound	v. t.
moundbird	n.
Mount	n.
Mount	v. i.
Mount	v. t.
Mount	n.
Mount"a*ble	a.
Moun"tain	n.
Moun"tain	a.
Moun`tain*eer"	n.
moun`tain*eer"	v. i.
moun`tain*eer"ing	n.
Moun"tain*er	n.
Moun"tain*et	n.
Moun"tain*ous	a.
Moun"tain*ous*ness	n.
Mount"ance	n.
Moun"tain spec"ter	a.
Mount"e*bank	n.
Mount"e*bank	v. t.
Mount"e*bank	v. i.
Mount"e*bank`er*y	n.
Mount"e*bank`ish	a.
Mount"e*bank*ism	n.
Mount"ed	a.
Mount"e*naunce	n.
Mount"er	n.
Mount"ing	n.
Mount"ing*ly	adv.
Mount"let	n.
Mount"y	n.
Mourn	v. i.
Mourn	v. t.
Mourne	n.
Mourn"er	n.
Mourn"ful	a.
Mourn"ing	n.
Mourn"ing	a.
Mourn"ing*ly	adv.
Mour"ni*val	n.
Mouse	n.
Mouse	v. i.
Mouse	v. t.
Mouse"-ear`	n.
Mouse"fish`	n.
Mouse"hole`	n.
mouse"kin	n.
mouse"ke*teer`	n.
Mous"er	n.
Mouse"tail`	n.
mouse"trap`	n.
Mous"ie	n.
Mous"ing	a.
Mous"ing	n.
Mou"sle	v. t.
Mous`que*taire"	n.
Mousquetaire cuff	n.
Mousse`line"	n.
Mousse`line de soie"	n.
moustachio	n.
Mous"y	a.
Mou"tan	n.
Mouth	n.
Mouth	v. t.
Mouth	v. i.
Mouthed	a.
Mouth"er	n.
Mouth"-foot`ed	a.
Mouth"ful	n.
Mouth"less	a.
Mouth"-made`	a.
Mouth"piece`	n.
mouthwash	n.
mouton	n.
Mov`a*bil"i*ty	n.
Mov"a*ble	a.
Mov"a*ble	n.
Mov"a*ble*ness	n.
Mov"a*bly	adv.
Move	v. t.
Move	v. i.
Move	n.
moveable	adj.
moved	pred. adj.
Move`less	a.
Move"ment	n.
Mo"vent	a.
Mo"vent	n.
Mov"er	n.
Mov"ie	n.
Mov"ing	a.
Mov"ing	n.
Mov"ing*ly	adv.
Mov"ing*ness	n.
Moving picture	n.
Mow	v. i.
Mow	n.
Mow	v.
Mow	v. t.
Mow	v. i.
Mow	n.
Mow	v. t.
Mow"burn`	v. i.
Mowe	v.
Mowe	n. & v.
Mow"er	n.
Mow"ing	n.
Mown	p. p. & a.
Mow"yer	n.
Mox"a	n.
Mox"ie	n.
Moy"a	n.
Moyle	n. & v.
Moz"a*rab	n.
Mr.	n.
MSB	n.
MSG	n.
MST	n.
MT	n.
mu	n.
mu'adhdhin	n.
muazzin	n.
Mu*cam"ide	n.
Mu"cate	n.
Muce	n.
Mu*ce"din	n.
Much	a.
Much	n.
Much	adv.
Much"el	a.
Much"ness	n.
Much"what`	adv.
Mu"cic	a.
Mu"cid	a.
Mu*cif"ic	a.
Mu"ci*form	a.
Mu"ci*gen	n.
Mu*cig"e*nous	a.
Mu"ci*lage	n.
Mu`ci*lag"i*nous	a.
Mu"cin	n.
Mu*cin"o*gen	n.
Mu*cip"a*rous	a.
Mu"ci*vore	n.
Muck	adv.
Muck	n.
muck	a.
muck	v. t.
muck	v. i. & t.
Muck"en*der	n.
Muck"er	n.
muck"er	n.
Muck"er	v. t.
Muck"er*er	n.
Muck"i*ness	n.
Muc"kle	a.
Muck"mid`den	n.
muck" pile`	n.
Muck" rake`	v. i.
muck"rake`	v. i.
muck"rak`er	n.
Muck"sy	a.
Muck"worm`	n.
Muck"y	a.
Mu"co*cele	n.
Mu"coid	a.
Mu"coid	n.
Mu"co*nate	n.
Mu*con"ic	a.
Mu`co*pu"ru*lent	a.
Mu"cor	prop. n.
Mucorales	prop. n.
mucosa	n.
Mu*cos"i*ty	n.
Mu"cous	a.
Mu"cous*ness	n.
Mu"cro	n.
Mu"cro*nate	a.
Mu*cron"u*late	a.
Mu"cu*lent	a.
Mu"cus	n.
Mu"cus*in	n.
Mud	n.
Mud	v. t.
Mu"dar	n.
Mu"da*rin	n.
mudcat	n.
mud"-daub`er	n.
mud"-crab`	n.
Mud"di*ly	adv.
Mud"der	n.
Mud"di*ness	n.
Mud"dle	v. t.
Mud"dle	v. i.
Mud"dle	n.
Mud"dle*head`	n.
Mud"dler	n.
Mud"dy	a.
Mud"dy	v. t.
Mud"dy-head`ed	a.
Mud"dy-met`tled	a.
Mud"fish`	n.
Mud"hole`	n.
Mu"dir	n.
Mud"sill`	n.
Mud"suck`er	n.
Mud"wall`	n.
Mud"wort`	n.
Mue	v. i.
mues"li	n.
mu*ez"zin	n.
Muff	n.
Muff	v. t.
Muf`fe*tee"	n.
Muf"fin	n.
Muf`fin*eer"	n.
Muff"ish	a.
Muf"fle	n.
Muf"fle	v. t.
Muf"fle	v. i.
Muf"fle	n.
muffled	adj.
Muf"fler	n.
Muf"lon	n.
Muf"ti	n.
muf"ti	n.
Mug	n.
mug	v. t.
mugful	n.
Mug"gard	a.
Mug"ger	n.
mugger	n.
Mug"get	n.
Mug"gi*ness	n.
Mug"ging	n.
Mug"gins	n.
Mug"gins	v. t.
Mug"gish	a.
Mug`gle*to"ni*an	n.
Mug"gy	a.
Mug"house`	n.
Mu"gi*en*cy	n.
Mu"gi*ent	a.
Mu"gil	prop. n.
Mugilidae	prop. n.
Mugiloidea	prop. n.
Mu"gi*loid	a.
Mug"weed`	n.
Mug"wort`	n.
mug"wump`	n.
Mug"wump`er*y	n.
Mu*ham"mad*an	a.
Mu*ham"mad*an	n.
Mu*ham"mad*an*ism	n.
Muharram	n.
muishond	n.
mujik	n.
Mu*la"da	n.
Mu*la"da	n.
Mu*lat"to	n.
Mu*lat"tress	n.
Mul"ber*ry	n.
Mul"ber*ry-faced`	a.
Mulch	n.
Mulch	v. t.
Mulct	n.
Mulct	v. t.
Mulc"ta*ry	a.
Mule	n.
Mule"-jen`ny	n.
Mule killer	n.
Mule"wort`	n.
Mu"ley	n.
Mul"ey	n.
Mu`li*eb"ri*ty	n.
Mu"li*er	n.
Mu"li*er*ly	adv.
Mu"li*er*ose`	a.
Mu`li*er*os"i*ty	n.
Mu"li*er*ty	n.
Mul"ish	a.
Mull	n.
Mull	n.
Mull	n.
Mull	v. t.
Mull	v. i.
Mull	n.
Mull	v. t.
Mul"la	n.
Mul`la*ga*taw"ny	n.
Mul"lah	n.
Mul"lar	n.
Mul"lein	n.
Mul"len	n.
Mull"er	n.
Mull"er	n.
M<uum/l*le"ri*an	prop. a.
Mul"let	n.
Mul"let	n.
Mul"let	n.
Mul"ley	n.
Mul"ley	a.
mulligan	n.
Mul`li*ga*taw"ny	n.
Mul"li*grubs	n.
Mul"lin*gong	n.
Mul"lion	n.
Mul"lion	v. t.
Mul"lock	n.
Mul"loid	a.
mull over	v. t.
Mul"mul	n.
Mulse	n.
Mult-	a.
Mul*tan"i*mous	a.
Mul`tar*tic"u*late	a.
Mul*te"i*ty	n.
Mul"ti-	a.
Mul`ti*cap"su*lar	a.
Mul`ti*car"i*nate	a.
Mul`ti*ca"vous	a.
Mul`ti*cel"lu*lar	a.
Mul`ti*cen"tral	a.
Mul`ti*cip"i*tal	a.
Mul"ti*col`or	a.
Mul`ti*cos"tate	a.
Mul`ti*cus"pid	a.
Mul`ti*cus"pi*date	a.
Mul`ti*den"tate	a.
Mul`ti*dig"i*tate	a.
Mul"ti*faced`	a.
Mul`ti*fa"ri*ous	a.
Mul`ti*fa"ri*ous*ly	adv.
Mul`ti*fa"ri*ous*ness	n.
Mul*tif"er*ous	a.
Mul"ti*fid	a.
Mul`ti*flo"rous	a.
Mul"ti*flue	a.
Mul"ti*foil	n.
Mul"ti*foil	a.
Mul"ti*fold	a.
Mul"ti*form	a.
Mul`ti*form"i*ty	n.
Mul`ti*form"ous	a.
Mul`ti*gen"er*ous	a.
Mul`ti*gran"u*late	a.
Mul"ti*graph	n.
Mul*tij"u*gate	a.
Mul*tij"u*gous	a.
Mul`ti*lat"er*al	a.
Mul`ti*lin"e*al	a.
Mul`ti*lo"bar	a.
Mul`ti*loc"u*lar	a.
Mul*til"o*quence	n.
Mul*til"o*quent	a.
Mul*til"o*quy	n.
Mul`ti*no"date	a.
Mul`ti*no"dous	a.
Mul`ti*no"mi*al	n. & a.
Mul`ti*nom"i*nal	a.
mul`ti*nom"i*nal	n.
Mul`ti*nu"cle*ar	a.
Mul`ti*nu"cle*ate	a.
Mul*tip"a*rous	a.
Mul*tip"ar*tite	a.
Mul"ti*ped	n.
Mul"ti*ped	a.
Mul"ti*phase	a.
Mul"ti*plane	a.
Mul"ti*plane	n.
Mul"ti*ple	a.
Mul"ti*ple	n.
Mul"ti*plex	a.
Mul"ti*pli`a*ble	a.
Mul"ti*pli*ca*ble	a.
Mul"ti*pli*cand`	n.
Mul"ti*pli*cate	a.
Mul`ti*pli*ca"tion	n.
Mul"ti*pli*ca*tive	a.
Mul"ti*pli*ca*tive*ly	adv.
Mul"ti*pli*ca`tor	n.
Mul`ti*pli"cious	a.
Mul`ti*plic"ity	n.
Mul"ti*pli`er	n.
Mul"ti*ply	v. t.
Mul"ti*ply	v. i.
Mul`ti*po"lar	a.
Mul*tip"o*tent	a.
Mul`ti*pres"ence	n.
Mul`ti*pres"ent	a.
Mul`ti*ra"di*ate	a.
Mul`ti*ram"i*fied	a.
Mul`ti*ra*mose"	a.
Mul*tis"cious	a.
Mul"ti*sect	a.
Mul`ti*sep"tate	a.
Mul`ti*se"ri*al	a.
Mul`ti*sil"i*quous	a.
Mul*tis"o*nous	a.
Mul`ti*spi"ral	a.
Mul`ti*stri"ate	a.
Mul`ti*sul"cate	a.
Mul"ti*syl`la*ble	n.
Mul`ti*tit"u*lar	a.
Mul`ti*tu"bu*lar	a.
Mul"ti*tude	n.
Mul`ti*tu"di*na*ry	a.
Mul`ti*tu"di*nous	a.
Mul*tiv"a*gant	a.
Mul*tiv"a*lence	n.
Mul*tiv"a*lent	a.
Mul"ti*valve	n.
Mul"ti*valve	a.
Mul*tiv"er*sant	a.
Mul*tiv"i*ous	a. & adv.
Mul*tiv"o*cal	a.
Mul*toc"u*lar	a.
Mul"tum	n.
Mul*tun"gu*late	a.
Mul"ture	n.
Mum	a.
Mum	interj.
Mum	n.
Mum	n.
Mum"ble	v. t.
Mum"ble	v. t.
Mum"ble*dy peg`	n.
Mum"ble*news`	n.
Mum"bler	n.
Mum"bling	a.
Mum"bo Jum"bo	n.
Mum"-chance`	n.
Mum"-chance`	a.
mu-meson	n.
Mumm	v. i.
Mumm"er	n.
Mum"mer*y	n.
Mum"mi*chog	n.
Mum`mi*fi*ca"tion	n.
Mum"mi*fied	a.
Mum"mi*form	a.
Mum"mi*fy	v. t.
mum"mi*fy	v. i.
Mum"my	n.
Mum"my	v. t.
Mum"my*chog	n.
Mump	v. i.
Mump	v. t.
Mump"er	n.
Mump"ish	a.
Mumps	n.
Mun	n.
Munch	v. t. & i.
Mun*chau"sen*ism	n.
Munch"er	n.
Mund	n.
Mun"dane	a.
Mun*dan"i*ty	n.
Mun*da"tion	n.
Mun"da*to*ry	a.
Mun"dic	n.
Mun*dif"i*cant	a.
Mun`di*fi*ca"tion	n.
Mun*dif"i*ca*tive	a.
Mun"di*fy	v. t.
Mun"dil	n.
Mun*div"a*gant	a.
Mun*dun"gus	n.
Mu"ner*a*ry	a.
Mu"ner*ate	v. t.
Mu`ner*a"tion	n.
Mung	n.
Mung" bean`	n.
Mun"ga	n.
Mung"corn`	n.
Mun"go	n.
Mun"goose	n.
Mun"grel	n. & a.
Mu*nic"i*pal	a.
Mu*nic"i*pal*ism	n.
Mu*nic`i*pal"i*ty	n.
Mu*nic"i*pal*ize	v. t.
Mu*nic"i*pal*ly	adv.
Mu*nif"ic	a.
Mu*nif"i*cate	v. t.
Mu*nif"i*cence	n.
Mu*nif"i*cence	n.
Mu*nif"i*cent	a.
Mu"ni*fy	v. t. & i.
Mu"ni*ment	n.
Mu*nite"	v. t.
Mu*ni"tion	n.
Mu"ni*ty	n.
munj	n.
Mun*jeet"	n.
Mun"jis*tin	n.
Mun"nion	n.
Mun"tin	n.
Munt"jac	n.
Muntz" met`al	n.
Mu*rae"noid	a.
Mu"rage	n.
Mu"ral	a.
Mur"der	n.
Mur"der	v. t.
murdered	adj.
Mur"der*er	n.
Mur"der*ess	n.
Mur"der*ment	n.
Mur"der*ous	a.
Mur"dress	n.
Mure	n.
Mure	v. t.
Mu"ren*ger	n.
Mu"rex	prop. n.
Mu*rex"an	n.
Mu*rex"ide	n.
Mu*rex"o*<ium/n	n.
Mu"ri*ate	n.
Mu"ri*a`ted	a.
Mu`ri*at"ic	a.
Mu`ri*a*tif"er*ous	a.
Mu"ri*cate	a.
Mu"ri*coid	a.
Mu*ric"u*late	a.
Mu"ride	n.
Mu"ri*form	a.
Mu"rine	a.
Mu"rine	n.
Mu"rin*ger	n.
Murk	a.
Murk	n.
Murk	n.
Murk"i*ly	adv.
Murk"i*ness	n.
Murk"y	a.
Mur"lins	n.
Mur"mur	n.
Mur"mur	v. i.
Mur"mur	v. t.
Mur`mur*a"tion	n.
Mur"mur*er	n.
Mur"mur*ing	a. & n.
Mur"mur*ous	a.
Mur"ni*val	n.
Mur"phy	n.
Murr	n.
Mur"rain	n.
Mur"rain	a.
Mur"ray*in	n.
Murre	n.
Murre"let	n.
Mur"rey	n.
Mur"rhine	a.
Mur"ri*on	a.
Mur"ri*on	n.
Mur"ry	n.
Murth	n.
Mur"ther	n. & v.
Mur"ther*er	n.
Mur"za	n.
Mus	prop. n.
Mu"sa	prop. n.
Musaceae	prop. n.
Mu*sa"ceous	a.
Mus"al	a.
Musales	prop. n.
Mu*sang"	n.
Mu"sar	n.
Mu"sard	n.
Mus"ca	prop. n.
Mus"ca*del`	n.
Muscadet	n.
Mus"ca*dine	n.
Mus*ca"les	n. pl.
Mus"cal*longe	n.
Mus"car*din	n.
Mus`car*dine"	n.
Mus*car"i*form	a.
Mus*ca"rin	n.
Mus"cat	n.
Mus"ca*tel`	a.
Mus"ca*tel`	n.
Musch"el*kalk`	n.
Mus"ci	n. pl.
Muscicapidae	prop. n.
Mus*cic"a*pine	a.
Mus"cid	n.
Muscidae	prop. n.
Mus"ci*form	a.
Mus"ci*form	a.
Muscivora-forficata	n.
Mus"cle	n.
mus"cle	v. t.
musclebuilder	n.
musclebuilding	n.
Mus"cled	a.
muscleman	n.
Mus"cle read`ing	n.
Mus*co"gees	n. pl.
Mus"coid	a.
Mus"coid	n.
Muscoidea	prop. n.
Mus*col"o*gy	n.
Mus*cos"i*ty	n.
Mus`co*va"do	a.
Mus`co*va"do	n.
Mus"co*vite	n.
Mus"co*vy duck`	a.
Mus`cu*lar"i*ty	n.
Mus"cu*lar*ize	v. t.
Mus"cu*lar*ly	adv.
Mus`cu*la"tion	n.
Mus"cu*la*ture	n.
Mus"cule	n.
Mus"cu*lin	n.
Mus`cu*lo*cu*ta"ne*ous	a.
Mus`cu*lo*phren"ic	a.
Mus`cu*los"i*ty	n.
Mus`cu*lo*spi"ral	a.
Mus"cu*lous	a.
Muse	n.
Muse	n.
Muse	v. i.
Muse	v. t.
Muse	n.
Muse"ful	a.
Muse"less	a.
Mus"er	n.
Mu"set	n.
Mu*sette"	n.
Mu*se"um	n.
Mush	n.
Mush	v. t.
Mush	n.
Mush	v. i.
Mush"room	n.
Mush"room	a.
mush"room	v. i.
Mush"room-head`ed	a.
Mush"y	a.
Mu"sic	n.
Mu"sic*al	a.
Mu"sic*al	n.
Mu`si`cale"	n.
Mu"sic*al*ly	adv.
Mu"sic*al*ness	n.
Mu"sic dra`ma	n.
Mu`si*co*ma"ni*a	n.
Mus"i*mon	n.
musing	adj.
Mus"ing*ly	adv.
Mu"sit	n.
Musk	n.
Musk	v. t.
Mus"ka*del`	n.
Mus"kat	n.
Mus"kel*lunge	n.
Mus"ket	n.
Mus`ket*eer"	n.
Mus*ke"to	n.
Mus`ket*oon"	n.
Mus"ket*ry	n.
Musk"i*ness	n.
Musk"mel`on	n.
Mus*ko"gees	n. pl.
Musk"rat`	n.
Musk"wood`	n.
Musk"y	a.
musk"y	n.
Mus"lim	n. & a.
Mus"lin	n.
Mus`lin*et"	n.
Mus"mon	n.
Mu`so*ma"ni*a	n.
Mus"quash	n.
Mus"quaw	n.
Mus"quet	n.
Mus*qui"to	n.
Mus"role	n.
Muss	n.
Muss	n.
Muss	v. t.
Muss	n.
Mus"sel	n.
Mus`si*ta"tion	n.
Mus"site	n.
Mus"sul*man	n.
Mus`sul*man"ic	a.
Mus"sul*man*ish	a.
Mus"sul*man*ism	n.
Mus"sul*man*ly	adv.
Muss"y	a.
Must	v. i. <or/ auxiliary
Must	n.
Must	v. t. & i.
must	a.
Mus"tac	n.
Mus*tache"	n.
Mus*ta"chio	n.
mus*ta"chioed	a.
Mus`tah"fiz`	n.
Mus`ta*i"ba	n.
Mus"tang	n.
Mus"tard	n.
Mus*tee"	n.
Mustela	prop. n.
mustelid	n.
Mustelidae	prop. n.
Mus"te*line	a.
Mustelus	prop. n.
Mus"ter	n.
Mus"ter	v. t.
Mus"ter	v. i.
Mus"ti*ly	a.
Mus"ti*ness	n.
Mus"ty	a.
Mu`ta*bil"i*ty	n.
Mu"ta*ble	a.
Mu"ta*ble*ness	n.
Mu"ta*bly	adv.
Mu"ta*cism	n.
Mu"tage	n.
mu"ta*gen	n.
mu`ta*gen"e*sis	n.
mu`ta*gen*i"ci*ty	n.
mu*tan"dum	n.
mu*ta"tion	n.
mutative	adj.
Mutch	n.
Mutch"kin	n.
Mute	v. t.
Mute	v. t. & i.
Mute	n.
Mute	a.
Mute	n.
muted	adj.
Mute"-hill`	n.
Mute"ly	adv.
Mute"ness	n.
Mu*tes`sa*rif"	n.
Mu*tes`sa*ri*fat"	n.
Mu"tic	a.
Mu"ti*late	a.
Mu"ti*late	n.
Mu"ti*late	v. t.
mutilated	adj.
Mu`ti*la"tion	n.
Mu"ti*la"tor	n.
Mu"ti*lous	a.
Mu"tine	n.
Mu"tine	v. i.
Mu"ti*neer`	n.
Mut"ing	n.
Mu"ti*nous	a.
Mu"ti*ny	n.
Mu"ti*ny	v. i.
Mut"ism	n.
Mu"to*scope	n.
mutt	n.
Mut"ter	v. i.
Mut"ter	v. t.
Mut"ter	n.
Mut"ter*er	n.
Mut"ter*ing*ly	adv.
Mut"ton	n.
muttonfish	n.
muttonhead	n.
Mut"ton*y	a.
Mu"tu*al	a.
Mu"tu*al*ism	n.
mutualist	adj.
Mu`tu*al"i*ty	n.
Mu"tu*al*ly	adv.
mutual savings bank	n.
Mu"tu*a*ry	n.
Mu`tu*a"tion	n.
Mu"tule	n.
Mux	n.
Mux	v. t.
Mux"y	a.
Muz"a*rab	n.
Muz`a*rab"ic	a.
muzjik	n.
Muz"zi*ness	n.
Muz"zle	n.
Muz"zle	v. t.
Muz"zle	v. i.
Muz"zle-load`er	n.
Muz"zle-load`ing	a.
Muz"zy	a.
MVP	n.
Mx	prop. n.
My	a. & poss. pron.
My"a	prop. n.
Myaceae	prop. n.
Myacidae	prop. n.
Myadestes	prop. n.
My*al"gi*a	n.
My*all" wood`	n. pl.
My*ce"li*um	n.
Myc"e*loid	a.
My*ce"tes	n.
Myc"e*toid	n. pl.
mycobacteria	n. pl.
mycobacterium	n.
my`co*der"ma	n.
My`co*log"ic	a.
My*col"o*gist	n.
My*col"o*gy	n.
My`co*mel"ic	a.
My`co*pro"te*in	n.
My"cose	n.
Myc"o*thrix	n.
Mycteria	prop. n.
My*da"le*ine	n.
Myd`a*tox"in	n.
Myd"a*us	n.
My*dri"a*sis	n.
Myd`ri*at"ic	a.
My`e*len*ceph"a*la	n. pl.
My`e*len`ce*phal"ic	a.
My`e*len*ceph"a*lon	n.
My`e*len*ceph"a*lous	a.
my"e*lin	n.
myelinic	adj.
My`e*li"tis	n.
My"e*lo*coele`	n.
myelofibrosis	n.
My`e*lo*gen"ic	a.
My"e*loid	a.
My`e*loid"in	n.
My"e*lon	n.
My"e*lo`nal	a.
My`e*lo*neu"ra	n. pl.
My*el"o*plax	n.
Myg"a*le	prop. n.
My"kiss	n.
Mylitta	prop. n.
Myl"o*don	n.
Mylodontidae	n.
My`lo*hy"oid	a.
my"na	n.
Myn"chen	n.
Myn"cher*y	n.
Myn*heer"	n.
my"o-	adj.
my`o*car*di"tis	n.
My`o*car"di*um	n.
My"o*chrome	n.
My`o*com"ma	n.
My`o*dy*nam"ics	n.
My`o*dy*na`mi*om"e*ter	n.
My`o*dy`na*mom"e*ter	n.
My`o*ep`i*the"li*al	a.
My*og"a*lid	n.
My"o*gram	n.
My"o*graph	n.
My`o*graph"ic	a.
My*og"ra*phy	n.
My`o*haem"a*tin	n.
My"oid	a.
My`o*lem"ma	n.
My"o*lin	n.
My`o*log"ic	a.
My*ol"o*gist	n.
My*ol"o*gy	n.
My*o"ma	n.
My"o*man`cy	n.
My"o*morph	n.
My`o*mor"pha	n. pl.
My`o*pa*thi"a	n.
My`o*path"ic	a.
My*op"a*thy	n.
My"ope	n.
My"o*phan	n.
My*o"pi*a	n.
My*op"ic	a.
My"ops	n.
My*op"sis	n.
My"o*py	n.
My"o*sin	n.
My*o"sis	n.
My`o*sit"ic	a.
My`o*si"tis	n.
My`o*so"tis	prop. n.
My*ot"ic	a.
My"o*tome	n.
My`o*tom"ic	a.
My*ot"o*my	n.
Myr"ci*a	n.
Myr"i*a-	a.
Myr"i*ad	n.
Myr"i*ad	a.
Myr"i*a*gram	n.
Myr"i*a*li`ter	n.
Myr"i*a*me`ter	n.
Myr"i*a*pod	n.
Myr`i*ap"o*da	n. pl.
Myr"i*arch	n.
Myr"i*are	n.
My*ri"ca	prop. n.
Myr"i*cin	n.
Myr"i*cyl	n.
Myr`i*o*log"ic*al	a.
Myr`i*ol"o*gist	n.
Myr"i*o*logue	n.
Myr`i*oph"yl*lous	a.
Myr`i*op"o*da	n. pl.
Myr`i*o*ra"ma	n.
Myr"i*o*scope	n.
My*ris"tate	n.
My*ris"tic	a.
My*ris"tin	n.
My*ris"tone	n.
Myrmecophaga	prop. n.
Myrmecophagidae	prop. n.
myrmecophagous	adj.
myrmecophile	n.
myrmecophilous	adj.
Myr"me*co*phyte`	n.
myrmecophytic	adj.
Myrmeleon	prop. n.
Myrmeleontidae	prop. n.
Myr"mi*cine	a.
Myr"mi*don	n.
Myr`mi*do"ni*an	a.
Myr`mo*the"rine	a.
My*rob"a*lan	n.
My*ron"ic	a.
My*rop"o*list	n.
Myr"o*sin	n.
My*rox"y*lon	prop. n.
Myrrh	n.
Myr"rhic	a.
Myr"rhine	a.
Myrtaceae	prop. n.
Myr*ta"ceous	a.
Myrtales	prop. n.
Myr"ti*form	a.
Myrtillocactus	prop. n.
Myr"tle	n.
Myrtus	prop. n.
My*self"	pron.
My*selv"en	pron.
Mysidacea	prop. n.
Mysidae	prop. n.
My"sis	prop. n.
Mys"ta*cal	a.
Mys`ta*gog"ic	a.
Mys"ta*gogue	n.
Mys"ta*go`gy	n.
Mys*te"ri*al	a.
Mys*te"ri*arch	n.
Mys*te"ri*ous	a.
Mys*te"ri*ous*ly	adv.
Mys*te"ri*ous*ness	n.
Mys"ter*ize	v. t.
Mys"ter*y	n.
Mys"ter*y	n.
Mys"tic	a.
Mys"tic	n.
Mys"ti*cete	n.
Mysticeti	prop. n.
Mys"ti*cism	n.
Mys`ti*fi*ca"tion	n.
Mys"ti*fi*ca`tor	n.
Mys"ti*fy	v. t.
mystique	n.
My"ta*cism	n.
Myth	n.
Mythe	n.
Myth"ic	a.
My*thog"ra*pher	n.
My*thol"o*ger	n.
Myth`o*lo"gi*an	n.
Myth`o*log"ic	a.
mythologisation	n.
My*thol"o*gist	n.
mythologization	n.
My*thol"o*gize	v. i.
My*thol"o*gi`zer	n.
Myth"o*logue	n.
My*thol"o*gy	n.
Myth"o*plasm	n.
Myth`o*poe"ic	a.
Myth`o*po*et"ic	a.
Myt"i*loid	a.
Myt`i*lo*tox"ine	n.
Myt"i*lus	n.
Myx"a	n.
myxedema	n.
Myx"ine	prop. n.
Myx"i*noid	a.
Myxinoidei	prop. n.
Myxobacter	prop. n.
myxobacterium	n.
Myxobacteriaceae	prop. n.
Myxocephalus	prop. n.
Myx`o*cys*to"de*a	n. pl.
Myx`oe*de"ma	n.
Myx*o"ma	n.
myxomatosis	n.
myxomycete	n.
Myx`o*my*ce"tes	n. pl.
Myxomycota	n.
Myxophyceae	prop. n.
Myx*oph"y*ta	n. pl.
Myx"o*pod	n.
Myxosporidia	prop. n.
myxosporidian	n.
My*zon"tes	n. pl.
My`zo*stom"a*ta	prop. n. pl.
