H	v. t.
H	n.
Ha	interj.
Haaf	n.
Haak	n.
Haar	n.
Ha"be*as cor"pus	n.
Hab"er*dash	v. i.
Hab"er*dash`er	n.
Hab"er*dash`er*y	n.
Hab`er*dine"	n.
Ha*ber"ge*on	n.
Habenaria	prop. n.
Hab"i*la*to*ry	a.
Hab"ile	a.
Ha*bil"i*ment	n.
Ha*bil"i*ment*ed	a.
Ha*bil"i*tate	a.
Ha*bil"i*tate	v. t.
Ha*bil`i*ta"tion	n.
Ha*bil"i*ty	n.
Hab"it	n.
Hab"it	v. t.
Hab`it*a*bil"i*ty	n.
Hab"it*a*ble	a.
Hab"it*a*cle	n.
Ha`bi`tan"	n.
Hab"it*ance	n.
Hab"it*an*cy	n.
Hab"it*ant	n.
Hab"i*tat	n.
Hab`i*ta"tion	n.
Hab"i*ta`tor	n.
Hab"it*ed	p. p. & a.
Ha*bit"ual	a.
Ha*bit"u*ate	v. t.
Ha*bit"u*ate	a.
Ha*bit`u*a"tion	n.
Hab"i*tude	n.
Ha`bi`tu`<eacute/"	n.
Hab"i*ture	n.
Hab"i*tus	n.
Ha"ble	a.
Hab"nab	adv.
Hach"ure	n.
Ha`ci*en"da	n.
Hack	n.
Hack	v. t.
Hack	v. t.
Hack	v. i.
Hack	n.
Hack	n.
Hack	v. i.
Hack	a.
Hack	v. t.
Hack	v. i.
Hack"a*more	n.
Hack"ber`ry	n.
Hack"bolt`	n.
Hack"buss	n.
Hack"ee	n.
Hackelia	prop. n.
hack"er	n.
hack"er*y	n.
hack"ie	n.
hac"kle	n.
Hac"kle	v. t.
Hac"kly	a.
Hack"man	n.
Hack"ma*tack`	n.
Hack"ney	n.
Hack"ney	a.
Hack"ney	v. t.
Hack"ney*man	n.
Hack"ster	n.
Hac"que*ton	n.
Had	imp. & p. p.
Had"der	n.
Had"die	n.
Had"dock	n.
Hade	n.
Hade	v. i.
Ha"des	n.
Hadj	n.
Hadj"i	n.
hadron	n.
hadrosaur	n.
Hadrosauridae	prop. n.
Had`ro*sau"rus	n.
Haec*ce"i*ty	n.
Haem`a*cy"a*nin	n.
Haem`a*cy*tom"e*ter	n.
Hae"mad	adv.
Haem`a*drom"e*ter	n.
Haem`a*drom"e*try	n.
Haem`a*drom"o*graph	n.
Hae`ma*dy*nam"e*ter	n.
Hae"mal	a.
Haem`a*phae"in	n.
Haem"a*pod	n.
Hae*map"o*dous	a.
Haem`a*poi*et"ic	a.
Haem`a*poph"y*sis	n.
Haem`a*stat"ics	n.
Haem`a*ta*chom"e*ter	n.
Haem`a*ta*chom"e*try	n.
Haem`a*tem"e*sis	n.
Hae*mat"ic	a.
Haem"a*tin	n.
Haem`a*ti*nom"e*ter	n.
Haem`a*tin`o*met"ric	a.
Haem"a*tite	n.
Haem`a*tit"ic	a.
Haem"a*to-	prefix.
Haem"a*to*blast	n.
Haem`a*toc"ry*a	n. pl.
Haem`a*toc"ry*al	a.
Haem`a*to*crys"tal*lin	n.
Hae`ma*to*dy`na*mom"e*ter	n.
Haem`a*to*gen"e*sis	n.
Haem`a*to*gen"ic	a.
Haem`a*tog"e*nous	a.
Haem`a*to*glob"u*lin	n.
Haem"a*toid	a.
Haem`a*toid"in	n.
Hae*mat"o*in	n.
Hae*mat"o*lin	n.
Haem`a*tol"o*gy	n.
Haem`a*tol"y*sis	n.
Haem`a*tom"e*ter	n.
Haem`a*to*phi*li"na	n. pl.
Haem"a*to*plast`	n.
Haem`a*to*plas"tic	a.
Haem`a*to*por"phy*rin	n.
Haem"a*to*sac`	n.
Haem"a*to*scope`	n.
Haem`a*to"sin	n.
Haem`a*to"sis	n.
Haem`a*to*ther"ma	n. pl.
Haem`a*to*ther"mal	a.
Haem`a*to*tho"rax	n.
Haem`a*tox"y*lin	n.
Haem`a*tox"y*lon	n.
Haem`a*to*zo"on	n.
Hae"mic	a.
Hae"min	n.
Haem"o-	prefix.
Haem"o*chrome	n.
Haem`o*chro"mo*gen	n.
Haem`o*chro*mom"e*ter	n.
Haem`o*cy"a*nin	n.
Haem`o*cy*tol"y*sis	n.
Haem`o*cy*tom"e*ter	n.
Haem`o*cy`to*tryp"sis	n.
Haem`o*drom"o*graph	n.
Haem`o*dro*mom"e*ter	n.
Hae`mo*dy*nam"e*ter	n.
Haem`o*glo"bin	n.
Haem`o*glo`bin*om"e*ter	n.
Hae"mol	n.
Haem`o*lu"te*in	n.
Hae*mol"y*sis	n.
Haem`o*ma*nom"e*ter	n.
Hae*mom"e*ter	n.
Hae"mo*ny	n.
Hae`mo*plas"tic	a.
Haem"or*rhoid"al	a.
Haem"o*scope	n.
Haem`o*stat"ic	a.
Haem`o*ta*chom"e*ter	n.
Haem`o*ta*chom"e*try	n.
Haf	imp.
Haf"fle	v. i.
haf"ni*um	n.
Haft	n.
Haft	v. t.
Haft"er	n.
Hag	n.
Hag	v. t.
Hag	n.
Hag"ber`ry	n.
Hag"born`	a.
Hag"but	n.
Hag"but*ter	n.
Hag"don	n.
Hag"fish`	n.
Hag*ga"da	n.
Hag"gard	a.
Hag"gard	n.
Hag"gard	n.
Hag"gard*ly	adv.
Hag"ged	a.
Hag"gis	n.
Hag"gish	a.
Hag"gish*ly	adv.
Hag"gle	v. t.
Hag"gle	v. i.
Hag"gle	n.
Hag"gler	n.
Ha"gi*ar`chy	n.
Ha`gi*oc"ra*cy	n.
Ha`gi*og"ra*pha	n. pl.
Ha`gi*og"ra*phal	n.
ha`gi*o*graph"ic	n.
Ha`gi*ol"a*try	n.
Ha`gi*ol"o*gist	n.
Ha`gi*ol"o*gy	n.
Ha"gi*o*scope`	n.
hag"-rid`den	a.
Hag"seed`	n.
Hag"ship	n.
Hag"-ta`per	n.
Hague"but	n.
Hague Tribunal	interj.
Ha-ha"	n.
Hai"ding*er*ite	n.
Hai"duck	n.
Haik	n.
Hai"kal	n.
Hai"kwan"	n.
Haikwan tael	n.
Hail	v. i.
Hail	v. t.
Hail	a.
Hail	v. t.
Hail	v. i.
Hail	interj.
Hail	n.
Hail"-fel`low	n.
Hailse	v. t.
Hail"shot`	n. pl.
Hail"stone`	n.
Hail"storm`	n.
Hail"y	a.
Hain	v. t.
Hain't	n.
hair"ball`	n.
Hair"bell`	n.
Hair"bird`	n.
Hair"brained`	a.
Hair"breadth`	a.
Hair"-brown`	a.
Hair"brush`	n.
Hair"cloth`	n.
Hair"dress`er	n.
hairdressing	n.
Haired	a.
Hai"ren	a.
Hair" grass`	n.
Hair"less	a.
hairlike	adj.
hairline	n.
hair"net`	n.
hair"piece`	n.
Hair"pin`	n.
Hair"-salt`	n.
Hair"split`ter	n.
Hair"split`ting	a.
Hair"spring`	n.
Hair"streak`	n.
Hair"tail`	n.
Hair" worm`	a.
Haiti	n.
Hai"ti*an	a. & n.
haj	n.
haj"i	n.
Ha"je	n.
Hake	n.
Hake	n.
Hake	v. i.
Hake's"-dame`	n.
Hak"e*ton	n.
Ha*kim"	n.
Ha"kim	n.
Hal	prop. n.
HAL	prop. n.
Ha*la"cha	n.
Ha*la"tion	n.
Hal"berd	n.
Hal`berd*ier"	n.
Hal"berd-shaped`	a.
Hal"cy*on	n.
Hal"cy*on	a.
Hal`cy*o"ni*an	a.
Hal"cy*o*noid	a. & n.
Hale	a.
Hale	n.
Hale	v. t.
Halenia	n.
Ha*le"si*a	n.
Half	a.
Half	adv.
Half	n.
Half	v. t.
Half`-and-half"	n.
halfback	n.
half-baked	a.
Half"beak`	n.
Half" blood`	n.
Half"-blood`ed	a.
Half"-boot`	n.
Half"-bound`	n.
Half"-bred`	a.
Half"-breed`	a.
Half"-breed`	n.
Half"-broth`er	n.
Half"-caste`	n.
Half"-clammed`	a.
Half"cock`	v. t.
Half"-cracked`	a.
Half"-deck`	n.
Half"-decked`	a.
Half"en	a.
Half"en*deal`	adv.
Half"er	n.
Half"-faced`	a.
Half"-fish`	n.
Half"-hatched`	a.
Half"-heard`	a.
half"heart`ed	a.
half-holiday	n.
Half"-hour`ly	a.
Half"-learned`	a.
Half"-length`	a.
Half"-life`	n.
half-light	n.
Half"-mast`	n.
Half"-moon`	n.
Half nelson	n.
Half"pace`	n.
half"pence	n.
half"pen*ny	n.
halfpennyworth	n.
Half"-pike`	n.
Half"-port`	n.
Half"-ray`	n.
Half"-read`	a.
Half" seas` o"ver	a.
Half"-sis`ter	n.
Half"-strained`	a.
Half"-sword`	n.
Half"-tim`bered	a.
half"time`	n.
Half tone	n.
Half"-tone`	a.
Half"-tongue`	n.
half-track	adj.
half-track	n.
half"-truth`	n.
Half"way`	adv.
Half"way`	a.
half"way house`	n.
Half"-wit`ted	a.
Half"-year`ly	a.
Hal"i*but	n.
Hal`i*chon"dri*ae	prop. n. pl.
Hal"i*core	n.
Hal"i*dom	n.
Hal`i*eu"tics	n.
Hal"i*mas	a.
Halimodendron	n.
Ha`li*og"ra*pher	n.
Ha`li*og"ra*phy	n.
Haliotidae	prop. n.
Ha`li*o"tis	prop. n.
Ha"li*o*toid`	a.
Hal`i*sau"ri*a	n. pl.
Ha"lite	n.
Ha*lit"u*ous	a.
Halk	n.
Hall	n.
Hall"age	n.
Hal`le*lu"iah	n. & interj.
Hal`le*lu*jat"ic	a.
Hal"liard	n.
Hal"li*dome	n.
Hal"li*er	n.
Hall"-mark`	n.
Hal*loa"	n.
Hal*loo"	v. i.
Hal*loo"	v. t.
Hal*loo"	interj.
Hal"low	v. t.
hallowed	adj.
Hal`low*een"	n.
Hal"low*mas	n.
Hal*loy"site	n.
Hall"statt	a.
Hal"lu*cal	a.
Hal*lu"ci*nate	v. i.
hal*lu"ci*nate	v. t.
hallucinating	adj.
Hal*lu`ci*na"tion	n.
Hal*lu"ci*na`tor	n.
Hal*lu"ci*na*to*ry	a.
hal*lu"ci*no*gen	n.
hal*lu"ci*no*gen`ic	adj.
Hal"lux	n.
hall"way	n.
Halm	n.
Hal"ma	n.
Hal"ma	n.
Ha"lo	n.
Ha"lo	v. t. & i.
halobacter	n.
Halocarpus	n.
Ha"loed	a.
Hal"o*gen	n.
Ha*log"e*nous	a.
Ha"loid	a.
Hal"o*man`cy	n.
Ha*lom"e*ter	n.
Ha*lo"nes	n. pl.
Hal"o*phyte	n.
Ha"lo*scope	n.
Hal*o*tri"chite	n.
Ha*lox"y*line	n.
Halp	imp.
Hal"pace	n.
Hals	n.
Halse	v. t.
Halse	v. t.
Hal"sen*ing	a.
Hals"er	n.
Halt	3d pers. sing. pres.
Halt	n.
Halt	v. i.
Halt	v. t.
Halt	a.
Halt	n.
Halt	v. i.
Halt"er	n.
Hal"ter	n.
Hal"ter	v. t.
Hal*te"res	n. pl.
Hal"ter-sack`	n.
Halt"ing*ly	adv.
Hal"vans	n. pl.
Hal"ve	n.
Halve	v. t.
Halved	a.
Halves	n.
Hal"we	n.
Hal"yard	n.
Hal`y*si"tes	n.
Ham	n.
Ham	n.
Ham	n.
Ham	v. i.
Ham"a*dry`ad	n.
Ha*ma"dry*as	n.
Ha*mal"	n.
Hamamelidaceae	n.
Hamamelidae	n.
Hamamelidanthum	n.
Hamamelidoxylon	n.
Ham`a*me"lis	n.
Ha"mate	a.
Ha"ma*ted	a.
Ha*ma"tum	n.
Ham"ble	v. t.
Ham"burg	n.
Hame	n.
Hame	n.
Ham"el	v. t.
Hame"seck`en	n.
Ham"fat`ter	n.
ham-fisted	adj.
Ha"mi*form	a.
Ham"il*ton pe"ri*od	n.
Ham`i*nu"ra	n.
Ha"mite	n.
Ham"ite	n.
Ham*it"ic	a.
Ham"let	n.
Ham"let*ed	p. a.
Ham"mer	n.
Ham"mer	v. t.
Ham"mer	v. i.
Ham"mer*a*ble	a.
Ham"mer-beam`	n.
Ham"mer break	n.
Ham"mer-dressed`	a.
Ham"mer*er	n.
Ham"mer-hard`en	v. t.
Ham"mer*head`	n.
Ham"mer*kop	n.
Ham"mer-less	a.
Hammer lock	n.
ham"ming	n.
Ham`mo*chry"sos	n.
Ham"mock	n.
Ha*mose"	n.
Ham"per	v. t.
Ham"per	v. t.
Ham"per	n.
Ham"shac`kle	v. t.
Ham"ster	n.
Ham"string`	n.
Ham"string`	v. t.
Ham"u*lar	a.
Ham"u*late	a.
Ham"ule	n.
Ham"u*lose`	a.
Ham"u*lus	n.
Han	inf. & plural pres.
Han"ap	n.
Han"a*per	n.
Hance	v. t.
Hance	n.
Hand	n.
Hand	n.
Hand	v. t.
Hand	v. i.
hand"bag`	n.
Hand"ball`	n.
Hand"bar`row	n.
handbasin	n.
hand"bask*et	n.
handbell	n.
Hand"bill`	n.
Hand"book`	n.
hand"brake`	n.
Hand"breadth`	n.
handbuild	v. t.
handcar	n.
Hand"cart`	n.
Hand"cloth`	n.
handcolor	v. t.
Hand"craft`	n.
hand"craft`	v. t.
hand-crafted	adj.
Hand"crafts`man	n.
Hand"cuff`	n.
Hand"cuff`	v. t.
hand-down	adj.
Hand"ed	a.
hand"er	n.
hand"fast`	n.
hand"fast`	a.
hand"fast`	v. t.
hand"fast`	a.
hand"fast`ly	adv.
hand"fish`	n.
hand"ful	n.
hand"-hole`	n.
hand"i*cap	n.
Hand"i*cap	v. t.
Hand"i*cap`per	n.
Hand"i*capped	a.
Hand"i*craft	n.
Hand"i*crafts`man	n.
Hand"i*ly	adv.
Hand"i*ness	n.
Hand"i`ron	n.
Hand"i*work`	n.
Hand"ker*cher	n.
Hand"ker*chief	n.
Han"dle	v. t.
Han"dle	v. i.
Han"dle	n.
Han"dle*a*ble	a.
han"dle*bar`	n.
handled	adj.
-handled	suff.
handleless	adj.
handler	n.
Hand"less	a.
handline	n.
Han"dling	n.
handlock	n.
hand-loomed	adj.
Hand"made`	a.
Hand"maid`	n.
hand-me-down	adj.
hand-me-down	n.
handoff	n.
hand-operated	adj.
hand"out	n.
handover	n.
hand-picked	adj.
hand"rail`	n.
hand"rest`	n.
hands	n.
Hand"saw`	n.
handsbreadth	n.
Hand"sel	n.
Hand"sel	v. t.
handset	n.
handsewn	adj.
handstand	n.
Hand"some	a.
Hand"some	v. t.
Hand"some*ly	adv.
Hand"some*ness	n.
Hand"spike`	n.
Hand"spring`	n.
handstitched	adj.
Hand"-tight`	a.
hand-to-hand	adj.
handwash	v.
handwear	n.
Hand"wheel`	n.
Hand"-winged`	a.
handwoven	adj.
Hand"writ`ing	n.
handwritten	adj.
Hand"y	a.
Hand"y-dan`dy	n.
Hand"y*fight`	n.
Hand"y*gripe`	n.
Hand"y*stroke`	n.
Hand"y*work`	n.
Hang	v. t.
Hang	v. i.
Hang	n.
hang"ar	n.
Hang"bird`	n.
Hang"-by`	n.
Hang"dog`	n.
Hang"dog`	a.
Hang"er	n.
Hang"er-on`	n.
Hang"ing	a.
Hang"ing	n.
Hang"man	n.
Hang"man*ship	n.
Hang"nail`	n.
Hang"nest`	n.
hangover	n.
Hank	n.
Hank	v. t.
Han"ker	v. i.
Han"ker*ing*ly	adv.
Han"key-pan"key	n.
hankie	n.
hanky	n.
Hanover	n.
Han`o*ve"ri*an	a.
Han`o*ve"ri*an	n.
Han"sa	n.
Han"sard	n.
Han"sard	n.
Hanse	n.
Hanse	n.
Han`se*at"ic	a.
Han"sel	n. & v.
Han"sel*ines	n.
Han"som	n.
Han't	n.
Han"u*man	n.
haoma	n.
Hap	v. t.
Hap	n.
Hap	n.
Hap	v. i.
Ha'"pen*ny	n.
Hap"haz`ard	n.
hap"haz`ard	a.
Haph*ta"rah	n.
Hap"less	a.
Hap"less*ly	adv.
Hap"loid	a.
Ha*plo"mi	n. pl.
haplosporidian	n.
Hap`lo*stem"o*nous	a.
Hap"ly	adv.
Happed	p. a.
Hap"pen	v. i.
happening	n.
Hap"pi*ly	adv.
Hap"pi*ness	n.
Hap"py	a.
haptic	adj.
Ha*pu"ku	n.
Haque"but	n.
ha"ra*ki`ri	n.
ha"ri-ka`ri	n.
Ha*rangue"	v. i.
Ha*rangue"	v. t.
Ha*rangue"ful	a.
Ha*rang"uer	n.
Har"ass	v. t.
Har"ass	n.
harassed	adj.
Har"ass*er	n.
Har"ass*ment	n.
Har"ber*ous	a.
Har"bin*ger	n.
Har"bin*ger	v. t.
Har"bor	n.
Har"bor	v. t.
Har"bor	v. i.
Har"bor*age	n.
Har"bor*er	n.
Har"bor*less	a.
Har"bor mas`ter	n.
Har"bor*ous	a.
Hard	a.
Hard	adv.
Hard	v. t.
Hard	n.
hard-and-fast	adj.
hard"ass	n.
hard"back`	adj.
hard"back`	n.
Hard"bake`	n.
hard-baked	adj.
Hard"beam`	n.
hard-bitten	adj.
hard"board`	n.
hard-boiled	adj.
hardbound	adj.
hard"cov*er	n. & a.
Hard"en	v. t.
Hard"en	v. i.
Hardenbergia	prop. n.
Hard"ened	a.
Hard"en*er	n.
Hard"en*ing	n.
Har"der	n.
Har*de"ri*an	a.
Hard"-fa`vored	a.
Hard"-fa`vored*ness	n.
Hard"-fea`tured	a.
Hard"fern`	n.
Hard"-fist`ed	a.
hard"-fought`	a.
Hard" grass`	n.
Hard"-hand`ed	a.
Hard"head`	n.
hard"head`ed	a.
Hard"-heart`ed	a.
hard-hitting	adj.
Har"di*head	n.
Har"di*hood	n.
Har"di*ly	adv.
Har"di*ment	n.
Har"di*ness	n.
Hard"ish	a.
Hard"-la`bored	a.
Hard"ly	adv.
hard"ly ev"er	adv.
Hard"-mouthed`	a.
Hard"ness	n.
hard"nose	n.
hard-nosed	adj.
Har"dock	n.
hard-of-hearing	adj.
hard-on	n.
Hard"pan`	n.
hard-pressed	adj.
Hards	n. pl.
Hard"-shell`	a.
Hard"ship	n.
Hard"spun`	a.
Hard steel	adj.
Hard"tack`	n.
Hard"tail`	n.
hard-to-please	adj.
Hard"-vis`aged	a.
Hard"ware`	n.
hard"ware`man	n.
hard"-wired"	a.
hard"wood`	n.
hard"wood`	adj.
hard"-won`	a.
hard"work`ing	adj.
Har"dy	a.
Har"dy	n.
Hare	v. t.
Hare	n.
Hare"bell`	n.
Hare"brained`	a.
Hare"foot`	n.
Hare"-heart`ed	a.
Hare"hound`	n.
Har"eld	n.
Hare"lip`	n.
Ha"rem	n.
Ha*ren"gi*form	a.
Hare's"-ear`	n.
Hare's"-foot` fern`	n.
Har"fang	n.
Ha`ri*a"li grass`	n.
Har"i*er	n.
Ha"ri*ka`ri	n.
Har`i*o*la"tion	n.
Har"ish	a.
Hark	v. i.
Hark"en	v. t. & i.
Harl	n.
Harle	n.
Har"lech group`	n.
Har"le*quin	v. i.
Har"le*quin	v. t.
Har"le*quin*ade`	n.
har"le*quin snake`	n.
Har"lock	n.
Har"lot	n.
Har"lot	a.
Har"lot	v. i.
Har"lot*ize	v. i.
Har"lot*ry	n.
Harm	n.
Harm	v. t.
Har"ma*line	n.
Har*mat"tan	n.
Har"mel	n.
Harm"ful	a.
Har"mine	n.
Harm"less	a.
Har*mon"ic	a.
Har*mon"ic	n.
Har*mon"i*ca	n.
Har*mon"ic*al*ly	adv.
Har*mon"i*con	n.
Har*mon"ics	n.
Har*mo"ni*ous	a.
Har*mon"i*phon	n.
Har"mo*nist	n.
Har"mo*nist	n.
Har*mo"ni*um	n.
harmonizable	adj.
Har`mo*ni*za"tion	n.
Har"mo*nize	v. i.
Har"mo*nize	v. t.
Har"mo*ni`zer	n.
Har`mo*nom"e*ter	n.
Har"mo*ny	n.
Har"most	n.
Har"mo*tome	n.
Har"ness	n.
Har"ness	v. t.
Har"ness cask`	n.
Harns	n. pl.
Harp	n.
Harp	v. i.
Harp	v. t.
Har"pa	n.
Har"pa*gon	n.
Harp"er	n.
Harp"ing	a.
Harp"ing i`ron	n. pl.
Harp"ist	n.
Har*poon"	n.
Har*poon"	v. t.
Har`poon*eer"	n.
Har*poon"er	n.
Harp"ress	n.
Harp"si*chon	n.
Harp"si*chord	n.
harpsichordist	n.
harpulla	n.
harpullia	n.
Har"py	n.
Har"que*bus	n.
Har"rage	v. t.
Har"re	n.
Har"ri*dan	n.
harried	adj.
Har"ri*er	n.
Har"ri*er	n.
Harrisia	prop. n.
Har"row	n.
Har"row	v. t.
Har"row	interj.
Har"row	v. t.
Har"row*er	n.
Har"row*er	n.
Har"ry	v. t.
Har"ry	v. i.
Har"ry	prop. n.
Harsh	a.
Harsh"ly	adv.
Harsh"ness	n.
Hars"let	n.
Hart	n.
hartebeest	n.
Hart"beest`	n.
Hart"en	v. t.
Hart"ford	n.
Hart's" clo`ver	n.
Harts"horn`	n.
Hart's"-tongue`	n.
Hart"wort`	n.
Har"um-scar"um	a.
Ha*rus`pi*ca"tion	n.
Ha*rus"pice	n.
Ha*rus"pi*cy	n.
Har"vest	n.
Har"vest	v. t.
Har"vest*er	n.
Har"vest-home"	n.
Har"vest*ing	a. & n.
Har"vest*less	a.
harvest-lice	n.
Har"vest*man	n.
Har"vest*ry	n.
Har"vey proc"ess	v. t.
Has	3d pers. sing. pres.
Has"ard	n.
Hase	v. t.
Hash	n.
Hash	v. t.
Hash"eesh	n.
hash"mark`	n.
Hask	n.
Has"let	n.
Hasp	n.
Hasp	v. t.
hassle	n.
hassle	v. i.
hassle	v. t.
Has"sock	n.
Hast	2d pers. sing. pres.
Has"tate	a.
Haste	n.
Haste	v. t. & i.
Has"ten	v. t.
Has"ten	v. i.
Has"ten*er	n.
Has"tif	a.
Has"tile	a.
Has"ti*ly	adv.
Has"ti*ness	n.
Has"tings	n. pl.
Has"tings sands`	a.
Has"ty	a.
Has"ty pud"ding	a.
Hat	sing. pres.
Hat	n.
Hat"a*ble	a.
Hat"band`	n.
Hat"box`	n.
Hatch	v. t.
Hatch	v. t.
Hatch	v. i.
Hatch	n.
Hatch	n.
Hatch	v. t.
Hatch"-boat`	n.
hatched	adj.
Hatch"el	n.
Hatch"el	v. t.
Hatch"el*er	n.
Hatch"er	n.
Hatch"er*y	n.
Hatch"et	n.
hatchet man	n.
Hatch"et*tine	n.
Hatch"ing	n.
Hatch"ment	n.
Hatch"ure	n.
Hatch"way`	n.
Hate	v. t.
Hate	n.
Hate"ful	a.
Hat"el	a.
hatemonger	n.
Hat"er	n.
Hath	v., 3d pers. sing. pres.
Hatiora	n.
Hat"less	a.
hatpin	n.
Hat"rack`	n.
Ha"tred	n.
Hat"stand`	n.
Hat"te	pres. & imp. sing. & pl.
Hat"ted	a.
Hat"ter	v. t.
Hat"ter	n.
Hat*te"ri*a	n.
Hat"ting	n.
Hat"ti-sher`if	n.
Hat"tree`	n.
Hau*ber"ge*on	n.
Hau"berk	n.
Hau"er*ite	n.
Haugh	n.
Haught	a.
Haugh"ti*ly	adv.
Haugh"ti*ness	n.
Haugh"ty	a.
Haul	v. t.
Haul	v. i.
Haul	n.
Haul"a*bout`	n.
Haul"age	n.
Haul"er	n.
haulier	n.
Haulm	n.
Haulm	n.
Hauls	n.
Haulse	v.
Hault	a.
Haum	n.
Haunce	v. t.
Haunch	n.
Haunched	a.
Haunt	v. t.
Haunt	v. i.
Haunt	n.
Haunt"ed	a.
Haunt"er	n.
Hau"ri*ent	a.
Hau"sen	n.
Hausse	n.
Haus`tel*la"ta	n. pl.
Haus"tel*late	a.
Haus*tel"lum	n.
Haus*to"ri*um	n.
Haut	a.
Haut"boy	n.
Haut"boy*ist	n.
Hau"tein	a.
Hau`teur"	n.
Haut`go<ucir/t"	n.
Haut`pas"	n.
Ha"<uum/y*nite	n.
Ha*van"a	prop. a.
Hav`an*ese"	a.
Have	v. t.
Have"less	a.
Hav"e*lock	n.
Ha"ven	n.
Ha"ven	v. t.
Ha"ven*age	n.
Ha"vened	p. a.
Ha"ven*er	n.
Ha"ver	n.
Hav"er	n.
Ha"ver	v. i.
Hav"er*sack	n.
Ha*ver"sian	a.
Hav"ier	n.
Hav`il*dar"	n.
Hav"ing	n.
Hav"ior	n.
Hav"oc	n.
Hav"oc	v. t.
Hav"oc	interj.
Haw	n.
Haw	n.
Haw	n.
Haw	v. i.
Haw	v. i.
Haw	v. t.
Ha*wai"ian	prop. a.
Hawe"bake`	n.
Haw"finch`	n.
Haw-haw"	n.
Haw*haw"	v. i.
Hawk	n.
Hawk	v. i.
Hawk	v. i.
Hawk	v. t.
Hawk	n.
Hawk	v. t.
Hawk	n.
hawk"bill`	n.
Hawk"bit`	n.
Hawked	a.
Hawk"er	n.
Hawk"er	v. i.
Hawk"er	n.
Hawk"ey	n.
Hawk"-eyed`	a.
Hawk"eye` State	n.
hawks"bill	n.
Hawk"weed`	n.
Hawm	n.
Hawm	v. i.
Hawse	n.
hawse"hole`	n.
Haws"er	n.
Haws"er-laid`	a.
Haw"thorn`	n.
Hay	n.
Hay	v. i.
Hay	n.
Hay	v. i.
Hay"bird`	n.
Hay"bote`	n.
Hay"cock`	n.
Hay"-cut`ter	n.
Hay"field`	n.
Hay"fork`	n.
Hay"loft`	n.
Hay"mak`er	n.
Hay"mak`ing	n.
Hay"mow`	n.
Hay"rack`	n.
Hay"rake`	n.
Hay"rick`	n.
hay"rig	n.
hay"seed	n.
Hay"stack`	n.
Hay"stalk`	n.
Hay"thorn`	n.
Hay"ti*an	a.
Hay"ward	n.
Haz"ard	n.
Haz"ard	v. t.
Haz"ard	v. i.
Haz"ard*a*ble	a.
Haz"ard*er	n.
Haz"ard*ize	n.
Haz"ard*ous	a.
haz"ard*ous*ness	n.
Haz"ard*ry	n.
Haze	n.
Haze	v. i.
Haze	v. t.
Ha"zel	n.
Ha"zel	a.
Haze"less	a.
Ha"zel*ly	a.
Ha"zel*nut`	n.
hazelwood	n.
Ha"zel*wort`	n.
Ha"zi*ly	adv.
Ha"zi*ness	n.
Ha"zle	v. t.
Ha"zy	a.
H"-bomb`	n.
HDL	n.
He	pron.
He	suffix.
Head	n.
Head	a.
Head	v. t.
Head	v. i.
Head"ache`	n.
Head"ach`y	a.
Head"band`	n.
Head"board`	n.
Head"bor*ough	n.
Head"-cheese`	n.
Head"dress`	n.
Head"ed	a.
Head"er	n.
Head`first"	adv.
Head"fish`	n.
Head" gear`	n.
Head"-hunt`er	n.
Head"i*ly	adv.
Head"i*ness	n.
Head"ing	n.
head-in-the-clouds	adj.
head"lamp`	n.
Head"land	n.
Head"less	a.
Head"light`	n.
Head"line`	n.
head"line`	v. t.
headlinese	n.
head"lock`	n.
Head"long`	adv.
Head"long	a.
Head"-lugged`	a.
Head"man`	n.
Head"mold` shot"	a.
Head"note`	n.
head-on	adj.
Head"pan`	n.
Head"piece`	n.
head"pin`	n.
Head"quar`ters	n. pl.
Head"race`	n.
Head"room`	n.
Head"rope`	n.
Head"sail`	n.
Head`shake`	n.
Head"ship	n.
Heads"man	n.
Head"spring`	n.
Head"stall`	n.
Head"stock`	n.
Head"stone`	n.
Head"strong`	a.
Head"strong`ness	n.
heads-up	adj.
heads-up	n.
Head"tire`	n.
Head"wa`ter	n.
Head"way`	n.
headword	n.
Head"work`	n.
Head"y	a.
Heal	v. t.
Heal	v. t.
Heal	v. i.
Heal	n.
Heal"a*ble	a.
Heal"all`	n.
Heald	n.
Heal"er	n.
Heal"ful	a.
Heal"ing	a.
Heal"ing*ly	adv.
Health	n.
Health"ful	a.
Health"ful*ly	adv.
Health"ful*ness	n.
Health"i*ly	adv.
Health"i*ness	n.
Health"less	a.
Health"less*ness	n.
Health"some	a.
Health"ward	a. & adv.
Health"y	a.
Heam	n.
Heap	n.
Heap	v. t.
Heap"er	n.
heaps	n.
Heap"y	a.
Hear	v. t.
Hear	v. i.
hearable	adj.
Heard	imp. & p. p.
Hear"er	n.
Hear"ing	n.
hearing-impaired	adj.
Heark"en	v. i.
Heark"en	v. t.
Heark"en*er	n.
Hear"sal	n.
Hear"say`	n.
Hearse	n.
Hearse	n.
Hearse	v. t.
Hearse"cloth`	n.
Hearse"like`	a.
Heart	n.
Heart	v. t.
Heart	v. i.
Heart"ache`	n.
heartbeat	n.
Heart"break`	n.
Heart"break`ing	a.
Heart"bro`ken	a.
Heart"burn`	n.
Heart"burned`	a.
Heart"burn`ing	a.
Heart"burn`ing	n.
Heart"dear`	a.
Heart"deep`	a.
Heart"-eat`ing	a.
Heart"ed	a.
Heart"ed*ness	n.
Heart"en	v. t.
Heart"en*er	n.
Heart"felt`	a.
Heart"grief`	n.
Hearth	n.
hearthrug	n.
Hearth"stone`	n.
Heart"i*ly	adv.
Heart"i*ness	n.
heartleaf	n.
Heart"less	a.
Heart"let	n.
Heart"lings	interj.
Heart"pea`	n.
Heart"quake`	n.
Heart"rend`ing	a.
Heart"-rob`bing	a.
Heart's"-ease`	n.
Heart"seed`	n.
heart"shaped`	a.
Heart"sick`	a.
Heart"some	a.
Heart"-spoon`	n.
Heart"strick`en	a.
Heart"strike`	v. t.
Heart"string`	n.
Heart"struck`	a.
Heart"swell`ing	a.
heart"warm`ing	adj.
Heart"-whole`	a.
Heart"wood`	n.
Heart"-wound`ed	a.
Heart"y	a.
Heart"y	n.
Heart"y*hale`	a.
Heat	n.
Heat	v. t.
Heat	v. i.
Heat	imp. & p. p.
heated	adj.
Heat"er	n.
Heath	n.
Heath"clad`	a.
Hea"then	n.
Hea"then	a.
Hea"then*dom	n.
Hea"then*esse	n.
Hea"then*ish	a.
Hea"then*ish*ly	adv.
Hea"then*ish*ness	n.
Hea"then*ism	n.
Hea"then*ize	v. t.
Hea"then*ness	n.
Hea"then*ry	n.
Heath"er	n.
Heath"er*y	a.
heathfowl	n.
Heath"y	a.
Heat"ing	a.
Heat"ing*ly	adv.
Heat"less	a.
heatstroke	n.
heaume	n.
Heave	v. t.
Heave	v. i.
Heave	n.
Heav"en	n.
Heav"en	v. t.
Heav"en*ize	v. t.
heav"en*li*ness	n.
Heav"en*ly	a.
Heav"en*ly	adv.
Heav"en*ly-mind`ed	a.
Heav"en*ward	a. & adv.
Heave" of`fer*ing	n.
Heaves	n.
Heav"i*ly	adv.
Heav"i*ness	n.
Heav"ing	n.
Heav"i*some	a.
Heav"y	a.
Heav"y	a.
Heav"y	adv.
Heav"y	v. t.
Heav"y-armed`	a.
Heav"y-had"ed	a.
heavy-handed	adj.
Heav"y-head"ed	a.
heavyhearted	adj.
heavy-laden	adj.
heavyset	adj.
Heav"y spar`	adj.
heavyweight	n.
Heb"do*mad	n.
Heb*dom"a*dal	a.
Heb*dom"a*dal*ly	adv.
Heb*dom"a*da*ry	n.
Heb`do*mat"ic*al	a.
He"be	n.
Heb"en	n.
Heb"e*non	n.
Heb"e*tate	v. t.
Heb"e*tate	a.
Heb`e*ta"tion	n.
He*bete"	a.
Heb"e*tude	n.
He"bra"ic	a.
He*bra"ic*al*ly	adv.
He"bra*ism	n.
He"bra*ist	n.
He`bra*is"tic	a.
He`bra*is"tic*al*ly	adv.
He"bra*ize	v. t.
He"bra*ize	v. i.
He"brew	n.
He"brew	a.
Hebrew calendar	n.
He*bri"cian	n.
He*brid"e*an	a.
Hec"a*tomb	n.
Hec`a*tom"pe*don	n.
Hec"de*cane	n.
Heck	n.
Heck	n.
Heck"er*ism	n.
Heck"i*mal	n.
Hec"kle	n. & v. t.
Hec"kle	v. t.
heckling	n.
Hec"tare`	n.
Hec"tic	a.
Hec"tic	n.
Hec`to*cot"y*lized	a.
Hec`to*cot"y*lus	n.
hec"to*gram	n.
Hec"to*gramme	n.
Hec"to*graph	n.
Hec"to*li`ter	n.
Hec"to*me`ter	n.
Hec"tor	n.
Hec"tor	v. t.
Hec"tor	v. i.
Hec"to*rism	n.
Hec"tor*ly	a.
Hec"to*stere	n.
Hed"dle	n.
Hed"dle	v. t.
Hed"dle-eye`	n.
Hed"dling	vb. n.
Hed`er*a"ceous	a.
Hed"er*al	a.
He*der"ic	a.
Hed`er*if"er*ous	a.
Hed"er*ose`	a.
Hedge	n.
Hedge	v. t.
Hedge	v. i.
Hedge"born`	a.
Hedge"bote`	n.
hedged	adj.
Hedge" fund`	n.
Hedge"hog`	n.
Hedge"less	a.
Hedge"pig`	n.
Hedg"er	n.
Hedge"row`	n.
Hedg"ing bill`	n.
He*don"ic	a.
He*don"ics	n.
Hed"on*ism	n.
Hed"on*ist	n.
Hed`o*nis"tic	a.
Hedysarum	n.
Heed	v. t.
Heed	v. i.
Heed	n.
Heed"ful	a.
Heed"less	a.
Heed"y	a.
hee-haw	v. i.
hee-haw	n.
Heel	v. i.
Heel	n.
Heel	v. t.
Heel"ball`	n.
Heel"er	n.
Heel"less	a.
Heel"path`	n.
Heel"piece`	n.
Heel"post`	n.
Heel"spur`	n.
Heel"tap`	n.
Heel"tap`	v. t.
Heel"tool`	n.
Heem"raad`	n.
Heep	n.
Heer	n.
Heer	n.
Heft	n.
Heft	n.
Heft	n.
Heft	v. t.
Heft"y	a.
hegari	n.
Hegel	prop. n.
He*ge"li*an	prop. a.
He*ge"li*an*ism	prop. n.
Heg`e*mon"ic	a.
He*gem`o*ny	n.
Heg"ge	n.
He*gi"ra	n.
he-huckleberry	n.
Heif"er	n.
Heigh"-ho	interj.
Height	n.
Height"en	v. t.
Height"en*er	n.
heights	n.
Heimdal	n.
Heimdall	n.
Heimdallr	n.
hei"nie	n.
Hei"nous	a.
heinousness	n.
Heir	n.
Heir	v. t.
Heir"dom	n.
Heir"ess	n.
Heir"less	a.
Heir"loom`	n.
Heir"ship	n.
He*ji"ra	n.
Hek"tare`	n.
Hek"to*graph	n.
Hel*a*mys	n.
Hel"co*plas`ty	n.
Held	imp. & p. p.
Hele	n.
Hele	v. t.
Hel"e*na	n.
Hel"e*nin	n.
Heleodytes	prop. n.
He"li*ac	a.
He*li"a*cal	a.
He*li"a*cal*ly	adv.
He`li*an"thin	n.
He`li*an"thoid	a.
He`li*an"thoi"de*a	n. pl.
helianthus	n.
Hel"i*cal	a.
Hel`i*chry"sum	n.
He*lic"i*form	a.
Hel"i*cin	n.
Hel"i*cine	a.
Hel"i*co*graph`	n.
Hel"i*coid	a.
Hel"i*coid	n.
Hel`i*coid"al	a.
Hel"i*con	prop. n.
Hel`i*co"ni*a	n.
Hel`i*co"ni*an	a.
Hel"i*cop`ter	n.
Hel"i*cop`ter	v. i.
Hel"i*cop`ter	v. t.
Hel`i*co"tre"ma	n.
He"li*o-	a.
He"li*o*chrome	n.
He`li*o*chro"mic	a.
He"li*o*chro`my	n.
He"li*o*gram	n.
He"li*o*graph	n.
He"li*o*graph	v. t.
He`li*o*graph"ic	a.
He`li*og"ra*phy	n.
He`li*o*grav"ure	n.
He`li*ol"a*ter	n.
He`li*ol"a*try	n.
He"li*o*lite	n.
He`li*om"e*ter	n.
He`li*o*met"ric	a.
He`li*om"e*try	n.
He`li*op"o*ra	n.
He"li*o*scope	n.
He"li*o*stat	n.
He"li*o*trope	n.
He"li*o*tro`per	n.
He`li*o*trop"ic	a.
He`li*ot"ro*pism	n.
He"li*o*type	n.
He`li*o*typ"ic	a.
He"li*o*ty`py	n.
He`li*o*zo"a	n. pl.
heliport	n.
Helipterum	n.
Hel`i*spher"ic	a.
He"li*um	n.
He"lix	n.
Hell	n.
Hell	v. t.
Hel`la*nod"ic	n.
Hell"bend`er	n.
hell-bent	adj.
Hell"born`	a.
Hell"bred`	a.
Hell"brewed`	a.
Hell"broth`	n.
Hell"-cat `	n.
Hell"-div`er	n.
Hell"doomed`	a.
Hel"le*bore	n.
Hel`le*bo"re*in	n.
Hel*leb"o*rin	n.
Hel"le*bo*rism	n.
Hel"lene	n.
Hel*le"ni*an	a.
Hel*len"ic	a.
Hel*len"ic	n.
Hel"len*ism	n.
Hel"len*ist	n.
Hel`le*nis"tic	a.
Hel`le*nis"tic*al*ly	adv.
Hel"len*ize	v. i.
Hel"len*ize	v. t.
Hel*len"o*type	n.
Hel"les*pont	n.
Hel`les*pon"tine	a.
Hell"ga*mite	n.
Hell"hag`	n.
Hell"-haunt`ed	a.
Hell"hound`	n.
Hel"li*er	n.
Hell"ish	a.
Hell"kite`	n.
Hel*lo"	interj. & n.
Hell"ward	adv.
Hell"y	a.
Helm	n.
Helm	n.
Helm	v. t.
Helm	n.
Helm	v. t.
Helm"age	n.
Helm"ed	a.
Hel"met	n.
Hel`met*ed	a.
Hel"met-shaped`	a.
Hel"minth	n.
Hel*min"tha*gogue	n.
Hel*min"thes	n. pl.
Hel`min*thi"a*sis	n.
Hel*min"thic	a.
Hel*min"thite	n.
Hel*min"thoid	a.
Hel*min`tho*log"ic	a.
Hel`min*thol"o*gist	n.
Hel`min*thol"o*gy	n.
Helm"less	a.
Helms"man	n.
Helm"wind`	n.
Helodermatidae	prop. n.
He"lot	n.
He"lot*ism	n.
Helotium	n.
He"lot*ry	n.
Help	v. t.
Help	v. i.
Help	n.
Help"er	n.
Help"ful	a.
helping	n.
Help"less	a.
Help"mate`	n.
Help"meet`	n.
Hel"ter-skel"ter	adv.
Helve	n.
Helve	v. t.
Hel*ve"tian	a.
Hel*ve"tic	a.
Hel"vine	n.
Helxine	n.
Hem	pron.
Hem	interj.
Hem	n.
Hem	v. i.
Hem	n.
Hem	v. t.
Hem"a-	n.
Hem"a*chrome	n.
Hem"a*cite	n.
Hem`a*drom"e*ter	n.
Hem`a*drom`e*try	n.
He`ma*dy*nam"ics	n.
He`ma*dy"na*mom"e*ter	n.
He"mal	a.
Hem`a*phae"in	n.
Hem`a*poph"y*sis	n.
Hem`a*stat"ic	a. & n.
Hem`a*stat"ics	n.
Hem`a*ta*chom"e*ter	n.
Hem`a*te"in	n.
Hem`a*tem"e*sis	n.
Hem"a*therm	n.
Hem`a*ther"mal	a.
He*mat"ic	a.
He*mat"ic	n.
Hem"a*tin	n.
He`ma*tin"ic	n.
Hem`a*ti*nom"e*ter	n.
Hem`a*tin`o*met"ric	a.
He*mat"i*non	n.
Hem"a*tite	n.
Hem`a*tit"ic	a.
Hem"a*to	n.
Hem`a*toc"ry*a	n. pl.
Hem`a*to*crys"tal*lin	n.
Hem"a*toid	a.
Hem`a*toid"in	n.
Hem`a*tol"o*gy	n.
hematolysis	n.
Hem`a*to"ma	n.
Hem`a*to*phil"i*a	n.
Hem`a*to"sin	n.
Hem`a*to"sis	n.
Hem`a*to*ther"ma	n. pl.
Hem"a*to*ther"mal	a.
Hem`a*tox"y*lin	n.
Hem`a*tu"ri*a	n.
Hem`au*tog"ra*phy	n.
Hem*el"y*tron	n.
Hem`e*ra*lo"pi*a	n.
Hem`er*o"bi*an	n.
He*mer"o*bid	a.
Hemerobiidae	prop. n.
Hemerocallidaceae	n.
Hem`e*ro*cal"lis	n.
Hem"i-	n.
Hem`i*al"bu"mose`	n.
Hem`i*an`aes*the"si*a	n.
Hem`i*bran"chi	n. pl.
Hem`i*car"di*a	n.
Hem`i*carp	n.
Hem`i*cer"e*brum	n.
Hem`i*col"lin	n.
Hem`i*cra"ni*a	n.
Hem"i*cra`ny	n.
Hem"i*cy`cle	n.
Hem`i*dac"tyl	n.
Hem`i-dem`i-sem"i*quaver	n.
Hem`i*di"tone	n.
He*mig"a*mous	a.
Hem"i*glyph	n.
Hem`i*he"dral	a.
Hem`i*he"drism	n.
Hem`i*he"dron	n.
Hem`i*hol`o*he"dral	a.
Hem`i*mel*lit"ic	a.
Hem`i*me*tab"o*la	n. pl.
Hem`i*met`a*bol"ic	a.
Hem`i*mor"phic	a.
He"min	n.
He*mi"na	n.
He*mi"o*nus	n.
Hem`i*o"pi*a	n.
Hem`i*or"tho*type	a.
Hem`i*pep"tone	n.
Hem`i*ple"gi*a	n.
Hem"i*ple`gy	n.
Hem"i*pode	n.
Hem`i*pro"te*in	n.
He*mip"ter	n.
He*mip"te*ra	n. pl.
He*mip"ter*al	a.
He*mip"ter*an	n.
Hemiramphidae	prop. n.
Hem`i*sect"	v. t.
Hem`i*sec"tion	n.
Hem"i*sphere	n.
Hem`i*spher"ic	a.
Hem`i*sphe"roid	n.
Hem`i*sphe*roid"al	a.
Hem`i*spher"ule	n.
Hem"i*stich	n.
He*mis"ti*chal	a.
Hem`i*sys"to*le	n.
Hem"i*tone	n.
He*mit"ro*pal	a.
Hem"i*trope	a.
Hem"i*trope	n.
He*mit"ro*py	n.
Hem"lock	n.
Hem"mel	n.
Hem"mer	n.
hemming-stitch	n.
Hem"o-	n.
Hem`o*glo"bin*om"e*ter	n.
hemolysis	n.
hemolytic	adj.
Hem`o*phil"i*a	n.
hem`o*phil"i*ac	n.
hem`o*phil"i*ac	a.
hem`o*phil"ic	adj.
He*mop"ty*sis	n.
Hem"or*rhage	n.
Hem`or*rhag"ic	a.
Hem`or*rhoid"al	a.
Hem"or*rhoids	n. pl.
hemosiderin	n.
hemosiderosis	n.
hemostat	n.
Hem`o*stat"ic	a.
Hem`o*stat"ic	n.
Hem`o*tho"rax	n.
Hemp	n.
Hemp"en	a.
Hemp"y	a.
Hem*self"	pron. pl.
Hem"stitch	v. t.
Hem"stitched	a.
He"muse	n.
Hen	n.
Hen"bane`	n.
Hen"bit`	n.
Hence	adv.
Hence	v. t.
Hence`forth"	adv.
Hence`for"ward	adv.
Hench"boy`	n.
Hench"man	n.
Hen"coop`	n.
Hende	a.
Hen*dec"a*gon	n.
Hen"de*cane	n.
Hen*dec`a*syl*lab"ic	a.
Hen*dec"a*syl`la*ble	n.
Hen*dec`a*to"ic	a.
Hen*di"a*dys	n.
Hen"dy	a.
Hen"en	adv.
Hen"fish`	n.
Heng	imp.
Hen"-heart`ed	a.
Hen"house`	n.
Hen"hus`sy	n.
He*ni"quen	n.
Hen"na	n.
Hen"ner*y	n.
Hen"nes	adv.
Hen`no*tan"nic	a.
He*nog"e* ny	n.
Hen"o*the*ism	n.
He*not"ic	a.
hen"peck`	v. t.
hen-of-the-woods	n.
Hen`ri*et"ta cloth`	n.
Hen"ry	n.
Hen's-foot`	n.
Hent	v. t.
Hen"ware`	n.
Henx"man	n.
henyard	n.
hep	n.
hep	a.
hep	interj.
hep"cat`	n.
He"par	n.
He*pat"ic	a.
He*pat"i*ca	n.
He*pat"ic*al	a.
Hep"a*tite	n.
Hep`a*ti"tis	n.
Hep`a*ti*za"tion	n.
Hep"a*tize	v. t.
He*pat"o*cele	n.
Hep`a*to*cys"tic	a.
Hep`a*to*gas"tric	a.
Hep`a*to*gen"ic	a.
Hep`a*tol"o*gy	n.
Hep"a*to-pan"cre*as	n.
Hep`a*to*re"nal	a.
Hep`a*tos"co*py	n.
Hep"pen	a.
Hep"per	n.
Hep"pel*white	a.
Hep"ta	n.
Hep"tad	n.
Hep"tade	n.
Hep"ta*glot	n.
Hep"ta*gon	n.
Hep*tag"o*nal	a.
Hep`ta*gyn"i*a	n. pl.
Hep`ta*gyn"i*an	a.
Hep`ta*he"dron	n.
Hep*tam"er*ous	a.
Hep*tan"dri*a	n. pl.
Hep*tan"dri*an	a.
Hep"tane	n.
Hep*tan"gu*lar	a.
Hep*taph"yl*lous	a.
Hep"tarch	n.
Hep*tar"chic	a.
Hep"tarch*ist	n.
Hep"tarch*y	n.
Hep`ta*sper"mous	a.
Hep"ta*stich	n.
Hep"ta*teuch	n.
Hep*tav"a*lent	a.
Hep"tene	n.
Hep"tine	n.
Hep*to"ic	a.
Hep"tone	n.
Hep" tree`	n.
Hep"tyl*ene	n.
Hep*tyl"ic	a.
Her	pron. & a.
Her	pron. pl.
He*rac"le*on*ite	n.
He*rak"line	n.
Her"ald	n.
Her"ald	v. t.
heralded	adj.
He*ral"dic	a.
He*ral"dic*al*ly	adv.
heraldist	adj.
Her"ald*ry	n.
Her"ald*ship	n.
Her"a*path*ite	n.
Her"aud	n.
Herb	n.
Her*ba"ceous	a.
Herb"age	n.
Herb"aged	a.
Herb"al	a.
Herb"al	n.
Herb"al*ism	n.
Herb"al*ist	n.
Herb"ar	n.
Her*ba"ri*an	n.
Herb"a*rist	n.
Her*ba"ri*um	n.
Herb"a*rize	v. t.
Herb"a*ry	n.
Herb"er	n.
Her"berg*age	n.
Her"ber*geour	n.
Her"bergh	n.
Her*bes"cent	a.
Herb"id	a.
Her*bif"er*ous	a.
Herb"ist	n.
Her*biv"o*ra	n. pl.
Her"bi*vore	n.
Her*biv"o*rous	a.
Herb"less	a.
Herb"let	n.
Her"bo*rist	n.
Her`bo*ri*za"tion	n.
Her"bo*rize	v. i.
Her"bo*rize	v. t.
Her"bor*ough	n.
Her*bose"	a.
Herb"-wom`an	n.
Herb"y	a.
Her*cog"a*mous	a.
Her*cu"le*an	a.
Her"cu*les	n.
Hercules'-club	prop. n.
Her*cyn"i*an	a.
Herd	a.
Herd	n.
Herd	n.
Herd	v. i.
Herd	v. t.
Herd"book`	n.
Herd"er	n.
Her"der*ite	n.
Herd"ess	n.
Herd"groom`	n.
Her"dic	n.
Herd"man	n.
Herds"wom`an	n.
Here	n.
Here	pron.
Here	adv.
Here"a-bout`	adv.
Here*aft"er	adv.
Here*aft"er	n.
Here*aft"er*ward	adv.
Here-at"	adv.
Here*by"	adv.
He*red`i*ta*bil"i*ty	n.
He*red"i*ta*ble	a.
He*red"i*ta*bly	adv.
Her`e*dit"a*ment	n.
He*red"i*ta*ri*ly	adv.
He*red"i*ta*ry	a.
He*red"i*ty	n.
Her"e*ford	n.
Here"hence`	adv.
Here*in"	adv.
Here`in*aft"er	adv.
Here`in*be*fore"	adv.
Here`in*to"	adv.
Her"e*mit	n.
Her`e*mit"ic*al	a.
Her"en	a.
Here*of"	adv.
Here*on"	adv.
Here*out"	adv.
Her"e*si*arch	n.
Her"e*si*arch`y	n.
Her`e*si*og"ra*pher	n.
Her`e*si*og"ra*phy	n.
Her"e*sy	n.
Her"e*tic	n.
He*ret"i*cal	a.
He*ret"i*cal*ly	adv.
He*ret"i*cate	v. t.
He*ret`i*fi*ca"tion	n.
Here*to"	adv.
Her"e*toch	n.
Here`to*fore"	adv.
Here`un*to"	adv.
Here`up*on"	adv.
Here*with"	adv.
Her"ie	v. t.
Her"i*ot	n.
Her"i*ot*a*ble	a.
Her"is*son	n.
Her`it*a*bil"i*ty	n.
Her"it*a*ble	a.
Her"it*age	a.
Her"it*ance	n.
Her"it*or	n.
Herl	n.
Her"ling	n.
Her"ma	n.
Her*maph`ro*de"i*ty	n.
Her*maph"ro*dism	n.
Her*maph"ro*dite	n.
Her*maph"ro*dite	a.
Her*maph`ro*dit"ic	a.
Her*maph"ro*dit*ism	n.
Her`me*neu"tic	a.
Her`me*neu"tic*al*ly	adv.
Her`me*neu"tics	n.
Her"mes	n.
Her*met"ic	a.
Her*met"ic*al*ly	adv.
Her"mit	n.
Her"mit*age	n.
Her"mit*a*ry	n.
Her"mit*ess	n.
Her*mit"i*cal	a.
Her`mo*dac"tyl	n.
Her`mo*ge"ni*an	n.
Hern	n.
Her*na"ni	n.
Herne	n.
Her"ni*a	n.
Her"ni*al	a.
Her`ni*ot"o*my	n.
Hern"shaw	n.
He"ro	n.
He*ro"di*an	prop. n.
He*ro`di*o"nes	n. pl.
He"ro*ess	n.
He*ro"ic	a.
He*ro"ic*al	a.
He*ro"ic*ness	n.
He`ro*i*com"ic	a.
her"o*in	n.
Her"o*ine	n.
Her"o*ism	n.
Her"on	n.
Her"on*er	n.
Her"on*ry	n.
Her"on*sew	n.
Her"on*shaw	n.
He`ro*<oum/l"o*gist	n.
He"ro*ship	n.
Her"pes	n.
Her"pes simp`lex	n.
Herpestes	n.
Her"pes*vir`us	n.
Her"pes zos`ter	n.
Her"pes zos`ter vir*us	n.
Her*pet"ic	a.
Her"pe*tism	n.
Her*pet`o*log"ic	a.
Her`pe*tol"o*gist	n.
Her`pe*tol"o*gy	n.
Her`pe*tot"o*mist	n.
Her`pe*tot"o*my	n.
Herr	n.
Her"ren*volk	n.
Her"ren*haus`	n.
Her"ring	n.
Her"ring*bone`	a.
Herrn"hut*er	n.
Hers	pron.
Her"sal	n.
Her"schel	n.
Her*sche"li*an	a.
Herse	n.
Herse	v. t.
Her*self"	pron.
Her"sil*lon	n.
Hert	n.
Her"te	n.
Her"te*ly	a. & adv.
Her"y	v. t.
Hertz	n.
Hertz"i*an	a.
Her"zog	n.
Hes"i*tan*cy	n.
Hes"i*tant	a.
Hes"i*tant*ly	adv.
Hes"i*tate	v. i.
Hes"i*tate	v. t.
hesitater	n.
hesitating	adj.
Hes"i*ta`ting*ly	adv.
Hes`i*ta"tion	n.
Hes"i*ta*tive	a.
Hes"i*ta*to*ry	a.
Hesp	n.
Hes"per	n.
Hes*per"e*tin	n.
Hes*pe"ri*an	a.
Hes*pe"ri*an	n.
Hes*pe"ri*an	a.
Hes"per*id	a. & n.
Hes*per"i*dene	n.
Hes*per"i*des	n. pl.
Hes*per"i*din	n.
Hes`pe*rid"i*um	n.
Hes`pe*ror"nis	n.
Hes"pe*rus	n.
Hes"sian	a.
Hes"sian	n.
Hess"ite	n.
Hest	n.
Hes"tern	a.
Hes"y*chast	n.
He*tae"ra	n.
He*tair"ism	n.
Hetch"el	v. t.
Hete	v. t. & i.
Het"er*a*canth	a.
Het"er*arch`y	n.
Het`e*raux*e"sis	n.
Het"er*o-	n.
Het`er*o*car"pous	a.
Het`er*o*ceph"a*lous	a.
Het`e*roc"e*ra	n. pl.
Het`er*o*cer"cal	a.
Het"er*o*cer`cy	n.
Het`er*o*chro"mous	a.
Het`er*och"ro*nism	n.
Het"er*o*clite	a.
Het"er*o*clite	n.
Het`er*o*clit"ic	a.
Het`er*oc"li*tous	a.
Het"er*o*cyst	n.
Het`er*o*dac"tyl	a.
Het`e*ro*dac"ty*l<ae/	n. pl.
Het`er*o*dac"tyl*ous	a.
Het"er*o*dont	a.
Het"er*o*dont	n.
Het"er*o*dox	a.
Het"er*o*dox	n.
Het"er*o*dox`al	a.
Het"er*o*dox`y	n.
Het`er*od"ro*mous	a.
Het`er*<oe/"cious	a.
Het`er*og"a*mous	a.
Het`er*og"a*my	n.
Het`er*o*gan"gli*ate	a.
Het"er*o*gene	a.
Het`er*o*ge"ne*al	a.
Het`er*o*ge*ne"i*ty	n.
Het`er*o*ge"ne*ous	a.
Het`er*o*gen"e*sis	n.
Het`er*o*ge*net"ic	a.
Het`er*og"e*nist	n.
Het`er*og"e*nous	a.
Het`er*og"e*ny	n.
Het`er*og"o*nous	a.
Het`er*og"o*ny	n.
Het`er*o*graph"ic	a.
Het`er*og"ra*phy	n.
Het`er*og"y*nous	a.
Het`er*ol"o*gous	a.
Het`er*ol"o*gy	n.
Het`e*rom"e*ra	n. pl.
Het`er*om"er*ous	a.
Het`er*o*mor"phic	a.
Het`er*o*mor"phism	n.
Het`er*o*mor"phous	a.
Het`e*ro*my*a"ri*a	n. pl.
Het`e*ro*ne*re"is	n.
Het`er*on"o*mous	a.
Het`er*on"o*my	n.
Het"er*o*nym	n.
Het`er*on"y*mous	a.
Het`er*o*ou`si*an	a.
Het`er*o*ou"si*an	n.
Het`er*o*ou"si*ous	a.
Het`er*o*path"ic	a.
Het`er*op"a*thy	n.
Het`er*o*pel"mous	a.
Het`e*roph"a*gi	n. pl.
Het`er*oph"e*mist	n.
Het`er*oph"e*my	n.
Het`er*oph"o*ny	n.
Het`er*oph"yl*lous	a.
Het"er*o*plasm	n.
Het`er*o*plas"tic	a.
Het`er*o*pod	n.
Het`e*rop"o*da	n. pl.
Het`er*op"o*dous	a.
Het`er*op"ter	n.
Het`e*rop"te*ra	n. pl.
Het`er*op"tics	n.
Het`er*os"cian	n.
Het`e*ro"sis	n.
Het`e*ro*so"ma*ti	n. pl.
Het`er*o*spor"ic	a.
Het"er*o*styled	a.
Het`er*o*sty"lism	n.
Het`er*o*tac"tous	a.
Het"er*o*tax`y	n.
Het`er*ot"o*pism	n.
Het`e*rot"ri*cha	n. pl.
Het`er*ot"ro*pal	a.
He"thing	n.
Het"man	n.
Heuchera	n.
Heugh	n.
Heuk	n.
Heu"land*ite	n.
Heu*ris"tic	a.
Heu*ris"tic	n.
heu*ris"ti*cal*ly	n.
Hevea	prop. n.
Hev"ed	n.
Hew	v. t.
Hew	n.
Hew	n.
Hewe	n.
Hew"er	n.
Hew"hole`	n.
Hewn	a.
Hex-	a.
Hex`a*cap"su*lar	a.
Hex"a*chord	n.
Hex`ac"id	a.
Hex*ac`ti*nel"lid	a.
Hex*ac`ti*nel"line	a.
Hex`ac*tin"i*a	n. pl.
Hex"ad	n.
Hex`a*dac"tyl*ous	a.
Hex"ade	n.
Hex"a*dec`ane	n.
Hex"a*gon	n.
Hex*ag"o*nal	a.
Hex*ag"o*nal*ly	adv.
Hex*ag"o*ny	n.
Hex"a*gram	n.
Hex`a*gyn"i*a	n. pl.
Hex`a*gyn"i*an	a.
Hex`a*he"dral	a.
Hex`a*he"dron	n.
Hex`a*hem"er*on	n.
Hex*am"er*ous	a.
Hex*am"e*ter	n.
Hex*am"e*ter	a.
Hex`a*met"ric	a.
Hex*am"e*trist	n.
Hex*an"dri*a	n. pl.
Hex*an"dri*an	a.
Hex"ane	n.
Hex*an"gu*lar	a.
Hex`a*pet"al*ous	a.
Hex*aph"yl*lous	a.
Hex"a*pla	n.
Hex"a*pod	a.
Hex*ap"o*da	n. pl.
Hex*ap"o*dous	a.
Hex*ap"ter*ous	a.
Hex"a*stich	n.
Hex"a*style	a.
Hex"a*teuch`	n.
Hex`a*tom"ic	a.
Hex*av"a*lent	a.
Hex"de*cyl	n.
Hex`de*cyl"ic	a.
Hex*ei"ko*sane	n.
Hex"ene	n.
Hex`i*col"ogy	n.
Hex"ine	n.
Hex*oc`ta*he"dron	n.
Hex*o"ic	a.
Hex"o*kin"ase	n.
Hex"one	n.
Hex"ose	n.
Hex"yl	n.
Hex"yl*ene	n.
Hex*yl"ic	a.
Hey	a.
Hey	interj.
Hey"day`	interj.
Hey"day`	n.
Hey"de*guy	n.
Heyh	a.
Heyne	n.
Hey"ten	adv.
Hi*a"tion	n.
Hi*a"tus	n.
Hibbertia	n.
Hi*ber"na*cle	n.
Hi`ber*nac"u*lum	n.
Hi*ber"nal	a.
Hi"ber*nate	v. i.
hibernating	adj.
Hi`ber*na"tion	n.
Hi*ber"ni*an	a.
Hi*ber"ni*cism	n.
Hi*ber"no-Celt"ic	n.
Hi*bis"cus	n.
Hic"ci*us doc"ti*us	n.
Hic"cough	v. i.
hick	n.
hick	adj.
hick"ey	n.
Hick"o*ry	n.
Hicks"ite	n.
Hick"up	n. & v. i.
Hick"wall`	n.
Hid	imp. & p. p.
Hid"age	n.
Hi*dal"go	n.
Hid"den	p. p. & a.
Hid"den*ite	n.
Hid"den*ly	adv.
Hide	v. t.
Hide	v. i.
Hide	n.
Hide	n.
Hide	v. t.
hide-and-seek	n.
hideaway	n.
Hide"bound`	a.
Hid"e*ous	a.
hide"out	n.
Hid"er	n.
Hid"ing	n.
Hid"ing	n.
Hi*dro"sis	n.
Hi*drot"ic	a.
Hi*drot"ic	n.
Hie	v. i.
Hie	n.
Hi"ems	n.
Hi"e*ra*pi"cra	n.
Hi"er*arch	n.
Hi"er*arch`al	a.
hi`er*arch"ic	a.
Hi"er*arch`ism	n.
Hi"er*arch`y	n.
Hi`er*at"ic	a.
Hi`er*oc"ra*cy	n.
Hi"er*o*glyph	n.
Hi`er*o*glyph"ic	a.
Hi`er*o*glyph`ic*ally	adv.
Hi`er*og"ly*phist	n.
Hi"er*o*gram	n.
Hi`er*o*gram"mat"ic	a.
Hi`er*o*gram"ma*tist	n.
Hi`er*o*graph"ic	a.
Hi`er*og"ra*phy	n.
Hi`er*ol"a*try	n.
Hi`er*o*log"ic	a.
Hi`er*ol"o*gist	n.
Hi`er*ol"o*gy	n.
Hi"er*o*man`cy	n.
Hi"er*o*mar`tyr	n.
Hi`e*rom*ne"mon	n.
Hi"er*on	n.
Hi`er*on"y*mite	n.
Hi*er"o*phant	n.
Hi`er*o*phan"tic	a.
Hi`er*os"co*py	n.
Hi`er*o*the"ca	n.
Hi"er*our`gy	n.
Hi`fa*lu"tin	n.
hifi	n.
Hig"gle	v. i.
Hig`gle*dy-pig"gle*dy	adv.
Hig"gler	n.
High	v. i.
High	a.
High	adv.
High	n.
High	v. i.
high-and-mighty	a.
high"ball`	n.
High"bind`er	n.
High"-blown`	a.
highboard	n.
High"born`	a.
High"boy`	n.
High"-bred`	a.
high"brow`	n.
highbrow	adj.
High"-built`	a.
high"chair`	n.
High"-church`	a.
High"-church`ism	n.
High"-church`man	n.
High"-church`man-ship	n.
High"-col`ored	a.
High"-em*bowed `	a.
High`-en"er*gy phys`ics	n.
higher	adj. prenom.
High"er crit"i*cism	a.
Higher National Diploma	n.
higher programming language	n.
higher-ranking	adj.
high"er-up"	n.
Higher thought	adj.
high`fa*lu"tin	n.
High"-fed`	a.
High"-fin`ished	a.
High five	n.
High"-flown`	a.
High"-flushed`	a.
highflyer	n.
High"fly`ing	a.
High"-go`	n.
High"-hand`ed	a.
High"-heart`ed	a.
High"-hoe`	n.
High"-hold`er	n.
highjack	v. t.
highjack	n.
highjacking	n.
High"land	n.
highland	adj.
High"land*er	n.
High"land*ry	n.
highlight	v. t.
highlight	n.
High"-low`	n.
High"ly	adv.
highly-developed	adj.
highly-sexed	adj.
High"men	n. pl.
High"-met`tled	a.
High"-mind"ed	a.
High"-mind`ed*ness	n.
High"most`	a.
High"ness	n.
High"-palmed`	a.
high-pitched	adj.
high-power	adj.
High"-pres`sure	a.
High" priest`	n.
High"-priest`ship	n.
High"-prin`ci*pled	a.
High"-proof`	a.
High"-raised`	a.
High"-reach`ing	a.
High"-red`	a.
High"road`	n.
high road	n.
highschool	n.
High"-sea`soned	a.
High"-sight`ed	a.
High"-souled`	a.
High"-sound`ing	a.
high-speed	adj.
High"-spir`it*ed	a.
High steel	n.
high-stepping	adj.
High"-stom`ached	a.
High"-strung`	a.
High"-swell`ing	a.
Hight	n.
Hight	v. t. & i.
Hight"en*er	n.
Highth	n.
High"-toned`	a.
High"-top`	n.
High"ty-tigh"ty	a.
high-up	n.
High"way`	n.
High"way`man	n.
High"way` rob"ber*y	n.
high-voltage	adj.
highwater	n.
high-water	a.
High"-wrought`	a.
Hi"gre	n.
Hig"-ta`per	n.
Hij"e*ra	n.
Hike	v. t.
Hike	v. i.
Hike	n.
Hi"lal	a.
Hi"lar	a.
Hi*la"ri*ous	a.
Hi*lar"i*ty	n.
Hil"a*ry term`	n.
Hile	v. t.
Hile	n.
Hill	n.
Hill	v. t.
Hill"i*ness	n.
Hill"ing	n.
Hill"ock	n.
Hill"side`	n.
Hill"top`	n.
Hill"y	a.
Hilt	n.
Hilt"ed	a.
Hi"lum	n.
Hi"lus	n.
Him	pron.
Him	pron.
Hi*ma"la*yan	a.
Himantoglossum	n.
Himantopus	n.
Himp"ne	n.
Him*self"	pron.
Him*self"	pron. pl.
Him*selve"	pron.
Him*yar"ic	a.
Hin	n.
Hinayana	n.
Hinayanist	n.
Hind	n.
Hind	n.
Hind	a.
Hind"ber*ry	n.
Hind"brain`	n.
Hind"er	a.
Hin"der	v. t.
Hin"der	v. i.
Hin"der*ance	n.
Hin"der*er	n.
Hind"er*est	a.
Hind"er*ling	n.
Hind"er*most`	a.
Hind"gut`	n.
Hin"di	n.
Hind"ley"s screw`	n.
Hin"doo calendar	n.
Hin"doo*sta"nee	a.
Hindostani	n.
hindquarter	n.
hindquarters	n.
Hin"drance	n.
hindshank	n.
hindsight	n.
Hin"du	n.
Hinduism	n.
Hindustan	n.
Hindustani	adj.
Hindustani	n.
Hine	n.
Hinge	n.
Hinge	v. t.
Hinge	v. i.
Hinged	a.
Hinge"less	a.
Hink	n.
Hin"ni*ate	v. i.
Hin"ny	n.
Hin"ny	n.
Hint	v. t.
Hint	v. i.
Hint	n.
hin"ter*land`	n.
Hint"ing*ly	adv.
Hip	n.
Hip	v. t.
Hip	n.
Hip	interj.
Hip	n.
hip	a.
hipbone	n.
Hipe	n.
Hipe	v. t. & i.
hip"flask`	n.
Hip"halt`	a.
hipless	adj.
hipline	n.
Hip lock	n.
Hip*pa"ri*on	n.
hippeastrum	n.
Hipped	a.
hipped	adj.
hip"pie	n.
hip"po	n.
Hip`po*bos"ca	n.
Hippoboscidae	n.
Hip"po*camp	n.
Hip`po*cam"pal	a.
Hip`po*cam"pus	n.
Hip`po*cen"taur	n.
Hip"po*cras	n.
Hip*poc"ra*tes	n.
Hip"po*crat"ic	a.
Hippocratic oath	n.
Hip"po*crene	n.
Hip"po*crep"i*an	n.
Hip`po*crep`i*form	a.
Hip"po*dame	n.
Hip"po*drome	n.
Hip"po*drome	v. i.
Hip"po*griff	n.
Hip"po*lith	n.
Hip`po*pa*thol`o*gy	n.
Hip*poph"a*gi	n. pl.
Hip*poph"a*gism	n.
Hip*poph"a*gist	n.
Hip*poph"a*gous	a.
Hip*poph"a*gy	n.
Hip"po*phile	n.
Hip`po*pot"a*mus	n.
Hip*pot"o*my	n.
Hip*pu"ric	a.
Hip"pu*rite	n.
Hip"-roofed`	a.
Hip"shot`	a.
hip"ster	n.
Hip" tree`	pron.
Hir"cic	a.
Hir"cin	n.
Hir"cine	a.
Hire	pron.
Hire	n.
Hire	v. t.
hired	adj.
Hire"less	a.
Hire"ling	n.
Hire"ling	a.
Hire purchase	n.
Hires	pron.
Hir*sute"	a.
Hir*sute"ness	n.
Hir*tel"lous	a.
Hi*ru"dine	a.
Hir`u*din"e*a	n. pl.
hirudinean	n.
Hirundinidae	n.
Hi*ru"do	n.
Hi*run"dine	a.
Hi*run"do	n.
His	pron.
His"ing*er*ite	n.
His*pan"ic	a.
His*pan"i*cism	n.
His*pan"i*cize	v. t.
Hispaniolan	adj.
His"pid	a.
His*pid"u*lous	a.
Hiss	v. i.
Hiss	v. t.
Hiss	n.
Hiss"ing	n.
Hiss"ing*ly	adv.
Hist	interj.
His`ti*ol"o*gy	n.
His`to*gen"e*sis	n.
His`to*ge*net"ic	a.
His*tog"e*ny	n.
His*tog"ra*pher	n.
His"to*graph"ic*al	a.
His*tog"ra*phy	n.
His`to*h<ae/m"a*tin	n.
His"toid	a.
His`to*log"ic	a.
His*tol"o*gist	n.
His*tol"o*gy	n.
His*tol"y*sis	n.
His`to*lyt"ic	a.
His*ton"o*my	n.
His*toph"y*ly	n.
His*to"ri*al	a.
His*to"ri*an	n.
his*tor"ic	a.
His*tor"ic*al*ly	adv.
His*tor"i*cize	v. t.
His"to*ried	a.
His*to"ri*er	n.
His`to*ri*ette"	n.
His*tor"i*fy	v. t.
His*to`ri*og"ra*pher	n.
His*to`ri*og"ra*pher*ship	n.
His*to`ri*og"ra*phy	n.
His*to`ri*ol"o*gy	n.
His*to`ri*on"o*mer	n.
His"to*rize	v. t.
His"to*ry	n.
His"to*ry	v. t.
His*tot"o*my	n.
His"to*zyme	n.
His"tri*on	n.
His`tri*on"ic	a.
His`tri*on"i*cism	n.
his`tri*on"ics	n.
His"tri*o*nism	n.
His"tri*o*nize	v. t.
Hit	pron.
Hit	3d pers. sing. pres.
Hit	v. t.
Hit	v. i.
Hit	n.
Hit.	adj.
Hitch	v. t.
Hitch	v. i.
Hitch	v. t.
Hitch	n.
Hitch"el	n. & v. t.
hitch"hike`	v. i.
hitchhiker	n.
Hithe	n.
Hith"er	adv.
Hith"er	a.
Hith"er*most`	a.
Hith"er*to`	adv.
Hith"er*ward	adv.
hit it off	v. i.
Hitlerian	adj.
hitless	adj.
hit man	n.
hit on	v. t.
hit-or-miss	adj.
Hit"ter	n.
hitting	n.
Hit"tite	n.
Hit"torf rays	n.
Hive	v. t.
Hive	v. i.
Hive"less	a.
Hiv"er	n.
Hives	n.
Hizz	v. i.
HMO	n.
H. M. S.	n.
HN	n.
Ho	pron.
Ho	n.
Ho	prop. n.
Ho	interj.
hoactzin	n.
hoagie	n.
Hoar	a.
Hoar	n.
Hoar	v. t.
Hoard	n.
Hoard	n.
Hoard	v. t.
Hoard	v. i.
Hoard"er	n.
Hoard"ing	n.
Hoared	a.
Hoar"frost`	n.
Hoar"hound`	n.
Hoar"i*ness	n.
Hoarse	a.
Hoarse"ly	adv.
Hoars"en	v. t.
Hoarse"ness	n.
Hoar"stone`	n.
Hoar"y	a.
Ho"at*zin	n.
Hoax	n.
Hoax	v. t.
Hoax"er	n.
Hoa"zin	n.
Hob	n.
Hob	n.
Hob	n.
Hob"a*nob`	v. i.
Hob"bism	n.
Hob"bist	n.
Hob"ble	v. i.
Hob"ble	v. t.
Hob"ble	n.
Hob"ble*bush`	n.
Hob"ble*de*hoy`	n.
Hob"bler	n.
Hob"bler	n.
Hob"ble skirt	a.
Hob"bling*ly	adv.
Hob"bly	a.
Hob"by	n.
Hob"by	n.
Hob`by*hors"ic*al	n.
Hob"gob`lin	n.
Hob"i*ler	n.
Ho"bit	n.
Hob"nail`	n.
Hob"nail`	v. t.
Hob"nailed`	a.
Hob"nob`	adv.
Hob"nob`	v. i.
Hob"nob`	n.
Ho"bo	n.
Hob"or*nob`	adv.
Ho"boy	n.
Hob"son's choice"	n.
Hoche"pot	n.
Hock	n.
Hock	n.
Hock	v. t.
Hock	n.
Hock"a*more	n.
Hock"day`	n.
Hock"ey	n.
Hock"herb`	n.
Hoc"kle	v. t.
Ho"cus	v. t.
Ho"cus	n.
Ho"cus-po"cus	n.
Ho"cus-po"cus	v. t.
Hod	n.
hod" car`ri*er	n.
Hod"den*gray`	a.
Hod"dy	n.
Hod"dy*dod`dy	n.
Hodge"podge`	n.
Hodg`kin's dis*ease"	a.
Hod"man	n.
Hod"man*dod	n.
Hod"o*graph	n.
ho*dom"e*ter	n.
Hodr	prop. n.
Hoe	n.
Hoe	v. t.
Hoe	v. i.
Hoe"cake`	n.
Hoe"moth`er	n.
Ho"ful	a.
Hog	n.
Hog	v. t.
Hog	v. i.
hogan	n.
Hog"back`	n.
Hog"chain`	n.
Hog"chok`er	n.
Hog"cote`	n.
Hog"fish`	n.
Hog"frame`	n.
Hogged	a.
Hog"ger	n.
Hog"ger*el	n.
Hog"ger-pipe`	n.
Hog"ger-pump"	n.
Hog"ger*y	n.
Hog"get	n.
Hog"ging	n.
Hog"gish	a.
Hogh	n.
Hog"herd	n.
Hog`ma*nay"	n.
Hog"nose`snake"	n.
Ho"go	n.
Hog"pen`	n.
Hog"reeve`	n.
Hog"ring`er	n.
Hog's"-back`	n.
Hog"score`	n.
Hogs"head	n.
Hog"skin`	n.
Hog"sty`	n.
Hog"wash`	n.
Hog"weed`	n.
Hoi"den	n.
Hoi"den	a.
Hoi"den	v. i.
Hoi"den*hood	n.
Hoi"den*ish	a.
Hoise	v. t.
Hoist	v. t.
Hoist	n.
Hoist	p. p.
Hoist"a*way`	n.
Hoist"way`	n.
Hoit	v. i.
Hoi"ty-toi`ty	a.
Hoke"day`	n.
Ho"ker	n.
Hok*kai"do	prop. n.
Hol	a.
Hol"arc*tic	a.
Hol`as*pid"e*an	a.
Hol"cad	n.
Hold	n.
Hold	v. t.
Hold	v. i.
Hold	n.
hold"all`	n.
Hold"back`	n.
Hold"er	n.
Hold"er	n.
Hold"er-forth`	n.
Hold"fast`	n.
Hold"ing	n.
holding company	n.
holdout	n.
holdover	n.
Hold"up	n.
Hold up	v. t.
Hole	a.
Hole	n.
Hole	v. t.
Hole	v. i.
Hole in the air	a.
Hol*eth"nos	n.
holey	adj.
Hol"i*but	n.
Hol"i*dam	n.
Hol"i*day	n.
Hol`i*day	a.
holier-than-thou	adj.
Ho"li*ly	adv.
Ho"li*ness	n.
Hol"ing	n.
Hol"la	interj.
Hol"la	v. i.
Hol"land	n.
Hol`lan*daise" sauce	n.
Hol"land*er	prop. n.
Hol"land*ish	a.
Hol"lands	n.
Hol*lo"	interj. & n.
Hol"lo	v. i.
Hol*loa"	interj.
Hol"low	a.
Hol"low	n.
Hol"low	v. t.
Hol"low	adv.
Hol*low"	interj.
Hol"low	v. i.
Hol"low	v. t.
hollowed	adj.
Hol"low-heart`ed	a.
Hol"low-horned`	a.
Hol"low*ly	adv.
Hol"low*ness	n.
holloware	n.
Hol"lus*chick`ie	n. sing. &  pl.
Hol"ly	adv.
Hol"ly	n.
hollygrape	n.
Hol"ly*hock	n.
Holm	n.
Holm	n.
Holmes	n.
Hol"mi*a	n.
Hol"mi*um	n.
Hol"mos	n.
Hol"o-	n.
Hol`o*blas"tic	a.
Hol"o*caust	n.
Holocene	n.
Holocentridae	prop. n.
Holocentrus	prop. n.
holocephalan	n.
Hol`o*ceph"a*li	n. pl.
Hol`o*cryp"tic	a.
Hol`o*crys"tal*line	a.
Holstein-Friesian	n.
hol"o*gram	n.
Hol"o*graph	n.
hol"o*graph	v. t.
Hol`o*graph"ic	a.
ho*log"ra*phy	v. t.
Hol`o*he"dral	a.
Hol`o*hem`i*he"dral	a.
Hol`o*me*tab"o*la	n. pl.
Hol`o*met`a*bol"ic	a.
Ho*lom"e*ter	n.
Hol`o*phan"er*ous	a.
Hol`o*pho"tal	a.
Hol"o*phote	n.
Hol`o*phras"tic	a.
Hol`o*phyt"ic	a.
Hol`o*rhi"nal	a.
Hol`o*sid"er*ite	n.
Ho*los"te*an	a.
Ho*los"te*i	n. pl.
Hol`o*ster"ic	a.
Hol`o*stom"a*ta	n. pl.
Ho*los"to*mate	a.
Hol`o*stom"a*tous	a.
Hol"o*stome	n.
Ho*los"tra*ca	n. pl.
Hol"o*thure	n.
Hol`o*thu"ri*an	a.
Hol`o*thu`ri*oi"de*a	n. pl.
Ho*lot"ri*cha	n. pl.
Hol"our	n.
Holp	imp. & p. p.
Hol"som	a.
Hol"stein	n.
Hol"ster	n.
Hol"stered	a.
Holt	3d pers. sing. pres.
Holt	n.
Hol"we	a.
Ho"ly	a.
Ho"ly cross"	n.
Ho"ly*stone`	n.
Ho"ly*stone`	v. t.
Hom"a*canth	a.
Hom"age	n.
Hom"age	v. t.
Hom"age*a*ble	a.
Hom"a*ger	n.
Hom`a*lo*graph"ic	a.
Hom"a*loid	a.
Hom"a*rus	n.
Ho*mat"ro*pine	n.
Hom`ax*o"ni*al	a.
hombre	n.
hom"burg	n.
Home	n.
Home	n.
Home	a.
Home	adv.
home	v. i.
home"bod`y	n.
Home"born`	a.
home"bound`	a.
Home"-bred`	a.
homebuilder	n.
home"com`ing	n.
Home"-driv`en	a.
Home"-dwell`ing	a.
Home"-felt`	a.
Home"field`	n.
homegrown	adj.
Home"-keep`ing	a.
Home"-keep`ing	n.
Home"less	a.
home"less	n. pl.
homelessness	n.
Home"like`	a.
Home"li*ly	adv.
Home"li*ness	n.
Home"ling	n.
Home"ly	a.
Home"ly	adv.
Home"lyn	n.
Home"made`	a.
Ho"me*o*path	n.
Ho`me*o*path"ic	a.
Ho`me*o*path"ic*al*ly	adv.
Ho`me*op"a*thist	n.
Ho*me*op"a*thy	n.
home-schooled	a.
home"school`ing	n.
homeostasis	n.
homeostatic	a.
homeostatically	adv.
homeotherm	n.
homeothermal	adj.
homeothermism	n.
Hom"er	n.
Ho"mer	n.
Ho"mer	n.
Ho"mer	n.
Home" run`	n.
Ho*mer"ic	a.
Home"sick`	a.
Home"-speak`ing	n.
Home"spun	a.
Home"spun	n.
Home"stall`	n.
Home"stead	n.
Home"stead*er	n.
homestretch	n.
hometown	n.
Home"ward	a.
Home"ward	adv.
homework	n.
homeworker	n.
hom"ey	adj.
Hom"i*ci`dal	a.
Hom"i*cide	n.
Hom"i*form	a.
Hom"i*lete	n.
Hom`i*let"ic	a.
Hom`i*let"ics	n.
Hom"i*list	n.
Hom"i*lite	n.
Hom"i*ly	n.
hominal	adj.
Hom"ing	p. a.
hominian	adj.
hominian	n.
Hominidae	prop. n.
hominine	adj.
Hominoidea	prop. n.
Hom"i*ny	n.
Hom"ish	a.
Hom"mock	n.
Hom"mock*y	a.
Ho"mo-	n.
Ho`mo*cat`e*gor"ic	a.
Ho`mo*cen"tric	a.
Ho`mo*cer"cal	a.
Ho"mo*cer`cy	n.
Ho`mo*cer`e*brin	n.
Ho`mo*chro"mous	a.
Ho`mo*dem"ic	a.
Ho`mo*der"mic	a.
Ho"mo*der`my	n.
Hom"o*dont	a.
Ho*mod"ro*mal	a.
Ho`mo*dy*nam"ic	a.
Ho`mo*dy"na*mous	a.
Ho`mo*dy"na*my	n.
Ho`m<oe/*o*me"ri*a	n.
Ho`m<oe/*o*mer"ic	a.
Ho`m<oe/*om"er*ous	a.
Ho`m<oe/*om"e*ry	n.
Ho`m<oe/*o*mor"phism	n.
Ho`m<oe/*o*mor"phous	a.
Ho`m<oe/*o*path"ic	a.
Ho`m<oe/*o*ther"mal	a.
Ho`m<oe/*o*zo"ic	a.
Ho*mog"a*mous	a.
Ho*mog"a*my	n.
Ho`mo*gan"gli*ate	a.
Ho"mo*gene	a.
Ho`mo*ge"ne*al	a.
Ho`mo*ge"ne*al*ness	n.
Ho`mo*ge*ne"i*ty	n.
Ho`mo*ge"ne*ous	a.
Ho`mo*ge"ne*ous*ness	n.
Ho`mo*gen"e*sis	n.
Ho`mo*ge*net"ic	a.
homogenize	v. t.
homogenized	adj.
Ho*mog"e*nous	a.
Ho*mog"e*ny	n.
Ho*mog"o*nous	a.
Ho*mog"o*ny	n.
Hom"o*graph	n.
Ho`mo*graph"ic	a.
Ho*mog"ra*phy	n.
Ho*moi`op*to"ton	n.
homoiotherm	n.
Ho*moi`o*ther"mal	a.
homoiothermism	n.
Ho`moi*ou"si*an	n.
Ho`moi*ou"si*an	a.
Ho*mol"o*gate	v. t.
Ho*mol`o*ga"tion	n.
Ho`mo*log"ic*al	a.
Ho*mol`o*gin"ic	a.
Ho*mol"o*gize	v. t.
Ho*mol"o*gon	n.
Hom`o*lo*gou"me*na	n. pl.
Ho*mol"o*gous	a.
Hom`o*lo*graph"ic	a.
Hom"o*logue	n.
Ho*mol"o*gy	n.
Ho*mom"al*lous	a.
Ho`mo*mor"phic	a.
Ho`mo*mor"phism	n.
Ho"mo*mor`phy	n.
Ho*mon"o*mous	a.
Ho*mon"o*my	n.
Hom"o*nym	n.
Ho*mon"y*mous	a.
Ho*mon"y*mous*ly	adv.
Ho*mon"y*my	n.
Ho`mo*<oum/r"gan	n.
Ho`mo*ou"si*an	a.
hom`o*pho"bi*a	n.
hom`o*pho"bic	a.
Hom"o*phone	n.
Ho`mo*phon"ic	a.
ho*moph"o*nous	adj.
Ho*moph"o*ny	n.
Ho`mo*phyl"ic	a.
Ho*moph"y*ly	n.
Ho"mo*plas`my	n.
Hom"o*plast	n.
Ho`mo*plas"tic	a.
Ho"mo*plas`ty	n.
Ho*mop"la*sy	n.
Ho`mo*pol"ic	a.
Ho*mop"ter	n.
Ho*mop"te*ra	n. pl.
Ho*mop"ter*an	n.
Ho*mop"ter*ous	a.
Ho"mo*styled	a.
Ho`mo*sys*tem"ic	a.
Ho`mo*tax"i*a	n.
Ho`mo*tax"i*al	a.
Ho`mo*tax"is	n.
Ho"mo*tax`y	n.
Ho`mo*ther"mic	a.
Ho*mot"o*nous	a.
Ho*mot"ro*pal	a.
Ho"mo*ty`pal	a.
Hom"o*type	n.
Ho`mo*typ"ic	a.
Ho"mo*ty`py	n.
Ho*mun"cu*lus	n.
Hond	n.
Hone	v. i.
Hone	n.
Hone	n.
Hone	v. t.
Hon"est	a.
Hon"est	v. t.
Hon`es*ta"tion	n.
Ho*nes"te*tee	n.
Hon"est*ly	adv.
Hon"es*ty	n.
Hone"wort`	n.
Hon"ey	n.
Hon"ey	v. i.
Hon"ey	v. t.
Hon"ey-bag`	n.
Hon"ey*bee`	n.
Hon"ey*ber`ry	n.
Hon"ey*bird`	n.
Hon"ey*comb`	n.
Hon"ey*combed`	a.
honeycreeper	n.
Hon"ey*dew`	n.
Hon"ey*dew` mel"on	n.
Hon"eyed	a.
honey eater	n.
honeyflower	n.
Hon"ey*less	a.
Hon"ey*moon`	n.
Hon"ey-mouthed`	a.
Hon"ey*stone`	n.
Hon"ey*suck`er	n.
Hon"ey*suc`kle	n.
Hon"ey*suc`kled	a.
Hon"ey-sweet`	a.
Hon"ey-tongued`	a.
Hon"ey*ware`	n.
Hon"ey*wort`	n.
Hong	n.
Hong	v. t. & i.
Hon"ied	a.
Hon"i*ton lace`	n.
Honk	n.
honk"er	n.
honky	n.
honky-tonk	n.
honky-tonk	a.
Hon"or	n.
Hon"or	v. t.
Hon"or*a*ble	a.
Hon"or*a*ble*ness	n.
Hon"or*a*bly	adv.
Hon`o*ra"ri*um	n.
Hon"or*a*ry	a.
honored	adj.
honoree	n.
Hon"or*er	n.
Hon`or*if"ic	a.
Hon"or*less	a.
honour	n. & v.
honours	n.
Hon"shu	prop. n.
Hont	n. & v.
Hon"v<eacute/d	n.
Hon"v<eacute/d*s<eacute/g`	n.
Hoo	interj.
hooch	n.
-hood	n.
Hood	v. t.
Hood	n.
Hood"cap`	n.
Hood"ed	a.
Hood"less	a.
Hood"lum	n.
Hood"man	n.
Hood"man-blind`	n.
Hood" mold`ing	n.
Hoo"doo	v. t.
Hoo"doo	n.
hoodooism	n.
Hood"wink	v. t.
Hood"y	n.
Hoof	n.
Hoof	v. i.
Hoof"bound`	a.
Hoofed	a.
hoof"er	n.
hoofing	n.
Hoof"less	a.
hooflike	adj.
hoofmark	n.
Hook	n.
Hook	v. t.
Hook	v. i.
Hook"ah	n.
hook"-and-lad"der com"pa*ny	n.
hook"-and-lad"der truck	n.
hook"-billed`	a.
Hooked	a.
Hook"ed*ness	n.
Hook"er	n.
Hooke's" gear"ing	n.
Hook"let	n.
Hook"-nosed`	a.
Hook"y	a.
Hook"y	n.
Hool	a.
Hoo"lock	n.
Hoom	n.
Hoo"noo*maun	n.
Hoop	n.
Hoop	v. t.
Hoop	v. i.
Hoop	v. t.
Hoop	n.
Hoop"er	n.
Hoop"er	n.
Hoop"oe	n.
hoops	n.
hoopskirt	n.
hoop"ster	n.
hoosegow	n.
Hoo"sier	n.
Hoo"sier State	v. i.
Hoot	v. t.
Hoot	n.
Hoot down	v. t.
hoot"en*an*ny	n.
hoot"er	n.
Hoove	n.
Hoov"en	a.
Hoover	n.
hoover	v. t.
Hop	v. i.
Hop	n.
Hop	n.
Hop	v. t.
Hop	v. i.
Hop"bine`	n.
Hope	n.
Hope	n.
Hope	v. i.
Hope	v. t.
hoped-for	adj.
Hope"ful	a.
Hope"ful*ly	adv.
Hope"ite	n.
Hope"less	a.
Hop"er	n.
Hop"ing*ly	adv.
Hop"lite	n.
Hop"-o'-my-thumb"	n.
Hopped	p. a.
Hop"per	n.
Hop"per*doz`er	n.
Hop"per*ings	n.
Hop`pes*tere"	a.
Hop"pet	n.
Hop"ping	n.
Hop"ping	n.
Hop"ple	v. t.
Hop"ple	n.
Hop"ple*bush`	n.
Hop"po	n.
hopsacking	n.
Hop"scotch`	n.
hop-skip	v. i.
hop", skip", and a jump"	n.
Hop"-thumb`	n.
Hop"yard`	n.
Ho"ral	a.
Ho"ra*ly	adv.
Ho"ra*ry	a.
Ho*ra"tian	a.
Horde	n.
Hor*de"ic	a.
Hor"de*in	n.
Hor*de"o*lum	n.
Hor"dock`	n.
Hore	a.
Hore"hound`	n.
Ho*ri"zon	n.
Hor`i*zon"tal	a.
Hor`i*zon*tal"i*ty	n.
Hor`i*zon"tal*ly	adv.
Hor`mo*go*ni"um	n.
Hor*mon"al	a.
Hor"mone	n.
Horn	n.
Horn	v. t.
Horn"beak`	n.
Horn"beam`	n.
Horn"bill`	n.
Horn"blende`	n.
Horn*blend"ic	a.
Horn"blow`er	n.
Horn"book`	n.
Horn"bug`	n.
Horned	a.
Horn"ed*ness	n.
Horn"el	n.
Horneophyton	n.
Horn"er	n.
Hor"net	n.
Horn"fish`	n.
Horn"foot`	a.
Horn"i*fy	v. t.
Horn"ing	n.
Horn"ish	a.
Hor*ni"to	n.
Horn"less	a.
Horn"-mad`	a.
Hor"no*tine	n.
Horn"owl`	n.
Horn"pike`	n.
Horn"pipe`	n.
Horn"pout`	n.
Horn"snake`	n.
Horn"stone`	n.
Horn"tail`	n.
Horn"work`	n.
Horn"wort`	n.
Horn"wrack`	n.
Horn"y	a.
Horn"y-hand`ed	a.
Horn"y*head`	n.
Ho*rog"ra*phy	n.
Hor"o*loge	n.
Ho*rol"o*ger	n.
Hor`o*log"ic*al	a.
Hor`o*lo`gi*og"ra*pher	n.
Hor`o*lo`gi*o*graph"ic	a.
Hor`o*lo`gi*og"ra*phy	n.
Ho*rol"o*gist	n.
Ho*rol"o*gy	n.
Ho*rom"e*ter	n.
Hor`o*met"ric*al	a.
Ho*rom"e*try	n.
Ho*rop"ter	n.
Hor`op*ter"ic	a.
Hor"o*scope	n.
Hor"o*sco`per	n.
Ho*ros"co*py	n.
Hor*ren"dous	a.
Hor"rent	a.
Hor"ri*ble	a.
Hor"ri*ble*ness	n.
Hor"ri*bly	adv.
Hor"rid	a.
Hor"rid*ly	adv.
Hor"rid*ness	n.
Hor*rif"ic	a.
Hor`ri*fi*ca"tion	n.
Hor"ri*fy	v. t.
Hor*rip`i*la"tion	n.
Hor*ris"o*nant	a.
Hor*ris"o*nous	a.
Hor"ror	n.
Hor"ror-stick`en	a.
Hor"ror-struck`	a.
Hors` de com`bat"	n.
Horse	v. t.
Horse	v. i.
Horse"back`	n.
horsebean	n.
horsebox	n.
horsebrier	n.
horse"cart`	n.
Horse`-chest"nut	n.
horsecloth	n.
Horse"-drench`	n.
Horse"fish`	n.
Horse"flesh`	n.
Horse"fly`	n.
Horse"foot`	n.
Horse" Guards`	n.
Horse"head`	n.
Horse"hide`	n.
Horse"-jock`ey	n.
Horse"knop`	n.
horse" lat`i*tude	n.
Horse"laugh`	n.
Horse"-leech`	n.
Horse"-leech`er*y	n.
Horse"less	a.
Horse"-lit`ter	n.
Horse"man	n.
Horse"man*ship	n.
horsemeat	n.
Horse"mint`	n.
Horse"nail`	n.
Horse"play`	n.
Horse"pond`	n.
Horse" pow`er	n.
Horse"rake`	n.
horseshit	n.
horse"show`	n.
Horse"shoe`	n.
Horse"shoe`ing	n.
Horse"sho`er	n.
Horse"tail`	n.
horse-trade	v. i. & t.
horse-trading	n.
horse-trail	n.
Horse"weed`	n.
Horse"whip`	n.
Horse"whip`	v. t.
Horse"wom`an	n.
Horse"wood`	n.
Horse"worm`	n.
Hors"i*ness	n.
Hors"ly	a.
Hors"y	a.
Hor*ta"tion	n.
Hor"ta*tive	a.
Hor"ta*tive	n.
Hor"ta*to*ry	a.
Hor*ten"sial	a.
Hor"ti*cul`tor	n.
Hor`ti*cul"tur*al	a.
Hor"ti*cul`ture	n.
Hor`ti*cul"tur*ist	n.
Hor"tu*lan	a.
Hor"tus sic"cus	n.
Ho*san"na	n.
Hose	n.
Ho"sen	n. pl.
hosepipe	n.
Ho"sier	n.
Ho"sier*y	n.
Hos"pice	n.
Hos"pi*ta*ble	a.
Hos"pi*ta*ble*ness	n.
Hos"pi*ta*bly	adv.
Hos"pi*tage	n.
Hos"pi*tal	n.
Hos"pi*tal	a.
Hos"pi*tal*er	n.
hospitalisation	n.
hospitalisation insurance	n.
hos"pi*tal*ise	v. t.
Hos"pi*tal*ism	n.
Hos`pi*tal"i*ty	n.
Hos"pi*tal*ize	v. t.
Hos"pi*tate	v. i.
Hos"pi*tate	v. t.
Hos*pi"ti*um	n.
Hos"po*dar`	n.
Host	n.
Host	n.
Host	n.
Host	v. t.
Host	v. i.
Hosta	prop. n.
Hostaceae	prop. n.
Hos"tage	n.
Hos"tel	n.
Hos"tel*er	n.
Hos"tel*ry	n.
Host"ess	n.
Host"ess-ship	n.
Hos"tie	n.
Hos"tile	a.
Hos"tile	n.
Hos"tile*ly	adv.
hostile takeover	n.
hostilities	n. pl.
Hos*til"i*ty	n.
Hos"til*ize	v. t.
Host"ing	n.
Hos"tler	n.
Host"less	a.
Host plant	n.
Hot	imp. & p. p.
Hot	a.
Hot"bed`	n.
Hot" blast`	a.
Hot"-brained`	a.
Hot bulb	n.
Hot"coc`kles	n.
hot" cross bun`	n.
hot" dog`	n.
hot" dog"	exclamation
Hote	v. t. & i.
hotei-chiku	n.
Ho*tel"	n.
H<ocir/tel`-de-ville"	n.
H<ocir/tel`-Dieu"	n.
hotelier	n.
Hot"en	p. p.
Hot"foot`	adv.
Hot"-head`	n.
Hot"-head`ed	a.
hotheaded	adj.
Hot"house`	n.
Hot"-liv`ered	a.
Hot"ly	adv.
Hot"-mouthed`	a.
Hot"ness	n.
Hot"press`	v. t.
Hot"pressed`	a.
Hot"-short`	a.
Hot"shot`	n.
hot"shot`	a.
Hot"-spir`it*ed	a.
Hot"spur`	n.
Hot"spur`	a.
Hot"ten*tot	n.
Hot"ten*tot*ism	n.
Hottonia	n.
hot-wire	v. t.
Hou"dah	n.
Hough	n.
Hough	v. t.
Hough	n.
Hough	v. t.
houhere	n.
Hou"let	n.
Hoult	n.
Hound	n.
Hound	v. t.
Hound"fish	n.
Hound"ing	n.
Hound's"-tongue`	n.
Houp	n.
Hour	n.
Hour"glass`	n.
Hou"ri	n.
Hour"ly	a.
Hour"ly	adv.
Hours	n. pl.
Hous"age	n.
House	n.
House	v. t.
House	v. i.
houseboat	n.
House"bote`	n.
housebound	adj.
house"break`	v. t.
House"break`er	n.
House"break`ing	n.
housebroken	adj.
House"build`er	n.
House"carl`	n.
housecoat	n.
housecraft	n.
housedog	n.
housefather	n.
house"fly`	n.
houseful	n.
houseguest	n.
House"hold`	n.
House"hold`	a.
House"hold`er	n.
housekeep	v. i.
House"keep`er	n.
House"keep`ing	n.
House"keep`ing	a.
Hou"sel	n.
Hou"sel	v. t.
House"leek`	n.
House"less	a.
House"less*ness	n.
House"line`	n.
House"ling`	a.
House"maid`	n.
houseman	n.
housemaster	n.
House"mate`	n.
houseplant	n.
house-proud	adj.
house-raising	n.
House"room`	n.
house-to-house	adj.
house"top`	n.
house-trained	adj.
housetrained	adj.
House"warm`ing	n.
House"wife`	n.
House"wife`	v. t.
House"wife`ly	a.
House"wif`er*y	n.
House"work`	n.
House"wright`	n.
Hous"ing	n.
Hous"ing	n.
housings	n.
Hous"ling	a.
Houss	n.
Hous*to"ni*a	n.
Hou"tou	n.
Houttuynia	n.
Houve	n.
Hou*yhnhnm"	n.
Hove	imp. & p. p.
Hove	v. i. & t.
Hove	v. i.
Hov"el	n.
Hov"el	v. t.
Hov"el*er	n.
Hov"el*ing	n.
Ho"ven	p. p.
Ho"ven	a.
Hov"er	n.
Hov"er	v. i.
hoya	n.
hov"er*craft	n.
Hov"er*er	n.
Hov"er-hawk`	n.
Hov"er*ing*ly	adv.
How	adv.
How*adj"i	n.
How*be"it	conj.
How"dah	n.
How"dy	n.
How"el	n.
How"el	v. t.
How"ell	n.
How*ev"er	adv.
How*ev"er	conj.
How"itz	n.
How"itz*er	n.
How"ker	n.
Howl	v. i.
Howl	v. t.
Howl	n.
Howl"er	n.
Howl"et	n.
Howp	v. i.
How"so	adv.
How`so*ev"er	adj. & conj.
Howve	n.
hoya	n.
Hox	v. t.
Hoy	n.
Hoy	interj.
hoya	n.
Hoy"den	n.
Hoy"man	n.
HQ	n.
hr	n.
HS1	n.
HS2	n.
Hsien	n.
huamachil	n.
Hua*na"co	n.
Hua*ra"che	n.
Huascaran	prop. n.
huastorium	n.
Hub	n.
Hub"ble-bub`ble	n.
Hub"ble Tel"e*scope	n.
Hub"bub	n.
Hub"by	a.
hub"by	n.
H<uum/b"ner*ite	n.
Huch	n.
Huck	v. i.
Huck"a*back	n.
Huc"kle	n.
Huc"kle-backed`	a.
Huc"kle*ber`ry	n.
Huck"ster	n.
Huck"ster	v. i.
Huck"ster*age	n.
Huck"ster*er	n.
Huck"stress	n.
Hud	n.
Hud"dle	v. i.
Hud"dle	v. t.
Hud"dle	n.
Hud"dler	n.
Hudge	n.
Hu`di*bras"tic	a.
Hudsonia	n.
Hud*so"ni*an	a.
Hue	n.
Hue	n.
Hued	a.
Hue"less	a.
Hu"er	n.
Huff	v. t.
Huff	v. i.
Huff	n.
Huff"cap`	n.
Huff"er	n.
Huff"i*ness	n.
Huff"ing*ly	adv.
Huff"ish	a.
Huff"y	a.
Hug	v. i.
Hug	v. t.
Hug	n.
Huge	a.
Hug"ger	n.
Hug"ger	v. t. & i.
Hug"ger-mug`ger	n.
Hug"ger-mug`ger	a.
hugging	n.
Hug"gle	v. t.
hug-me-tight	n.
Hugoesque	adj.
Hugueninia	n.
Hu"gue*not	n.
Hu"gue*not*ism	n.
Hu"gy	a.
Hu"ia bird`	n.
Hui"sher	v. t.
Huke	n.
Hu"lan	n.
Hulch	n.
Hulch"y	a.
Hulk	n.
Hulk	v. t.
Hulk"ing	a.
Hull	n.
Hull	v. t.
Hull	v. i.
Hul`la*ba*loo"	n.
Hulled	a.
Hull"er	n.
Hul*lo"	interj.
Hull"y	a.
Hu"lo*ist	n.
Hu"lo*the*ism	n.
Hul"ver	n.
Hum	v. i.
Hum	v. t.
Hum	n.
Hum	interj.
Hu"man	a.
Hu"man	n.
Hu"man*ate	a.
Hu*mane"	a.
Hu*man"ics	n.
Hu*man"i*fy	v. t.
Hu"man*ism	n.
humanisation	n.
humanise	v.
Hu"man*ist	n.
Hu`man*is"tic	a.
Hu*man`i*ta"ri*an	a.
Hu*man`i*ta"ri*an	n.
Hu*man`i*ta"ri*an*ism	n.
Hu`ma*ni"tian	n.
Hu*man"i*ty	n.
Hu*man`i*za"tion	n.
Hu"man*ize	v. t.
Hu"man*ize	v. i.
Hu"man*i`zer	n.
Hu"man*kind`	n.
humanlike	adj.
Hu"man*ly	adv.
Hu"man*ness	n.
Hu"mate	n.
Hu*ma"tion	n.
Hum"bird`	n.
Hum"ble	a.
Hum"ble	a.
Hum"ble	v. t.
Hum"ble*bee`	n.
Hum"ble*head`	n.
Hum"ble*ness	n.
Hum"bler	n.
Hum"bles	n. pl.
Hum"blesse	n.
Hum"bly	adv.
Hum"bug`	n.
Hum"bug`	v. t.
Hum"bug`ger	n.
Hum"bug`ger*y	n.
Hum"drum`	a.
Hum"drum`	n.
Hu*mect"	v. t.
Hu*mec"tant	a.
Hu`mec*ta"tion	n.
Hu*mec"tive	a.
Hu"mer*al	a.
Hu"me*rus	n.
Hu"mic	a.
Hu`mi*cu*ba"tion	n.
Hu"mid	a.
humidification	n.
humidifier	n.
humidify	v. t.
Hu*mid"i*ty	n.
Hu"mid*ness	n.
Hu"mi*fuse	a.
Hu*mil"i*ant	a.
Hu*mil"i*ate	v. t.
humiliated	adj.
humiliating	adj.
Hu*mil`i*a"tion	n.
Hu*mil"i*ty	n.
Hu"min	n.
Hu*mi"ri	n.
Hum"ite	n.
Hum"mel	v. t.
Hum"mel	a.
Hum"mel*er	n.
Hum"mer	n.
Hum"ming	a.
Hum"ming	n.
hummingbird	n.
Hum"mock	n.
Hum"mock*ing	n.
Hum"mock*y	a.
Hum"mum	n.
Hu"mor	n.
Hu"mor	v. t.
Hu"mor*al	a.
Hu"mor*al*ism	n.
Hu"mor*al*ist	n.
Hu"mor*ism	n.
Hu"mor*ist	n.
Hu`mor*is"tic	a.
Hu"mor*ize	v. t.
Hu"mor*less	a.
Hu"mor*ous	a.
Hu"mor*ous*ly	adv.
Hu"mor*ous*ness	n.
Hu"mor*some	a.
Hu"mor*some*ly	adv.
Hu"mor*some*ness	n.
humour	n.
humourous	adj.
Hump	n.
Hump	v. t.
Hump"back`	n.
Hump"backed`	a.
Hump"backed` salm"on	n.
Humped	a.
Humph	interj.
Hump"less	a.
Hump"-shoul`dered	a.
Hump"y	a.
Hum"strum`	n.
Hu"mu*lin	n.
Hu"mus	n.
Hun	n.
Hunch	n.
Hunch	v. t.
Hunch"back`	n.
Hunch"backed`	a.
hunched	adj.
Hun"dred	n.
Hun"dred	a.
Hun"dred*er	n.
Hun"dred*fold`	n.
Hun"dredth	a.
Hun"dredth	n.
Hun"dred*weight`	n.
Hung	imp. & p. p.
Hun*ga"ri*an	a.
Hun"ga*ry	n.
Hun"ger	n.
Hun"ger	v. i.
Hun"ger	v. t.
Hun"ger-bit`	a.
Hun"gered	a.
Hun"ger*er	n.
Hun"ger*ly	a.
Hun"ger*ly	adv.
Hun"ger-starve`	v. t.
Hun"gred	a.
Hun"gri*ly	adv.
hungriness	n.
Hun"gry	a.
Hunk	n.
Hun"ker	n.
Hun"ker down	v.
Hun"ker*ism	n.
Hun"kers	n. pl.
Hunks	n.
Hunk"y	a.
Hunnemannia	n.
Hunnish	a.
Hunt	v. t.
Hunt	v. i.
Hunt	n.
Hunt"-count`er	n.
Hunt"e	n.
Hunt"er	n.
Hun*te"ri*an	a.
Hunt"ing	n.
Hunt"ress	n.
Hunts"man	n.
Hunts"man*ship	n.
Hunt's"-up`	n.
Hur"den	n.
Hur"dle	n.
Hur"dle	v. t.
Hur"dle*work`	n.
Hurds	n.
Hur"dy-gur`dy	n.
Hur*ka"ru	n.
Hurl	v. t.
Hurl	v. i.
Hurl	n.
Hurl"bat`	n.
Hurl"bone`	n.
Hurl"er	n.
Hurl"ing	n.
Hurl"wind`	n.
Hur"ly	n.
Hur"ly-bur`ly	n.
Hu*ro"ni*an	a.
Hu"ron-Ir`o*quous"	n.
Hu"rons	n. pl.
Hurr	v. i.
Hur*rah"	interj.
Hur*rah"	n.
Hur*rah"	v. i.
Hur*rah"	v. t.
Hur"ri*cane	n.
Hur`ri*ca"no	n.
Hur"ried	a.
Hur"ri*er	n.
Hur"ries	n.
Hur"ry	v. t.
Hur"ry	v. i.
Hur"ry	n.
Hur"ry*ing*ly	adv.
Hur"ry-skur`ry	adv.
Hurst	n.
Hurt	n.
Hurt	v. t.
Hurt"er	n.
Hurt"er	n.
Hurt"er	n.
Hurt"ful	a.
hurting	n.
hurting	adj.
Hur"tle	v. i.
Hur"tle	v. t.
Hur"tle*ber`ry	n.
Hurt"less	a.
Hus"band	n.
Hus"band	v. t.
Hus"band*a*ble	a.
Hus"band*age	n.
Hus"band*less	a.
Hus"band*ly	a.
Hus"band*man	n.
Hus"band*ry	n.
Hush	v. t.
Hush	v. i.
Hush	n.
Hush	a.
hushed	adj.
hushed-up	adj.
Hush"er	n.
Hush"ing	n.
Husk	n.
Husk	v. t.
Husked	a.
Hus"ki*ly	adv.
Hus"ki*ness	n.
Husk"ing	n.
Husk"y	a.
Hus"ky	a.
Hus"ky	a.
Hus"ky	n.
Hu"so	n.
Hus*sar"	n.
Huss"ite	n.
Hus"sy	n.
Hus"sy	n.
Hus"tings	n. pl.
Hus"tle	v. t.
Hus"tle	v. i.
Hus"wife	n.
Hus"wife	v. t.
Hus"wife*ly	a.
Hus"wife*ry	n.
Hut	n.
Hutch	v. t. & i.
Hutch	n.
Hutch	v. t.
Hutch`un*so"ni*an	n.
Hut*to"ni*an	a.
Hut"ton*ing	n.
Hux"ter	n. & v. i.
Huy*ghe"ni*an	a.
Huzz	v. i.
Huz*za"	interj.
Huz"za	n.
Huz*za"	v. i.
Huz*za"	v. t.
Hy	a.
Hy"a*cine	n.
Hy"a*cinth	n.
Hy`a*cin"thi*an	a.
Hy`a*cin"thine	a.
Hyades	n.
Hy"a*des	n. pl.
hyaena	n.
Hyaenidae	prop. n.
Hy*a"le*a	n.
Hy`a*les"cence	n.
hyalin	n.
Hy"a*line	a.
Hy"a*line	n.
Hy"a*lite	n.
Hy*al"o*graph	n.
Hy`a*log"ra*phy	n.
Hy"a*loid	a.
Hy`a*lo*ne"ma	n.
Hy*al"o*phane	n.
Hy`a*lo*spon"gi*a	n. pl.
Hy*al"o*type	n.
Hy*ber"na*cle	a.
Hyb"o*dont	a.
Hyb"o*dus	n.
Hy"brid	n.
Hy"brid	a.
Hy"brid*ism	n.
Hy"brid*ist	n.
Hy*brid"i*ty	n.
Hy"brid*i`za*ble	a.
Hy`brid*i*za"tion	n.
Hy"brid*i`ze	v. t.
Hy"brid*ize	v. i.
Hy"brid*i`zer	n.
Hy"brid*ous	a.
Hyd"age	n.
Hy`dan*to"ic	a.
Hy*dan"to*in	n.
Hy"da*tid	n.
Hy*dat"i*form	a.
Hy"da*toid	a.
Hy"dr-	n.
Hy*drach"nid	n.
Hy*drac"id	n.
Hy`dra*cryl"ic	a.
Hy`drac*tin"i*an	n.
Hy*dr<ae/"mi*a	n.
Hy"dra*gogue	a.
Hy*dram"ide	n.
Hy*dram"ine	n.
Hy*dran"ge*a	peop. n.
Hydrangeaceae	prop. n.
Hy"drant	n.
Hy"dranth	n.
Hy*drar"go*chlo"ride	n.
Hy*drar"gy*rate	a.
Hy*drar"gy*rism	n.
Hy*drar"gy*rum	n.
Hy`drar*thro"sis	n.
Hy*dras"tine	n.
Hy"dra-taint`ed	a.
Hy"drate	n.
Hy"drate	v. t.
Hy"dra*ted	a.
Hy*dra"tion	n.
Hy*drau"lic	a.
Hy*drau"lic*al	a.
Hy*drau"li*con	n.
Hy*drau"lics	n.
Hy"dra*zine	n.
Hy"dren*ceph"s*loid	a.
Hy"dri*a	n.
Hy"dri*ad	n.
Hy"dric	a.
Hy"dride	n.
Hy"dri*form	a.
Hy*dri"na	n. pl.
Hy*dri"o*date	n.
Hy`dri*od"ic	a.
Hy*dri"o*dide	n.
Hy"dro	n.
Hy"dro-	n.
Hy"dro*bi"plane	n.
Hy`dro*bil`i*ru"bin	n.
Hy`dro*bran`chi*a"ta	n. pl.
Hy`dro*bro"mate	n.
Hy`dro*bro"mic	a.
Hy`dro*bro"mide	n.
Hy`dro*car"bon	n.
Hy`dro*car`bo*na"ceous	a.
Hy`dro*car"bon*ate	n.
Hy`dro*car`bo*sty"ril	n.
Hy`dro*car"bu*ret	n.
Hy`dro*cau"lus	n.
Hy`dro*cele	n.
Hy`dro*ce*phal"ic	a.
Hy`dro*ceph"a*loid	a.
Hy`dro*ceph"a*lous	a.
Hy`dro*ceph"a*lus	n.
Hy`dro*chlo"rate	n.
Hy`dro*chlo"ric	a.
Hy`dro*chlo"ride	n.
Hy`dro*co*ral"li*a	n. pl.
Hy`dro*cy"a*nate	n.
Hy`dro*cy*an"ic	a.
Hy`dro*cy"a*nide	n.
Hy`dro*dy*nam"ic	a.
Hy`dro*dy*nam"ics	n.
Hy`dro*dy`na*mom"e*ter	n.
Hy`dro-e*lec"tric	a.
Hy`dro-ex*tract"or	n.
Hy`dro*fer`ri*cy*an"ic	n.
Hy`dro*fer`ro*cy*an"ic	a.
Hy`dro*flu"ate	n.
Hy`dro*flu*or"ic	a.
Hy`dro*flu`o*sil"i*cate	n.
Hy`dro*flu`o*si*lic"ic	a.
Hy`dro*gal*van"ic	a.
Hy"dro*gen	n.
Hy"dro*gen*ate	v. t.
Hy`dro*gen*a"tion	n.
Hy"dro*gen*ide	n.
Hy`dro*ge"ni*um	n.
Hy"dro*gen*ize	v. t.
Hy*drog"e*nous	a.
Hy*drog"no*sy	n.
Hy"drog*ode	n.
Hy*drog"ra*pher	n.
Hy`dro*graph"ic	a.
Hy*drog"ra*phy	n.
Hy*drog"u*ret	n.
Hy"droid	a.
Hy*droi"de*a	n. pl.
Hy`dro*ki*net"ic	a.
Hy"dro*lase	n.
Hy`dro*log"ic*al	a.
Hy*drol"o*gist	n.
Hy*drol"o*gy	n.
Hy*drol"y*sis	n.
Hy`dro*lyt"ic	a.
Hy`dro*mag"ne*site	n.
Hy"dro*man`cy	n.
Hy`dro*man"tic	a.
Hy`dro*me*chan"ics	n.
Hy`dro*me*du"sa	n.
Hy"dro*mel	n.
Hy`dro*mel*lon"ic	a.
Hy`dro*met`al*lur"gic*al	a.
Hy`dro*met"al*lur`gy	n.
Hy`dro*me"te*or	n.
Hy`dro*me`te*or`o*log"ic*al	a.
Hy`dro*me`te*or*ol"o*gy	n.
Hy*drom"e*ter	n.
Hy`dro*met"ric	a.
Hy`dro*met"ro*graph	n.
Hy*drom"e*try	n.
Hy`dro*mi"ca	n.
Hy`dro*ne*phro"sis	n.
Hy"dro*path	n.
Hy`dro*path"ic	a.
Hy*drop"a*thist	n.
Hy*drop"a*thy	n.
Hy`dro*per`i*to*ne"um	n.
Hy"dro*phane	n.
Hy*droph"a*nous	a.
Hy"dro*phid	n.
Hy`dro*phlo"rone	n.
Hy`dro*pho"bi*a	n.
Hy`dro*phob"ic	a.
Hy"dro*pho`by	n.
Hy*droph"o*ra	n. pl.
Hy"dro*phore	n.
Hy`dro*phyl"li*um	n.
Hy"dro*phyte	n.
Hy*droph`y*tol"o*gy	n.
Hy*drop"ic	a.
Hy*drop"ic*al*ly	adv.
Hy"dro*pi`per	n.
Hy"dro*plane	n.
Hy"dro*plane	v. i.
Hy`dro*pneu*mat"ic	a.
Hy`dro*pneu*mat"ic gun carriage	n.
Hy"dro*pult	n.
Hy`dro*qui"none	n.
Hy`dro*rhi"za	n.
Hy"dro*salt`	n.
Hy"dro*scope	n.
Hy"dro*some	n.
Hy`dro*sor"bic	a.
Hy"dro*sphere	n.
Hy"dro*stat	n.
Hy`dro*stat"ic	a.
Hy`dro*stat"ic*al*ly	adv.
Hy`dro*sta*ti"cian	n.
Hy`dro*stat"ics	n.
Hy`dro*sul"phate	n.
Hy`dro*sul"phide	n.
Hy`dro*sul"phite	n.
Hy`dro*sul"phu*ret	n.
Hy`dro*sul"phu*ret`ed	a.
Hy`dro*sul*phu"ric	a.
Hy`dro*sul"phur*ous	a.
Hy`dro*tel"lu*rate	n.
Hy`dro*tel*lu"ric	a.
Hy`dro*the"ca	n.
Hy`dro*ther`a*peu"tics	n.
Hy`dro*ther"a*py	n.
Hy`dro*ther"mal	a.
Hy`dro*tho"rax	n.
Hy*drot"ic	a.
Hy*drot"ic*al	a.
Hy"dro*trope	n.
Hy`dro*trop"ic	a.
Hy*drot"ro*pism	n.
Hy"drous	a.
Hy`dro*xan"thane	n.
Hy`dro*xan"thic	a.
Hy*drox"ide	n.
Hy*drox"y-	n.
Hy*drox`yl*am"ine	n.
hydroxymethyl	n.
hydroxyproline	n.
Hy`dro*zo"a	n. pl.
Hy`dro*zo"al	a.
Hy`dro*zo"<oum/n	n.
Hy"dru*ret	n.
Hy"drus	n.
Hye	n. & v.
Hy*e"mal	a.
Hy"e*mate	v. i.
Hy`e*ma"tion	n.
Hy"en	n.
Hy*e"na	n.
Hy"e*tal	a.
Hy"e*to*graph	n.
Hy`e*to*graph"ic	a.
Hy`e*tog"ra*phy	n.
Hy`e*tol"o*gy	n.
Hy*ge"ia	n.
Hy*ge"ian	a.
Hy"ge*ist	n.
Hy"gie*ist	n.
Hy"gi*ene	n.
Hy`gi*en"ic	a.
Hy`gi*en"ics	n.
Hy"gi*en*ism	n.
Hy"gi*en*ist	n.
Hy`gi*ol"o*gy	n.
Hy"grine	n.
Hy"gro*deik	n.
Hy"gro*graph	n.
Hy*grol"o*gy	n.
Hy*grom"e*ter	n.
Hy`gro*met"ric	a.
Hy*grom"e*try	n.
Hy*groph"a*nous	a.
Hy`groph*thal"mic	a.
Hy"gro*plasm	n.
Hy"gro*scope	n.
Hy`gro*scop"ic	a.
Hy`gro*sco*pic"i*ty	n.
Hy`gro*stat"ics	n.
Hyke	n.
Hyk"sos	n.
Hy"l<ae/*o*saur`	n.
Hy*lar"chi*cal	a.
Hy"le*o*saur"	n.
Hyl"ic	a.
Hy"li*cist	n.
Hy"lism	n.
Hy"lo*bate	n.
Hy*lo"des	n.
Hy"lo*ism	n.
Hy"lo*ist	n.
Hy*lop"a*thism	n.
Hy*lop"a*thist	n.
Hy*loph"a*gous	a.
Hy"lo*the*ism	n.
Hy"lo*the*ist	n.
Hy`lo*zo"ic	a.
Hy`lo*zo"ism	n.
Hy`lo*zo"ist	n.
Hy*mar"	n.
Hy"men	n.
Hy"men	n.
hymenal	adj.
Hy`me*ne"al	a.
Hy`me*ne"al	n.
Hy*me"ni*um	n.
Hymenogastrales	n.
Hy`me*nog"e*ny	n.
Hy`me*no*my*ce"tes	n. pl.
Hy*men"o*phore	n.
Hy`me*nop"ter	n.
Hy`me*nop"te*ra	n. pl.
Hy`me*nop"ter*al	a.
Hy`me*nop"ter*an	n.
hymenopteron	n.
Hymn	n.
Hymn	v. t.
Hymn	v. i.
Hym"nal	n.
Hym"nic	a.
Hymn"ing	a.
Hymn"ing	n.
Hym"nist	n.
Hym"no*dy	n.
Hym*nog"ra*pher	n.
Hym*nog"ra*phy	n.
Hym*nol"o*gist	n.
Hym*nol"o*gy	n.
Hymp"ne	n.
Hynd"reste	a.
Hyne	n.
Hy"o-	n. pl.
Hy`o*glos"sal	a.
Hy`o*glos"sus	n.
Hy"oid	a.
Hy"oid	n.
Hy*oid"e*al	a.
Hy`o*man*dib"u*lar	a.
Hy`o*men"tal	a.
Hy`o*pas"tron	n.
Hy*os"cine	n.
Hy`os*cy"a*mine	n.
Hy`os*cy"a*mus	n.
Hy`o*ster"nal	a.
Hy`o*ster"num	n.
Hy`o*styl"ic	a.
Hyp	n.
Hyp	v. t.
Hy*p<ae/"thral	a.
Hy*pal"la*ge	n.
Hyp`al*le"lo*morph	n.
Hy*pan"thi*um	n.
Hy`pa*poph"y*sis	n.
Hy`par*te"ri*al	a.
Hy*pas"pist	n.
Hy*pax"i*al	a.
Hy"per-	a.
hyperactivity	n.
Hy`per*<ae/"mi*a	n.
Hy`per*<ae/s*the"si*a	n.
Hy`per*a*poph"y*sis	n.
Hy`per*as"pist	n.
Hy`per*bar"ic	a.
Hy`per*bat"ic	a.
Hy*per"ba*ton	n.
Hy*per"bo*la	n.
Hy*per"bo*le	n.
Hy`per*bol"ic	a.
Hy`per*bol"ic*al*ly	adv.
Hy`per*bol"i*form	a.
Hy*per"bo*lism	n.
Hy*per"bo*list	n.
Hy*per"bo*lize	v. i.
Hy*per"bo*lize	v. t.
Hy*per"bo*loid	n.
Hy*per"bo*loid	a.
Hy`per*bo"re*an	a.
Hy`per*bo"re*an	n.
Hy`per*car"bu*ret`ed	a.
Hy`per*cat`a*lec"tic	a.
Hy`per*chlo"ric	a.
Hy`per*chro"ma*tism	n.
Hy`per*crit"ic	n.
Hy`per*crit"ic	a.
Hy`per*crit"ic*al	a.
Hy`per*crit"ic*al*ly	adv.
Hy`per*crit"i*cise	v. t.
Hy`per*crit"i*cism	n.
hypercube	n.
Hy`per*di*crot"ic	a.
Hy`per*di"cro*tism	n.
Hy`per*di"cro*tous	a.
Hy`per*du*li"a	n.
Hy"per*du`ly	n.
Hy`per*es*the"si*a	n.
Hy"per*gol	a.
Hy`per*gol"ic	a.
Hy*per"i*cum	n.
hyperinflation	n.
Hy`per*i*no"sis	n.
Hy*pe"ri*on	n.
Hy`per*ki*ne"sis	n.
Hy`per*ki*net"ic	a.
Hy`per*met`a*mor"pho*sis	n.
Hy*per"me*ter	n.
Hy`per*met"ric*al	a.
Hy`per*me*tro"pi*a	n.
Hy`per*myr`i*o*ra"ma	n.
hypernym	n.
hypernymy	n.
Hy`per*o*ar"ti*a	n. pl.
Hyperodontidae	prop. n.
hyperon	n.
Hyperoodon	prop. n.
hy"per*ope	n.
Hy`per*o"pi*a	n.
Hy`per*or*gan"ic	a.
hy`per*or"tho*dox	a.
Hy`per*or"tho*dox`y	n.
Hy`per*o*tre"ta	n. pl.
Hy`per*ox"ide	n.
Hy`per*ox"y*gen*a`ted	a.
Hy`per*ox`y*mu"ri*ate	n.
Hy`per*ox`y*mu`ri*at"ic	a.
Hy`per*phys"ic*al	a.
Hy`per*pla"si*a	n.
Hy`per*plas"tic	a.
Hy`perp*n<oe/"a	n.
Hy`per*py*rex"i*a	n.
Hy`per*se*cre"tion	n.
Hy`per*sen`si*bil"i*ty	n.
hy`per*son"ic	n.
hy"per*space	n.
hy"per*sphere	n.
Hy"per*sthene	n.
Hy`per*sthen"ic	a.
hypertension	n.
hypertensive	n.
hypertensive	n.
hyperthermia	n.
Hy`per*thet"ic*al	a.
Hy`per*thyr"i*on	n.
hy`per*ton"ic	n.
hyperthyroidism	n.
Hy`per*troph"ic	a.
Hy*per"tro*phied	a.
Hy*per"tro*phy	n.
hyperventilate	v. i.
hyperventilation	n.
hypha	n.
Hyphantria	n.
Hy"ph<ae/	n. pl.
Hy"phen	n.
Hy"phen	v. t.
Hy"phen*a`ted	a.
Hyphenated American	n. pl.
Hy*pid`i*o*mor"phic	a.
Hyp`i*no"sis	n.
Hyp`na*gog"ic	a.
Hyp"no*bate	n.
Hyp"no*cyst	n.
Hyp`no*gen"ic	a.
Hyp*nol"o*gist	n.
Hyp*nol"o*gy	n.
Hyp"no*scope	n.
Hyp*no"sis	n.
Hyp*not"ic	a.
Hyp*not"ic	n.
Hyp"no*tism	n.
Hyp"no*tist	n.
Hyp`no*ti*za"tion	n.
Hyp"no*tize	v. t.
Hyp"no*ti`zer	n.
Hyp"num	n.
Hy"po-	n.
Hy"po	n.
Hy`po*a"ri*an	a.
Hy`po*a"ri*on	n.
Hy"po*blast	n.
Hy`po*blas"tic	a.
Hy*pob"o*le	n.
Hy`po*bran"chi*al	a.
Hy"po*carp	n.
Hy`po*car`po*ge"an	a.
Hyp"o*caust	n.
Hy`po*chlo"rite	n.
Hy`po*chlo"rous	a.
Hy`po*chon"dres	n. pl.
Hy`po*chon"dri*a	n.
Hy`po*chon"dri*ac	a.
Hy`po*chon"dri*ac	n.
Hy`po*chon"dri*a*cal	a.
Hy`po*chon"dri*a*cism	n.
Hy`po*chon"dri*a*sis	n.
Hy`po*chon"dri*asm	n.
Hy`po*chon"dri*um	n.
Hy`po*chon"dry	n.
Hyp"o*cist	n.
Hy`po*clei"di*um	n.
Hyp`o*co*ris"tic	a.
Hyp`o*cra*ter"i*form	a.
Hyp`o*cra*ter`i*mor"phous	a.
Hy*poc"ri*sy	n.
Hyp"o*crite	n.
Hyp"o*crite*ly	adv.
Hyp`o*crit"ic	a.
Hyp`o*crit"ic*al	a.
Hyp`o*crys"tal*line	a.
Hy`po*cy"cloid	n.
Hyp`o*dac"ty*lum	n.
Hyp"o*derm	n.
Hyp`o*der"ma	n.
Hyp`o*der*mat"ic	a.
Hyp`o*der"mic	a.
hyp`o*der"mic	n.
Hyp`o*der"mic need"le	n.
Hyp`o*der"mic syr"inge	n.
Hyp`o*der"mis	n.
Hyp`o*di*crot"ic	a.
Hyp`o*g<ae/"ic	a.
Hyp`o*gas"tric	a.
Hyp`o*gas"tri*um	n.
Hyp`o*ge"an	a.
Hyp"o*gene	a.
Hyp`o*ge"ous	a.
Hyp`o*ge"um	n.
Hyp`o*glos"sal	a.
Hy*pog"na*tous	a.
Hyp"o*gyn	n.
Hy*pog"y*nous	a.
Hy`po*hy"al	a.
Hy`po*nas"tic	a.
Hy`po*nas"ty	n.
Hy`po*ni"trite	n.
Hy`po*ni"trous	a.
hyponym	n.
hyponymy	n.
Hy`po*phar"ynx	n.
Hy`po*phos"phate	n.
Hy`po*phos"phite	n.
Hy`po*phos*phor"ic	a.
Hy`po*phos"phor*ous	a.
Hy*poph"yl*lous	a.
Hy`po*phys"i*al	a.
Hy*poph"y*sis	n.
Hy`po*plas"tron	n.
Hy*pop"ti*lum	n.
Hy`po*ra"di*us	n.
Hy`po*rha"chis	n.
Hy`po*skel"e*tal	a.
Hy`po*spa"di*as	n.
Hy*pos"ta*sis	n.
Hy*pos"ta*size	v. t.
Hy`po*stat"ic	a.
Hy`po*stat"ic*al*ly	adv.
Hy*pos"ta*tize	v. t.
Hy`po*ster"num	n.
Hy"po*stome	n.
Hy*pos"tro*phe	n.
Hy"po*style	a.
Hy`po*sul"phate	n.
Hy`po*sul"phite	n.
Hy`po*sul*phur"ic	a.
Hy`po*sul"phur*ous	a.
Hy`po*tar"sus	n.
Hy*pot"e*nuse	n.
Hy*poth"ec	n.
Hy`po*the"ca	n.
Hy*poth"e*cate	v. t.
Hy*poth`e*ca"tion	n.
Hy*poth"e*ca`tor	n.
Hy*poth"e*nal	a.
Hy*poth"e*nar	n.
Hy*poth`e*nu"sal	a.
Hy*poth"e*nuse	n.
Hy*poth"e*sis	n.
Hy`po*thet"ic	a.
Hy*poth"e*tist	n.
Hy`po*tra*che"li*um	n.
Hy*pot"ri*cha	n. pl.
Hy`po*tro"choid	n.
Hy`po*ty*po"sis	n.
Hy`po*xan"thin	n.
Hy`po*zo"ic	a.
Hyp"pish	a.
Hyp"po*griff	n.
Hyp"si*loid	a.
Hyp*som"e*ter	n.
Hyp`so*met"ric	a.
Hyp*som"e*try	n.
Hypsiprymnodon	n.
Hy*pu"ral	a.
Hy"ra*coid	a.
Hyr`a*coi"de*a	n. pl.
Hyracotherium	n.
Hy"rax	n.
Hyr*ca"ni*an	a.
Hyrse	n.
Hyrst	n.
Hy"son	n.
Hys"sop	n.
Hyssopus	n.
Hys`ter*an"thous	a.
Hys`te*re"sis	n.
Hys`ter*et"ic	a.
Hys*te"ri*a	n.
Hys*ter"ic	a.
hys*ter"ic*al	a.
Hys*ter"ics	n. pl.
Hys`ter*o*ep"i*lep`sy	n.
Hys`ter*o*gen"ic	a.
Hys`ter*ol"o*gy	n.
Hys"te*ron prot"e*ron	n.
Hys`ter*ot"o*my	n.
Hys"tri*cine	a.
Hys`tri*co*mor"phous	a.
Hys"trix	prop. n.
Hythe	n.
