D	n.
Dab	n.
Dab	v. i.
Dab	n.
Dabb	n.
Dab"ber	n.
Dab"ble	v. t.
Dab"ble	v. i.
Dab"bler	n.
Dab"bling*ly	adv.
Dab"chick`	n.
Da*boi"a	n.
Dab"ster	n.
Da`ca"po	n.
Dacelo	n.
dacha	n.
Dachs"hund`	n.
Da"cian	a.
Dacninae	n.
da*coit"	n.
da*coit"y	n.
Da*co"tahs	n. pl.
Dacron	n.
Dacrycarpus	n.
Dacrydium	n.
Dacrymyces	n.
dac"tyl	n.
dac"tyl*ar	a.
Dac"tyl*et	n.
Dac*tyl"ic	a.
Dac*tyl"ic	n.
dac*tyl"i*o*glyph	n.
dac*tyl`i*og"ly*phy	n.
Dac*tyl`i*og"ra*phy	n.
Dac*tyl`i*ol"o*gy	n.
Dac*tyl"i*o*man`cy	n.
Dac"tyl*ist	n.
Dac`tyl*i"tis	n.
Dac`tyl*ol"o*gy	n.
Dac*tyl"o*man`cy	n.
Dac`tyl*on"o*my	n.
Dac`tyl*op"ter*ous	a.
Dactyloscopidae	n.
Dac`ty*lo*the"ca	n.
dac`tyl*o*zo"oid	n.
Dad	n.
Dad"dle	v. i.
Dad"dock	n.
Dad"dy	n.
Dad"dy long"legs`	v. t.
Dade	v. i.
Da"do	n.
D<ae/"dal	a.
D<ae/d"a*lous	a.
D<ae/"mon	n.
Daff	v. t.
Daff	n.
Daff	v. i.
Daff	v. t.
Daf"fo*dil	n.
Daft	a.
Daft"ness	n.
Dag	n.
Dag	n.
Dag	n.
Dag	v. t.
Dag	v. i.
dagame	n.
Dagan	prop. n.
Dagda	n.
dagga	n.
Dag"ger	n.
Dag"ger	v. t.
Dag"ger	n.
Dagges	n. pl.
Dag"gle	v. t.
Dag"gle	v. i.
Dag"gle-tail`	a.
Dag"gle-tail`	n.
Dag"lock`	n.
Da"go	n.
Da*go"ba	n.
Da"gon	n.
Dag"swain`	n.
Dag"-tailed`	a.
Da*guer"re*an	a.
Da*guerre"o*type	n.
Da*guerre"o*type	v. t.
Da*guerre"o*ty`per	n.
Da*guerre"o*ty`py	n.
Da`ha*be"ah	n.
Dah"lia	n.
Dah"lin	n.
Da*hoon"	n.
Dail	n.
Dai"li*ness	n.
Dai"ly	a.
Dai"ly	n.
Dai"ly	adv.
Dai"mi*o	n.
Daint	n.
Dain"ti*fy	v. t.
Dain"ti*ly	adv.
Dain"ti*ness	n.
Dain"trel	n.
Dain"ty	n.
Dain"ty	a.
daiquiri	n.
Da"<ium/*ra	n.
Dai"ry	n.
Dai"ry*ing	n.
Dai"ry*maid`	n.
Dai"ry*man	n.
Dai"ry*wom`an	n.
Da"is	n.
Dai"sied	a.
Dai"sy	n.
daisybush	n.
Dak	n.
Dakar	prop. n.
Da"ker	n.
Da"ker hen`	n.
Da*ko"ta group`	n. pl
Dal	n.
Dalbergia	n.
Dale	n.
Dalea	n.
Dales"man	n.
daleth	imp.
Dalles	n. pl.
Dal"li*ance	n.
Dal"li*er	n.
dallis grass	n.
Dal"lop	n.
Dal"ly	v. i.
Dal"ly	v. t.
Dal*ma"ni*a	n.
Dal`ma*ni"tes	n.
Dal*ma"tian	a.
Dal*mat"i*ca	n.
dalo	n.
Dal` se"gno	n.
dalton	n.
Dal*to"ni*an	n.
Dal"ton*ism	n.
Dam	n.
Dam	n.
Dam	v. t.
Dama	n.
Dam"age	n.
Dam"age	v. t.
Dam"age	v. i.
Dam"age*a*ble	a.
damaged	adj.
Dam"age fea`sant	n.
damaging	adj.
Damaliscus	n.
Da"man	n.
Dam"ar	n.
Da*ma"ra	n.
Dam"as*cene	a.
Dam"as*cene	n.
Dam`as*cene"	v. t.
damascened	adj.
Damascus	prop. n.
Da*mas"cus steel	n.
Dam"ask	a.
Dam"ask	v. t.
Dam"as*keen`	v. t.
Dam"as*kin	n.
Da*mas*s<eacute/"	a.
Dam"as*sin	n.
Dam"bo*nite	n.
Dam"bose	n.
Dame	n.
Dame"wort`	n.
Da`mi*a"na	n.
Da"mi*an*ist	n.
Dam"mar	n.
Dam"ma*ra	n.
Damn	v. t.
Damn	v. i.
Dam`na*bil"i*ty	n.
Dam"na*ble	a.
Dam"na*ble*ness	n.
Dam"na*bly	adv.
Dam*na"tion	n.
Dam"na*to*ry	a.
Damned	a.
Dam*nif"ic	a.
Dam`ni*fi*ca"tion	n.
Dam"ni*fy	v. t.
Damn"ing	a.
Damn"ing*ness	n.
dam"num	n.
Dam"o*sel	n.
Dam"our*ite	n.
Damp	n.
Damp	a.
Damp	v. i.
Damp"en	v. t.
Damp"en	v. i.
dampening	n.
damp"er	n.
Damp"ish	a.
Damp"ne	v. t.
Damp"ness	n.
Damp" off`	a.
Dam"sel	n.
damselfish	n.
damselfly	n.
Dam"son	n.
Dan	n.
Dan	n.
Danaidae	n.
Da"na*ide	n.
Da"na*ite	n.
Da"na*lite	n.
Danaus	n.
Dan"bu*rite	n.
Dance	v. i.
Dance	v. t.
Dance	n.
Dan"cer	n.
Dan"cer*ess	n.
Dan`cet`t<eacute/"	a.
Dan"cing	p. a. & vb. n.
Dan"cy	a.
Dan"de*li`on	n.
Dan"der	n.
Dan"der	v. i.
Dan"di	n.
Dan"die	n.
Dan"die Din"mont	n.
Dan"di*fied	a.
Dan"di*fy	v. t.
Dan"di*prat	n.
Dan"dle	v. t.
Dan"dler	n.
Dan"driff	n.
Dandruff	n.
Dan"dy	n.
Dan"dy-cock`	n. masc.
Dan"dy*ish	a.
Dan"dy*ism	n.
Dan"dy*ize	v. t. & i.
Dan"dy*ling	n.
Dane	n.
Dane"geld`	n.
Dane"wort`	n.
Dang	imp.
Dang	v. t.
Dan"ger	n.
Dan"ger	v. t.
Dan"ger*ful	a.
Dan"ger*less	a.
Dan"ger*ous	a.
Dan"gle	v. i.
Dan"gle	v. t.
Dan"gle*ber`ry	n.
Dan"gler	n.
Dan"i*el	n.
Dan"ish	a.
Dan"ite	n.
Dank	a.
Dank	n.
Dank	n.
Dank"ish	a.
Dan"ne*brog	n.
Dan`seuse"	n.
Dansk	a.
Dansk"er	n.
Dan*te"an	a.
Dan*tesque"	a.
Da*nu"bi*an	a.
Dap	v. i.
Da*pat"ic*al	a.
Daph"ne	n.
Daph"ne*tin	n.
Daph"ni*a	n.
Daph"nin	n.
Daph"no*man`cy	n.
Dap"i*fer	n.
Dap"per	a.
Dap"per*ling	n.
Dap"ple	n.
Dap"ple	a.
Dap"ple	v. t.
Dar"bies	n. pl.
Dar"by	n.
Dar"by*ite	n.
Dardanelles	n.
Dar*da"ni*an	a. & n.
Dare	v. i.
Dare	v. t.
Dare	n.
Dare	v. i.
Dare	v. t.
Dare	n.
Dare"-dev`il	n.
Dare"-dev`il*try	n
Dare"ful	a.
Dar"er	n.
Dar es Salaam	prop. n.
Darg	n.
Dar"ic	n.
Dar"ing	n.
Dar"ing	a.
Da`ri*ole"	n.
Dark	a.
Dark	n.
Dark	v. t.
dark-blue	adj.
dark-brown	adj.
Dark"en	v. t.
Dark"en	v. i.
darkened	adj.
Dark"en*er	n.
Dark"en*ing	n.
Dark"ful	a.
dark-green	adj.
dark-haired	adj.
dark"ie	n.
Dark"ish	a.
Dar"kle	v. i.
Dark"ling	adv.
Dark"ling	p. pr. & a.
Dark"ly	adv.
Dark"ness	n.
dark-skinned	adj.
Dark"some	a.
dark"y	n.
dar"ling	n.
dar"ling	a.
Dar`ling*to"ni*a	n.
Darmera	n.
Darn	v. t.
Darn	n.
Darn	v. t.
darned	adj.
dar"nel	n.
Darn"er	n.
Dar"nex	n.
Da*roo"	n.
Darr	n.
Dar"raign	v. t.
Dar"rein	a.
Dart	n.
Dart	v. t.
Dart	v. i.
Dar"tars	n.
dartboard	n.
Dart"er	n.
Dart"ing*ly	adv.
Dar"tle	v. t. & i.
Dar*to"ic	a.
Dar"toid	a.
Dar"tos	n.
Dar"trous	a.
Darussalam Bandar Seri Begawan	prop. n.
Dar*win"i*an	a.
Dar*win"i*an	n.
Dar*win"i*an*ism	n.
Dar"win*ism	n.
Dase	v. t.
Dase"we	v. i.
Dash	v. t.
Dash	v. i.
Dash	n.
Dash"board`	n.
Dash`een"	n.
dash"er	n.
Dash"ing	a.
Dash"ing*ly	adv.
Dash"ism	n.
dash"pot`	n.
Dash"y	a.
Das"tard	n.
Das"tard	a.
Das"tard	v. t.
Das"tard*ize	v. t.
Das"tard*li*ness	n.
Das"tard*ly	a.
Das"tard*ness	n.
Das"tard*y	n.
Das"we	v. i.
Da*sym"e*ter	n.
Das`y*p<ae/"dal	a.
Das`y*p<ae/"des	n. pl.
Das`y*p<ae/"dic	a.
Dasyproctidae	n.
Dasypus	n.
Dasyuridae	n.
das"y*ure	n.
Das`y*u"rine	a.
Dasyurus	n.
DAT	n.
Da"ta	n. pl.
database	n.
data-based	adj.
dat"a*ble	a.
Da*ta"ri*a	n.
Da"ta*ry	n.
Date	n.
Date	n.
Date	v. t.
Date	v. i.
dateable	adj.
dated	adj.
date"less	a.
Date line	n.
Da*tis"cin	n.
Da"tive	a.
Da"tive	n.
Da"tive*ly	adv.
Dat"o*lite	n.
Datril	n.
Da"tum	n.
Da*tu"ra	n.
Da*tu"rine	n.
Daub	v. t.
Daub	v. i.
Daub	n.
daubed	adj.
Daubentonia	n.
Daubentoniidae	n.
Daub"er	n.
Daub"er*y	n.
Daub"ing	n.
Dau"bree*lite	n.
Daub"y	a.
Daugh"ter	n.
Daugh"ter-in-law`	n.
Daugh"ter*li*ness	n.
Daugh"ter*ly	a.
Dauk	v. t.
Daun	n.
Daunt	v. t.
Daunt"er	n.
daunting	adj.
daunt"less	a.
dauntlessness	n.
Dau"phin	n.
Dau"phin*ess	n.
Dauw	n.
davallia	n.
Davalliaceae	n.
Dav"en*port	n.
Da*vid"ic	a.
Daviesia	n.
Dav"it	n.
Da"vy Jones"	n.
Da"vy*um	n.
Daw	n.
Daw	v. i.
Daw	v. t.
Daw"dle	v. i.
Daw"dle	v. t.
Daw"dle	n.
Daw"dler	n.
Dawe	n.
Daw"ish	a.
Dawk	n.
Dawk	v. t.
Dawk	n.
Dawn	v. i.
Dawn	n.
dawn"ing	n.
Daw"son*ite	n.
Day	n.
Day"aks	n. pl.
day-and-night	adj.
daybed	n.
day boarder	n.
Day"book`	n.
dayboy	n.
Day"break`	n.
Day"-coal`	n.
Day"dream`	n.
Day"dream`er	n.
Day"flow`er	n.
Day"fly`	n.
Day"-la`bor	n.
Day"-la`bor*er	n.
Day"light`	n.
day" lil`y	n.
Day"mare`	n.
Day"-net`	n.
Day"-peep`	n.
Days"man	n.
day"spring`	n.
day"-star`	n.
day"time`	n.
day-to-day	adj.
day"wom`an	n.
Daze	v. t.
Daze	n.
dazed	adj.
Daz"zle	v. t.
Daz"zle	v. i.
Daz"zle	n.
Daz"zle*ment	n.
Daz"zling*ly	adv.
DBMS	n.
D-day	n.
De-	v. t.
deaccession	v. t.
Dea"con	n.
Dea"con	v. t.
Dea"con*ess	n.
Dea"con*hood	n.
Dea"con*ry	n.
Dea"con*ship	n.
de*ac"ti*vate	v. t.
de*ac`ti*va"tion	n.
Dead	a.
Dead	adv.
Dead	n.
Dead	v. t.
Dead	v. i.
dead` beat"	n.
Dead"beat`	a.
Dead"born`	a.
Dead"en	v. t.
Dead"en*er	n.
dead"en*ing	adj.
dead"en*ing	n.
Dead"-eye`	n.
Dead"head`	n.
Dead"-heart`ed	a.
Dead"house`	n.
Dead"ish	a.
Dead"latch`	n.
Dead"light`	n.
Dead"li*hood	n.
Dead"li*ness	n.
dead"lock`	n.
deadlocked	adj.
dead"ly	a.
dead"ly	adv.
Dead"ness	n.
dead-on	adj.
Dead"-pay`	n.
Dead"-reck`on*ing	n.
Deads	n. pl.
Dead"-stroke`	a.
Dead"wood`	n.
Dead"works`	n. pl.
Deaf	a.
Deaf	v. t.
deaf-aid	n.
deaf and dumb	adj.
Deaf"en	v. t.
deafened	adj.
deaf"en*ing	n.
deaf"en*ing	a.
Deaf"ly	adv.
Deaf"ly	a.
Deaf"-mute`	n.
deaf-muteness	n.
Deaf"ness	n.
Deal	n.
Deal	v. t.
Deal	v. i.
De*al"bate	v. t.
De`al*ba"tion	n.
Deal"er	n.
Deal"fish`	n.
Deal"ing	n.
Dealth	n.
De*am"bu*late	v. i.
De*am`bu*la"tion	n.
De*am"bu*la*to*ry	a.
De*am"bu*la*to*ry	n.
Dean	n.
Dean"er*y	n.
Dean"ship	n.
Dear	a.
Dear	n.
Dear	adv.
Dear	v. t.
Dear"born	n.
Dear"-bought`	a.
Deare	v. t. & n.
Dear"ie	n.
Dear"ling	n.
Dear"-loved`	a.
Dear"ly	adv.
Dearn	a.
Dearn	v. t.
Dear"ness	n.
Dearth	n.
De`ar*tic"u*late	v. t.
Dear"worth`	a.
Dear"y	n.
De"as	n.
Death	n.
Death"bed	n.
Death"bird`	n.
Death"blow`	n.
Death"ful	a.
Death"ful*ness	n.
death" knell`	n.
Death"less	a.
Death"like`	a.
Death"li*ness	n.
Death"ly	a.
Death"ly	adv.
death-roll	n.
Death's"-head`	n.
Death's"-herb`	n.
Deaths"man	n.
Death"ward	adv.
Death"watch`	n.
De*au"rate	a.
De*au"rate	v. t.
De`au*ra"tion	n.
Deave	v. t.
De*bac"chate	v. i.
De`bac*cha"tion	n.
De*ba"cle	n.
De*bar"	v. t.
De*barb"	v. t.
De"bark"	v. t. & i.
De`bar*ka"tion	n.
De*bar"ment	n.
De*bar"rass	v. t.
De*base"	v. t.
De*based"	a.
De*base"ment	n.
De*bas"er	n.
De*bas"ing*ly	adv.
De*bat"a*ble	a.
De*bate"	v. t.
De*bate"	v. i.
De*bate"	n.
De*bate"ful	a.
De*bate"ful*ly	adv.
De*bate"ment	n.
De*bat"er	n.
De*bat"ing	n.
De*bat"ing*ly	adv.
De*bauch"	v. t. & i.
De*bauch"	n.
De*bauched"	a.
De*bauch"ed*ly	adv.
De*bauch"ed*ness	n.
Deb`au*chee"	n.
De*bauch"er	n.
De*bauch"er*y	n.
De*bauch"ment	n.
De*bauch"ness	n.
De*beige"	n.
De*bel"	v. t.
De*bel"late	v. t.
Deb`el*la"tion	n.
De be"ne es"se	n.
De*ben"tured	a.
Debenture stock	a.
De*bil"i*tant	a.
De*bil"i*tate	v. t.
debilitated	adj.
debilitating	adj.
debilitative	adj.
De*bil`i*ta"tion	n.
De*bil"i*ty	n.
Deb"it	n.
Deb"it	v. t.
Deb"it card`	n.
Deb"it*or	n.
De`bi*tu`mi*ni*za"tion	n.
De`bi*tu"mi*nize	v. t.
D<eacute/`blai"	n.
Deb`o*nair"	a.
Deb`o*nair"i*ty	n.
Deb`o*nair"ly	adv.
Deb`o*nair"ness	n.
De*bosh"	v. t.
De*bosh"ment	n.
De*bouch"	v. i.
D<eacute/`bou`ch<eacute/"	n.
D<eacute/`bou`chure"	n.
De*brief"	v.
De*bride"	v.
De*bride"ment	n.
D<eacute/`bris"	n.
De*bruised"	a.
Debt	n.
Debt"ed	p. a.
Debt*ee"	n.
Debt"less	a.
Debt"or	n.
De*bul"li*ate	v. i.
Deb`ul*li"tion	n.
De*burse"	v. t. &  i.
De"bu*scope	n.
D<eacute/`but"	n.
D<eacute/`bu`tant"	n.
D<eacute/`bu`tante"	fem. n.
Dec"a-	pref.
De*cac`e*ra"ta	n. pl.
Dec"a*chord	n.
Dec`a*cu"mi*na`ted	a.
Dec"ad	n.
Dec"a*dal	a.
Dec"ade	n.
De*ca"dence	n.
De*ca"dent	a.
De*ca"dent	n.
Dec"a*dist	n.
Dec"a*gon	n.
De*cag"o*nal	a.
Dec"a*gram	n.
Dec`a*gyn"i*a	n. pl.
Dec`a*gyn"i*an	a.
Dec`a*he"dral	a.
Dec`a*he"dron	n.
De*cal`ci*fi*ca"tion	n.
De*cal"ci*fy	v. t.
De*cal`co*ma"ni*a	n.
Dec"a*li`ter	n.
Dec"a*log	n.
De*cal"o*gist	n.
Dec"a*logue	n.
De*cam"e*ron	n.
Dec"a*me`ter	n.
De*camp"	v. i.
De*camp"ment	n.
Dec"a*nal	a.
De*can"dri*a	n. pl.
De*can"dri*an	a.
Dec"ane	n.
Dec*an"gu*lar	a.
De*ca"ni	a.
De*cant"	v. t.
De*can"tate	v. t.
De`can*ta"tion	n.
De*cant"er	n.
De*caph"yl*lous	a.
De*cap"i*tate	v. t.
decapitated	adj.
De*cap`i*ta"tion	n.
Dec"a*pod	n.
De*cap"o*da	prop. n. pl.
De*cap"o*dal	a.
De*car"bon*ate	v. t.
De*car`bon*i*za"tion	n.
De*car"bon*ize	v. t.
De*car"bon*i`zer	n.
De*car`bu*ri*za"tion	n.
De*car"bu*rize	v. t.
De*card"	v. t.
De*car"di*nal*ize	v. t.
Dec"a*stere	n.
Dec"a*stich	n.
Dec"a*style	a.
Dec`a*syl*lab"ic	a.
de*cath"lon	n.
Dec`a*to"ic	a.
De*cay"	v. i.
De*cay"	v. t.
De*cay"	n.
decayable	adj.
De*cayed"	a.
De*cay"er	n.
De*cease"	n.
De*cease"	v. i.
De*ceased"	a.
De*cede"	v. i.
De*ce"dent	a.
De*ce"dent	n.
De*ceit"	n.
De*ceit"ful	a.
De*ceit"ful*ly	adv.
De*ceit"ful*ness	n.
De*ceit"less	a.
De*ceiv"a*ble	a.
De*ceiv"a*ble*ness	n.
De*ceiv"a*bly	adv.
De*ceive"	v. t.
De*ceiv"er	n.
decelerate	v. i.
decelerate	v. t.
deceleration	n.
De*cem"ber	prop. n.
De*cem"brist	n.
De`cem*den"tate	a.
De*cem"fid	a.
De`cem*loc"u*lar	a.
De*cem"pe*dal	a.
De*cem"vir	n.
De*cem"vi*ral	a.
De*cem"vi*rate	n.
De*cem"vir*ship	n.
De"cence	n.
De"cen*cy	n.
De"cene	n.
De*cen"na*ry	n.
De*cen"ni*al	a.
De*cen"ni*al	n.
De*cen"ni*um	n.
De*cen"no*val	a.
de"cent	a.
decentralisation	n.
decentralise	v.
decentralizing	adj. prenom.
de*cen`tral*i*za"tion	n.
De*cen"tral*ize	v. t.
De*cep"ti*ble	a.
De*cep"tion	n.
De*cep"tious	a.
De*cep"tive	a.
De*cep"tive*ly	adv.
De*cep"tive*ness	n.
De`cep*tiv"i*ty	n.
De*cep"to*ry	a.
De*cern"	v. t.
De*cern"i*ture	n.
De*cerp"	v. t.
De*cerpt"	a.
De*cerp"ti*ble	a.
De*cerp"tion	n.
De`cer*ta"tion	n.
De*ces"sion	n.
De*charm"	v. t.
De*chris"tian*ize	v. t.
De*cid"a*ble	a.
Dec"i*are`	n.
De*cide"	v. t.
De*cide"	v. i.
De*cid"ed	a.
De*cid"ed*ly	adv.
De*cide"ment	n.
Dec"i*dence	n.
De*cid"er	n.
De*cid"u*a	n.
De*cid`u*a"ta	n. pl.
De*cid"u*ate	a.
Dec`i*du"i*ty	n.
De*cid"u*ous	a.
De*cid"u*ous*ness	n.
Dec"i*gram	n.
Dec"il	n.
Dec"i*li`ter	n.
De*cil"lion	n.
De*cil"lionth	a.
De*cil"lionth	n.
Dec"i*mal	a.
Dec"i*mal	n.
decimalisation	n.
decimalise	v.
decimalization	n.
dec"i*mal*ism	n.
Dec"i*mal*ize	v. t.
Dec"i*mal*ly	adv.
Dec"i*mate	v. t.
Dec`i*ma"tion	n.
Dec"i*ma`tor	n.
D<eacute/`cime"	n.
Dec"i*me`ter	n.
Dec`i*mo*sex"to	n.
Dec`i*mo*sex"to	a.
De"cine	n.
De*ci"pher	v. t.
De*ci"pher*a*ble	a.
De*ci"pher*er	n.
De*ci"pher*ess	n.
De*ci"pher*ment	n.
De*cip"i*en*cy	n.
De*cip"i*um	n.
De*ci"sion	n.
De*ci*sive	a.
De*ci"so*ry	a.
Dec"i*stere	n.
De*cit"i*zen*ize	v. t.
De*civ"i*lize	v. t.
Deck	v. t.
Deck	n.
Deck"el	n.
Deck" chair`	n.
decked	adj.
Deck"er	n.
dec"kle	n.
Dec"kle edge`	a.
De*claim"	v. i.
De*claim"	v. t.
De*claim"ant	n.
De*claim"er	n.
Dec`la*ma"tion	n.
Dec"la*ma`tor	n.
De*clam"a*to*ry	a.
De*clar"a*ble	a.
De*clar"ant	n.
Dec`la*ra"tion	n.
Declaration of Independence	n.
De*clar"a*tive	a.
De*clar"a*tive*ly	adv.
Dec"la*ra`tor	n.
De*clar"a*to*ri*ly	adv.
De*clar"a*to*ry	a.
De*clare"	v. t.
De*clare"	v. i.
declared	adj.
De*clar"ed*ly	adv.
De*clar"ed*ness	n.
De*clare"ment	n.
De*clar"er	n.
De*class"	v. t.
d<eacute/class<eacute/	adj.
declassification	n.
declassified	adj.
declassify	v.
declaw	v. t.
De*clen"sion	n.
De*clen"sion*al	a.
De*clin"a*ble	a.
De*clin"al	a.
Dec"li*nate	a.
Dec`li*na"tion	n.
Dec"li*na`tor	n.
De*clin"a*to*ry	a.
De*clin"a*ture	n.
De*cline"	v. i.
De*cline"	v. t.
De*cline"	n.
De*clined"	a.
De*clin"er	n.
declining	adj.
Dec`li*nom"e*ter	n.
De*clin"ous	a.
De*cliv"i*tous	a.
De*cliv"i*ty	n.
declutch	v. i. & t.
De*coct"	v. t.
De*coct"i*ble	a.
De*coc"tion	n.
De*coc"ture	n.
decode	v. t.
De`co*her"er	n.
de*col"late	v. t.
De*col"la*ted	a.
De`col*la"tion	n.
D<eacute/`col`le*tage"	n.
D<eacute/`col`le*t<eacute/"	a.
De*col"ling	n.
decolonisation	n.
decolonization	n.
decolonize	v. t.
decolonize	v. i.
De*col"or	v. t.
De*col"or*ant	n.
De*col"or*ate	a.
De*col"or*ate	v. t.
De*col`or*a"tion	n.
De*col"or*ize	v. t.
De"com*plex`	a.
De`com*pos"a*ble	a.
De`com*pose"	v. t.
De`com*pose"	v. i.
De`com*posed"	a.
De`com*pos"ite	a.
De`com*pos"ite	n.
De*com`po*si"tion	n.
decompositional	adj.
De`com*pound"	v. t.
De`com*pound"	a.
De`com*pound"	n.
De`com*pound"a*ble	a.
decompress	v. i.
decompress	v. t.
decompressing	n.
decompression	n.
De`con*cen"trate	v. t.
De*con`cen*tra"tion	n.
De`con*coct"	v. t.
De*con"se*crate	v. t.
de`con*struct"	v. t.
de`con*struc"tion	n.
de`con*struc"tion*ism	n.
de`con*struc"tion*ist	adj.
de`con*tam"i*nate	v. t.
decontamination	n.
decor	n.
Dec"o*ra*ment	n.
Dec"o*rate	v. t.
decorated	adj.
dec`o*ra"tion	n.
Decoration Day	a.
Dec"o*ra`tor	n.
de*core"	v. t.
De*core"ment	n.
Dec"or*ous	a.
De*cor"ti*cate	v. t.
De*cor`ti*ca"tion	n.
De*cor"ti*ca`tor	n.
De*cor"um	n.
De*coy"	v. t.
De*coy"	n.
De*coy"-duck`	n.
De*coy"er	n.
De*coy"-man`	n.
De*crease"	v. i.
De*crease"	v. t.
De*crease"	n.
decreased	adj.
De*crease"less	a.
De*creas"ing	a.
De`cre*a"tion	n.
De*cree"	n.
De*cree"	v. t.
De*cree"	v. i.
De*cree"a*ble	a.
De*cre"er	n.
De*creet"	n.
Dec"re*ment	n.
De*crep"it	a.
De*crep"i*tate	v. t.
De*crep"i*tate	v. i.
De*crep`i*ta"tion	n.
De*crep"it*ness	n.
De*crep"i*tude	n.
De`cres*cen"do	a. & adv.
De*cres"cent	a.
De*cres"cent	n.
De*cre"tal	a.
De*cre"tal	n.
De*crete"	n.
De*cre"tion	n.
De*cre"tist	n.
De*cre"tive	a.
Dec`re*to"ri*al	a.
Dec"re*to*ri*ly	adv.
Dec"re*to*ry	a.
De*crew"	v. i.
De*cri"al	n.
De*cri"er	n.
De*crown"	v. t.
De`crus*ta"tion	n.
De*cry"	v. t.
decrypt	v.
Dec`u*ba"tion	n.
De*cu"bi*tus	n.
D<eacute/`cu`lasse`ment"	n.
Dec"u*man	a.
decumary	n.
De*cum"bence	n.
De*cum"bent	a.
De*cum"bent*ly	adv.
De*cum"bi*ture	n.
Dec"u*ple	a.
Dec"u*ple	n.
Dec"u*ple	v. t.
De*cu"ri*on	n.
De*cu"ri*on*ate	n.
De*cur"rence	n.
De*cur"rent	a.
De*cur"sion	n.
De*cur"sive	a.
De*cur"sive*ly	adv.
De*curt"	v. t.
De`cur*ta"tion	n.
Dec"u*ry	n.
De*cus"sate	v. t.
De*cus"sate	a.
De*cus"sate*ly	adv.
De`cus*sa"tion	n.
De*cus"sa*tive	a.
De*cus"sa*tive*ly	adv.
De"cyl	n.
De*cyl"ic	a.
De*dal"ian	a.
Ded"a*lous	a.
De*dans"	n.
Dede	a.
De*dec"o*rate	v. t.
De*dec`o*ra"tion	n.
De*dec"o*rous	a.
De`den*ti"tion	n.
Ded"i*cate	p. a.
Ded"i*cate	v. t.
dedicated	adj.
Ded`i*ca*tee"	n.
Ded`i*ca"tion	n.
Ded"i*ca`tor	n.
Ded`i*ca*to"ri*al	a.
Ded"i*ca*to*ry	a.
Ded"i*ca*to*ry	n.
Ded"i*mus	n.
De*di"tion	n.
Ded"o*lent	a.
De*duce"	v. t.
De*duce"ment	n.
De*du`ci*bil"i*ty	n.
De*du"ci*ble	a.
De*du"ci*ble*ness	n.
De*du"ci*bly	adv.
De*du"cive	a.
De*duct"	v. t.
deducted	adj.
De*duct"i*ble	a.
De*duc"tion	n.
De*duct"ive	a.
De*duct"ive*ly	adv.
De*duc"tor	n.
De*duit"	n.
De*du`pli*ca"tion	n.
Deed	a.
Deed	n.
Deed	v. t.
Deed"ful	a.
Deed"less	a.
Deed" poll`	n.
Deed"y	a.
Deem	v. t.
Deem	v. i.
Deem	n.
Deem"ster	n.
de-energize	v. t.
Deep	a.
Deep	adv.
Deep	n.
Deep"en	v. t.
Deep"en	v. i.
deep-eyed	adj.
deep fat	n.
deep-fat-fry	v. t.
Deep"-fet`	a.
deep-fried	adj.
deep-fry	v.
Deep"-laid`	a.
Deep"ly	adv.
deep-mined	adj.
Deep"-mouthed`	a.
Deep"ness	n.
Deep"-read`	a.
deep-rooted	adj.
Deep"-sea`	a.
deep-seated	adj.
deep-set	adj.
deep-six	v. t.
Deep"-waist`ed	a.
deep-water	adj.
Deer	n. sing. & pl.
Deer"ber`ry	n.
Deer"grass`	n.
Deer"hound`	n.
Deer"let	n.
Deer"-neck`	n.
deer's-ear	n.
Deer"skin`	n.
Deer"stalk`er	n.
Deer"stalk`ing	n.
Deer's"-tongue`	n.
dee	n.
Dees	n. pl.
Dees	n.
de-escalate	v. t.
de-escalation	n.
De*e"sis	n.
De"ess	n.
Deev	n.
De*face"	v. t.
defaced	adj.
De*face"ment	n.
De*fa"cer	n.
De` fac"to	v. t.
De*fail"ance	n.
De*fail"ure	n.
De*fal"cate	v. t.
De*fal"cate	v. i.
De`fal*ca"tion	n.
Def"al*ca`tor	n.
De*falk"	v. t.
Def`a*ma"tion	n.
De*fam"a*to*ry	a.
De*fame"	v. t.
De*fame"	n.
De*fam"er	n.
De*fam"ing*ly	adv.
Def"a*mous	a.
De*fat"i*ga*ble	a.
De*fat"i*gate	v. t.
De*fat`i*ga"tion	n.
De*fault"	n.
De*fault"	v. i.
De*fault"	v. t.
De*fault"er	n.
De*fea"sance	n.
De*fea"sanced	a.
De*fea"si*ble	a.
De*feat"	v. t.
De*feat"	n.
defeatism	n.
De*fea"ture	n.
De*fea"tured	p. p.
Def"e*cate	a.
Def"e*cate	v. t.
Def"e*cate	v. i.
Def`e*ca"tion	n.
Def"e*ca`tor	n.
De*fect"	n.
De*fect"	v. i.
De*fect"	v. t.
De*fect`i*bil"i*ty	n.
De*fect"i*ble	a.
De*fec"tion	n.
De*fec"tion*ist	n.
De*fec"tious	a.
De*fect"ive	a.
De*fect"ive	n.
De*fec`tu*os"i*ty	n.
De*fec"tu*ous	a.
Def`e*da"tion	n.
De*fence"	n. & v. t.
defenceless	adj.
De*fend"	v. t.
De*fend"a*ble	a.
De*fend"ant	a.
De*fend"ant	n.
De`fen*dee"	n.
De*fend"er	n.
De*fend"ress	n.
de*fen"es*trate	v. t.
de*fen`es*tra"tion	n.
de*fen"sa*tive	n.
De*fense"	n.
De*fense"	v. t.
De*fense"less	a.
De*fens"er	n.
De*fen`si*bil"i*ty	n.
De*fen"si*ble	a.
De*fen"si*ble*ness	n.
De*fen"sive	a.
De*fen"sive	n.
De*fen"sive*ly	adv.
De*fen"sor	n.
De*fen"so*ry	a.
De*fer"	v. t.
De*fer"	v. i.
De*fer"	v. t.
De*fer"	v. i.
Def"er*ence	n.
Def"er*ent	a.
Def"er*ent	n.
Def`er*en"tial	a.
Def`er*en"tial*ly	adv.
De*fer"ment	n.
De*fer"rer	n.
De`fer*ves"cence	n.
De*feu"dal*ize	v. t.
De*fi"ance	n.
De*fi"ant	a.
De*fi"a*to*ry	a.
De*fi"bri*nate	v. t.
De*fi`bri*na"tion	n.
De*fi"bri*nize	v. t.
De*fi"cience	n.
De*fi"cien*cy	n.
De*fi"cient	a.
Def"i*cit	n.
De*fi"er	n.
De*fig`u*ra"tion	n.
De*fig"ure	v. t.
De`fi*lade"	v. t.
De`fi*lad"ing	n.
De*file"	v. i.
De*file"	v. t.
De*file"	n.
De*file"	v. t.
defiled	adj.
De*file"ment	n.
De*file"ment	n.
De*fil"er	n.
De*fil`i*a"tion	n.
De*fin"a*ble	a.
De*fine"	v. t.
De*fine"	v. i.
De*fine"ment	n.
De*fin"er	n.
Def"i*nite	a.
Def"i*nite	n.
Def"i*nite*ly	adv.
Def"i*nite*ness	n.
Def`i*ni"tion	n.
Def`i*ni"tion*al	a.
De*fin"i*tive	a.
De*fin"i*tive	n.
De*fin"i*tive*ly	adv.
De*fin"i*tive*ness	n.
De*fin"i*tude	n.
De*fix"	v. t.
Def`la*gra*bil"i*ty	n.
De*fla"gra*ble	a.
Def"la*grate	v. i.
Def"la*grate	v. t.
Def`la*gra"tion	n.
Def"la*gra`tor	n.
de*flate"	v. t.
deflated	adj.
deflation	n.
deflationary	adj.
deflator	n.
de*flect"	v. t.
De*flect"	v. i.
De*flect"a*ble	a.
De*flect"ed	a.
De*flec"tion	n.
De*flec`tion*i*za"tion	n.
De*flec"tion*ize	v. t.
De*flect"ive	a.
De*flect"or	n.
De*flexed"	a.
De*flex"ion	n.
De*flex"ure	n.
De*flo"rate	a.
Def`lo*ra"tion	n.
de*flour"	v. t.
De*flour"er	n.
De*flow"	v. i.
de*flow"er	v. t.
De*flow"er*er	n.
Def"lu*ous	a.
De*flux"	n.
De*flux"ion	n.
Def"ly	adv.
Def`<oe/*da"tion	n.
De*fo"li*ate	a.
deformational	adj.
de*fol"i*ate	v. t.
de*fo`li*a"tion	n.
De*force"	v. t.
De*force"ment	n.
De*force"or	n.
De*for"ciant	n.
De*for`ci*a"tion	n.
De*for"est	v. t.
De*form"	v. t.
De*form"	a.
Def`or*ma"tion	n.
De*formed"	a.
De*form"er	n.
De*form"i*ty	n.
De*fors"er	n.
De*foul"	v. t.
De*fraud"	v. t.
De`frau*da"tion	n.
De*fraud"er	n.
De*fraud"ment	n.
De*fray"	v. t.
De*fray"al	n.
De*fray"er	n.
De*fray"ment	n.
defrock	v. t.
defrost	v. t.
defrost	v. i.
defroster	n.
deft	a.
Deft"ly	adv.
Deft"ness	n.
De*funct"	a.
De*funct"	n.
De*func"tion	n.
de*func"tive	a.
de*fuse"	v. t.
defusing	n.
de*fy"	v. t.
de*fy"	n.
d<eacute/`ga`g<eacute/"	a.
de*gar"nish	v. t.
De*gar"nish*ment	n.
de*gauss"	n.
degaussing	n.
De*gen"der	v. i.
De*gen"er*a*cy	n.
De*gen"er*ate	a.
De*gen"er*ate	v. i.
de*gen"er*ate	n.
De*gen"er*ate*ly	adv.
De*gen"er*ate*ness	n.
De*gen`er*a"tion	n.
De*gen`er*a"tion*ist	n.
De*gen"er*a*tive	a.
De*gen"er*ous	a.
De*gen"er*ous*ly	adv.
De*germ"	v. t.
De*ger"mi*na`tor	n.
De*glaze"	v. t.
De*glaz"ing	n.
De*glo"ried	a.
De*glu"ti*nate	v. t.
De*glu`ti*na"tion	n.
Deg`lu*ti"tion	n.
Deg`lu*ti"tious	a.
De*glu"ti*to*ry	a.
Deg`ra*da"tion	n.
De*grade"	v. t.
De*grade"	v. i.
De*grad"ed	a.
De*grade"ment	n.
de*grad"ing	a.
de*grad"ing*ly	adv.
D<eacute/`gras"	n.
Deg`ra*va"tion	n.
De*grease"	v. t.
De*gree"	n.
de*greed"	a.
degressive	adj.
De"gu	n.
De*gum"	v. t.
De*gust"	v. t.
Deg`us*ta"tion	n.
De*hisce"	v. i.
De*his"cence	n.
De*his"cent	a.
De`ho*nes"tate	v. t.
De*hon`es*ta"tion	n.
De*horn"	v. t.
De*hors"	prep.
De*hors"	n.
De*hort"	v. t.
De`hor*ta"tion	n.
De*hort"a*tive	a.
De*hort"a*to*ry	a.
De*hort"er	n.
De*hu"man*ize	v. t.
de*hu*mid"i*fy	v. t.
De*husk"	v. t.
de*hy"drate	v. t.
de*hy"drate	v. i.
dehydrated	adj.
De`hy*dra"tion	n.
De*hy"dro*gen*ate	v. t.
De*hy`dro*gen*a"tion	n.
de*ice	v. t.
deicer	n.
De"i*cide	n.
Deic"tic	a.
Deic"tic*al*ly	adv.
De*if"ic	a.
De`i*fi*ca"tion	n.
De"i*fied	a.
De"i*fi`er	n.
De"i*form	a.
De`i*for"mi*ty	n.
De"i*fy	v. t.
Deign	v. t.
Deign	v. i.
Deign"ous	a.
Deil	n.
Dei*noc"e*ras	n.
Dei*nor"nis	n.
Dei"no*saur	n.
Dei`no*the"ri*um	n.
De*in"te*grate	v. t.
Dein"te*ous	a.
de-iodinase	n.
de-iodinate	v. t.
de-iodinating	adj.
de-iodination	n.
de-ionate	v.
de*i`on*i*za"tion	n.
de*i"on*ize`	v. t.
de*i"on*ized`	a.
de*i"on*iz`er	n.
de*ip"a*rous	a.
Deip*nos"o*phist	n.
De"is	n.
De"ism	n.
De"ist	n.
De*is"tic	a.
De*is"tic*al*ly	adv.
De*is"tic*al*ness	n.
De"i*tate	a.
De"i*ty	n.
deixis	n.
De*ject"	v. t.
De*ject"	a.
De*jec"ta	n. pl.
De*ject"ed	a.
De*ject"er	n.
De*jec"tion	n.
De*ject"ly	adv.
De*jec"to*ry	a.
De*jec"ture	n.
Dej"er*ate	v. i.
Dej`er*a"tion	n.
D<eacute/`jeu`n<eacute/"	n.
D<eacute/`jeu`ner"	n.
De` ju"re	n.
Dek"a*gram	n.
Dek"a*li`ter	n.
Dek"a*me`ter	n.
Dek"a*stere`	n.
De"kle	n.
Del	n.
del	n.
De*lac`er*a"tion	n.
De*lac`ry*ma"tion	n.
De`lac*ta"tion	n.
De*laine"	n.
De*lam`i*na"tion	n.
De`lap*sa"tion	n.
De*lapse"	v. i.
De*lap"sion	n.
De`las*sa"tion	n.
De*late"	v. t.
De*late"	v. i.
De*la"tion	n.
De*la"tor	n.
Del"a*ware	n.
Delawarean	n.
Delawarian	n.
Del"a*wares	n. pl.
De*lay"	n.
De*lay"	v. t.
De*lay"	v. i.
De*lay"er	n.
De*lay"ing*ly	adv.
De*lay"ment	n.
Del` cred"er*e	imperative sing.
De"le	v. t.
Dele	v. t.
Del"e*ble	a.
De*lec"ta*ble	a.
De*lec"tate	v. t.
De`lec*ta"tion	n.
De*lec"tus	n.
Del`e*ga*cy	n.
Del"e*gate	n.
Del"e*gate	a.
Del"e*gate	v. t.
delegating	n.
Del`e*ga"tion	n.
Del"e*ga*to*ry	a.
De*len"da	n. pl.
Del`e*nif"ic*al	a.
De*lete"	v. t.
Del`e*te"ri*ous	a.
Del"e*ter*y	a.
Del"e*ter*y	n.
De*le"tion	n.
Del`e*ti"tious	a.
Del"e*tive	a.
Del"e*to*ry	n.
Delf	n.
delf	n.
delft	n.
Delft"ware`	n.
Del"i*bate	v. t.
Del`i*ba"tion	n.
Del"i*ber	v. t. & i.
De*lib"er*ate	a.
De*lib"er*ate	v. t.
De*lib"er*ate	v. i.
De*lib"er*ate*ly	adv.
De*lib"er*ate*ness	n.
De*lib`er*a"tion	n.
De*lib"er*a*tive	a.
De*lib"er*a*tive	n.
De*lib"er*a*tive*ly	adv.
De*lib"er*a`tor	n.
Del"i*brate	v. t.
Del`i*bra"tion	n.
Del"i*ca*cy	n.
Del"i*cate	a.
Del"i*cate	n.
Del"i*cate*ly	adv.
Del"i*cate*ness	n.
Del`i*ca*tes"sen	n. pl.
Del"i*ces	n. pl.
De*li"ci*ate	v. t.
De*li"cious	a.
De*li"cious*ly	adv.
De*li"cious*ness	n.
De*lict"	n.
Del"i*gate	v. t.
Del`i*ga"tion	n.
De*light"	n.
De*light"	v. t.
De*light"	v. i.
De*light"a*ble	a.
De*light"ed	a.
De*light"ed*ly	adv.
De*light"er	n.
De*light"ful	a.
De*light"ing	a.
De*light"less	a.
De*light"ous	a.
De*light"some	a.
De*lig"nate	v. t.
De*li"lah	n.
De*lim"it	v. t.
delimitate	v.
De*lim`i*ta"tion	n.
de*line"	v. t.
De*lin"e*a*ble	a.
De*lin"e*a*ment	n.
De*lin"e*ate	a.
De*lin"e*ate	v. t.
delineated	adj.
De*lin`e*a"tion	n.
De*lin"e*a`tor	n.
De*lin"e*a*to*ry	a.
De*lin"e*a*ture	n.
Del`i*ni"tion	n.
De*lin"quen*cy	n.
De*lin"quent	a.
De*lin"quent	n.
De*lin"quent*ly	adv.
Del"i*quate	v. i.
Del"i*quate	v. t.
Del`i*qua"tion	n.
Del`i*quesce"	v. i.
Del`i*ques"cence	n.
Del`i*ques"cent	a.
De*liq"ui*ate	v. i.
De*liq`ui*a"tion	n.
De*liq"ui*um	n.
De*lir"a*cy	n.
De*lir"a*ment	n.
De*lir"an*cy	n.
De*lir"ant	a.
De*lir"ate	v. t. & i.
Del`i*ra"tion	n.
De*lir"i*ant	n.
De*lir`i*fa"cient	a.
De*lir"i*ous	a.
De*lir"i*um	n.
De*lit"	n.
De*lit"a*ble	a.
Del`i*tes"cence	n.
Del`i*tes"cen*cy	n.
Del`i*tes"cent	a.
De*lit"i*gate	v. i.
De*lit`i*ga"tion	n.
De*liv"er	v. t.
De*liv"er	a.
De*liv"er*a*ble	a.
De*liv"er*ance	n.
De*liv"er*er	n.
De*liv"er*ess	n.
De*liv"er*ly	adv.
De*liv"er*ness	n.
De*liv"er*y	n.
Dell	n.
Del"la Crus"ca	a.
De"loo	n.
De*loul"	n.
Delph	n.
Delph	n.
Del"phi*an	a.
Del"phic	a.
Del"phin	a.
Del"phin	n.
Del"phine	a.
Del*phin"ic	a.
Del*phin"ic	a.
Del"phi*nine	n.
Del"phi*noid	a.
Del`phi*noi"de*a	n. pl.
Del*phi"nus	n.
Del*sarte"	n.
Del"ta	n.
Delta connection	n.
Del*ta"ic	a.
Del*thy"ris	n.
Del"tic	a.
Del*tid"i*um	n.
Del`to*he"dron	n.
Del"toid	a.
Del"toid	n.
delts	n. pl.
De*lud"a*ble	a.
De*lude"	v. t.
De*lud"er	n.
Del"uge	n.
Del"uge	v. t.
De*lun"dung	n.
De*lu"sion	n.
De*lu"sion*al	a.
De*lu"sive	a.
De*lu"so*ry	a.
deluxe	adj.
Delve	v. t.
Delve	v. i.
Delve	n.
Delv"er	n.
demagnetization	n.
De*mag"net*ize	v. t.
Dem"a*gog	n.
Dem`a*gog"ic	a.
Dem"a*gog*ism	n.
Dem"a*gogue	n.
demagoguery	n.
Dem"a*gog`y	n.
De*main"	n.
De*mand"	v. t.
De*mand"	v. i.
De*mand"	n.
De*mand"a*ble	a.
De*mand"ant	n.
De*mand"er	n.
De*mand"ress	n.
De*man"toid	n.
De*mar"cate	v. t.
De`mar*ca"tion	n.
De*march"	n.
De*march	n.
De`mar*ka"tion	n.
demasculinization	n.
demasculinize	v. t.
De`ma*te"ri*al*ize	v. t.
Deme	n.
De*mean"	v. t.
De*mean"	n.
De*mean"	n.
De*mean"ance	n.
De*mean"or	n.
De*mean"ure	n.
De"men*cy	n.
De*ment"	v. t.
De*ment"	a.
De*men"tate	a.
De*men"tate	v. t.
De`men*ta"tion	n.
De*ment"ed	a.
de*ment"ed*ness	n.
De*men"ti*a	n.
De*meph"i*tize	v. t.
De*merge"	v. t.
De*mer"it	n.
De*mer"it	v. t.
De*mer"it	v. i.
De*merse"	v. t.
De*mersed"	a.
De*mer"sion	n.
De*mes"mer*ize	v. t.
De*mesne"	n.
De*mesn"i*al	a.
Dem"i-	n.
Dem"i*bas"tion	n.
Dem"i*bri*gade"	n.
Dem"i*ca`dence	n.
Dem"i*can"non	n.
Dem"i*cir`cle	n.
Dem"i*cul"ver*in	n.
Dem"i*de"i*fy	v. t.
Dem"i*dev`il	n.
Dem"i*god	n.
Dem"i*god`dess	n.
Dem"i*gorge`	n.
Dem"i*grate	v. i.
Dem`i*gra"tion	n.
Dem"i*groat`	n.
Dem"i-is`land	n.
Dem"i*john	n.
Dem"i*lance`	n.
Dem"i*lan`cer	n.
Dem"i*lune`	n.
Dem"i*man`	n.
Dem`i*monde"	n.
Dem"i*na"tured	a.
Dem"i*qua`ver	n.
Dem`i*re*lief"	n.
Dem"i*rep`	n.
Dem"i-ri*lie"vo	n.
De*mis`a*bil"i*ty	n.
De*mis"a*ble	a.
De*mise"	n.
De*mise"	v. t.
Dem`i*sem"i*qua`ver	n.
De*miss"	a.
De*mis"sion	n.
De*mis"sion*a*ry	a.
De*miss"ive	a.
De*miss"ly	adv.
Dem"i*suit`	n.
De*mit"	v. t.
De*mit"	v. i.
De*mit"	n.
De*mi"-tasse"	n.
Dem"i*tint`	n.
Dem"i*tone`	n.
Dem"i*urge	n.
Dem`i*ur"gic	a.
Dem"i*vill`	n.
Dem"i*volt`	n.
Dem"i*wolf`	n.
De*mob`i*li*za"tion	n.
De*mob"i*lize	v. t.
Demochelys	prop. n.
De*moc"ra*cy	n.
Dem"o*crat	n.
Dem`o*crat"ic	a.
Dem`o*crat"ic*al	a.
Dem`o*crat"ic*al*ly	adv.
De*moc"ra*tism	n.
De*moc"ra*tist	n.
De*moc"ra*tize	v. t.
De*moc"ra*ty	n.
demodulator	n.
De`mo*gor"gon	n.
demographic	adj.
de*mog"ra*phy	n.
De`moi`selle"	n.
De*mol"ish	v. t.
De*mol"ish`er	n.
De*mol"ish*ment	n.
Dem`o*li"tion	n.
Dem`o*li"tion*ist	n.
De"mon	n.
De"mon*ess	n.
demonetisation	n.
de*mon`e*ti*za"tion	n.
de*mon"e*tize	v. t.
De*mo"ni*ac	a.
De*mo"ni*ac	n.
Dem`o*ni"a*cal*ly	adv.
Dem`o*ni"a*cism	n.
De*mo"ni*al	a.
De*mo"ni*an	a.
De*mo"ni*an*ism	n.
De*mo"ni*asm	n.
De*mo"nic	a.
De"mon*ism	n.
De"mon*ist	n.
De"mon*ize	v. t.
De`mon*oc"ra*cy	n.
De`mon*og"ra*pher	n.
De`mon*ol"a*try	n.
De`mon*ol"o*ger	n.
De`mon*o*log"ic	a.
De`mon*ol"o*gist	n.
De`mon*ol"o*gy	n.
De`mon*om"a*gy	n.
De*mon`o*ma"ni*a	n.
De*mon"o*mist	n.
De*mon"o*my	n.
De"mon*ry	n.
De"mon*ship	n.
De*mon`stra*bil"i*ty	n.
De*mon"stra*ble	a.
De*mon"stra*ble*ness	n.
De*mon"stra*bly	adv.
De*mon"strance	n.
Dem"on*strate	v. t.
demonstrated	adj.
Dem"on*stra`ter	n.
Dem`on*stra"tion	n.
De*mon"stra*tive	a.
De*mon"stra*tive	n.
De*mon"stra*tive*ly	adv.
De*mon"stra*tive*ness	n.
Dem"on*stra`tor	n.
De*mon"stra*to*ry	a.
De*mor"age	n.
De*mor`al*i*za"tion	n.
De*mor"al*ize	v. t.
demoralized	adj.
demoralizing	adj.
Demosthenes	prop. n.
Dem`os*then"ic	a.
De*mote"	v. t.
De*mot"ic	a.
De*mot"ics	n.
De*mount"	v. i.
De*mount"a*ble	v. t.
Demp"ster	n.
De*mulce"	v. t.
De*mul"cent	a.
De*mul"cent	n.
De*mul"sion	n.
De*mur"	v. i.
De*mur"	v. t.
De*mur"	n.
De*mure"	a.
De*mure"	v. i.
De*mure"ly	adv.
De*mure"ness	n.
De*mur"i*ty	n.
De*mur"ra*ble	a.
De*mur"rage	n.
De*mur"ral	n.
De*mur"rer	n.
De*my"	n.
De*my"	a.
demythologisation	n.
demythologization	n.
demythologize	v. t.
demythologized	adj.
Den	n.
Den	v. i.
Denali	prop. n.
De*nar"co*tize	v. t.
De*na"ri*us	n.
Den"a*ry	a.
Den"a*ry	n.
de*na"tion*al*i*sa"tion	n.
De*na`tion*al*i*za"tion	n.
De*na"tion*al*ize	v. t.
De*nat"u*ral*ize	v. t.
De*na"ture	v. t.
De*na"ture	v. i.
denaturized	adj.
De*nay"	v. t.
De*nay"	n.
Den"dra*chate	n.
Dendranthema	n.
Dendraspis	prop. n.
Den"dri*form	a.
Den"drite	n.
Den*drit"ic	a.
Dendroaspis	prop. n.
Den`dro*c<oe/"la	n. pl.
Den"droid	a.
Dendrolagus	prop. n.
Den"dro*lite	n.
Den*drol"o*gist	n.
Den*drol"o*gous	a.
den*drol"o*gy	n.
Dendromecon	prop. n.
Den*drom"e*ter	n.
Den"e*gate	v. t.
Den`e*ga"tion	n.
Den"gue	n.
De*ni"a*ble	a.
De*ni"al	n.
De*ni"ance	n.
De*ni"er	n.
De*nier"	n.
Den"i*grate	v. t.
denigrating	adj.
Den`i*gra"tion	n.
Den"i*gra`tor	n.
denigratory	a.
Den"im	n.
Den`i*tra"tion	n.
De*ni`tri*fi*ca"tion	n.
De*ni"tri*fy	v. t.
Den`i*za"tion	n.
De*nize"	v. t.
Den"i*zen	n.
Den"i*zen	v. t.
Den`i*zen*a"tion	n.
Den"i*zen*ize	v. t.
Den"i*zen*ship	n.
Den"mark sat"in	n.
De*nom"i*na*ble	a.
De*nom"i*nate	v. t.
De*nom"i*nate	a.
De*nom`i*na"tion	n.
De*nom`i*na"tion*al	a.
De*nom`i*na"tion*al*ism	n.
De*nom`i*na"tion*al*ist	n.
De*nom`i*na"tion*al*ly	adv.
De*nom`i*na"tive	a.
De*nom`i*na"tive	n.
De*nom`i*na"tive*ly	adv.
De*nom"i*na`tor	n.
De*not"a*ble	a.
denotatum	n.
De*no"tate	v. t.
De`no*ta"tion	n.
De*not"a*tive	a.
De*note"	v. t.
De*note"ment	n.
De*not"ive	a.
D<eacute/`noue`ment"	n.
De*nounce"	v. t.
De*nounce"ment	n.
De*noun"cer	n.
Dense	a.
Dense"ly	adv.
Dense"ness	n.
densification	n.
Den*sim"e*ter	n.
densitometer	n.
densitometry	n.
Den"si*ty	n.
Dent	n.
Dent	v. t.
Dent	n.
den"tal	a.
Den"tal	n.
Den"tal*ism	n.
Den*ta"li*um	n.
Dentaria	n.
Den"ta*ry	a.
Den"tate	a.
Den"tate-cil"i*ate	a.
Den"tate*ly	adv.
Den"tate-sin"u*ate	a.
Den*ta"tion	n.
Dent"ed	a.
Dent"el	n.
Den*telle"	n.
Den*tel"li	n. pl.
Den"tex	n.
Den`ti*ce"te	n. pl.
Den"ti*cle	n.
Den*tic"u*late	a.
Den*tic`u*la"tion	n.
Den*tif"er*ous	a.
Den"ti*form	a.
Den"ti*frice	n.
Den*tig"er*ous	a.
Den"til	n.
Den`ti*la"bi*al	a.
Den"ti*la`ted	a.
Den`ti*la"tion	n.
Den"ti*lave	n.
Den"tile	n.
Den`ti*lin"gual	a.
Den*til"o*quist	n.
Den*til"o*quy	n.
Den"ti*nal	a.
Den"tine	n.
Den"ti*phone	n.
Den`ti*ros"ter	n.
Den`ti*ros"tral	a.
Den`ti*ros"trate	a.
Den"ti*scalp	n.
Den"tist	n.
Den*tis"tic	a.
Den"tist*ry	n.
Den*ti"tion	n.
Den"tize	v. t. & i.
Den"toid	a.
Den`to*lin"gual	a.
Den"ture	n.
De*nud"ate	v. t.
Den`u*da"tion	n.
De*nude"	v. t.
denumerable	adj.
De*nun"ci*ate	v. t.
De*nun`ci*a"tion	n.
De*nun"ci*a*tive	a.
De*nun"ci*a`tor	n.
De*nun"ci*a*to*ry	a.
De`nu*tri"tion	n.
De*ny"	v. t.
De*ny"	v. i.
De*ny"ing*ly	adv.
De`ob*struct"	v. t.
De*ob"stru*ent	a.
De"o*dand`	n.
De`o*dar"	n.
De"o*date`	n.
De*o"dor*ant	n.
De*o`dor*i*za"tion	n.
De*o"dor*ize	v. t.
De*o"dor*i`zer	n.
De*on"er*ate	v. t.
De*on`to*log"ic*al	a.
De`on*tol"o*gist	n.
De`on*tol"o*gy	n.
De`o*per"cu*late	a.
De*op"pi*late	v. t.
De*op`pi*la"tion	n.
De*op"pi*la*tive	a. & n.
De*or`di*na"tion	n.
De*os"cu*late	v. t.
De*ox"i*date	v. t.
De*ox`i*da"tion	n.
De*ox`i*di*za"tion	n.
De*ox"i*dize	v. t.
De*ox"i*di`zer	n.
De*ox"y*gen*ate	v. t.
De*ox`y*gen*a"tion	n.
De*ox"y*gen*ize	v. t.
deoxyribonucleic acid	n.
deoxyribonucleotide	n.
deoxyribose	n.
deoxyribosenucleic acid	n.
De*paint"	p. p.
De*paint"	v. t.
De*paint"er	n.
De*par"dieux`	interj.
De*part"	v. i.
De*part"	v. t.
De*part"	n.
De*part"a*ble	a.
departed	n. sing. & pl.
departed	adj.
departing	adj.
De*part"er	n.
De*part"ment	n.
De`part*men"tal	a.
De*part"ment store	n.
De*pas"cent	a.
De*pas"ture	v. t. & i.
De*pa"tri*ate	v. t. & i.
De*pau"per*ate	v. t. & i.
De*pau"per*ate	a.
De*pau"per*ize	v. t.
De*peach"	v. t.
De*pec"ti*ble	a.
De*pec`u*la"tion	n.
De*peinct"	v. t.
De*pend"	v. i.
dependability	n.
De*pend"a*ble	a.
De*pend"ant	n.
De*pend"ence	n.
De*pend"en*cy	n.
De*pend"ent	a.
De*pend"ent	n.
De*pend"ent*ly	adv.
De*pend"er	n.
De*pend"ing*ly	adv.
De*peo"ple	v. t.
De*per"dit	n.
De*per"dite*ly	adv.
Dep`er*di"tion	n.
De*per"ti*ble	a.
De*phase"	v. t.
De*phlegm"	v. t.
De*phleg"mate	v. t.
De`phleg*ma"tion	n.
De*phleg"ma*tor	n.
De*phleg"ma*to*ry	a.
De*phlegm"ed*ness	n.
De`phlo*gis"tic*cate	v. t.
De*phos`phor*i*za"tion	n.
De*pict"	p. p.
De*pict"	v. t.
depicted	adj.
De*pic"tion	n.
De*pic"ture	v. t.
Dep"i*late	v. t.
Dep`i*la"tion	n.
De*pil"a*to*ry	a.
Dep"i*lous	a.
De*pla"nate	a.
De*plant"	v. t.
De`plan*ta"tion	n.
De*plete"	v. t.
depleted	adj.
De*ple"tion	n.
De*ple"tive	a.
De*ple"to*ry	a.
Dep`li*ca"tion	n.
Dep`loi*ta"tion	n.
De*plor`a*bil"i*ty	n.
De*plor"a*ble	a.
De*plor"a*ble*ness	n.
De*plor"a*bly	adv.
De*plo"rate	a.
Dep`lo*ra"tion	n.
De*plore"	v. t.
De*plore"	v. i.
De*plor"ed*ly	adv.
De*plor"ed*ness	n.
De*plore"ment	n.
De*plor"er	n.
De*plor"ing*ly	adv.
De*ploy"	v. t. & i.
de*ploy"	v. t.
De*ploy"	n.
deployment	n.
De*plu"mate	a.
Dep`lu*ma"tion	n.
De*plume"	v. t.
De*po`lar*i*za"tion	n.
De*po"lar*ize	v. t.
De*po"lar*i`zer	n.
De*pol"ish	v. t.
De*pol"ish*ing	n.
De*pone"	v. t.
De*pone"	v. i.
De*po"nent	n.
De*po"nent	a.
De*pop"u*la*cy	n.
De*pop"u*late	v. t.
De*pop"u*late	v. i.
De*pop`u*la"tion	n.
De*pop"u*la`tor	n.
De*port"	v. t.
De*port"	n.
De`por*ta"tion	n.
deportee	n.
De*port"ment	n.
De*por"ture	n.
De*pos"a*ble	a.
De*pos"al	n.
De*pose"	v. t.
De*pose"	v. i.
De*pos"er	n.
De*pos"it	v. t.
De*pos"it	n.
De*pos"i*ta*ry	n.
Dep`o*si"tion	n.
De*pos"i*tor	n.
De*pos"i*to*ry	n.
De*pos"i*tum	n.
De*pos"i*ture	n.
De"pot	n.
Dep"per	a.
Dep`ra*va"tion	n.
De*prave"	v. t.
De*prav"ed*ly	adv.
De*prav"ed*ness	n.
De*prave"ment	n.
De*prav"er	n.
De*prav"ing*ly	adv.
De*prav"i*ty	n.
dep"re*ca*ble	a.
dep"re*cate	v. t.
Dep"re*ca`ting*ly	adv.
Dep`re*ca"tion	n.
Dep"re*ca*tive	a.
Dep"re*ca`tor	n.
dep"re*ca*to*ry	a.
De*pre"ci*ate	v. t.
De*pre"ci*ate	v. i.
De*pre`ci*a"tion	n.
De*pre"ci*a`tive	a.
De*pre"ci*a`tor	n.
De*pre"ci*a*to*ry	a.
Dep"re*da*ble	a.
Dep"re*date	v. t.
Dep"re*date	v. i.
Dep`re*da"tion	n.
Dep"re*da`tor	n.
Dep"re*da`to*ry	a.
De*pred"i*cate	v. t.
Dep`re*hend"	v. t.
Dep`re*hen"si*ble	a.
Dep`re*hen"sion	n.
De*press"	v. t.
De*press"	a.
De*press"ant	n.
De*pressed"	a.
De*press"ing*ly	adv.
De*pres"sion	n.
De*press"ive	a.
De*pres`so*mo"tor	a.
De*press"or	n.
Dep"ri*ment	a.
De*pri"sure	n.
De*priv"a*ble	a.
Dep`ri*va"tion	n.
De*prive"	v. t.
deprived	adj.
De*prive"ment	n.
De*priv"er	n.
De*pros"trate	a.
De`pro*vin"cial*ize	v. t.
Depth	n.
Depth"en	v. t.
Depth"less	a.
De*pu"ce*late	v. t.
De*pu"di*cate	v. t.
De*pulse"	v. t.
De*pul"sion	n.
De*pul"so*ry	a.
Dep"u*rant	a. & n.
Dep"u*rate	a.
Dep"u*rate	v. t.
Dep`u*ra"tion	n.
Dep"u*ra*tive	a.
Dep"u*ra`tor	n.
Dep"u*ra*to*ry	a.
De*pure"	v. t.
De*pur"ga*to*ry	a.
Dep`u*ri"tion	n.
Dep"u*ta*ble	a.
Dep`u*ta"tion	n.
Dep"u*ta`tor	n.
De*pute"	v. t.
De*pute"	n.
dep"u*tise	v. t.
dep"u*tize	v. t.
dep"u*ty	n.
De*quan"ti*tate	v. t.
De*queen"	v. t.
De*rac"i*nate	v. t.
De*rac`i*na"tion	n.
De*raign"	v. t.
De*raign"ment	n.
De*rail"	v. t.
De*rail"ment	n.
De*range"	v. t.
De*ranged"	a.
De*range"ment	n.
De*ran"ger	n.
De*ray"	n.
Der"bi*o	n.
Der"by	n.
Der"by*shire spar"	a.
Dere	v. t.
Dere	n.
De*re"cho	n.
De*reine	v. t.
Der"e*lict	a.
Der"e*lict	n.
Der`e*lic"tion	n.
De`re*li"gion*ize	v. t.
Dere"ling	n.
Dere"ling	n.
De`rep*li*ca"tion	n.
Derf	a.
De*ride"	v. t.
De*rid"er	n.
De*rid"ing*ly	adv.
De ri`gueur"	n.
De*ri"sive	a.
De*ri"so*ry	a.
De*riv"a*ble	a.
De*riv"a*bly	adv.
De*riv"al	n.
Der"i*vate	a.
Der"i*vate	v. t.
Der`i*va"tion	n.
Der`i*va"tion*al	a.
De*riv"a*tive	a.
De*riv"a*tive	n.
derivatize	v. t.
De*rive"	v. t.
De*rive"	v. i.
De*rive"ment	n.
De*riv"er	n.
Derk	a.
-derm	n.
Derm	n.
Der"ma	n.
Dermacentor	n.
Derm"al	a.
Der*map"te*ra	n.
Der*mat"ic	a.
Der`ma*ti"tis	n.
Der*mat"o*gen	n.
Der*mat"o*gen	n.
Der*ma*tog"ra*phy	n.
Der"ma*toid	a.
dermatologic	adj.
der`ma*tol"o*gist	n.
Der`ma*tol"o*gy	n.
Der`ma*to*path"ic	a.
Der*mat"o*phyte	n.
Der*mes"tes	n.
Der*mes"toid	a.
Der"mic	a.
Der"mis	n.
Der`mo*bran`chi*a"ta	n. pl.
Der`mo*bran"chi*ate	a.
Der`mo*h<ae/"mal	a.
Der"moid	a.
Der`mo*neu"ral	a.
Der`mo*path"ic	a.
Der"mo*phyte	n.
Der*mop"te*ra	n. pl.
Der*mop"ter*an	n.
Der*mop"te*ri	n. pl.
Der*mop`te*ryg"i*i	n. pl.
Der`mo*skel"e*ton	n.
Der`mos*to"sis	n.
Dern	n.
Dern	a.
Derne	v. t. & i.
Dern"ful	a.
Der`nier"	a.
Dern"ly	adv.
Der"o*gant	a.
Der"o*gate	v. t.
Der"o*gate	v. i.
Der"o*gate	n.
Der"o*gate*ly	adv.
Der`o*ga"tion	n.
De*rog"a*tive	a.
Der"o*ga`tor	n.
de*rog"a*to*ri*ly	adv.
de*rog"a*to*ri*ness	n.
de*rog"a*to*ry	a.
Der`o*tre"ma*ta	n. pl.
Der"re	a.
Der"rick	n.
Der"ring	a.
derring-do	n.
Der"rin*ger	n.
Derth	n.
Der`tro*the"ca	n.
Der"vish	n.
Der"worth	a.
desalinate	v. t.
desalination	n.
desalinisation	n.
desalinization	n.
desalinize	v. t.
desalt	v.
descale	v. t.
Des"cant	n.
Des*cant"	v. i.
Des*cant"er	n.
Descartes	prop. n.
De*scend"	v. i.
De*scend"	v. t.
De*scend"ant	a.
De*scend"ant	n.
descendants	n.
De*scend"ent	a.
De*scend"er	n.
De*scend`i*bil"i*ty	n.
De*scend"i*ble	a.
De*scend"ing	a.
De*scend"ing*ly	adv.
De*scen"sion	n.
De*scen"sion*al	a.
De*scen"sive	a.
De*scen"so*ry	n.
De*scent"	n.
De*scrib"a*ble	a.
De*scribe"	v. t.
De*scribe"	v. i.
De*scrib"ent	n.
De*scrib"er	n.
De*scri"er	n.
De*scrip"tion	n.
De*scrip"tive	a.
De*scrive"	v. t.
De*scry"	v. t.
De*scry"	n.
Des"e*cate	v. t.
Des"e*crate	v. t.
Des"e*cra`ter	n.
Des`e*cra"tion	n.
Des"e*cra`tor	n.
De*seg`men*ta"tion	n.
de*seg"re*gate	v. t.
de`seg*re*ga"tion	n.
desensitisation	n.
desensitise	v. t.
desensitized	adj.
desensitization	n.
desensitize	v. t.
desensitizing	adj.
De*sert"	n.
Des"ert	n.
Des"ert	a.
De*sert"	v. t.
De*sert"	v. i.
deserted	adj.
De*sert"er	n.
De*sert"ful	a.
De*ser"tion	n.
De*sert"less	a.
De*sert"less*ly	adv.
Des"ert*ness	n.
De*sert"rix	n.
De*serve"	v. t.
de*serve"	v. i.
deserved	adj.
de*serv"ed*ly	adv.
De*serv"ed*ness	n.
De*serv"er	n.
De*serv"ing	n.
De*serv"ing	a.
desex	v. t.
desexualize	v. i. & t.
Des`ha*bille	n.
desicate	v. t.
dessicate	v. t.
De*sic"cant	a.
Des"ic*cate	v. t.
Des"ic*cate	v. i.
Des`ic*ca"tion	n.
De*sic"ca*tive	a.
Des"ic*ca`tor	n.
De*sic"ca*to*ry	a.
De*sid"er*a*ble	a.
De*sid`e*ra"ta	n. pl.
De*sid"er*ate	v. t.
De*sid`er*a"tion	n.
De*sid"er*a*tive	a.
De*sid"er*a*tive	n.
De*sid`e*ra"tum	n.
De*sid"i*ose`	a.
De*sid"i*ous*ness	n.
De*sight"	n.
De*sight"ment	n.
De*sign"	v. t.
De*sign"	v. i.
De*sign"	n.
Des"ig*na*ble	a.
Des"ig*nate	a.
Des"ig*nate	v. t.
Des`ig*na"tion	n.
Des"ig*na*tive	a.
Des"ig*na`tor	n.
Des"ig*na*to*ry	a.
De*sign"ed*ly	adv.
De*sign"er	n.
De*sign"ful	a.
De*sign"ing	a.
De*sign"ing	n.
De*sign"less	a.
De*sign"ment	n.
De*sil"ver	v. t.
De*sil`ver*i*za"tion	n.
De*sil"ver*ize	v. t.
Des"i*nence	n.
Des"i*nent	a.
Des`i*nen"tial	a.
De*sip"i*ent	a.
De*sir`a*bil"i*ty	n.
De*sir"a*ble	a.
De*sir"a*ble*ness	n.
De*sir"a*bly	adv.
De*sire"	v. t.
De*sire"	n.
De*sire"ful	a.
De*sire"ful*ness	n.
De*sire"less	a.
De*sir"er	n.
De*sir"ous	a.
De*sir"ous*ly	adv.
De*sir"ous*ness	n.
De*sist"	v. i.
De*sist"ance	n.
De*sist"ive	a.
De*si"tion	n.
Des"i*tive	a.
Des"i*tive	n.
Desk	n.
Desk	v. t.
Desk"work`	n.
Des"man	n.
Des"mid	n.
Des"mine	n.
Des`mo*bac*te"ri*a	n. pl.
Desmodontidae	n.
Desmodus	n.
Des"mo*dont	n.
Des*mog"na*thous	a.
Des"moid	a.
Des*mol"o*gy	n.
Des`mo*my*a"ri*a	n. pl.
Des"o*late	a.
Des"o*late	v. t.
desolated	adj.
Des"o*late*ly	adv.
Des"o*late*ness	n.
Des"o*la`ter	n.
Des`o*la"tion	n.
Des"o*la`tor	n.
Des"o*la*to*ry	a.
De`so*phis"ti*cate	v. t.
Des`ox*al"ic	a.
desoxyribonucleic acid	n.
De*spair"	v. i.
De*spair"	v. t.
De*spair"	n.
De*spair"er	n.
De*spair"ful	a.
De*spair"ing	a.
De*spar"ple	v. t. & i.
De*spatch"	n. & v.
De`spe*cif"i*cate	v. t.
De*spec`i*fi*ca"tion	n.
De*spect"	n.
De*spec"tion	n.
De*speed"	v. t.
De*spend"	v. t.
Des`per*a"do	n.
Des"per*ate	a.
Des"per*ate	n.
Des"per*ate*ly	adv.
Des"per*ate*ness	n.
Des`per*a"tion	n.
Des`pi*ca*bil"i*ty	n.
Des"pi*ca*ble	a.
Des"pi*ca*ble*ness	n.
Des"pi*ca*bly	adv.
Des*pi"cien*cy	n.
De*spis"a*ble	a.
De*spis"al	n.
De*spise"	v. t.
De*spis"ed*ness	n.
De*spise"ment	n.
De*spis"er	n.
De*spis"ing*ly	adv.
De*spite"	n.
De*spite"	v. t.
De*spite"	prep.
De*spite"ful	a.
Des*pit"e*ous	a.
Des*pit"e*ous*ly	adv.
De*spit"ous	a.
De*spoil"	v. t.
de*spoil"	n.
despoiled	adj.
de*spoil"er	n.
de*spoil"ment	n.
Despoina	prop. n.
de*spo`li*a"tion	n.
de*spond"	v. i.
De*spond"	n.
De*spond"ence	n.
De*spond"en*cy	n.
De*spond"ent	a.
De*spond"er	n.
De*spond"ing*ly	adv.
De*spon"sage	n.
De*spon"sate	v. t.
Des`pon*sa"tion	n.
De*spon"so*ry	n.
De*sport"	v. t. & i.
Des"pot	n.
Des"po*tat	n.
Des*pot"ic	a.
Des"po*tism	n.
Des"po*tist	n.
Des"po*tize	v. t.
De*spread"	v. t. & i.
Des"pu*mate	v. t. & i.
Des`pu*ma"tion	n.
De*spume"	v. t.
Des"qua*mate	v. i.
Des`qua*ma"tion	n.
De*squam"a*tive	a.
De*squam"a*to*ry	n.
Dess	n.
Des*sert"	n.
Des*tem"per	n.
Des"tin	n.
Des"ti*na*ble	a.
Des"ti*na*bly	adv.
Des"ti*nal	a.
Des"ti*nate	a.
Des"ti*nate	v. t.
Des`ti*na"tion	n.
Des"tine	v. t.
Des"ti*nist	n.
Des"ti*ny	n.
De*stit"u*ent	a.
Des"ti*tute	a.
Des"ti*tute	v. t.
Des"ti*tute*ly	adv.
Des"ti*tute*ness	n.
Des`ti*tu"tion	n.
Des*trer"	n.
De*strie"	v. t.
De*stroy"	v. t.
De*stroy"a*ble	a.
destroyed	adj.
De*stroy"er	n.
De*struct"	v. t.
De*struc`ti*bil"i*ty	n.
De*struc"ti*ble	a.
De*struc"ti*ble*ness	n.
De*struc"tion	n.
De*struc"tion*ist	n.
De*struc"tive	a.
De*struc"tive	n.
De*struc"tive*ly	adv.
destructive-metabolic	adj. prenom.
De*struc"tive*ness	n.
De*struc"tor	n.
De*struie"	v. t.
Des`u*da"tion	n.
De*suete"	a.
Des"ue*tude	n.
De*sul"phu*rate	v. t.
De*sul`phu*ra"tion	n.
De*sul"phur*ize	v. t.
Des"ul*to*ri*ly	adv.
Des"ul*to*ri*ness	n.
Des`ul*to"ri*ous	a.
Des"ul*to*ry	a.
De*sume"	v. t.
desynchronize	v. t.
desynchronization	n.
De`syn*on`y*mi*za"tion	n.
De`syn*on"y*mize	v. t.
De*tach"	v. t.
De*tach"	v. i.
De*tach"a*ble	a.
De*tached"	a.
De*tach"ment	n.
De"tail	n.
De"tail	v. t.
de*tailed"	adj.
De*tail"er	n.
detailing	n.
details	n.
De*tain"	v. t.
De*tain"	n.
De*tain"der	n.
De*tain"er	n.
De*tain"ment	n.
De*tect"	a.
De*tect"	v. t.
De*tect"a*ble	a.
De*tect"er	n.
De*tec"tion	n.
De*tect"ive	a.
De*tect"ive	n.
De*tect"or	n.
De*tect"or bar	v. t.
De*tent"	n.
detente	n.
De*ten"tion	n.
De*ter"	v. t.
De*terge"	v. t.
De*ter"gen*cy	n.
De*ter"gent	a.
De*te"ri*o*rate	v. t.
de*te"ri*o*rate	v. i.
deteriorating	adj.
De*te`ri*o*ra"tion	n.
de*te`ri*or"i*ty	n.
De*ter"ment	n.
De*ter`mi*na*bil"i*ty	n.
De*ter"mi*na*ble	a.
De*ter"mi*na*ble*ness	n.
De*ter"mi*na*cy	n.
De*ter"mi*nant	a.
De*ter"mi*nant	n.
De*ter"mi*nate	a.
De*ter"mi*nate	v. t.
De*ter"mi*nate*ly	adv.
De*ter"mi*nate*ness	n.
De*ter`mi*na"tion	n.
De*ter"mi*na*tive	a.
De*ter"mi*na*tive	n.
De*ter"mi*na`tor	n.
De*ter"mine	v. t.
De*ter"mine	v. i.
De*ter"mined	a.
De*ter"min*ed*ly	adv.
De*ter"min*er	n.
De*ter"min*ism	n.
De*ter"min*ist	n.
de*ter`min*ist"ic	a.
De`ter*ra"tion	n.
De*ter"rence	n.
De*ter"rent	a.
De*ter"rent	n.
De*ter"sion	n.
De*ter"sive	a.
De*ter"sive*ly	adv.
De*ter"sive*ness	n.
De*test"	v. t.
De*test`a*bil"i*ty	n.
De*test"a*ble	a.
De*test"a*ble*ness	n.
De*test"a*bly	adv.
De*tes"tate	v. t.
Det`es*ta"tion	n.
De*test"er	n.
de*throne"	v. t.
de*throne"ment	n.
de*thron"er	n.
De*thron`i*za"tion	n.
De*thron"ize	v. t.
Det"i*nue	n.
Det"o*nate	v. i.
Det"o*nate	v. t.
Det"o*na`ting	a. & n.
Det`o*na"tion	n.
Det"o*na`tor	n.
Det`o*ni*za"tion	n.
Det"o*nize	v. t. & i.
De*tor"sion	n.
De*tort"	v. t.
De*tor"tion	n.
De`tour"	n.
detox	n.
detox	v. t.
detoxicate	v. t.
detoxify	v. t.
detoxification	n.
De*tract"	v. t.
De*tract"	v. i.
De*tract"er	n.
De*tract"ing*ly	adv.
De*trac"tion	n.
De*trac"tious	a.
De*tract"ive	a.
De*tract"ive*ness	n.
De*tract"or	n.
De*tract"o*ry	a.
De*tract"ress	n.
De*train"	v. i. & t.
De*trect"	v. t.
detribalisation	n.
detribalization	n.
detribalize	v. t.
Det"ri*ment	n.
Det"ri*ment	v. t.
Det`ri*men"tal	a.
Det`ri*men"tal*ness	n.
De*tri"tal	a.
De*trite"	a.
De*tri"tion	n.
De*tri"tus	n.
De*trude"	v. t.
De*trun"cate	v. t.
De`trun*ca"tion	n.
De*tru"sion	n.
Dette	n.
Dette"les	a.
De`tu*mes"cence	n.
De"tur	n.
De*turb"	v. t.
De*tur"bate	v. t.
Det`ur*ba"tion	n.
De*turn"	v. t.
De*tur"pate	v. t.
Det`ur*pa"tion	n.
Deuce	n.
Deuce	n.
Deu"ced	a.
Deuse	n.
Deu`ter*o*ca*non"ic*al	a.
Deu`ter*og"a*mist	n.
Deu`ter*og"a*my	n.
Deu`ter*o*gen"ic	a.
Deu`ter*on"o*mist	n.
Deu`ter*on"o*my	n.
Deu`ter*o*pa*thi"a	n.
Deu`ter*o*path"ic	a.
Deu`ter*os"co*py	n.
Deu`ter*o*zo"oid	n.
Deut`hy*drog"u*ret	n.
Deu"to-	n.
Deu"to*plasm	n.
Deu`to*plas"tic	a.
Deu`to*sul"phu*ret	n.
Deu*tox"ide	n.
Deut"zi*a	n.
Dev	n.
De`va*na"ga*ri	n.
De*vap`o*ra"tion	n.
De*vast"	v. t.
Dev"as*tate	v. t.
devastated	adj.
devastating	adj.
Dev`as*ta"tion	n.
Dev"as*ta`tor	n.
Dev`as*ta"vit	n.
De"va*ta	n.
Deve	a.
Dev"el*in	n.
De*vel"op	v. t.
De*vel"op	v. i.
De*vel"op*a*ble	a.
developed	adj.
developing	adj.
developing	n.
De*vel"op*er	n.
De*vel"op*ment	n.
De*vel`op*men"tal	a.
Dev`e*nus"tate	v. t.
De*ver"gence	n.
De*vest"	v. t.
De*vest"	v. i.
De*vex"	a.
De*vex"	n.
De*vex"i*ty	n.
De"vi	n.
deviance	n.
De"vi*ant	a.
De"vi*ate	v. i.
De"vi*ate	v. t.
de"vi*ate	a.
de"vi*ate	n.
de`vi*a"tion	n.
De"vi*a`tor	n.
De"vi*a*to*ry	a.
De*vice"	n.
De*vice"ful	a.
De*vice"ful*ly	adv.
Dev"il	n.
dev"il	v. t.
Dev"il-div`er	n.
deviled egg	n.
Dev"il*et	n.
Dev"il*fish`	n.
Dev"il*ing	n.
Dev"il*ish	a.
Dev"il*ism	n.
Dev"il*ize	v. t.
Dev"il*kin	n.
devil-may-care	adj.
Dev"il*ment	n.
Dev"il*ry	n.
Dev"il's darn"ing-nee`dle	v. t.
Dev"il*ship	n.
Dev"il*try	n.
Dev"il*wood`	n.
De"vi*ous	a.
De*vir"gin*ate	a.
De*vir"gin*ate	v. t.
De*vir`gi*na"tion	n.
De*vis"a*ble	a.
De*vis"al	n.
De*vise"	v. t.
De*vise"	v. i.
De*vise"	n.
De*vise"	n.
Dev`i*see"	n.
De*vis"er	n.
De*vis"or	n.
Dev"i*ta*ble	a.
De*vi"tal*ize	v. t.
Dev`i*ta"tion	n.
De*vit`ri*fi*ca"tion	n.
De*vit"ri*fy	v. t.
De*vo"cal*ize	v. t.
Dev`o*ca"tion	n.
De*void"	v. t.
De*void"	a.
De*voir"	n.
Dev"o*lute	v. t.
Dev`o*lu"tion	n.
De*volve"	v. t.
De*volve"	v. i.
De*volve"ment	n.
De"von	n.
De*vo"ni*an	a.
De*vo"ni*an	n.
Dev`o*ra"tion	n.
De*vo"ta*ry	n.
De*vote"	v. t.
De*vote"	a.
De*vote"	n.
De*vot"ed	a.
Dev`o*tee"	n.
De*vote"ment	n.
De*vot"er	n.
De*vo"tion	n.
De*vo"tion*al	a.
De*vo"tion*al*ist	n.
De*vo`tion*al"i*ty	n.
De*vo"tion*al*ly	adv.
De*vo"to	n.
De*vo"tor	n.
De*vour"	v. t.
De*vour"a*ble	a.
De*vour"er	n.
De*vour"ing*ly	adv.
De*vout"	a.
De*vout"	n.
De*vout"ful	a.
De*vout"less	a.
De*vout"ly	adv.
De*vout"ness	n.
De*vove"	v. t.
De*vow"	v. t.
De*vul"gar*ize	v. t.
Dew	n.
Dew	v. t.
Dew	a. & n.
Dew"ar	n.
Dew"claw`	n.
Dew"drop`	n.
Deweyan	prop. adj.
dew"fall`	n.
dew"i*ness	n.
Dew"lap`	n.
Dew"lapped`	a.
Dew"less	a.
Dew"-point`	n.
Dew"ret`	v. t.
Dew"ret`ting	n.
Dew"rot`	v. t.
Dew"worm`	n.
Dew"y	a.
dexamethasone	n.
Dexedrine	n.
Dex"ter	a.
Dex"ter	n.
Dex*ter"i*cal	a.
Dex*ter"i*ty	n.
Dex"ter*ous	a.
Dex"ter*ous*ly	adv.
Dex"ter*ous*ness	n.
Dex"trad	adv.
Dex"tral	a.
Dex*tral"i*ty	n.
Dex"tral*ly	adv.
Dex*trer"	n.
Dex"trin	n.
Dex"tro-	a.
Dex`tro*glu"cose`	n.
Dex`tro*gy"rate	a.
Dex*tron"ic	a.
Dex`tro*ro"ta*ry	a.
Dex`tro*ro"ta*to*ry	a.
Dex*tror"sal	a.
Dex"trose`	n.
Dex"trous	a.
Dey	n.
Dey	n.
Deye	v. i.
Deyn"te	n. & a.
De*zinc`i*fi*ca"tion	n.
De*zinc"i*fy	v. t.
Dhaka	prop. n.
Dharma	prop. n.
Dhaulagiri	prop. n.
Dhole	n.
Dho"ny	n.
Dhoor"ra	n.
Dhow	n.
Di-	n.
Di*ab`a*te"ri*al	a.
diabatic	adj.
di`a*be"tes	n.
Di`a*bet"ic	a.
Dia`ble*rie"	n.
Di`a*bol"ic	a.
Di`a*bol"i*fy	v. t.
Di*ab"o*lism	n.
Di*ab"o*lize	v. t.
Di*ab"o*lo	n.
Di`a*ca*thol"i*con	n.
Di`a*caus"tic	a.
Di`a*caus"tic	n.
Di*ach"y*lon	n.
Di*ac"id	a.
Di`a*co"di*um	n.
Di*ac"o*nal	a.
Di*ac"o*nate	n.
Di*ac"o*nate	a.
Di*ac"o*pe	n.
Di`a*cous"tic	a.
Di`a*cous"tics	n.
Di`a*crit"ic	a.
Di`ac*tin"ic	a.
Di`a*del"phi*a	n. pl.
Di`a*del"phi*an	a.
Di"a*dem	n.
Di"a*dem	v. t.
Di"a*drom	n.
Di*<ae/r"e*sis	n.
Di`<ae/*ret"ic	a.
Di`a*ge`o*trop"ic	a.
Di`a*ge*ot"ro*pism	n.
Di"a*glyph	n.
Di`a*glyph"ic	a.
Di`ag*nose"	v. t. & i.
diagnosing	n.
Di`ag*no"sis	n.
Di`ag*nos"tic	a.
Di`ag*nos"tic	n.
Di`ag*nos"ti*cate	v. t. & i.
Di`ag*nos"tics	n.
Di`a*gom"e*ter	n.
Di*ag"o*nal	a.
Di*ag"o*nal	n.
diagonalizable	adj.
diagonalize	v. t.
Di*ag"o*nal*ly	adv.
Di`a*go"ni*al	a.
Di"a*gram	n.
Di"a*gram	v. t.
Di`a*gram*mat"ic	a.
Di"a*graph	n.
Di`a*graph"ic	a.
Di`a*graph"ics	n.
Di`a*he`li*o*trop"ic	a.
Di`a*he`li*ot"ro*pism	n.
Di"al	n.
Di"al	v. t.
Di"a*lect	n.
Di`a*lec"tal	a.
Di`a*lec"tic	n.
Di`a*lec"tic	a.
Di`a*lec"tic*al*ly	adv.
Di`a*lec*ti"cian	n.
Di`a*lec"tics	n.
Di`a*lec*tol"o*gy	n.
Di`a*lec"tor	n.
Di"al*ing	n.
Di"al*ist	n.
Di*al"la*ge	n.
Di"al*lage	n.
Di"al*lel	a.
Di*al"lyl	n.
Di`a*log"ic*al	a.
Di`a*log"ic*al*ly	adv.
Di*al"o*gism	n.
Di*al"o*gist	n.
Di*al`o*gis"tic	a.
Di*al"o*gite	n.
Di*al"o*gize	v. t.
Di"a*logue	n.
Di"a*logue	v. i.
Di"a*logue	v. t.
Di`al*y*pet"al*ous	a.
Di*al"y*sis	n.
Di`a*lyt"ic	a.
Di*al"y*zate	n.
Di`a*ly*za"tion	n.
Di"a*lyze	v. t.
Di"a*lyzed	a.
Di"a*ly`zer	n.
Di`a*mag"net	n.
Di`a*mag*net"ic	a.
Di`a*mag*net"ic	n.
Di`a*mag*net"ic*al*ly	adv.
Di`a*mag"net*ism	n.
Di`a*man*tif"er*ous	a.
Di`a*man"tine	a.
Di*am"e*ter	n.
Di*am"e*tral	a.
Di*am"e*tral	n.
Di*am"e*tral*ly	adv.
Di*am"e*tric	a.
Di*am"e*tric*al*ly	adv.
Di*am"ide	n.
Di*am"i*do-	a.
Di*am"ine	n.
Di"a*mond	n.
Di"a*mond	a.
Diamond anniversary	n.
Di"a*mond*ed	a.
Di"a*mond*ize	v. t.
Di"a*mond-shaped`	a.
Diamond State	n.
Di"an	a.
Di*a"na	n.
Di*an"dri*a	n. pl.
Di*an"dri*an	a.
Di*an"drous	n.
Di*a"ni*um	n.
Di`a*no*et"ic	a.
Di`a*noi*al"o*gy	n.
Di*an"thus	n.
Di"a*pase	n.
Di"a*pasm	n.
Di`a*pa"son	n.
Di`a*pe*de"sis	n.
Diapensiaceae	n.
Diapensiales	n.
Di`a*pen"te	n.
Di"a*per	n.
Di"a*per	v. t.
Di"a*per	v. i.
Di"a*per*ing	n.
Di"a*phane	n.
Di"a*phaned	a.
Di`a*pha*ne"i*ty	n.
Di`a*phan"ic	a.
Di*aph"a*nie	n.
Di`a*pha*nom"e*ter	n.
Di`a*phan"o*scope	n.
Di`a*phan"o*type	n.
Di*aph"a*nous	a.
Di*aph"a*nous*ly	adv.
Di*aph`e*met"ric	a.
Di`a*phon"ic	a.
Di`a*phon"ics	n.
Di`a*pho*re"sis	n.
Di`a*pho*ret"ic	a.
Di`a*pho*ret"ic	n.
Di"a*phote	n.
Di"a*phragm	n.
Di`a*phrag*mat"ic	a.
diaphyseal	adj.
Di*aph"y*sis	n.
Di`ap*no"ic	a.
Di*ap`o*phys"ic*al	a.
Di`a*poph"y*sis	n.
Di"arch*y	n.
Di*a"ri*al	a.
Di"a*rist	n.
Di`ar*rhe"a	n.
Di`ar*rhe"al	a.
Di`ar*rhet"ic	a.
Di`ar*thro"di*al	a.
Di`ar*thro"sis	n.
Di"a*ry	n.
Di"a*ry	a.
Di*as"po*ra	n.
Di"a*spore	n.
Di"a*stase	n.
Di`a*sta"sic	a.
Di*as"ta*sis	n.
Di`a*stat"ic	a.
Di"a*stem	n.
Di`a*ste"ma	n.
Di*as"ter	n.
Di*as"to*le	n.
Di`as*tol"ic	a.
Di"a*style	n.
Di`a*tes"sa*ron	n.
Di`a*ther"mal	a.
Di`a*ther"man*cy	n.
Di`a*ther"ma*nism	n.
Di`a*ther"ma*nous	a.
Di`a*ther"mic	a.
Di`a*ther*mom"e*ter	n.
Di`a*ther"mous	a.
Di*ath"e*sis	n.
Di`a*thet"ic	a.
Di"a*tom	n.
di`a*to*ma"ceous	a.
di`a*to*ma"ceous earth`	a.
Diatomophyceae	n.
Di*at"o*mous	a.
Di`a*ton"ic	a.
Di`a*ton"ic*al*ly	adv.
Di"a*tribe	n.
Di*at"ri*bist	n.
Di`a*try"ma	n.
Di`a*zeuc"tic	a.
Di*az"o-	v. t.
Dib	v. i.
Dib	n.
Di*ba"sic	a.
Di`ba*sic"i*ty	n.
Dib"ber	n.
Dib"ble	n.
Dib"ble	v. i.
Dib"ble	v. t.
Dib"bler	n.
dibrach	n.
dibranch	n.
Dibranchia	n.
Di*bran`chi*a"ta	n. pl.
Di*bran"chi*ate	a.
dibs	n.
dib"stone`	n.
di*bu"tyl	n.
di*ca"cious	a.
di*cac"i*ty	n.
di*cal"cic	a.
di`car*bon"ic	a.
di"cast	n.
di*cas"ter*y	n.
dice	n.
dice	v. i.
dice	v. t.
dice"box`	n.
Di*cen"tra	Prop. n.
di*ceph"a*lous	a.
Di"cer	n.
Dich	v. i.
Di*chas"tic	a.
Di`chla*myd"e*ous	a.
Di*chlo"ride	n.
Di*chog"a*mous	a.
Di*chog"a*my	n.
Di*chot"o*mist	n.
Di*chot"o*mize	v. t.
Di*chot"o*mize	v. i.
Di*chot"o*mous	a.
Di*chot"o*my	n.
Di*chro"ic	a.
Di*chro"i*scope	n.
Di"chro*ism	n.
Di"chro*ite	n.
Di`chro*it"ic	a.
Di*chro"mate	n.
Di`chro*mat"ic	a.
Di*chro"ma*tism	n.
Di*chro"mic	a.
Di"chro*ous	a.
Di"chro*scope	n.
Di`chro*scop"ic	a.
Di"cing	n.
Dick*cis"sel	n.
Dick"ens	n. <or/ interj.
Dick"er	n.
Dick"er	v. i. & t.
Dick"ey	n.
dickeybird	n.
dickie	n.
dickie-seat	n.
Dicksonia	prop. n.
Dicksoniaceae	prop. n.
dicky	adj.
dicky	n.
dickybird	n.
dicky-seat	n.
Di*clin"ic	a.
Dic"li*nous	a.
Di*coc"cous	a.
di"cot	n.
di*cot"yl	n.
di*cot`y*le"don	n.
Dicotyledonae	n.
Dicotyledones	n.
di*cot`y*led"on*ous	a.
Di"cro*tal	a.
Di*crot"ic	a.
Di"cro*tism	n.
Dic"ta	n. pl.
Dic"ta*graph	n.
Dic*tam"nus	n.
Dic"ta*phone	n.
Dic"tate	v. t.
Dic"tate	v. i.
Dic"tate	n.
Dic*ta"tion	n.
Dic*ta"tor	n.
Dic`ta*to"ri*al	a.
Dic`ta*to"ri*an	a.
Dic*ta"tor*ship	n.
Dic"ta*to*ry	a.
Dic*ta"tress	n.
Dic*ta"trix	n.
Dic*ta"ture	n.
Dic"tion	n.
Dic`tion*al"ri*an	n.
Dic"tion*a*ry	n.
Dic"to*graph	n.
dictostylium	n.
Dic"tum	n.
Dic*ty"o*gen	n.
Di*cy"a*nide	n.
Di`cy*e"ma*ta	n. pl.
Di`cy*e"mid	a.
Di*cyn"o*dont	n.
Did	imp.
Di*dac"tic	a.
Di*dac"tic	n.
Di*dac"tic*al*ly	adv.
Di*dac"ti*cism	n.
Di`dac*tic"i*ty	n.
Di*dac"tics	n.
Di*dac"tyl	n.
Di*dac"tyl*ous	a.
Di"dal	n.
Di"dap`per	n.
Di*das"ca*lar	a.
Di`das*cal"ic	a.
Did"dle	v. i.
Did"dle	v. t.
Did"dler	n.
Di*del"phi*a	n. pl.
Di*del"phi*an	a.
Di*del"phic	a.
Di*del"phid	a.
Di*del"phid	n.
Di*del"phous	a.
Di*del"phyc	a.
Di*del"phys	n.
Di"dine	a.
Di"do	n.
Di*do"ni*a	n.
Di"drachm	n.
Didst	2d pers. sing. imp.
Di*duce"ment	n.
Di*duc"tion	n.
Di"dym	n.
Di*dym"i*um	n.
Did"y*mous	a.
Did`y*na"mi*a	n. pl.
Did`y*na"mi*an	a.
Di*dyn"a*mous	a.
Die	v. i.
Die	n.
Di*e"cian	a.
Di*e"dral	a.
Dieffenbachia	n.
Di`e*ge"sis	n.
die"hard`	n.
die"hard`	a.
Di`e*lec"tric	n.
Di*el"y*tra	n.
Di`en*ceph"a*lon	n.
Di*er"e*sis	n.
Diervilla	n.
Diesel	n.
Die"sink`er	n.
Die"sink`ing	n.
Di"es I"r<ae/	n.
Di"es ju*rid"i*cus	n.
diestrous	adj.
diestrum	n.
diestrus	n.
Di"et	n.
Di"et	v. t.
Di"et	v. i.
Di"et	n.
Di`e*ta"ri*an	n.
Di"et*a*ry	a.
Di"et*a*ry	n.
Di"et*er	n.
Di`e*tet"ic	a.
Di`e*tet"ic*al*ly	adv.
Di`e*tet"ics	n.
Di`e*tet"ist	n.
Di*eth`yl*am"ine	n.
Di*et"ic	a.
Di*et"ic*al	a.
Di"et*ine	n.
Di"et*ist	n.
Dif*fame`	n.
Dif*far`re*a"tion	n.
Dif"fer	v. i.
Dif"fer	v. t.
Dif"fer*ence	n.
Dif"fer*ence	v. t.
Dif"fer*ent	a.
dif`fer*en"ti*a	n.
differentiable	adj.
differentiated	adj.
dif`fer*en"tial	a.
Dif`fer*en"tial	n.
Dif`fer*en"tial*ly	adv.
Dif`fer*en"ti*ate	v. t.
Dif`fer*en"ti*ate	v. i.
Dif`fer*en`ti*a"tion	n.
Dif`fer*en"ti*a`tor	n.
Dif"fer*ent*ly	adv.
Dif"fer*ing*ly	adv.
Dif"fi*cile	a.
Dif`fi*cil"i*tate	v. t.
Dif"fi*cult	a.
Dif"fi*cult	v. t.
Dif"fi*cult*ate	v. t.
Dif"fi*cult*ly	adv.
Dif"fi*cult*ness	n.
Dif"fi*cul*ty	n.
Dif*fide"	v. i.
Dif"fi*dence	n.
Dif"fi*den*cy	n.
Dif"fi*dent	a.
Dif"fi*dent*ly	adv.
Dif*find	v. t.
Dif*fine"	v. t.
Dif*fin"i*tive	a.
Dif*fis"sion	n.
Dif*fla"tion	n.
Dif"flu*ence	n.
Dif"flu*ent	a.
Dif"form`	a.
Dif*form"i*ty	n.
Dif*fract"	v. t.
Dif*frac"tion	n.
Dif*frac"tive	a.
Dif*fran"chise	n.
Dif*fuse"	v. t.
Dif*fuse"	v. i.
Dif*fuse"	a.
Dif*fused"	a.
Dif*fuse"ly	adv.
Dif*fuse"ness	n.
Dif*fus"er	n.
Dif*fu`si*bil"i*ty	n.
Dif*fu"si*ble	a.
Dif*fu"si*ble*ness	n.
Dif*fu"sion	n.
Dif*fu"sive	a.
Dif*fu"sive*ly	adv.
Dif*fu"sive*ness	n.
Dif`fu*siv"i*ty	n.
Dig	v. t.
Dig	v. i.
dig	v. t.
Dig	n.
Dig"a*mist	n.
Di*gam"ma	n.
Di*gam"mate	a.
Dig"a*mous	a.
Dig"a*my	n.
Di*gas"tric	a.
Di*ge"ne*a	n. pl.
Di*gen"e*sis	n.
Dig"e*nous	a.
Dig"er*ent	v. t.
Di*gest"	v. i.
Di"gest	n.
Di*gest"ed*ly	adv.
Di*gest"er	n.
Di*gest`i*bil"i*ty	n.
Di*gest"i*ble	a.
Di*gest"i*ble*ness	n.
Di*ges"tion	n.
Di*gest"ive	a.
Di*gest"ive	n.
Di*gest"or	n.
Di*ges"ture	n.
Dig"ga*ble	a.
Dig"ger	n.
Dig"gers	n. pl.
Dig"ging	n.
diggings	n.
Dight	v. t.
Dight"er	n.
dig"it	n.
dig"it	v. t.
dig"i*tal	a.
digital computer	n.
dig"i*ta`lin	n.
Dig`i*ta"lis	n.
digitalisation	n.
digitalization	n.
digitalize	v. t.
Digitaria	n.
dig"i*tate	v. t.
Dig"i*tate	a.
Dig`i*ta"tion	n.
Dig"i*ti*form	a.
Dig"i*ti*grade	a.
Dig"i*ti*grade	n.
Dig`i*ti*par"tite	a.
dig"i*tize	v. t.
Dig`i*to"ri*um	n.
dig`i*tox"in	n.
Dig"i*tule	n.
Di*gla"di*ate	v. i.
Di*gla`di*a"tion	n.
Di*glot"tism	n.
Di"glyph	n.
Dig*na"tion	n.
Digne	a.
Dig`ni*fi*ca"tion	n.
Dig"ni*fied	a.
dig"ni*fy	v. t.
dignifying	adj.
dig"ni*ta*ry	n.
Dig"ni*ty	n.
Dig*no"tion	n.
Dig"o*nous	a.
di*gox"in	n.
Di"gram	n.
Di"graph	n.
Di*graph"ic	a.
Di*gress"	v. i.
Di*gress"	n.
Di*gres"sion	n.
Di*gres"sion*al	a.
Di*gress"ive	a.
Di*gress"ive*ly	adv.
digs	n.
Digue	n.
Di*gyn"i*a	n.
Di*gyn"i*an	a.
Di*he"dral	a.
Di*he"dron	n.
Di`hex*ag"o*nal	a.
Di`i*amb"	n.
Di`i*am"bus	n.
Di*i"o*dide	n.
di*i`o*do*tyr"o*sine	n.
Di`i*sat"o*gen	n.
Di*ju"di*cant	n.
Di*ju"di*cate	v. i.
Di*ju`di*ca"tion	n.
Di"ka	n.
Dike	n.
Dike	v. t.
Dike	v. i.
Dik"er	n.
Di*lac"er*ate	v. t.
Di*lac`er*a"tion	n.
Di*la"ni*ate	v. t.
Di*la`ni*a"tion	n.
Di*lap"i*date	v. t.
Di*lap"i*date	v. i.
Di*lap"i*da`ted	a.
Di*lap`i*da"tion	n.
Di*lap"i*da`tor	n.
Di*la`ta*bil"i*ty	n.
Di*lat"a*ble	a.
Dil`a*ta"tion	n.
Dil`a*ta"tor	n.
Di*late"	v. t.
Di*late"	v. i.
Di*late"	a.
Di*lat"ed	a.
Di*lat"ed*ly	adv.
Di*lat"er	n.
Di*la"tion	n.
Di*la"tion	n.
Di*lat"ive	a.
Dil`a*tom"e*ter	n.
Di*lat"or	n.
Dil"a*to*ri*ly	adv.
Dil"a*to*ri*ness	n.
Dil"a*to*ry	a.
dil"do	n.
Dil"do	n.
dil"do	n.
Di*lec"tion	n.
Di*lem"ma	n.
Dil"et*tant`	a.
Dil`et*tant"	n.
Dil`et*tan"te	n.
Dil`et*tan"te*ish	a.
Dil`et*tan"te*ism	n.
Dil`et*tant"ish	a.
Dil`et*tant"ism	n.
Dil"i*gence	n.
Di`li*gence"	n.
Dil"i*gen*cy	n.
Dil"i*gent	a.
Dil"i*gent*ly	adv.
Dill	n.
Dill	v. t.
dillenia	n.
Dilleniaceae	n.
Dilleniidae	n.
Dil"ling	n.
Dil*lu"ing	n.
dil"ly	n.
dil"ly	n.
dil"ly-dal`ly	v. i.
Di*log"ic*al	a.
Dil"o*gy	n.
Di*lu"cid	a.
Di*lu"ci*date	v. t.
Di*lu`ci*da"tion	n.
Dil"u*ent	a.
Dil"u*ent	n.
Di*lute"	v. t.
Di*lute"	v. i.
Di*lute"	a.
Di*lut"ed	a.
Di*lute"ness	n.
Di*lut"er	n.
Di*lu"tion	n.
Di*lu"vi*al	a.
Di*lu"vi*al*ist	n.
Di*lu"vi*an	a.
Di*lu"vi*ate	v. i.
Di*lu"vi*um	n.
Dim	a.
Dim	v. t.
Dim	v. i.
Dim"ble	n.
Dime	n.
Di*men"sion	n.
Di*men"sion*al	a.
Di*men"sioned	a.
Di*men"sion*less	a.
Di*men"si*ty	n.
Di*men"sive	a.
Dim"e*ra	n. pl.
Dim"er*an	n.
Dim"er*ous	a.
Dim"e*ter	a.
Di*meth"yl	n.
Di*met"ric	a.
Dim`i*ca"tion	n.
Di*mid"i*ate	a.
Di*mid"i*ate	v. t.
Di*mid`i*a"tion	n.
Di*min"ish	v. t.
Di*min"ish	v. i.
Di*min"ish*a*ble	a.
Di*min"ish*er	n.
Di*min"ish*ing*ly	adv.
Di*min"ish*ment	n.
Di*min`u*en"do	adv.
Di*min"u*ent	a.
Dim`i*nu"tal	a.
Dim"i*nute	a.
Dim"i*nute*ly	adv.
Dim`i*nu"tion	n.
Di*min`u*ti"val	a.
Di*min"u*tive	a.
Di*min"u*tive	n.
Di*min"u*tive*ly	adv.
Di*min"u*tive*ness	n.
Dim"ish	a.
Di*mis"sion	n.
Dim"is*so*ry	a.
Di*mit"	v. t.
Dim"i*ty	n.
Dim"ly	adv.
Dim"mish	a.
Dim"ness	n.
Di"morph`	n.
Di*mor"phic	a.
Di*mor"phism	n.
Di*mor"phous	a.
Dim"ple	n.
Dim"ple	v. i.
Dim"ple	v. t.
Dim"ple*ment	n.
Dim"ply	a.
Dim"-sight`ed	a.
dim-witted	adj.
Dim"y*a	n. pl.
Dim`y*a"ri*an	a.
Dim"y*a*ry	a. & n.
Din	n.
Din	v. t.
Din	v. i.
Di*naph"thyl	n.
Di"nar	n.
Di"nar*chy	n.
Dine	v. i.
Dine	v. t.
Din"er	n.
Din"er-out`	n.
Di*net"ic*al	a.
Ding	v. t.
Ding	v. i.
Ding	n.
ding"-a-ling	n.
Ding"dong` the"o*ry	n.
Din"gi*ly	adv.
Din"gi*ness	n.
Din"gle	n.
Din"gle-dan`gle	adv.
Din"go	n.
Ding"thrift`	n.
Din"gy	a.
Di*nich"thys	n.
Din"ing	n. & a.
dininghall	n.
diningroom	n.
Dink	a.
dink	v. t.
dink	n.
dink	n.
dink	n.
Dinka	prop. n.
dinky	adj.
Din"mont	n.
din"ner	n.
Din"ner*less	a.
Din"ner*ly	a.
dinnertime	n.
Di*noc"e*ras	n.
Dinocerata	n.
Dinoflagellata	n.
dinoflagellate	n.
Di*nor"nis	n.
Di"no*saur	n.
Di`no*sau"ri*a	n. pl.
Di"no*there	n.
Din*ox"ide	n.
Din"some	a.
Dint	n.
Dint	v. t.
Di*nu`mer*a"tion	n.
Di*oc"e*san	a.
Di*oc"e*san	n.
Di"o*cese	n.
Di`o*ce"se*ner	n.
Di"o*don	n.
Di"o*dont	a.
Di*<oe/"ci*a	n. pl.
Di*<oe/"cian	a.
Di*<oe/"cious*ly	adv.
Di*<oe/"cious*ness	n.
Di*<oe/"cism	n.
dioestrous	adj.
Di*og"e*nes	n.
Di*oi"cous	a.
Di*om`e*de"a	n.
Di`o*n<ae/"a	n.
Di`o*ny"si*a	n. pl.
Di`o*ny"si*ac	a.
Di`o*ny"sian	a.
Di`o*phan"tine	a.
Di*op"side	n.
Di*op"tase	n.
Di*op"ter	n.
Di*op"tre	n.
Di*op"tric	a.
Di*op"tric	a.
Di*op"trics	n.
Di*op"try	n.
Di`o*ra"ma	n.
Di`o*ram"ic	a.
Di"o*rism	n.
Di`o*ris"tic	a.
Di"o*rite	n.
Di`o*rit"ic	a.
Di`or*thot"ic	a.
Di`os*co"re*a	n.
Dioscoreaceae	n.
Di*o"ta	n.
Di*ox"ide	n.
Di`ox*in"dol	n.
Dip	v. t.
Dip	v. i.
Dip	n.
Di*pas"chal	a.
Dip"chick`	n.
Di*pet"al*ous	a.
Di*phe"nyl	n.
Diph*the"ri*a	n.
Diph*the"ri*al	a.
Diph`the*rit"ic	a.
Diph"thong	n.
Diph"thong	v. t.
Diph*thon"gal	a.
Diph*thon"gal*ize	v. t.
Diph`thon*ga"tion	n.
Diph*thong"ic	a.
Diph`thong*i*za"tion	n.
Diph"thong*ize	v. t. & i.
Diph`y*cer"cal	a.
Diph`y*gen"ic	a.
Diph"yl*lous	a.
Diph"y*o*dont	a.
Diph`y*o*zo"oid	n.
Di*pla"nar	a.
Di*plei"do*scope	n.
Di"plex	a.
Dip`lo*blas"tic	a.
Dip`lo*car"di*ac	a.
Dip`lo*coc"cus	n.
Dip"lo*<eum/	n.
Dip`lo*et"ic	a.
Dip`lo*gen"ic	a.
Dip"lo*graph	n.
Di*plo"ic	a.
dip"loid	n.
dip"loid	a.
Di*plo"ma	n.
Di*plo"ma*cy	n.
Dip"lo*mat	n.
Dip"lo*mate	v. t.
Dip`lo*ma"tial	a.
Dip`lo*mat"ic	a.
Dip`lo*mat"ic	n.
Dip`lo*mat"ic*al*ly	adv.
Dip`lo*mat"ics	n.
Di*plo"ma*tism	n.
Di*plo"ma*tist	n.
Di*plo"pi*a	n.
Dip"lo*pod	n.
Di*plop"o*da	n. pl.
Dip`lo*stem"o*nous	a.
Dip`lo*stem"o*ny	n.
diplotene	n.
Dip*neu"mo*na	n. pl.
Dip"no*i	n. pl.
Dipodomys	n.
Dipogon	n.
Dip"o*dy	n.
Di*po"lar	a.
dipped	adj.
Dip"pel's oil`	n.
Dip"ping	n.
Di`pris*mat"ic	a.
Di`pro*par"gyl	n.
Di*pro"pyl	n.
Di*pro"to*don	n.
Dip"sas	n.
Dip*set"ic	a.
Dip"sey	a.
Dip"sey	n.
Dip`so*ma"ni*a	n.
Dip`so*ma"ni*ac	n.
Dip`so*ma*ni"a*cal	a.
Dip*so"sis	n.
dipstick	n.
Dip"te*ra	n. pl.
Dip"ter*al	a.
Dip"ter*an	n.
Dip`te*ro*car"pus	n.
Dip"ter*ous	a.
Dip`ter*yg"i*an	a.
Dipteryx	n.
Dip"tote	n.
Dip"tych	n.
Di*pyre"	n.
Di`py*re"nous	a.
Di*pyr"i*dine	n.
Di*pyr"i*dyl	n.
Di*ra`di*a"tion	n.
Dire	a.
Di*rect"	a.
Di*rect"	v. t.
Di*rect"	v. i.
Di*rect"	n.
Di*rect"-act`ing	a.
Di*rect"-cou"pled	a.
Direct current	adj.
Di*rect"er	n.
Di*rec"tion	n.
directional	adj.
directionality	n.
directionless	adj.
Di*rect"ive	a.
directivity	n.
Di*rect"ly	adv.
Di*rect"ness	n.
Direct nomination	n.
Di*rect"o*rate	n.
Di*rec*to"ri*al	a.
Di*rect"or*ship	n.
Di*rect"o*ry	a.
Di*rect"o*ry	n.
Direct primary	n.
Di*rect"rix	n.
Dire"ful	a.
Dire"ly	adv.
Di*rempt"	a.
Di*rempt"	v. t.
Di*remp"tion	n.
Dire"ness	n.
Di*rep"tion	n.
Di*rep*ti"tious	a.
Di*rep*ti"tious*ly	adv.
Dirge	n.
Dirge"ful	a.
Dir"i*ge	n.
Dir"i*gent	a.
Dir"i*gent	n.
Dir"i*gi*ble	a.
dir`i*gisme"	n.
dir`i*giste"	a.
Dir"i*ment	a.
Dirk	n.
Dirk	v. t.
Dirk	a.
Dirk	v. t.
Dirk"ness	n.
Dirl	v. i. & t.
Dirt	n.
Dirt	v. t.
dirt-cheap	adj.
Dirt"i*ly	adv.
Dirt"i*ness	n.
Dirt"y	a.
Dirt"y	v. t.
dirtying	n.
Di*rup"tion	n.
dis-	prop. n.
dis	v. t.
disa	n.
dis`a*bil"i*ty	n.
Dis*a"ble	a.
Dis*a"ble	v. t.
disabled	adj.
Dis*a"ble*ment	n.
disabling	adj.
dis`a*buse"	v. t.
dis`ac*com"mo*date	v. t.
Dis`ac*com`mo*da"tion	n.
Dis`ac*cord"	v. i.
Dis`ac*cord"	n.
Dis`ac*cord"ant	a.
Dis`ac*cus"tom	v. t.
Dis`a*cid"i*fy	v. t.
Dis`ac*knowl"edge	v. t.
Dis`ac*quaint"	v. t.
Dis`ac*quaint"ance	n.
Dis*ac"ryl	n.
Dis`a*dorn"	v. t.
Dis`ad*vance"	v. t. & i.
Dis`ad*van"tage	n.
Dis`ad*van"tage	v. t.
Dis`ad*van"tage*a*ble	a.
Dis*ad`van*ta"geous	a.
Dis`ad*ven"ture	n.
Dis`ad*ven"tur*ous	a.
Dis`ad*vise"	v. t.
Dis`af*fect"	v. t.
Dis`af*fect"ed	a.
Dis`af*fec"tion	n.
Dis`af*fec"tion*ate	a.
Dis`af*firm"	v. t.
Dis`af*firm"ance	n.
Dis*af`fir*ma"tion	n.
Dis`af*for"est	v. t.
Dis*ag"gre*gate	v. t.
Dis*ag`gre*ga"tion	n.
Dis`a*gree"	v. i.
Dis`a*gree"a*ble	a.
Dis`a*gree"a*ble*ness	n.
Dis`a*gree"a*bly	adv.
Dis`a*gree"ance	n.
Dis`a*gree"ment	n.
Dis`a*gre"er	n.
Dis`al*liege"	v. t.
Dis`al*low"	v. t.
Dis`al*low"a*ble	a.
Dis`al*low"ance	n.
Dis`al*ly"	v. t.
Dis*an"chor	v. t. & i.
Dis`an*gel"ic*al	a.
Dis*an"i*mate	v. t.
Dis*an`i*ma"tion	n.
Dis`an*nex"	v. t.
Dis`an*nul"	v. t.
Dis`an*nul"ler	n.
Dis`an*nul"ment	n.
Dis`a*noint"	v. t.
Dis`ap*par"el	v. t.
Dis`ap*pear"	v. i.
Dis`ap*pear"ance	n.
Dis`ap*pear"ing	p. pr. & vb. n.
Dis`ap*pend"en*cy	n.
Dis`ap*pend"ent	a.
Dis`ap*point"	v. t.
Dis`ap*point"ed	a.
disappointing	a.
disappointing	n.
Dis`ap*point"ment	n.
Dis`ap*pre"ci*ate	v. t.
Dis*ap`pro*ba"tion	n.
Dis*ap"pro*ba`to*ry	a.
Dis`ap*pro"pri*ate	a.
Dis`ap*pro"pri*ate	v. t.
Dis`ap*pro`pri*a"tion	n.
Dis`ap*prov"al	n.
Dis`ap*prove	v. t.
Dis`ap*prov"er	n.
disapproving	adj.
Dis`ap*prov"ing*ly	adv.
Dis"ard	n.
Dis*arm"	v. t.
Dis*arm"a*ment	n.
Dis*ar"ma*ture	n.
Dis*armed"	a.
Dis*arm"er	n.
disarming	adj.
disarming	n.
Dis`ar*range"	v. t.
disarranged	adj.
Dis`ar*range"ment	n.
Dis`ar*ray"	v. t.
Dis`ar*ray"	n.
Dis`ar*ray"ment	n.
Dis`ar*tic"u*late	v. t.
Dis`ar*tic"u*la`tor	n.
dis`as*sem"ble	v. t.
dis`as*sem"ble	v. i.
dis`as*sem"bler	n.
Dis`as*sent"	v. i.
Dis`as*sent"	n.
Dis`as*sent"er	n.
Dis*as`si*du"i*ty	n.
Dis`as*sim"i*late	v. t.
Dis`as*sim`i*la"tion	n.
Dis`as*sim"i*la*tive	a.
Dis`as*so"ci*ate	v. t.
Dis*as"ter	n.
Dis*as"ter	v. t.
Dis*as"ter*ly	adv.
Dis*as"trous	a.
Dis`at*tire"	v. t.
Dis`aug*ment"	v. t.
Dis*au"thor*ize	v. t.
Dis`a*vaunce"	v. t.
Dis`a*ven"ture	n.
Dis`a*ven"tur*ous	a.
Dis`a*vouch"	v. t.
Dis`a*vow"	v. t.
disavowable	adj.
Dis`a*vow"al	n.
Dis`a*vow"ance	n.
Dis`a*vow"er	n.
Dis`a*vow"ment	n.
Dis*band"	v. t.
Dis*band"	v. i.
Dis*band"ment	n.
Dis*bar"	v. t.
Dis*bark"	v. t.
Dis*bark"	v. t.
Dis*bar"ment	n.
Dis*base"	v. t.
Dis`be*come"	v. t.
Dis*be*lief"	n.
Dis`be*lieve"	v. t.
Dis`be*liev"er	n.
Dis*bench"	v. t.
Dis*bend	v. t.
Dis*bind"	v. t.
Dis*blame"	v. t.
Dis*bod"ied	a.
Dis`bos*ca"tion	n.
Dis*bow"el	v. t.
Dis*branch"	v. t.
Dis*bud"	v. t.
Dis*bur"den	v. t.
Dis*bur"den	v. i.
Dis*bur"geon	v. t.
Dis*burse"	v. t.
Dis*burse"ment	n.
Dis*burs"er	n.
Dis*bur"then	v. t.
Disc	n.
Dis*cage"	v. t.
Disc"al	a.
Dis*cal"ce*ate	v. t.
Dis*cal"ce*at`ed	a.
Dis*cal`ce*a"tion	n.
Dis*calced"	a.
Dis*camp"	v. t.
Dis*can"dy	v. i.
Dis"cant	n.
Dis*ca*pac"i*tate	v. t.
Dis*card"	v. t.
Dis*card"	v. i.
Dis*card"	n.
Dis*car"dure	n.
Dis*car"nate	a.
Dis*case"	v. t.
Dis*cede"	v. i.
Dis*cept"	v. i.
Dis`cep*ta"tion	n.
Dis`cep*ta"tor	n.
Dis*cern"	v. t.
Dis*cern"	v. i.
Dis*cern"ance	n.
Dis*cern"er	n.
Dis*cern"i*ble	a.
Dis*cern"i*ble*ness	n.
Dis*cern"i*bly	adv.
Dis*cern"ing	a.
Dis*cern"ing*ly	adv.
Dis*cern"ment	n.
Dis*cerp"	v. t.
Dis*cerp`i*bil"i*ty	n.
Dis*cerp"i*ble	a.
Dis*cerp"tion	n.
Dis*cerp"tive	a.
Dis*ces"sion	n.
Dis*charge"	v. t.
Dis*charge"	v. i.
Dis*charge"	n.
Dis*char"ger	n.
Dis*chev"ele	a.
Dis*church"	v. t.
Dis*cide"	v. t.
Dis*cif"er*ous	a.
Dis`ci*flo"ral	a.
Dis"ci*form	a.
Dis*ci"na	n.
Dis*cinct	a.
Dis*cind"	v. t.
Dis*ci"ple	n.
Dis*ci"ple	v. t.
Dis*ci"ple*ship	n.
Dis*ci"pless	n.
Dis"ci*plin*a*ble	a.
Dis"ci*plin*a*ble*ness	n.
Dis"ci*plin*al	a.
Dis"ci*plin*ant	n.
Dis`ci*plin*a"ri*an	a.
Dis`ci*plin*a"ri*an	n.
Dis"ci*plin*a*ry	a.
Dis`ci*pline	n.
Dis"ci*pline	v. t.
Dis"ci*plin*er	n.
disc" jock`ey	n.
Dis*claim"	v. t.
Dis*claim"	v. t.
Dis*claim"er	n.
Dis`cla*ma"tion	n.
Dis*clame"	v. t.
Dis*claun"der	v. t.
Dis*cloak"	v. t.
Dis*close"	v. t.
Dis*close"	n.
Dis*closed"	p. a.
Dis*clos"er	n.
Dis*clo"sure	n.
Dis*cloud"	v. t.
Dis*clout"	v. t.
Dis*clu"sion	n.
Dis*coast"	v. i.
Dis`co*blas"tic	a.
Dis*cob"o*lus	n.
Dis`co*dac"tyl	n.
Dis`co*dac*tyl"i*a	n. pl.
Dis`co*dac"tyl*ous	a.
Dis`co*her"ent	a.
Dis"coid	a.
Dis"coid	n.
Dis*coid"al	a.
Dis"co*lith	n.
Dis*col"or	v. t.
Dis*col"or*ate	v. t.
Dis*col`or*a"tion	n.
dis*col"ored	a.
discolour	v.
discoloured	adj.
discombobulate	v.
discombobulated	adj.
Dis*com"fit	v. t.
Dis*com"fit	a.
Dis*com"fit	n.
discomfited	adj.
discomfited	n. pl.
Dis*com"fi*ture	n.
Dis*com"fort	v. t.
Dis*com"fort	n.
Dis*com"fort*a*ble	a.
Dis`com*mend"	v. t.
Dis`com*mend"a*ble	a.
Dis*com`men*da"tion	n.
Dis`com*mend"er	n.
Dis`com*mis"sion	v. t.
Dis*com"mo*date	v. t.
Dis`com*mode"	v. t.
Dis`com*mo"di*ous	a.
Dis`com*mod"i*ty	n.
Dis*com"mon	v. t.
Dis`com*mu"ni*ty	n.
Dis*com"pa*ny	v. t.
Dis`com*plex"ion	v. t.
Dis`com*pli"ance	n.
Dis`com*pose"	v. t.
Dis`com*posed"	a.
Dis*com`po*si"tion	n.
Dis`com*po"sure	n.
Dis*compt"	v. t.
Dis`con*cert"	v. t.
Dis`con*cert"	n.
disconcerting	adj.
Dis`con*cer"tion	n.
Dis`con*du"cive	a.
Dis`con*form"a*ble	a.
Dis`con*form"i*ty	n.
Dis`con*gru"i*ty	n.
Dis`con*nect"	v. t.
disconnected	adj.
disconnectedness	n.
Dis`con*nec"tion	n.
Dis*con"se*crate	v. t.
Dis`con*sent"	v. i.
Dis*con"so*la`cy	n.
Dis*con"so*late	n.
Dis*con"so*late	a.
Dis*con"so*la`ted	a.
Dis*con`so*la"tion	n.
Dis`con*tent"	a.
Dis`con*tent"	v. t.
Dis`con*tent"	n.
Dis*con`ten*ta"tion	n.
Dis`con*tent"ed	p. p. & a.
Dis`con*tent"ful	a.
Dis`con*tent"ing	a.
Dis`con*tent"ive	a.
Dis`con*tent"ment	n.
Dis`con*tin"u*a*ble	a.
Dis`con*tin"u*ance	n.
Dis`con*tin`u*a"tion	n.
Dis`con*tin"ue	v. t.
Dis`con*tin"ue	v. i.
Dis`con*tin`u*ee"	n.
Dis`con*tin"u*er	n.
Dis*con`ti*nu"i*ty	n.
Dis`con*tin"u*or	n.
Dis`con*tin"u*ous	a.
Dis`con*ven"ience	n.
Dis`con*ven"ient	a.
Dis*coph"o*ra	n. pl.
Dis"cord`	n.
Dis*cord"	v. i.
Dis*cord"a*ble	a.
Dis*cord"ance	n.
Dis*cord"ant	a.
Dis*cord"ful	a.
Dis*cord"ous	a.
Dis*cor"po*rate	a.
Dis*cor`re*spond"ent	a.
Dis*cost"	v. i.
Dis*coun"sel	v. t.
Dis"count`	v. t.
Dis"count`	v. i.
Dis"count`	n.
Dis*count"a*ble	a.
Dis*coun"te*nance	v. t.
Dis*coun"te*nance	n.
Dis*coun"te*nan*cer	n.
Dis"count`er	n.
Dis*cour"age	v. t.
Dis*cour"age	n.
Dis*cour"age*a*ble	a.
Dis*cour"age*ment	n.
Dis*cour"a*ger	n.
Dis*cour"a*ging	a.
Dis*coure"	v. t.
Dis*course"	n.
Dis*course"	v. i.
Dis*course"	v. t.
Dis*cours"er	n.
Dis*cours"ive	a.
Dis*cours"ive	n.
Dis*cour"te*ous	a.
Dis*cour"te*sy	n.
Dis*court"ship	n.
Disc"ous	a.
Dis*cov"e*nant	v. t.
Dis*cov"er	v. t.
Dis*cov"er	v. i.
Dis*cov`er*a*bil"i*ty	n.
Dis*cov"er*a*ble	a.
Dis*cov"er*er	n.
Dis*cov"er*ment	n.
Dis*cov"ert	a.
Dis*cov"ert	n.
Dis*cov"er*ture	n.
Dis*cov"er*y	n.
Dis*cov"er*y Day	v. t.
Dis*cred"it	n.
Dis*cred"it	v. t.
dis*cred"it*a*ble	a.
discredited	adj.
dis*cred"it*or	n.
Dis*creet"	a.
Dis*crep"ance	n.
Dis*crep"ant	a.
Dis*crep"ant	n.
Dis*crete"	a.
Dis*crete"	v. t.
Dis*crete"ly	adv.
Dis*cre"tion	n.
Dis*cre"tion*al	adv.
Dis*cre"tive	a.
Dis*cre"tive*ly	adv.
Dis*crim"i*na*ble	a.
Dis*crim"i*nal	a.
Dis*crim"i*nant	n.
Dis*crim"i*nate	a.
Dis*crim"i*nate	v. t.
Dis*crim"i*nate	v. i.
Dis*crim"i*nate*ly	adv.
Dis*crim"i*nate*ness	n.
Dis*crim"i*na`ting	a.
Dis*crim`i*na"tion	n.
Dis*crim"i*na*tive	a.
Dis*crim"i*na*tive*ly	adv.
Dis*crim"i*na`tor	n.
Dis*crim"i*na*to*ry	a.
Dis*crim"i*nous	a.
Dis*crive"	v. t.
Dis*crown"	v. t.
Dis*cru"ci*ate	v. t.
Dis*cu"bi*to*ry	a.
Dis*cul"pate	v. t.
Dis`cul*pa"tion	n.
Dis*cul"pa*to*ry	a.
Dis*cum"ben*cy	n.
Dis*cum"ber	v. t.
Dis*cure"	v. t.
Dis*cur"rent	a.
Dis*cur"sion	n.
Dis*cur"sist	n.
Dis*cur"sive	a.
Dis*cur`so*ry	a.
Dis*cur"sus	n.
Dis"cus	n.
Dis*cuss"	v. t.
discussant	n.
Dis*cuss"er	n.
Dis*cus"sion	n.
Dis*cus"sion*al	a.
dis*cuss"ive	a.
Dis*cuss"ive	n.
Dis*cu"tient	a.
Dis*dain"	n.
Dis*dain"	v. t.
Dis*dain"	v. i.
Dis*dained"	a.
Dis*dain"ful	a.
Dis*dain"ish*ly	adv.
Dis*dain"ous	a.
Dis*dain"ous*ly	adv.
Dis*de"i*fy	v. t.
Dis*deign"	v. t.
Dis*di"a*clast	n.
Dis*di`a*pa"son	n.
Dis*ease"	n.
Dis*ease"	v. t.
Dis*eased"	a.
Dis*eas"ed*ness	n.
Dis*ease"ful	a.
Dis*ease"ful*ness	n.
Dis*ease"ment	n.
Dis*edge"	v. t.
Dis*ed"i*fy	v. t.
Dis*eld"er	v. t.
Di*sel"e*nide	n.
Dis`em*bark"	v. t.
Dis`em*bark"	v. i.
Dis*em`bar*ka"tion	n.
Dis`em*bark"ment	n.
Dis`em*bar"rass	v. t.
Dis`em*bar"rass*ment	n.
Dis`em*bay"	v. t.
Dis`em*bel"lish	v. t.
Dis`em*bit"ter	v. t.
Dis`em*bod"ied	a.
Dis`em*bod"i*ment	n.
Dis`em*bod"y	v. t.
Dis`em*bogue"	v. t.
Dis`em*bogue"	v. i.
Dis`em*bogue"ment	n.
Dis`em*bos"som	v. t.
Dis`em*bow"el	v. t.
Dis`em*bow"el*ment	n.
Dis`em*bow"ered	a.
Dis`em*bran"gle	v. t.
Dis`em*broil"	v. t.
Dis`em*ploy"	v. t.
Dis`em*ploy"ment	n.
Dis`em*pow"er	v. t.
Dis`en*a"ble	v. t.
Dis`en*am"or	v. t.
Dis`en*chained"	a.
Dis`en*chant"	v. t.
Dis`en*chant"er	n.
disenchanting	adj.
Dis`en*chant"ment	n.
Dis`en*charm"	v. t.
Dis`en*close	v. t.
Dis`en*cour"age*ment	n.
Dis`en*crese"	v. i.
Dis`en*crese"	n.
Dis`en*cum"ber	v. t.
Dis`en*cum"brance	n.
Dis`en*dow"	v. t.
Dis`en*dow"ment	n.
Dis`en*fran"chise	v. t.
disenfranchised	adj.
Dis`en*gage"	v. t.
Dis`en*gage"	v. i.
Dis`en*gaged"	a.
Dis`en*gage"ment	n.
Dis`en*ga"ging	a.
Dis`en*no"ble	v. t.
Dis`en*roll"	v. i.
Dis`en*san"i*ty	n.
Dis`en*shroud"ed	a.
Dis`en*slave"	v. t.
Dis`en*tail"	v. t.
dis`en*tan"gle	v. t.
disentangled	adj.
Dis`en*tan"gle*ment	n.
Dis`en*ter"	v. t.
Dis`en*thrall"	v. t.
Dis`en*thrall"ment	n.
Dis`en*throne"	v. t.
Dis`en*ti"tle	v. t.
Dis`en*tomb"	v. t.
Dis`en*trail"	v. t.
Dis`en*trance"	v. t.
Dis`en*twine"	v. t.
Di*sep"al*ous	a.
Dis*ert"	a.
Dis*er"ti*tude	n.
Dis*ert"y	adv.
Dis`es*pouse"	v. t.
Dis`es*tab"lish	v. t.
Dis`es*tab"lish*ment	n.
dis`es*tab`lish*men*ta"ri*an*ism	n.
Dis`es*teem"	n.
Dis`es*teem"	v. t.
Dis`es*teem"er	n.
Dis*es`ti*ma"tion	n.
Dis*ex"er*cise	v. t.
Dis*fame"	n.
Dis*fan"cy	v. t.
Dis*fash"ion	v. t.
Dis*fa"vor	n.
Dis*fa"vor	v. t.
Dis*fa"vor*a*ble	a.
Dis*fa"vor*a*bly	adv.
Dis*fa"vor*er	n.
Dis*fea"ture	v. t.
Dis*fel"low*ship	v. t.
Dis*fig`u*ra"tion	n.
Dis*fig"ure	v. t.
Dis*fig"ure	n.
disfigured	adj.
Dis*fig"ure*ment	n.
Dis*fig"ur*er	n.
Dis*flesh"	v. t.
Dis*for"est	v. t.
Dis*for`es*ta"tion	n.
Dis*form"i*ty	n.
Dis*fran"chise	v. t.
disfranchised	adj.
Dis*fran"chise*ment	n.
Dis*fri"ar	v. t.
Dis*frock"	v. t.
Dis*fur"nish	v. t.
Dis*fur"nish*ment	n.
Dis*fur"ni*ture	n.
Dis*fur"ni*ture	v. t.
Dis*gage"	v. t.
Dis*gal"lant	v. t.
Dis*gar"land	v. t.
Dis*gar"nish	v. t.
Dis*gar"ri*son	v. t.
Dis*gav"el	v. t.
Dis*gest"	v. t.
Dis*ges"tion	n.
Dis*glo"ri*fy	v. t.
Dis*glo"ry	n.
Dis*gorge"	v. t.
Dis*gorge"	v. i.
Dis*gorge"ment	n.
Dis*gos"pel	v. i.
Dis*grace"	n.
Dis*grace"	v. t.
disgraced	adj.
Dis*grace"ful	a.
Dis*gra"cer	n.
Dis*gra"cious	a.
Dis*gra"cive	a.
Dis`gra*da"tion	n.
Dis*grade"	v. t.
Dis*grad"u*ate	v. t.
Dis"gre*gate	v. t.
Dis`gre*ga"tion	n.
Dis*grun"tle	v. t.
Dis*guise"	v. t.
Dis*guise"	n.
Dis*guis"ed*ly	adv.
Dis*guis"ed*ness	n.
Dis*guise"ment	n.
Dis*guis"er	n.
Dis*guis"ing	n.
Dis*gust"	v. t.
Dis*gust"	n.
disgusted	adj.
Dis*gust"ful	a.
Dis*gust"ful*ness	n.
Dis*gust"ing	a.
Dish	n.
Dish	v. t.
Dis`ha*bil"i*tate	v. t.
Dis`ha*bille"	n.
Dis*hab"it	v. t.
Dis*hab"it*ed	p. a.
Dis`ha*bit"u*ate	v. t.
Dis*ha"ble	v. t.
Dis*hal"low	v. t.
Dis`har*mo"ni*ous	a.
Dis*har"mo*ny	n.
Dis*haunt"	v. t.
Dish"cloth`	n.
Dish"clout`	n.
Dis*heart"	v. t.
Dis*heart"en	v. t.
dis*heart"ened	adj.
disheartening	adj.
dis*heart"en*ment	n.
dis*heir"	v. t.
dis*helm"	v. t.
dis*her"i*son	n.
dis*her"it	v. t.
Dis*her"it*ance	n.
Dis*her"it*or	n.
Di*shev"el	v. t.
Di*shev"el	v. i.
Di*shev"ele	p. p. & a.
di*shev"eled	a.
Dish"ful	n.
Dish"ing	a.
Dis*hon"est	a.
Dis*hon"est	v. t.
Dis*hon"est*ly	adv.
Dis*hon"es*ty	n.
dishpan	n.
Dis*hon"or	n.
Dis*hon"or	v. t.
Dis*hon"or*a*ble	a.
Dis*hon"or*a*ry	a.
Dis*hon"or*er	n.
Dis*horn"	v. t.
Dis*horse"	v. t.
Dis*house"	v. t.
dishpan	n.
dishrag	n.
Dis*hu"mor	n.
Dis*hu"mor	v. t.
dishware	n.
Dish"wash`er	n.
Dish"wa`ter	n.
dishy	adj.
Dis`il*lu"sion	n.
Dis`il*lu"sion	v. t.
disillusioning	adj.
Dis`il*lu"sion*ize	v. t.
Dis`il*lu"sion*ment	n.
Dis`im*bit"ter	v. t.
Dis`im*park"	v. t.
Dis`im*pas"sioned	a.
Dis`im*prove"	v. t.
Dis`im*prove"	v. i.
Dis`im*prove"ment	n.
Dis`in*car"cer*ate	v. t.
Dis*in`cli*na"tion	n.
Dis`in*cline"	v. t.
Dis`in*close"	v. t.
Dis`in*cor"po*rate	v. t.
Dis`in*cor"po*rate	a.
Dis`in*cor`po*ra"tion	n.
Dis`in*fect"	v. t.
dis`in*fect"ant	n.
dis`in*fec"tion	n.
dis`in*fect"or	n.
Dis`in*flame"	v. t.
disinflation	n.
Dis*in`ge*nu"i*ty	n.
Dis`in*gen"u*ous	a.
Dis`in*hab"it*ed	a.
Dis`in*her"i*son	n.
Dis`in*her"it	v. t.
Dis`in*her"it*ance	n.
Dis`in*hume"	v. t.
Dis`in*sure"	v. t.
Dis*in"te*gra*ble	a.
Dis*in"te*grate	v. t.
Dis*in"te*grate	v. i.
Dis*in`te*gra"tion	n.
Dis*in"te*gra`tor	n.
Dis`in*ter"	v. t.
Dis*in"ter*ess	v. t.
Dis*in"ter*ess*ment	n.
Dis*in"ter*est	p. a.
Dis*in"ter*est	n.
Dis*in"ter*est	v. t.
Dis*in"ter*est*ed	a.
Dis*in"ter*est*ed*ly	adv.
Dis*in"ter*est*ed*ness	n.
Dis*in"ter*est*ing	a.
Dis`in*ter"ment	n.
Dis`in*thrall"	v. t.
Dis`in*thrall"ment	n.
Dis*in"tri*cate	v. t.
Dis`in*ure"	v. t.
Dis`in*ves"ti*ture	n.
Dis`in*vig"or*ate	v. t.
Dis`in*volve"	v. t.
Dis*jec"tion	n.
disk jockey	n.
diskjockey	v. i.
Dis*join"	v. t.
Dis*join"	v. i.
disjoined	adj.
Dis*joint"	a.
Dis*joint"	n.
Dis*joint"	v. t.
Dis*joint"	v. i.
Dis*joint"ed	a.
Dis*joint"ly	adv.
Dis*ju`di*ca"tion	n.
Dis*junct"	a.
Dis*junc"tion	n.
Dis*junc"tive	a.
Dis*junc"tive	n.
Dis*junc"tive*ly	adv.
Dis*junc"ture	n.
Disk	n.
Disk clutch	n.
dis*kind"ness	n.
Disk"less	a.
disklike	adj.
Dis*lade"	v. t.
Dis*leal"	a.
Dis*leave"	v. t.
Dis*like"	v. t.
dis*like"	n.
dis*like"ful	a.
dis*like"li*hood	n.
Dis*lik"en	v. t.
Dis*like"ness	n.
Dis*lik"er	n.
Dis*limb"	v. t.
Dis*limn"	v. t.
Dis*link"	v. t.
Dis*live"	v. t.
Dis"lo*cate	v. t.
Dis"lo*cate	a.
dislocated	adj.
Dis`lo*ca"tion	n.
Dis*lodge"	v. t.
Dis*lodge"	v. i.
Dis*lodge"	n.
dislodgement	n.
Dis*lodg"ment	n.
Dis*loign"	v. t.
Dis*loy"al	a.
Dis*loy"al*ly	adv.
Dis*loy"al*ty	n.
Dis*mail"	v. t.
Dis"mal	a.
Dis"mal*ly	adv.
Dis"mal*ness	n.
Dis*man"	v. t.
Dis*man"tle	v. t.
Dis*march"	v. i.
Dis*mar"ry	v. t.
Dis*mar"shal	v. t.
Dis*mask"	v. t.
Dis*mast"	v. t.
Dis*mast"ment	n.
Dis*maw"	v. t.
Dis*may"	v. t.
Dis*may"	v. i.
Dis*may"	n.
Dis*may"ed*ness	n.
Dis*may"ful	a.
Disme	n.
Dis*mem"ber	v. t.
Dis*mem"ber*ment	n.
Dis*met"tled	a.
Dis*miss"	v. t.
Dis*miss"	n.
Dis*miss"al	n.
dismissible	adj.
Dis*mis"sion	n.
Dis*miss"ive	a.
Dis*mort"gage	v. t.
Dis*mount"	v. i.
Dis*mount"	v. t.
Dis*nat"u*ral*ize	v. t.
Dis*na"tured	a.
Dis`o*be"di*ence	n.
Dis`o*be"di*en*cy	n.
Dis`o*be"di*ent	a.
Dis`o*be"di*ent*ly	adv.
Dis`o*bei"sance	n.
Dis`o*bei"sant	a.
Dis`o*bey"	v. t.
Dis`o*bey"	v. i.
Dis`o*bey"er	n.
Dis*ob`li*ga"tion	n.
Dis*ob"li*ga*to*ry	a.
Dis`o*blige"	v. t.
Dis`o*blige"ment	n.
Dis`o*bli"ger	n.
Dis`o*bli"ging	a.
Dis*oc"ci*dent	v. t.
Dis*oc`cu*pa"tion	n.
Dis`o*pin"ion	n.
Dis*op"pi*late	v. t.
Dis*orb"	v. t.
Dis*ord"	n.
Dis`or*deined"	a.
Dis*or"der	n.
Dis*or"der	v. t.
Dis*or"dered	a.
Dis*or"der*li*ness	n.
Dis*or"der*ly	a.
Dis*or"der*ly	adv.
Dis*or"di*nance	n.
Dis*or"di*nate	a.
Dis*or"di*nate*ly	adv.
Dis*or`di*na"tion	n.
Dis*or`gan*i*za"tion	n.
Dis*or"gan*ize	v. t.
Dis*or"gan*i`zer	n.
Dis*o"ri*ent	v. t.
Dis*o"ri*en*tate	v. t.
disoriented	adj.
disorienting	adj.
Dis*own"	v. t.
disowned	adj.
disowning	n.
Dis*own"ment	n.
Dis*ox"i*date	v. t.
Dis*ox`i*da"tion	n.
Dis*ox"y*gen*ate	v. t.
Dis*ox`y*gen*a"tion	n.
Dis*pace"	v. i.
Dis*pair"	v. t.
Dis*pand"	v. t.
Dis*pan"sion	n.
Dis*par"a*dised	a.
Dis*par"age	v. t.
Dis"pa*rage`	n.
Dis*par"age*ment	n.
dis*par"a*ger	n.
disparaging	adj.
dis*par"a*ging*ly	adv.
Dis"pa*rate	a.
Dis"pa*rates	n. pl.
Dis`pa*ri"tion	n.
Dis*par"i*ty	n.
Dis*park"	v. t.
Dis*par"kle	v. t.
Dis*part"	v. t.
Dis*part"	v. i.
Dis*part"	n.
Dis*part"	v. t.
Dis*pas"sion	n.
Dis*pas"sion*ate	a.
Dis*pas"sioned	a.
Dis*patch"	v. t.
Dis*patch"	v. i.
Dis*patch"	n.
Dis*patch"er	n.
Dis*patch"ful	a.
Dis*patch"ment	n.
Dis"pa*thy	n.
Dis*pau"per	v. t.
Dis*pau"per*ize	v. t.
Dis*peed"	v. t.
Dis*pel"	v. t.
Dis*pence"	v. i. & n.
Dis*pend"	v. t.
Dis*pend"er	n.
Dis*pen"sa*ble	a.
Dis*pen"sa*ble*ness	n.
Dis*pen"sa*ry	n.
Dis`pen*sa"tion	n.
Dis*pen"sa*tive	a.
Dis*pen"sa*tive*ly	adv.
Dis"pen*sa`tor	n.
Dis*pen"sa*to*ri*ly	adv.
Dis*pen"sa*to*ry	a.
Dis*pen"sa*to*ry	n.
Dis*pense"	v. t.
Dis*pense"	v. i.
Dis*pense"	n.
Dis*pense"	n.
dispensed	adj.
Dis*pens"er	n.
Dis*peo"ple	v. t.
Dis*peo"pler	n.
Dis*perge"	v. t.
Di*sper"mous	a.
Dis*per"ple	v. t.
Dis*per"sal	n.
Dis*perse"	v. t.
Dis*perse"	v. i.
Dis*persed"	a.
Dis*perse"ness	n.
Dis*pers"er	n.
Dis*per"sion	n.
Dis*pers"ive	a.
Dis*per"son'*ate	v. t.
Dis*pir"it	v. t.
dis*pir"it*ed	a.
dispiriting	adj.
Dis*pir"it*ment	n.
Dis*pit"e*ous	a.
Dis*place"	v. t.
Dis*place"a*ble	a.
Dis*place"ment	n.
Dis*pla"cen*cy	n.
Dis*pla"cer	n.
Dis*plant"	v. t.
Dis`plan*ta"tion	n.
Dis*plat"	v. t.
Dis*play"	v. t.
Dis*play"	v. i.
Dis*play"	n.
Dis*played"	a.
Dis*play"er	n.
Dis"ple	v. t.
Dis*pleas"ance	n.
Dis*pleas"ant	a.
Dis*please"	v. t.
Dis*please"	v. i.
Dis*pleas"ed*ly	adv.
Dis*pleas"ed*ness	n.
Dis*pleas"er	n.
Dis*pleas"ing	a.
Dis*pleas"ure	n.
Dis*pleas"ure	v. t.
Dis*plen"ish	v. t.
Dis"pli*cence	n.
Dis*plode"	v. t.
Dis*plode"	v. i.
Dis*plo"sion	n.
Dis*plo"sive	a.
Dis*plume"	v. t.
Dis"po*line	n.
Dis*pond"	n.
Di*spon"dee	n.
Dis*pone"	v. t.
Dis`po*nee"	n.
Dis*pon"er	n.
Dis*ponge"	v. t.
Dis*pope"	v. t.
Di*spor"ous	a.
Dis*port"	n.
Dis*port"	v. i.
Dis*port"	v. t.
Dis*port"ment	n.
Dis*pos"a*ble	a.
dis*pos"a*ble in"come	n.
Dis*pos"al	n.
Dis*pose"	v. t.
Dis*pose"	v. i.
Dis*pose"	n.
Dis*posed"	p. a.
Dis*pos"ed*ness	n.
Dis*pose"ment	n.
Dis*pos"er	n.
Dis*pos"ing*ly	adv.
Dis*pos"it*ed	a.
Dis`po*si"tion	n.
Dis`po*si"tion*al	a.
Dis`po*si"tioned	a.
Dis*pos"i*tive	a.
Dis*pos"i*tive*ly	adv.
Dis*pos"it*or	n.
Dis`pos*sess"	v. t.
dispossessed	adj.
Dis`pos*ses"sion	n.
Dis`pos*sess"or	n.
Dis*post"	v. t.
Dis*po"sure	n.
Dis*prais"a*ble	a.
Dis*praise"	v. t.
Dis*praise"	n.
Dis*prais"er	n.
Dis*praising*ly	adv.
Dis*pread"	v. t.
Dis*pread"	v. i.
Dis*pread"er	n.
Dis*prej"u*dice	v. t.
Dis`pre*pare"	v. t.
Dis*prince"	v. t.
Dis*pris"on	v. t.
Dis*priv"i*lege	v. t.
Dis*prize"	v. t.
Dis`pro*fess"	v. t.
Dis*prof"it	n.
Dis*prof"it	v. i. & i.
Dis*prof"it*a*ble	a.
Dis*proof"	n.
Dis*prop"er*ty	v. t.
Dis`pro*por"tion	n.
Dis`pro*por"tion	v. t.
Dis`pro*por"tion*a*ble	a.
Dis`pro*por"tion*al	a.
Dis`pro*por`tion*al"i*ty	n.
Dis`pro*por"tion*al*ly	adv.
Dis`pro*por"tion*ate	a.
Dis*pro"pri*ate	v. t.
Dis*prov"a*ble	a.
Dis*prov"al	n.
Dis*prove"	v. t.
Dis*prov"er	n.
Dis`pro*vide"	v. t.
Dis*punct"	a.
Dis*punct"	v. t.
Dis*punge"	v. t.
Dis*punge"	v. t.
Dis*pun"ish*a*ble	a.
Dis*pur"pose	v. t.
Dis*purse"	v. t.
Dis`pur*vey"	v. t.
Dis`pur*vey"ance	n.
Dis`pu*ta*ble	a.
Dis`pu*ta*ble*ness	n.
Dis`pu*tac"i*ty	n.
dis"pu*tant	a.
dis"pu*tant	n.
Dis`pu*ta"tion	n.
Dis`pu*ta"tious	a.
Dis*put"a*tive	a.
Dis*pute"	v. i.
Dis*pute"	v. t.
Dis*pute"	n.
Dis*pute"less	a.
Dis*put"er	n.
Dis*pu"ti*son	n.
Dis*qual`i*fi*ca"tion	n.
dis*qual"i*fied	adj.
dis*qual"i*fy	v. t.
Dis*quan"ti*ty	v. t.
Dis*qui"et	a.
Dis*qui"et	n.
Dis*qui"et	v. t.
Dis*qui"et*al	n.
Dis*qui"et*er	n.
Dis*qui"et*ful	a.
Dis*qui"et*ive	a.
Dis*qui"et*ly	adv.
Dis*qui"et*ment	n.
Dis*qui"et*ness	n.
Dis*qui"et*ous	a.
Dis*qui"et*tude	n.
Dis`qui*si"tion	n.
Dis`qui*si"tion*al	a.
Dis`qui*si"tion*a*ry	a.
Dis*quis"i*tive	a.
Dis*quis`i*to"ri*al	a.
Dis*quis"i*to*ry	a.
Dis*range"	v. t.
Dis*rank"	v. t.
dis*rate"	v. t.
dis*ray"	v. t.
dis`re*gard"	v. t.
Dis`re*gard"	n.
Dis`re*gard"er	n.
Dis`re*gard"ful	a.
Dis`re*gard"ful*ly	adv.
Dis*rel"ish	n.
Dis*rel"ish	v. t.
Dis`re*mem"ber	v. t.
Dis`re*pair"	n.
Dis*rep`u*ta*bil"i*ty	n.
Dis*rep"u*ta*ble	a.
Dis*rep"u*ta*bly	adv.
Dis*rep`u*ta"tion	n.
Dis`re*pute"	n.
Dis`re*pute"	v. t.
Dis`re*spect"	n.
Dis`re*spect"	v. t.
Dis`re*spect`a*bil"i*ty	n.
Dis`re*spect"a*ble	a.
Dis`re*spect"er	n.
Dis`re*spect"ful	a.
Dis`re*spect"ive	a.
Dis*rev"er*ence	v. t.
Dis*robe"	v. t. & i.
Dis*rob"er	n.
Dis*roof"	v. t.
Dis*root"	v. t.
Dis*rout"	v. i.
Dis*rud"der	v. t.
Dis*ru"li*ly	adv.
Dis*ru"ly	a.
Dis*rupt"	a.
dis*rupt"	v. t.
disrupted	adj.
Dis*rup"tion	n.
Dis*rupt"ive	a.
Dis*rup"ture	n.
Dis*sat`is*fac"tion	n.
Dis*sat`is*fac"to*ry	a.
dissatisfied	adj.
Dis*sat"is*fy	v. t.
Dis*seat"	v. t.
Dis*sect"	v. t.
Dis*sect"ed	a.
Dis*sect"i*ble	a.
Dis*sect"ing	a.
Dis*sec"tion	n.
Dis*sect"or	n.
Dis*seize"	v. t.
Dis`sei*zee"	n.
Dis*sei"zin	n.
Dis*sei"zor	n.
Dis*sei"zor*ess	n.
Dis*sei"zure	n.
Dis*sem"blance	n.
Dis*sem"blance	n.
Dis*sem"ble	v. t.
Dis*sem"ble	v. i.
Dis*sem"bler	n.
Dis*sem"bling	a.
Dis*sem"i*nate	v. t. & i.
dis*sem"i*na`ted	p. a.
disseminating	adj.
dis*sem`i*na"tion	n.
dis*sem"i*na*tive	a.
Dis*sem"i*na`tor	n.
Dis*sen"sion	n.
Dis*sen"sious	a.
Dis*sent"	v. i.
Dis*sent"	n.
Dis`sen*ta"ne*ous	a.
Dis"sen*ta*ny	a.
Dis`sen*ta"tion	n.
Dis*sent"er	n.
Dis*sent"er*ism	n.
Dis*sen"ti*ate	v. t.
Dis*sen"tient	a.
dissenting	adj.
Dis*sen"tious	a.
Dis*sent"ive	a.
Dis*sep"i*ment	n.
Dis*sert"	v. i.
Dis"ser*tate	v. i.
Dis`ser*ta"tion	n.
Dis`ser*ta"tion*al	a.
Dis`ser*ta"tion*ist	n.
Dis"ser*ta`tor	n.
Dis*sert"ly	adv.
Dis*serve"	v. t.
Dis*serv"ice	n.
Dis*serv"ice*a*ble	a.
Dis*set"tle	v. t.
Dis*set"tle*ment	n.
Dis*sev"er	v. t.
Dis*sev"er	v. i.
Dis*sev"er*ance	n.
Dis*sev`er*a"tion	n.
Dis*sev"er*ment	n.
Dis*shad"ow	v. t.
Dis*sheathe"	v. i.
Dis*ship"	v. t.
Dis*shiv"er	v. t. & i.
Dis"si*dence	n.
Dis"si*dent	a.
Dis"si*dent	n.
Dis"si*dent*ly	adv.
Dis*sil"i*ence	n.
Dis*sil"i*ent	a.
Dis`si*li"tion	n.
Dis*sim"i*lar	a.
Dis*sim`i*lar"i*ty	n.
Dis*sim"i*lar*ly	adv.
Dis*sim"i*late	v. t.
Dis*sim`i*la"tion	n.
Dis*sim"i*le	n.
Dis`si*mil"i*tude	n.
Dis*sim"u*late	a.
dis*sim"u*late	v. i.
dissimulating	adj.
dis*sim`u*la"tion	n.
Dis*sim"u*la`tor	n.
Dis*sim"ule	v. t. & i.
Dis*sim"u*ler	n.
Dis*sim"u*lour	n.
Dis"si*pa*ble	a.
dis"si*pate	v. t.
Dis"si*pate	v. i.
Dis"si*pa`ted	a.
Dis`si*pa"tion	n.
dis"si*pa*tive	a.
Dis`si*pa*tiv"i*ty	n.
Dis"site	a.
Dis*slan"der	v. t.
Dis*slan"der	n.
Dis*slan"der*ous	a.
Dis*so`cia*bil"i*ty	n.
Dis*so"cia*ble	a.
Dis*so"cial	a.
Dis*so"cial*ize	v. t.
dis*so"ci*ate	v. t.
dissociated	adj.
Dis*so`ci*a"tion	n.
Dis*so"ci*a*tive	a.
Dis`so*lu*bil"i*ty	n.
Dis"so*lu*ble	a.
Dis"so*lu*ble*ness	n.
Dis"so*lute	a.
Dis"so*lute*ly	adv.
Dis"so*lute*ness	n.
Dis`so*lu"tion	n.
Dis*solv`a*bil"i*ty	n.
Dis*solv"a*ble	a.
Dis*solv"a*tive	n.
Dis*solve"	v. t.
Dis*solve"	v. i.
dissolved	adj.
dis*solv"ent	a.
Dis*solv"ent	n.
Dis*solv"er	n.
Dis*solv"ing	a.
Dis"so*nance	n.
Dis"so*nan*cy	n.
Dis"so*nant	a.
Dis*spir"it	v. t.
Dis*suade"	v. t.
Dis*suad"er	n.
Dis*sua"sion	n.
Dis*sua"sive	a.
Dis*sua"so*ry	n.
Dis*sun"der	v. t.
Dis*sweet"en	v. t.
Dis`syl*lab"ic	a.
Dis`syl*lab`i*fi*ca"tion	n.
Dis`syl*lab"i*fy	v. t.
Dis*syl"la*bize	v. t.
Dis*syl"la*ble	n.
Dis`sym*met"ric*al	a.
Dis*sym"me*try	n.
Dis*sym"pa*thy	n.
Dis"tad	adv.
Dis"taff	n.
Dis*tain"	v. t.
Dis"tal	a.
Dis"tal*ly	adv.
Dis"tance	n.
Dis"tance	v. t.
Dis"tan*cy	n.
Dis"tant	a.
Dis*tan"tial	a.
Dis"tant*ly	adv.
Dis*taste"	n.
Dis*taste"	v. t.
Dis*taste"	v. i.
Dis*taste"ful	a.
Dis*taste"ive	a.
Dis*tas"ture	n.
Dis*tem"per	v. t.
Dis*tem"per	n.
Dis*tem"per*ance	n.
Dis*tem"per*ate	a.
Dis*tem"per*ate*ly	adv.
Dis*tem"per*a*ture	n.
Dis*tem"per*ment	n.
Dis*tend"	v. t.
Dis*tend"	v. i.
Dis*ten`si*bil"i*ty	n.
Dis*ten"si*ble	a.
Dis*ten"sion	n.
Dis*ten"sive	a.
Dis*tent"	a.
Dis*tent"	n.
Dis*ten"tion	n.
Dis*ter"	v. t.
Dis*ter"mi*nate	a.
Dis*ter`mi*na"tion	n.
Dis"thene	n.
Dis*throne"	v. t.
Dis*thron"ize	v. t.
Dis"tich	n.
Dis"tich	a.
Dis"tich*ous*ly	adv.
Dis*til"	v. t. & i.
Dis*till"	v. i.
Dis*till"	v. t.
Dis*till"a*ble	a.
Dis"till*ate	n.
Dis`til*la"tion	n.
Dis*til"la*to*ry	a.
Dis*till"er	n.
Dis*till"er*y	n.
Dis*till"ment	n.
Dis*tinct"	a.
Dis*tinct"	v. t.
Dis*tinc"tion	n.
Dis*tinc"tive	a.
Dis*tinc"tive*ly	adv.
Dis*tinc"tive*ness	n.
Dis*tinct"ly	adv.
Dis*tinct"ness	n.
Dis*tinc"ture	n.
Dis*tin"guish	v. t.
Dis*tin"guish	v. i.
Dis*tin"guish*a*ble	a.
Dis*tin"guish*a*ble*ness	n.
Dis*tin"guish*a*bly	adv.
Dis*tin"guished	a.
Dis*tin"guish*ed*ly	adv.
Dis*tin"guish*er	n.
Dis*tin"guish*ing	a.
Dis*tin"guish*ing*ly	adv.
Dis*tin"guish*ment	n.
Dis*ti"tle	v. t.
Dis"to*ma	n.
Dis*tort"	a.
Dis*tort"	v. t.
Dis*tort"er	n.
Dis*tor"tion	n.
Dis*tort"ive	a.
Dis*tract"	a.
Dis*tract"	v. t.
Dis*tract"ed	a.
Dis*tract"ed*ly	adv.
Dis*tract"ed*ness	n.
Dis*tract"er	n.
Dis*tract"ful	a.
Dis*tract"i*ble	a.
Dis*tract"ile	a.
Dis*tract"ing	a.
Dis*trac"tion	n.
Dis*trac"tious	a.
Dis*trac"tive	a.
Dis*train"	v. t.
Dis*train"	v. i.
Dis*train"a*ble	a.
Dis*train"er	n.
Dis*train"or	n.
Dis*traint"	n.
Dis`trait"	a.
Dis*traught"	p. p. & a.
Dis*traught"ed	a.
Dis*tream"	v. i.
Dis*tress"	n.
Dis*tress"	v. t.
distressed	adj.
Dis*tress"ed*ness	n.
Dis*tress"ful	a.
distressfulness	n.
dis*tress"ing	a.
Dis*tress"ing	adv.
Dis*trib"u*ta*ble	a.
Dis*trib"u*ta*ry	a.
Dis*trib"ute	v. t.
Dis*trib"ute	v. i.
distributed	adj.
Dis*trib"u*ter	n.
Dis*trib"u*ting	a.
Dis`tri*bu"tion	n.
Dis`tri*bu"tion*al	a.
Dis`tri*bu"tion*ist	n.
Dis*trib"u*tive	a.
Dis*trib"u*tive	n.
Dis*trib"u*tive*ly	adv.
Dis*trib"u*tive*ness	n.
Dis*trib"u*tor	n.
Dis"trict	a.
Dis"trict	n.
Dis"trict	v. t.
Dis*tric"tion	n.
Dis"trict*ly	adv.
Dis*trin"gas	n.
Dis*trou"ble	v. t.
dis*trust"	v. t.
dis*trust"	n.
Dis*trust"er	n.
Dis*trust"ful	a.
Dis*trust"ing	a.
Dis*trust"less	a.
Dis*tune"	v. t.
Dis*turb"	v. t.
Dis*turb"	n.
Dis*turb"ance	n.
Dis`tur*ba"tion	n.
Dis*turb"er	n.
Dis*turn"	v. t.
Dis"tyle	a.
Di*sul"phate	n.
Di*sul"phide	n.
Di*sul"phu*ret	n.
Di`sul*phu"ric	a.
Dis*u"ni*form	a.
Dis*un"ion	n.
Dis*un"ion*ist	n.
Dis`u*nite"	v. t.
Dis`u*nite"	v. i.
Dis`u*nit"er	n.
Dis*u"ni*ty	n.
Dis*us"age	n.
Dis*use"	v. t.
Dis*use"	n.
Dis*u"til*ize	v. t.
Dis*val`u*a"tion	n.
Dis*val"ue	v. t.
Dis*val"ue	n.
Dis`van*ta"geous	a.
Dis*vel"op	v. t.
Dis*ven"ture	n.
Dis*vouch"	v. t.
Dis*warn"	v. t.
Dis*wit"ted	a.
Dis*wont"	v. t.
Dis*work"man*ship	n.
Dis*wor"ship	v. t.
Dis*wor"ship	n.
Dis*worth"	v. t.
Dis*yoke"	v. t.
Dit	n.
Dit	v. t.
Di*ta"tion	n.
Ditch	n.
Ditch	v. t.
Ditch	v. i.
Ditch"er	n.
Dite	v. t.
Di*ter"e*bene	n.
Di*the"cal	a.
Di"the*ism	n.
Di"the*ist	n.
Di`the*is"tic	a.
Di`thi*on"ic	a.
Dith"y*ramb	n.
Dith`y*ram"bic	a.
Dith`y*ram"bus	n.
Di"tion	n.
Di"tion*a*ry	a.
Di"tion*a*ry	n.
Di"to*kous	a.
Di*tol"yl	n.
Di"tone`	n.
Di`tri*chot"o*mous	a.
Di`tro*che"an	a.
Di*tro"chee	n.
Dit"ro*ite	n.
Ditt	n.
Dit*tan"der	n.
Dit"ta*ny	n.
Dit"tied	a.
Dit"to	n.
Dit"to	adv.
Dit*tol"o*gy	n.
Dit"ty	n.
Dit"ty	v. i.
Dit"ty-bag`	n.
Dit"ty-box`	n.
Di*u"re*ide	n.
Di`u*re"sis	n.
Di`u*ret"ic	a.
Di`u*ret"ic*al	a.
Di`u*ret"ic*al*ness	n.
Di*ur"na	n. pl.
Di*ur"nal	a.
Di*ur"nal	n.
Di*ur"nal*ist	n.
Di*ur"nal*ly	adv.
Di*ur"nal*ness	n.
Di`ur*na"tion	n.
Di`u*tur"nal	a.
Di`u*tur"ni*ty	n.
Di"va	n.
Di`va*ga"tion	n.
Div"a*lent	a.
Di*van"	n.
Di*var"i*cate	v. i.
Di*var"i*cate	v. t.
Di*var"i*cate	a.
Di*var"i*cate*ly	adv.
Di*var`i*ca"tion	n.
Di*var`i*ca"tor	n.
Di*vast"	a.
Dive	v. i.
Dive	v. t.
Dive	n.
Dive"dap`per	n.
Di*vel"	v. t.
Di*vel"lent	a.
Di*vel"li*cate	v. t.
Div"er	n.
Di"verb	n.
Di*ver"ber*ate	v. t.
Di*ver`ber*a"tion	n.
Di*verge"	v. i.
Di*verge"ment	n.
Di*ver"gence	n.
Di*ver"gent	a.
Di*ver"ging	a.
Di*ver"ging*ly	adv.
Di"vers	a.
Di"verse	a.
Di*verse"	adv.
Di*verse"	v. i.
Di"verse*ly	adv.
Di*verse"ness	n.
Di*ver`si*fi`a*bil"i*ty	n.
Di*ver"si*fi`a*ble	a.
Di*ver`si*fi*ca"tion	n.
Di*ver"si*fied	a.
Di*ver"si*fi`er	n.
Di*ver"si*form	a.
Di*ver"si*fy	v. t.
Di`ver*sil"o*quent	a.
Di*ver"sion	n.
diversionary	adj.
Di*ver"si*ty	n.
Di`ver*siv"o*lent	a.
Di*ver"so*ry	a.
Di*ver"so*ry	n.
Di*vert"	v. t.
Di*vert"	v. i.
Di*vert"er	n.
Di*vert"i*ble	a.
Di*ver"ti*cle	n.
Div`er*tic"u*lar	a.
Div`er*tic"u*lum	n.
Di*ver`ti*men"to	n.
Di*vert"ing	a.
Di*vert"ise	v. t.
Di*vert"ise*ment	n.
Di`ver`tisse`ment"	n.
Di*vert"ive	a.
Di"ves	n.
Di*vest"	v. t.
Di*vest"i*ble	a.
Di*vest"i*ture	n.
Di*vest"ment	n.
Di*ves"ture	n.
Div"et	n.
Di*vid"a*ble	a.
Di*vid"ant	a.
Di*vide"	v. t.
Di*vide"	v. i.
Di*vide"	n.
Di*vid"ed	a.
Di*vid"ed*ly	adv.
Div"i*dend	n.
Div"i*dent	n.
Di*vid"er	n.
Di*vid"ing	a.
Di*vid"ing*ly	adv.
Di"vi-di"vi	n.
Di*vid"u*al	a.
Di*vid"u*al*ly	adv.
Di*vid"u*ous	a.
Div`i*na"tion	n.
Div"i*na`tor	n.
Di*vin"a*to*ry	a.
Di*vine"	a.
Di*vine"	n.
Di*vine"	v. t.
Di*vine"	v. i.
Di*vine"ly	adv.
Di*vine"ment	n.
Di*vine"ness	n.
Di*vin"er	n.
Di*vin"er*ess	n.
Div"ing	a.
Di*vin"i*fy	v. t.
Di*vin"ing	a.
Di*vin"ing*ly	adv.
Div`i*nis"tre	n.
Di*vin"i*ty	n.
Di*vin"i*ty calf`	n.
Div"i*nize	v. t.
Di*vis`i*bil"i*ty	n.
Di*vis"i*ble	a.
Di*vis"i*ble	n.
Di*vi"sion	n.
Di*vi"sion*al	a.
Di*vi"sion*al*ly	adv.
Di*vi"sion*a*ry	a.
Di*vi"sion*or	n.
Di*vi"sive	a.
Di*vi"sor	n.
Di*vorce"	n.
Di*vorce"	v. t.
Di*vorce"a*ble	a.
divorced	adj.
Di*vor`cee"	n.
Di*vorce"less	a.
Di*vorce"ment	n.
Di*vor"cer	n.
Di*vor"ci*ble	a.
Di*vor"cive	a.
Div"ot	n.
Di*vul"gate	a.
Di*vul"gate	v. t.
Div"ul*ga`ter	n.
Div`ul*ga"tion	n.
Di*vulge"	v. t.
Di*vulge"	v. i.
Di*vul"sive	a.
divvy	n.
div"vy	v. t. & i.
Dix"ie	prop. n.
Dixiecrats	n.
Dixieland	n.
Diz"en	v. t.
Dizz	v. t.
Diz"zard	n.
Diz"zi*ly	adv.
Diz"zi*ness	n.
Diz"zy	a.
Diz"zy	v. t.
DJ	n.
Djer*eed"	n.
DJIA	n.
Djibouti	prop. n.
Djiboutian	prop. adj.
Djiboutian	n.
djin"nee	n.
dkg	n.
D-layer	n.
DNA	n.
DNA polymerase	n.
DNase	n.
do.	n.
Do	n.
do	v. t. <or/ auxiliary
Do	v. i.
Do	n.
Do"ab	a.
Do"-all`	n.
Do"and	p. pr.
Doat	v. i.
Dob"ber	n.
Dob"bin	n.
Dob"by	n.
Dob"chick`	n.
Do*bell's" so*lu"tion	n.
Dob"ule	n.
Do"cent	a.
Do*ce"t<ae/	n. pl.
Do*cet"ic	a.
Doc"e*tism	n.
Doch"mi*ac	a.
Doch"mi*us	n.
Doc`i*bil"i*ty	n.
Doc"i*ble	a.
Doc"ile	a.
Do*cil"i*ty	n.
Doc"i*ma*cy	n.
Doc`i*mas"tic	a.
Doc`i*mol"o*gy	n.
Doc"i*ty	n.
Dock	n.
Dock	n.
Dock	v. t.
Dock	n.
Dock	v. t.
Dock"age	n.
Dock"-cress`	n.
docker	n.
Dock"et	n.
Dock"et	v. t.
dockhand	n.
docking	n.
dock-walloper	n.
dock"yard`	n.
Doc`o*glos"sa	n. pl.
doc"quet	n. & v.
doc"tor	n.
Doc"tor	v. t.
Doc"tor	v. i.
Doc"tor*al	a.
Doc"tor*al*ly	adv.
Doc"tor*ate	n.
Doc"tor*ate	v. t.
Doc"tor*ess	n.
Doc"tor*ly	a.
Doc"tor*ship	n.
Doc"tress	n.
Doc"tri*na*ble	a.
Doc`tri*naire"	n.
doc"tri*nal	a.
Doc"tri*nal	n.
Doc"tri*nal*ly	adv.
Doc"tri*na"ri*an	n.
Doc`tri*na"ri*an*ism	n.
doc"trine	n.
docudrama	n.
doc"u*ment	n.
Doc"u*ment	v. t.
Doc`u*men"tal	a.
Doc`u*men"ta*ry	a.
DoD	prop. n.
Dodd	v. t.
Dod"dart	n.
Dod"ded	a.
Dod"der	n.
Dod"der	v. t. & i.
Dod"dered	a.
doddering	adj.
doddery	adj.
Do*dec"a*gon	n.
Do*dec`a*gyn"i*a	n. pl.
Do*dec`a*gyn"i*an	a.
Do*dec`a*he"dral	a.
Do*dec`a*he"dron	n.
Do`de*can"dri*a	n. pl.
Do`de*can"dri*an	a.
Do"de*cane	n.
Do*dec"a*style	a.
Do*dec`a*syl*lab"ic	a.
Do*dec"a*syl`la*ble	n.
Do*dec`a*tem"o*ry	n.
Dodge	v. i.
Dodge	v. t.
Dodge	n.
Dodgem	n.
dodg"er	n.
Dodg"er	prop. n.
Dodg"er*y	n.
Dod"i*pate	n.
Dod"kin	n.
Dod"man	n.
Do"do	n.
Doe	n.
Doe	n.
Doe, John	a.
D<oe/g"ling	n.
Do"er	n.
Does	3d pers. sing. pres.
Doe"skin`	n.
Doff	v. t.
Doff	v. i.
Doff"er	n.
Dog	n.
Dog	v. t.
Do"gal	a.
Do"gate	n.
Dog"bane`	n.
Dog" bee`	n.
Dog"bolt`	n.
Dog"-bri`er	n.
Dog"cart`	n.
Dog" day`	n.
Doge	n.
dog-ear	n.
dog"-eared`	a.
Doge"ate	n.
Doge"less	a.
do"gey	n.
Dog"-faced`	a.
Dog" fan`cier	n.
Dog"-fox`	n.
Dog"ged	a.
Dog"ged*ly	adv.
Dog"ged*ness	n.
Dog"ger	n.
Dog"ger	n.
Dog"ger*el	a.
Dog"ger*el	n.
Dog"ger*man	n.
Dog"get	n.
Dog"gish	a.
dog"gone	a.
dog"gone	adv.
dog"gone	v. t.
Dog"grel	a. & n.
Dog"-head`ed	a.
Dog"-heart`ed	a.
Dog"hole`	n.
do"gie	n.
dog"-leg`ged	a.
Dog"ma	n.
dog*mat"ic	n.
dog*mat"ic	a.
Dog*mat"ic*al*ly	adv.
Dog*mat"ic*al*ness	n.
Dog`ma*ti"cian	n.
Dog*mat"ics	n.
Dog"ma*tism	n.
Dog"ma*tist	n.
Dog"ma*tize	v. i.
Dog"ma*tize	v. t.
Dog"ma*ti`zer	n.
Dog"-rose`	n.
Dog's"-bane`	n.
Dog's"-ear`	n.
Dog"ship	n.
Dog"shore`	n.
Dog"sick`	a.
Dog"skin	n.
Dog"sleep`	n.
Dog's"-tail grass`	n.
Dog" Star`	n.
Dog"tie`	n.
Dog"tooth`	n.
Dog"trick`	n.
Dog"vane`	n.
Dog"watch`	n.
Dog"-wea`ry	a.
Dog"wood`	n.
do"gy	n.
doh	n.
Doha	prop. n.
Doh"tren	n. pl.
Doi"ly	n.
Do"ing	n.
Doit	n.
Doit"kin	n.
do-it-yourself	adj.
do-it-yourselfer	n.
Dok`i*mas"tic	a.
Do"ko	n.
Do*la"bra	n.
Do*lab"ri*form	a.
Dol"ce	adv.
Dol*ci"no	n.
dol"drums	n. pl.
Dole	n.
Dole	n.
Dole	n.
Dole	v. t.
Dole"ful	a.
Do"lent	a.
Do*len"te	a. & adv.
Dol"er*ite	n.
Dol`er*it"ic	a.
Dole"some	a.
Dolf	imp.
Dol`i*cho*ce*phal"ic	a.
Dol`i*cho*ceph"a*ly	n.
Dolichotis	n.
do"li*o*form	a.
Doliolidae	n.
Do*li"o*lum	n.
Do"-lit`tle	n.
Do"li*um	n.
doll	n.
dol"lar	n.
dollar bill	n.
dollarfish	n.
dollhouse	n.
Doll"man	n.
Dol"ly	n.
Dol"ly	n.
Dol"ly Var"den	n.
Dol"man	n.
dolmas	n.
dol"men	n.
dol"o*mite	n.
dol`o*mit"ic	a.
dol"o*mize	v. t.
do"lor	n.
Dol`or*if"er*ous	a.
Dol`or*if"ic	a.
Do`lo*ro"so	a. & adv.
Dol"or*ous	a.
dolourous	adj.
dolostone	n.
dol"phin	n.
dol"phin*et	n.
dolphinfish	n.
dolt	n.
dolt	v. i.
dolt"ish	a.
Do"lus	n.
Dolv"en	p. p.
-dom	n.
Dom"a*ble	a.
Dom"a*ble*ness	n.
Dom"age	n.
Do*main"	n.
Do"mal	a.
Do*ma"ni*al	a.
Dome	n.
Dome	n.
Dome"book`	n.
Domed	a.
Domes"day`	n.
Domes"man	n.
Do*mes"tic	a.
Do*mes"tic	n.
Do*mes"tic*al	a.
Do*mes"tic*al	n.
Do*mes"tic*al*ly	adv.
Do*mes"ti*cant	a.
Do*mes"ti*cate	v. t.
domesticated	adj.
Do*mes`ti*ca"tion	n.
Do*mes"ti*ca`tor	n.
Do`mes*tic"i*ty	n.
Dom"ett	n.
Do"mey*kite	n.
Dom"i*cal	a.
Dom"i*cile	n.
Dom"i*cile	v. t.
Dom`i*cil"i*ar	n.
Dom`i*cil"l*a*ry	a.
Dom`i*cil"i*ate	v. t.
Dom`i*cil`i*a"tion	n.
Dom"i*cul`ture	n.
Dom"i*fy	v. t.
Dom"i*na	n.
Dom"i*nance	n.
Dom"i*nant	a.
Dom"i*nant	n.
Dom"i*nate	v. t.
Dom"i*nate	v. i.
dominated	adj.
dominating	adj.
Dom`i*na"tion	n.
Dom"i*na*tive	a.
Dom"i*na`tor	n.
dom"i*ne	n.
Dom`i*neer"	v. i. & t.
Dom`i*neer"ing	a.
Do*min"ic*al	a.
Do*min"ic*al	n.
Do*min"i*can	prop. a.
Do*min"i*can	prop. n.
do*min"i*cide	n.
Dom"i*nick	n.
Dom"i*nie	n.
Do*min"ion	n.
Do*min"ion Day	n.
Dom"i*no	n.
Dom"i*no the"o*ry	n.
Dom"i*ta*ble	a.
Do"mite	n.
Don	n.
Don	v. t.
Do"<ntil/a	n.
Do"na*ble	a.
Donar	n.
Do"na*ry	n.
Don"at	n.
Don"a*ta*ry	n.
Do"nate	v. t.
donated	adj.
Do*na"tion	n.
Don"a*tism	n.
Don"a*tist	n.
Don`a*tis"tic	a.
Don"a*tive	n.
Don"a*tive	a.
Do*na"tor	n.
Don"a*to*ry	n.
Do"-naught`	n.
Do"nax	n.
Don*cel"la	n.
Done	p. p.
Done	a.
Do*nee"	n.
Don"et	n.
Do"ni	n.
Do*nif"er*ous	a.
Don"jon	n.
Don"key	n.
donkey's tail	n.
donkey's years	n.
donkeywork	n.
Don"go*la	n.
Don"na	n.
Don"nat	n.
Don`n<eacute/e"	n.
Donnian	adj.
donnish	adj.
don"nism	n.
Do"nor	n.
do"-noth`ing	a.
do-nothing	n.
Do"-noth`ing*ism	n.
Don"ship	n.
Don"zel	n.
Doo	n.
Doob" grass`	n.
doo"dle*sack`	n.
doo"fus	n.
doo"hick*ey	n.
doole	n.
Doo"ly	n.
Doom	n.
Doom	v. t.
Doom"age	n.
Doom"ful	a.
Doom" palm`	n.
Dooms"man	n.
Doom"ster	n.
Door	n.
doorbell	n.
Door"case`	n.
Door"cheek`	n.
Door"ga	n.
Door"ing	n.
Door"keep`er	n.
doorknocker	n.
Door"less	a.
doorlock	n.
doorman	n.
doormat	n.
Door"nail`	n.
Door"plane`	n.
Door"post`	n.
Door"sill`	n.
Door"stead	n.
Door"step`	n.
Door"stone`	n.
door"stop`	n.
door"stop*per	n.
door-to-door	adj.
Door"way`	n.
Door"yard`	n.
Dop	n.
Dop	v. i.
Dop	n.
Dop"ant	n.
Dope	n.
Dope	v. t.
Dope"-book`	n.
Dop"ey	a.
Dop"pel*g<aum/ng`er	n.
Dop"per	n.
Dop"pler*ite	n.
Doq"uet	n.
Dor	n.
Dor	n.
Dor	v. t.
Do*ra"do	n.
Dor"bee`tle	n.
Do"ree	n.
Dore"tree`	n.
Dor"hawk`	n.
Do"ri*an	a.
Do"ri*an	n.
Dor"ic	a.
Dor"ic	n.
Dor"i*cism	n.
Do"ris	n.
Do"rism	n.
dork	n.
Dor"king fowl`	n.
Dorm	n.
Dor"man*cy	n.
Dor"man*cy	n.
Dor"mant	n.
Dor"mer	n.
Dor"mi*tive	a.
Dor"mi*to*ry	n.
Dor"mouse	n.
Dor"my	a.
Dorn	n.
Dor"nick	n.
Dorp	n.
Dorr	n.
Dorr	v. t.
Dorr"fly`	n.
Dorr"hawk`	n.
Dor"sad	adv.
Dor"sal	a.
Dor"sal	n.
Dor"sale	n.
Dor"sal*ly	adv.
Dorse	n.
Dorse	n.
Dor"sel	n.
Dor"ser	n.
dor`si*bran`chi*a"ta	n. pl.
Dor`si*bran"chi*ate	a.
Dor*sif"er*ous	n.
Dor*sip"a*rous	a.
Dor`si*ven"tral	a.
Dor`so*ven"tral	a.
Dor"sum	n.
Dor"tour	n.
Do"ry	n.
Do"ry	n.
Do*ryph"o*ra	n.
Do*ryph"o*ros	n.
Dos`-<agrave/-dos"	adv.
Dos`-<agrave/-dos"	n.
Dos"age	n.
Dose	n.
Dose	v. t.
Dos"el	n.
do`-si`-do"	n.
dosimeter	n.
do*sim"et*er	n.
do*sim"et*er badge	n.
do*sim"e*try	n.
Do*sol"o*gy	n.
Doss	n.
doss	v. i.
Doss house	n.
Dos"ser	n.
Dos`sier"	n.
Dos"sil	n.
Dost	2d pers. sing. pres.
Dostoevski	prop. n.
Dostoevskian	prop. adj.
Dot	n.
Dot	n.
Dot	v. t.
Dot	v. i.
DoT	prop. n.
Do"tage	n.
Do"tal	a.
Do"tant	n.
Do"tard	n.
Do"tard*ly	a.
Do"ta*ry	n.
Do*ta"tion	n.
Dote	n.
Dote	v. i.
Dote	n.
Dot"ed	a.
Dote"head`	n.
Dot"er	n.
Dot"er*y	n.
Doth	3d pers. sing. pres.
Dot"ing	a.
Dot"ish	a.
Dot"tard	n.
Dot"ted	a.
Dot"ter*el	a.
Dot"ter*el	n.
Dot"ting pen`	n.
Dot"ty	a.
Do"ty	a.
Dou`ane"	n.
Dou`a"nier"	n.
Dou"ar	n.
Dou"ay Bi"ble	a.
Dou"ble	adv.
Dou"ble	v. t.
Dou"ble	v. i.
Dou"ble	n.
Dou"ble-act`ing	a.
Dou"ble-bank"	v. t.
Dou"ble-banked`	a.
Dou"ble-bar`reled	a.
Dou"ble-beat` valve"	a.
Dou"ble-charge`	v. t.
double cross	v. t.
double cross	n.
double-crosser	n.
doubled	adj.
Dou"ble deal"er	adj.
Dou"ble-deck"er	n.
Dou"ble-dye`	v. t.
Dou"ble-dyed`	a.
Dou"ble-end"er	n.
Dou"ble-en*ten"dre	n.
Dou"ble-eyed`	a.
Dou"ble*gang`er	n.
Dou"ble-faced`	a.
Dou"ble first`	a.
Dou"ble-head"ed	a.
doubleheader	n.
Dou"ble-heart"ed	a.
Dou"ble-hung`	a.
Dou"ble-lock`	v. t.
Dou"ble-milled`	a.
Dou"ble-mind"ed	a.
Dou"ble*ness	n.
Double pedro	a.
Dou"ble-quick`	n.
Dou"ble-quick`	v. i. & t.
Dou"bler	n.
Dou"ble-rip"per	n.
dou"bles	n.
dou"ble-shade`	v. t.
dou"ble stan"dard	n.
Dou"ble-sur"faced	a.
Doub"let	n.
Dou"ble-thread`ed	a.
Dou"ble-tongue`	n.
Dou"ble-tongued`	a.
Dou"ble-tongu`ing	n.
Dou"ble*tree`	n.
Doub"lets	n. pl.
Dou"bling	n.
Doub*loon"	n.
Dou`blure"	n.
Dou"bly	adv.
Doubt	v. i.
Doubt	v. t.
Doubt	n.
Doubt"a*ble	a.
Doubt"ance	n.
Doubt"er	n.
Doubt"ful	a.
Doubt"ful*ly	adv.
Doubt"ful*ness	n.
Doubt"ing	a.
Doubt"less	a.
Doubt"less	adv.
Doubt"less*ly	adv.
Doubt"ous	a.
Douc	n.
Douce	a.
Douce"pere`	n.
Dou"cet	n.
Dou`ceur"	n.
Douche	n.
Dou"cine	n.
Douck"er	n.
Dough	n.
Dough"-baked`	a.
Dough"bird`	n.
Dough"face`	n.
Dough"-faced`	a.
Dough"face`ism	n.
Dough"i*ness	n.
Dough"-knead`ed	a.
Dough"nut	n.
Dough"ti*ly	adv.
Dough"ti*ness	n.
Dough"tren	n. pl.
Dough"ty	a.
Dough"y	a.
Dou*loc"ra*cy	n.
Doum" palm`	n.
Dour	a.
Dou"ra	n.
Dou`rou*cou"li	n.
Douse	v. t.
Douse	v. i.
Douse	v. t.
Dous"ing-chock`	n.
Dout	v. t.
Dout"er	n.
Dove	n.
Dove"cot`	n.
Dove"-eyed`	a.
Dove"kie	n.
Dove"let	n.
Dove"like`	a.
Dove" plant`	n.
Dove"ship	n.
Dove"tail`	n.
Dove"tail`	v. t.
Dov"ish	a.
Dovyalis	n.
Dow	n.
Dow	v. t.
Dow	prop. n.
Dow"a*ble	a.
Dow"a*ger	n.
Dow"a*ger*ism	n.
Dow"cet	n.
Dow"dy	a.
Dow"dy	n.
Dow"dy*ish	a.
Dow"el	n.
Dow"el	v. t.
doweling	n.
Dow"er	n.
Dow"ered	p. a.
Dow"er*less	a.
Dow"er*y	n.
Dow"itch*er	n.
Dow-Jones Index	n.
Dow-Jones Industrial Average	n.
Dowl	n.
Dow"las	n.
Dowle	n.
Down	n.
Down	v. t.
Down	n.
Down	adv.
Down	prep.
Down	v. t.
Down	v. i.
Down	a.
down-and-out	adj.
down-and-out	n.
Down"bear`	v. t.
downbeat	n.
downbound	adj.
down-bow	n.
down"cast`	a.
Down"cast`	n.
Down"come`	n.
Down"com`er	n.
downed	adj.
downer	n.
Down"fall`	n.
Down"fall`en	a.
Down"fall`ing	a.
Down"gyved`	a.
Down"haul`	n.
Down"heart`ed	a.
Down"hill`	adv.
Down"hill`	a.
Down"hill`	n.
Down"i*ness	n.
Down"looked`	a.
Down"ly`ing	n.
down-market	adj.
Down"pour`	n.
Down"right`	adv.
Down"right`	a.
Down"-share`	n.
Down"sit`ting	n.
downsizing	n.
downslope	n.
downstage	n.
downstage	adj.
downstage	adv.
downstair	adj.
down"stairs	adv.
Down"steep`y	a.
Down"stream`	adv.
Down"stroke`	n.
Down" syn`drome	n.
Down"throw`	n.
down-to-earth	adj.
Down"trod`	a.
Down"ward	adv.
Down"ward	a.
Down"weed`	n.
Down`weigh"	v. t.
Down"-wind`	adv.
down"wind	adj.
Down"y	a.
Down"y wood"peck*er	n.
Dow"ral	a.
Dow"ress	n.
Dow"ry	n.
Dowse	v. t.
Dowse	v. i.
Dowse	n.
Dows"er	n.
Dowst	n.
Dow"ve	n.
Dox`o*log"ic*al	a.
Dox*ol"o*gize	v. i.
Dox*ol"o*gy	n.
Dox"y	n.
Doy`en"	n.
doy`enne"	n. f.
doyley	n.
doy"ly	n.
Doze	v. i.
Doze	v. t.
Doze	n.
Doz"en	n.
Doz"enth	a.
Doz"er	n.
Doz"i*ness	n.
Doz"y	a.
Doz"zled	a.
DPhil	n.
Dr.	n.
Drab	n.
Drab	v. i.
Drab	n.
Drab	a.
Drab"ber	n.
Drab"bet	n.
Drab"bish	a.
Drab"bish	a.
Drab"ble	v. t.
Drab"ble	v. i.
Drab"bler	n.
Drab"ble-tail`	n.
Dra*c<ae/"na	prop. n.
Dra"canth	n.
Drachm	n.
Drach"ma	n.
Drach"me	n.
Dra"cin	n.
Dra"co	n.
Dra`co*ceph"a*lum	prop. n.
Dra*co"ni*an	a.
Dra*con"ic	a.
Dra*co"nin	n.
Dra*con"tic	a.
Dra*con"tine	a.
Dra*cun"cu*lus	n.
Drad	p. p. & a.
Drad"de	imp.
Dradge	n.
Draff	n.
Draff"ish	a.
Draff"y	a.
Draft	n.
Draft	a.
Draft	v. t.
drafting	n.
Drafts"man	n.
draftsmanship	n.
draftsperson	n.
draft"y	adj.
Drag	n.
Drag	v. t.
Drag	v. i.
Drag	n.
Dra*gan"tine	n.
Drag"bar`	n.
Drag"bolt`	n.
dragee	n.
Dra`g<eacute/es"	n. pl.
dragging	adj.
Drag"gle	v. t.
Drag"gle	v. i.
draggled	adj.
Drag"gle-tail`	n.
Drag"gle-tailed`	a.
Drag line	n.
Drag"man	n.
Drag"net`	n.
Drag"o*man	n.
drag"on	n.
Drag"on*et	n.
Drag"on*ish	a.
Drag"on*like`	a.
Drag`on*nade"	n.
Drag"on's blood	n.
Dra*goon"	v. t.
Drag`oon*ade"	n.
Dra*goon"er	n.
Drail	v. t. & i.
Drain	v. t.
Drain	v. i.
Drain	n.
Drain"a*ble	a.
Drain"age	n.
drain"board`	n.
Draine	n.
drained	adj.
Drain"er	n.
Drain"ing	vb. n.
Drain"pipe`	n.
Drain"tile`	n.
Drain"trap`	n.
Drake	n.
Drake	n.
Drake	n.
Drake"stone	n.
Dram	n.
Dram	v. i. & t.
DRAM	n.
Dra"ma	n.
Dra*mat"ic	a.
Dra*mat"ic*al*ly	adv.
dramatisation	n.
Dram"a*tis per*so"n<ae/	n.
Dram"a*ti`za*ble	a.
dram`a*ti*za"tion	n.
Dram"a*tize	v. t.
Dram`a*tur"gic	a.
Dram"a*tur`gist	n.
Dram"a*tur`gy	n.
Dram"ming	n.
Dram"sell`er	n.
Dram"shop`	n.
Drank	imp.
Drank	n.
Drap` d'<eacute/*t<eacute/"	v. t.
Drape	v. i.
draped	adj.
Dra"per	n.
Dra"per*ied	a.
Dra"per*y	n.
Dra"pet	n.
Dras"tic	a.
Dras"ty	a.
Draugh	n.
Draught	n.
Draught	a.
Draught	v. t.
Draught"board`	n.
Draught"house`	n.
Draughts	n. pl.
Draughts	n. pl.
Draughts"man	n.
Draughts"man*ship	n.
Draught"y	a.
Drave	imp.
Dra"vi*da	n. pl.
Dra*vid"i*an	prop. a.
Dravidic	prop. n.
draw	v. t.
Draw	v. i.
Draw	n.
Draw"a*ble	a.
Draw"back`	n.
Draw"bar`	n.
Draw"bench`	n.
Draw"bolt`	n.
Draw"bore`	n.
Draw"bore`	v. t.
Draw"boy`	n.
Draw"bridge`	n.
Draw"can*sir	n.
Draw"-cut`	n.
draw*ee"	n.
draw"er	n.
Draw"fil`ing	n.
Draw"gear`	n.
Draw"gloves`	n. pl.
Draw"head`	n.
Draw"ing	n.
Draw"ing knife"	n.
Draw"ing-room`	n.
drawknife	n.
Drawl	v. t.
Drawl	v. i.
Drawl	n.
Draw"latch`	n.
Drawl"ing	n.
Draw"link`	n.
Draw"loom`	n.
Drawn	p. p. & a.
Draw"net`	n.
drawnwork	n.
Draw"plate`	n.
Draw"rod`	n.
Draw"shave`	n.
Draw"spring`	n.
Dray	n.
Dray	n.
Dray"age	n.
Dray"man	n.
Draz"el	n.
Dread	v. t.
Dread	v. i.
Dread	n.
Dread	a.
Dread"a*ble	a.
Dread"-bolt`ed	a.
Dread"er	n.
Dread"ful	a.
Dread"ful*ly	adv.
Dread"ful*ness	n.
Dread"ing*ly	adv.
Dread"less	a.
Dread"less	adv.
Dread"less*ness	n.
Dread"ly	a.
Dread"naught`	n.
Dread"nought`	n.
Dream	n.
Dream	v. i.
Dream	v. t.
Dream"er	n.
Dream"ful	a.
Dream"i*ly	adv.
Dream"i*ness	n.
Dream"ing*ly	adv.
Dream"land`	n.
Dream"less	a.
dreamlike	adj.
dream"world`	n.
dream"y	a.
Drear	a.
Drear	n.
Drear"i*head	n.
Drear"i*ly	adv.
Drear"i*ment	n.
Drear"i*ness	n.
Drear"ing	n.
Drear"i*some	a.
Drear"y	a.
Drec"che	v. t.
Drec"che	v. i.
Dredge	n.
Dredge	v. t.
Dredge	n.
Dredge	v. t.
Dredg"er	n.
Dredg"er	n.
Dree	v. t.
Dree	v. i.
Dree	a.
Dreg	n.
Dreg"gi*ness	n.
Dreg"gish	a.
Dreg"gy	a.
Drei"bund`	n.
dreidel	n.
Drein	v. i.
Drein"te	imp.
Dreis"se*na	prop. n.
Drench	v. t.
Drench	n.
Drench	n.
Drench"e	v. t. & i.
Drench"er	n.
Dren"gage	n.
Drent	p. p.
Dres"den ware`	v. t.
Dress	v. i.
Dress	n.
dressage	n.
Dress circle	adj.
dressed to kill	pred. adj.
dressed-up	adj.
dress"er	n.
Dress"er	n.
Dress" goods"	n.
Dress"ing	n.
Dressing table	n.
Dress"mak`er	n.
Dress"mak`ing	n.
Dress"y	a.
Drest	p. p.
Dretch	v. t. & i.
Dreul	v. i.
Drev"il	n.
Drew	imp.
Drey	n.
Dreye	a.
Dreyn"te	imp.
Drib	v. t.
Drib	v. t. & i.
Drib	n.
Drib"ber	n.
Drib"ble	v. i.
Drib"ble	v. t.
Drib"ble	n.
Drib"bler	n.
Drib"blet	n.
Drie	v. t.
Dried	imp. & p. p.
dried-out	adj.
dried-up	adj.
Dri"er	n.
Dri"er	compar.
Drift	n.
Drift	v. i.
Drift	v. t.
Drift	a.
Drift"age	n.
Drift"bolt`	n.
Drift"less	a.
Drift"piece"	n.
Drift"pin`	n.
Drift"way`	n.
Drift"weed`	n.
Drift"wind`	n.
Drift"wood`	n.
Drift"y	a.
Drill	v. t.
Drill	v. i.
Drill	n.
Drill	v. t.
Drill	v. i.
Drill	n.
Drill	n.
Drill	n.
Drill"er	n.
Drill"ing	n.
Drill"ing	n.
Drill"ing	n.
Drill"mas`ter	n.
Drill" press`	n.
Dri"ly	adv.
Dri"mys	n.
Drink	v. i.
Drink	v. t.
Drink	n.
Drink"a*ble	a.
Drink"a*ble*ness	n.
Drink"er	n.
Drink"ing	n.
Drink"less	a.
Drip	v. i.
Drip	v. t.
Drip	n.
drip-dry	adj.
Drip"ping	n.
Drip"ple	a.
drippy	adj.
Drip"stone`	n.
Drive	v. t.
Drive	n.
Drive	v. i.
Drive	p. p.
Drive	n.
Drive"bolt`	n.
drive-by	n.
drive-in	n.
drive-in	a.
drive-in window	n.
driveshaft	n.
drive-through	a.
Driv"el	v. i.
Driv"el	n.
Driv"el*er	n.
Driv"en	p. p.
Drive"pipe`	n.
Driv"er	n.
Drive"way`	n.
Driv"ing	a.
Driv"ing	n.
Driz"zle	v. i.
Driz"zle	v. t.
Driz"zle	n.
drizzling	adj.
Driz"zly	a.
Drock	n.
Drof"land	n.
Dro"gher	n.
Drog"man	n.
Drogue	n.
Droh	imp.
Droil	v. i.
Droil	n.
Droit	n.
Droi"tu*ral	a.
Droitzsch"ka	n.
Droll	a.
Droll	n.
Droll	v. i.
Droll	v. t.
Droll"er	n.
Droll"er*y	n.
Droll"ing*ly	adv.
Droll"ish	a.
Droll"ist	n.
Dro`m<ae/*og"na*thous	a.
Drom`a*the"ri*um	n.
Drome	n.
Drome	n.
Drom"e*da*ry	n.
Drom"ond	n.
Drone	v. i.
Drone" bee`	n.
Dron"go	n.
Dron"ish	a.
Dron"ke*lewe	a.
Dron"te	n.
Dron"y	a.
Drool	v. i.
Droop	v. i.
Droop	v. t.
Droop	n.
Droop"er	n.
Droop"ing*ly	adv.
droopy	adj.
Drop	n.
Drop	v. t.
Drop	v. i.
drop" cloth`	n.
drop forge	n.
dropforge	v. t.
dropkick	n.
dropkicker	n.
drop"let	n.
drop"light`	n.
Drop"meal`	adv.
drop-off	n.
dropped	adj.
drop"per	n.
Drop"ping	n.
droppings	n. pl.
Drop"ping*ly	adv.
Drop"si*cal	a.
Drop"si*cal*ness	n.
Drop"sied	a.
Drop"sy	n.
Dropt	imp. & p. p.
Drop"wise`	adv.
Drop"worm`	n.
Drop"wort`	n.
Dros"e*ra	n.
Droseraceae	n.
droshky	n.
dros"ky	n.
Dro*som"e*ter	n.
Drosophilidae	n.
Drosophyllum	n.
Dross	n.
Dros"sel	n.
Dross"less	a.
Dross"y	a.
Drotch"el	n.
Drough	imp.
Drought	n.
Drought"i*ness	n.
Drought"y	a.
Drou"my	a.
Drouth	n.
Drouth"y	a.
Drove	imp.
Drove	n.
Drove	v. t. & i.
Dro"ven	p. p.
Dro"ver	n.
Dro"vy	a.
Drow	imp.
Drown	v. i.
Drown	v. t.
Drown"age	n.
Drown"er	n.
Drowse	v. i.
Drowse	v. t.
Drowse	n.
drow"si*head	n.
drow"si*hed	n.
drow"si*ly	adv.
drow"si*ness	n.
drowsing	adj. prenom.
Drow"sy	a.
Drowth	n.
Droyle	v. i.
Drub	v. t.
Drub	n.
Drub"ber	n.
Drudge	v. i.
Drudge	v. t.
Drudge	n.
Drudg"er	n.
Drudg"er*y	n.
Drudg"ing box`	adv.
Dru"er*y	n.
Drug	v. i.
Drug	n.
Drug	n.
Drug	v. i.
Drug	v. t.
drugged	adj.
drugging	n.
Drug"ger	n.
Drug"get	n.
drug"gist	n.
Drug"ster	n.
drugstore	n.
Dru"id	n.
Dru"id*ess	n.
Dru*id"ic	a.
Dru"id*ish	a.
Dru"id*ism	n.
Drum	n.
Drum	v. i.
Drum	v. t.
Drum"beat`	n.
Drum"ble	v. i.
Drum"fish`	n.
Drum"head`	n.
Drum"lin	n.
Drum"ly	a.
Drum" ma"jor	n.
Drum"mer	n.
Drum"ming	n.
Drum"mond light`	n.
Drum winding	a.
Drunk	n.
Drunk"ard	n.
Drunk"en	a.
Drunk"en*head	n.
Drunk"en*ly	adv.
Drunk"en*ness	n.
Drunk"en*ship	n.
Dru*pa"ceous	a.
Drup"al	a.
Drupe	n.
Drup"el	n.
Druse	n.
Druse	n.
Dru"sy	a.
Drux"ey	a.
Dry	a.
Dry	v. t.
Dry	v. i.
Dry"ad	n.
Dryadella	n.
Dry*an"dra	n.
Dry"as	n.
Dry"-beat`	v. t.
Dry"-boned`	a.
dry-clean	v. t.
dry-cleaned	adj.
Dry" dock`	n.
Dry"-eyed`	a.
Dry"-fist`ed	a.
Dry"foot	n.
Dry" goods`	a.
Dry"ly	adv.
Drymoglossum	n.
Drynaria	n.
Dry"ness	n.
Dry" nurse`	v. t.
Dry`o*bal"a*nops	n.
drypis	n.
Dry"-rub`	v. t.
Dry"salt`er	n.
Dry"salt`er*y	n.
Dry"-shod`	a.
Dry"-stone`	a.
Dryth	n.
Du"ad	n.
Du"al	a.
Du"a*lin	n.
Du"al*ism	n.
Du"al*ist	n.
Du`al*is"tic	a.
Du"al"i*ty	n.
Du"an	n.
Du"ar*chy	n.
Dub	v. t.
Dub	v. i.
Dub	v. t.
Dub	n.
Dub	n.
Dubb	n.
Dub"ber	n.
Dub"ber	n.
Dub"bing	n.
Du*bi"e*ty	n.
Du`bi*os"i*ty	n.
Du"bi*ous	a.
Du"bi*ous*ly	adv.
Du"bi*ous*ness	n.
Du"bi*ta*ble	a.
Du"bi*tan*cy	n.
Du"bi*tate	v. i.
Du`bi*ta"tion	n.
Du"bi*ta*tive	a.
Dublin	prop. n.
Du*bois"i*a	n.
Du*bois"ine	n.
Du"cal	a.
Du"cal*ly	adv.
Duc"at	n.
Duc`a*toon"	n.
Du"ces te"cum	n.
Du`chesse" d'An`gou`l<ecir/me"	n.
Duck	n.
Duck	n.
Duck	v. t.
Duck	v. i.
Duck	n.
Duck"bill`	n.
duck-billed	adj.
Duck"-billed`	a.
Duck"-billed` plat"y*pus	a.
Duck"er	n.
Duck"ing	n. & a.
Duck"-legged`	a.
Duck"ling	n.
Duck"meat`	n.
Duck's"-bill`	a.
Duck's"-foot`	n.
Duck"weed`	n.
ducky	a.
ducky	n.
Duct	n.
Duc"ti*ble	a.
Duc"tile	a.
Duc`ti*lim"e*ter	n.
Duc*til"i*ty	n.
Duc"tion	n.
Duct"less	a.
Duc"tor	n.
Duc"ture	n.
Dud"der	v. t.
Dud"der	v. i.
Dud"der	n.
Dud"der*y	n.
Dude	n.
Du*deen"	n.
Dudg"eon	n.
Dudg"eon	n.
Dudg"eon	a.
Dud"ish	a.
Duds	n. pl.
Due	a.
Due	adv.
Due	n.
Due	v. t.
Due"bill`	n.
Due"ful	a.
Du"el	n.
Du"el	v. i. & t.
Du"el*er	n.
Du"el*ing	n.
Du"el*ist	n.
Du*e"lo	n.
Du*e"<ntil/a	n.
Due"ness	n.
Du*en"na	n.
Du*et"	n.
Du`et*ti"no	n.
Du*et"to	n.
Duff	n.
Duff	n.
Duff	v. t.
Duf"fel	n.
Duffel bag	n.
Duf"fer	n.
Duf"fer	n.
Duf"fle	n.
Du*fren"ite	n.
Dug	n.
Dug	imp. & p. p.
Du*gong"	n.
Dug"out`	n.
Dug"way`	n.
Duke	n.
Duke	v. i.
duke	v. t.
Duke"dom	n.
Duke"ling	n.
Duke"ship	n.
Du*kho*bors"	n. pl.
Dul`ca*ma"ra	n.
Dul`ca*ma"rin	n.
Dulce	v. t.
Dulce"ness	n.
Dul"cet	a.
Dul`ci*an"a	n.
Dul`ci*fi*ca"tion	n.
Dul"ci*fied	a.
Dul*cif"lu*ous	a.
Dul"ci*fy	v. t.
Dul*cil"o*quy	n.
Dul"ci*mer	n.
Dul*cin"e*a	n.
Dul"ci*ness	n.
Dul*ci"no	n.
Dul"cite	n.
Dul"ci*tude	n.
Dul"co*rate	v. t.
Dul`co*ra"tion	n.
Du"ledge	n.
Du*li"a	n.
Dull	a.
Dull	v. t.
Dull	v. i.
Dull"ard	n.
Dull"-brained`	a.
Dull"-browed`	a.
Dull"er	n.
Dull"-eyed`	a.
Dull"head`	n.
Dull"ish	a.
Dull"ness	n.
Dull"-sight`ed	a.
Dull"some	a.
Dull"-wit`ted	a.
Dul"ly	adv.
Du*loc"ra*cy	n.
Dulse	n.
Dul"wil*ly	n.
Du"ly	adv.
Du"mal	a.
Dumb	a.
Dumb	v. t.
dumb"bell`	n.
dumbfound	v. t.
dumb` down"	v. t.
dumbfounded	adj.
dumbfounding	adj.
Dum"ble*dor`	n.
Dumb"ly	adv.
Dumb"ness	n.
Dumb"-wait`er	n.
Dum"dum bul"let	a.
Dum"found`	v. t.
dumfounded	adj.
dum"found`er	v. t.
dumfounding	adj.
Dum"ma*dor`	n.
Dum"mer*er	n.
Dum"my	a.
Dum"my	n.
Du`mose"	a.
Dump	n.
Dump	n.
Dump	v. t.
Dump	n.
dump	n.
Dump"age	n.
dumpcart	n.
dump cart	n.
dumped	adj.
dumper	n.
Dump"i*ness	n.
Dump"ish	a.
Dum"ple	v. t.
Dump"ling	n.
Dumps	n. pl.
dump" truck`	n.
Dump"y	a.
Dump"y lev"el	prop. n.
Dun	n.
Dun	v. t.
Dun	v. t. & i.
Dun	n.
Dun	a.
Dun"bird`	n.
Dunce	n.
Dunce"dom	n.
Dun"cer*y	n.
Dun"ci*cal	a.
Dun"ci*fy	v. t.
Dun"cish	a.
Dun"der	n.
Dun"der*head`	n.
Dun"der-head`ed	a.
Dun"der*pate`	n.
Dune	n.
Dun"fish	n.
Dung	n.
Dung	v. t.
Dung	v. i.
Dun`ga*ree"	n.
dun"geon	n.
Dun"geon	v. t.
Dung"fork`	n.
Dung"hill`	n.
Dung"meer`	n.
Dung"y	a.
Dung"yard`	n.
Dun"ker	prop. n.
Dunkerque	prop. n.
Dunkirk	prop. n.
Dun"lin	n.
Dun"nage	n.
Dun"ner	n.
Dun"nish	a.
dun*no"	phrase
Dun"nock	n.
Dun"ny	a.
Dunt	n.
Dunt"ed	a.
Dun"ter	n.
Du"o	n.
Du`o*dec`a*he"dral	a.
Du`o*de*cen"ni*al	a.
Du`o*dec"i*mal	a.
Du`o*dec"i*mal	n.
Du`o*dec"im*fid	a.
Du`o*dec"i*mo	a.
Du*o*dec"i*mo	n.
Du`o*dec"u*ple	a.
Du`o*de"nal	a.
Du`o*den"a*ry	a.
Du`o*de"num	n.
Du"o*graph	n.
Du`o*lit"er*al	a.
Duo"mo	n.
Du"o*tone	n.
Du"o*type	n.
Dup	v. t.
Dup"a*ble	a.
Dupe	n.
Dupe	v. t.
Dup"er	n.
Dup"er*y	n.
Du"pi*on	n.
Du"ple	a.
Du"plex	a.
Du"plex	v. t.
du"plex	n.
du"plex*er	n.
duplicability	n.
duplicable	adj.
du"pli*cate	a.
Du"pli*cate	n.
Du"pli*cate	v. t.
du`pli*ca"tion	n.
du"pli*ca*tive	a.
du"pli*ca*ture	n.
du*plic"i*tous	adj.
du*plic"i*ty	n.
Dup"per	n.
Dur	a.
Du"ra	n.
Du`ra*bil"i*ty	n.
Du"ra*ble	a.
Du"ra*ble*ness	n.
Du"ra*bly	adv.
Du"ral	a.
Duralumin	prop. n.
Du"ra ma"ter	n.
Dur"ance	n.
Dur"an*cy	n.
Dur"ant	n.
Du*ran"te	prep.
Du*ra"tion	n.
Dur"a*tive	a.
Dur"bar	n.
Dure	a.
Dure	v. i.
Dure"ful	a.
Dure"less	a.
Du"rene	n.
Du"ress	n.
Du*ress"	v. t.
Du*ress"or	n.
Dur"ga	n.
Dur"ham	n.
Du"ri*an	n.
Dur"ing	prep.
Du"ri*o	n.
Du"ri*ty	n.
Du*rom"e*ter	n.
Du"rous	a.
Dur"ra	n.
Durst	imp.
Du`ru*ku"li	n.
Du*ryl"ic	a.
Duse	n.
Dushanbe	prop. n.
Dusk	a.
Dusk	n.
Dusk	v. t.
Dusk	v. i.
Dusk"en	v. t.
Dusk"i*ly	adv.
Dusk"i*ness	n.
Dusk"ish	a.
Dusk"ness	n.
Dusk"y	a.
Dust	n.
Dust	v. t.
dustbin	n.
Dust"brush`	n.
dust"cart	n.
dust"cloth`	n.
dust"er	n.
dust"i*ness	n.
dust"less	a.
dust"man	n.
dust"mop	n.
dust"pan`	n.
dust"-point`	n.
dust" storm`	n.
dust"up	n.
dust"y	a.
Dutch	a.
Dutch	n.
Dutch"man	n.
Dutchman's breeches	n.
Dutchman's-pipe	n.
Du"te*ous	a.
Du"ti*a*ble	a.
Du"tied	a.
Du"ti*ful	a.
Du"ty	n.
Du*um"vir	n.
Du*um"vi*ral	a.
Du*um"vi*rate	n.
Dux	n.
Duy"ker*bok	n.
Du*young"	n.
D" valve`	n.
Dwale	n.
Dwang	n.
Dwarf	n.
Dwarf	v. t.
Dwarf	v. i.
Dwarf"ish	a.
Dwarf"ling	n.
Dwarf"y	a.
Dwaul	v. i.
Dwell	v. i.
Dwell	v. t.
Dwell"er	n.
Dwell"ing	n.
Dwelt	imp. & p. p.
Dwin"dle	v. i.
Dwin"dle	v. t.
Dwin"dle	n.
Dwin"dle*ment	n.
dwindling	adj.
dwindling	n.
Dwine	v. i.
Dy	n.
Dy"ad	n.
Dy"ad	a.
Dy*ad"ic	a.
Dy"aks	n. pl.
Dy"as	n.
Dyaus	prop. n.
Dyaus-pitar	prop. n.
dyb"buk	n.
Dye	v. t.
Dye	n.
Dye	n.
dyed	adj.
dyed-in-the-wool	adj.
Dye"house`	n.
Dye"ing	n.
Dy"er	n.
dyer's broom	n.
Dye"stuff`	n.
Dye"wood`	n.
Dy"ing	a.
Dy"ing	n.
Dy"ing*ly	adv.
Dy"ing*ness	n.
Dyke	n.
Dy*nac`ti*nom"e*ter	n.
Dy"nam	n.
Dy*nam"e*ter	n.
Dy`na*met"ric*al	a.
Dy*nam"ic	a.
dynamical	adj.
Dy*nam"ic*al*ly	adv.
dynamic RAM	n.
Dy*nam"ics	n.
Dy"na*mism	n.
Dy"na*mist	n.
Dy"na*mi`tard	n.
Dy"na*mite	n.
Dy"na*mi`ter	n.
Dy"na*mi`ting	n.
Dy"na*mi`tism	n.
Dy"na*mi*za`tion	n.
Dy`na*mo-e*lec"tric	a.
Dy*nam"o*graph	n.
Dy`na*mom"e*ter	n.
Dy`na*mo*met"ric	a.
Dy`na*mom"e*try	n.
Dy"nast	n.
Dy*nas"ta	n.
Dy*nas"tic	a.
Dy*nas"tic*al	a.
Dy*nas"ti*dan	n.
Dy"nas*ty	n.
Dyne	n.
Dys-	n.
Dys*cra"si*a	n.
Dys"cra*site	n.
Dys"cra*sy	n.
Dys`en*ter"ic	a.
Dys"en*ter*y	n.
dysfunctional	adj.
Dys`ge*nes"ic	a.
Dys*gen"e*sis	n.
dysgenic	adj.
dysgenics	n.
dyskinesia	n.
dyslectic	adj.
dys*lex"i*a	n.
dyslexic	adj.
Dys`lo*gis"tic	a.
Dys"lu*ite	n.
Dys"ly*sin	n.
Dys*men`or*rhe"a	n.
Dys"no*my	n.
Dys"o*dile	n.
Dys*pep"si*a	a.
Dys*pep"tic	n.
Dys*pep"tone	n.
Dys*pha"gi*a	n.
Dys*pho"ni*a	n.
Dys*pho"ri*a	n.
Dysp*n<oe/"a	n.
Dysp*no"ic	a.
Dys*pro"si*um	n.
Dys*te`le*ol"o*gy	n.
Dys*to"ci*a	n.
Dys"tome	a.
Dys*u"ri*a	n.
Dys*u"ric	a.
Dze"ren	n.
Dzig"ge*tai	n.
