L	n.
L	n.
L	a.
La	n.
La	interj.
laa"ger	n.
Laa"ger	v. t. & i.
Laas	n.
Lab	v. i.
lab	n.
lab	a.
Lab"a*dist	n.
La`bar`raque's" so*lu"tion	n.
Lab"a*rum	n.
Lab"da*num	n.
Lab`e*fac"tion	n.
Lab"e*fy	v. t.
La"bel	n.
La"bel	v. t.
La"bel*er	n.
La*bel"lum	n.
La"bent	a.
La"bi*a	n. pl.
La"bi*al	a.
La"bi*al	n.
La"bi*al*ism	n.
La`bi*al*i*za"tion	n.
La"bi*al*ize	v. t.
La"bi*al*ly	adv.
La"bi*ate	v. t.
La"bi*ate	a.
La"bi*ate	n.
La"bi*a`ted	a.
La`bi*a`ti*flo"ral	a.
Lab`i*dom"e*ter	n.
La"bile	a.
La*bil"i*ty	n.
La*bim"e*ter	n.
La`bi*o*den"tal	a.
La`bi*o*na"sal	a.
La"bi*o*plas`ty	n.
La"bi*ose`	a.
La"bi*palp	n.
La`bi*pal"pus	n.
La"bi*um	n.
Lab"lab	n.
La"bor	n.
La"bor	v. i.
La"bor	v. t.
Lab"o*rant	n.
Lab"o*ra*to*ry	n.
Labor Day	a.
La"bored*ly	adv.
La"bor*er	n.
La"bor*ing	a.
La*bo"ri*ous	a.
La"bor*less	a.
La"bor*ous	a.
La"bor-sav`ing	a.
La"bor*some	a.
la"bour	n.
laboured	adj.
labourer	n.
labourious	adj.
Labourite	n.
Lab`ra*dor"	n.
Lab"ra*dor`ite	n.
La"bras	n. pl.
La"bret	n.
La"broid	a.
La"brose`	a.
La"brum	n.
La"brus	n.
La*bur`nic	a.
La*bur`nine	n.
La*bur"num	n.
Lab"y*rinth	n.
Lab`y*rin"thal	a.
Lab`y*rin"thi*an	a.
Lab`y*rin"thi*branch	a.
Lab`y*rin"thic	a.
Lab`y*rin"thi*ci	n. pl.
Lab`y*rin"thi*form	a.
Lab`y*rin"thine	a.
Lab`y*rin"tho*don	n.
Lab`y*rin"tho*dont	a.
Lab`y*rin`tho*don"ta	prop. n. pl.
Lac	n.
Lac	n.
Lac"cic	a.
Lac"cin	n.
Lac"co*lite	n.
Lace	n.
Lace	v. t.
Lace	v. i.
lacebark	n.
Lace"-bark`	n.
Laced	a.
Lac`e*d<ae/*mo"ni*an	a.
lace into	v. t.
Lace"man	n.
Lac"er*a*ble	a.
Lac"er*ate	v. t.
Lac"er*ate	p. a.
lacerated	adj.
Lac`er*a"tion	n.
Lac"er*a*tive	a.
La"cert	n.
La*cer"ta	n.
La*cer"ta	n.
La*cer"tian	a.
lacertid	n.
Lacertidae	n.
Lac`er*til"i*a	n. pl.
Lac`er*til"i*an	a. & n.
La*cer"ti*loid	a.
La*cer"tine	a.
La*cer"tus	n.
Lace"wing`	n.
Lace"-winged`	a.
Lach"es	n.
Lach"ry*ma*ble	a.
Lach"ry*m<ae/ Chris"ti	n.
Lach"ry*mal	a.
Lach"ry*mal	n.
Lach"ry*mals	n. pl.
Lach"ry*ma*ry	a.
Lach"ry*mate	v. i.
Lach`ry*ma"tion	n.
lachrymator	n.
Lach"ry*ma*to*ry	n.
lachrymatory	adj.
Lach"ry*mi*form	a.
Lach"ry*mose`	a.
La"cing	n.
La*cin"i*a	n.
La*cin"i*ate	a.
La*cin"i*o*late	a.
La*cin"u*la	n.
Lack	n.
Lack	v. t.
Lack	v. i.
Lack	interj.
lack`a*dai"si*cal	a.
Lack"a*dai`sy	interj.
Lack"a*dai`sy	a.
Lack"a*day`	interj.
Lack"brain`	n.
Lack"er	n.
Lack"er	n. & v.
Lack"ey	n.
Lack"ey	v. t.
Lack"ey	v. i.
Lack"lus`ter	n.
Lack"lus`ter	a.
Lac"mus	n.
La*co"ni*an	a.
La*con"ic	a.
La*con"ic	n.
La*con"ic*al	a.
La*con"ic*al*ly	adv.
La*con"i*cism	n.
Lac"o*nism	n.
Lac"o*nize	v. i.
Lac"quer	n.
Lac"quer	v. t.
Lac"quer*er	n.
Lac"quer*ing	n.
lacrimation	n.
lacrimator	n.
lacrimatory	adj.
La`cri*mo"so	a.
La*crosse"	n.
Lac"ry*mal	n. & a.
Lac"ry*ma*ry	n.
Lac"tam	n.
Lac*tam"ic	a.
Lac*tam"ide	n.
Lac"tant	a.
Lac"ta*rene	n.
Lac"ta*ry	a.
Lac"ta*ry	n.
Lac"tate	n.
lactating	adj.
Lac*ta"tion	n.
Lac"te*al	a.
Lac"te*al	n.
Lac"te*al*ly	adv.
Lac"te*an	a.
Lac"te*ous	a.
Lac"te*ous*ly	adv.
Lac*tes"cence	n.
Lac*tes"cent	a.
Lac"tic	a.
Lac"tide	n.
Lac*tif"er*ous	a.
Lac*tif"ic	a.
Lac"ti*fuge	n.
Lac"tim	n.
Lac*tim"ide	n.
Lac"tin	n.
Lac`to*a*bu"min	n.
Lac`to*bu`ty*rom"e*ter	n.
Lac`to*den*sim"e*ter	n.
Lac*tom"e*ter	n.
Lac"tone	n.
Lac*ton"ic	a.
Lac*ton"ic	a.
Lac`to*pro"te*in	n.
Lac"to*ry	a.
Lac"to*scope	n.
lac"tose`	n.
lac"tose` in*tol"er*ance	n.
Lac*tu"ca	n.
Lac`tu*ca"ri*um	n.
Lac*tu"cic	a.
Lac*tu"cin	n.
Lac*tu"cone	n.
Lac`tu*ram"ic	a.
Lac"tyl	n.
La*cu"na	n.
La*cu"nal	a.
La*cu"nar	n.
La*cune"	n.
Lac"u*nose`	a.
La*cus"tral	a.
Lac"work`	n.
Lad	p. p.
Lad	n.
Lad"a*num	n.
Lad"de	imp.
Lad"der	n.
ladder-back	n.
ladder-backed	n.
ladder company	n.
ladder-proof	adj.
Lad"die	n.
Lade	v. t.
Lade	v. i.
Lade	n.
Lade"man	n.
Lad"en	p. & a.
La"died	a.
La"dies' ear`drops`	n.
La"di*fy	v. t.
La*din"	n.
Lad"ing	n.
La*di"no	n.
La*di"no	n.
Lad"kin	n.
La"dle	n.
La"dle	v. t.
La"dle*ful	n.
La*drone"	n.
La"dy	n.
La"dy	a.
ladybeetle	n.
La"dy*bird`	n.
La"dy*bug`	n.
La"dy*clock`	n.
La"dy` Day`	n.
La"dy*fish`	n.
La"dy*hood	n.
lady-in-waiting	n.
La"dy-kill`er	n.
La"dy-kill`ing	n.
La"dy*kin	n.
La"dy*like`	a.
La"dy*like`ness	n.
La"dy*love`	n.
lady-of-the-night	n.
La"dy's bed"straw`	n.
La"dy's cloth`	n.
La"dy's fin"ger	n.
La"dy's hair"	n.
La"dy*ship	n.
La"dy's la"ces	n.
lady-slipper	n.
La"dy's look"ing-glass`	n.
La"dy's man"tle	n.
La"dy's smock"	n.
La"dy's thim"ble	n.
La"dy's thumb"	n.
La"dy's tra"ces	n.
L<ae/"laps	n.
Laem"mer*gey`er	n.
L<ae/*mod"i*pod	n.
L<ae/`mo*dip"o*da	n. pl.
L<ae/`mo*dip"o*dous	a.
L<ae/*te"re Sun"day	n.
L<ae/v"i*gate	a.
L<ae/"vo-	pref.
L<ae/"vo*ro"ta*to*ry	a.
L<ae/v"u*lose`	n.
La`fa`yette"	n.
Laft	p. p.
Laf"te	imp.
Lag	a.
Lag	n.
Lag	v. i.
Lag	v. t.
Lag	n.
Lag	v. t.
La"gan	n. & v.
La*gar"to	n.
La*ge"na	n.
La*ge"ni*an	a.
La*ge"ni*form	a.
Lagenophera	prop. n.
La"ger	n.
La"ger beer`	n.
La"ger wine`	n.
Lag"gard	a.
Lag"gard	n.
Lag"ger	n.
Lag"ging	n.
Lag"ging*ly	adv.
Lag"ly	adv.
La*gniappe	n.
lag"o*morph	n.
Lag`o*mor"pha	prop. n. pl.
la*goon"	n.
Lag`oph*thal"mi*a	n.
La*go"pous	a.
Lagorchestes	prop. n.
Lagostomus	prop. n.
Lagothrix	prop. n.
Lag"thing	n.
La*gune"	n.
La"ic	a.
La"ic	n.
La"ic*al"i*ty	n.
La"ic*al*ly	adv.
Laid	imp. & p. p.
Laid"ly	a.
Lain	p. p.
Lain"ere	n.
Lair	n.
Laird	n.
Laird"ship	n.
La"ism	n.
Lais`sez" faire"	n.
La"i*ty	n.
La*ka"o	n.
Lake	n.
Lake	n.
Lake	v. i.
Lake	n.
Lake"-dwell`er	n.
lakefront	n.
Lake"let	n.
Lak"er	n.
lakeshore	n.
lakeside	n.
Lake"weed`	n.
Lakh	n.
La"kin	n.
Lak"ke	n. & v.
Lak"y	a.
Lak"y	a.
Lal*la"tion	n.
La"lo	n.
Lam	v. t.
La"ma	n.
La"ma	n.
La"ma*ic	a.
La"ma*ism	n.
La"ma*ist	n.
La`ma*is"tic	a.
La*man"tin	n.
La*marck"i*an	a.
La*marck"i*an*ism	n.
La"marck"ism	n.
La"ma*ser*y	n.
Lamb	n.
Lamb	v. i.
Lamb"ale`	n.
lam*bast"	v. t.
Lam*baste"	v. t.
Lam"ba*tive	a.
Lam"ba*tive	n.
Lamb"da	n.
Lamb"da*cism	n.
Lamb"doid	a.
Lamb*doid"al	a.
Lam"bent	a.
Lambertia	n.
Lam"bert pine`	n.
Lambis	n.
Lamb"kill`	n.
Lamb"kin	n.
Lamb"like	a.
Lam"boys	n. pl.
Lam"bre*quin	n.
Lamb"skin`	n.
Lamb"skin`net"	n.
Lamb's-quar"ters	n.
Lam*doid"al	a.
Lame	a.
Lame	v. t.
lamedh	n.
Lam"el	n.
La*mel"la	n.
Lam"el*lar	a.
Lam"el*la*ry	a.
Lam"el*late	a.
La*mel"li*branch	n.
La*mel`li*bran"chi*a	n. pl.
Lam`el*li*bran"chi*ate	a.
La*mel"li*corn	a.
La*mel`li*cor"ni*a	n. pl.
Lam`el*lif"er*ous	a.
La*mel"li*form	a.
Lam`el*li*ros"tral	a.
La*mel`li*ros"tres	n. pl.
Lam"el*lose`	a.
Lame"ly	adv.
Lame"ness	n.
La*ment"	v. i.
La*ment"	v. t.
La*ment"	n.
Lam"en*ta*ble	a.
Lam`en*ta"tion	n.
La*ment"ed	a.
La*ment"er	n.
La*men"tin	n.
La*ment"ing	n.
La*ment"ing*ly	adv.
Lames	n. pl.
La*met"ta	n.
La"mi*a	n.
Lam"i*na	n.
Lam`i*na*bil"i*ty	n.
Lam"i*na*ble	a.
Lam"i*nar	a.
Lam`i*na"ri*a	n.
Lam`i*na"ri*an	a.
Lam"i*na*rite	n.
Lam"i*na*ry	a.
Lam"i*nate	a.
Lam"i*nate	v. t.
Lam"i*nate	v. i.
lam"i*na`ted	a.
Lam"i*na`ting	a.
Lam`i*na"tion	n.
Lam`i*nif"er*ous	a.
Lam`i*ni*plan"tar	a.
Lam`i*ni"tis	n.
Lam"ish	a.
Lamm	v. t.
Lam"mas	n.
Lam"mer*geir	n.
Lamnidae	n.
Lam*nun"gui*a	n. pl.
Lamp	n.
Lamp	n.
Lam"pad	n.
Lam"pa*dist	n.
Lam"pa*drome	n.
Lam"pas	n.
Lam"pate	n.
Lamp"black`	n.
Lam"per eel`	n.
Lam"pern	n.
Lam"pers	n.
Lam"pic	a.
Lamp"ing	a.
Lamp"less	a.
Lamp"light`	n.
Lamp"light`er	n.
lamplit	adj.
Lam*poon"	n.
Lam*poon"	v. t.
Lam*poon"er	n.
Lam*poon"ry	n.
Lamp"-post`	n.
Lam"prel	n.
Lam"prey	n.
Lam"pron	n.
lampshade	n.
lampshell	n.
Lampyridae	prop. n.
Lam*py"rine	n.
Lam*py"ris	n.
LAN	n.
Lanai	n.
Lan"ark*ite	n.
La"na*ry	n.
La"nate	n.
Lancaster	prop. n.
Lan`cas*te"ri*an	prop. a.
Lancastrian	prop. a.
Lancastrian	prop. n.
Lance	n.
Lance	v. t.
lance" cor`por*al	n.
Lance" fish`	n.
Lance"gay`	n.
Lance"let	n.
Lance"ly	a.
Lan"ce*o*lar	a.
Lan"ce*o*late	a.
Lance`pe*sade"	n.
Lan"cer	n.
lancers	n.
Lan"cet	n.
lan"cet*fish`	n.
Lance"wood`	n.
Lanch	v. t.
Lan*cif"er*ous	a.
Lan"ci*form	a.
Lan"ci*nate	v. t.
Lan"ci*na`ting	a.
Lan`ci*na"tion	n.
Land	n.
Land	n.
Land	v. t.
Land	v. i.
Lan"dam*man	n.
Lan"dau	n.
Lan`dau*let"	n.
Land"drost`	n.
Land"ed	a.
Land"er	n.
Land"fall	n.
Land"flood`	n.
Land"grave`	n.
Land*gra"vi*ate	n.
Land"gra*vine	n.
Land"hold`er	n.
landholding	n.
Land"ing	a.
Land"ing	n.
land"ing gear`	n.
land"ing strip`	n.
land"la`dy	n.
Land League	n.
Land"leap`er	n.
Land"less	a.
Land"lock`	v. t.
Land"locked`	a.
Land"lo`per	n.
Land"lord`	n.
Land"lord`ism	n.
Land"lord`ry	n.
Land"loup`er	n.
Land"loup`ing	a.
Land"lub`ber	n.
landlubberly	adj.
Land"man	n.
Land"mark`	n.
landmass	n.
Land of Steady Habits	prop. n.
Land"own`er	n.
Land"own`ing	n.
Land"-poor`	a.
Land"reeve`	n.
Land"scape	n.
landscaping	n.
Land"scap`ist	n.
Land"skip	n.
Land"slide`	n.
Lands"man	n.
Lands"thing`	n.
Land"storm`	n.
Land"streight`	n.
Land"sturm`	n.
Land"tag`	n.
Land"wait`er	n.
Land"ward	adv. & a.
Land"wehr`	n.
Lane	a.
Lane	n.
Lang	a. & adv.
Lan"ga*ha	n.
Lan`ga*rey"	n.
Lan"gate	n.
Lang"dak`	n.
Lan"grage	n.
Lan"gret	n.
Lan"gridge	n.
Lang`syne"	adv. & n.
Lang`ter*a*loo"	n.
Lan"guage	n.
Lan"guage	v. t.
Lan"guaged	a.
Lan"guage*less	a.
Langued	a.
Langue` d'oc"	n.
Langue` d'o<ium/l"	adv.
Lan"guet	n.
Lan"guid	a.
Lan"guish	v. i.
Lan"guish	v. i.
Lan"guish	n.
Lan"guish*er	n.
Lan"guish*ing	a.
Lan"guish*ing*ly	adv.
Lan"guish*ment	n.
Lan"guish*ness	n.
Lan"guor	n.
Lan"guor*ous	a.
Lan"gure	v. i.
Lan"gya	n.
Lan"iard	n.
La`ni*ar"i*form	a.
La"ni*a*ry	a.
La"ni*a*ry	n.
La"ni*ate	v. t.
La`ni*a"tion	n.
Lan"ier	n.
La*nif"er*ous	n.
La*nif"i*cal	a.
Lan"i*fice	n.
La*nig"er*ous	a.
La"ni*oid	a.
Lank	a.
Lank	v. i. & t.
Lank"i*ness	n.
Lank"ly	adv.
Lank"ness	n.
Lank"y	a.
Lan"ner	n. f.
Lan"o*lin	n.
lansa	n.
Lan"seh	n.
Lans"que*net	n.
Lant	n.
Lant	n.
Lant	n.
Lan*ta"ni*um	n.
Lan`ta*nu"ric	a.
Lan"ter*loo`	n.
Lan"tern	n.
Lan"tern	v. t.
lanternfish	n.
lanternfly	n.
Lan"tern-jawed`	a.
lanthanide	n.
Lan"tha*nite	n.
lanthanon	n.
Lanthanotidae	n.
Lanthanotus	n.
Lan"tha*num	n.
Lan"tho*pine	n.
Lan"thorn	n.
La*nu"gi*nose`	a.
La*nu"go	n.
Lan"yard	n.
Lan"yer	n.
La*oc"o*<oum/n	prop. n.
La*od`i*ce"an	a.
Laos	prop. n.
Laotian	prop. n.
Laotian	prop. a.
Lao-tse	prop. n.
Lap	n.
Lap	v. t.
Lap	v. t.
Lap	v. i.
Lap	v. i.
Lap	v. t.
Lap	n.
Lap"a*ro*cele`	n.
laparoscope	n.
laparoscopy	n.
Lap`a*rot"o*my	n.
Lap"board`	n.
Lap"dog`	n.
La*pel"	n.
La*pelled"	a.
Lap"ful	n.
Lap"i*cide	n.
Lap`i*da"ri*an	a.
Lap`i*da"ri*ous	a.
Lap"i*da*ry	n.
Lap"i*da*ry	a.
Lap"i*date	v. t.
Lap`i*da"tion	n.
La*pid"e*ous	a.
Lap`i*des"cence	n.
Lap`i*des"cent	a.
Lap"i*des"cent	n.
Lap`i*dif"ic	a.
La*pid`i*fi*ca"tion	n.
La*pid"i*fy	v. t.
La*pid"i*fy	v. i.
Lap"i*dist	n.
Lap"il*la"tion	n.
La*pil"li	n. pl.
La"pis	n.
La"pis laz"u*li	n.
Lap"-joint`ed	a.
Lap"land*er	n.
Lap"land*ish	a.
Lap"ling	n.
Lapp	n.
Lap*pa"ceous	a.
Lap"per	n.
Lap"pet	n.
Lap"pet	v. t.
Lap"pic	a.
Lap"ping	n.
Lap"pish	a.
Lap*po"ni*an	a.
Lapps	n. pl.
Laps"a*ble	a.
Lapse	n.
Lapse	v. i.
Lapse	v. t.
Lapsed	a.
Laps"i*ble	a.
Lap"sid`ed	a.
Lap"stone`	n.
Lap"streak`	a.
lap up	v. t.
La*pu"tan	a.
Lap"-weld`ed	a.
Lap"wing`	n.
Lap"work`	n.
Laq"uay	n.
La"que*ar	n.
Laq"ue*a*ry	a.
Lar	n.
Lar	n.
Lar"a*mie group`	n.
Lar"board`	n.
Lar"board`	a.
Lar"ce*ner	n.
Lar"ce*nous	a.
Lar"ce*ny	n.
Larch	n.
Larch"en	a.
Lard	n.
Lard	v. t.
Lard	v. i.
Lar`da*ce"in	n.
Lar*da"ceous	a.
Lard"er	n.
Lard"er*er	n.
Lard"er*y	n.
Lar"don	n.
Lard"ry	n.
Lard"y	a.
Lare	n.
Lare	n.
Lare	v. t.
La"res	n. pl.
Large	a.
Large	adv.
Large	n.
Large"-a`cred	a.
Large"-hand`ed	a.
Large"-heart`ed	a.
Large"ly	adv.
Large"ness	n.
large-scale	adj.
Lar"gess	n.
largest	adj.
Lar"get	n.
Lar*ghet"to	a. & adv.
Lar*gif"i*cal	a.
Lar*gif"lu*ous	a.
Lar*gil"o*quent	a.
Lar"gish	a.
Lar*gi"tion	a. & adv.
Lari	prop. n.
Lar"i*at	n.
Lar"i*at	v. t.
Laridae	prop. n.
La"rine	a.
Larix	prop. n.
Lar`ix*in"ic	a.
Lark	n.
Lark	v. i.
Lark	n.
Lark	v. i.
Lark"-col`ored	a.
Lark"er	n.
Lark's"-heel`	n.
Lark"spur	n.
Lar"mi*er	n.
La"roid	a.
Lar"ri*kin	n.
Lar"rup	v. t.
Lar"ry	n.
Lar"um	n.
Lar"va	n.
Larvacea	prop. n.
lar"val	a.
Lar*va"li*a	prop. n. pl.
Lar"vate	a.
Lar"va*ted	a.
Larve	n.
Lar"vi*form	a.
Lar*vip"a*rous	a.
La"ry	n.
Lar`yn*ge"al	a.
Lar`yn*ge"an	a.
Lar`yn*gec"to*my	n.
Lar`yn*gis"mus	n.
Lar`yn*gi"tis	n.
La*ryn"go*graph	n.
La*ryn`go*log"ic*al	a.
Lar`yn*gol"o*gist	n.
Lar`yn*gol"o*gy	n.
Lar`yn*goph"o*ny	n.
La*ryn"go*scope	n.
La*ryn`go*scop"ic	a.
Lar`yn*gos"co*pist	n.
Lar`yn*gos"co*py	n.
La*ryn"go*tome	n.
Lar`yn*got"o*my	n.
La*ryn`go*tra"che*al	a.
la*ryn`go*tra`che*ot"o*my	n.
lar"ynx	n.
Las	n.
Las	a. & adv.
lasagna	n.
Las"car	n.
Las"ci*ous	a.
las*civ"i*en*cy	n.
Las*civ"i*ent	a.
Las*civ"i*ous	a.
las*civ"i*ous*ness	n.
lase	v. i.
laser	n.
laser beam	n.
laser disk	n.
laser light	n.
laser printer	n.
laser surgery	n.
La"ser*wort`	n.
Lash	n.
Lash	v. t.
Lash	v. i.
Lash	v. t.
Lash"er	n.
Lash"er	n.
Lash"ing	n.
Lash"ing	n.
lasiocampid	n.
Lasiocampidae	n.
Lask	n.
Las"ket	n.
Lass	n.
Lasse	a. & adv.
Las"sie	n.
Las"si*tude	n.
Lass"lorn`	a.
Lass"o	n.
Las"so	v. t.
Last	3d pers. sing. pres.
Last	a.
Last	adv.
Last	v. i.
Last	n.
Last	v. t.
Last	n.
Last"age	n.
Last"e	imp.
Last"er	n.
Last"er*y	n.
Lasthenia	prop. n.
Last"ing	a.
Last"ing	n.
Last"ing*ly	adv.
lastingness	n.
Last"ly	adv.
Lastreopsis	prop. n.
Lat	v. t.
La"ta	n.
Lat`a*ki"a	n.
Latch	v. t.
Latch	n.
Latch	v. t.
latched	adj.
Latch"et	n.
Latch"ing	n.
Latch"key`	n.
latch"key` child	n.
Latch"string`	n.
Late	a.
Late	adv.
latecomer	n.
Lat"ed	a.
la*teen"	a.
lateen sail	n.
lateen-rig	n.
lateen-rigged	adj.
Late"ly	adv.
La"tence	n.
La"ten*cy	n.
Late"ness	n.
La"tent	a.
La"tent*ly	adv.
La"ter	n.
Lat"er	a.
Lat"er*ad	adv.
Lat"er*al	a.
lat"er*al	n.
lat"er*al	v. t. & i.
Lat`er*al"i*ty	n.
Lat"er*al*ly	adv.
Lat"er*an	n.
Lat"ered	a.
Lat`er*i*fo"li*ous	a.
Lat"er*ite	n.
Lat`er*it"ic	a.
Lat"er*i"tious	a.
La"tes	n.
La*tes"cence	n.
La*tes"cent	a.
Late"wake`	n.
Late"ward	a. & adv.
La"tex	n.
Lath	n.
Lath	v. t.
Lathe	n.
Lathe	n.
lathee	n.
Lath"er	n.
Lath"er	v. t.
Lath"er	v. i.
Lath"er	v. t.
Lathe"reeve`	n.
Lath"ing	n.
Lath"-shaped`	a.
Lath"work`	n.
Lath"y	a.
La"tian	a.
La*tib"u*lize	v. i.
La*tib"u*lum	n.
Lat`i*cif"er*ous	a.
Lat"i*clave	n.
Lat`i*cos"tate	a.
Lat`i*den"tate	a.
Lat`i*fo"li*ate	a.
La"ti*go	n.
La"ti*go hal"ter	n.
Lat"i*mer	n.
Latimeria	prop. n.
Latimeridae	prop. n.
Lat"in	a.
Lat"in	n.
Lat"in	v. t.
Lat"in A*me"ri*ca	prop. n.
Lat"in A*me"ri*can	prop. a.
Lat"in A*me"ri*can	prop. n.
latinate	adj.
Latinise	v. t.
Lat"in*ism	n.
Lat"in*ist	n.
Lat`in*is"tic	a.
La*tin"i*tas`ter	n.
La*tin"i*ty	n.
Lat`in*i*za"tion	n.
Lat"in*ize	v. t.
Lat"in*ize	v. i.
Lat"in*ly	adv.
La"tion	n.
Lat`i*ros"tral	a.
Lat`i*ros"tres	n. pl.
Lat"ish	a.
Lat`i*ster"nal	a.
Lat"i*tan*cy	n.
Lat"i*tant	a.
Lat"i*tat	n.
Lat`i*ta"tion	n.
Lat"i*tude	n.
Lat`i*tu"di*nal	a.
Lat`i*tu`di*na"ri*an	a.
Lat`i*tu`di*na"ri*an	n.
Lat`i*tu`di*na"ri*an*ism	n.
Lat`i*tu"di*nous	a.
Lat"on	n.
La"trant	a.
La"trate	v. i.
La*tra"tion	n.
La*treu"tic*al	a.
La*tri"a	n.
La*trine"	n.
Lat"ro*cin`y	n.
lat"te	n.
Lat"ten	n.
Lat"ter	a.
Lat"ter*day`	a.
Lat"ter-day` saint"	n.
Lat"ter*kin	n.
Lat"ter*ly	adv.
Lat"ter*math	n.
Lat"tice	n.
Lat"tice	v. i.
latticed	adj.
latticelike	adj.
Lat"tice*work`	n.
Lat"ti*cing	n.
La"tus rec"tum	n.
Laud	n.
Laud	v. i.
Laud`a*bil"i*ty	n.
Laud"a*ble	a.
Laud"a*ble*ness	n.
Laud"a*bly	adv.
Lau"da*nine	n.
Lau"da*num	n.
Lau*da"tion	n.
Laud"a*tive	a.
Laud"a*tive	n.
Lau*da"tor	n.
Laud"a*to*ry	a.
Laud"er	n.
Laugh	v. i.
Laugh	v. t.
Laugh	n.
Laugh"a*ble	a.
Laugh"er	n.
Laugh"ing	a. & n.
Laugh"ing*ly	adv.
Laugh"ing*stock`	n.
Laugh"some	a.
Laugh"ter	n.
Laugh"ter*less	a.
Laugh"wor`thy	a.
Lau"mont*ite	n.
Launce	n.
Launce	n.
Launce	n.
Launce"gaye`	n.
Launch	v. i.
Launch	v. i.
Launch	n.
launcher	n.
launching	n.
launchpad	n.
Laund	n.
Laun"der	n.
Laun"der	v. t.
Laun"der*er	n.
Laun"der*ing	n.
Laun"dress	n.
Laun"dress	v. i.
Laun"dry	n.
Laun"dry*man	n.
Lau"ra	n.
Lau*ra"ceous	a.
Lau"rate	n.
Lau"re*ate	a.
Lau"re*ate	n.
Lau"re*ate	v. i.
Lau"re*ate*ship	n.
Lau`re*a"tion	n.
Lau"rel	n.
Lau"reled	a.
lau"rels	n. pl.
laurel-tree	n.
Lau*ren"tian	a.
Lau"rer	n.
Lau"res*tine	n.
Lau"ric	a.
Lauric acid	a.
Lau"rin	n.
Lau"ri*nol	n.
Lau"ri*ol	n.
Lau"rite	n.
Lau"rone	n.
Lau"rus	n.
Laus	a.
Laut"ver*schie`bung	n.
lav	n.
La"va	n.
la`va*la"va	n.
la`va`liere"	n.
la`va`liere" mic"ro*phone	n.
Lavandula	n.
Lav"a*ret	n.
Lavatera	n.
La*vat"ic	a.
La*va"tion	n.
Lav"a*to*ry	a.
Lav"a*to*ry	n.
Lav"a*ture	n.
Lave	v. t.
Lave	v. i.
Lave	v. t.
Lave	n.
Lave"-eared`	a.
La*veer"	v. i.
Lave"ment	n.
Lav"en*der	n.
Lav"er	n.
Lav"er	n.
La"ver	n.
La"ver*ock	n.
La"vic	a.
Lav"ish	a.
Lav"ish	v. t.
Lav"ish*er	n.
Lav"ish*ly	adv.
Lav"ish*ment	n.
Lav"ish*ness	n.
La*v<oe/"si*um	n.
La*volt"	n.
La*vol`ta*teer"	n.
Lav"our	n.
La"vrock	n.
Law	n.
Law	v. t.
Law	interj.
Law"-a*bid`ing	a.
law-breaking	n.
law"break`er	n.
Lawe	v. t.
Law"er	n.
Law"ful	a.
lawfully-begotten	adj.
Law"giv`er	n.
Law"giv`ing	a.
Law"ing	n.
Law"ing	n.
Law"less	a.
Law"mak`er	n.
law-makers	n. pl.
Law"mak`ing	a.
Law"mon`ger	n.
Lawn	n.
Lawn	n.
Lawnd	n.
Lawn"y	a.
Lawn"y	a.
lawrencium	n.
Laws	n.
Law*so"ni*a	n.
Law"suit`	n.
Law"yer	n.
lawyerbush	n.
Law"yer*like`	a.
Lax	a.
Lax	n.
Lax*a"tion	n.
Lax"a*tive	a.
Lax"a*tive*ness	n.
Lax*a"tor	n.
Lax"i*ty	n.
Lax"ly	adv.
Lax"ness	n.
Lay	imp.
Lay	a.
Lay	n.
Lay	n.
Lay	n.
Lay	a.
Lay	v. t.
Lay	v. i.
Lay	n.
layabout	n.
layby	n.
Lay"er	n.
layered	adj.
Lay"er*ing	n.
Lay*ette"	n.
Layia	n.
Lay"ing	n.
Lay"land`	n.
Lay"man	n.
Lay"ner	n.
layperson	n.
Lay" read"er	n.
Lay"ship	n.
Lay"stall`	n.
La"zar	n.
Laz`a*ret"	n.
Lazaret fever	n.
La"zar*like`	a.
Laz`a*ro"ni	n. pl.
La"zar*wort`	n.
Laze	v. i.
Laze	v. t.
La"zi*ly	adv.
La"zi*ness	n.
Laz"u*li	n.
Laz"u*lite	n.
La"zy	a.
La"zy*back`	n.
La"zy*bones`	n.
Laz`za*ro"ni	n. pl.
lcm	n.
Ld.	n.
LDL	n.
Lea	n.
Lea	n.
Leach	n.
Leach	n.
Leach	v. t.
Leach	v. i.
Leach	n.
Leach"y	a.
Lead	n.
Lead	v. t.
Lead	v. t.
Lead	v. i.
Lead	n.
Lead"ed	a.
Lead"en	a.
Lead"er	n.
leaderless	adj.
leaders	n.
Lead"er*ship	n.
lead-free	adj.
Lead"hill*ite	n.
lead-in	n.
Lead"ing	a.
Lead"ing	n.
Lead"ing edge	n.
Lead"man	n.
Leads"man	n.
leadplant	n.
lead to	v. t.
Lead"wort`	n.
Lead"y	a.
Leaf	n.
Leaf	v. i.
Leaf"age	n.
Leaf"cup`	n.
leaf cutter	n.
Leafed	a.
Leaf"et	n.
Leaf"-foot`ed	a.
leaf-hopper	n.
Leaf"i*ness	n.
Leaf"less	a.
Leaf"let	n.
Leaf"-nosed`	n.
leafroller	n.
Leaf"stalk`	n.
Leaf"y	a.
League	n.
League	n.
League	v. i.
League	v. t.
Lea"guer	n.
Lea"guer	v. t.
Lea"guer*er	n.
Leak	n.
Leak	a.
Leak	v. i.
Leak"age	n.
Leak"i*ness	n.
leak"ing	adj.
leak"proof`	adj.
Leak"y	a.
Leal	a.
Leam	n. & v. i.
Leam	n.
Leam"er	n.
Lean	v. t.
Lean	v. i.
Lean	v. t.
Lean	a.
Lean	n.
Lean"-faced`	a.
Lean"ing	n.
Lean"ly	adv.
Lean"ness	n.
Lean"-to`	a.
Lean"-to`	n.
Lean"-wit`ted	a.
Lean"y	a.
Leap	n.
Leap	v. i.
Leap	v. t.
Leap	n.
Leap"er	n.
Leap"er	n.
Leap"frog`	n.
Leap"ful	n.
Leap"ing	a. & n.
Leap"ing*ly	adv.
Leap" year`	n.
Lear	v. t.
Lear	n.
Lear	a.
Lear	n.
Learn	v. t.
Learn	v. i.
Learn"a*ble	a.
Learn"ed	a.
learn"ed*ness	n.
Learn"er	n.
Learn"ing	n.
Leas"a*ble	a.
Lease	v. i.
Lease	v. t.
Lease	n.
Lease"hold`	a.
Lease"hold`	n.
Lease"hold`er	n.
lease-lend	n.
Leas"er	n.
Leas"er	n.
Leash	n.
Leash	v. t.
Leas"ing	n.
Lea"sow	n.
Least	a.
Least	adv.
Least	conj.
Least"ways`	adv.
Lea"sy	a.
Leat	n.
Leath"er	n.
Leath"er	v. t.
leath"er	a.
Leath"er*back`	n.
Leath"er*et	n.
leatherfish	n.
Leath"er*head`	n.
leatherjack	n.
leatherjacket	n.
leatherleaf	n.
leatherlike	adj.
Leath"ern	a.
leath"er*neck`	n.
Leath"er*wood`	n.
leatherwork	n.
Leath"er*y	a.
Leave	v. i.
Leave	v. t.
Leave	n.
Leave	v. t.
Leave	v. i.
Leaved	a.
Leave"less	a.
Leav"en	n.
Leav"en	v. t.
leavened	adj.
Leav"en*ing	n.
Leav"en*ous	a.
Leav"er	n.
Leaves	n.
Leave"-tak`ing	n.
Leav"i*ness	n.
Leav"ings	n. pl.
Leav"y	a.
Leb"an	n.
Le*ca"ma	n.
Le*can"o*man`cy	n.
Lec`a*no"ric	a.
Lec`a*no"rin	n.
Lech	v. t.
lech	n. & v. i.
Lechanorales	n.
lechatelierite	n.
Le*che"	n.
Lech"er	n.
Lech"er	v. i.
Lech"er*er	n.
Lech"er*ous	a.
lech"er*ous*ness	n.
Lech"er*y	n.
Lec"i*thin	n.
Lec"tern	n.
Lec*ti"ca	n.
Lec"tion	n.
Lec"tion*a*ry	n.
Lec"tor	n.
Lec"tu*al	a.
Lec"ture	n.
Lec"ture	v. t.
Lec"ture	v. i.
Lec"tur*er	n.
Lec"ture*ship	n.
Lec"turn	n.
Lec"y*this	n.
Led	imp. & p. p.
Led"en	n.
Ledge	n.
Ledge"ment	n.
Ledg"er	n.
Ledg"ment	n.
Ledg"y	a.
Ledum	prop. n.
Lee	v. i.
Lee	n.
Lee	n.
Lee	a.
Lee"an`gle	n.
Lee"board`	n.
Leech	n.
Leech	v. t.
Leech	n.
Leech	n.
Leech	v. t.
Leech"craft`	n.
Leed	n.
Leef	a. & adv.
Leek	n.
Leeme	v. & n.
Leep	strong imp.
Leer	v. t.
Leer	a.
Leer	n.
Leer	n.
Leer	v. i.
Leer	v. t.
Leere	n.
Leer"ing*ly	adv.
Lees	n. pl.
Lees	n.
Leese	v. t.
Leese	v. t.
Leet	obs. imp.
Leet	n.
Leet	n.
Leet	n.
Leet"man	n.
Lee"ward	a.
Lee"way`	n.
Left	imp. & p. p.
Left	a.
Left	n.
left" brain`	n.
left"-brain`	a.
left"-brained`	a.
left` field"	n.
Left"-hand`	a.
Left"-hand`ed	a.
Left"-hand`ed*ness	n.
left`hand"er	n.
leftish	adj.
leftist	adj.
leftist	n.
left-of-center	adj.
Left"-off`	a.
leftover	adj.
leftover	n.
left-slanting	adj.
Left"ward	adv.
left-wing	a.
left wing	n.
left-winger	n.
lefty	n.
Le"ful	a.
Leg	n.
Leg	v. t.
Leg"a*cy	n.
Le"gal	a.
legalese	n.
legalisation	n.
Le"gal*ism	n.
Le"gal*ist	n.
Le*gal"i*ty	n. 
Le`gal*i*za"tion	n.
Le"gal*ize	v. t.
Le"gal*ly	adv.
Le*gan"tine	a.
Leg"a*ta*ry	n.
Leg"ate	n.
Leg`a*tee"	n.
Leg"ate*ship	n.
Leg"a*tine	a.
Le*ga"tion	n.
Le*ga"to	a.
Leg`a*tor"	n.
Le`ga*tu"ra	n.
Leg"a*ture	n.
Leg bridge	v. t.
Lege"ment	n.
Leg"end	n.
Leg"end	v. t.
Leg"end*a*ry	a.
Leg"end*a*ry	n.
Leg"er	n.
Leg"er	a.
Leg"er	a.
Leg`er*de*main"	n.
Leg`er*de*main"ist	n.
Le*ger"i*ty	n.
Legge	v. t.
Legge	v. t.
Legged	a.
Leg`gi*a"dro	a. & adv.
Leg"ging	n.
Leg"ging	a. & vb. n.
Leg"gy	a.
Leg"horn	n.
Leg`i*bil"i*ty	n.
Leg"i*ble	a.
Leg"i*ble*ness	n.
Leg"i*bly	adv.
Le*gif"ic	a.
Le"gion	n.
Le"gion*a*ry	a.
Le"gion*a*ry	n.
Le"gioned	a.
Le"gion*ry	n.
Leg"is*late	v. i.
legislating	n.
Leg`is*la"tion	n.
Leg"is*la*tive	a.
Leg"is*la*tive*ly	adv.
Leg"is*la`tor	n.
Leg`is*la*to"ri*al	a.
Leg"is*la`tor*ship	n.
Leg"is*la`tress	n.
Leg"is*la`ture	n.
Le"gist	n.
Le*git"im	n.
Le*git"i*ma*cy	n.
Le*git"i*mate	a.
Le*git"i*mate	v. t.
Le*git"i*mate*ly	adv.
Le*git"i*mate*ness	n.
Le*git`i*ma"tion	n.
Le*git"i*ma*tist	n.
Le*git"i*ma*tize	v. t.
Le*git"i*mism	n.
Le*git"i*mist	n.
Le*git"i*mize	v. t.
Leg"less	a.
Leg"-of-mut"ton	a.
Le"go-lit"er*a*ry	a.
leg-pull	n.
leg-pulling	n.
Le`gu*le"ian	a.
Leg"ume	n.
Le*gu"men	n.
Le*gu"min	n.
Le*gu"mi*nous	a.
Lei"ger	n.
Leiopelma	n.
Leiopelmatidae	n.
Leiophyllum	n.
Lei*ot"ri*chan	a.
Lei*ot"ri*chi	n. pl.
Lei*ot"ri*chous	a.
Lei*po"a	n.
Lei`po*thym"ic	a.
Leis"ter	n.
Lei"sur*a*ble	a.
Lei"sur*a*bly	adv.
Lei"sure	n.
Lei"sure	a.
Lei"sured	a.
Lei"sure*ly	a.
Lei"sure*ly	adv.
Leit"mo*tif"	n.
Leitneria	prop. n.
Leitneriaceae	prop. n.
LEM	n.
Lemaireocereus	n.
Le"man	n.
lemanderin	n.
Leme	n.
Leme	v. i.
Lem"ma	n.
lem`ma*tiz*a"tion	v. t.
lem"ma*tize	v. t.
Lem"man	n.
Lem"ming	n.
Lemna	n.
Lemnaceae	n.
Lem"ni*an	a.
Lem`nis*ca"ta	n.
Lem*nis"cus	n.
Lem"on	n.
Lem`on*ade"	n.
lemonwood	n.
lemony	adj.
Le"mur	n.
Lem"u*res	n. pl.
Le*mu"ri*a	n.
Lem"u*rid	a. & n.
Le*mu"ri*dous	a.
Lem"u*roid	a.
Lem`u*roi"de*a	n. pl.
Le"na	n.
Le*nard" rays	n.
Lenard tube	v. t.
Lend"a*ble	a.
Lend"er	n.
Lend"es	n. pl.
Lend"ing	n.
lend-lease	n.
Lends	n. pl.
Lene	v. t.
Le"ne	a.
Le"ne	n.
Leng"er	a.
Length	n.
Length	v. t.
Length"en	v. t.
Length"en	v. i.
Length"ful	a.
Length"i*ly	adv.
Length"i*ness	n.
Length"ways`	adv.
Length"y	a.
Le"ni*ence	n.
Le"ni*ent	a.
Le"ni*ent	n.
Le"ni*ent*ly	adv.
Len"i*fy	v. t.
Len"i*ment	n.
Leningrad	prop. n.
Leninism	prop. n.
Len"i*tive	a.
Len"i*tive	n.
Len"i*tive*ness	n.
Len"i*tude	n.
Len"i*ty	n.
Len`ni-Len*a"pe	n. pl.
Le"no	n.
Le*noc"i*nant	a.
Lens	n.
Lent	imp. & p. p.
Lent	n.
Lent	a.
Len`ta*men"te	adv.
Len*tan"do	a.
Lent"en	n.
Lent"en	a.
Lent"en*tide`	n.
Len"ti*cel	n.
Len`ti*cel"late	a.
Len`ti*celle"	n.
Len*tic"u*la	n.
Len*tic"u*lar	a.
Len*tic"u*lar*ly	adv.
Len"ti*form	a.
Len*tig"i*nose`	a.
Len*tig"i*nous	a.
Len*ti"go	n.
Len"til	n.
Lentinus	n.
Len*tis"cus	n.
lentissimo	a. & adv.
Len"ti*tude	n.
Len"to	a. & adv.
Len"toid	a.
Len"tor	n.
Len"tous	a.
L'en`voi"	n.
Le"o	n.
Le"od	n.
Le"on	n.
Le"onced	a.
Le`o*nese"	a.
Le"o*nid	n.
Le"o*nine	a.
Leonotis	n.
Leontocebus	prop. n.
Leontopodium	n.
Le*on"to*don	n.
Leonurus	n.
Leop"ard	n.
leop"ard*bane	n.
leop"ard*ess	n.
leop"ard's bane`	n.
leop"ard*wood`	n.
lep	strong imp.
Lepadidae	prop. n.
Lep"a*dite	n.
Lep"a*doid	n.
Lep"al	n.
Lepanto	n.
Le"pas	n.
Lep"er	n.
Lep"ered	a.
Lep"er*ize	v. t.
Lep"er*ous	a.
Lep"id	a.
Lep"i*dine	n.
Lepidodendrales	n.
Lep`i*do*den"drid	n.
Lep`i*do*den"droid	a.
Lep`i*do*den"dron	n.
Lep`i*do*ga"noid	n.
Le*pid"o*lite	n.
Lep`i*dom"e*lane	n.
Lep`i*dop"ter	n.
Lep`i*dop"te*ra	n. pl.
Lep`i*dop"ter*al	a.
lepidopteran	a.
lepidopteran	n.
Lep`i*dop"ter*ist	n.
lepidopteron	n.
lepidopterous	a.
Lep`i*do*sau"ri*a	n. pl.
Lep`i*do*si"ren	n.
Lep"i*dote	a.
lepiota	n.
Le*pis"ma	n.
Le*pis"moid	a.
Lepomis	n.
leporid	n.
Leporidae	n.
leporide	n.
Lep"o*rine	a.
leppy	n.
Le"pra	n.
Lep"re	n.
leprechaun	n.
Lep"rose`	a.
Le*pros"i*ty	n.
Lep"ro*sy	n.
Lep"rous	a.
Lep"ry	n.
Lep"ti*form	a.
Lep`to*car"di*a	n. pl.
Lep`to*car"di*an	a.
Lep`to*cer"cal	a.
Lep`to*dac"tyl	n.
Leptodactylidae	n.
Lep`to*dac"tyl*ous	a.
Leptodactylus	n.
Leptoglossus	n.
Lep*tol"o*gy	n.
Lep`to*men`in*gi"tis	n.
lepton	n.
Leptopteris	n.
Leptoptilus	n.
Lep"to*rhine	a.
Lep*tos"tra*ca	n. pl.
Lep"to*thrix	n.
Lep"to*thrix	a.
Lep"tus	n.
Lep"ty*nite	n.
Lepus	n.
Ler	n.
Lere	n.
Lere	v. t. & i.
Lere	a.
Lere	n.
Ler"ed	a.
Ler*n<ae/"a	n.
Ler`n<ae/*a"ce*a	n. pl.
Ler*ne"an	n.
lerot	n.
Les	n.
Les"bi*an	a.
Les"bi*an	n.
Les"bi*an*ism	n.
Lesbian love	v. t.
Lese`-maj"es*ty	n.
Le"sion	n.
lespedeza	n.
Lesquerella	prop. n.
-less	conj.
Less	a.
Less	adv.
Less	n.
Less	v. t.
Les*see"	n.
Less"en	v. t.
Less"en	v. i.
Less"en*er	n.
lessening	adj.
lessening	n.
Less"er	a.
Less"er	adv.
Les"ses	n. pl.
Les"son	n.
Les"son	v. t.
Les"sor	n.
less-traveled	adj.
Lest	v. i.
Lest	n.
Lest	a.
Lest	conj.
Les"ter	n.
-let	suff.
Let	v. t.
Let	n.
Let	v. t.
Let	v. i.
Let"-a*lone"	a.
Letch	v. & n.
Letch	n.
Letch"y	a.
Lete	v. t.
Let"en	p. p.
Leth"al	n.
Le"thal	a.
Le*thal"i*ty	n.
Le*thar"gic	a.
Leth"ar*gize	v. t.
Leth"ar*gy	n.
Leth"ar*gy	v. t.
Le"the	n.
Le"the	n.
Le*the"an	a.
Le"theed	a.
Le"the*on	n.
Le"the*on*ize	v. t.
Le*thif"er*ous	a.
Le"thy	a.
Let"-off`	n.
Let"te	v. t.
Let"ter	n.
Let"ter	n.
Let"ter	n.
Let"ter	v. t.
let"ter bomb`	n.
letter-bomb	v. t.
lettercard	n.
Let"tered	a.
Let"ter*er	n.
Let"ter*gram	n.
Let"ter*ing	n.
Let"ter*less	a.
Let"tern	n.
letter-perfect	adj.
Let"ter*press`	n.
Let"ter*ure	n.
Let"ter*wood`	n.
Let"tic	a.
Let"tish	a.
Let"trure	n.
Letts	n. pl.
Let"tuce	n.
Let"u*a*ry	n.
Let"-up`	n.
Leuc-	pref.
Leu`ca*den"dron	n.
Leu*can"i*line	n.
Leu*ch<ae/"mi*a	n.
Leu"cic	a.
Leu"cine	n.
Leuciscus	prop. n.
Leu"cite	n.
Leu*cit"ic	a.
Leu"ci*toid	n.
Leu"co-	pref.
Leu"co*cyte	n.
Leu`co*cy*th<ae/"mi*a	n.
Leu`co*cy`to*gen"e*sis	n.
Leu`co*e`thi*op"ic	a.
Leu`co*e"thi*ops	n.
Leu"co*line	n.
Leu*co"ma	n.
Leu*co"ma*ine	n.
Leu*con"ic	a.
Leu*cop"a*thy	n.
Leu"co*phane	n.
Leu`co*phleg"ma*cy	n.
Leu`co*phleg*mat"ic	a.
Leu"co*phyll	n.
Leu*coph"yl*lous	a.
Leu"co*plast	n.
Leu*cop"y*rite	n.
Leu`cor*rh<oe/"a	n.
Leu"co*ryx	n.
Leu"co*scope	n.
Leu"co*soid	a.
Leu"co*sphere	n.
Leu`co*tu"ric	a.
Leu"cous	a.
Leu*cox"ene	n.
leu*k<ae/"mi*a	n.
Leuke	a.
Leu"ko*plast	n.
Le*va"na	n.
Le"vant	a.
Le*vant"	n.
Le"vant	a.
Le*vant"	v. i.
Le*vant"er	n.
Le*vant"er	n.
Le*vant"ine	a.
Le*vant"ine	n.
Le*va`ri fa"ci*as	n.
Le*va"tion	n.
Le*va"tor	n.
Leve	a.
Leve	n. & v.
Leve	v. i.
Leve	v. t.
Leve	v. t.
Le*ve"che	n.
Lev"ee	n.
Lev"ee	v. t.
Lev"ee	n.
Lev"ee	v. t.
Le*v<eacute/e" en` masse"	n.
Leve"ful	a.
Lev"el	n.
Lev"el	a.
Lev"el	v. t.
Lev"el	v. i.
Lev"el*er	n.
lev"el*head"ed	a.
Lev"el*ing	n.
Lev"el*ism	n.
Lev"el*ly	adv.
Lev"el*ness	n.
Lev"en	n.
Lev"er	a.
Lev"er	adv.
Le"ver	n.
Lev"er*age	n.
Lev"er*et	n.
Lev"er*ock	n.
Lev"er*wood`	n.
Lev"e*sel	n.
Lev"et	n.
Lev"i*a*ble	a.
Le*vi"a*than	n.
Lev"i*er	n.
Lev"i*ga*ble	a.
Lev"i*gate	a.
Lev"i*gate	v. t.
Lev"i*gate	a.
Lev`i*ga"tion	n.
Lev"in	n.
Lev"in*er	n.
Le"vir	n.
Lev"i*rate	a.
Lev`i*ra"tion	n.
Lev`i*ros"tres	n. pl.
Lev"i*tate	v. i.
Lev"i*tate	v. t.
Lev`i*ta"tion	n.
Le"vite	n.
Le*vit"ic*al	a.
Le*vit"ic*al*ly	adv.
Le*vit"i*cus	n.
Lev"i*ty	n.
Le"vo-	pref.
le`vo*do"pa	a.
Le`vo*gy"rate	a.
le`vo*ro"ta*ry	a.
Le`vo*ro*ta"tion	n.
Le`vo*ro"ta*to*ry	a.
Lev"u*lin	n.
Lev`u*lin"ic	a.
Lev`u*lo"san	n.
Lev"u*lose`	n.
Lev"y	n.
Lev"y	n.
Lev"y	v. t.
Lev"y	v. i.
Lev"yne	n.
Lew	a.
Lewd	a.
Lewd"ster	n.
Lew"is	n.
Lex	n.
lex"ic*al	a.
lex"i*cal*ize	v. t.
Lex`i*cog"ra*pher	n.
Lex`i*co*graph"ic	a.
Lex`i*cog"ra*phist	n.
Lex`i*cog"ra*phy	n.
Lex`i*col"o*gist	n.
Lex`i*col"o*gy	n.
Lex"i*con	n.
Lex"i*con*ist	n.
Lex`i*graph"ic	a.
Lex*ig"ra*phy	n.
Lex`i*phan"ic	a.
Lex`i*phan"i*cism	n.
Lex`i*phar"mic	a.
Ley	v. t. & i.
Ley	n.
Ley	n.
Ley	n.
Ley	a.
Ley"den jar"	n.
Leymus	prop. n.
Leyte	prop. n.
Ley"ser	n.
Lese` maj"es*ty	n.
LF	n.
LH	n.
Lhasa	n.
Lher"zo*lite	n.
Li	n.
Li`a*bil"i*ty	n.
Li"a*ble	a.
Li"a*ble*ness	n.
Li"age	n.
li*aise"	v. i.
li`ai`son"	n.
Li*ane"	n.
Li"ar	n.
Li"ard	a.
Liard	n.
Li"as	n.
Li*as"sic	a.
Lib	v. t.
Lib"a*ment	n.
Li"bant	a.
Li*ba"tion	n.
Li"ba*to*ry	a.
Lib"bard	n.
Lib"bard's bane`	n.
Li"bel	n.
Li"bel	v. t.
Li"bel	v. i.
Li"bel*ant	n.
Li"bel*er	n.
Li"bel*ist	n.
Li *bel"la	n.
Li`bel*lee"	n.
li*bel"lu*lid	n.
li*bel"lu*loid	a.
Li"bel*ous	a.
Li"ber	n.
Lib"er*al	a.
Lib"er*al	n.
liberalisation	n.
Lib"er*al*ism	n.
Lib"er*al*ist	n.
Lib`er*al*is"tic	a.
Lib`er*al"i*ty	n.
Lib`er*al*i*za"tion	n.
Lib"er*al*ize	v. t.
Lib"er*al*i`zer	n.
Lib"er*al*ly	adv.
Lib"er*ate	v. t.
liberated	adj.
liberating	adj.
Lib`er*a"tion	n.
Lib"er*a`tor	n.
Lib"er*a*to*ry	a.
Liberian	adj.
Liberian	n.
Lib`er*ta"ri*an	a.
Lib`er*ta"ri*an	n.
Lib`er*ta"ri*an*ism	n.
Lib"er*ti*cide	n.
Lib"er*tin*age	n.
Lib"er*tine	n.
Lib"er*tine	a.
Lib"er*tin*ism	n.
Lib"er*ty	n.
Li*beth"en*ite	n.
libidinal	adj.
Li*bid"i*nist	n.
Li*bid`i*nos"i*ty	n.
Li*bid"i*nous	a.
li*bi"do	n.
Lib"ken	n.
Libocedrus	n.
Li"bra	n.
Li"bral	a.
Li*bra"ri*an	n.
Li*bra"ri*an*ship	n.
Li"bra*ry	n.
Li"brate	v. i.
Li"brate	v. t.
Li*bra"tion	n.
Li*bra"tion point`	n.
Li"bra*to*ry	a.
Li*bret"tist	n.
Li*bret"to	n.
Li"bri*form	a.
Libya	prop. n.
Lib"y*an	a.
Lice	n.
licence	a.
Li"cense	n.
Li"cense	v. t.
Li"censed	a.
Li`cen*see"	n.
Li"cens*er	n.
Li"cen*sure	n.
Li*cen"ti*ate	n.
Li*cen"ti*ate	v. t.
Li*cen"tious	a.
Lich	a.
Lich	n.
Lichanura	n.
lichee	n.
Li"chen	n.
Li"chened	a.
Li*chen"ic	a.
Li*chen"i*form	a.
Li"chen*in	n.
Li`chen*o*graph"ic	a.
Li`chen*og"ra*phist	n.
Li`chen*og"ra*phy	n.
Li`chen*ol"o*gist	n.
Li`chen*ol"o*gy	n.
Li"chen*ous	a.
Li"chi`	n.
Lich"wale`	n.
Lich"wort`	n.
Lic"it	a.
Lic`i*ta"tion	n.
Lick	v. t.
Lick	n.
Lick	v. t.
Lick	n.
Lick"er	n.
Lick"er*ish	a.
Lick"er*ous	a.
Lick"ing	n.
Lick"pen`ny	n.
Lick"-spig`ot	n.
Lick"-spit`tle	n.
Lic"o*rice	n.
Lic"o*rous	a.
Lic"our	n.
Lic"tor	n.
Lid	n.
Lid"ded	a.
Lidge	n.
Lid"less	a.
lido	n.
Lie	n.
Lie	n.
Lie	v. i.
Lie	v. i.
Lie	n.
Lie"ber*k<uum/hn	prop. n.
Lie"ber*k<uum/hn's glands`	n.
liebfraumilch	n.
Liechtenstein	prop. n.
Liechtensteiner	prop. a.
Liechtensteiner	prop. n.
Lied	n.
Lie"der*kranz	n.
Lie"der*ta`fel	n.
Lief	n.
Lief	a.
Lief	n.
Lief	adv.
Lief"some	a.
Lieg"ance	n.
Liege	a.
Liege	n.
Liege"man	n.
Lie"ger	n.
Lie"gian*cy	n.
Li"en	p. p.
Lien	n.
Li*e"nal	a.
Li*en"cu*lus	n.
Li*e`no-in*tes"ti*nal	a.
Li`en*ter"ic	a.
Li"en*ter*y	n.
Li"er	n.
Lierne" rib`	n.
Lieu	n.
Lieu*ten"an*cy	n.
Lieu*ten"ant	n.
Lieu*ten"ant gen"er*al	n.
Lieu*ten"ant*ry	n.
Lieu*ten"ant*ship	n.
Lieve	a.
Lif	n.
Life	n.
Life"blood`	n.
Life"boat`	n.
Life"ful	a.
life"-giv`ing	a.
Life"hold`	n.
Life"less	a.
life"less*ness	n.
Life"like`	a.
lifeline	n.
Life"long	a.
Life"ly	adv.
Life"mate`	n.
Lif"en	v. t.
life-of-man	n.
Life"-pre*serv`er	n.
Life"-sav`ing	a.
life"-size`	a.
life-sustaining	adj.
Life"some	a.
Life"spring`	n.
Life"string"	n.
Life"time`	n.
Life"-wea`ry	a.
Lif"lode	n.
Lift	n.
Lift	v. t.
Lift	v. i.
Lift	n.
Lift"a*ble	a.
lifted	adj.
Lift"er	n.
Lift"ing	a.
liftoff	n.
Lig	v. i.
Lig"a*ment	n.
Lig`a*men"tal	a.
Li"gan	n.
ligase	n.
Li"gate	v. t.
Li*ga"tion	n.
Li*ga"tor	n.
Lig"a*ture	n.
Lig"a*ture	v. t.
Lig"e	v. t. & i.
Li"geance	n.
Lige"ment	n.
Lig"ge	v. i.
Lig"ger	n.
Light	n.
Light	a.
Light	v. t.
Light	v. i.
Light	a.
Light	adv.
Light	v. t.
Light	v. i.
Light"a*ble	a.
Light"-armed`	a.
Light"-boat`	n.
lightbulb	n.
light-coloured	adj.
light-duty	adj.
Light"e	imp.
lighted	adj.
Light"en	v. i.
Light"en	v. i.
Light"en	v. t.
Light"en	v. t.
lightening	n.
Light"er	n.
Light"er	n.
Light"er	v. t.
Light"er*age	n.
Light"er*man	n.
Light"-fin`gered	a.
Light"-foot`	a.
Light"ful	a.
light-green	adj.
light-haired	adj.
Light"-hand`ed	a.
Light"-head`ed	a.
Light"-heart`ed	a.
Light"-heeled`	a.
Light"-horse`man	n.
Light"house`	n.
Light"ing	n.
Light"-legged`	a.
Light"less	a.
lightlessness	n.
Light"ly	adv.
Light"man	n.
Light"-mind`ed	a.
Light"ness	n.
Light"ness	n.
Light"ning	n.
Light"ning	vb. n.
Light"-o'-love`	n.
Light"room`	n.
lights	n. pl.
light-sensitive	adj.
light"ship`	n.
light-skinned	adj.
Light"some	a.
lights-out	n.
Light"-struck`	a.
Light"weight`	n.
Light"weight`	a.
Light"-winged`	a.
Light"wood`	n.
Light"y	a.
Light-year	n.
Lig"ne*ous	a.
Lig*nif"er*ous	a.
Lig`ni*fi*ca"tion	n.
Lig"ni*form	a.
Lig"ni*fy	v. t.
Lig"ni*fy	v. i.
Lig"nin	n.
Lig`ni*per"dous	a.
Lig*nir"e*ose`	n.
Lig"nite	n.
Lig*nit"ic	a.
Lig`ni*tif"er*ous	a.
Lig`no*cer"ic	a.
Lig"none`	n.
Lig`no*tu"ber	n.
Lig*nose"	a.
Lig"nose`	n.
Lig"num rho"di*um	n.
Lig"ro*in	n.
Lig"sam	n.
Lig"u*la	n.
Lig"u*late	a.
Lig"ule	n.
Lig`u*li*flo"rous	a.
Lig"ure	n.
Li*gus"trin	n.
Lik"a*ble	a.
Like	a.
Like	n.
Like	adv.
Like	v. t.
Like	v. i.
Like"a*ble	a. 
Like"hood	n.
Like"li*hood	n.
Like"li*ness	n.
Like"ly	a.
Like"ly	adv.
Like"-mind`ed	a.
Lik"en	v. t.
Like"ness	n.
Lik"er*ous	a.
Like"wise`	adv. & conj.
Li"kin`	n.
Lik"ing	p. a.
Lik"ing	n.
Li"lac	n.
Lil"a*cin	n.
Lil`i*a"ceous	a.
Lil"i*al	a.
Lil"ied	a.
Liliidae	prop. n.
liliopsid	n.
Liliopsida	n.
Lilith	n.
Lilium	n.
Lill	v. i.
Lil`li*pu"tian	n.
Lil`li*pu"tian	a.
Lil"ly-pil`ly	n.
Lilt	v. i.
Lilt	v. t.
Lilt	n.
lilting	adj.
Lil"y	n.
Lil"y-hand`ed	a.
Lil"y-liv`ered	a.
lilyturf	n.
Lil"y*wort`	n.
Lim	n.
Li"ma	n.
Li*ma"ceous	a.
Lim`a*ci"na	n.
Li`ma`<cced/on"	n.
Li"maille	n.
Li"man	n.
Li*ma"tion	n.
Li"ma*ture	n.
Li"max	n.
Limb	n.
Limb	v. t.
Limb	n.
Lim"bat	n.
Lim"bate	a.
Lim"bec	n.
Lim"bec	v. t.
Limbed	a.
Lim"ber	n.
Lim"ber	v. t.
Lim"ber	a.
Lim"ber	v. t.
Lim"ber*ness	n.
limbic	adj.
limbic system	n.
Limb"less	a.
Limb"meal`	adv.
Lim"bo	n.
Lim"bo	n.
Lim"bous	a.
Lim"burg cheese	n.
Lime	n.
Lime	n.
Lime	n.
Lime	n.
Lime	v. t.
lime	a.
limeade	n.
Lime"hound`	n.
Lime"kiln`	n.
lime" light`	n.
limen	n.
Li*men"e*an	a.
Limenitis	n.
Lim"er	n.
Lim"er*ick	n.
Lime"stone`	n.
Lime twig	a.
Lime"wa`ter	n.
Li*mic"o*l<ae/	n. pl.
Li*mic"o*line	a.
liminal	adj.
liminality	n.
Lim"i*ness	n.
Lim"it	n.
Lim"it	v. t.
Lim"it	v. i.
Lim"it*a*ble	a.
Lim`i*ta"ne*ous	a.
Lim`i*ta"ri*an	a.
Lim"i*ta*ry	a.
Lim"i*ta*ry	n.
Lim"i*tate	a.
Lim`i*ta"tion	n.
Lim"it*ed	a.
Lim"it*ed*ly	adv.
Lim"it*ed*ness	n.
Lim"it*er	n.
Lim"it*ive	a.
Lim"it*less	a.
Lim"it*our	n.
Lim"mer	a.
Lim"mer	n.
Limn	v. t.
Lim*n<ae/"a	prop. n.
Lim"ner	n.
Lim"ni*ad	n.
Lim"ning	n.
Limnodromus	n.
limnology	n.
limo	n.
Li*moges"	prop. n.
limonene	n.
Li*mo"ni*ad	n.
Li*mo"nin	n.
Li"mon*ite	n.
Li*mo"sis	n.
Li"mous	a.
Li`mou*sine"	n.
Li`mou*sine" lib`er*al	n.
Limp	v. i.
Limp	n.
Limp	n.
Limp	a.
Limp"a	n.
Limp"er	n.
Lim"pet	n.
Lim"pid	a.
Lim*pid"i*ty	n.
Lim"pid*ness	n.
Lim"pin	n.
Limp"ing*ly	adv.
Limp"i*tude	n.
Limp"kin	n.
Limp"ness	n.
Limp"sy	a.
Li"mu	n.
Lim"ule	n.
Lim`u*loi"de*a	n. pl.
Lim"u*lus	n.
Lim"y	a.
Lin	v. i.
Lin	v. t.
Lin	n.
Lin"age	n.
Lin"a*ment	n.
Linaria	n.
Li*nar"ite	n.
Linch	n.
Lin"chi	n.
Linch"pin`	n.
Lin"coln green"	n.
Lincolnian	adj.
lincomycin	n.
Linc"ture	n.
Lind	n.
lindane	n.
Lin"den	n.
Lindera	n.
Lindheimera	n.
Lin"di*a	n.
Lin"di*form	a.
lin"dy	n.
Line	n.
Line	v. t.
Line	n.
Line	v. t.
Lin"e*age	n.
Lin"e*al	a.
Lin`e*al"i*ty	n.
Lin"e*al*ly	adv.
Lin"e*a*ment	n.
Lin"e*ar	a.
Lin`e*ar*en"sate	a.
Lin"e*ar*ly	adv.
Lin"e*ar-shaped`	a.
Lin"e*a*ry	a.
Lin"e*ate	a.
Lin`e*a"tion	n.
Lin"e*a*ture	n.
linecut	n.
lined	adj.
linelike	adj.
Line"man	n.
linemen	n. pl.
Lin"en	a.
Lin"en	n.
Lin"en*er	n.
Lin"e*o*late	a.
Lin"er	n.
line-shooter	n.
linesman	n.
Line"-up`	n.
-ling	suff.
-ling	n.
Ling	n.
Lin"ga	n.
Ling"-bird`	n.
lingcod	n.
Lin"gel	n.
lingenberry	n.
Lin"gence	n.
Lin"ger	v. i.
Lin"ger	v. t.
Lin"ger*er	n.
Lin`ge*rie"	n.
Lin"ger*ing	a.
Lin"ger*ing*ly	adv.
Lin"get	n.
Ling"ism	n.
Lin"gle	n.
Lin"go	n.
Lin*go"a wood`	n.
Lin"got	n.
Lin"gua	n.
Lin*gua"cious	a.
Lin`gua*den"tal	a.
Lin`gua*den"tal	n.
Lin"gua Fran"ca	n.
Lin"gual	a.
Lin"gual	n.
Lin*gual"i*ty	n.
Lin`gua*tu"li*da	n. pl.
Lin*guat`u*li"na	n. pl.
Lin`gui*den"tal	a. & n.
Lin"gui*form	a.
Lin"guist	n.
Lin*guis"tic	a.
Lin*guis"tic*al*ly	adv.
Lin*guis"tics	n.
lin"gu*la	n.
Lin"gu*late	a.
Li*nig"er*ous	a.
Lin"i*ment	n.
Lin"ing	n.
Link	n.
Link	n.
Link	n.
Link	v. t.
Link	v. i.
Link"age	n.
linked	a.
Link"boy`	n.
Link" mo"tion	n.
Links	n.
linkup	n.
Link"work`	n.
Linnaea	n.
Linnaeus	n.
Lin*n<ae/"a bo`re*a"lis	n.
Lin*n<ae/"an	prop. a.
Lin*n<ae/"ite	n.
Linne	n.
Lin"net	n.
Li*no"le*ate	n.
Li*no"le*ic	a.
Li*no"le*um	n.
Lin"o*type	n.
Li*nox"in	n.
Lin*sang"	n.
Lin"seed`	n.
Lin"sey	n.
Lin"sey-wool"sey	n.
Lin"sey-wool"sey	a.
Lin"stock	n.
Lint	n.
Lin"tel	n.
Lin"tie	n.
Lint"seed`	n.
Li"num	n.
Li"on	n.
Li"onced	a.
Li"on*cel	n.
Li"on*el	n.
Li"on*ess	n.
Li"on*et	n.
Li"on-heart`	n.
Li"on-heart`ed	a.
Li"on*hood	n.
lion-hunter	n.
Li"on*ism	n.
Li"on*ize	v. t.
Li"on*like`	a.
Li"on*ly	a.
Li"on's ear`	n.
Li"on's foot`	n.
Li"on*ship	n.
Li"on's leaf`	n.
Li"on's tail`	n.
Li"on's tooth`	n.
Lip	v. t.
Lip	v. t.
Li*p<ae/"mi*a	n.
Li*pans"	n. pl.
Li*pa"ri*an	n.
Liparidae	n.
liparis	n.
Lip"a*rite	n.
lip*e"mi*a	n.
lipfern	n.
Lip"ic	a.
lip"id	n.
lipide	n.
lip`id*e"mi*a	n.
lipid-lowering	a.
lip`id*o"sis	n.
Li*pin"ic	a.
Lip"less	a.
Lip"let	n.
Lip`o*ceph"a*la	n. pl.
Lip"o*chrin	n.
Lip"o*gram	n.
Lip`o*gram*mat"ic	a.
Lip`o*gram"ma*tist	n.
lip`oi*de"mi*a	n.
Li*po"ma	n.
lipophilic	adj.
lipophobic	adj.
Li`po*thym"ic	a.
Li*poth"y*mous	a.
Li*poth"y*my	n.
lipotropic	adj.
Lipotyphla	n.
Lipped	a.
Lip"pi*tude	n.
Lipse	v. i.
Lip"yl	n.
Liq"ua*ble	a.
Li"quate	v. i.
Li"quate	v. t.
Li*qua"tion	n.
Liq`ue*fa"cient	n.
Liq`ue*fac"tion	n.
Liq"ue*fi`a*ble	a.
liquefied	adj.
Liq"ue*fi`er	n.
Liq"ue*fy	v. t.
Liq"ue*fy	v. i.
Li*ques"cen*cy	n.
Li*ques"cent	a.
Li`queur"	n.
Liq"uid	a.
Liq"uid	n.
Liq"uid air	n.
Liq"uid*am`ber	n.
Liq"ui*date	v. t.
Liq`ui*da"tion	n.
Liq"ui*da`tor	n.
liquidise	v. t.
Li*quid"i*ty	n.
Liq"uid*ize	v. t.
Liq"uid*ly	adv.
Liq"uid*ness	n.
liquified	adj.
liquify	v. t. & i.
Liq"uor	n.
Liq"uor	v. t.
Liq"uor*ice	n.
Liq"uor*ish	a.
Liq"uor*ous	a.
Li"ra	n.
Li*rel"la	n.
Li*rel"li*form	a.
Lir`i*o*den"dron	n.
Lir"i*pipe	n.
Lir"i*poop	n.
Li*roc"o*nite	n.
Lis"bon	n.
Lisle	n.
Lisne	n.
Lisp	v. i.
Lisp	v. t.
Lisp	n.
LISP	n.
Lisp"er	n.
Lisp"ing*ly	adv.
Liss	n.
Liss	v. t.
Lis`sen*ceph"a*la	n. pl.
Lis"som	a.
List	n.
List	v. t.
List	v. i.
List	v. t.
List	v. i.
List	n.
List	n.
List	v. t.
List	v. i.
List	v. t.
listed	adj.
List"el	n.
Lis"ten	v. i.
Lis"ten	v. t.
Lis"ten*er	n.
listening	n.
List"er	n.
Lis"ter	n.
List"er	n.
Lis*te"ri*an	a.
Lis"ter*ism	n.
Lis"ter*ize	v. t.
List"ful	a.
List"ing	n.
List"less	a.
Lit	imp. & p. p.
Lit"a*ny	n.
Lit"arge	n.
Li"tchi`	n.
-lite	suff.
Lite	a., adv., & n.
Li"ter	n.
Lit"er*a*cy	n.
Lit"er*al	a.
Lit"er*al	n.
Lit"er*al*ism	n.
Lit"er*al*ist	n.
Lit`er*al"i*ty	n.
Lit`er*al*i*za"tion	n.
Lit"er*al*ize	v. t.
Lit"er*al*i`zer	n.
Lit"er*al*ly	adv.
Lit"er*al*ness	n.
Lit"er*a*ry	a.
Lit"er*ate	a.
Lit"er*ate	n.
Lit`e*ra"ti	n. pl.
Lit`e*ra"tim	adv.
Lit`er*a"tion	n.
Lit"er*a`tor	n.
Lit"er*a*ture	n.
Lit`e*ra"tus	n.
-lith	suff.
Lith	3d pers. sing. pres.
Lith	n.
li*th<ae/"mi*a	n.
Lith"a*gogue	n.
Lith"arge	n.
Li*thar"gy*rum	n.
Lith"ate	n.
Lithe	v. t. & i.
Lithe	a.
Lithe	v. t.
Lithe"ly	adv.
Lithe"ness	n.
Li"ther	a.
Li"ther*ly	a.
Lithe"some	a.
Lith"i*a	n.
Li*thi"a*sis	n.
Lith"ic	a.
Lith"ic	n.
Lith"ic	a.
Lith`i*oph"i*lite	n.
Lith"i*um	n.
Lith"o	a.
Lith"o*carp	n.
Lith`o*chro*mat"ics	n.
Lith`o*chro"mics	n.
Lith"o*clast	n.
Lith"o*cyst	n.
Lith"o*dome	n.
Li*thod"o*mous	a.
Li*thod"o*mus	n.
Lith"o*fel"lic	a.
Lith`o*frac"teur	n.
Lith`o*gen"e*sy	n.
li*thog"e*nous	a.
lith"o*glyph	n.
li*thog"ly*pher	n.
lith`o*glyph"ic	a.
lith`o*glyp"tics	n.
lith"o*graph	v. t.
lith"o*graph	n.
li*thog"ra*pher	n.
lith`o*graph"ic	a.
Li*thog"ra*phy	n.
Lith"oid	a.
Li*thol"a*try	n.
Lith`o*log"ic	a.
Lith`o*log"ic*al*ly	adv.
Li*thol"o*gist	n.
Li*thol"o*gy	n.
Lith"o*man`cy	n.
Lith"o*marge	n.
Lith`on*thrip"tic	a. & n.
Lith`on*trip"tic	a.
Lith"on*trip"tist	n.
Lith"on*trip`tor	n.
Li*thoph"a*gous	a.
Lith"o*phane	n.
Lith"o*phos`phor	n.
Lith`o*phos*phor"ic	a.
Lith`o*pho*tog"ra*phy	n.
Lith"o*phyll	n.
Lith"o*physe	n.
Lith"o*phyte	n.
Lith`o*phyt"ic	a.
Li*thoph"y*tous	a.
Li*tho"sian	n.
Lith"o*sphere	n.
Lith"o*tint	n.
Lith"o*tome	n.
Lith`o*tom"ic	a.
Li*thot"o*mist	n.
Li*thot"o*my	n.
Lith"o*trip`sy	n.
Lith`o*trip"tic	a. & n.
Lith"o*trip`tist	n.
Lith"o*trip`tor	n.
Lith"o*trite	n.
Li*thot"ri*ty	n.
Lith"o*type	n.
Lith"o*type	v. t.
Lith`o*typ"ic	a.
Li*thot"y*py	n.
Li*thox`yl	n.
Lith`u*a"ni*an	a.
Lith`u*a"ni*an	n.
Lith"y	a.
Lit"i*ga*ble	a.
Lit"i*gant	a.
Lit"i*gant	n.
Lit"i*gate	v. t.
Lit"i*gate	v. i.
Lit`i*ga"tion	n.
litigatious	adj.
Lit"i*ga`tor	n.
litiginous	adj.
Li*ti"gious	a.
Li*ti"gious*ly	adv.
Li*ti"gious*ness	n.
Lit"mus	n.
litmus test	n.
litoral	n.
Li"to*tes	n.
Li*tran"e*ter	n.
Li"tre	n.
Lit"ter	n.
Lit"ter	v. t.
Lit"ter	v. i.
Lit`te`ra`teur"	n.
litter-bearer	n.
lit"ter*bin`	n.
lit"ter*bug`	n.
lit"tered	adj.
lit"ter*er	n.
lit"ter*mate`	n.
Lit"ter*y	a.
Lit"tle	a.
Lit"tle	n.
Lit"tle	adv.
Lit"tle-ease`	n.
littleneck	n.
Lit"tle*ness	n.
littler	adj.
littlest	adj.
Lit"to*ral	a.
Lit"to*ri"na	n.
Lit"tress	n.
Lit"u*ate	a.
Lit"u*i*form	a.
Lit"u*ite	n.
Lit"u*rate	a.
Li*tur"gic	adv.
Li*tur"gics	n.
Li*tur`gi*ol"o*gist	n.
Li*tur`gi*ol"o*gy	n.
Lit"ur*gist	n.
Lit"ur*gy	n.
Lit"u*us	n.
Liv"a*ble	a.
Live	v. i.
Live	v. t.
Live	a.
Live	n.
liveable	a.
live-bearer	n.
Lived	a.
lived-in	adj.
Live"-for*ev`er	n.
Live"li*hed	n.
Live"li*hood	n.
Live"li*hood	n.
Live"li*ly	adv.
Live"li*ness	n.
Live"lode`	n.
Live"long`	a.
Live"ly	a.
Live"ly	adv.
liven	v. t.
liveness	n.
Liv"er	n.
Liv"er	n.
Liv"er	n.
Liv"er-col`ored	a.
Liv"ered	a.
Liv"er-grown`	a.
Liv"er*ied	a.
Liv"er*ing	n.
Liv"er*leaf`	n.
Liverpudlian	adj.
Liverpudlian	n.
Liv"er*wort`	n.
Liv"er*y	n.
Liv"er*y	v. t.
Liv"er*y*man	n.
Liv"er*y sta`ble	n.
Lives	n.
Lives	a. & adv.
Liv"id	a.
Li*vid"i*ty	n.
Liv"id*ness	n.
Liv"ing	a.
Liv"ing	n.
Liv"ing*ly	adv.
Liv"ing*ness	n.
Liv"ing pic"ture	n.
Li*vo"ni*an	a.
Li*vo"ni*an	n.
Li"vor	n.
Li`vrai`son"	n.
Li"vre	n.
Lix*iv"i*al	a.
Lix*iv"i*ate	a.
Lix*iv"i*ate	v. t.
Lix*iv`i*a"tion	n.
Lix*iv"i*ous	a.
Lix*iv"i*um	n.
Lixt	2d pers. sing. pres.
Li"za	n.
Liz"ard	n.
lizardfish	n.
Liz"ard's tail`	n.
Lla"ma	n.
Llan*dei"lo group`	n.
Lla"no	n.
Lloyd's	n.
Llullaillaco	prop. n.
Llyr	prop. n.
Lo	interj.
Loach	n.
Load	n.
Load	v. t.
load-bearing	adj.
loaded	adj.
Load"er	n.
Load"ing	n.
Load"man*age	n.
loads	n.
load-shedding	n.
Loads"man	n.
Load"star`	n.
Load"stone`	n.
Loaf	n.
Loaf	v. i.
Loaf	v. t.
Loaf"er	n.
loaf"ing	n.
Loam	n.
Loam	v. i.
loamless	adj.
Loam"y	a.
Loan	n.
Loan	n.
Loan	v. t.
Loan"a*ble	a.
loan"blend	n.
loaner	n.
Loan"in	n.
Loan"mon`ger	n.
loanword	n.
loasa	n.
Loasaceae	n.
Loath	a.
Loathe	v. t.
Loathe	v. i.
Loath"er	n.
Loath"ful	a.
Loath"ing	n.
Loath"ing*ly	adv.
Loath"li*ness	n.
Loath"ly	a.
Loath"ly	adv.
Loath"ness	n.
Loath"some	a.
Loath"y	a.
Loaves	n.
Lob	n.
Lob	v. t.
Lob	v. t.
Lob	n.
Lob	n.
Lo"bar	a.
Lo"bate	a.
Lo"bate*ly	adv.
Lob"bish	a.
Lob"by	n.
Lob"by	v. i.
Lob"by	v. t.
Lob"by*ist	n.
Lob"cock`	n.
Lobe	n.
lobectomy	n.
Lobed	a.
Lobe"foot`	n.
Lobe"-foot`ed	a.
Lobe"let	n.
Lo*be"li*a	n.
Lobeliaceae	n.
Lo*be`li*a"ceous	a.
Lo*be"lin	n.
Lo*be"line	n.
Lo"bi*ped	a.
Lob"lol`ly	n.
Lo*bo"sa	n. pl.
Lobotes	n.
Lobotidae	n.
lobotomy	n.
Lob"scouse`	n.
Lob"sid`ed	a.
Lobs"pound`	n.
Lob"ster	n.
lobsterback	n.
lobster-backed	adj.
Lob"ster pot	n.
Lob"ster ther"mi*dor	n.
Lob"ster trap	n.
Lob"u*lar	a.
lobularity	n.
Lob"u*late	a.
Lob"ule	n.
Lob`u*lette"	n.
Lob"worm`	n.
Lo"cal	a.
Lo"cal	n.
Lo`cale"	n.
localisation	n.
localise	v. t.
Lo"cal*ism	n.
Lo*cal"i*ty	n.
Lo`cal*i*za"tion	n.
Lo"cal*ize	v. t.
localized	adj.
Lo"cal*ly	adv.
Lo"cate	v. t.
Lo"cate	v. i.
located	adj.
locating	n.
Lo*ca"tion	n.
Loc"a*tive	a.
Lo"ca*tor	n.
Lo*cel"late	a.
Loch	n.
Loch	n.
Loch*a"ber ax"	n.
Loch"age	n.
Loch"an	n.
Loche	n.
Lo*chi"a	n. pl.
Lo"chi*al	a.
Lock	n.
Lock	n.
Lock	v. t.
Lock	v. i.
Lock"age	n.
lock"box`	n.
Lock"-down`	n.
Locked"-jaw`	n.
Lock"en	p. p.
Lock"en	n.
Lock"er	n.
Lock"et	n.
lock-gate	n.
Lock" hos"pi*tal	n.
Lock"jaw`	n.
Lock"less	a.
Lock"man	n.
lockmaster	n.
locknut	n.
Lock"out`	n.
Lock"ram	n.
Lock"smith`	n.
Lock" step`	n.
Lock" stitch`	n.
Lock"up`	n.
Lock" wash`er	n.
Lock"-weir`	n.
Lock"y	a.
Lo"co	adv.
Lo"co	n.
Lo"co	v. t.
Lo"co	n.
lo"co	a.
Loco disease	n.
locoism	n.
locomote	v. i.
Lo`co*mo"tion	n.
Lo"co*mo`tive	a.
Lo"co*mo`tive	n.
Lo"co*mo`tive*ness	n.
Lo`co*mo"tor	a.
Loc"u*la*ment	n.
Loc"u*lar	a.
Loc"u*late	a.
Loc"ule	n.
Loc"u*li*ci`dal	a.
Loc"u*lose`	a.
Loc"u*lus	n.
Lo"cum te"nens	n.
Lo"cus	n.
Lo"cust	n.
Lo*cus"ta	n.
Lo`cus*tel"la	n.
Lo*cus"tic	a.
Lo"cust*ing	p. a.
Lo"cust tree`	n.
Lo*cu"tion	n.
Loc"u*to*ry	n.
Lod"de	n.
Lode	n.
Lode"man*age	n.
Lode"-ship`	n.
Lodes"man	n.
Lode"star`	n.
Lode"stone`	n.
Lodge	n.
Lodge	v. i.
Lodge	v. t.
Lodge"a*ble	a.
Lodged	a.
Lodge"ment	n.
lodgepole	n.
lodgepole pine	n.
Lodg"er	n.
Lodg"ing	n.
lodgings	n.
Lodg"ment	n.
Lod"i*cule	n.
Loel"ling*ite	n.
Loess	n.
Loev"en's lar"va	n.
Loffe	v. i.
Loft	n.
Loft	a.
Loft	v. t.
Loft	v. t. & i.
Loft"er	n.
Loft"i*ly	adv.
Loft"i*ness	n.
Loft"ing iron	a.
Log	n.
Log	n.
Log	v. t.
Log	v. i.
Log"an	n.
Logania	prop. n.
Log`a*<oe/d"ic	a.
Log"a*rithm	n.
Log`a*rith*met"ic	a.
Log`a*rith*met"ic*al*ly	adv.
Log`a*rith"mic	a.
Log`a*rith"mic*al*ly	adv.
Log"-chip`	n.
Log"cock`	n.
Loge	n.
Log"gan	n.
Log"gat	n.
Logge	n. & v.
Logged	a.
Log"ger	n.
Log"ger*head`	n.
Log"ger*head`ed	a.
Log"ger*heads`	n.
Log"gia	n.
Log"ging	n.
Log"ic	n.
Log"ic*al	a.
Log`i*cal"i*ty	n.
Log"ic*al*ly	adv.
Log"ic*al*ness	n.
Lo*gi"cian	n.
Log"ics	n.
log in	v. i.
Lo*gis"tic	a.
logistician	n.
Lo*gis"tics	n.
Log"man	n.
Log`o*d<ae/d"a*ly	n.
Log"o*gram	n.
Lo*gog"ra*pher	n.
Log`o*graph"ic	a.
Lo*gog"ra*phy	n.
Log"o*griph	n.
Lo*gom"a*chist	n.
Lo*gom"a*chy	n.
Log`o*met"ric	a.
Log"os	n.
Log"o*thete	n.
Log"roll`	v. i. & t.
Log"roll`er	n.
Log"roll`ing	n.
Log"-ship	n.
Log"wood`	n.
-lo*gy	suff.
Lo"gy	a.
Lo"hock	n.
Loi"mic	a.
Loin	n.
loincloth	n.
Loir	n.
Loire	prop. n.
Loiseleuria	prop. n.
Loi"ter	v. i.
Loi"ter*er	n.
Loi"ter*ing*ly	adv.
Lok	n.
Lo*ka"o	n.
Loke	n.
Lok"o*rys	n.
Lo*li"go	n.
Lolium	n.
Loll	v. i.
Loll	v. t.
Lol"lard	n.
Lol"lard*ism	n.
Loll"er	n.
Loll"ing*ly	adv.
Lol"li*pop	n.
Lol"lop	v. i.
lo"ma	n.
lomatia	n.
lo*mat"i*nous	a.
Lom"bard	prop. a.
Lom"bard	prop. n.
Lom`bard*eer"	n.
Lom"bard-house	n.
Lom*bar"dic	a.
Lo"ment	n.
Lo`men*ta"ceous	a.
Lom"o*nite	n.
Lomp"ish	a.
Lonchocarpus	prop. n.
Lond	n.
Lon"don	n.
Lon"don*er	n.
Lon"don*ism	n.
Lon"don*ize	v. i.
Lon"don*ize	v. i.
Lon"don smoke	n.
Lone	a.
Lone"li*ness	n.
Lone"ly	a.
Lone"ness	n.
Lone"some	a.
lone"some*ness	n.
Lone-Star State	prop. n.
Long	a.
Long	n.
Long	adv.
Long	prep.
Long	v. i.
long-acting	adj.
Lon"gan	n.
longanberry	n.
Lon`ga*nim"i*ty	n.
Long"-armed`	a.
Long"beak`	n.
longbeard	n.
Long"boat`	n.
Long"bow`	n.
Long"-breathed`	a.
long-dated	adj.
long-distance	adj.
Long"-drawn`	a.
long-drawn-out	adj.
Longe	n.
Longe	n.
Long"er	n.
Lon*ge"val	a.
Lon*gev"i*ty	n.
Lon*ge"vous	a.
long-faced	adj.
long-familiar	adj.
long-haired	adj.
Long"hand`	n.
Long"head"ed	a.
Long"horn`	n.
Long"-horned`	a.
Lon"gi*corn	a.
Lon`gi*cor"ni*a	n. pl.
Lon`gi*lat"er*al	a.
Lon*gil"o*quence	n.
Lon*gim"a*nous	a.
Lon*gim"e*try	n.
Long"ing	n.
Long"ing*ly	adv.
Lon*gin"qui*ty	n.
Lon"gi*palp	n.
Lon"gi*pen"nate	a.
Lon`gi*pen"nes	n. pl.
Lon`gi*pen"nine	a.
Lon`gi*ros"ter	n.
Lon`gi*ros"tral	a.
Lon`gi*ros"tres	n. pl.
Long"ish	a.
Lon"gi*tude	n.
Lon`gi*tu"di*nal	a.
Lon`gi*tu"di*nal	n.
Lon`gi*tu"di*nal*ly	adv.
long-lasting	adj.
long-legged	adj.
Long"legs`	n.
Long"-lived`	a.
Long"ly	adv.
Long"mynd rocks"	n. pl.
Long"ness	n.
Long"nose`	n.
long-play	adj.
long-playing	adj.
Long" prim"er	n.
long-range	adj.
long-run	adj.
long-shanked	adj.
Long"shanks`	n.
Long"shore`	a.
Long"shore`man	n.
Long"-sight	n.
Long"-sight`ed	a.
Long"-sight`ed*ness	n.
Long"some	a.
Long"spun`	a.
Long"spur`	n.
long-standing	adj.
Long"-stop`	n.
Long"-suf`fer*ance	n.
Long"-suf`fer*ing	n.
Long"-suf`fer*ing	n.
Long"tail`	n.
long-term	adj.
Long"-tongue`	n.
Long"-tongued`	a.
Lon"gu*lite	n.
Long"-waist`ed	a.
Long"ways`	adv.
long-wearing	adj.
Long"-wind"ed	a.
Long"wise`	adv.
Lonicera	n.
lontar	n.
Loo	n.
Loo	v. t.
Loob	n.
Loo"bi*ly	a.
Loo"bi*ly	adv.
Loo"by	n.
Looch	n.
Loof	n.
Loof	n.
Loof	v. i.
Look	v. i.
Look	v. t.
Look	n.
look"down`	n.
looked-for	adj.
Look"er	n.
Look"ing	a.
Look"ing	n.
Look"ing-glass`	n.
Look"out`	n.
look-over	n.
look"up	n.
Lool	n.
Loom	n.
Loom	n.
Loom	v. i.
Loom	n.
Loom"-gale`	n.
Loom"ing	n.
Loon	n.
Loon	n.
looney	n.
loon"y	a.
loony	n.
loony bin	n.
Loop	n.
Loop	n.
Loop	v. t.
Looped	a.
Loop"er	n.
Loop"hole`	n.
Loop"holed`	a.
Loop"ie	a.
Loop"ing	n.
Loop"ing	p. pr. & vb. n.
Loop"light`	n.
loop-line	n.
Loord	n.
Loos	n.
Loose	a.
Loose	n.
Loose	v. n.
Loose	v. i.
loose-fitting	adj.
loose-jowled	adj.
loose"leaf`	adj.
looseleaf binder	n.
looseleaf paper	n.
Loose"ly	adv.
Loos"en	v. t.
Loos"en	v. i.
loosened	adj.
Loos"en*er	n.
Loose"ness	n.
Loose"strife`	n.
Loos"ish	a.
Loot	n.
Loot	v. t. & i.
looted	adj.
Loot"er	n.
Loo"ver	n.
Lop	n.
Lop	v. t.
Lop	n.
Lop	v. i.
Lop	v. t.
Lop	a.
Lope	imp.
Lope	v. i.
Lope	n.
Lop"eared`	a.
Lope"man	n.
Lop"er	n.
Loph"ine	n.
Lo*phi"o*mys	n.
Loph"o*branch	a.
Loph`o*bran"chi*ate	a.
Loph`o*bran"chi*i	n. pl.
Loph"o*phore	n.
Lo*phop"o*da	n. pl.
Lo*phos"te*on	n.
Lop"pard	n.
Lop"per	n.
Lop"per	v. i.
Lop"ping	n.
Lop"py	a.
Lop"seed`	n.
Lop"sid`ed	a.
lop"sid`ed victory	n.
Lo*qua"cious	a.
Lo*qua"cious*ly	adv.
Lo*qua"cious*ness	n.
Lo*quac"i*ty	n.
Lo"quat	n.
Lo"ral	n.
Lor"an	n.
Lo"rate	a.
Lor"cha	n.
Lord	n.
Lord	n.
Lord	v. t.
Lord	v. i.
Lord"ing	n.
Lord"kin	n.
lordless	adj.
Lord"like`	a.
Lord"li*ness	n.
Lord"ling	n.
Lord"ly	a.
Lord"ly	adv.
Lord*ol"a*try	n.
Lor*do"sis	n.
Lords" and La"dies	n.
Lord"ship	n.
Lore	n.
Lore	imp. & p. p.
Lore	n.
Lor"e*al	a.
Lor"el	n.
Lor"en	p. p.
Lores"man	n.
Lo*ret"o nuns	n.
Lo`ret*tine"	n.
Lor`gnette"	n.
Lo"ri	n.
Lo*ri"ca	n.
Lor`i*ca"ta	n. pl.
Lor"i*cate	v. t.
Lor"i*cate	a.
Lor"i*cate	n.
Lor`i*ca"tion	n.
Lor"i*keet	n.
Lor"i*mer	n.
Lor"ing	n.
Lo"ri*ot	n.
Lo"ris	n.
Lorn	a.
Lor"rie	n.
Lo"ry	n.
Los	n.
Los"a*ble	a.
Los"ange	n.
Lose	v. t.
Lose	v. i.
Los"el	n.
Los"el	a.
Los"en*ger	n.
Los"en*ger*ie	n.
Los"er	n.
Lo"sing	a.
Los"ing	a.
Los"ing*ly	adv.
losings	n.
Loss	n.
losses	n.
Loss"ful	a.
loss leader	n.
Loss"less	a.
los"sy com*pres"sion	n.
Lost	a.
Lot	n.
Lot	v. t.
Lote	n.
Lote	n.
Lote	v. i.
Loth	a.
loth	adj.
Lo*tha"ri*o	n.
Lothringen	prop. n.
Lo"tion	n.
Lo"to	n.
Lo*tong"	n.
Lo*toph"a*gi	n. pl.
Lo"tos	n.
Lot"ter*y	n.
Lot"to	n.
Lo"ture	n.
Lo"tus	n.
Lo"tus-eat`er	n.
louche	adj.
Lou*chettes"	n. pl.
Loud	a.
Loud	adv.
Loud"ful	a.
Loud"ly	adv.
loud-mouth	n.
Loud"-mouthed`	a.
Loud"ness	n.
loud"speak*er	n.
Loud"-voiced`	a.
Lough	n.
Lough	strong imp.
Lou"is d'or`	n.
Louisianan	prop. n.
Lou"is qua*torze"	n.
Louk	n.
Lounge	v. i.
Lounge	n.
Loun"ger	n.
Loup	n.
Loup"-cer`vier"	n.
loupe	n.
Loup`-ga`rou"	n.
Loup"ing	n.
Loup`-loup"	n.
Loups	n. pl.
Lour	n.
Lou"ri	n.
Louse	n.
Louse	v. t.
Louse"wort`	n.
Lous"i*ly	adv.
Lous"i*ness	n.
Lous"y	a.
Lout	v. i.
Lout	n.
Lout	v. t.
Lout"ish	a.
Lou*tou"	n.
Lou"ver	n.
Lou"ver	n.
louvered	adj.
lou"vered door`	n.
lou"vered win"dow	n.
Lov"a*ble	a.
Lov"age	n.
Love	n.
Love	v. t.
Love	v. i.
Love"a*ble	a.
lovebird	n.
loved	adj.
Love"-dru`ry	n.
Lov*ee"	n.
Love"ful	a.
Love"less	a.
Love"li*ly	adv.
Love"li*ness	n.
Love"lock`	n.
Love"lorn`	a.
Love"ly	a.
Love"ly	adv.
Love"-mak`ing	n.
Love"mon`ger	n.
love-philter	n.
love-potion	n.
Lov"er	n.
Lo"ver	n.
Lo"ver*wise`	adv.
Love"-sick`	a.
Love"-sick`ness	n.
Love"some	a.
lovesong	n.
love-token	n.
Lov"ing	a.
Lov"ing cup`	n.
Lov"ing*ly	adv.
Lov"ing*ness	n.
Lov"yer	n.
Low	strong imp.
Low	v. i.
Low	n.
Low	n.
Low	n.
Low	v. i.
Low	a.
Low	n.
Low	adv.
Low	v. t.
lowan	n.
lowball	n.
lowball	v. t.
Low"bell`	n.
Low"bell`	v. t.
Low"born`	a.
Low"boy`	n.
Low"bred`	a.
low-cal	adj.
low-ceilinged	adj.
Low"-church`	a.
Low"-church`ism	n.
Low"-church`man	n.
Low"-church`man*ship	n.
low-class	adj.
low-cost	adj.
low-cut	adj.
low"down`	n.
low"down`	a.
low-emission	adj.
Low"er	a.
Low"er	v. t.
Low"er	v. i.
Low"er	v. i.
Low"er	n.
low"er*case`	a.
lower-class	adj.
lowerclassman	n.
lowered	adj.
Low"er*ing	a.
Low"er*ing*ly	adv.
lower limit	n.
lower-middle-class	adj.
Low"er*most`	a.
lower-ranking	adj.
Low"er*y	a.
Lowgh	strong imp.
low-grade	adj.
Low"ing	n.
Low"ish	a.
Lowk	n.
low-key	adj.
Low"land	n.
Low"land*er	n.
low-level	adj.
Low"li*hood	n.
Low"li*ly	adv.
Low"li*ness	n.
Low"-lived`	a.
Low"ly	a.
Low"ly	adv.
low-lying	adj.
Low"-mind`ed	a.
Low"-mind`ed*ness	n.
Lown	n.
Low"-necked`	a.
Low"ness	n.
low-pitched	adj.
low-polluting	adj.
Low"-pres`sure	a.
low-priced	adj.
low-resolution	adj.
low-rise	adj.
Low"ry	n.
low-set	adj.
Low"-spir`it*ed	a.
Low steel	a.
low-sudsing	adj.
low-tech	adj.
low-tension	adj.
Low"-thought`ed	a.
low-toned	adj.
low-voltage	adj.
low-warp loom	n.
Lox`o*drom"ic	a.
Lox`o*drom"ics	n.
Lox*od"ro*mism	n.
Lox*od"ro*my	n.
Loy	n.
Loy"al	a.
Loy"al*ist	n.
Loy"al*ly	adv.
Loy"al*ness	n.
Loy"al*ty	n.
Loz"enge	n.
Loz"enged	a.
Loz"en*gy	a.
L-P	n.
L-plate	n.
Lr	n.
LSD	n.
Ltd.	n.
LTM	n.
Lu	n. & v. t.
Lu	n.
Lub"bard	n.
Lub"bard	a.
Lub"ber	n.
Lub"ber*ly	a.
Lub"ber*ly	adv.
Lu"bric	a.
Lu"bri*cant	a.
Lu"bri*cant	n.
Lu"bri*cate	v. t.
lubricated	adj.
Lu`bri*ca"tion	n.
Lu"bri*ca`tor	n.
Lu*bric"i*tate	v. i.
Lu*bric"i*ty	n.
Lu"bri*cous	a.
Lu`bri*fi*ca"tion	n.
Lu`carne"	n.
Luc*chese"	n. sing. & pl.
Luce	n.
Lu"cen*cy	n.
Lu"cent	a.
Lu"cern	n.
Lu"cern	n.
Lu"cern	n.
Lu*cer"nal	a.
Lu`cer*na"ri*a	n.
Lu`cer*na"ri*an	a.
Lu`cer*nar"i*da	n. pl.
Lu"cerne	n.
Lu"cid	a.
Lu*cid"i*ty	n.
Lu"cid*ly	adv.
Lu"cid*ness	n.
Lu"ci*fer	n.
Lu`ci*fe"ri*an	a.
Lu`ci*fe"ri*an	n.
Lu*cif"er*in	n.
Lu*cif"er*ase	n.
Lu*cif"er*ous	a.
Lu*cif"er*ous*ly	adv.
Lu*cif"ic	a.
Lu"ci*form	a.
Lu*cif"ri*an	a.
Lu*cim"e*ter	n.
Lu"cite	prop. n.
Luck	n.
Luck"i*ly	adv.
Luck"i*ness	n.
Luck"less	a.
Lucknow	n.
Luck"y	a.
Luck`y proach"	n.
Lu"cra*tive	a.
Lu"cra*tive*ly	adv.
Lu"cre	n.
Lu*crif"er*ous	a.
Lu*crif"ic	a.
Luc*ta"tion	n.
Luc"tu*al	a.
Lu"cu*brate	v. i.
Lu"cu*brate	v. t.
Lu`cu*bra"tion	n.
Lu"cu*bra`tor	n.
Lu"cu*bra*to*ry	a.
Lu"cule	n.
Lu"cu*lent	a.
Lu"cu*lent*ly	adv.
Lu*cul"lite	n.
Lu*cu"ma	n.
Lud"dite	n.
Lu*dib"ri*ous	a.
Lu"di*bund	a.
Lu"di*crous	a.
Lu`di*fi*ca"tion	n.
Lu*dif"i*ca*to*ry	a.
Lud"lam*ite	n.
Lud"low group`	n.
Lud"wig*ite	n.
Lu"es	n.
Luff	n.
Luff	v. i.
Luf"fer	n.
Lug	n.
Lug	v. i.
Lug	v. i.
Lug	n.
Lug	n.
Luganda	n.
luge	n.
lug"er	n.
Lug"gage	n.
Lug"ger	n.
Lug"ger	n.
Lug"mark`	n.
Lug"sail`	n.
Lu*gu"bri*ous	a.
lu*gu"bri*ous*ness	n.
Lug"worm`	n.
Luke	a.
Luke"warm`	a.
Lull	v. t.
Lull	v. i.
Lull	n.
lull"a*by	n.
Lull"er	n.
Lull"ing*ly	adv.
Lum	n.
Lu"ma*chel	n.
Lum*bag"i*nous	a.
Lum*ba"go	n.
Lum"bar	a.
Lum"ber	n.
Lum"ber	v. t.
Lum"ber	v. i.
Lum"ber*er	n.
Lum"ber*ing	n.
lum"ber*jack`	n.
Lum"ber*man	n.
Lum"ber State	n.
Lum"bric	n.
Lum"bric*al	a.
Lum*bric"i*form	a.
Lum"bri*coid	a.
Lum"bri*cus	n.
Lu"men	n.
Lu"mi*nant	a.
Lu"mi*na*ry	n.
Lu"mi*nate	v. t.
Lu`mi*na"tion	n.
Lu"mine	v. i.
Lu`mi*nes"cence	n.
Lu`mi*nes"cent	a.
Lu`mi*nif"er*ous	a.
Lu`mi*nos"i*ty	n.
Lu"mi*nous	a.
lu"mi*nous*ness	n.
Lum"mox	n.
Lump	n.
Lump	v. i.
Lump*ec"to*my	n.
lump"en	adj.
Lump"en	n.
Lump`en*pro*le*tar"i*at	n.
Lump"er	n.
Lump"er	n.
Lump"fish`	n.
Lump"ing	a.
Lump"ish	a.
Lump"suck`er	n.
Lump together	v. t.
Lump"y	a.
Lump"y-jaw`	n.
Lu"na*cy	n.
Lu"nar	a.
Lu"nar	n.
Lunaria	prop. n.
Lu*na"ri*an	n.
Lu"na*ry	a.
Lu"na*ry	n.
Lu"nate	a.
Lu"na*tic	a.
Lu"na*tic	n.
lunatic fringe	n.
Lu*na"tion	n.
Lunch	n.
Lunch	v. i.
Lunch"eon	n.
Lunch"eon	v. i.
luncher	n.
lunching	n.
lunchroom	n.
lunchtime	n.
Lunda	n.
Lune	n.
Lu"net	n.
Lu*nette"	n.
Lung	n.
Lunge	n.
Lunge	v. i.
Lunge	v. t.
Lunge	n.
Lunged	a.
lunger	n.
Lung"fish`	n.
Lung"-grown`	a.
Lun"gie	n.
Lun"gis	n.
Lung"less	a.
Lun"goor	n.
lung-power	n.
Lung"worm`	n.
Lung"wort`	n.
Lu"ni*cur"rent	a.
Lu"ni*form	a.
Lu"ni*so"lar	a.
Lu"ni*stice	n.
Lu"ni*tid`al	a.
Lunt	n.
Lu"nu*la	n.
Lu"nu*lar	a.
Lu"nu*late	a.
Lu"nule	n.
Lu"nu*let	n.
Lu"nu*lite	n.
Lu"ny	a.
Lu*per"cal	a.
Lu*per"cal	n.
Lu`per*ca"li*a	n. pl.
Lu"pine	n.
Lu"pine	a.
Lu"pin*in	n.
Lu"pin*ine	n.
Lu"pu*lin	n.
Lu"pu*line	n.
Lu`pu*lin"ic	a.
Lu"pus	n.
Lur*ca"tion	n.
Lurch	v. i.
Lurch	n.
Lurch	v. t.
Lurch	n.
Lurch	v. i.
Lurch	v. i.
Lurch"er	n.
Lurch"er	n.
Lurch"line`	n.
Lur"dan	a.
Lur"dan	n.
Lure	n.
Lure	v. t.
Lure	v. i.
Lurg	n.
Lu"rid	a.
Lurk	v. i.
Lurk"er	n.
Lur"ry	n.
Luscinia	n.
Lus"cious	a.
Lu"sern	n.
Lush	a.
Lush	n.
Lush"burg	n.
Lusitania	n.
Lu`si*ta"ni*an	a.
Lusk	a.
Lusk	n.
Lusk	v. i.
Lusk"ish	a.
Lu*so"ri*ous	a.
Lus"she*burgh	n.
Lust	n.
Lust	v. i.
Lust"er	n.
Lus"ter	n.
Lus"ter	n.
Lus"ter	v. t.
Lus"ter*ing	n.
Lus"ter*less	a.
Lust"ful	a.
Lus"tic	a.
Lus"ti*head	n.
Lus"ti*hood	n.
Lus"ti*ly	adv.
Lus"ti*ness	n.
Lust"less	a.
Lus"tral	a.
Lus"trate	v. t.
Lus*tra"tion	n.
Lus"tre	n.
Lus"tri*cal	a.
Lus"tring	n.
Lus"trous	a.
Lus"trum	n.
Lust"wort`	n.
Lust"y	a.
Lu"sus na*tu"r<ae/	n.
Lut"a*nist	n.
Lu*ta"ri*ous	a.
Lu*ta"tion	n.
Lute	n.
Lute	v. t.
Lute	n.
Lute	v. i.
Lute	v. t.
Lute"-backed`	a.
Lu*te"ci*um	n.
Lu*te"ic	a.
Lu"te*in	n.
Lut"e*nist	n.
Lu"te*o-	pref.
Lu"te*o*co*balt"ic	a.
Lu"te*o*lin	n.
Lu"te*ous	a.
Lut"er	n.
Lut"er	n.
Lu*tes"cent	a.
Lute"string`	n.
Lu*te"ti*um	n.
Luth	n.
Lu"ther*an	a.
Lu"ther*an	n.
Lu"ther*an*ism	n.
Lu"thern	n.
lu"thi*er	n.
Lu"ti*dine	n.
Lut"ing	n.
Lut"ist	n.
Lu*tose"	a.
Lutra	n.
Lutrinae	n.
Lu"tu*lence	n.
Lu"tu*lent	a.
Lutzen	n.
Luvaridae	n.
Luvarus	n.
Lu*wack"	n.
Lux	v. t.
Lux"ate	a.
Lux"ate	v. t.
Lux*a"tion	n.
Luxe	n.
Luxembourger	n.
Luxembourgian	adj.
Luxemburger	n.
Luxemburger	adj.
Lux"ive	a.
Lux*ul"li*an*ite	n.
luxuria	n.
Lux*u"ri*ance	n.
Lux*u"ri*an*cy	n.
Lux*u"ri*ant	a.
Lux*u"ri*ant*ly	adv.
Lux*u"ri*ate	v. i.
Lux*u`ri*a"tion	n.
Lux`u*ri"e*ty	n.
Lux*u"ri*ous	a.
Lux"u*rist	n.
Lux"u*ry	n.
Luz	n.
lx	adj.
lxx	adj.
lxxx	adj.
-ly	suff.
Ly"am	n.
Lybian	adj.
Lycaena	n.
lycaenid	n.
Lycaenidae	n.
Lycaeon	n.
Ly"can*thrope	n.
Ly`can*thro"pi*a	n.
Ly`can*throp"ic	a.
Ly*can"thro*pist	n.
Ly*can"thro*pous	a.
Ly*can"thro*py	n.
lycee	n.
Ly*ce"um	n.
Lyche	a.
Ly"chee`	n.
Lych" gate`	n.
Lych"nis	n.
Lych"no*bite	n.
Lych"no*scope	n.
Lyc"ine	n.
Lycium	prop. n.
Lycoperdaceae	prop. n.
Lycoperdales	prop. n.
Ly`co*per"don	prop. n.
Lycopersicon	n.
Lycophyta	n.
Ly"co*pod	n.
Ly"co*pode	n.
Ly`co*po`di*a"ceous	a.
Lycopodineae	n.
Ly*cop"o*dite	n.
Ly`co*po"di*um	n.
Lycopsida	n.
Lycopus	n.
Lycosa	n.
Lycosidae	n.
Ly*cot"ro*pous	a.
Lydd"ite	n.
Lyd"en	n.
Lyd"i*an	a.
Lyd"ine	n.
Lye	n.
Lye	n.
Lye	n.
Ly`en*ceph"a*la	n. pl.
Ly`en*ceph"a*lous	a.
Ly"er*man	n.
Lygaeidae	n.
Lyginopteridales	n.
Lyginopteris	n.
Ly*go"di*um	n.
Lygus	n.
Ly"ing	p. pr. & vb. n.
Ly"ing	p. pr. & vb. n.
Ly"ing-in"	n.
Ly"ing*ly	adv.
Ly"ken	v. t.
Lym	n.
Ly*mail"	n.
lymantriid	n.
Lymantriidae	n.
Lyme" grass`	n.
Lymph	n.
Lym`pha*de*ni"tis	n.
Lym`pha*de*no"ma	n.
Lym*phan`ge*i"tis	n.
Lym*phan"gi*al	a.
Lymph"ate	a.
Lym*phat"ic	a.
Lym*phat"ic	n.
Lym*phi"tis	n.
Lymph node	a.
Lym*phog"ra*phy	n.
Lymph"oid	a.
Lym*pho"ma	n.
Lymph"y	a.
Lyn	n.
Lyn*ce"an	a.
Lynch	v. t.
Lynch"er	n.
Lynch" law`	n.
Lynde	n.
Lyne	n.
Lynx	n.
Lynx"-eyed`	a.
Lyonia	prop. n.
Lyonnais	prop. n.
Ly`on`naise"	a.
lyophilise	adj.
lyophilised	adj.
lyophilize	v. t.
lyophilized	adj.
Ly`o*po"ma*ta	n. pl.
Ly"ra	n.
Ly"ra*id	n.
Ly"rate	a.
Lyre	n.
Lyre" bird`	n.
lyreflower	n.
Lyr"ic	a.
Lyr"ic	n.
lyricality	n.
Lyr"ic*al*ly	adv.
Lyr"i*cism	n.
Ly"rid	n.
Ly"rie	n.
Ly*rif"er*ous	a.
Lyr"ism	n.
Lyr"ist	n.
Lysichiton	n.
Lysiloma	n.
Lysimachia	n.
Ly*sim"e*ter	n.
Ly"sis	n.
Lys"sa	n.
Ly*te"ri*an	a.
Lythe	n.
Lythe	a.
Lyth`on*thrip"tic	a.
Lyt"ta	n.
