T	v. t.
Taas	n.
Tab	n.
Ta*bac"co	n.
Ta*ba"nus	n.
Tab"ard	n.
Tab"ard*er	n.
Tab"a*ret	n.
Ta*bas"co sauce	n.
Tab"bi*net	n.
Tab"by	n.
Tab"by	a.
Tab"by	v. t.
Tab`e*fac"tion	n.
Tab"e*fy	v. t.
Ta*bel"lion	n.
Ta"ber	v. i.
Tab"erd	n.
Tab"er*na*cle	n.
Tab"er*na*cle	v. i.
Tab`er*nac"u*lar	a.
Ta"bes	n.
Ta*bes"cent	a.
Ta*bet"ic	a.
Tab"id	a.
Ta*bif"ic	a.
Tab"inet	n.
Tab"la*ture	n.
Ta"ble	n.
Ta"ble	v. t.
Ta"ble	v. i.
Ta`bleau"	n.
Ta`bleau" vi`vant"	n.
Ta"ble*book`	n.
Ta"ble*cloth`	n.
Ta"ble d'h<ocir/te"	n.
Ta"ble*man	n.
Ta"ble*ment	n.
Ta"bler	n.
Ta"ble*spoon`	n.
Ta"ble*spoon`ful	n.
Ta"blet	n.
Ta"ble*ware`	n.
Table work	n.
Tab"loid	n.
Tab"loid	a.
Ta*boo"	n.
Ta*boo"	v. t.
Ta*boo"	a.
Ta"bor	n.
Ta"bor	v. i.
Ta"bor	v. t.
Ta"bor*er	n.
Tab"o*ret	n.
Tab"o*rine	n.
Ta"bor*ite	n.
Ta"bour	n. & v.
Tab"ou*ret	n.
Tab"rere	n.
Tab"ret	n.
Ta*bu"	n. & v.
Tab"u*la	n.
Tab"u*lar	a.
Tab`u*lar*i*za"tion	n.
Tab"u*lar*ize	v. t.
Tab`u*la"ta	n. pl.
Tab"u*late	v. t.
Tab`u*la"tion	n.
Tac	n.
Tac"a*ma*hac`	n.
Ta*caud"	n.
Tac`-au-tac"	n.
Tace	n.
Tace	n.
Ta"cet	v. impers.
Tache	n.
Tache	n.
Tach*hy"drite	n.
Tach"i*na	n.
Ta*chis"to*scope	n.
Tach"o*graph	n.
Ta*chom"e*ter	n.
Ta*chom"e*try	n.
Tach"y*di*dax`y	n.
Tach`y*glos"sa	n. pl.
Tach"y*graph	n.
Ta*chyg"ra*pher	n.
Tach`y*graph"ic	a.
Ta*chyg"ra*phy	n.
Tach"y*lyte	n.
Ta*chym"e*ter	n.
Ta*chym"e*try	n.
Tach"y*scope	n.
Tac"it	a.
Tac"i*turn	a.
Tac`i*tur"ni*ty	n.
Tack	n.
Tack	n.
Tack	v. t.
Tack	v. i.
Tack"er	n.
Tack"et	n.
Tack"ey	a. & n.
Tack"ing	n.
Tac"kle	n.
tac"kle	n.
Tac"kle	v. t.
Tac"kled	a.
Tac"kling	n.
Tacks"man	n.
Tack"y	a.
Tack"y	a.
Tack"y	n.
Ta*con"ic	a.
Tact	n.
Tac"ta*ble	a.
Tact"ful	a.
Tac"tic	a.
Tac"tic	n.
Tac*ti"cian	n.
Tac"tics	n.
Tac"tile	a.
Tac*til"i*ty	n.
Tac"tion	n.
Tact"less	a.
Tac"tu*al	a.
Tad"pole`	n.
Tae"di*um	n.
Tael	n.
Taen	p. p.
Tae"ni*a	n.
Tae"ni*a*cide`	n.
Tae*ni"a*da	n. pl.
Tae"ni*a*fuge`	n.
Tae*ni"a*sis	n.
Tae`ni*a"ta	n. pl.
Tae*nid"i*um	n.
Tae`ni*o*glos"sa	n. pl.
Tae`ni*o*glos"sate	a.
Tae"ni*oid	a.
Tae`ni*oi"de*a	n. pl.
Tae*ni"o*la	n.
Tae`ni*o*so"mi	n. pl.
Taf"fer*er	n.
Taf"fe*ta	n.
Taff"rail	n.
Taf"fy	n.
Taf"i*a	n.
Tag	n.
Tag	v. t.
Tag	v. i.
Tag	n.
Ta*gal"	n.
Ta*ga"log	n.
Tag"belt`	n.
Tag day	n.
Tag"let	n.
Tagl"ia	n.
Tagl`ia*co"tain	a.
Tagl*io"ni	n.
Tag"lock`	n.
Tag"ni*cate	n.
Tag"-rag`	n. & a.
Tag sale	n.
Tag"sore`	n.
Tag"tail`	n.
Tag"u*an	n.
Ta`gui*ca"ti	n.
Ta"ha	n.
Ta*ha"leb	n.
Ta*hi"ti*an	a.
Tahr	n.
Tai	a.
Tai	n.
Tail	n.
Tail	a.
Tail	n.
Tail	v. t.
Tail	v. i.
Tail"age	n.
Tail"-bay`	n.
Tail"block`	n.
Tail"board`	n.
Tailed	a.
Tail"ing	n.
Taille	n.
Tail"less	a.
Tail"lie	n.
Tai"lor	n.
Tai"lor	v. i.
Tai"lor*ess	n.
Tai"lor*ing	adv.
Tai"lor-made`	a.
Tail"piece`	n.
Tail"pin"	n.
Tail"race`	n.
Tail"stock`	n.
Tail"-wa`ter	n.
Tail"zie	n.
Tain	n.
Taint	n.
Taint	v. i.
Taint	v. t.
Taint	v. t.
Taint	v. i.
Taint	n.
Taint	v. t.
Taint"less	a.
Taint"less*ly	adv.
Tain"ture	n.
Taint"worm`	n.
Tai"ping"	a.
Tai"ra	n.
Tairn	n.
Tait	n.
Ta*ja<cced/"u	n.
Taj Ma*hal"	prop. n.
Take	p. p.
Take	v. t.
Take	v. i.
Take	n.
Take"-in`	n.
Tak"en	p. p.
Take"off`	n.
Take" off`	v. i.
Take" off`	v. t.
take"o*ver	n.
Tak"er	n.
take` the heat"	phr.
Take"-up`	n.
Tak"ing	a.
Tak"ing	n.
Tak"ing-off`	n.
Tal"a*poin	n.
Tal"a*poin	n.
Ta*la"ri*a	n. pl.
Tal"bot	n.
Tal"bo*type	n.
Talc	n.
Tal*cose"	a.
Tal"cum	n.
Tale	n.
Tale	n.
Tale	v. i.
Tale"bear`er	n.
Tale"bear`ing	a.
Tale"bear`ing	n.
Ta"led	n.
Tale"ful	a.
Tal`e*gal"la	prop. n.
Tal"ent	n.
Tal"ent*ed	a.
Ta"les	n.
Tales"man	n.
Tale"tell`er	n.
Tale"wise`	adv.
Tal"ia*co`tian	a.
Tal`i*a"tion	n.
Ta"li*on	n.
Tal"i*pes	n.
Tal"i*pot	n.
Tal"is*man	n.
Tal`is*man"ic	a.
talk	v. i.
Talk	v. t.
Talk	n.
Talk"a*tive	a.
Talk"er	n.
Talk"ing	a.
Tall	a.
Tal"lage	n.
Tal"lage	v. t.
Tall"boy`	n.
Tal"li*er	n.
Tal"lis	n.
Tal"lith	n.
Tall"ness	n.
Tal"low	n.
Tal"low	v. t.
Tal"low*er	n.
Tal"low-face`	n.
Tal"low-faced`	a.
Tal"low*ing	n.
Tal"low*ish	a.
Tal"low*y	a.
Tall"wood`	n.
Tal"ly	n.
Tal"ly	v. t.
Tal"ly	v. i.
Tal"ly	adv.
Tal"ly*ho`	interj. & n.
Tal"ly*man	n.
Tal"ma	n.
Tal"mud	n.
Tal*mud"ic	a.
Tal"mud*ism	n.
Tal"mud*ist	n.
Tal`mud*is"tic	a.
Tal"on	n.
Ta*look"	n.
Ta*look"dar	n.
Tal"pa	n.
Ta"lus	n.
Ta"lus	n.
Tam`a*bil"i*ty	n.
Tam"a*ble	a.
Ta*ma"le	n.
Ta*man"du	n.
Ta`ma*noir"	n.
Tam"a*rack	n.
Tam"a*ric	n.
Tam"a*rin	n.
Tam"a*rind	n.
Tam"a*risk	n.
Tam"bac	n.
Tam"bour	n.
Tam"bour	v. t.
Tam*bour"a	n.
Tam`bou`rin"	n.
Tam`bour*ine"	n.
Tam`bour*ine"	n.
Tam"breet	n.
Tam`bu*rin"	n.
Tame	v. t.
Tame	a.
Tame	v. t.
Tame"a*ble	a.
Tame"less	a.
Tame"ly	adv.
Tame"ness	n.
Tam"er	n.
Ta*mer*lane"	prop. n.
Ta"mi*as	n.
Ta"mil	a.
Ta"mil	n.
Ta*mil"i*an	a. & n.
Tam"ine	n.
Tam"is	n.
Tam"kin	n.
Tam"my	n.
Tam`-o'-shan"ter	n.
Ta*mox"i*fen	n.
Tamp	v. t.
Tam"pan	n.
Tam"pe*on	n.
Tamp"er	n.
Tam"per	v. i.
Tam"per*er	n.
Tam*pi"co fi"ber	n.
Tam"pi*on	n.
Tam"poe	n.
Tam"pon	n.
Tam"pon	v. t.
Tam"poon	n.
Tam"-tam`	n.
Ta"mul	a. & n.
Tam"worth	n.
Tan	n.
Tan	n.
Tan	a.
Tan	v. t.
Tan	v. i.
Ta"na	n.
Tan"a*ger	n.
Tan"a*grine	a.
Tan"a*groid	a.
Tanak	n.
Ta*na"te	n.
Tan"dem	adv. & a.
Tan"dem	n.
Tan"dem cart	n.
Tang	n.
Tang	n.
Tang	n.
Tang	v. t.
Tang	v. i.
Tan"ga*lung	n.
Tan"ge*lo	n.
Tan"gence	n.
Tan"gen*cy	n.
Tan"gent	n.
Tan"gent	a.
Tan*gen"tal	a.
Tan*gen"tial	a.
Tan*gen"tial*ly	adv.
Tangent spoke	n.
Tang"fish`	n.
Tan*ghin"i*a	n.
Tan`gi*bil"i*ty	n.
Tan"gi*ble	a.
Tan"gle	v. t.
Tan"gle	v. i.
Tan"gle	n.
Tan"gle*fish`	n.
Tan"gling*ly	adv.
Tan"gly	a.
Tan"go	n.
Tan"gram	n.
Tangue	n.
Tan"gun	n.
Tang"whaup	n.
Tan"i*er	n.
Tan"ist	n.
Tan"ist*ry	n.
Ta"nite	n.
Tank	n.
Tank	n.
Tan"ka	n.
Tank"age	n.
Tank"ard	n.
Tan"ki*a	n.
Tank"ling	n.
Tank ship	n.
Tank war"fare	n.
Tan"ling	n.
Tan"na*ble	a.
Tan"nage	n.
Tan"nate	n.
Tan"ner	n.
Tan"ner	n.
Tan"ner*y	n.
Tan"nic	a.
Tan"ni*er	n.
Tan"ni*gen	n.
Tan"nin	n.
Tan"ning	n.
Tan"rec	n.
Tan"sy	n.
Tant	n.
Tan"ta*late	n.
Tan*tal"ic	a.
Tan"ta*lism	n.
Tan"ta*lite	n.
Tan`ta*li*za"tion	n.
Tan"ta*lize	v. t.
Tan"ta*li`zer	n.
Tan"ta*li`zing*ly	adv.
Tan"ta*lum	n.
Tan"ta*lus	n.
Tan"ta*mount`	a.
Tan"ta*mount`	v. i.
Tan*tiv"y	adv.
Tan*tiv"y	n.
Tan*tiv"y	v. i.
Tan"tra	n.
Tan"trism	n.
Tan"trum	n.
Tan"yard`	n.
Tan`y*stom"a*ta	n. pl.
Ta"o*ism	n.
Tao`tai"	n.
Tap	v. t.
Tap	n.
Tap	v. i.
Tap	n.
Tap	v. t.
Ta"pa	n.
Tap`a*de"ra	n.
Ta`pa*yax"in	n.
Tape	n.
Tape	v. t.
Tape deck	n.
Tape"line`	n.
Ta"per	n.
Ta"per	a.
Ta"per	v. i.
Ta"per	v. t.
Tape recorder	n.
Tape recording	n.
Ta"pered	a.
Ta"per*ing	a.
Ta"per*ness	n.
Tap"es*try	n.
Tap"es*try	v. t.
Tap"es*try bee"tle	n.
Tap"e*ti	n.
Ta*pe"tum	n.
Tape"worm`	n.
Tap"house`	n.
Taph*ren"chy*ma	n.
Tap"i*nage	n.
Tap`i*o"ca	n.
Ta"pir	n.
Ta"pir*oid	a.
Ta"pis	n.
Tap"is	v. t.
Tap"is*er	n.
Tap"ish	v. i.
Tap"lash`	n.
Tap"lings	n. pl.
Ta*po"a ta"fa	n.
Tap"per	n.
Tap"pes*ter	n.
Tap"pet	n.
Tap"pet rod	v. i.
Tap"pit hen`	n.
Tap"room`	n.
Tap"root`	n.
Tap"ster	n.
Ta"qua-nut`	n.
Tar	n.
Tar	n.
Tar	v. t.
Tar"a*nis	n.
Tar`an*tass"	n.
Tar`an*tel"la	n.
Tar"ant*ism	n.
Ta*ran"tu*la	n.
Ta*ran"tu*la`ted	a.
Tar*bog"an	n. & v.
Tar*boosh"	n.
Tar*da"tion	n.
Tar`di*gra"da	n. pl.
Tar"di*grade	a.
Tar"di*grade	n.
Tar"di*gra`dous	a.
Tar"di*ly	adv.
Tar"di*ness	n.
Tar`di*ta"tion	n.
Tar"di*ty	n.
Tar"do	a.
Tar"do	n.
Tar"dy	a.
Tar"dy	v. t.
Tare	imp.
Tare	n.
Tare	n.
Tare	v. t.
Tared	a.
Ta*ren"te	n.
Tar"ent*ism	n.
Ta*ren"tu*la	n.
Targe	n.
Tar"get	n.
Tar"get date	n.
Tar"get language	n.
Tar"get*ed	a.
Tar`get*eer"	n.
Tar"gum	n.
Tar"gum*ist	n.
Tar"heel	n.
Tar"heel state	n.
Tar"iff	n.
Tar"iff	v. t.
Tar"in	n.
Tar"ing	n.
Tar"la*tan	n.
Tarn	n.
Tar"nish	v. t.
Tar"nish	v. i.
Tar"nish	n.
Tar"nish*er	n.
Ta"ro	n.
Tar"ot	n.
Tar"pan	n.
Tar*pau"lin	n.
Tar*pe"ian	a.
Tar"pon	n.
Tar"pum	n.
Tar"quin*ish	a.
Tar"race	n.
Tar"ra*gon	n.
Tar"ras	n.
Tarre	v. t.
Tar"ri*ance	n.
Tar"ri*er	n.
Tar"ri*er	n.
Tar"rock	n.
Tar"ry	a.
Tar"ry	v. i.
Tar"ry	v. t.
Tar"ry	n.
Tar"sal	a.
Tar"sal	n.
Tar*sa"le	n.
Tarse	n.
Tarse	n.
Tar*sec"to*my	n.
Tar"sel	n.
Tar"si	n.
Tar"si*a	n.
Tar"si*er	n.
Tar"si*us	n.
Tar"so-	a.
Tar`so*met`a*tar"sus	n.
Tar*sor"rha*phy	n.
Tar*sot"o*my	n.
Tar"sus	n.
Tart	a.
Tart	n.
Tar"tan	n.
Tar"tan	n.
Tar"tar	n.
Tar"tar	n.
Tar"tar	a.
Tar"tar	n.
Tar"tar*a`ted	a.
Tar*ta"re*an	a.
Tar*ta"re*ous	a.
Tar*ta"ri*an	a.
Tar*ta"ri*an	n.
Tar*tar"ic	a.
Tar"tar*ine	n.
Tar"tar*ize	v. t.
Tar"tar*ize	v. t.
Tar"tar*ous	a.
Tar"tar*ous	a.
Tar"ta*rum	n.
Tar"ta*rus	prop. n.
Tar"ta*ry	n.
Tar*ti"ni's tones`	a.
Tart"let	n.
Tart"ly	adv.
Tart"ness	n.
Tar*tral"ic	a.
Tar*tram"ate	n.
Tar*tram"ic	a.
Tar*tram"ide	n.
Tar"trate	n.
Tar"tra`ted	a.
Tar"tra*zine	n.
Tar*trel"ic	a.
Tar"tro-	n.
Tar*tron"ic	a.
Tar"tro*nyl	n.
Tar`tro*vin"ic	a.
Tar*tuffe"	n.
Tar*tuff"ish	a.
Tar"weed`	n.
Tas	n.
Tas	v. t.
Tas"co	n.
Ta*sim"er	n.
Task	n.
Task	v. t.
Task"er	n.
Task"mas`ter	n.
Task wage	n.
Tas"let	n.
Tas*ma"ni*an	a.
Tasse	n.
Tas"sel	n.
Tas"sel	n.
Tas"sel	n.
Tas"sel	v. i.
Tas"sel	v. t.
Tas"set	n.
Tast"a*ble	a.
Taste	v. t.
Taste	v. i.
Taste	n.
Taste"ful	a.
Taste"less	a.
Tast"er	n.
Tast"i*ly	adv.
Tast"ing	n.
Tas"to	n.
Tast"y	a.
Tat	n.
Tat	n.
Ta*tau"pa	n.
Tatch	n.
Tath	3d pers. sing. pres.
Tath	n.
Tath	v. t.
Ta*tou"	n.
Tat"ou*ay	n.
Tat"ou*hou	n.
Tatt	v. t. & i.
Tat"ta	n.
Tat"ter	n.
Tat"ter	n.
Tat"ter	v. t.
Tat`ter*de*mal"ion	n.
Tat"ter*sall's	n.
Tat"ting	n.
Tat"tle	v. i.
Tat"tle	n.
Tat"tler	n.
Tat"tler*y	n.
Tat"tling	a.
Tat*too"	n.
Tat*too"	v. t.
Tat*too"	n.
Tat"ty	n.
Ta*tu"	n.
Ta*tu"si*id	n.
Tau	n.
Tau	n.
Taught	a.
Taught	imp. & p. p.
Taunt	a.
Taunt	v. t.
Taunt	n.
Taunt"er	n.
Taunt"ing	a. & n.
Taunt"ing*ly	adv.
Taunt"ress	n.
Tau"pie	n.
Taur	n.
Tau`ri*cor"nous	a.
Tau"rid	n.
Tau`ri*dor"	n.
Tau"ri*form	a.
Tau"rine	a.
Tau"rine	n.
Tau`ro*cho"late	n.
Tau`ro*chol"ic	a.
Tau"ro*col	n.
Tau`ro*ma"chi*an	a.
Tau*rom"a*chy	n.
Tau"rus	n.
Tau*ryl"ic	a.
Taut	a.
Tau*taug"	n.
Tau`te*gor"ic*al	a.
Tau"to*chrone	n.
Tau*toch"ro*nous	a.
Tau*tog"	n.
Tau`to*log"ic	a.
Tau`to*log"ic*al	a.
Tau*tol"o*gist	n.
Tau*tol"o*gize	v. i.
Tau*tol"o*gous	a.
Tau*tol"o*gy	n.
Tau`to*mer"ic	a.
Tau*tom"er*ism	n.
Tau`to*ou"si*an	a.
Tau`to*phon"ic*al	a.
Tau*toph"o*ny	n.
Tau`to*zon"al	a.
Tav"ern	n.
Tav"ern*er	n.
Tav"ern*ing	n.
Tav"ern*man	n.
Taw	n.
Taw	v. t.
Taw	v. t.
Taw	n.
Taw"dri*ly	adv.
Taw"dri*ness	n.
Taw"dry	a.
Taw"dry	n.
Taw"er	n.
Taw"er*y	n.
Taw"ni*ness	n.
Taw"ny	a.
Taws	n.
Tax	n.
Tax	v. t.
Tax`a*bil"i*ty	n.
Tax"a*ble	a.
Tax`as*pid"e*an	a.
Tax*a"tion	n.
Tax certificate	n.
Tax`e*op"o*da	n. pl.
Tax"er	n.
Tax"gath`er*er	n.
Tax"i*arch	n.
Tax"i*corn	n.
Tax`i*der"mic	a.
Tax"i*der`mist	n.
Tax"i*der`my	n.
taximeter	n.
Tax"ine	n.
Tax"is	n.
-tax"is	n.
tax"i	n.
tax"i*cab	n.
Tax"less	a.
Tax*ol"o*gy	n.
Tax"on	n.
Tax`o*nom"ic	a.
Tax*on"o*mist	n.
Tax*on"o*my	n.
Tax"or	n.
Tax"pay`er	n.
Tay"lor-White" proc`ess	n.
Tay"-Sachs Disease	n.
Ta"zel	n.
Taz"za	n.
T" cart`	n.
Tchick	n.
tchotch"ke	n.
T connection	a.
Tea	n.
Tea	v. i.
Tea"ber`ry	n.
Teach	v. t.
Teach	v. i.
Teach"a*ble	a.
Teach"a*ble*ness	n.
Teache	n.
Teach"er	n.
Teach"ing	n.
Teach"less	a.
Tea"cup`	n.
Tea"cup`ful	n.
Tead	n.
Tea"gle	n.
Teague	n.
Teak	n.
Tea"ket`tle	n.
Teal	n.
Team	n.
Team	v. i.
Team	v. t.
Teamed	a.
Team"ing	n.
Team"ster	n.
Team"work`	n.
Tea"pot`	n.
Tea"poy	n.
Tear	n.
Tear	v. t.
Tear	v. i.
Tear	n.
Tear"er	n.
Tear"-fall`ing	a.
Tear"ful	a.
Tear"less	a.
Tear"pit`	n.
Tear"-thumb`	n.
Tear"y	a.
Tea"-sau`cer	n.
Tease	v. t.
Tease	n.
Tea"sel	n.
Tea"sel	v. t.
Tea"sel*er	n.
Tea"sel*ing	n.
Teas"er	n.
Tea"sle	n. & v. t.
Tea"spoon`	n.
Tea"spoon`ful	n.
Teat	n.
Teat"ed	a.
Teathe	n. & v.
Teat"ish	a.
Teaze"-hole`	n.
Tea"zel	n. & v. t.
Tea"zer	n.
Tea"zle	n. & v. t.
Te"beth	n.
Tech"i*ly	adv.
Tech"i*ness	n.
Tech"nic	a.
Tech"nic	n.
Tech"nic*al	a.
Tech`ni*cal"i*ty	n.
Tech"nic*al*ly	adv.
Tech"nic*al*ness	n.
Tech"nic*als	n. pl.
Tech*ni"cian	n.
Tech"ni*cist	n.
Tech`ni*co*log"ic*al	a.
Tech`ni*col"o*gy	n.
Tech`ni*col"or	n.
Tech"nics	n.
Tech"ni*phone	n.
Tech`nique"	n.
Tech"nism	n.
Tech"no	n.
Tech"no*bab`ble	n.
tech*noc"ra*cy	n.
tech"no*crat	n.
Tech*nog"ra*phy	n.
Tech`no*log"ic	a.
Tech`no*log"ic*al	a.
Tech*nol"o*gist	n.
Tech*nol"o*gy	n.
Tech"y	a.
Tec`ti*branch	n.
Tec`ti*bran"chi*a	n. pl.
Tec`ti*bran`chi*a"ta	n. pl.
Tec`ti*bran"chi*ate	a.
Tect"ly	adv.
Tec*tol"o*gy	n.
Tec*ton"ic	a.
Tec*ton"ics	n.
Tec*to"ri*al	a.
Tec"tri*ces	n. pl.
Te"cum	n.
Ted	v. t.
Ted"der	n.
Ted"der	n.
Ted"der	v. t.
Te*des"co	a.
Te` De"um	n.
Te`di*os"i*ty	n.
Te"di*ous	a.
Te"di*um	n.
Tee	n.
Tee	n.
Tee	v. t.
Teeing ground	n.
Teel	n.
Teel"seed`	n.
Teem	v. t.
Teem	v. t.
Teem	v. i.
Teem	v. t.
Teem"er	n.
Teem"ful	a.
Teem"ing	a.
Teem"less	a.
Teen	n.
Teen	v. t.
Teen	v. t.
Teen	n.
Teen"age	n.
Teen"age`	n.
Teen"ag`er	n.
Teend	v. t. & i.
Teen"ful	a.
Teens	n. pl.
Tee"ny	a.
Teen"y	a.
Tee*ong"	n.
Teest	n.
Tees"wa`ter	n.
Tee"tan	n.
Tee"tee	n.
Tee"ter	v. i. & t.
Tee"ter-tail`	n.
Teeth	n.
Teeth	v. i.
Teeth"ing	n.
Tee*to"tal	a.
Tee*to"tal*er	n.
Tee*to"tal*ism	n.
Tee*to"tal*ly	adv.
Tee*to"tum	n.
Tee-to"-tum	n.
Tee"tuck	n.
Tee"uck	n.
Tee"wit	n.
Teg	n.
Teg"men	n.
Teg*men"tal	a.
Teg*men"tum	n.
Te*guex"in	n.
Teg"u*la	n.
Teg"u*lar	a.
Teg`u*la"ted	a.
Teg"u*ment	n.
Teg`u*men"ta*ry	a.
Te-hee"	n. & interj.
Te-hee"	v. i.
Teil	n.
Teind	n.
Teine	n.
Tein"land	n.
Tei"no*scope	n.
Teint	n.
Tein"ture	n.
Tek	n.
Tel`a*mo"nes	n. pl.
Tel*an`gi*ec"ta*sis	n.
Tel*an`gi*ec"ta*sy	n.
Te"lar*ly	adv.
Te"la*ry	a.
Tel*au"to*gram	n.
Tel*au"to*graph	n.
Tel`e*chi"ro*graph	n.
Tel"e*du	n.
Te*le"ga	n.
Te*leg"o*ny	n.
Tel"e*gram	n.
Tel`e*gram*mic	a.
Tel"e*graph	n.
Tel"e*graph	v. t.
Te*leg"ra*pher	n.
telegraphese	n.
Tel`e*graph"ic	a.
Tel`e*graph"ic*al	a.
Te*leg"ra*phist	n.
Telegraph plant	n.
Tel`e*graph"o*scope	n.
Te*leg"ra*phy	n.
Tel`e*gu"	prop. a. & n.
Tel`e*hy`dro*ba*rom"e*ter	n.
Tel`e-i*con"o*graph	n.
tel`e*ki*ne"sis	n.
Tel`-el-A*mar"na	n.
Tel`e*lec"tric	a.
Tel`e*lec"tro*scope	n.
telemarketing	n.
Tel`e*me*chan"ic	a.
Tel`e*ma"chus	prop. n.
Tel`e*me`te*or"o*graph	n.
Te*lem"e*ter	n.
Tel`e*met"ro*graph	n.
Te*lem"e*try	n.
Tel`e*mo"tor	n.
telencephalon	n.
Tel*en"er*gy	n.
Te*len"gi*scope	n.
Te`le*o*ceph"a*li	n. pl.
Te`le*o*log"ic*al	a.
Te`le*ol"o*gist	n.
Te`le*ol"o*gy	n.
Te"le*o*phore`	n.
Te`le*or*gan"ic	a.
Te`le*o*saur"	n.
Te`le*o*sau"rus	n.
Te"le*ost	n.
Te`le*os"te*an	a.
Te`le*os"te*i	n. pl.
Te"le*os`to*mi	n. pl.
Te`le*o*zo"ic	a.
Te*le*o*zo"on	n.
Te*lep"a*thy	n.
Tel"e*pheme	n.
Tel"e*phone	n.
Tel"e*phone	v. t.
Tel`e*phone ex*change"	a.
Tel`e*phon"ic*al*ly	adv.
Te*leph"o*ny	n.
Tel"e*phote	n.
Tel`e*pho"to	a.
telephoto	n.
Tel`e*pho"to*graph	n.
Tel`e*pho`to*graph"ic	a.
Tel`e*pho*tog"ra*phy	n.
Tel`e*pho"to lens	n.
Tel`e*po*lar"i*scope	n.
Tel`e*ryth"in	n.
Tel"e*scope	n.
Tel"e*scope	v. i.
Tel"e*scope	v. t.
Tel"e*scope	a.
Telescope bag	a.
Tel`e*scop"ic*al*ly	adv.
Tel`e*scop"ic sight`	a.
Te*les"co*pist	n.
Te*les"co*py	n.
Tel"e*seism	n.
Tel"e*seme	n.
Tel"esm	n.
Tel`es*mat"ic	a.
Tel`e*spec"tro*scope	n.
Tel`e*ste"re*o*graph`	n.
Tel`e*ste"re*o*scope	n.
Te*les"tic	a.
Te*les"tich	n.
Tel`e*ther"mo*graph	n.
Tel`e*ther*mom"e*ter	n.
Te*leu"to*spore	n.
Tel"ford	a.
Tel"ford*ize	v. t.
Tel`har*mon"ic	a.
Tel`har*mo"ni*um	n.
Tel"ic	a.
Tell	v. t.
Tell	v. i.
Tell	n.
Tell	n.
Tell"a*ble	a.
Tel"len	n.
Tell"er	n.
Tell"er*ship	n.
Tel*li"na	n.
Tell"ing	a.
Tell"tale`	a.
Tell"tale`	n.
Tel*lu"ral	a.
Tel"lu*rate	n.
Tel"lu*ret	n.
Tel"lu*ret`ed	n.
Tel`lur*hy"dric	a.
Tel*lu"ri*an	a.
Tel*lu"ri*an	n.
Tel*lu"ric	a.
Tel"lu*ride	n.
Tel"lu*rism	n.
Tel"lu*rite	n.
Tel*lu"ri*um	n.
Tel"lu*rize	v. t.
Tel"lu*rous	a.
Tel`o*dy*nam"ic	a.
Tel`oo*goo"	n.
Te*lot"ro*cha	n.
Te*lot"ro*chal	a.
Tel"o*type	n.
Tel"pher	n.
Tel"pher*age	n.
Tel"son	n.
Tel`u*gu"	n.
Tel`u*gu"	a.
Tem*blor"	n.
Tem`er*a"ri*ous	a.
Tem`er*a"tion	n.
Te*mer"i*ty	n.
Tem"er*ous	a.
Tem*pe"an	a.
Tem"per	v. t.
Tem"per	n.
Tem"per	v. i.
Tem"pe*ra	n.
Tem"per*a*ble	a.
Tem"per*a*ment	n.
Tem`per*a*men"tal	a.
Tem"per*ance	n.
Tem"per*an*cy	n.
Tem"per*ate	a.
Tem"per*ate	v. t.
Tem"per*ate*ly	adv.
Tem"per*ate*ness	n.
Tem"per*a*tive	a.
Tem"per*a*ture	n.
Tem"pered	a.
Tem"per*er	n.
Tem"per*ing	n.
Tem"per screw	n.
Tem"pest	v. t.
Tem"pest	v. i.
Tem*pes"tive	a.
Tem`pes*tiv"i*ly	n.
Tem*pes"tu*ous	a.
Tem"plar	n.
Tem"plar	a.
Tem"plate	n.
Tem"ple	n.
Tem"ple	n.
Tem"ple	n.
Tem"ple	v. t.
Tem"pled	a.
Tem"plet	n.
Tem"po	n.
Tem"po*ral	a.
Tem"po*ral	a.
Tem"po*ral	n.
Tem`po*ral"i*ty	n.
Tem"po*ral*ly	adv.
Tem"po*ral*ness	n.
Tem"po*ral*ty	n.
Tem`po*ra"ne*ous	a.
Tem"po*ra*ri*ly	adv.
Tem"po*ra*ri*ness	n.
Tem"po*ra*ry	a.
Tem"po*rist	n.
Tem`po*ri*za"tion	n.
Tem"po*rize	v. t.
Tem"po*ri`zer	n.
Tem"po*ri`zing*ly	adv.
Tem"po*ro-	a.
Tem`po*ro*fa"cial	a.
Tem`po*ro*ma"lar	a.
Tem`po*ro*max"il*la*ry	a.
Temps	n.
Tempse	n.
Tempt	v. t.
Tempt`a*bil"i*ty	n.
Tempt"a*ble	a.
Temp*ta"tion	n.
Temp*ta"tion*less	a.
Temp*ta"tious	a.
Tempt"er	n.
Tempt"ing	a.
Tempt"ress	n.
Temse	n.
Tem"u*lence	n.
Tem"u*lent	a.
Tem"u*lent*ive	a.
Ten	a.
Ten	n.
Ten`a*bil"i*ty	n.
Ten"a*ble	a.
Ten`a*ble*ness	n.
Ten"ace	n.
Te*na"cious	a.
Te*nac"i*ty	n.
Te*nac"u*lum	n.
Ten"a*cy	n.
Te*naille"	n.
Te*nail"lon	n.
Ten"an*cy	n.
Ten"ant	n.
Ten"ant	v. t.
Ten"ant*a*ble	a.
Ten"ant*less	a.
Ten"ant*ry	n.
Ten"ant saw`	n.
Tend	v. t.
Tend	v. t.
Tend	v. i.
Tend	v. i.
Tend"ance	n.
Tend"ence	n.
Tend"en*cy	n.
Tend"er	n.
Ten"der	v. t.
Ten"der	n.
Ten"der	a.
Ten"der	n.
Ten"der	v. t.
Ten"der*foot`	n.
Ten"der-heart`ed	a.
Ten"der-heft`ed	a.
Ten"der*ling	n.
Ten"der*loin`	n.
Ten"der*ly	adv.
Ten"der*ness	n.
Ten"di*nous	a.
Tend"ment	n.
Ten"don	n.
Ten"don*ous	a.
Ten`do*syn`o*vi"tis	n.
Ten"drac	n.
Ten"dre	n.
Ten*dresse"	n.
Ten"dril	n.
Ten"dril	a.
Ten"driled	a.
Ten"dron	n.
Ten"dry	n.
Tene	n. & v.
Ten"e*brae	n.
Te*neb"ri*cose`	a.
Ten`e*brif"ic	a.
Ten`e*brif"ic*ous	a.
Te*ne"bri*ous	a.
Ten"e*brose`	a.
Ten`e*bros"i*ty	n.
Ten"e*brous	a.
Ten"e*ment	n.
Ten`e*men"tal	a.
Ten`e*men"ta*ry	a.
Ten"ent	n.
Ten"er*al	a.
Ten`er*iffe"	n.
Te*ner"i*ty	n.
Te*nes"mic	a.
Te*nes"mus	n.
Ten"et	n.
Ten"fold`	a. & adv.
Te"ni*a	n.
Te"ni*oid	a.
Ten"nant*ite	n.
Ten`n<eacute/"	n.
Ten"nis	n.
Ten"nis	v. t.
Ten*no"	n.
Ten"nu	n.
Ten`ny*so"ni*an	a.
Ten"-o'*clock`	n.
Ten"on	n.
Ten"on	v. t.
Te*no"ni*an	a.
Ten`o*ni"tis	n.
Ten`o*ni"tis	n.
Ten"or	n.
Te*nor"rha*phy	n.
Ten`o*si"tis	n.
Ten`o*syn`o*vi"tis	n.
Ten"o*tome	n.
Te*not"o*my	n.
Ten"pen*ny	a.
Ten"pen*ny	a.
Ten"pins	n.
Ten"-pound`er	n.
Ten"rec	n.
Tense	n.
Tense	a.
Ten`si*bil"i*ty	n.
Ten"si*ble	a.
Ten"sile	a.
Ten"siled	a.
Ten*sil"i*ty	n.
Ten"sion	n.
Ten"sioned	a.
Ten"si*ty	n.
Ten"sive	a.
Ten"sor	n.
Ten"-strike`	n.
Ten"sure	n.
Tent	n.
Tent	n.
Tent	v. t.
Tent	v. t.
Tent	n.
Tent	n.
Tent	v. i.
Ten"ta*cle	n.
Ten"ta*cled	a.
Ten*tac"u*lar	a.
Ten*tac`u*la"ta	n. pl.
Ten*tac"u*late	a.
Ten`ta*cu*lif"e*ra	n. pl.
Ten`ta*cu*lif"er*ous	a.
Ten`ta*cu"li*form	a.
Ten*tac"u*lite	n.
Ten*tac"u*lo*cyst	n.
Ten*tac"u*lum	n.
Tent"age	n.
Ten*ta"tion	n.
Ten*ta"tive	a.
Ten*ta"tive	n.
Tent"ed	a.
Ten"ter	n.
Ten"ter	n.
Ten"ter	v. i.
Ten"ter	v. t.
Tent"ful	n.
Tenth	a.
Tenth	n.
Tenth"ly	adv.
Tenth"me`ter	n.
Ten`thre*din"i*des	n. pl.
Ten"tif	a.
Ten"tif*ly	adv.
Ten*tig"i*nous	a.
Tent"mak`er	n.
Ten*to"ri*um	n.
Tent"o*ry	n.
Tent"wort`	n.
Ten"u*ate	v. t.
Ten`u*i*fo"li*ous	a.
Te*nu"i*ous	a.
Ten`u*i*ros"ter	n.
Ten`u*i*ros"tral	a.
Ten`u*i*ros"tres	n. pl.
Ten"u*is	n.
Te*nu"i*ty	n.
Ten"u*ous	a.
Ten"ure	n.
Te`o*cal"li	n.
Te`o*sin"te	n.
Tep"al	n.
Tep*ee"	n.
Tep`e*fac"tion	n.
Tep"e*fy	v. t. & i.
Teph"ra*man`cy	n.
Teph"rite	n.
Teph"ro*ite	n.
Te*phro"si*a	n.
Tep"id	a.
Te*pid"i*ty	n.
Te"por	n.
Te*qui"la	n.
Ter-	a.
Ter`a*cryl"ic	a.
Ter"aph	n.
Ter"a*phim	n. pl.
Ter"a*pin	n.
Te*rat"ic*al	a.
Ter`a*tog"e*ny	n.
Ter"a*toid	a.
Ter`a*to*log"ic*al	a.
Ter`a*tol"o*gy	n.
Ter`a*to"ma	n.
Ter"bic	a.
Ter"bi*um	n.
Terce	n.
Ter"cel	n.
Terce"let	n.
Ter"cel*lene	n.
Ter*cen"te*na*ry	a.
Ter"cet	n.
Ter"cine	n.
Ter"e*bate	n.
Ter"e*bene	n.
Ter`e*ben"thene	n.
Te*reb"ic	a.
Ter`e*bi*len"ic	a.
Ter"e*binth	n.
Ter`e*bin"thic	a.
Ter`e*bin"thi*nate	a.
Ter`e*bin"thine	a.
Ter"e*bra	n.
Ter"e*brant	a.
Ter`e*bran"ti*a	n. pl.
Ter"e*brate	v. t.
Ter"e*bra`ting	a.
Ter`e*bra"tion	n.
Ter`e*brat"u*la	n.
Ter`e*brat"u*lid	n.
Ter`e*bra*tu"li*form	a.
Ter"e*dine	n.
Te*re"do	n.
Ter"ek	n.
Ter*eph"tha*late	n.
Ter`eph*thal"ic	a.
Ter"et	a.
Te*rete"	a.
Te*re"tial	a.
Ter"e*tous	a.
Ter"gal	a.
Ter"gant	a.
Ter*gem"i*nal	a.
Ter*gem"i*nous	a.
Ter*gif"er*ous	a.
Ter"gite	n.
Ter"gi*ver*sate	v. i.
Ter`gi*ver*sa"tion	n.
Ter"gi*ver*sa`tor	n.
Ter"gum	n.
Te"rin	n.
Term	n.
Term	v. t.
Ter"ma	n.
Ter"ma*gan*cy	n.
Ter"ma*gant	n.
Ter"ma*gant	a.
Ter`ma*ta"ri*um	n.
Ter"ma*ta*ry	n.
Term day	n.
Ter"mes	n.
Ter"mi*na*ble	a.
Ter"mi*nal	a.
Ter"mi*nal	n.
Ter`mi*na"li*a	n. pl.
Ter"mi*nant	n.
Ter"mi*nate	v. t.
Ter"mi*nate	v. i.
Ter`mi*na"tion	n.
Ter`mi*na"tion*al	a.
Ter"mi*na*tive	a.
Ter"mi*na`tor	n.
Ter"mi*na*to*ry	a.
Ter"mine	v. t.
Ter"mi*ner	n.
Ter"mi*nism	n.
Ter"mi*nist	n.
Ter`mi*no*log"ic*al	a.
Ter`mi*nol"o*gy	n.
Term insurance	n.
Ter"mite	n.
Term"less	a.
Term"ly	a.
Term"ly	adv.
Ter`mo*nol"o*gy	n.
Term"or	n.
Term policy	n.
Tern	a.
Tern	n.
Ter"na*ry	a.
Ter"na*ry	n.
Ter"nate	a.
Terne"plate`	n.
Ter"ni*on	n.
Ter"pene	n.
Ter*pen"tic	a.
Ter`pe*nyl"ic	a.
Ter"pi*lene	n.
Ter"pin	n.
Ter"pin*ol	n.
Terp*sich"o*re	n.
Terp`sich*o*re"an	a.
Ter"ra	n.
Ter"race	n.
Ter"race	v. t.
Ter"ra*cul`ture	n.
Ter"ra in*cog"ni*ta	n.
Ter"rane	n.
Ter"ra*pin	n.
Ter*ra"que*ous	a.
Ter"rar	n.
Ter"ras	n.
Ter*reen"	n.
Ter*re"i*ty	n.
Ter"rel	n.
Terre"mote`	n.
Ter*rene"	n.
Ter*rene"	a.
Ter*rene"	n.
Ter*ren"i*ty	n.
Ter"re*ous	a.
Terre"plein`	n.
Ter*res"tre	a.
Ter*res"tri*al	a.
Ter*res"tri*al	n.
Ter*res"tri*fy	v. t.
Ter*res"tri*ous	a.
Ter"ret	n.
Terre"-ten`ant	n.
Terre"-verte`	n.
Ter"ri*ble	a.
Ter*ric"o*lae	n. pl.
Ter`ri*en"ni*ak	n.
Ter"ri*er	n.
Ter"ri*er	n.
Ter*rif"ic	a.
Ter*rif"ic*al	a.
Ter*rif"ic*al*ly	adv.
Ter"ri*fy	v. t.
Ter*rig"e*nous	a.
Ter*rine"	n.
Ter`ri*to"ri*al	a.
Ter`ri*to`ri*al"i*ty	n.
Ter`ri*to"ri*al*ize	v. t.
Ter`ri*to"ri*al*ly	adv.
Ter`ri*to"ri*al wa"ters	a.
Ter"ri*to*ry	n.
Ter"ror	n.
Ter"ror*ism	n.
Ter"ror*ist	n.
Ter"ror*ize	v. t.
Ter"ror*less	a.
Ter"ry	n.
Ter*sanc"tus	n.
Terse	a.
Ter*sul"phide	n.
Ter*sul"phu*ret	n.
Ter"-ten`ant	n.
Ter"tial	a. & n.
Ter"tian	a.
Ter"tian	n.
Ter"ti*a*ry	a.
Ter"ti*a*ry	n.
Ter"ti*ate	v. t.
Ter"ti*um quid	n.
Ter"za ri"ma	n.
Tes"la coil	a.
Tes`sel*la"ta	n. pl.
Tes"sel*late	v. t.
Tes"sel*late	a.
Tes"sel*la`ted	a.
Tes`sel*la"tion	n.
Tes"se*ra	n.
Tes`se*ra"ic	a.
Tes"se*ral	a.
Tes"su*lar	a.
Test	n.
Test	v. t.
Test	n.
Test	v. i.
Test	n.
Test"a*ble	a.
Tes*ta"ce*a	n. pl.
Tes*ta"cean	n.
Tes*ta`ce*og"ra*phy	n.
Tes*ta`ce*ol"o*gy	n.
Tes*ta"ceous	a.
Tes"ta*cy	n.
Tes"ta*ment	n.
Tes`ta*men"tal	a.
Tes`ta*men"ta*ry	a.
Tes`ta*men*ta"tion	n.
Tes"ta*men*tize	v. i.
Tes*ta"mur	n.
Tes"tate	a.
Tes"tate	n.
Tes*ta"tion	n.
Tes*ta"tor	n.
Tes*ta"trix	n.
Tes"te	n.
Tes"ter	n.
Tes"ter	n.
Tes"tern	n.
Tes"tern	v. t.
Tes"tes	n.
Tes`ti*car"di*nes	n. pl.
Tes"ti*cle	n.
Tes"ti*cond	a.
Tes*tic"u*lar	a.
Tes*tic"u*late	a.
Tes`ti*<egrave/re"	n.
Tes"tif	a.
Tes`ti*fi*ca"tion	n.
Tes"ti*fi*ca`tor	n.
Tes"ti*fi`er	n.
Tes"ti*fy	v. i.
Tes"ti*fy	v. t.
Tes"ti*fy	adv.
Tes`ti*mo"ni*al	n.
Tes`ti*mo"ni*al	a.
Tes"ti*mo*ny	n.
Tes"ti*mo*ny	v. t.
Tes"ti*ness	n.
Test"ing	n.
Tes"tis	n.
Test"-mark`et	v. t.
Tes"ton	n.
Tes*tone"	n.
Tes*toon"	n.
Tes*tos"ter*one	n.
Tes*tu"di*nal	a.
Tes*tu`di*na"ri*ous	a.
Tes*tu`di*na"ta	n. pl.
Tes*tu"di*nate	a.
Tes`tu*din"e*ous	a.
Tes*tu"do	n.
Tes"ty	a.
Te*tan"ic	a.
Te*tan"ic	n.
Tet"a*nin	n.
Tet`a*ni*za"tion	n.
Tet"a*nize	v. t.
Tet"a*noid	a.
Tet`a*no*mo"tor	n.
Tet"a*nus	n.
Tet"a*ny	n.
Te*tard"	n.
Te*tar`to*he"dral	a.
Te*tar`to*he"drism	n.
Te*taug"	n.
Tetch"i*ness	n.
Tetch"y	a.
T<ecir/te	n.
T<ecir/te`-<agrave/-t<ecir/te"	n.
T<ecir/te`-<agrave/-t<ecir/te"	a.
T<ecir/te`-<agrave/-t<ecir/te"	adv.
T<ecir/te`-de-pont"	n.
Te*tel"	n.
Teth"er	n.
Teth"er	v. t.
Teth"er-ball`	n.
Te*thy"dan	n.
Te`thy*o"de*a	n. pl.
Te"thys	n.
Tet"ra-	a.
Tet`ra*bor"ic	a.
Tet`ra*bran`chi*a"ta	n. pl.
Tet`ra*bran`chi*ate	a.
Tet`ra*car"pel	a.
Tet"ra*chord	n.
Tet`ra*chot"o*mous	a.
Tet*rac"id	a.
Tet`ra*coc"cous	a.
Tet`ra*co"lon	n.
Te`tra*co*ral"la	n. pl.
Te*trac`ti*nel"lid	n.
Te*trac`ti*nel"li*da	n. pl.
Tet"rad	n.
Tet`ra*dac"tyl	a.
Tet`ra*dac"tyl*ous	a.
Tet`ra*dec"ane	n.
Tet`ra*de*cap"o*da	n. pl.
Tet*rad"ic	a.
Tet"ra*dite	n.
Tet"ra*don	n.
Tet"ra*dont	a. & n.
Tet"ra*drachm	n.
Tet*rad"y*mite	n.
Tet`ra*dy*na"mi*a	n. pl.
Tet`ra*dy*na"mi*an	n.
Tet`ra*dy*na"mi*an	a.
Tet"ra*gon	n.
Te*trag"o*nal	a.
Tet`ra*gram"ma*ton	n.
Tet`ra*gyn"i*a	n. pl.
Tet`ra*gyn"i*an	a.
Tet`ra*he"dral	a.
Tet`ra*he"dral*ly	adv.
Tet`ra*he"drite	n.
Tet`ra*he"dron	n.
Tet`ra*hex`a*he"dral	a.
Tet`ra*hex`a*he"dron	n.
tet`ra*hy`dro*can*nab"i*nol	n.
Tet`ra*kis*hex`a*he"dron	n.
Tet"ra*ko*sane`	n.
Te*tral"o*gy	n.
Te*tram"e*ra	n. pl.
Te*tram"er*ous	a.
Te*tram"e*ter	n.
Tet`ra*meth"yl*ene	n.
Tet"ra*morph	n.
Te*tran"dri*a	n. pl.
Te*tran"dri*an	a.
Te*tra"o*nid	n.
Tet`ra*pet"al*ous	a.
Tet`ra*phar"ma*com	n.
Tet`ra*phe"nol	n.
Te*traph"yl*lous	a.
Tet"ra*pla	n.
Tet`rap*neu"mo*na	n. pl.
Tet`rap*nue*mo"ni*an	n.
Tet"ra*pod	n.
Te*trap"o*dy	n.
Te*trap"ter*an	n.
Te*trap"ter*ous	a.
Tet"rap*tote	n.
Te"trarch	n.
Te"trarch	a.
Te*trarch"ate	n.
Te*trarch"ic*al	a.
Tet"rarch*y	n.
Tet`ra*schis"tic	a.
Tet`ra*sep"al*ous	a.
Tet`ra*spas"ton	n.
Tet`ra*sper"mous	a.
Tet"ra*spore	n.
Te*tras"tich	n.
Tet"ra*style	a.
Tet`ra*syl*lab"ic	a.
Tet"ra*syl`la*ble	n.
Tet`ra*the"cal	a.
Tet`ra*thi"on*ate	n.
Tet`ra*thi*on"ic	a.
Tet`ra*tom"ic	a.
Te*trav"a*lence	n.
Te*trav"a*lent	a.
Te*trax"ile	a.
Tet*raz"ine	n.
Tet*raz"o-	a.
Tet*raz"ole	n.
Tet"ra*zone	n.
Tet"ric	a.
Te*tric"i*ty	n.
Tet"ric*ous	a.
Te*trin"ic	a.
Tet"ro*don	n.
Tet"ro*dont	a.
Tet"rol	n.
Tet*rol"ic	a.
Tet"rose	n.
Tet*rox"ide	n.
Tet"ryl	n.
Tet"ryl*ene	n.
Tet"ter	n.
Tet"ter	v. t.
Tet"ter*ous	a.
Tet"ter-tot`ter	n.
Tet"ter*wort`	n.
Tet`ti*go"ni*an	n.
Tet"tish	a.
Tet"tix	n.
Tet"ty	a.
Teu"fit	n.
Teuk	n.
Teu"ton	n.
Teu*ton"ic	a.
Teu*ton"ic	n.
Teu*ton"i*cism	n.
Tew	v. t.
Tew	v. i.
Tew	v. t.
Tew	n.
Te"wan	n.
Tewed	a.
Tew"el	n.
Te"whit	n.
Tew"taw	v. t.
Tex"as	n.
Tex"as Leagu"er	n.
Text	v. t.
Text"-book`	n.
Text hand	n.
Tex"tile	a.
Tex"tile	n.
Text"man	n.
Tex*to"ri*al	a.
Tex"trine	a.
Tex"tu*al	a.
Tex"tu*al*ist	n.
Tex"tu*al*ly	adv.
Tex"tu*a*rist	n.
Tex"tu*a*ry	a.
Tex"tu*a*ry	n.
Tex"tu*el	a.
Tex"tu*ist	n.
Tex"tur*al	a.
Tex"ture	n.
Tex"ture	v. t.
Tex"tur*y	n.
Teyne	n.
Th	n.
Thai	a.
Thak	v. t.
Thal`a*men*ceph"a*lon	n.
Tha*lam"ic	a.
Thal`a*mi*flo"ral	a.
Thal"a*mo*coele`	n.
Thal`a*moph"o*ra	n. pl.
Thal"a*mus	n.
Tha*las"si*an	n.
Tha*las"sic	a.
Thal`as*sin"i*an	n.
Thal`as*sog"ra*phy	n.
tha"ler	n.
Tha*li"a	n.
Tha`li*a"ce*a	n. pl.
Tha*li"an	a.
Thal"late	n.
Thal"lene	n.
Thal"lic	a.
Thal"line	a.
Thal"line	n.
Thal"li*ous	a.
Thal"li*um	n.
Thal"lo*gen	n.
Thal"loid	a.
Thal*loph"y*ta	n. pl.
Thal"lo*phyte	n.
Thal"lous	a.
Thal"lus	n.
Thal"weg`	n.
Tham"muz	n.
Tham"no*phile	n.
Tha"myn	n.
Than	conj.
Than	adv.
Tha"na	n.
Than"age	n.
Than"a*toid	a.
Than`a*tol"o*gy	n.
than`a*top"sis	n.
Than`a*top"sis	prop. n.
Thane	n.
thane"dom	n.
thane"hood	n.
thane"ship	n.
thank	n.
Thank	v. t.
Thank"ful	a.
Thank"less	a.
Thank"ly	adv.
Thanks"give	v. t.
Thanks"giv`er	n.
Thanks"giv`ing	n.
Thank"wor`thi*ness	n.
Thank"wor`thy	a.
Thar	n.
Thar	v. impersonal, pres.
Tharms	n. pl.
Tha"ros	n.
That	pron., a., conj., & adv.
Thatch	n.
Thatch	v. t.
Thatch"er	n.
Thatch"ing	n.
Thaught	n.
Thau`ma*tol"a*try	n.
Thau"ma*trope	n.
thau"ma*turge	n.
thau`ma*tur"gic	a.
thau`ma*tur"gics	n.
thau`ma*tur"gist	n.
thau`ma*tur"gus	n.
thau"ma*tur`gy	n.
thave	n.
thaw	v. i.
thaw	v. t.
thaw	n.
thaw"y	a.
The	v. i.
The	definite article.
The	adv.
The"a	prop. n.
the*an"dric	a.
the`an*throp"ic	a.
The*an"thro*pism	n.
The*an"thro*pist	n.
The*an"thro*py	n.
The*ar"chic	a.
The"ar*chy	n.
The"a*ter	n.
The"a*tin	n.
The"a*tral	a.
The*at"ric	a.
The*at"ric*al	a.
The*at"ric*als	n. pl.
Theave	n.
The*ba"ic	a.
The"ba*id	n.
The*ba"ine	n.
The"ban	a.
The"ban	n.
The"ca	n.
The"cal	a.
The"ca*phore	n.
The*cas"po*rous	a.
The*ca"ta	n. pl.
Thec"la	n.
The`co*dac"tyl	n.
The"co*dont	a.
The"co*dont	n.
The`co*don"ti*a	n. pl.
The*coph"o*ra	n. pl.
The`co*so"ma*ta	n. pl.
The"dom	n.
Thee	v. i.
Thee	pron.
Theft	n.
Theft"bote`	n.
Thegn	n.
Thegn"hood	n.
The"i*form	a.
The"ine	n.
Their	pron. & a.
The"ism	n.
The"ism	n.
The"ist	n.
The*is"tic	a.
Thel*phu"si*an	n.
The*lyt"o*kous	a.
Them	pron.
The*mat"ic	a.
Theme	n.
The"mis	n.
Them*selves"	pron.
Then	adv.
Then	conj.
Then"a*days	adv.
The"nal	a.
The"nar	n.
The*nard"ite	n.
Thence	adv.
Thence`forth"	adv.
Thence`for"ward	adv.
Thence`from"	adv.
The`o*bro"ma	n.
The`o*bro"mic	a.
The`o*bro"mine	n.
The`o*chris"tic	a.
The*oc"ra*cy	n.
The*oc"ra*sy	n.
The"o*crat	n.
The`o*crat"ic	a.
The*od"i*cy	n.
The*od"o*lite	n.
The*od`o*lit"ic	a.
The`o*gon"ic	a.
The*og"o*nism	n.
The*og"o*nist	n.
The*og"o*ny	n.
The*ol"o*gas`ter	n.
The*ol"o*ger	n.
The`o*lo"gi*an	n.
The`o*log"ic	a.
The`o*log"ic*al	a.
The`o*log"ics	n.
The*ol"o*gist	n.
The*ol"o*gize	v. t.
The*ol"o*gize	v. i.
The*ol"o*gi`zer	n.
The"o*logue	n.
The*ol"o*gy	n.
The*om"a*chist	n.
The*om"a*chy	n.
The"o*man`cy	n.
The`o*pa*thet"ic	a.
The*op"a*thy	n.
The`o*phan"ic	a.
The*oph"a*ny	n.
The`o*phil`an*throp"ic	a.
The`o*phi*lan"thro*pism	n.
The`o*phi*lan"thro*pist	n.
The`o*phi*lan"thro*py	n.
The`o*phil`o*soph"ic	a.
The`op*neus"ted	a.
The`op*neus"tic	a.
The"op*neus`ty	n.
The*or"bist	n.
The*or"bo	n.
The"o*rem	n.
The"o*rem	v. t.
The`o*re*mat"ic	a.
The`o*rem"a*tist	n.
The`o*rem"ic	a.
The`o*ret"ic	a.
The`o*ret"ics	n.
The*or"ic	a.
The"o*ric	n.
The*or"i*ca	n. pl.
The*or"ic*al	a.
The*or"ic*al*ly	adv.
The"o*rist	n.
The`o*ri*za"tion	n.
The"o*rize	v. i.
The"o*ri`zer	n.
The"o*ry	n.
The"o*soph	n.
The`o*soph"ic	a.
The*os"o*phism	n.
The*os"o*phist	n.
The*os`o*phis"tic*al	a.
The*os"o*phize	v. i.
The*os"o*phy	n.
Ther`a*peu"tae	n. pl.
Ther`a*peu"tic	a.
Ther`a*peu"tic	n.
Ther`a*peu"tics	n.
Ther`a*peu"tist	n.
Ther"a*py	n.
There	adv.
There"a*bout`	adv.
There*af"ter	adv.
There"a*gain`	adv.
There"-a*nent`	adv.
There*at"	adv.
There`be*fore"	adv.
There*by"	adv.
There*for"	adv.
There"fore	conj. & adv.
There*from"	adv.
There*in"	adv.
There`in*to"	adv.
There*of"	adv.
The`re*ol"o*gy	n.
There*on"	adv.
There*out"	adv.
There*to"	adv.
There`to*fore"	adv.
There*un"der	adv.
There`un*to"	adv.
There`up*on"	adv.
There*while"	adv.
There*with"	adv.
There`with*al"	adv.
Therf	a.
The"ri*ac	n.
The"ri*ac	a.
The"ri*al	a.
The"ri*o*dont	n.
The`ri*o*don"ta	n. pl.
The`ri*o*don"ti*a	n. pl.
The`ri*ot"o*my	n.
Therm	n.
Ther"mae	n. pl.
Ther"mal	a.
Ther"mal*ly	adv.
Ther*man"ti*dote	n.
Ther*met"o*graph	n.
Ther"mic	a.
Ther`mi`dor"	n.
Ther*mif"u*gine	n.
Ther"mo-	n.
Ther`mo*bar"o*graph	n.
Ther`mo*ba*rom"e*ter	n.
Ther`mo*bat"ter*y	n.
Ther`mo*cau"ter*y	n.
Ther`mo*chem"ic	a.
Ther`mo*chem"is*try	n.
Ther`mo*chro"ic	a.
Ther*moch"ro*sy	n.
Ther"mo*cou`ple	n.
Ther"mo*cur`rent	n.
Ther"mo*din	n.
Ther`mo*dy*nam"ic	a.
Ther`mo*dy*nam"ics	n.
Ther`mo*e*lec"tric	a.
Ther`mo*e*lec"tric couple	n.
Ther`mo*e`lec*trom"e*ter	n.
Ther"mo*gen	n.
Ther`mo*gen"ic	a.
Ther*mog"e*nous	a.
Ther"mo*gram	n.
Ther"mo*graph	n.
Ther*mog"ra*phy	n.
Ther`mo*junc"tion	n.
Ther*mol"o*gy	n.
Ther`mo*lu`mi*nes"cence	n.
Ther`mo*ly"sin	n.
Ther*mol"y*sis	n.
Ther`mo*lyt"ic	a.
Ther"mo*lyze	v. t.
Ther`mo*mag"net*ism	n.
Ther*mom"e*ter	n.
Ther`mo*met"ric	a.
Ther`mo*met"ric*al*ly	adv.
Ther`mo*met"ro*graph	n.
Ther*mom"e*try	n.
Ther`mo*mo"tor	n.
Ther`mo*mul"ti*pli`er	n.
Ther`mo*neu*ro"sis	n.
Ther`mo*neu*tral"i*ty	n.
Ther`mo*phil"ic	a.
Ther"mo*phone	n.
Ther"mo*phore	n.
Ther"mo*pile	n.
Ther`mo*reg"u*la`tor	n.
Ther"mo*scope	n.
Ther`mo*scop"ic	a.
Ther`mo*si"phon	n.
Ther`mo*sta"ble	a.
Ther"mo*stat	n.
Ther`mo*stat"ic	a.
Ther`mo*sys*tal"tic	a.
Ther`mo*tac"tic	a.
Ther"mo*tank	n.
Ther`mo*tax"ic	a.
Ther`mo*tax"is	n.
Ther`mo*ten"sile	a.
Ther`mo*ten"sion	n.
Ther`mo*ther"a*py	n.
Ther*mot"ic	a.
Ther*mot"ics	n.
Ther*mot"o*nus	n.
Ther`mo*trop"ic	a.
Ther*mot"ro*pism	n.
Ther"mo*type	n.
Ther*mot"y*py	n.
Ther`mo*vol*ta"ic	a.
The"roid	a.
The`ro*mor"pha	n. pl.
The*rop"o*da	n. pl.
The*sau"rus	n.
These	pron.
Thes"i*cle	n.
The"sis	n.
Thes"mo*thete	n.
Thes"pi*an	a.
Thes*sa"li*an	a.
Thes`sa*lo"ni*an	a.
The"ta	n.
Thet"ic*al	a.
The"tine	n.
The*ur"gic	a.
The"ur*gist	n.
The"ur*gy	n.
Thew	n.
Thewed	a.
Thew"y	a.
They	pron. pl.
Thi*al"dine	n.
Thi"al*ol	n.
Thib"e*tan	a.
Thib"et cloth`	a. & n.
Thi"ble	n.
Thick	a.
Thick	n.
Thick	adv.
Thick	v. t. & i.
Thick"bill`	n.
Thick"en	v. t.
Thick"en	v. i.
Thick"en*ing	n.
Thick"et	n.
Thick"head`	n.
Thick"-head`ed	a.
Thick"ish	a.
Thick"-knee`	n.
Thick"ly	adv.
Thick"ness	n.
Thick"set`	a.
Thick"set`	n.
Thick"skin`	n.
Thick"-skinned`	a.
Thick"skull`	n.
Thick"-skulled`	a.
Thick" wind`	a.
Thid"er	adv.
Thid"er*ward	adv.
Thief	n.
Thief"ly	a. & adv.
Thi"e*none	n.
Thi"e*nyl	n.
Thieve	v. t. & i.
Thiev"er*y	n.
Thiev"ish	a.
Thigh	n.
Thig`mo*tac"tic	a.
Thig`mo*tax"is	n.
Thilk	pron.
Thill	n.
Thill"er	n.
Thim"ble	n.
Thim"ble*ber`ry	n.
Thim"ble*eye`	n.
Thim"ble*ful	n.
Thim"ble*rig`	n.
Thim"ble*rig`	v. t.
Thim"ble*rig`ger	n.
Thim"ble*weed`	n.
Thin	a.
Thin	adv.
Thin	v. t.
Thin	v. i.
Thine	pron. & a.
Thing	n.
Thing	n.
Think	v. t.
Think	v. t.
Think	n.
Think"a*ble	a.
Think"er	n.
Think"ing	a.
Think"ing	n.
Thin"ly	a.
Thin"ner	n.
Thin"ness	n.
Thin"nish	a.
Thin"o*lite	n.
Thin"-skinned`	a.
Thi"o-	n.
Thi`o*car*bon"ic	a.
Thi`o*cy"a*nate	n.
Thi`o*cy*an"ic	a.
Thi`o*naph"thene	n.
Thi*on"ic	a.
Thi"on*ine	n.
Thi"on*ol	n.
Thi*on"o*line	n.
Thi"on*yl	n.
Thi"o*phene	n.
Thi`o*phen"ic	a.
Thi`o*phe"nol	n.
Thi*oph"thene	n.
Thi`o*sul"phate	n.
Thi`o*sul*phur"ic	a.
Thi`o*to"lene	n.
Thi*ox"ene	n.
Third	a.
Third	n.
Third"-bor`ough	n.
Third"ings	n. pl.
Third"ly	adv.
Third"-pen`ny	n.
Third rail	v. t.
Thirl"age	n.
Thirst	n.
Thirst	v. t.
Thirst	v. t.
Thirst"er	n.
Thirst"i*ly	adv.
Thirst"i*ness	n.
Thirs"tle	n.
Thirst"y	a.
Thir"teen`	a.
Thir"teen`	n.
Thir"teenth`	a.
Thir"teenth`	n.
Thir"ti*eth	a.
Thir"ti*eth	n.
Thir"ty	a.
Thir"ty	n.
Thir"ty-sec`ond	a.
This	pron. & a.
This"tle	n.
This"tly	a.
Thith"er	adv.
Thith"er	a.
Thith"er*to`	adv.
Thith"er*ward	adv.
Thit"see	n.
Thlip"sis	n.
Tho	def. art.
Tho	pron. pl.
Tho	adv.
Tho	conj.
Thole	n.
Thole	v. t.
Thole	v. i.
Tho*mae"an	n.
Thom"as phos"phate	n.
Tho"mist	n.
Tho"mite	n.
Thom"sen*o*lite	n.
Thom"sen's dis*ease"	a.
Thom*so"ni*an*ism	n.
Thom"son*ite	n.
Thomson process	n.
Tho"oid	a.
Thor	n.
Tho`ra*cen*te"sis	n.
Tho*rac"ic	a.
Tho*rac"ic	n.
Tho*rac"i*ca	n. pl.
Tho`ra*com"e*ter	n.
Tho`ra*co*plas"ty	n.
Tho`ra*cos"tra*ca	n. pl.
Tho`ra*cot"o*my	n.
Tho"ral	a.
Tho"rax	n.
Tho"ri*a	n.
Thor"ic	a.
Tho"rite	n.
Tho"ri*um	n.
Thorn	n.
Thorn	v. t.
Thorn"back`	n.
Thorn"bill`	n.
Thorn"bird`	n.
Thorn"but	n.
Thorn"-head`ed	a.
Thorn"less	a.
Thorn"set`	a.
Thorn"tail`	n.
Thorn"y	a.
Thor"o	a.
Thor"ough	prep.
Thor"ough	a.
Thor"ough	adv.
Thor"ough	n.
Thor"ough bass`	n.
Thor"ough*bred`	a.
Thor"ough*fare`	n.
Thor"ough*go`ing	a.
Thor"ough-light`ed	a.
Thor"ough*ly	adv.
Thor"ough*ness	n.
Thor"ough*paced`	a.
Thor"ough*pin`	n.
Thor"ough*sped`	a.
Thor"ough*stitch`	adv.
Thor"ough*wax`	n.
Thor"ough*wort`	n.
Thor"ow	prep.
Thor"ow	a.
Thorp	n.
Those	pron.
Thoth	n.
thou	pron.
Thou	v. t.
Thou	v. i.
Though	conj.
Though	adv.
Thought	imp. & p. p.
Thought	n.
Thought"ful	a.
Thought"less	adv.
Thought transference	n.
Thou"sand	a.
Thou"sand*fold`	a.
Thou"sand legs`	a.
Thou"sandth	n.
Thow"el	n.
Thra"cian	a.
Thrack	v. t.
Thrack"scat	n.
Thral"dom	n.
Thrall	n.
Thrall	a.
Thrall	v. t.
Thrall"dom	n.
Thrall"-less	a.
Thrall"-like`	a.
Thra"nite	n.
Thrap"ple	n.
Thrash	v. t.
Thrash	v. t.
Thrash"el	n.
Thrash"er	n.
Thrash"ing	a. & n.
Thra*son"ic*al	a.
Thraste	v. t.
Thrave	n.
Thraw	n. & v.
Thread	n.
Thread	v. t.
Thread"bare`	a.
Thread"bare`ness	n.
Thread"en	a.
Thread"er	n.
Thread"fin`	n.
Thread"fish`	n.
Thread"i*ness	n.
threads	n. pl.
Thread"-shaped`	a.
Thread"worm`	n.
Thread"y	a.
Threap	v. t.
Threap	v. i.
Threap	n.
Threat	n.
Threat	v. t. & i.
Threat"en	v. t.
Threat"en	v. i.
Threat"en*er	n.
Threat"en*ing	a. & n.
Threat"ful	a.
Threave	n.
Three	a.
Three	n.
Three"-coat`	a.
Three"-col`or	a.
Three"-cor`nered	a.
Three"-deck`er	n.
Three"-flow`ered	a.
Three"fold`	a.
Three"-hand`ed	a.
Three"-leafed`	a.
Three"-lobed`	a.
Three"-mile`	a.
Three"-nerved`	a.
Three"-part`ed	a.
Three"pence	n.
Three"pen*ny	a.
Three"-pile`	n.
Three"-piled`	a.
Three"-ply`	a.
Three"-point`ed	a.
Three"-port`	a.
Three"-quar`ter	a.
Three"-score`	a.
Three"-sid`ed	a.
Three"-square`	a.
Three"-torque` system of control	a.
Three"-way`	a.
Threne	n.
Thre*net"ic	a.
Thren"ode	n.
Thren"o*dist	n.
Thren"o*dy	n.
Threpe	v. t.
Threp*sol"o*gy	n.
Thresh	v. t. & i.
Thresh"er	n.
Thresh"-fold`	n.
Thresh"old	n.
Thresh"wold`	n.
Threste	v. t.
Thret"teen`	a.
Thret"ty	a.
Threw	imp.
Thrib"ble	a.
Thrice	adv.
Thrice"cock`	n.
Thrid	a.
Thrid	v. t.
Thrid	n.
Thri"fal`low	v. t.
Thrift	n.
Thrift"i*ly	adv.
Thrift"i*ness	n.
Thrift"less	a.
Thrift"y	a.
Thrill	n.
Thrill	n.
Thrill	v. t.
Thrill	v. i.
Thrill	n.
Thrill"ant	a.
Thrill"ing	a.
Thring	v. t. & i.
Thrips	n.
Thrist	n.
Thrit"tene`	a.
Thrive	v. i.
Thriv"en	p. p.
Thriv"er	n.
Thriv"ing*ly	adv.
Thriv"ing*ness	n.
Thro'	n.
Throat	v. t.
Throat"band`	n.
Throat"boll`	n.
Throat"ing	n.
Throat"latch`	n.
Throat"wort`	n.
Throat"y	a.
Throb	v. i.
Throb	n.
Throd"den	v. i.
Throe	n.
Throe	v. i.
Throe	v. t.
Throm"bin	n.
Throm*bo"sis	n.
Throm"bus	n.
Throne	n.
Throne	v. t.
Throne	v. i.
Throne"less	a.
Throng	n.
Throng	v. i.
Throng	v. t.
Throng	a.
Throng"ly	adv.
Throp	n.
Throp"ple	n.
Throp"ple	v. t.
Thros"tle	n.
Thros"tling	n.
Throt"tle	n.
Throt"tle	v. t.
Throt"tle	v. i.
Throt"tler	n.
Through	prep.
Through	adv.
Through	a.
Through"ly	adv.
Through*out"	prep.
Through*out"	adv.
Throve	imp.
Throw	n.
Throw	n.
Throw	v. t.
Throw	v. i.
Throw	n.
throw away	v. t.
throw"a*way	a.
throw"a*way	n.
throw"back	n.
Throw back	v. i.
Throw"-crook`	n.
Throwe	n.
Throw"er	n.
Throw"ing	a. & n.
Throw"ing stick`	a. & p. p.
Throw"-off`	n.
Throw"ster	n.
Thru	prep., adv. & a.
Thrum	n.
Thrum	v. t.
Thrum	v. i.
Thrum	v. t.
Thrum"-eyed`	a.
Thrum"my	a.
Thrum"wort`	n.
Thru*out"	n.
Thrush	n.
Thrush"el	n.
Thrush"er	n.
Thrust	n. & v.
Thrust	v. t.
Thrust	v. i.
Thrust	n.
Thrust"er	n.
Thrust"ing	n.
Thrus"tle	n.
Thryes	a.
Thry"fal`low	v. t.
Thud	n.
Thud	v. i. & t.
Thug	n.
Thug*gee"	n.
Thug"ger*y	n.
Thu"ja	n.
thu"jone	n.
Thu"le	prop. n.
Thu"li*a	n.
Thu"li*um	n.
Thumb	n.
Thumb	v. t.
Thumb	v. i.
Thumb"bird`	n.
Thumbed	a.
Thumb"kin	n.
Thumb"less	a.
Thumb"screw`	n.
Thum"mie	n.
Thum"mim	n. pl.
Thump	n.
Thump	v. t.
Thump	v. i.
Thump"er	n.
Thump"ing	a.
Thun"der	n.
Thun"der	v. i.
Thun"der	v. t.
Thun"der*bird`	n.
Thun"der*bolt`	n.
Thun"der*burst`	n.
Thun"der*clap`	n.
Thun"der*cloud`	n.
Thun"der*er	n.
Thun"der*fish`	n.
Thun"der*head`	n.
Thun"der*ing	a.
Thun"der*ing	n.
Thun"der*less	a.
Thun"der*ous	a.
Thun"der*proof`	a.
Thun"der*show`er	n.
Thun"der*stone`	n.
Thun"der*storm`	n.
Thun"der*strike`	v. t.
Thun"der*worm`	n.
Thun"der*y	a.
Thun"drous	a.
Thun"ny	n.
Thurgh	prep.
Thurgh"fare`	n.
Thu"ri*ble	n.
Thu*rif"er*ous	a.
Thu`ri*fi*ca"tion	n.
Thu*rin"gi*an	a.
Thu*rin"gite	n.
Thurl	n.
Thurl	v. t.
Thurl"ing	n.
Thur"rok	n.
Thurs"day	n.
Thurst	n.
Thus	n.
Thus	adv.
Thus"sock	n.
Thu"ya	n.
Thu"yin	n.
Thwack	v. t.
Thwack	n.
Thwaite	n.
Thwaite	n.
Thwart	a.
Thwart	adv.
Thwart	prep.
Thwart	n.
Thwart	v. t.
Thwart	v. i.
Thwart"er	n.
Thwart"ing*ly	adv.
Thwart"ly	adv.
Thwart"ness	n.
Thwite	v. t.
Thwit"tle	v. t.
Thwit"tle	n.
Thy	pron.
Thy"ine wood`	n.
Thym"ate	n.
Thyme	n.
Thym"ene	n.
Thym"i*a*tech`ny	n.
Thym"ic	a.
Thy"mic	a.
Thym"ol	n.
thy"mus	a.
Thym"y	a.
Thy"ro-	a.
Thy`ro*hy"al	n.
Thy`ro*hy"oid	a.
Thy"roid	a.
Thy*roid"e*al	a.
Thy*rot"o*my	n.
Thyrse	n.
Thyr"soid	a.
Thyr"sus	n.
Thy`sa*nop"ter	n.
Thy`sa*nop"te*ra	n. pl.
Thy`sa*nop"ter*an	n.
Thy`sa*nop"ter*ous	a.
Thys`a*nu"ra	n. pl.
Thys`a*nu"ran	n.
Thys`a*nu"rous	a.
Thys"be	n.
Thy*self"	pron.
Ti"ar	n.
Ti*a"ra	n.
Ti*a"raed	a.
Tib"-cat`	n.
Tib"i*a	n.
Tib"i*al	a.
Tib"i*al	n.
Tib`i*a"le	n.
Ti*bic"i*nate	v. i.
Tib"i*o-	a.
Tib`i*o*tar"sus	n.
Tib"rie	n.
Tic	n.
Ti*cal"	n.
Tice	v. t.
Tice	n.
Tice"ment	n.
Tich"or*rhine	n.
Tick	n.
Tick	v. i.
Tick	n.
Tick	n.
Tick	v. i.
Tick	n.
Tick	v. t.
Tick"en	n.
Tick"er	n.
ticker tape parade	n.
Tick"et	v. t.
Tick"et*ing	n.
Tick"ing	n.
Tic"kle	v. t.
Tic"kle	v. i.
Tic"kle	a.
Tic"kle-foot`ed	a.
Tick"len*burg	n.
Tic"kle*ness	n.
Tic"kler	n.
Tic"klish	a.
Tick"seed`	n.
Tick"tack`	n.
Tick"tack`	adv.
Tic`po*lon"ga	n.
Tid	a.
Tid"al	a.
Tid"al wave	n.
Tid"bit`	n.
Tid"de	imp.
Tid"der	v. t.
Tid"dle*dy*winks`	n.
Tid"dly*winks`	n.
Tide	n.
Tide	v. t.
Tide	v. i.
Tid"ed	a.
Tide"land	n.
Tide"less	a.
Tide"mark	n.
Tide"-rode`	a.
Tides"man	n.
Tide"wait`er	n.
Tide"way`	n.
Tid"ife	n.
Ti"di*ly	adv.
Ti"di*ness	n.
Ti"ding	n.
Ti"dings	n. pl.
Tid"ley	n.
Tid*ol"o*gy	n.
Ti"dy	n.
Ti"dy	a.
Ti"dy	n.
Ti"dy	v. t.
Ti"dy	v. i.
Ti"dy*tips`	n.
Tie	n.
Tie	v. t.
Tie	v. i.
Tie"bar`	n.
Tie"beam`	n.
Tien an men	n.
Ti*en"da	n.
Ti"er	n.
Ti"er	n.
Tier	n.
Tierce	n.
Tier*c<eacute/"	a.
Tier"cel	n.
Tierce"-ma`jor	n.
Tier"cet	n.
Tie"-rod	n.
Tiers` <eacute/`tat"	n.
Tie"wig`	n.
Tiff	n.
Tiff	v. i.
Tiff	v. t.
Tif"fa*ny	n.
Tif"fa*ny	a.
Tif"fin	n.
Tiff"ish	a.
Tift	n.
Tig	n.
Ti*gel"la	n.
Ti*gelle"	n.
Ti"ger	n.
Ti"ger-eye`	n.
Ti"ger-foot`	n.
Ti"ger-foot`ed	a.
Ti"ger*ine	a.
Ti"ger*ish	a.
Ti"ger's-foot`	n.
Tigh	n.
Tight	p. p.
Tight	a.
Tight	v. t.
Tight"en	v. t.
Tight"en*er	n.
Tight"er	n.
Tight"ly	adv.
Tight"ness	n.
Tights	n. pl.
Tig"lic	a.
Ti"gress	n.
Ti"grine	a.
Ti"grish	a.
Tike	n.
Tike	n.
Tik"or	n.
Ti*kur"	n.
Ti"kus	n.
Til	prep. & conj.
Til"bu*ry	n.
Til"de	n.
Tile	v. t.
Tile	n.
Tile	v. t.
Tile"-drain`	v. t.
Tile"fish`	n.
Til"er	n.
Til"er	n.
Til"er*y	n.
Tile"seed`	n.
Tile"stone`	n.
Til"i*a	n.
Til`i*a"ceous	a.
Til"ing	n.
Till	n.
Till	n.
Till	n.
Till	prep.
Till	conj.
Till	v. t.
Till	v. i.
Till"a*ble	a.
Till"age	n.
Til*land"si*a	n.
Till"er	n.
Till"er	n.
Till"er	v. i.
Till"er	n.
Til"ley	n.
Till"man	n.
Til"lo*dont	n.
Til`lo*don"ti*a	n. pl.
Til"lot	n.
Til"low	v. i.
Til"ly-val`ly	interj., adv., or a.
Til"mus	n.
Til seed	n.
Tilt	v. t.
Tilt	v. t.
Tilt	v. i.
Tilt	n.
Tilt"er	n.
Tilth	n.
Tilt" ham`mer	n.
Tilt"-mill`	n.
Til tree	n.
Tilt"-yard`	n.
Ti"mal	n.
Tim"a*line	a.
Tim"bal	n.
Tim`bale"	n.
Tim"ber	n.
Tim"ber	n.
Tim"ber	v. t.
Tim"ber	n.
Tim"ber	v. t.
Tim"ber	v. i.
Tim"bered	a.
Tim"ber*head`	n.
Tim"ber*ing	n.
Tim"ber*ling	n.
Tim"ber*man	n.
Tim"ber*work`	n.
Tim"bre	n.
Tim"bre	n.
Tim"brel	n.
Tim"breled	a.
Timbuctoo	prop. n.
Tim`bu*rine"	n.
Time	n.
Time	v. t.
Time	v. i.
Time"ful	a.
Time"-hon`ored	a.
Time"keep`er	n.
Time"less	a.
Time"less*ly	adv.
Time"li*ness	n.
Time"ling	n.
Time"ly	a.
Time"ly	adv.
Ti*men"o*guy	n.
Time"ous	a.
Time"piece`	n.
Time"pleas`er	n.
Time policy	n.
Time"sav`ing	a.
Time"serv`er	n.
Time"serv`ing	a.
Time"serv`ing	n.
Time signature	n.
Tim"id	a.
Ti*mid"i*ty	n.
Tim"id*ous	a.
Tim"ist	n.
Tim"mer	n.
Ti*moc"ra*cy	n.
Ti`mo*crat"ic	a.
Tim`o*neer"	n.
Tim"or*ous	a.
Tim"or*some	a.
Tim"o*thy	n.
Tim"o*thy	prop. n.
Tim"ous	a.
Tim"pa*no	n.
Timur	prop. n.
Tim"-whis`key	n.
Tin	n.
Tin	v. t.
Ti*nam"i*des	n. pl.
Tin"a*mou	n.
Tin"cal	n.
Tin"chel	n.
Tinct	a.
Tinct	n.
Tinct	v. t.
Tinc*to"ri*al	a.
Tinc"ture	n.
Tinc"ture	v. t.
Tind	v. t.
Tin"dal	n.
Tin"der	n.
Tine	n.
Tine	v. t.
Tine	v. i.
Tine	v. t.
Tine	n.
Tin"e*a	n.
Tin"e*an	n.
Tined	a.
Tin"e*id	n.
Tine"man	n.
Ti"net	n.
Ting	n.
Ting	v. i.
Ting	n.
Tinge	v. t.
Tinge	n.
Tin"gent	a.
Tin"ger	n.
Tin"gid	a.
Tin"gis	n.
Tin"gle	v. i.
Tink	v. i.
Tink	n.
Tink"er	n.
Tink"er	v. t.
Tink"er	v. i.
Tink"er*ing	n.
Tink"er*ly	a.
Tink"er*shire	n.
Tin"kle	v. i.
Tin"kle	v. t.
Tin"kle	n.
Tin"kler	n.
Tin"kling	n.
Tin"man	n.
Tin"mouth`	n.
Tinned	a.
Tin"nen	a.
Tin"ner	n.
Tin"ni*ent	a.
Tin"ning	n.
Tin*ni"tus	n.
Tin"nock	n.
Tin"ny	a.
Tin"sel	n.
Tin"sel	a.
Tin"sel	v. t.
Tin"sel*ly	a.
Tin"sel*ly	adv.
Tin"smith`	n.
Tin"stone`	n.
Tint	n.
Tint	v. t.
Tin`ta*mar"	n.
Tin"ter*nell	n.
Tin"tie	n.
Tin`tin*nab"u*lar	a.
Tin`tin*nab`u*la"tion	n.
Tin`tin*nab"u*lous	a.
Tin`tin*nab"u*lum	n.
Tin"to	n.
Tint*om"e*ter	n.
Tin"type`	n.
Tin"ware`	n.
Ti"ny	a.
Tip	n.
Tip	v. t.
Tip	v. t.
Tip	v. i.
Tip	n.
Tip"cart`	n.
Tip"cat`	n.
Tip"per	n.
Tip"pet	n.
Tip"ping	n.
Tip"ple	v. i.
Tip"ple	v. t.
Tip"ple	n.
Tip"ple	n.
Tip"pled	a.
Tip"pler	n.
Tip"pling-house`	n.
Tip"si*fy	v. t.
Tip"si*ly	adv.
Tip"si*ness	n.
Tip"staff`	n.
Tip"ster	n.
Tip"stock`	n.
Tip"sy	a.
Tip"toe`	n.
Tip"toe`	a.
Tip"toe`	v. i.
Tip"top`	n.
Tip"top`	a.
Tip"u*la	n.
Tip"u*la*ry	a.
Tip"-up`	n.
Ti*rade"	n.
Ti`rail`leur"	n.
Tire	n.
Tire	n.
Tire	v. t.
Tire	v. i.
Tire	v. i.
Tire	v. t.
Tired	a.
Tired"ness	n.
Tire" iron	n.
Tire"less	a.
Tire"ling	a.
Tire"some	a.
Tire"-wom`an	n.
Tir"ing-house`	n.
Tir"ing-room`	n.
Tirl	v. i.
Tir"ma	n.
Ti"ro	n.
T" i`ron	a.
Tir"ra*lir`ra	n.
Tir"rit	n.
Tir"wit	n.
'T is	n.
Ti"sar	n.
Tis"ic	a.
Tis"ic	n.
Tis"ick*y	a.
Tis"ri	n.
Tis"sue	n.
Tis"sue	v. t.
Tis"sued	a.
Tit	n.
Ti"tan	a.
ti"tan*ate	n.
Ti"tan crane	a.
Ti*tan"ic	prop. n.
ti*tan"ic	a.
Ti`tan*if"er*ous	a.
Ti"tan*ite	n.
Ti`tan*it"ic	a.
Ti*ta"ni*um	n.
Ti"tan*o-	n.
Ti"tan*ous	a.
Tit"bit`	n.
Tith	a.
Tith"a*ble	a.
Tithe	n.
Tithe	a.
Tithe	v. t.
Tithe	v. i.
Tith"er	n.
Tith"ing	n.
Tith"ing*man	n.
Tith"ly	a.
Ti*thon"ic	a.
Tith`o*nic"i*ty	n.
Ti*thon`o*graph"ic	a.
Tith`o*nom"e*ter	n.
Tith"y*mal	n.
Ti"ti	n.
Ti"ti	n.
Tit"il*late	v. t. & i.
tit`il*la"tion	n.
Tit"il*la*tive	a.
Tit"i*vate	v. t. & i.
Tit"lark`	n.
Ti"tle	n.
Ti"tle	v. t.
Ti"tled	a.
Ti"tle*less	a.
Ti"tle-page`	n.
Tit"ler	n.
Tit"ling	n.
Tit"mal	n.
Tit"mouse`	n.
Ti"trate	v. t.
Ti"tra*ted	a.
Ti*tra"tion	n.
Tit"ter	v. t.
Tit"ter	n.
Tit"ter	v. i.
Tit"ter*el	n.
Tit"ter-tot`ter	v. i.
Tit"ti*mouse`	n.
Tit"tle	n.
Tit"tle*bat	n.
Tit"tle-tat`tle	n.
Tit"tle-tat`tle	v. i.
Tit"tle-tat`tling	n.
Tit"tup	v. i.
Tit"tup	n.
Tit"tup*py	a.
Tit"ty	n.
Tit"u*bate	v. i.
Tit`u*ba"tion	n.
Tit"u*lar	a.
Tit"u*lar	n.
Tit`u*lar"i*ty	n.
Tit"u*lar*ly	adv.
Tit"u*la*ry	n.
Tit"u*la*ry	a.
Tit"uled	a.
Tiv"er	n.
Tiv"er	v. t.
Tiv"o*li	n.
Tiv"y	adv.
Ti"za	n.
TLC	n.
Tlin"git	prop. n. pl.
T` lym"pho*cyte	n.
To-	prep.
To	prep.
Toad	n.
Toad"eat`er	n.
Toad"fish`	n.
Toad"flax`	n.
Toad"head`	n.
Toad"ish	a.
Toad"let	n.
Toad"stone`	n.
Toad"stool`	n.
Toad"y	n.
Toad"y	v. t.
Toad"y*ism	n.
Toast	v. t.
Toast	n.
Toast"er	n.
Toast"ing	a. & n.
Toast"mas`ter	n.
Toat	n.
To*bac"co	n.
To*bac"co*ning	n.
To*bac"co*nist	n.
To-beat"	v. t.
To*bi"as fish`	n.
To"bine	n.
To"bit	n.
To*bog"gan	n.
To*bog"gan	v. i.
To*bog"gan*er	n.
To-break"	v. t.
To-brest"	v. t.
To"by	n.
Toc*ca"ta	n.
Toc`ca*tel"la	n.
Toch"er	n.
Tock"ay	n.
To"co	n.
To*col"o*gy	n.
To*co*ro"ro	n.
Toc"sin	n.
Tod	n.
Tod	v. t. & i.
To-day"	adv.
To-day"	n.
Tod"dle	v. i.
Tod"dle	n.
Tod"dler	n.
Tod"dy	n.
To-do"	n.
To"dy	n.
Toe	n.
Toe	v. t.
Toe	v. i.
Toed	a.
Toe drop	n.
Toff	n.
Tof"fee	n.
To*fore"	prep. & adv.
Toft	n.
Toft"man	n.
To"fus	n.
Tog	v. t. & i.
To"ga	n.
To"ga*ted	a.
To"ged	a.
To*geth"er	adv.
Tog"ger*y	n.
Tog"gle	n.
Tog"gle	v. t.
Tog"gle switch`	n.
Toght	a.
To*gid"er	adv.
Togs	n. pl.
Togue	n.
To*hew"	v. t.
To"hu*bo"hu	n.
Toil	n.
Toil	v. i.
Toil	v. t.
Toil	n.
Toil"er	n.
Toi"let	n.
Toi*lette"	n.
Toil"ful	a.
Toi`li*nette"	n.
Toil"less	a.
Toil"some	a.
Toise	n.
Toi`son"	n.
Toi`son" d'or"	n.
To"ken	n.
To"ken	v. t.
To"kened	a.
To"ken*less	a.
Tok"in	n.
Tol	v. t.
To"la	n.
To*lane"	n.
Tol"booth`	n.
Told	imp. & p. p.
Tole	v. t.
To*le"do	n.
Tol`er*a*bil"i*ty	n.
Tol"er*a*ble	a.
Tol"er*ance	n.
Tol"er*ant	a.
Tol"er*ate	v. t.
Tol`er*a"tion	n.
Toll	v. t.
Toll	v. t.
Toll	v. i.
Toll	n.
Toll	n.
Toll	v. i.
Toll	v. t.
Toll"a*ble	a.
Toll"age	n.
Toll"booth`	n.
Toll"booth`	v. t.
Toll"er	n.
Toll"er	n.
Tol"le*tane	a.
Toll"gate`	n.
Toll"house`	n.
Toll"man	n.
Tol"men	n.
Tol"ses*ter	n.
Tol"sey	n.
Tol*stoy"an	a.
Tolt	n.
Tol"tec	n.
To*lu"	n.
Tol"u*ate	n.
Tol"u*ene	n.
Tol`u*e"nyl	n.
To*lu"ic	a.
Tol"u*id	n.
To*lu"i*dine	n.
Tol"u*ol	n.
To*lu"ric	a.
Tol`u*ta"tion	n.
Tol"u*yl	n.
Tol"u*yl*ene	n.
Tol"yl	n.
Tol"yl*ene	n.
Tol`y*peu"tine	n.
Tom	n.
Tom	n.
Tom"a*hawk	n.
Tom"a*hawk	v. t.
Tom"a`ley	n.
To*man"	n.
Tom and Jerry	n.
Tomb	n.
Tomb	v. t.
Tom"bac	n.
Tom"bes*ter	n.
Tomb"less	a.
Tom"boy`	n.
Tomb"stone`	n.
Tom"cat`	n.
Tom"cod`	n.
Tome	n.
Tome"let	n.
To"men*tose`	a.
To*men"tous	a.
To*men"tum	n.
Tom"fool`	n.
Tom`fool"er*y	n.
Tom`fool"ish*ness	n.
To"mi*um	n.
Tom"john`	n.
Tom"my	n.
Tom"my At"kins	prop. n.
Tom"nod`dy	n.
Tom o' Bed"lam	n.
To*morn"	adv.
To*mor"row	adv.
To*mor"row	n.
Tom"pi*on	n.
Tom"pon	n.
Tom"rig`	n.
Tom"tate	n.
Tom"tit`	n.
Tom"-tom`	n.
Ton	pl.
Ton	n.
Ton	n.
Ton	n.
To*nal"i*ty	n.
To"-name`	n.
Ton"ca bean`	n.
Tone	v. t.
Toned	a.
Tone"less	a.
Tong	n.
Tong	n.
Ton"ga	n.
Ton"ga	n.
Tong"kang	n.
Ton"go	n.
Tongs	n. pl.
Tongue	n.
Tongue	v. t.
Tongue	v. i.
Tongue"bird`	n.
Tongued	a.
Tongue"fish`	n.
Tongue"less	a.
Tongue"let	n.
Tongue"-pad`	n.
Tongue"-shaped`	a.
Tongue"-shell`	n.
Tongue"ster	n.
Tongue"-tie`	n.
Tongue"-tie`	v. t.
Tongue"-tied`	a.
Tongue"worm`	n.
Tongu"ing	vb. n.
Tongu"y	a.
Ton"ic	a.
Ton"ic	n.
Ton"ic*al	a.
To*nic"i*ty	n.
To*night"	adv.
To*night"	n.
Ton"ite	n.
Ton"ka bean`	n.
Tonne	n.
Tonne	n.
Ton`neau"	n.
Ton"ni*hood	n.
Ton"nish	a.
To*nom"e*ter	n.
To*nom"e*try	n.
Ton"o*phant	n.
Ton"ous	a.
Ton"quin bean`	n.
Ton"sil*ar	a.
Ton"sile	a.
Ton`sil*it"ic	a.
Ton`sil*i"tis	n.
Ton`sil*lec"to*my	n.
Ton`sil*li"tis	n.
Ton*sil"o*tome	n.
Ton`sil*ot"o*my	n.
Ton"sor	n.
Ton*so"ri*al	a.
Ton"sure	n.
Ton"sured	a.
Ton*tine"	n.
Ton*tine" in*su"rance	n.
To"ny	n.
Too	adv.
Took	imp.
Tool	n.
Tool	v. t.
Tool	v. i.
Tool"ing	n.
Tool"-post`	n.
Tool"-rest`	n.
Tool"shed	a.
Toom	v. t.
Toon	pl.
Toon	n.
Toon"wood`	n.
Toot	v. i.
Toot	v. t.
Toot	v. i.
Toot	v. t.
Toot"er	n.
Tooth	n.
Tooth	v. t.
Tooth"ache`	n.
Tooth"back`	n.
Tooth"bill`	n.
Tooth"brush`	n.
Tooth"draw`er	n.
Toothed	a.
Tooth"ful	a.
Tooth"ing	n.
Tooth"less	a.
Tooth"let	n.
Tooth"let*ed	a.
Tooth"pick`	n.
Tooth"pick`er	n.
Tooth"shell"	n.
Tooth"some	a.
Tooth"wort`	n.
Tooth"y	a.
Too"tle	v. i.
Too*zoo"	n.
Top	n.
Top	n.
Top	v. i.
Top	v. t.
To"parch	n.
To"parch*y	n.
Top"-ar`mor	n.
To"pau	n.
To"paz	n.
To*paz"o*lite	n.
Top" bil*ling	n.
Top"-block`	n.
Top"-boots	n. pl.
Top"-chain`	n.
Top"-cloth	n.
Top"coat`	n.
Top"-drain`	v. t.
Top"-drain`ing	n.
Top"-dress`	v. t.
Top"-dress`ing	n.
Tope	n.
Tope	n.
Tope	n.
Tope	v. i.
To"pek	n.
To"per	n.
Top"et	n.
Top fermentation	a.
Top"ful	a.
Top`gal"lant	a.
Top`gal"lant	n.
Toph	n.
To*pha"ceous	a.
Top"-ham`per	n.
Top"-heav`y	a.
To"phet	n.
Toph"in	n.
To"phus	n.
To"pi	n.
Top`i*a"ri*an	a.
Top"i*a*ry	a.
Top"ic	n.
Top"ic	a.
Top"ic*al	a.
Top"ic*al*ly	adv.
Top"knot`	n.
Top"less	a.
Top"-light`	n.
Top"man	n.
Top"mast	n.
Top"most`	a.
To*pog"ra*pher	n.
Top`o*graph"ic	a.
To*pog"ra*phist	n.
To*pog"ra*phy	n.
To*pol"o*gist	n.
To*pol"o*gy	n.
To*pon"o*my	n.
Top"o*nym	n.
To*pon"y*my	n.
Top"o*phone	n.
Top out	n.
Top"piece`	n.
Top"ping	a.
Top"ping	n.
Top"ping*ly	adv.
Top"ping*ly	a.
Top"ple	v. i.
Top"ple	v. t.
Top"-proud`	a.
Top rake	n.
Top"sail`	n.
Tops"-and-bot`toms	n. pl.
Top" sec`ret	a.
Top" ser`geant	n.
Top"-shaped`	a.
Top"-shell`	n.
Tops"man	n.
Top"soil`	n.
Top"soil`ing	n.
Top"stone`	n.
Top"sy-tur"vy	adv.
Top"-tac`kle	n.
Top"-tim`bers	n.
Top"-tool`	n.
Toque	n.
To*quet"	n.
Tor	n.
To*race"	v. t.
To"rah	n.
To"ran	n.
Tor"bern*ite	n.
Torc	n.
Torch	n.
Torch"bear`er	n.
Torch"er	n.
Torch"light`	n.
Tor"chon lace`	n.
Torch" song`	n.
Torch"wood`	n.
Torch"wort`	n.
Tore	imp.
Tore	n.
Tore	n.
To"re*a*dor`	n.
To-rend"	v. t.
Tor"et	n.
Tor"et	n.
To"reu`ma*tog"ra*phy	n.
To*reu`ma*tol"o*gy	n.
To*reu"tic	a.
Tor"goch	n.
To*ril"to	n.
To`rin*ese"	a.
Tor"ment	n.
Tor*ment"	v. t.
Tor*ment"er	n.
Tor*ment"ful	a.
Tor"men*til	n.
Tor*ment"ing	a.
Tor"ment*ise	n.
Tor*ment"or	n.
Tor*ment"ress	n.
Tor"ment*ry	n.
Tor"mi*na	n. pl.
Tor"mi*nous	a.
Torn	p. p.
Tor*na"do	n.
Tor*na"ri*a	n.
To*rose"	a.
To*ros"i*ty	n.
Torous	a.
Tor*ped"i*nous	a.
Tor*pe"do	n.
Tor*pe"do	v. t.
Tor*pe"do-boat` de*stroy"er	n.
Torpedo shell	a.
Tor*pes"cence	n.
Tor*pes"cent	a.
Tor"pid	a.
Tor"pid	n.
Tor*pid"i*ty	n.
Tor"pid*ly	adv.
Tor"pid*ness	n.
Tor"pi*fy	v. t.
Tor"pi*tude	n.
Tor"por	n.
Tor`por*if"ic	a.
Tor"quate	a.
tor"qua*ted	a.
Torque	n.
Torqued	a.
Tor"ques	n.
Tor`re*fac"tion	n.
Tor"re*fy	v. t.
Tor"rens sys`tem	n.
Tor"rent	a.
Tor*ren"tial	a.
Tor`ri*cel"li*an	a.
Tor"rid	a.
Tor*rid"i*ty	n.
Tor"rid*ness	n.
Tor"ril	n.
Tor"rock	n.
Tor*sade"	n.
Tor"sal	n.
Torse	n.
Tor"sel	n.
Tor`si*bil"l*ty	n.
Tor"sion	n.
Tor"sion*al	a.
Tor"sion e*lec*trom"e*ter	n.
Tor"so	n.
Tort	n.
Tort	a.
Tor"ta	n.
Tor"teau	n.
Tor`ti*col"lis	n.
Tor"tile	a.
Tor*til"i*ty	n.
Tor*til"la	n.
Tor"tion	n.
Tor"tious	a.
Tor"tious*ly	adv.
Tor"tive	a.
Tor"toise	n.
tortoise-shell	adj.
Tor"tri*cid	a.
Tor"trix	n.
Tor"tu*lous	a.
Tor"tu*ose`	a.
Tor`tu*os"l*ty	n.
Tor"tu*ous	a.
Tor"tur*a*ble	a.
Tor"ture	n.
tor"ture	v. t.
Tor"tur*er	n.
Tor"tur*ing*ly	adv.
Tor"tur*ous	a.
Tor"u*la	n.
Tor"u*la*form`	a.
Tor"u*lose	a.
Tor"u*lous	a.
To"rus	n.
Torved	a.
Tor"vi*ty	a.
Tor"vous	a.
To"ry	n.
To"ry	a.
To"ry*ism	n.
To*scat"ter	v. t.
Tose	v. t.
Tosh	a.
To*shred"	v. t.
Toss	v. t.
Toss	v. i.
Toss	n.
Tos"sel	n.
Toss"er	n.
Toss"i*ly	adv.
Toss"ing	n.
Toss"pot`	n.
Toss"y	a.
Tost	imp. & p. p.
Tos"to	a.
To*swink"	v. i.
Tot	n.
Tot	n.
Tot	v. t.
To"ta	n.
To"tal	a.
To"tal	n.
To"tal	v. t.
To"tal*is	n.
To"tal*i*sa`tor	n.
To*tal"i*ty	n.
To`tal*i*za"tion	n.
To"tal*i*za`tor	n.
To"tal*ize	v. t.
To"tal*ize	v. i.
To"tal*i`zer	n.
To"tal*ly	adv.
To"tal*ness	n.
To"ta*ra	n.
Tote	v. t.
Tote	n.
To*tear"	v. t.
To"tem	n.
To*tem"ic	a.
To"tem*ism	n.
To"tem*ist	n.
To"tem pole	n.
T'oth"er	a.
To`ti*pal"mi	n. pl.
To`ti*pres"ence	n.
To`ti*pres"ent	a.
Tot"ter	v. i.
Tot"ter*er	n.
Tot"ter*ing*ly	adv.
Tot"ter*y	a.
Tot"tle	v. i.
Tot"tlish	a.
Tot"ty	a.
Tot"y	a.
To"ty	n.
Tou"can	n.
Tou"can*et	n.
Touch	v. t.
Touch	v. i.
Touch	n.
Touch"a*ble	a.
Touch"back`	n.
Touch"-box`	n.
Touch"down`	n.
Touch"hole`	n.
Touch"i*ly	adv.
Touch"i*ness	n.
Touch"ing	a.
Touch"ing	prep.
Touch"ing	n.
Touch"-me-not`	n.
Touch"-nee`dle	n.
Touch"-pa`per	n.
Touch"stone`	n.
touch" on	v. t.
touch" up`	n.
touch" up paint`	n.
Touch"wood`	n.
Touch"y	a.
Tough	a.
tough	n.
Tough"-cake`	n.
Tough"en	v. i. & t.
Tough"-head`	n.
Tough"ish	a.
Tough"ly	adv.
Tough"ness	n.
Tough"-pitch`	n.
Tou"ite	n.
Tou*pee"	n.
Tou"pet*tit	n.
Tour	n.
Tour	n.
Tour	v. i.
Tou*ra"co	n.
Tour*bil"lion	n.
Tour"ing car	n.
Tour"ma*line	n.
Tourn	n.
Tour"na*ment	n.
Tourn"er*y	n.
Tour"ney	n.
Tour"ney	v. i.
Tour"ni*quet	n.
Tour`nois"	n.
Tour*nure"	n.
Touse	v. t. & i.
Touse	n.
Tous"el	v. t.
Tous"er	n.
Tou"sle	v. t.
Tous`-les`-mois"	n.
Tou"sy	a.
Tout	v. i.
Tout	v. i.
Tout	n.
Tout	n.
Tout	v. i.
Tout	v. t.
Tout	n.
Tout`-en`sem"ble	n.
Tout"er	n.
Touze	v. t. & i.
Tow	n.
Tow	v. t.
Tow	n.
Tow"age	n.
Tow"all	n.
To"ward	prep.
To"ward	adv.
To"ward	a.
To"ward*li*ness	n.
To"ward*ly	a.
To"ward*ness	n.
To"wards	prep. & adv.
Tow"boat`	n.
Tow"el	n.
Tow"el	v. t.
Tow"el*ing	n.
Tow"er	n.
Tow"er	v. i.
Tow"er	v. t.
Tow"ered	a.
Tow"er*ing	a.
Tow"er*y	a.
Tow"-head`	n.
To*whee"	n.
To*wil"ly	n.
Tow"line`	n.
Town	n.
town" and gown"	a.
Town"-cri`er	n.
Towned	a.
Town"hall`	n.
Town"house`	n.
Town"ish	a.
Town"less	a.
Town"let	n.
Towns"folk`	n.
Town"ship	n.
Towns"man	n.
Towns"peo`ple	n.
Town"ward	adv.
Tow"path`	n.
Tow"rope`	n.
Tow"ser	n.
Tow"y	a.
Tox*<ae/"mi*a	a.
Tox`al*bu"min	n.
Tox"ic	a.
Tox"i*cant	n.
Tox`i*ca"tion	n.
Tox*ic"i*ty	n.
Tox`i*co*gen"ic	a.
Tox`i*co*log"ic*al	a.
Tox`i*col"o*gist	n.
Tox`i*col"o*gy	n.
Tox`i*co*ma"ni*a	n.
Tox*if"e*ra	n. pl.
Tox"in	n.
Tox`i*pho"bi*a	n.
Tox"o*don	n.
Tox`o*don"ta	n.pl.
Tox`o*glos"sa	n. pl.
Tox"oid	n.
Tox*oph"i*lite	n.
Tox"o*tes	n.
Toy	n.
Toy	v. i.
Toy	v. t.
To*year	adv.
Toy"er	n.
Toy"ful	a.
Toy"house`	n.
Toy"ing*ly	adv.
Toy"ish	a.
Toy"man	n.
Toy"shop`	n.
Toy"some	a.
Toze	v. t.
To"zy	a.
Tra"be*a	n.
Tra"be*a`ted	a.
Tra`be*a"tion	n.
Tra*bec"u*la	n.
Tra*bec"u*lar	a.
Tra*bec"u*late	a.
Tra"bu	n.
Trace	n.
Trace	n.
Trace	v. t.
Trace	v. i.
Trace"a*ble	a.
Tra"cer	n.
Tra"cer/y	n.
Tra"che*a	n.
Tra"che*al	a.
Tra`che*a"ri*a	n. pl.
Tra"che*a*ry	a.
Tra`che*a"ta	n. pl.
Tra"che*ate	a.
Tra"che*ate	n.
Tra"che*id	n.
Tra`che*i"tis	n.
Tra*chel"i*dan	n.
Tra*chel"i*pod	n.
Tra`che*lip"o*da	n. pl.
Tra`che*lip"o*dous	a.
Tra`che*lo*bran"chi*ate	a.
Tra`che*lor"rha*phy	n.
Tra*chen"chy*ma	n.
Tra`che*o*bran"chi*a	n.
Tra`che*o*bron"chi*al	a.
Tra"che*o*cele	n.
Tra`che*oph"o*nae	n. pl.
Tra`che*os"co*py	n.
Tra`che*ot"o*my	n.
Tra"chi*noid	a.
Tra*chi"tis	n.
Tra*cho"ma	n.
Tra`chy*car"pous	a.
Tra`chy*me*du"sae	n. pl.
Tra`chy*sper"mous	a.
Tra`chy*stom"a*ta	n. pl.
Tra"chyte	n.
Tra*chyt"ic	a.
Trach"y*toid	a.
Tra"cing	n.
Track	n.
Track	v. t.
Track"age	n.
Track"er	n.
Track"lay`er	n.
Track"less	a.
Track"man	n.
Track"mas`ter	n.
Track"-road`	n.
Track"scout	n.
Track"walk`er	n.
Track"way`	n.
Tract	n.
Tract	n.
Tract	v. t.
Tract`a*bil"i*ty	n.
Tract"a*ble	a.
Trac*ta"ri*an	n.
Trac*ta"ri*an	a.
Trac*ta"ri*an*ism	n.
Tract"ate	n.
Trac*ta"tion	n.
Trac*ta"tor	n.
Tract"ile	a.
Trac*til"i*ty	n.
Trac"tion	n.
Trac"tion*al	a.
Traction wheel	n.
Trac*ti"tious	a.
Tract"ive	a.
Tract"or	n.
Trac"tor air"plane	n.
Trac`to*ra"tion	n.
Tractor screw	n.
Tract"o*ry	n.
Tract"rix	n.
Trad	imp.
Trade	n.
Trade	v. i.
Trade	v. t.
Trade	imp.
Trad"ed	a.
Trade"ful	a.
trade-in	n.
Trade"less	a.
Trade"-mark`	n.
Trade name	n.
Trad"er	n.
Trad`es*can"ti*a	prop. n.
Trades"folk`	n.
Trades"man	n.
Trades"peo`ple	n.
trades" un`ion	n.
Trades"wom`an	n.
Trad"ing	a.
Tra*di"tion	n.
Tra*di"tion	v. t.
Tra*di"tion*al	a.
Tra*di"tion*al*ism	n.
Tra*di"tion*al*ist	n.
Tra*di"tion*al*ly	adv.
Tra*di"tion*a*ri*ly	adv.
Tra*di"tion*a*ry	a.
Tra*di"tion*a*ry	n.
Tra*di"tion*er	n.
Trad"i*tive	a.
Trad"i*tor	n.
Tra*duce"	v. t.
Tra*duce"ment	n.
Tra*du"cent	a.
Tra*du"cer	n.
Tra*du"cian	n.
Tra*du"cian*ism	n.
Tra*du"ci*ble	a.
Tra*du"cing*ly	adv.
Tra*duct"	v. t.
Tra*duct"	n.
Tra*duc"tion	n.
Tra*duc"tive	a.
Traf"fic	v. i.
Traf"fic	v. t.
Traf"fic	n.
Traf"fic*a*ble	a.
Traf"fick*er	n.
Traf"fic*less	a.
Traf"fic mile	n.
Tra*ge"di*an	n.
Tra`g<eacute/`dienne"	n.
Tra*ge"di*ous	a.
Trag"e*dy	n.
Trag"ic	a.
Trag"ic	n.
Trag`i-com"e*dy	n.
Trag`i-com"ic	a.
Trag`i-com`i-pas"tor*al	a.
Trag"o*pan	n.
Tra"gus	n.
T" rail`	v. t.
Trail	v. i.
Trail	n.
Trail"er	n.
Trail"er	n.
Trail"ing	a. & vb. n.
Trail"ing edge	v. t.
Train	v. i.
Train	n.
Train"a*ble	a.
Train"band`	n.
Train"bear`er	n.
Train dispatcher	n.
Train"er	n.
Train"ing	n.
Train"ing wheels	a.
Traipse	v. i.
Trais	n. pl.
Trait	n.
Trai`teur"	n.
Trai"tor	n.
Trai"tor	a.
Trai"tor	v. t.
Trai"tor*ess	n.
Trai"tor*ly	a.
Trai"tor*ous	a.
Trai"tor*y	n.
Trai"tress	n.
Tra*ject"	v. t.
Traj"ect	n.
Tra*jec"tion	n.
Tra*ject"o*ry	n.
Tra"jet	n.
Tra*la"tion	n.
Tral`a*ti"tion	n.
Tral`a*ti"tious	a.
Tral`a*ti"tious*ly	adv.
Tra*lin"e*ate	v. i.
Tra*lu"cen*cy	n.
Tra*lu"cent	a.
Tram	n.
Tram	n.
Tram	n.
Tram	v. t.
Tram	v. i.
Tra"ma	n.
Tram"ble	v. t.
Tram"mel	n.
Tram"mel	v. t.
Tram"meled	a.
Tram"mel*er	n.
Tram"mel wheel`	n.
Tra`mon*ta"na	n.
Tra*mon"tane	a.
Tra*mon"tane	n.
Tramp	v. t.
Tramp	v. i.
Tramp	n.
Tramp"er	n.
Tram"ple	v. t.
Tram"ple	v. i.
Tram"ple	n.
Tram"pler	n.
Tram*poose"	v. i.
Tram"rail`	n.
Tram"road`	n.
Tram"way`	n.
Tra*na"tion	n.
Trance	n.
Trance	v. t.
Trance	v. i.
Tran"ect	n.
Tran"gram	n.
Tran"nel	n.
Tran"quil	a.
Tran`quil*i*za"tion	n.
Tran"quil*ize	v. t.
Tran"quil*i`zer	n.
Tran"quil*i`zing	a.
Tran*quil"li*ty	n.
Tran"quil*ly	adv.
Tran"quil*ness	n.
Trans-	v. t.
Trans*act"	v. i.
Trans*ac"tion	n.
Trans*act"or	n.
Trans*al"pine	a.
Trans*al"pine	n.
Trans*an"i*mate	v. t.
Trans*an`i*ma"tion	n.
Trans`at*lan"tic	a.
Trans*au"di*ent	a.
Trans*ca"len*cy	n.
Trans*ca"lent	a.
Tran*scend"	v. t.
Tran*scend"	v. i.
Tran*scend"ence	a.
Tran*scend"ent	n.
Tran`scen*den"tal	a.
Tran`scen*den"tal	n.
Tran`scen*den"tal*ism	n.
Tran`scen*den"tal*ist	n.
Tran`scen*den*tal"i*ty	n.
Tran`scen*den"tal*ly	adv.
Tran*scend"ent*ly	adv.
Tran*scend"ent*ness	n.
Tran*scen"sion	n.
Trans"co*late	v. t.
Trans`co*la"tion	n.
Trans*con`ti*nen"tal	a.
Trans*cor"po*rate	v. i.
Tran*scrib"bler	n.
Tran*scribe"	v. t.
Tran*scrib"er	n.
Tran"script	n.
Tran*scrip"tion	n.
Tran*scrip"tive	a.
Trans*cur"	v. i.
Trans*cur"rence	n.
Trans*cur"sion	n.
Trans*di"a*lect	v. t.
Trans*duc"tion	n.
Transe	n.
Trans*el"e*ment	v. t.
Trans*el`e*men*ta"tion	n.
Tran"senne	n.
Tran"sept	n.
Tran*sex"ion	n.
Trans*fem"i*nate	v. t.
Trans*fer"	v. t.
Trans"fer	n.
Trans*fer`a*bil"i*ty	n.
Trans*fer"a*ble	a.
Trans`fer*ee"	n.
Trans"fer*ence	n.
Trans`fer*og"ra*phy	n.
Trans*fer"rence	n.
Trans*fer"rer	n.
Trans*fer"ri*ble	a.
Trans*fig"u*rate	v. t.
Trans*fig`u*ra"tien	n.
Trans*fig"ure	v. t.
Trans*fix"	v. t.
Trans*fix"ion	n.
Trans"flu*ent	a.
Trans"flux	n.
Trans"fo*rate	v. t.
Trans*form"	v. t.
Trans*form"	v. i.
Trans*form"a*ble	a.
Trans`for*ma"tion	n.
Trans*form"a*tive	a.
Trans*form"er	n.
Trans*form"ism	n.
Trans*freight"	v. i.
Trans`fre*ta"tion	n.
Trans*frete"	v. i.
Trans"fuge	n.
Trans*fund"	v. t.
Trans*fuse"	v. t.
Trans*fu"si*ble	a.
Trans*fu"sion	n.
Trans*fu"sive	a.
Trans*gress"	v. t.
Trans*gress"	v. i.
Trans*gres"sion	n.
Trans*gres"sion*al	a.
Trans*gress"ive	a.
Trans*gress"ive*ly	adv.
Trans*gress"or	n.
Tran*shape"	v. t.
Tran*ship"	v. t.
Tran*ship"ment	n.
Trans*hu"man	a.
Trans*hu"man*ize	v. t.
Tran"sience	n.
Tran"sient	a.
Tran"sient	n.
Tran*sil"i*ence	n.
Trans*i"re	n.
Trans*isth"mi*an	a.
Trans*ist"or	n.
Trans"it	n.
Trans"it	v. t.
Tran*si"tion	n.
Tran*si"tion*al	a.
Tran*si"tion*a*ry	a.
Tran*si"tion zone	a.
Tran"si*to*ri*ly	adv.
Tran"si*to*ri*ness	n.
Tran"si*to*ry	a.
Trans*lat"a*ble	a.
Trans*late"	v. t.
Trans*late	v. i.
Trans*la"tion	n.
Trans`la*ti"tious	a.
Trans*lat"ive	a.
Trans*lat"or	n.
Trans*lat"or*ship	n.
Trans*lat"o*ry	a.
Trans*lat"ress	n.
Trans`la*va"tion	n.
Trans*lit"er*ate	v. t.
Trans*lit`er*a"tion	n.
Trans`lo*ca"tion	n.
Trans*lu"cence	n.
Trans*lu"cent	a.
Trans*lu"cent*ly	adv.
Trans*lu"cid	a.
Trans"lu*na*ry	a.
Trans`ma*rine"	a.
Trans"me*a*ble	a.
Trans"me*ate	v. t.
Trans`me*a"tion	n.
Trans*mew"	v. t. & i.
Trans"mi*grant	a.
Trans"mi*grate	v. i.
Trans`mi*gra"tion	n.
Trans"mi*gra`tor	n.
Trans*mi"gra*to*ry	a.
Trans*mis`si*bil"i*ty	n.
Trans*mis"si*ble	a.
Trans*mis"sion	n.
Trans*mis"sion dy`na*mom"e*ter	n.
Trans*mis"sive	a.
Trans*mit"	v. t.
Trans*mit"tal	n.
Trans*mit"tance	n.
Trans*mit"ter	n.
Trans*mit"ti*ble	a.
Trans*mog`ri*fi*ca"tion	n.
Trans*mog"ri*fy	v. t.
Trans*move"	v. t.
Trans*mu`ta*bil"i*ty	n.
Trans*mut"a*ble	a.
Trans`mu*ta"tion	n.
Trans`mu*ta"tion*ist	n.
Trans*mute"	v. t.
Trans*mut"er	n.
Trans*mu"tu*al	a.
Trans`na*ta"tion	n.
Trans*na"ture	v. t.
Tran"som	n.
Trans"pa*dane`	a.
Trans*pal"a*tine	a.
Trans*pare"	v. t. & i.
Trans*par"ence	n.
Trans*par"en*cy	n.
Trans*par"ent	a.
Trans*pass"	v. t.
Trans*pass"	v. i.
Trans*pass"a*ble	a.
Trans*pat"ron*ize	v. t.
Tran*spe"ci*ate	v. t.
Tran*spic"u*ous	a.
Trans*pierce"	v. t.
Tran*spir"a*ble	a.
Tran`spi*ra"tion	n.
Tran*spir"a*to*ry	a.
Tran*spire"	v. i.
Tran*spire"	v. t.
Trans*place"	v. t.
Trans*plant"	v. t.
Trans`plan*ta"tion	n.
Trans*plant"er	n.
Tran*splen"den*cy	n.
Tran*splen"dent	a.
Trans*port"	v. t.
Trans"port	n.
Trans*port`a*bil"i*ty	n.
Trans*port"a*ble	a.
Trans*port"al	n.
Trans*port"ance	n.
Trans*port"ant	a.
Trans`por*ta"tion	n.
Trans*port"ed	a.
Trans*port"er	n.
Trans*port"ing	a.
Trans*port"ing*ly	adv.
Trans*port"ment	n.
Trans*pos"a*ble	a.
Trans*pos"al	n.
Trans*pose"	v. t.
Trans*pos"er	n.
Trans`po*si"tion	n.
Trans`po*si"tion*al	a.
Trans*pos"i*tive	a.
Trans*print"	v. t.
Trans*prose"	v. t.
Trans*re"gion*ate	a.
Trans*shape"	v. t.
Trans*ship"	v. t.
Trans*ship"ment	n.
Trans"sum`mer	n.
Tran`sub*stan"ti*ate	v. t.
Tran`sub*stan`ti*a"tion	n.
Tran`sub*stan"ti*a`tor	n.
Tran`su*da"tion	n.
Tran*su"da*to*ry	a.
Tran*sude"	v. i.
Tran*sume"	v. t.
Tran*sumpt"	n.
Tran*sump"tion	n.
Tran*sump"tive	a.
Trans*va"sate	v. t.
Trans`va*sa"tion	n.
Trans*vec"tion	n.
Trans*ver"ber*ate	v. t.
Trans*ver"sal	a.
Trans*ver"sal	n.
Trans*verse"	a.
Trans"verse	n.
Trans*verse"	v. t.
Trans*verse"	v. t.
Trans*verse"ly	adv.
Trans*ver"sion	n.
Trans*vert"	v. t.
Trans*vert"i*ble	a.
Trans`vo*la"tion	n.
Trant	v. i.
Trant"er	n.
Trap	v. t.
Trap	n.
Trap	a.
Trap	n.
Trap	v. t.
Trap	v. i.
Tra*pan"	n.
Tra*pan"	v. t.
Tra*pan"ner	n.
Trap"ball`	n.
Trap"door`	n.
Trape	v. i.
Trapes	n.
Trapes	v. i.
Trap"e*zate	a.
Tra*peze"	n.
Tra*pe"zi*form	a.
Tra*pe"zi*um	n.
Trap`e*zo*he"dral	a.
Trap`e*zo*he"dron	n.
Trap"e*zoid	n.
Trap"e*zoid	a.
Trap`e*zoid"al	a.
Trap"hole	n.
Trap"pe*an	a.
Trap"per	n.
Trap"pings	n. pl.
Trap"pist	n.
Trap"pous	n.
Trap"pures	n. pl.
Trap"py	a.
Traps	n. pl.
Trap shooting	n.
Trash	n.
Trash	v. t.
Trash	v. i.
Trash"i*ly	adv.
Trash"i*ness	n.
Trash"y	a.
Trass	n.
Trau"lism	n.
Trau*mat"ic	a.
Trau"ma*tism	n.
Traunce	n. & v.
Traunt	v. i.
Traunt"er	n.
Trav"ail	n.
Tra`vail"	n.
Trav"ail	v. i.
Trav"ail	v. t.
Trav"ail*ous	a.
Trave	n.
Trav"el	v. i.
Trav"el	v. t.
Trav"el	n.
Trav"eled	a.
Trav"el*er	n.
Trav"el-taint`ed	a.
Trav"ers	adv.
Trav"ers*a*ble	a.
Trav"erse	a.
Trav"erse	adv.
Trav"erse	n.
Trav"erse	v. t.
Trav"erse	v. i.
Trav"erse drill	n.
Trav"ers*ing	a.
Trav"er*tine	n.
Trav"es*ty	a.
Trav"es*ty	n.
Trav"es*ty	v. t.
Tra`vois"	n.
Trawl	v. i.
Trawl	n.
Trawl"boat`	n.
Trawl"er	n.
Trawl"er*man	n.
Trawl"net`	n.
Trawl"warp`	n.
Tray	v. t.
Tray	n.
Tray"ful	n.
Trays	n. pl.
Tray"-trip`	n.
Treach"er	n.
Treach"er*ous	a.
Treach"er*y	n.
Treach"e*tour	n.
Trea"cle	n.
Trea"cly	a.
Tread	v. i.
Tread	v. t.
Tread	n.
Tread"board`	n.
Tread"er	n.
Tread"fowl`	n.
Trea"dle	n.
Tread"mill`	n.
Tread"-soft`ly	n.
Tread"wheel`	n.
Treague	n.
Trea"son	n.
Trea"son*a*ble	a.
Trea"son*ous	a.
Treas"ure	n.
Treas"ure	v. t.
Treas"ure-house`	n.
Treas"ur*er	n.
Treas"ur*er*ship	n.
Treas"ur*ess	n.
Treas"ure-trove`	n.
Treas"ur*y	n.
Treas"ur*y stock	v. t.
Treat	v. i.
Treat	n.
Treat"a*ble	a.
Treat"a*bly	adv.
Treat"er	n.
Trea"tise	n.
Trea"tis*er	n.
Treat"ment	n.
Trea"ture	n.
Trea"ty	n.
Tre"ble	a.
Tre"ble	adv.
Tre"ble	n.
Tre"ble	v. t.
Tre"ble	v. i.
Tre"ble*ness	n.
Treb"let	n.
Tre"bly	adv.
Treb"u*chet	n.
Tre*cen"tist	n.
Tre*cen"to	n. & a.
Tre*chom"e*ter	n.
Treck"schuyt`	n.
Tred"dle	n.
Tre*dille"	n.
Tree	n.
Tree	v. t.
Tree"beard`	n.
Tree burial	n.
Tree"less	a.
Treen	a.
Treen	pl.
Tree"nail`	n.
Tref	a.
Tre"fle	n.
Tr<eacute/`fl<eacute/"	a.
Tre"foil	n.
Tre"foiled`	a.
Treg"et	n.
Treg"et*our	n.
Treg"et*ry	n.
Tre*ha"la	n.
Tre"ha*lose`	n.
Treil"lage	n.
Trek	v. i.
Trek	n.
Trek"ker	n.
Trek*om"e*ter	n.
Trel"lis	n.
Trel"lised	a.
Tre*man"do	a.
Trem"a*tode	n.
Trem`a*to"de*a	n. pl.
Trem"a*toid	a.
Trem"ble	v. i.
Trem"ble	n.
Trem"bler	n.
Trem"bling	a.
Tre*mel"la	n.
Tre*men"dous	a.
Tre"mex	n.
Trem"ie	n.
Tre*mo*lan"do	a.
Trem"o*lite	n.
Tre"mo*lo	n.
Tre"mor	n.
Trem"u*lant	a.
Trem"u*lous	a.
Tren	n.
Tre"nail`	n.
Trench	v. t.
Trench	v. i.
Trench	n.
Trench"and	a.
Trench"ant	a.
Trench"ant*ly	adv.
Trench"er	n.
Trench"er-man	n.
Trench"more	n.
Trench"more	v. i.
Trench"-plow"	v. t.
Trend	v. i.
Trend	v. t.
Trend	n.
Trend	v. t.
Trend	n.
Trend"er	n.
Tren"dle	n.
Tren"nel	n.
Tren"tal	n.
Trente" et` qua`rante"	n.
Tre*pan"	v. t. & i.
Tre*pan"	n.
Tre*pan"	v. t.
Tre*pang"	n.
Trep"an*ize	v. t.
Tre*pan"ner	n.
Trep"e*get	n.
Tre*phine"	n.
Tre*phine"	v. t.
Trep"id	a.
Trep`i*da"tion	n.
Tre*pid"i*ty	n.
Tres"ayle`	n.
Tres"or	n.
Tres"pass	v. i.
Tres"pass	n.
Tres"pass*er	n.
Tress	n.
Tressed	a.
Tres"sel	n.
Tress"ful	a.
Tres"sure	n.
Tres"sured	a.
Tress"y	a.
Tres"-tine`	n.
Tres"tle	n.
Tres"tle*tree`	n.
Tres"tle*work`	n.
Tres"-tyne`	n.
Tret	3d pers. sing. pres.
Tret	n.
Tret"a*ble	a.
Treth"ing	n.
Tre"tis	n.
Tre*tis"	a.
Tre"vat	n.
Trev"et	n.
Trew	a.
Trews	n. pl.
Trewth	n.
Trey	n.
Tri-	a.
Tri"a*ble*ness	n.
Tri*ac"id	a.
Tri"a*cle	n.
Tri`a*con`ta*he"dral	a.
Tri"a*con`ter	n.
Tri"ad	n.
Tri`a*del"phous	a.
Tri*ad"ic	a.
Tri"a*kis*oc`ta*he"dron	n.
Tri"al	n.
tri"al and er"ror	n.
Tri"a*logue	n.
Tri*am"ide	n.
Tri*am"ine	n.
Tri"an`der	n.
Tri*an"dri*a	n. pl.
Tri*an"dri*an	a.
Tri"an`gle	n.
Tri"an`gled	a.
Tri*an"gu*lar	a.
Tri*an`gu*la"res	n. pl.
Tri*an`gu*lar"i*ty	n.
Tri*an"gu*lar*ly	adv.
Tri*an"gu*late	v. t.
Tri*an`gu*la"tion	n.
Tri"ar*chy	n.
Tri*a"ri*an	a.
Tri`ar*tic"u*late	a.
Tri"as	n.
Tri*as"sic	a.
Tri*at"ic	a.
Tri`a*tom"ic	a.
Trib"al	a.
Trib"al*ism	n.
Tri*ba"sic	a.
Trib"ble	n.
Tribe	n.
Tribe	v. t.
Trib"let	n.
trib"o-	n.
trib`o*e*lec*tric"i*ty	n.
tri*bol"o*gy	n.
Tri*bom"e*ter	n.
Tri"brach	n.
Tri*brac"te*ate	a.
Tri*bro`mo*phe"nol	n.
Trib"u*al	a.
Trib`u*la"tion	n.
Tri*bu"nal	n.
Tri`bu*nal"	n.
Trib"u*na*ry	a.
Trib"u*nate	n.
Trib"une	n.
Trib"une*ship	n.
Trib`u*ni"cian	a.
Trib`u*ni"tious	a.
Trib"u*ta*ri*ly	adv.
Trib"u*ta*ri*ness	n.
Trib"u*ta*ry	a.
Trib"u*ta*ry	n.
Trib"ute	n.
Trib"ute	v. i.
Trib"u*ter	n.
Tri"ca	n.
Tri*car`bal*lyl"ic	a.
Tri*car"bi*mide	n.
Trice	v. t.
Trice	n.
Tri`cen*na"ri*ous	a.
Tri*cen"ni*al	a.
Tri*cen"te*na*ry	a.
Tri"ceps	n.
Tri*chi"a*sis	n.
Tri*chi"na	n.
Trich`i*ni"a*sis	n.
Trich"i*nize	v. t.
Tri*chi"no*scope	n.
Trich`i*no"sis	n.
Trich"i*nous	a.
Trich"ite	n.
Trich`i*u"ri*form	a.
Trich`i*u"roid	a.
Trich`i*u"rus	n.
Tri*chlo"ride	n.
Trich`o*bran"chi*a	n.
Trich"o*cyst	n.
Trich"o*gyne	n.
Tri*chom"a*nes	n.
Tri*chom"a*tose`	a.
Trich"ome	n.
Trich"o*phore	n.
Tri*chop"ter	n.
Tri*chop"te*ra	n. pl.
Tri*chop"ter*an	a.
Tri"chord	n.
Trich`o*scol"i*ces	n. pl.
Tri*chot"o*mous	a.
Tri*chot"o*my	n.
Tri*chro"ic	a.
Tri"chro*ism	n.
Tri`chro*mat"ic	a.
Tri*chro"ma*tism	n.
Tri*chro"mic	a.
Tri*chro"mic	a.
Tri*cip"i*tal	a.
Trick	n.
Trick	v. t.
Trick"er	n.
Trick"er	n.
Trick"er*y	n.
Trick"i*ness	n.
Trick"ing	a.
Trick"ing	n.
Trick"ish	a.
Tric"kle	v. i.
Tric"kle	n.
Trick"ment	n.
Trick"si*ness	n.
Trick"ster	n.
Trick"sy	a.
Trick"track`	n.
Trick"y	a.
Tric"li*nate	a.
Tri*clin"i*a*ry	a.
Tri*clin"ic	a.
Tri*clin"i*um	n.
Tri*coc"cous	a.
Tri"col`or	n.
Tri"col`ored	a.
Tri`cor*nig"er*ous	a.
Tri*cor"po*ral	a.
Tri*cos"tate	a.
Tri`cot"	n.
Tri*crot"ic	a.
Tri"cro*tism	n.
Tri"cro*tous	a.
Tri*cur"vate	a.
Tri*cus"pid	a.
Tricus"pid*ate	a.
Tri"cy*cle	n.
Tri*dac"na	n.
Tri*dac"tyl	a.
Tri*dac"tyl*ous	a.
Trid"dler	n.
Tride	a.
Tri*dec"ane	n.
Tri`dec*a*to"ic	a.
Tri`de*cat"y*lene	n.
Tri"dent	n.
Tri"dent	a.
Tri*den"tate	a.
Tri"dent*ed	a.
Tri`dent*if"er*ous	a.
Tri*den"tine	a.
Tri*di`a*pa"son	n.
Tri`di*men"sion*al	a.
Tri"ding	n.
Trid"u*an	a.
Trid"y*mite	n.
Tried	imp. & p. p.
Tri*e"dral	a.
Tri*en"ni*al	a.
Tri*en"ni*al	n.
Tri*en"ni*al*ly	adv.
Tri"ens	n.
Tri"er	n.
Tri"er*arch	n.
Tri"er*arch`y	n.
Tri`e*ter"ic*al	a.
Tri`e*ter"ics	n. pl.
Tri*eth`yl*am"ine	n.
Tri*fa"cial	a.
Tri"fal`low	v. t.
Tri*fa"ri*ous	a.
Tri*fas"ci*a`ted	a.
Tri"fid	a.
Tri*fis"tu*la*ry	a.
Tri"fle	n.
Tri"fle	v. i.
Tri"fle	v. t.
Tri"fler	n.
Tri"fling	a.
Tri*flo"ral	a.
Tri*fluc`tu*a"tion	n.
Tri*fo"li*ate	a.
Tri*fo"li*o*late	a.
Tri*fo"li*um	n.
Tri"fo*ly	n.
Tri*fo"ri*um	n.
Tri"form	a.
Tri*form"i*ty	n.
Tri*fur"cate	a.
Trig	v. t.
Trig	a.
Trig	v. t.
Trig	n.
Trig"a*mist	n.
Trig"a*mous	a.
Trig"a*my	n.
Tri*gas"tric	a.
Tri*gem"i*nal	a.
Tri*gem"i*nous	a.
Tri*gen"ic	a.
Tri`ger proc"ess	a.
Tri*ges"i*mo-se*cun"do	n.
Trig"ger	n.
Tri*gin`tal	n.
Tri*glyc"er*ide	n.
Tri"glyph	n.
Tri*glyph"ic	a.
Trig"ness	n.
Tri"gon	n.
Tri"go*nid	a.
Tri`gone"	n.
Tri*go"ni*a	n.
Trig`o*noc"er*ous	a.
Trig"o*no*dont`	a.
Trig`o*no*met"ric	adv.
Trig`o*nom"e*try	n.
Trig"o*nous	a.
Tri"gram	n.
Tri`gram*mat"ic	a.
Tri*gram"mic	a.
Tri"graph	n.
Tri"gyn	n.
Tri*gyn"i*a	n. pl.
Tri*gyn"i*an	a.
Tri*he"dral	a.
Tri*he"dron	n.
Tri*ho"ral	a.
Tri*hy"brid	n.
Trij"u*gate	a.
Trij"u*gous	a.
Tri"ko*sane	n.
Tri*lat"er*al	a.
Tri*lem"ma	n.
Tri*lin"e*ar	a.
Tri*lin"gual	a.
Tri*lin"guar	a.
Tri*lit"er*al	a.
Tri*lit"er*al*ism	n.
Tri*lit`er*al"i*ty	n.
Tri"lith	n.
Tri*lith"ic	a.
Tril"i*thon	n.
Trill	v. i.
Trill	v. t.
Trill	v. t.
Trill	v. i.
Trill	n.
Tril"la*chan	n.
Tril"ling	n.
Tril"lion	n.
Tril"li*um	n.
Tril"lo	n.
Tri*lo"bate	a.
Tri`lo*ba"tion	n.
Tri"lobed	a.
Tri`lo*bi"ta	n. pl.
Tri"lo*bite	n.
Tri`lo*bit"ic	a.
Tri*loc"u*lar	a.
Tril"o*gy	n.
Tri*lu"mi*nar	a.
Trim	v. t.
Trim	v. i.
Trim	n.
Trim	a.
Tri*mac"u*la`ted	a.
Tri*mel"lic	a.
Tri*mem"bral	a.
Tri"me*ra	n. pl.
Tri"mer*an	n.
Tri"mer*ous	a.
Tri`me*sit"ic	a.
Tri*mes"ter	n.
Tri*mes"tral	a.
Tri*mes"tri*al	a.
Trim"e*ter	a.
Tri*meth"yl	n.
Tri*meth"yl*ene	n.
Tri*met"ric	a.
Tri*met"ric*al	a.
Trim"ly	adv.
Trim"mer	n.
Trim"ming	a.
Trim"ming	n.
Trim"ming*ly	adv.
Trim"ness	n.
Tri"morph	n.
Tri*mor"phic	a.
Tri*mor"phism	n.
Tri*mur"ti	n.
Trim`y*a"ri*an	n.
Tri"nal	a.
Trin"dle	v. t. & n.
Trine	a.
Trine	n.
Trine	v. t.
Tri*nerv"ate	a.
Tri"nerve`	a.
Trin"ga	n.
Trin"gle	n.
Trin"goid	a.
Trin`i*ta"ri*an	a.
Trin`i*ta"ri*an	n.
Trin`i*ta"ri*an*ism	n.
Tri*ni`tro*cel"lu*lose"	n.
Tri*ni`tro*phe"nol	n.
Trin"i*ty	n.
Trin`i*u"ni*ty	n.
Trink	n.
Trin"ket	n.
Trin"ket	n.
Trin"ket	v. i.
Trin"ket*er	n.
Trin"ket*ry	n.
Trin"kle	v. i.
Tri*noc"tial	a.
Tri*nod"al	a.
Tri*no"mi*al	n.
Tri*no"mi*al	a.
Tri*nom"i*nal	n. & a.
Tri*nu"cle*us	n.
Tri"o	n.
Tri*ob"o*lar	a.
Tri*oc"tile	n.
Tri*<oe/"ci*a	n. pl.
Tri*<oe/"cious	a.
Tri"ole	n.
Tri*o"le*in	n.
Tri"o*let	n.
Tri"o*nal	n.
Tri*on`y*choi"de*a	n. pl.
Tri*on"yx	n.
Tri"or	n.
Tri"ose	n.
Tri*ox"ide	n.
Trip	v. i.
Trip	v. t.
Trip	n.
Tri*pal"mi*tate	n.
Tri*pal"mi*tin	n.
Tri*pang"	n.
Tri"part`ed	a.
Tri*part"i*ble	a.
Tri*par"tient	a.
Trip"ar*tite	a.
Trip`ar*tite*ly	adv.
Trip`ar*ti"tion	n.
Tri*pas"chal	a.
Tripe	n.
Trip"e*dal	a.
Tripe`-de-roche"	n.
Trip"el	n.
Tripe"man	n.
Tri*pen"nate	a.
Tri*per"son*al	a.
Tri*per"son*al*ist	n.
Tri*per`son*al"i*ty	n.
Trip"er*y	n.
Tripe"stone`	n.
Tri*pet"al*oid	a.
Tri*pet"al*ous	a.
Trip" ham`mer	n.
Triph"thong	n.
Triph*thon"gal	a.
Triph"y*line	n.
Triph"y*lite	n.
Triph"yl*lous	a.
Tri*pin"nate	a.
Tri`pin*nat"i*fid	a.
Tri*pit"a*ka	n.
Tri*pla"sian	a.
Tri"ple	a.
Tri"ple	v. i.
Tri"ple-crowned`	a.
Tri"ple-head`ed	a.
Trip"let	n.
Tri"ple-tail`	n.
Tri"plex	a.
Trip"li*cate	a.
Trip"li*cate	n.
Trip"li*cate-ter`nate	a.
Trip"li*ca"tion	n.
Tri*plic"i*ty	n.
Trip`li*cos"tate	a.
Trip"lite	n.
Trip`lo*blas"tic	a.
Trip*loi"dite	n.
Trip"ly	adv.
Trip"mad`am	n.
Tri"pod	n.
Tri*po"di*an	n.
Trip"o*dy	n.
Trip"o*li	n.
Trip"o*line	a.
Tri*pol"i*tan	a.
Tri"pos	n.
Trip"pant	a.
Trip"per	n.
Trip"pet	n.
Trip"ping	a.
Trip"ping	n.
Trip"ping*ly	adv.
Trip"sis	n.
Trip"tote	n.
Trip"tych	n.
Tri*pu"di*a*ry	a.
Tri*pu"di*ate	v. i.
Tri*pu`di*a"tion	n.
Tri`quad*ran"tal	a.
Tri*que"tral	a.
Tri*que"trous	a.
Tri*que"trum	n.
Tri*ra"di*ate	a.
Tri`rec*tan"gu*lar	a.
Tri"reme	n.
Tri`rhom*boid"al	a.
Tri*sac"cha*ride	n.
Tri*sac`ra*men*ta"ri*an	n.
Tris*ag"i*on	n.
Tri*sect"	v. t.
Tri*sect"ed	a.
Tri*sec"tion	n.
Tri*ser"al*ous	a.
Tri*se"ri*al	a.
Tris*kel"i*on	n.
Tris"mus	n.
Tris*ni"trate	n.
Tris*oc`ta*he"dron	n.
Tri"spast	n.
Tri*sper"mous	a.
Tri*splanch"nic	a.
Trist	v. t. & i.
Trist	n.
Trist	a.
Triste	n.
Tri*ste"a*rate	n.
Tri*ste"a*rin	n.
Trist"ful	a.
Trist"ful*ly	adv.
Tris"tich*ous	a.
Tri`stig*mat"ic	a.
Tris*ti"ti*ate	v. t.
Tris"to*ma	n.
Trist"y	a.
Tri"sulc	n.
Tri*sul"cate	a.
Tri*sul"phide	n.
Tris`yl*lab"ic	a.
Tri*syl"la*ble	n.
Trite	a.
Tri*ter"nate	a.
Tri"the*ism	n.
Tri"the*ist	n.
Tri`the*is"tic	a.
Tri"the*ite	n.
Tri"thing	n.
Tri*thi"on*ate	n.
Tri`thi*on"ic	a.
Trit"i*at*ed	a.
Trit"ic*al	a.
Trit"i*cin	n.
Trit"i*cum	n.
trit"i*um	n.
Tri"ton	n.
Tri"tone`	n.
Tri*to"ri*um	n.
Tri*to"vum	n.
Tri`to*zo"oid	n.
Tri`tu*ber"cu*lar	a.
Tri`tu*ber"cu*ly	n.
Trit"u*ra*ble	a.
Trit"u*rate	v. t.
Trit`u*ra"tion	n.
Trit"ure	n.
Tri*tu"ri*um	n.
Tri"tyl	n.
Tri"tyl*ene	n.
Tri"umph	n.
Tri"umph	v. i.
Tri"umph	v. t.
Tri*um"phal	a.
Tri*um"phal	n.
Tri*um"phant	a.
Tri*um"phant*ly	adv.
Tri"umph*er	n.
Tri"umph*ing	a.
Tri*um"vir	n.
Tri*um"vi*rate	n.
Tri*um"vi*ry	n.
Tri"une	a.
Tri*un"gu*lus	n.
Tri*u"ni*ty	n.
Triv"a*lence	n.
Triv"a*lent	a.
Tri"valve	n.
Tri*val"vu*lar	a.
Triv"ant	n.
Tri*ver"bi*al	a.
Triv"et	n.
Triv"i*al	a.
Triv"i*al	n.
Triv"i*al*ism	n.
Triv`i*al"i*ty	n.
Triv"i*al*ly	adv.
Triv"i*al*ness	n.
Triv"i*um	n.
Tri"week`ly	a.
Troad	n.
Troat	v. i.
Troat	n.
Tro"car	n.
Tro"cha	n.
Tro*cha"ic	n.
Tro*cha"ic	a.
Tro"chal	a.
Tro*chan"ter	n.
Tro`chan*ter"ic	a.
Tro*chan"tine	n.
Tro"char	n.
Tro"che	n.
Tro"chee	n.
Tro"chil	n.
Troch"i*li	n. pl.
Tro*chil"ic	a.
Tro*chil"ics	n.
Tro*chil"i*dist	n.
Troch"i*los	n.
Troch"i*lus	n.
Tro"ching	n.
Tro*chis"cus	n.
Tro"chisk	n.
Tro"chite	n.
Troch"le*a	n.
Troch"le*ar	n.
Troch"le*a*ry	a.
Tro"choid	n.
Tro"choid	a.
Tro*choid"al	a.
Tro*chom"e*ter	n.
Troch"o*sphere	n.
Tro"chus	n.
Tro"co	n.
Trod	imp. & p. p.
Trod"den	p. p.
Trode	imp.
Trode	n.
Trog"lo*dyte	n.
Trog`lo*dy"tes	n.
Trog`lo*dyt"ic	a.
Tro"gon	n.
Tro"gon*oid	a.
Trogue	n.
Tro"ic	a.
Tro"i*lite	n.
Tro"i*lus	n.
Tro"i*lus butterfly	a.
Tro"jan horse`	n.
Troll	n.
Troll	v. t.
Troll	v. i.
Troll	n.
Troll"er	n.
Trol"ley	n.
Trol"ley car	n.
Trol"lop	n.
Trol`lop*ee"	n.
Trom"bone	n.
Trom"mel	n.
Tromp	n.
Tromp	n.
Tromp"il	n.
Tron	n.
Tro"na	n.
Tron"age	n.
Tro*na"tor	n.
Trone	n.
Trone	n.
Trone	n.
Troop	n.
Troop	v. i.
Troop	v. t.
Troop"bird`	n.
Troop"er	n.
Troop"fowl`	n.
Troop"i*al	n.
Troop"meal`	adv.
Troop"ship`	n.
Troost"ite	n.
Tro*pae"o*lin	n.
Trope	n.
Tro*pe"ine	n.
Tro"phi	n. pl.
Troph"ic	a.
Tro"phied	a.
Tro*pho"ni*an	a.
Troph"o*some	n.
Troph"o*sperm	n.
Tro"phy	n.
Trop"ic	a.
Trop"ic	n.
Trop"ic	a.
Trop"ic*al	a.
Trop"ic*al*ly	adv.
Trop"i*dine	n.
Tro*pil"i*dene	n.
Tro"pine	n.
Tro"pism	n.
Trop"ist	n.
Trop`o*log"ic	a.
Tro*pol"o*gize	v. t.
Tro*pol"o*gy	n.
Trop"po	adv.
Tros"sers	n. pl.
Trot	v. i.
Trot	v. t.
Trot	n.
Troth	n.
Troth"less	a.
Troth"plight`	v. t.
Troth"plight`	a.
Troth"plight`	n.
Troth"plight`ed	a.
Trot"ter	n.
Trot"toir	n.
Trou"ba*dour`	n.
Trou"bla*ble	a.
Trou"ble	v. t.
Trou"ble	a.
Trou"ble	n.
Trou"bler	n.
Trou"ble*some	a.
Trou"blous	a.
Trou"-de-loup"	n.
Trough	n.
Trough"-shell`	n.
Troul	v. t. & i.
Trounce	v. t.
Troupe	n.
Troup"i*al	n.
Trouse	n.
Trou"ser*ing	n.
Trou"sers	n. pl.
Trousse	n.
Trous`seau"	n.
Trout	n.
Trout"bird`	n.
Trout"-col`ored	a.
Trout"let	n.
Trout"ling	n.
Trou`v<egrave/re"	n.
Tro"ver	n.
Trow	n.
Trow	v. i. & t.
Trow"el	n.
Trow"eled	n.
Trowl	n.
Trowsed	a.
Trow"sers	n. pl.
Troy	n.
Troy"ounce	n.
Tru"age	n.
Tru"an*cy	n.
Tru"and	n. & a.
Tru"ant	n.
Tru"ant	a.
Tru"ant	v. i.
Tru"ant	v. t.
Tru"ant*ly	adv.
Tru"ant*ship	n.
Trub	n.
Trub"tall`	n.
Tru*bu"	n.
Truce	n.
Truce"break`er	n.
Truce"less	a.
Truch"man	n.
Tru`ci*da"tion	n.
Truck	n.
Truck	v. t.
Truck	v. t.
Truck	v. i.
Truck	n.
Truck"age	n.
Truck"age	n.
Truck"er	n.
Truck"ing	n.
Truc"kle	n.
Truc"kle	v. i.
Truc"kle	v. t.
Truc"kle-bed`	n.
Truc"kler	n.
Truck"man	n.
Tru"cu*lence	n.
Tru"cu*lent	a.
Tru"cu*lent*ly	adv.
Trudge	v. i.
Trudge"man	n.
Trudg"en stroke	a.
True	adv.
True"-blue`	a.
True"-blue`	n.
True"-born`	a.
True"-bred`	a.
True"-heart`ed	a.
True"love`	n.
True"ness	n.
True"-pen`ny	n.
Truf"fle	n.
Truf"fled	a.
Trug	n.
Trug"ging-house`	n.
Tru"ism	n.
Tru`is*mat"ic	a.
Trui`t<eacute/"	a.
Trull	n.
Trul`li*za"tion	n.
Tru"ly	adv.
Trump	n.
Trump	v. i.
Trump	n.
Trump	v. i.
Trump	v. t.
Trump	v. t.
Trump"er*y	n.
Trump"er*y	a.
Trump"et	n.
Trump"et	v. t.
Trump"et	v. i.
Trump"et*er	n.
Trump"et*ing	n.
Trump"ets	n. pl.
Trump"et-shaped`	a.
Trump"et-tongued`	a.
Trump"et*weed`	n.
Trump"et*wood`	n.
Trum"pie	n.
Trump"like`	a.
Trun"cal	a.
Trun"cate	v. t.
Trun"cate	a.
Trun"ca*ted	a.
Trun*ca"tion	n.
Trunch	n.
Trun"cheon	n.
Trun"cheon	v. t.
Trun"cheoned	a.
Trun`cheon*eer"	n.
Trun"cus	n.
Trun"dle	n.
Trun"dle	v. t.
Trun"dle	v. i.
Trun"dle-bed`	n.
Trun"dle*head`	n.
Trun"dle*tail`	n.
Trunk	n.
Trunk	v. t.
Trunk"back`	n.
Trunked	a.
Trunk engine	n.
Trunk"ful	n.
Trunk piston	n.
Trun"nel	n.
Trun"nel	n.
Trun"nion	n.
Trun"nioned	a.
Tru"sion	n.
Truss	n.
Truss	v. t.
Truss"ing	n.
Trust	n.
Trust	a.
Trust	v. t.
Trust	v. i.
Trust company	n.
Trus*tee"	v. t.
Trus*tee" proc"ess	n.
Trustee stock	n.
Trust"ful	a.
Trust"i*ly	adv.
Trust"i*ness	n.
Trust"ing	a.
Trust"less	a.
Trust"wor`thy	a.
Trust"y	a.
Truth	n.
Truth	v. t.
Truth"ful	a.
Truth"less	a.
Truth"-lov`er	n.
Truth"ness	n.
Truth"-tell`er	n.
Truth"y	a.
Tru`ti*na"tion	n.
Trut*ta"ceous	a.
Try	v. t.
Try	v. i.
Try	n.
Try	a.
Try cock	n.
Try"ing	a.
Try"out	n.
Try out	v. i.
Try out	v. t.
Tryp"sin	n.
Tryp*sin"o*gen	n.
Tryp"tic	a.
Tryp"tone	n.
Try"sail	n.
Try"-square`	n.
Tryst	n.
Tryst	v. t.
Tryst	v. i.
Tryst"er	n.
Tryst"ing	n.
Tsar	n.
Tsa*ri"na	n.
Tschak*meck"	n.
Tsche"go	n.
Tse"be	n.
Tset"se	n.
T" square`	n.
Tu`a*te"ra	n.
Tub	n.
Tub	v. t.
Tub	v. i.
Tu"ba	n.
Tub"al	a.
Tub"bing	n.
Tub"by	a.
Tube	n.
Tube	v. t.
Tube"form	a.
Tube"-nosed`	a.
Tu"ber	n.
Tube rail"way	n.
Tu"ber*cle	n.
Tu"ber*cled	a.
Tu*ber"cu*lar	a.
Tu*ber"cu*lar*ize	v. t.
Tu*ber"cu*late	a.
Tu*ber"cu*lin	n.
Tu*ber"cu*lin test	n.
Tu*ber"cu*lo*cid`al	a.
Tu*ber"cu*lo*ci`din	n.
Tu*ber"cu*loid	a.
Tu*ber"cu*lose`	a.
Tu*ber"cu*losed`	a.
Tu*ber`cu*lo"sis	n.
Tu*ber"cu*lous	a.
Tu*ber"cu*lum	n.
Tu`ber*if"er*ous	a.
Tube"rose`	n.
Tu"ber*ose`	a.
Tu`ber*os"i*ty	n.
Tu"ber*ous	a.
Tube"-shell`	n.
Tube"worm`	n.
Tub"fish`	n.
Tub"ful	n.
Tu*bic"i*nate	v. i.
Tu*bic"o*lae	n. pl.
Tu*bic"o*lar	a.
Tu"bi*cole	n.
Tu*bic"o*lous	a.
Tu"bi*corn	n.
Tu"bi*corn`ous	a.
Tu"bi*form	a.
Tu`bi*na"res	n. pl.
Tub"ing	n.
Tu*bip"o*ra	n.
Tu"bi*pore	n.
Tu"bi*po*rite	n.
Tu"bi*valve	n.
Tub"man	n.
Tu"bu*lar	a.
Tu`bu*la"ri*a	n.
Tu`bu*la"ri*ae	n. pl.
Tu`bu*la"ri*an	n.
Tu`bu*la"ri*an	a.
Tu"bu*lar`i*da	n. pl.
Tu"bu*late	a.
Tu"bu*la`ted	a.
Tu`bu*la"tion	n.
Tu"bu*la`ture	n.
Tu"bule	n.
Tu`bu*li*bran"chi*an	n.
Tu`bu*li*bran`chi*a"ta	n. pl.
Tu"bu*li*cole`	n.
Tu`bu*li*den"tate	a.
Tu"bu*li*form`	a.
Tu"bu*li*pore"	n.
Tu"bu*lose`	a.
Tu"bu*lure	n.
Tu*can"	n.
Tu"cet	n.
Tuch	n.
Tuck	n.
Tuck	n.
Tuck	v. t.
Tuck	v. i.
Tuck	n.
Tuck"a*hoe	n.
Tuck"er	n.
Tuck"er	v. t.
Tuck"et	n.
Tuck"et	n.
Tuck"-net`	n.
Tuck pointing	n.
Tu*cu"ma	n.
Tu"dor	a.
Tu"e	n.
Tue"fall	n.
Tue"-i`ron	n.
Tue"-i`rons	n. pl.
Tues"day	n.
Tu"et	n.
Tu"fa	a.
Tuff	n.
Tuf*foon"	n.
Tuft	n.
Tuft	v. t.
Tuft	v. i.
Tuf-taf"fe*ta	n.
Tuft"ed	a.
Tuft"hunt`er	n.
Tuft"hunt`ing	n.
Tuft"y	a.
Tug	v. t.
Tug	v. i.
Tug	n.
Tu*gan"	n.
Tug"boat`	n.
Tug"ger	n.
Tug"ging*ly	adv.
Tuille	n.
Tu*i"tion	n.
Tu*i"tion*a*ry	a.
Tu"ko-tu*ko	n.
Tu"la met`al	n.
Tu"lip	n.
Tu"lip-eared`	a.
Tu"lip*ist	n.
Tu`lip*o*ma"ni*a	n.
Tu`lip*o*ma"ni*ac	n.
Tu"lip-shell`	n.
Tu"lip*wood`	n.
Tull	v. t.
Tulle	n.
Tul"li*an	a.
Tul"li*bee	n.
Tum"ble	v. i.
Tum"ble	v. t.
Tum"ble	n.
Tum"ble*bug`	n.
Tum"ble-down`	a.
Tum"ble*dung`	n.
Tum"bler	n.
Tum"bler*ful	n.
Tum"ble*weed`	n.
Tum"bling	a. & vb. n.
Tum"brel	n.
Tu`me*fa"cient	a.
Tu`me*fac"tion	n.
Tu"me*fy	v. t.
Tu"me*fy	v. i.
Tu*mes"cence	n.
Tu*mes"cent	a.
Tu"mid	a.
Tu*mid"i*ty	n.
Tum"mals	n.
Tu"mor	n.
Tu"mored	a.
Tu"mor*ous	a.
Tump	n.
Tump	v. t.
Tump"line`	n.
Tum"-tum`	n.
Tu"mu*lar	a.
Tu"mu*late	v. t.
Tu"mu*late	v. i.
Tu"mu*lose`	a.
Tu`mu*los"i*ty	n.
Tu"mu*lous	a.
Tu"mult	n.
Tu"mult	v. i.
Tu"mult*er	n.
Tu*mul"tu*a*ri*ly	adv.
Tu*mul"tu*a*ri*ness	n.
Tu*mul"tu*a*ry	a.
Tu*mul"tu*ate	v. i.
Tu*mul`tu*a"tion	n.
Tu*mul"tu*ous	a.
Tu"mu*lus	n.
Tun	n.
Tun	v. t.
Tu"na	n.
Tu"na	n.
Tun"a*ble	a.
Tun"-bel`lied	a.
Tun"-dish`	n.
Tun"dra	n.
Tune	n.
Tune	v. t.
Tune	v. i.
Tune"ful	a.
Tune"less	a.
Tun"er	n.
Tun"-great`	a.
Tung"state	n.
Tung"sten	n.
Tung*sten"ic	a.
Tung"sten lamp	a.
Tung"stite	n.
Tun*gus"es	n. pl.
Tun*gus"ic	a.
Tun"hoof`	n.
Tu"nic	n.
Tu"ni*ca*ry	n.
Tu`ni*ca"ta	pr. n. pl.
Tu"ni*cate	a.
Tu"ni*cate	pr. n.
Tu"ni*cin	n.
Tu"ni*cle	n.
Tun"ing	a. & n.
Tunk	n.
Tun"ker	n.
Tun"nage	n.
Tun"nel	n.
Tun"nel	v. t.
Tun"nel	v. i.
Tun"nel stern	n.
Tup	v. t. & i.
Tup	n.
Tu*pai"	n.
Tu*pai"id	n.
Tu"pe*lo	n.
Tu"pi	pr. n.
Tu"pi*an	a.
Tup"man	n.
tuppence	n.
Tupperware	n.
Tupperware party	n.
Tuque	n.
Tur	n.
Tu"ra*cin	n.
turaco	n.
Tu*ra`co*ver"din	n.
Tu*ra"ni*an	pr. a.
Tu*ra"ni*an	pr. n.
Tu*ra"ni*ans	n. pl.
Tu"ratt	n.
Tur"ban	n.
Tur"band	n.
Tur"baned	a.
Tur"ban-shell`	n.
Tur"bant	n.
Tur"ban-top`	n.
Tur"ba*ry	n.
Tur`bel*la"ri*a	n. pl.
Tur`bel*la"ri*an	n.
Tur"beth	n.
Tur"bid	a.
Tur*bid"i*ty	n.
Tur"bid*ly	adv.
Tur"bid*ness	n.
Tur*bil"lion	n.
Tur`bi*na"ceous	a.
Tur"bi*nal	a.
Tur"bi*nal	n.
Tur"bi*nate	v. i.
Tur"bi*nate	a.
Tur`bi*na"tion	n.
Tur"bine	n.
Tur`bi*nel"la	pr. n.
Tur"bi*nite	n.
Tur"bi*noid	a.
Tur"bit	n.
Tur"bite	n.
Tur"bith	n.
tur"bo	n.
tur"bo-	n.
Tur`bo*gen"er*a`tor	n.
Tur"bot	n.
Tur"bu*lence	n.
Tur"bu*len*cy	n.
Tur"bu*lent	a.
Tur"bu*lent*ly	adv.
Tur"cism	n.
Tur"co*man	pr. n.
Tur`di*for"mes	n. pl.
Tur"dus	pr. n.
Tu*reen"	n.
Tu*reen"ful	n.
Turf	n.
Turf	v. t.
Turf"en	a.
Turf"i*ness	n.
Turf"ing	n.
Turf"ite	n.
Turf"less	a.
Turf"man	n.
Turf"y	a.
Tur"gent	a.
Tur*gesce"	v. i.
Tur*ges"cence	n.
Tur*ges"cent	a.
Tur"gid	a.
Tur*gid"i*ty	n.
Tur"gid*ous	a.
Tu"ri*o	n.
Tu"ri*ole	n.
Tu"ri*on	n.
Tu`ri*o*nif"er*ous	a.
Turk	n.
Tur"keis	a.
Tur"key	pr. n.
Tur"key	n.
Tur"keys	a.
Tur"key-trot`	n.
Turk"ic	a.
Tur"kis	n.
Turk"ish	pr. a.
Turk"ism	n.
Tur"kle	n.
Turk"o	n.
Tur`ko-I*ra"ni*an	pr. a.
Tur`ko-I*ra"ni*an	pr. n.
Tur*kois"	n. & a.
Tur"ko*man	n.
Turk's"-head`	n.
Tur"lu*pin	n.
Turm	n.
Tur"ma*line	n.
Tur"mer*ic	n.
Tur"mer*ic	a.
Tur"mer*ol	n.
Tur"moil	n.
Tur*moil"	v. t.
Tur*moil"	v. i.
Turn	v. t.
Turn	v. i.
Turn	n.
Turn"broach`	n.
Turn"-buc`kle	n.
Turn"bull's blue`	n.
Turn"down`	a.
Turn"down`	n.
Tur"nep	n.
Turn"er	n.
Tur"ner	n.
Tur"ner*ite	n.
Turn"er*y	n.
Tur"ney	n. & v.
Turn"hal`le	n.
Tur`ni*ci*mor"phae	pr. n. pl.
Turn"ing	n.
Turn"ing*ness	n.
Tur"nip	n.
Tur"nip-shell"	n.
Tur"nix	n.
Turn"key`	n.
turn"key`	a.
Turn"-out`	n.
Turn"o`ver	n.
Turn"o`ver	a.
Turn"pike`	n.
Turn"pike`	v. t.
Turn"plate`	n.
Turn"-sick`	a.
Turn"-sick`	n.
Turn"sole`	n.
Turn"spit`	n.
Turn"stile`	n.
Turn"stone`	n.
Turn"ta`ble	n.
Tur"nus	n.
Turn"ve*rein`	n.
Turn"wrest`	n.
Tu*ro"ni*an	n.
Tur"pen*tine	n.
Tur"pen*tine State	n.
Tur"pin	n.
Tur"pi*tude	n.
Tur*quoise"	n.
Tur*quoise"	a.
Tur"rel	n.
Tur"ret	n.
Tur"ret deck	a.
Tur"ret*head	n.
Tur"ric*al	a.
Tur*ric"u*late	a.
Tur"ri*lite	n.
Tur`ri*tel"la	n.
Tur`ri*tel"loid	a.
Tur"tle	n.
Tur"tle	n.
Tur"tle*back`	n.
Tur"tle*dove`	n.
Tur"tle-foot`ed	a.
Tur"tle*head`	n.
Tur"tle peg	n.
Tur"tle-shell`	n.
Tur"tling	n.
Turves	pl.
Tus"can	a.
Tus"can	n.
Tus`ca*ro"ras	n. pl.
Tusch"e	n.
Tus"cor	n.
Tush	interj.
Tush	n.
tush	n.
tush"ie	n.
Tusk	n.
Tusk	n.
Tusk	v. i.
Tusked	a.
Tusk"er	n.
Tusk"-shell`	n.
Tusk"y	a.
Tus"sac grass`	n.
Tus"sah silk`	a.
Tus*sic"u*lar	a.
Tus"sis	n.
Tus"sive	a.
Tus"sle	v. i. & t.
Tus"sle	n.
Tus"sock	n.
Tus"sock*y	a.
Tus"suck	n.
Tut	interj.
Tut	n.
Tu"te*lage	n.
Tu"te*lar	a.
Tu"tele	n.
Tu"te*nag	n.
Tut"-mouthed`	a.
Tut"-nose`	n.
Tu"tor	n.
Tu"tor	v. t.
Tu"tor*age	n.
Tu"tor*ess	n.
Tu*to"ri*al	a.
tu*to"ri*al	n.
Tu"tor*ism	n.
Tu"tor*ize	v. t.
Tu"tor*ship	n.
Tu"tor*y	n.
Tu"tress	n.
Tu"trix	n.
Tut"san	n.
Tut"ti	n. pl.
Tut"ti-frut`ti	n.
Tut"ty	n.
Tut"-work`	n.
Tut"-work`man	n.
Tu"um	n.
Tu-whit"	n. & interj.
tux	n.
Tu`y<egrave/re"	n.
Tuz	n.
Tu"za	n.
Twad"dell	n.
Twad"dle	v. i. & t.
Twad"dle	n.
Twad"dler	n.
Twad"dling	a. & n.
Twad"dy	n.
Twag"ger	n.
Twain	a. & n.
Twaite	n.
Twaite	n.
Twang	n.
Twang	v. i.
Twang	v. t.
Twang	n.
Twan"gle	v. i. & t.
Twank	v. t.
Twan"kay	n.
'T was	v. i.
Twat"tle	v. t.
Twat"tle	n.
Twat"tler	n.
Tway	a. & n.
Tway"blade`	n.
Tweag	v. t.
Tweag	n.
Tweak	v. t.
Tweak	n.
Tweed	n.
Twee"dle	v. t.
Twee"dle*dum` and Twee"dle*dee`	n. & v.
Tweer	n.
Tweese	n.
Twee"zers	n. pl.
Twelfth	a.
Twelfth	n.
Twelfth"-cake`	n.
Twelfth"-day`	n.
Twelfth"-night`	n.
Twelfth"-sec`ond	n.
Twelfth"tide`	n.
Twelve	a.
Twelve	n.
Twelve"mo	a. & n.
Twelve"month	n.
Twelve"pence	n.
Twelve"pen*ny	a.
Twelve"score`	n. & a.
Twen"ti*eth	a.
Twen"ti*eth	n.
Twen"ty	a.
Twen"ty	n.
Twen"ty*fold`	a.
Twen`ty-four"mo	a.
twenty-four-seven	adj. & adv.
Twey	a.
Twey"fold`	a.
Twi"bil	n.
Twi"billed	a.
Twice	adv.
Twid"dle	v. t.
Twid"dle	v. i.
Twid"dle	n.
Twi"fal`low	v. t.
Twi"fold`	a.
Twig	v. t.
Twig	v. t.
Twig	n.
Twig	v. t.
Twig"gen	a.
Twig"ger	n.
Twig"gy	a.
Twight	v. t.
Twight	p. p.
Twight"e	imp.
Twig"less	a.
Twig"some	a.
Twi"light`	n.
Twi"light`	a.
Twill	v. t.
Twill	n.
Twil"ly	n.
Twilt	n.
Twin	a.
Twin	n.
Twin	v. i.
Twin	v. t.
Twin	v. i.
Twin"born`	a.
Twine	n.
Twine	v. t.
Twine	v. i.
Twin"er	n.
Twinge	v. t.
Twinge	v. i.
Twinge	n.
Twin"ing	a.
Twin"ing	a.
Twink	v. i.
Twink	n.
Twin"kle	v. i.
Twin"kle	n.
Twin"kler	n.
Twin"kling	n.
Twin"leaf`	n.
Twin"like`	a.
Twin"ling	n.
Twinned	a.
Twin"ner	n.
Twin"ning	n.
Twin"ter	n.
Twire	n.
Twire	v. i.
Twire	v. i.
Twire"-pipe`	n.
Twirl	v. t.
Twirl	v. i.
Twirl	n.
Twist	v. t.
Twist	v. i.
Twist	n.
Twist"e	imp.
Twist"ed	a.
Twist"er	n.
Twist"ic*al	a.
Twist"ing	a. & n.
Twit	v. t.
Twitch	v. t.
Twitch	n.
Twitch"er	n.
Twitch" grass`	n.
Twit"lark`	n.
Twit"ter	n.
Twit"ter	v. i.
Twit"ter	v. t.
Twit"ter	n.
Twit"ter*ing	n.
Twit"ting*ly	adv.
Twit"tle-twat`tle	n.
'Twixt	n.
Two	a.
Two	n.
Two"-cap`suled	a.
Two"-cleft`	a.
Two"-cy`cle	n.
Two"-deck`er	n.
Two"-edged`	a.
Two"fold`	a.
Two"fold`	adv.
Two"-foot`	a.
Two"-forked`	a.
Two"-hand`	a.
Two"-hand`ed	a.
Two"-lipped`	a.
Two"-name`	a.
Two"-part`ed	a.
Two"pence	n.
Two"pen*ny	a.
Two"-phase`	a.
Two"-ply`	a.
Two"-port`	a.
Two"-ranked`	a.
Two"-sid`ed	a.
Two"-speed`	a.
Two"-step`	n.
Two"-throw`	a.
Two"-tongued`	a.
Two"-to-one"	a.
Two"-way`	a.
Twy"blade`	n.
Ty"-all`	n.
Ty"burn tick`et	n.
Ty*chon"ic	a.
Ty*coon"	n.
Ty"dy	n.
Tye	n.
Tye	v. t.
Ty"er	n.
Ty*foon"	n.
Ty"ger	n.
Ty"ing	p. pr.
Ty"ing	n.
Tyke	n.
Ty"la*rus	n.
Ty"ler	n.
Ty*lop"o*da	n. pl.
Ty*lo"sis	n.
Tym"bal	n.
Tymp	n.
Tym"pan	n.
Tym"pa*nal	n.
Tym*pan"ic	a.
Tym*pan"ic	n.
Tym"pa*nist	n.
Tym`pa*ni"tes	n.
Tym`pa*nit"ic	a.
Tym`pa*ni"tis	n.
Tym"pa*nize	v. i.
Tym"pa*nize	v. t.
Tym"pa*no	n.
Tym"pa*no-	a.
Tym"pa*num	n.
Tym"pa*ny	n.
Tynd	v. t.
Tyne	v. t.
Tyne	v. i.
Tyne	n.
Tyne	n.
Ty"ny	a.
Typ"al	a.
-type	n.
Type	n.
Type	v. t.
Type"set`ter	n.
Type"set`ting	n.
Type"write`	v. t. & i.
Type"writ`er	n.
Type"writ`ing	n.
Typh*li"tis	n.
Typh"lo*sole	n.
Ty*pho"e*an	a.
Ty"phoid	a.
Ty`pho*ma*la"ri*al	a.
Ty`pho*ma"ni*a	n.
Ty"phon	n.
Ty*phoon"	n.
Ty"phos	n.
Ty`pho*tox"in	n.
Ty"phous	a.
Ty"phus	n.
Typ"ic	a.
Typ"ic*al	a.
Typ`i*fi*ca"tion	n.
Typ"i*fi`er	n.
Typ"i*fy	v. t.
Typ"ist	n.
Ty"po	n.
Ty"po	n.
Typ"o*cos`my	n.
Ty"po*graph	n.
Ty*pog"ra*pher	n.
Ty`po*graph"ic	a.
Ty*pog"ra*phy	n.
Typ"o*lite	n.
Ty`po*li*thog"ra*phy	n.
Ty*pol"o*gy	n.
Ty*poth"e*tae	n. pl.
Ty"ran	n.
Ty"ran*ness	n.
Ty*ran"nic	a.
Ty*ran"ni*ci`dal	a.
Ty*ran"ni*ci`de	n.
Tyr"an*nish	a.
Tyr"an*nize	v. i.
Tyr"an*nize	v. t.
Tyr"an*nous	a.
Tyr"an*ny	n.
Tyr"ant	n.
Ty"rant	v. i.
Tyre	n.
tyre	n.
Tyre	n. & v.
Tyre	v. i.
Tyr"i*an	a.
Tyr"i*an	n.
Ty"ro	n.
Ty"ro*cin*y	n.
Tyr"o*lite	n.
Ty"ro*nism	n.
Tyr"o*sin	n.
Tyr`o*tox"i*con	n.
Tyr`o*tox"ine	n.
Ty"son*ite	n.
Ty"stie	n.
Tythe	n.
Tyth"ing	n.
Tzar	n.
Tza*ri"na	n.
Tzet"ze	n.
