V	n.
Va"can*cy	n.
Va"cant	a.
Va"cant*ly	adv.
Va"cate	v. t.
Va*ca"tion	n.
Va*ca"tur	n.
Vac"ca*ry	n.
Vac*ci"na	n.
Vac"ci*nal	a.
Vac"ci*nate	v. t.
Vac`ci*na"tion	n.
Vac"ci*na`tor	n.
Vac"cine	a.
Vac"cine	n.
Vac"cine point`	n.
Vac*cin"i*a	n.
Vac"ci*nist	n.
Vac*cin"i*um	n.
Va`cher"	n.
Vach"er*y	n.
Va`chette" clasp	n.
Vac"il*lant	a.
Vac"il*late	v. i.
Vac"il*la`ting	a.
Vac`il*la"tion	n.
Vac"il*la*to*ry	a.
Vac"u*ate	v. t.
Vac`u*a"tion	n.
Vac"u*ist	n.
Va*cu"i*ty	n.
Va*cu"na	prop. n.
Vac"u*o*la`ted	a.
Vac"u*o*la"tion	n.
Vac"u*ole	n.
Vac`u*om"e*ter	n.
Vac"u*ous	a.
Vac"u*ous*ness	n.
Vac"u*um	n.
Vac"u*um clean"er	n. pl.
Vade	v. i.
Va`de me"cum	n.
Va"di*um	n.
Vae	n.
Va"frous	a.
Vag"a*bond	a.
Vag"a*bond	n.
Vag"a*bond	v. i.
Vag"a*bond`age	n.
Vag"a*bond`ism	n.
Vag"a*bond`ize	v. i.
Vag"a*bond`ry	n.
Va"gal	a.
Va"gan*cy	n.
Va*gan"tes	prop. n. pl.
Va*ga"ri*ous	a.
Va*ga"ry	n.
Va"gi*ent	a.
Va*gi"na	n.
Vag"i*nal	a.
Vag"i*nant	a.
Vag"i*nate	a.
Vag`i*na"ti	n. pl.
Vag`i*ner*vose"	a.
Vag`i*nic"o*la	prop. n.
Vag`i*nis"mus	n.
Vag`i*ni"tis	n.
Vag`i*no*pen"nous	a.
Va*gin"u*la	n.
Vag"i*nule	n.
Vag"is*sate	v. i.
Va"gous	a.
Va"gran*cy	n.
Va"grant	a.
Va"grant	n.
Va"grant*ly	adv.
Va"grant*ness	n.
Vague	a.
Vague	n.
Vague	v. i.
Vague	n.
Vague"ly	adv.
Vague"ness	n.
Va"gus	a.
Vail	n. & v. t.
Vail	n.
Vail	v. t.
Vail	v. i.
Vail	n.
Vail"er	n.
Vai"mure	n.
Vain	a.
Vain	n.
Vain`glo"ri*ous	a.
Vain`glo"ry	n.
Vain"ly	adv.
Vain"ness	n.
Vair	n.
Vair"y	a.
Vaish"na*va	n.
Vaish"na*vism	n.
Vais"ya	n.
Vai"vode	n.
Va*keel"	n.
Val"ance	n.
Val"ance	v. t.
Vale	n.
Vale	n.
Val`e*dic"tion	n.
Val`e*dic*to"ri*an	n.
Val`e*dic"to*ry	a.
Val`e*dic"to*ry	n.
Va"lence	n.
Va*len"ci*a	n.
Va*len`ci*ennes" lace"	n.
Va*len"ti*a	n.
Val"en*tine	n.
Val`en*tin"i*an	n.
Val`er*am"ide	n.
Val"er*ate	n.
Va*le"ri*an	n.
Va*le`ri*an*a"ceous	a.
Va*le"ri*an*ate	n.
Va*le`ri*an"ic	a.
Va*ler"ic	a.
Va*ler"i*dine	n.
Val"er*in	n.
Va*ler"i*trine	n.
Val"er*o-	n.
Val"er*yl	n.
Val`er*yl*ene	n.
Val"et	n.
Val`e*tu`di*na"ri*an	a.
Val`e*tu`di*na"ri*an	n.
Val`e*tu`di*na"ri*an*ism	n.
Val`e*tu"di*na*ry	a.
Val`e*tu"di*na*ry	n.
Val`e*tu"di*nous	a.
Val*hal"la	n.
Val"iance	n.
Val"iant	a.
Val"id	a.
Val"i*date	v. t.
Val`i*da"tion	n.
Va*lid"i*ty	n.
Val"id*ly	adv.
Val"id*ness	n.
Val"inch	n.
Va*lise"	n.
Val*kyr"i*a	n.
Val*kyr"i*an	a.
Val*lan"cy	n.
Val"lar	a.
Val"lar	n.
Val"la*ry	a.
Val*la"tion	n.
Val"la*to*ry	a.
Val*lec"u*la	n.
Val`let's pills"	n.
Val"lum	n.
Va*lo"ni*a	n.
Val"or	n.
Val`or*i*za"tion	n.
Val"or*ous	a.
Val*sal"vi*an	a.
Val"u*a*ble	a.
Val"u*a*ble	n.
Val"u*a*ble*ness	n.
Val"u*a*bly	adv.
Val`u*a"tion	n.
Val"u*a`tor	n.
Val"ue	n.
Val"ue	v. t.
Val"ued	a.
Val"ued pol"i*cy	a.
Val"u*er	n.
Val"ure	n.
Valv"al	a.
Val"va*sor	n.
Val*va"ta	n.
Valv"ate	a.
Valve	n.
Valved	a.
Valve"let	n.
Valve"-shell`	n.
Val"vu*la	n.
Valv"u*lar	a.
Valv"ule	n.
Val"yl*ene	n.
Vam"brace	n.
va*moose"	v. i. & t.
va*mose"	v. i. & t.
Vamp	v. i.
Vamp	n.
vamp	n.
Vamp	v. t.
vamp	v. t. & i.
Vamp"er	n.
Vamp"er	v. i.
Vam"pire	n.
Vam"pir*ism	n.
Vam"plate`	n.
Va"mure	n.
Van	n.
Van	n.
Van	v. t.
Van	n.
Van	n.
Van	v. t.
Van"a*date	n.
Va*nad"ic	a.
Va*nad"i*nite	n.
Va*na"di*ous	a.
Van"a*dite	n.
Va*na"di*um	n.
Va*na"di*um bronze`	a.
Van"a*dyl	n.
Van"-cou`ri*er	n.
Van"dal	n.
Van"dal	a.
Van"dal*ism	n.
Van*dyke"	a.
Van*dyke"	prop. n.
Van*dyke"	v. t.
Van*dyke" beard`	n.
Van*es"sa	n.
Van*es"si*an	n.
Van"foss`	n.
Vang	n.
Van"glo	n.
Van"guard`	n.
Va*nil"la	n.
Va*nil"late	n.
Va*nil"lic	a.
Va*nil"lin	n.
Va*nil"loes	n. pl.
Va*nil"lyl	n.
Va*nil"o*quence	n.
Va*nil"o*quent	a.
Van"ish	v. i.
Van"ish	n.
Van"ish*ing	a. & n.
Van"ish*ment	n.
Van"i*ty	n.
Van"i*ty box	n.
Van"ner	n.
Van"ner hawk`	n.
Van"quish	v. t.
Van"quish	n.
Van"quish*a*ble	a.
Van"quish*er	n.
Van"quish*ment	n.
Van"sire	n.
Vant	v. i.
Van"tage	n.
Van"tage	v. t.
Van"tage game	n.
Vantage point	n.
Vant"-cou`ri*er	n.
Van't Hoff's law	a.
Vap	n.
Vap"id	a.
Va*pid"i*ty	n.
Va"por	n.
Va"por	v. i.
Va"por	v. t.
Vap`o*ra*bil"i*ty	n.
Vap"o*ra*ble	a.
Vap"o*rate	v. i.
Vap`o*ra"tion	n.
Va"pored	a.
Va"por*er	n.
Va"por gal"va*niz`ing	a.
Vap`o*rif"ic	a.
Va*por"i*form	a.
Vap`o*rim"e*ter	n.
Va"por*ing	a.
Va"por*ish	a.
Vap"o*ri`za*ble	a.
Vap`o*ri*za"tion	n.
Vap"o*rize	v. t.
Vap"o*rize	v. i.
Vap"o*ri`zer	n.
Va"por*ose`	a.
Va"por*ous	a.
Va"por*ous*ness	n.
Vapor pressure	a.
Vap`u*la"tion	n.
Va*que"ro	n.
Va"ra	n.
Va"ran	n.
Va*ran"gi*an	n.
Va*ra"nus	prop. n.
Vare	n.
Vare	n.
Var"ec	n.
Var*gue"no	n.
Va"ri	n.
Va`ri*a*bil"i*ty	n.
Va"ri*a*ble	a.
Va"ri*a*ble	n.
Va"ri*a*ble*ness	n.
Va"ri*a*bly	adv.
Va"ri*ance	n.
Va"ri*ant	a.
Va"ri*ant	n.
Va"ri*ate	v. t. & i.
Va`ri*a"tion	n.
Var`i*cel"la	n.
Var"i*ces	n. pl.
Va*ric"i*form	a.
Var"i*co*cele	n.
Var"i*cose`	a.
Var`i*cos"is	n.
Var`i*cos"i*ty	n.
Var`i*cot"o*my	n.
Var"i*cous	a.
Va"ried	a.
Va"ri*e*gate	v. t.
Va"ri*e*ga`ted	a.
Va`ri*e*ga"tion	n.
Va"ri*er	n.
Va*ri"e*tal	a.
Va*ri"e*tas	n.
Va*ri"e*ty	n.
Variety show	a.
Va"ri*formed	a.
Va"ri*fy	v. t.
Va*ri"o*la	n.
Va*ri"o*lar	a.
Va`ri*o*la"tion	n.
Va"ri*ole	n.
Va`ri*ol"ic	a.
Va"ri*o*lite	n.
Va`ri*o*lit"ic	a.
Va"ri*o*loid	a.
Va"ri*o*loid	n.
Va*ri"o*lous	a.
Va`ri*om"e*ter	n.
Va`ri*o"rum	a.
Va"ri*ous	a.
Va"ri*ous*ly	adv.
Var"is*cite	n.
Va*risse"	n.
Va"rix	n.
Vark	n.
Var"let	n.
Var"let*ry	n.
Var"nish	n.
Var"nish	v. t.
Var"nish*er	n.
Var"nish*ing	n.
Var"si*ty	n.
Var`so`vienne"	n.
Var"ta*bed	n.
Va*ru"na	n.
Va"rus	n.
Var"vel	n.
Var"veled	a.
Va"ry	v. t.
Va"ry	v. i.
Va"ry	n.
Va"ry*ing	a. & n.
Vas	n.
Vas"cu*lar	a.
Vas`cu*lar"i*ty	n.
Vas`cu*lar*i*za"tion	n.
Vas"cu*lose`	n.
Vas"cu*lum	n.
Vase	n.
Vase clock	n.
Vas"e*line	n.
Vase"-shaped`	a.
Vas"i*form	a.
Vas`o*con*strict"or	a.
Vas`o*con*strict"or	n.
Vas`o*den"tine	n.
Vas`o*di*lat"or	a.
Vas`o*di*lat"or	n.
Vas`o*form"a*tive	a.
Vas`o*hy`per*ton"ic	a.
Vas`o*hy`po*ton"ic	a.
Vas`o-in*hib"i*to*ry	a.
Vas`o*mo"tor	a.
Vas"sal	n.
Vas"sal	a.
Vas"sal	v. t.
Vas"sal*age	n.
Vas"sal*ess	n.
Vas"sal*ry	n.
Vast	a.
Vast	n.
Vas*ta"tion	n.
Vas"tel	n.
Vas*tid"i*ty	n.
Vas"ti*tude	n.
Vast"i*ty	n.
Vast"ly	adv.
Vast"ness	n.
Vas"ty	a.
Va"sum	n.
Vat	n.
Vat	v. t.
Vat"ful	n.
Vat"ic*al	a.
Vat"i*can	n.
Vat"i*can Coun"cil	n.
Vat"i*can*ist	n.
Vat"i*cide	n.
Va*tic"i*nal	a.
Va*tic"i*nate	v. i. & t.
Va*tic`i*na"tion	n.
Va*tic"i*na`tor	n.
Vat"i*cine	n.
Vaude"ville	n.
Vau*dois"	n. sing. & pl.
Vau*doux"	n. & a.
Vault	n.
Vault	v. t.
Vault	v. i.
Vault"age	n.
Vault"ed	a.
Vault"er	n.
Vault"ing	n.
Vault"y	a.
Vaunce	v. i.
Vaunt	v. i.
Vaunt	v. t.
Vaunt	n.
Vaunt	n.
Vaunt	v. t.
Vaunt"-cou`ri*er	n.
Vaunt"er	n.
Vaunt"ful	a.
Vaunt"ing*ly	adv.
Vaunt"mure`	n.
Vauque"lin*ite	n.
Vaut	v. i.
Vaut	n.
Vaut"y	a.
Vav"a*sor	n.
Vav"a*so*ry	n.
Va"ward`	n.
Va"za par`rot	n.
Ve"a*dar	n.
Veal	n.
Vec"tion	n.
Vec`ti*ta"tion	n.
Vec"tor	n.
Vec"ture	n.
Ve"da	n.
Ve*dan"ta	n.
Ve*dan"tic	a.
Ve*dan"tist	n.
Ved"dahs	n. pl.
Ve*dette"	n.
Ve"dic	a. 
Ve"dro	n.
Veer	v. i.
Veer	v. t.
Veer"a*ble	a.
Veer"ing	a.
Veer"y	n.
Ve"ga	n.
Ve"ga	n.
ve"gan	n.
Veg`e*ta*bil"i*ty	n.
Veg`e*ta*ble	a.
Veg"e*ta*ble	n.
Veg"e*tal	a.
Veg"e*tal	n.
Veg`e*tal"i*ty	n.
Veg`e*ta"ri*an	n.
Veg`e*ta"ri*an	a.
Veg`e*ta"ri*an*ism	n.
Veg"e*tate	v. i.
Veg`e*ta"tion	n.
Veg"e*ta*tive	a.
Ve*gete"	a.
Veg"e*tism	n.
Veg"e*tive	a.
Veg"e*tive	n.
Veg"e*to-an"i*mal	a.
Veg"e*tous	a.
Ve"he*mence	n.
Ve"he*men*cy	n.
Ve"he*ment	a.
Ve"he*ment*ly	adv.
Ve"hi*cle	n.
Ve"hi*cled	a.
Ve*hic"u*lar	a.
Ve*hic"u*la*ry	a.
Ve*hic"u*late	v. t. & i.
Ve*hic`u*la"tion	n.
Ve*hic"u*la*to*ry	a.
Vehm	n.
Vehm"ge*richt	n.
Veh"mic	a.
Veil	n.
Veil	v. t.
Veiled	a.
Veiled plate	n.
Veil"less	a.
Vein	n.
Vein	v. t.
Vein"al	a.
Veined	a.
Vein"less	a.
Vein"let	n.
Vein"ous	a.
Vein quartz	n.
Vein"y	a.
Ve"lar	a.
Ve*la"ri*um	n.
Ve"late	a.
Veldt	n.
Veldt sore	n.
Ve*lel"la	n.
Ve*lif"er*ous	a.
Vel"i*ger	n.
Vel`i*ta"tion	n.
Ve*liv"o*lant	a.
Vell	n.
Vell	v. i.
Vel*le"i*ty	n.
Vel"let	n.
Vel"li*cate	v. t.
Vel"li*cate	v. i.
Vel`li*ca"tion	a.
Vel*lon"	n.
Vel"lum	n.
Vel"lum*y	a.
Vel`o*cim"e*ter	n.
Ve*loc"i*pede	n.
Ve*loc"i*pe`dist	n.
Ve*loc"i*ty	n.
Ve*lours"	n.
Ve*lou`t<eacute/"	n.
Velt"fare	n.
Ve"lum	n.
Vel"ure	n.
Vel`u*ti"na	n.
Ve*lu"ti*nous	a.
Vel"verd	n.
Vel`ver*et"	n.
Vel"vet	n.
Vel"vet	a.
Vel"vet	v. i.
Vel"vet	v. t.
Vel"vet*breast`	n.
Vel`vet*een"	n.
Vel"vet*ing	n.
Vel"vet*leaf`	n.
Vel"vet*y	a.
Ve"na	n.
Ve*na"da	n.
Ve"nal	a.
Ve"nal	a.
Ve*nal"i*ty	n.
Ve"nal*ly	adv.
Ve*nan"tes	n. pl.
Ven"a*ry	a.
Ve*nat"ic	a.
Ve*nat"i*ca	n.
Ve*na"tion	n.
Ve*na"tion	n.
Ven`a*to"ri*al	a.
Vend	v. t.
Vend	n.
Ven"dace	n.
Vend*ee"	n.
Ven`d<eacute/`miaire"	n.
Vend"er	n.
Ven*det"ta	n.
Vend`i*bil"i*ty	n.
Vend"i*ble	a.
Vend"i*ble	n.
Ven"di*tate	v. t.
Ven`di*ta"tion	n.
Ven*di"tion	n.
Vend"or	n.
Vend"or's lien	n. pl.
Ven*due"	n.
Ve*neer"	v. t.
Ve*neer"	n.
Ve*neer"ing	n.
Ve*nef"ic*al	a.
Ven"e*fice	n.
Ven`e*fi"cial	a.
Ven"e*mous	a.
Ven"e*nate	v. t.
Ven"e*nate	a.
Ven`e*na"tion	n.
Ve*nene"	a.
Ven"e*nose`	a.
Ven`er*a*bil"i*ty	n.
Ven"er*a*ble	a.
Ven`e*ra"ce*a	prop. n. pl.
Ven"er*ate	v. t.
Ven`er*a"tion	n.
Ven"er*a`tor	n.
Ve*ne"re*al	a.
Ve*ne"re*al	n.
Ve*ne"re*an	a.
Ve*ne"re*ous	a.
Ven"er*ous	a.
Ven"er*y	n.
Ven"er*y	n.
Ve`ne*sec"tion	n.
Ve*ne"tian	a.
Ve*ne"tian	n.
Ven"ew	n.
Ven"ey	n.
Venge	v. t.
Venge"a*ble	a.
Venge"ance	n.
Venge"ance*ly	adv.
Venge"ful	a.
Venge"ment	n.
Ven"ger	n.
Ve"ni*a*ble	a.
Ve"ni*al	a.
Ve`ni*al"i*ty	n.
Ven"in	n.
Ve*ni"re fa"ci*as	n.
Ve*ni"te	n.
Ven"om	n.
Ven"om	v. t.
Ven"om*ous	a.
Ve*nose"	a.
Ve*nos"i*ty	n.
Ven"ous	a.
Vent	n.
Vent	v. t.
Vent	n.
Vent	v. i.
Vent	n.
Vent	v. t.
Vent"age	n.
Vent"ail	n.
Vent"er	n.
Vent"er	n.
Vent"hole	n.
Ven"ti*duct	n.
Ven"ti*late	v. t.
Ven`ti*la"tion	n.
Ven"ti*la*tive	a.
Ven"ti*la`tor	n.
Ven*tose"	n.
Ven*tose"	a.
Ven`tose"	n.
Ven*tos"i*ty	n.
Ven"touse	n.
Ven"touse	v. t. & i.
Ven"trad	adv.
Ven"tral	a.
Ven"tri*cle	n.
Ven"tri*cose`	a.
Ven*tric"u*lar	a.
Ven*tric"u*lite	n.
Ven*tric"u*lous	a.
Ven*tric"u*lus	n.
Ven`tri*lo*cu"tion	n.
Ven`tri*lo"qui*al	a.
Ven*tril"o*quism	n.
Ven*tril"o*quist	n.
Ven*tril"o*quize	v. i.
Ven*tril"o*quous	a.
Ven*tril"o*quy	n.
Ven`tri*mes"on	n.
Ven"tro-	a.
Ven"ture	n.
Ven"ture	v. i.
Ven"ture	v. t.
Ven"tur*er	n.
Ven"ture*some	a.
Ven"tur*ine	n.
Ven"tur*ous	a.
Ven"tuse	v. t. & i.
Ven"ue	n.
Ven"ule	n.
Ven"u*lose`	a.
Ve"nus	n.
Ve*nust"	a.
Ve*ra"cious	a.
Ve*ra"cious*ly	adv.
Ve*rac"i*ty	n.
Ve*ran"da	n.
Ver`a*tral"bine	n.
Ve*ra"trate	n.
Ve*ra"tri*a	n.
Ve*ra"tric	a.
Ver`a*tri"na	n.
Ve*ra"trine	n.
Ve*ra"trol	n.
Ve*ra"trum	prop. n.
Verb	n.
Ver"bal	a.
Ver"bal	n.
Ver"bal*ism	n.
Ver"bal*ist	n.
Ver*bal"i*ty	n.
Ver`bal*i*za"tion	n.
Ver"bal*ize	v. t.
Ver"bal*ize	v. i.
Ver"bal*ly	adv.
Ver*ba"ri*an	a.
Ver*ba"ri*an	n.
Ver*ba"ri*um	n.
Ver*ba"tim	adv.
Ver*be"na	n.
Ver`be*na"ceous	a.
Ver"be*nate	v. t.
Ver"ber*ate	v. t.
Ver`ber*a"tion	n.
Ver"bi*age	n.
Verb"i*fy	v. t.
Ver*big"er*ate	v. i.
Ver*bose"	a.
Ver*bos"i*ty	n.
Verd	n.
Ver"dan*cy	n.
Ver"dant	a.
Verd` an*tique"	adv.
Ver"der*er	n.
Ver"dict	n.
Ver"di*gris	n.
Ver"di*gris	v. t.
Ver"din	n.
Ver"dine	n.
Ver"din*gale	n.
Ver"dit	n.
Ver"di*ter	n.
Ver"di*ture	n.
Ver"doy	a.
Ver"dure	n.
Ver"dured	a.
Ver"dure*less	a.
Ver"dur*ous	a.
Ver"e*cund	a.
Ver`e*cun"di*ous	a.
Ver`e*cun"di*ty	n.
Ver*ein"	n.
Ver`e*til"lum	n.
Ver"ga*lieu	n.
Verge	n.
Verge	v. i.
Verge"board`	n.
Ver"gen*cy	n.
Ver"ger	n.
Ver"ger	n.
Ver`get`t<eacute/"	a.
Ver*gette"	n.
Ve*rid"ic*al	a.
Ver"i*fi`a*ble	a.
Ver`i*fi*ca"tion	n.
Ver"i*fi*ca*tive	a.
Ver"i*fi`er	n.
Ver"i*fy	v. t.
Ve*ril"o*quent	a.
Ver"i*ly	adv.
Ver"ine	n.
Ver`i*sim"i*lar	a.
Ver`i*si*mil"i*tude	n.
Ver`i*si*mil"i*ty	n.
Ver`i*sim"i*lous	a.
Ver"i*ta*ble	a.
Ver"i*tas	n.
Ver"i*ty	n.
Ver"juice`	n.
Ver"meil	n.
Ver`me*ol"o*gist	n.
Ver`me*ol"o*gy	n.
Ver"mes	n. pl.
Ver"me*tid	n.
Ver*me"tus	n.
Ver`mi*cel"li	n.
Ver"mi*cide	n.
Ver*mi"cious	a.
Ver*mic"u*lar	a.
Ver*mic"u*late	v. t.
Ver*mic"u*late	a.
Ver*mic"u*la`ted	a.
Ver*mic`u*la"tion	n.
Ver"mi*cule	n.
Ver*mic"u*lite	n.
Ver*mic"u*lose`	a.
Ver"mi*form	a.
Ver`mi*for"mi*a	n. pl.
Ver*mif"u*gal	a.
Ver"mi*fuge	n.
Ver"mil	n.
Ver`mi*lin"gui*a	n. pl.
Ver*mil"ion	n.
Ver*mil"ion	v. t.
Ver"mi*ly	n.
Ver"min	n. sing. & pl.
Ver"mi*nate	v. i.
Ver`mi*na"tion	n.
Ver"min*ly	a. & adv.
Ver"min*ous	a.
Ver"min*ous*ly	adv.
Ver*mip"a*rous	a.
Ver*miv"o*rous	a.
Ver"muth	n.
Ver"na*cle	n.
Ver*nac"u*lar	a.
Ver*nac"u*lar	n.
Ver*nac"u*lar*ism	n.
Ver*nac"u*lar*i*za"tion	n.
Ver*nac"u*lar*ly	adv.
Ver*nac"u*lous	a.
Ver"nage	n.
ver"nal	a.
Ver"nant	a.
Ver"nate	v. i.
Ver*na"tion	n.
Ver"ner's law	n.
Ver"ni*cose`	a.
Ver"ni*er	n.
Ver"nile	a.
Ver*nil"i*ty	n.
Ver"nine	n.
Ver"nish	n. & v.
Ver"no*nin	n.
Ver`o*nese"	a.
Ve*ron"i*ca	n.
Ver"ray	a.
Ver"ray*ment	adv.
Ver"rel	n.
Ver*ric"u*late	a.
Ver*ru"ca	n.
Ver*ru"ci*form	a.
Ver"ru*cose`	a.
Ver"ru*cous	a.
Ver*ru"cu*lose`	a.
Ver*ru"gas	n.
Vers	n. sing. & pl.
Ver`sa*bil"i*ty	n.
Ver"sa*ble	a.
Ver"sa*ble*ness	n.
Ver"sal	a.
Ver"sant	a.
Ver"sant	n.
Ver"sa*tile	a.
Ver`sa*til"i*ty	n.
Vers` de so`ci<eacute/`t<eacute/"	n.
Verse	v. t.
Verse	v. i.
Versed	a.
Versed	a.
Verse"man	n.
Verse"mon`ger	n.
Vers"er	n.
Vers"et	n.
Ver"si*cle	n.
Ver"si*col`or	a.
Ver*sic"u*lar	a.
Ver`si*fi*ca"tion	n.
Ver"si*fi*ca`tor	n.
Ver"si*fi`er	n.
Ver"si*fy	v. i.
Ver"si*fy	v. t.
Ver"sion	n.
Ver"sion*ist	n.
Ver"so	n.
Ver"sor	n.
Verst	n.
Ver"su*al	a.
Ver"sus	prep.
Ver*sute"	a.
Vert	n.
Ver"te*ber	n.
Ver"te*bra	n.
Ver"te*bral	a.
Ver"te*bral	n.
Ver"te*bral*ly	adv.
Ver`te*brar*te"ri*al	a.
Ver`te*bra"ta	n. pl.
Ver"te*brate	n.
Ver"te*brate	a.
Ver"te*bre	n.
Ver"te*bro-	a.
Ver"tex	n.
Ver"ti*cal	a.
Ver"ti*cal	n.
Ver`ti*cal"i*ty	n.
Ver"ti*cal*ly	adv.
Ver"ti*cal*ness	n.
Ver"ti*cil	n.
Ver`ti*cil*las"ter	a.
Ver*tic"il*late	a.
Ver`ti*cil"lus	n.
Ver*tic"i*ty	n.
Ver"ti*cle	n.
Ver*tig"i*nate	a.
Ver*tig"i*nous	a.
Ver"ti*go	n.
Ver`ti*lin"e*ar	a.
Ver"tu	n.
Ver"tu*ous	a.
Ver`u*mon*ta"num	n.
Ver"vain	n.
Verve	n.
Ver"vel	n.
Ver"vet	n.
Ver"y	a.
Ver"y	adv.
Ver"y's night signals	n.
Vese	n.
Ve*si"ca	n.
Ves"i*cal	a.
Ves"i*cant	n.
Ves"i*cate	v. t.
Ves`i*ca"tion	n.
Ves"i*ca*to*ry	a.
Ves"i*cle	n.
Ves"i*co-	a.
Ves`i*co*u"ter*ine	a.
Ves`i*co*vag"i*nal	a.
Ve*sic"u*la	n.
Ve*sic"u*lar	a.
Ve*sic`u*la"ri*a	n.
Ve*sic`u*la"ta	n. pl.
Ve*sic"u*late	a.
Ve*sic"u*late	v. t.
Ve*sic`u*la"tion	n.
Ve*sic`u*li"tis	n.
Ve*sic"u*lose`	a.
Ves"pa	prop. n.
Ves"per	n.
Ves"per	a.
Ves"per*al	a.
Ves"pers	n. pl.
Ves`per*til"i*o	n.
Ves`per*til`i*o"nes	n. pl.
Ves`per*til`i*o"nine	a.
Ves"per*ti`nal	a.
Ves"per*tine	a.
Ves"pi*a*ry	n.
Ves*pil"lo	n.
Ves"sel	n.
Ves"sel	v. t.
Ves"sel*ful	n.
Ves"ses	n.
Ves"sic*non	n.
Vest	n.
Vest	v. t.
Vest	v. i.
Ves"ta	n.
Ves"tal	a.
Ves"tal	n.
Ves*ta"les	n. pl.
Vest"ed	a.
Vest"ed interest	a.
Ves"ti*a*ry	n.
Ves"ti*a*ry	a.
Ves*tib"u*lar	a.
Ves"ti*bule	n.
Ves"ti*bule	v. t.
Vestibuled train	n.
Ves"ti*gate	v. t.
Ves"tige	n.
Ves*tig"i*al	a.
Vest"ing	n.
Ves"ti*ture	n.
Vest"let	n.
Vest"ment	n.
Ves"try	n.
Ves"try*man	n.
Ves"ture	n.
Ves"tured	a.
Ve*su"vi*an	a.
Ve*su"vi*an	n.
Ve*su"vi*an*ite	n.
Ve*su"vine	n.
Vetch	n.
Vetch"ling	n.
Vetch"y	a.
Vet"er*an	a.
Vet"er*an	n.
Vet"er*an*ize	v. i.
vet`er*i*na"ri*an	n.
Vet"er*i*na*ry	a.
Vet"i*ver	n.
Ve"to	n.
Ve"to	v. t.
Ve"to*ist	n.
Vet*tu"ra	n.
Vet`tu*ri"no	n.
Ve*tust"	a.
Vex	v. t.
Vex	v. i.
Vex*a"tion	n.
Vex*a"tious	a.
Vexed	a.
Vex"er	n.
Vex"il	n.
Vex"il*lar	n.
Vex`il*la"tion	n.
Vex*il"lum	n.
Vex"ing*ly	adv.
V" hook`	n.
Vi"a	prep.
Vi`a*bil"i*ty	n.
Vi"a*ble	a.
Vi`a*duct	n.
Vi"age	n.
Vi"al	n.
Vi"al	v. t.
Vi*am"e*ter	n.
Vi"and	n.
Vi"and*er	n.
Vi"-ap`ple	n.
Vi"a*ry	a.
Vi"a*tec`ture	n.
Vi*at"ic	a.
Vi*at"i*cum	n.
Vi`a*tom"e*ter	n.
Vi*bi"ces	n. pl.
Vi*brac"u*lum	n.
Vi"bran*cy	n.
Vi"brant	a.
Vi"brate	v. t.
Vi"brate	v. i.
Vi"bra*tile	a.
Vi`bra*til"i*ty	n.
Vi*bra"tion	n.
Vi*bra"ti*un`cle	n.
Vi"bra*tive	a.
Vi"bra*tor	n.
Vi"bra*to*ry	a.
Vib"ri*o	prop. n.
Vi*bris"sa	n.
Vi"bro*graph	n.
Vi"bro*scope	n.
Vi*bur"num	n.
Vic"ar	n.
Vic"ar*age	n.
Vi*ca"ri*al	a.
Vi*ca"ri*an	n.
Vi*ca"ri*ate	a.
Vi*ca"ri*ate	n.
Vi*ca"ri*ous	a.
Vi*ca"ri*ous*ly	adv.
Vic"ar*ship	n.
Vic"ar*y	n.
Vice	n.
Vice	n.
Vice	v. t.
Vi"ce	prep.
Vice	a.
Viced	a.
Vice*ge"ren*cy	n.
Vice*ge"rent	a.
Vice*ge"rent	n.
Vice"man	n.
Vic"e*na*ry	a.
Vi*cen"ni*al	a.
Vice`-re"gal	a.
Vice"roy	n.
Vice*roy"al*ty	n.
Vice"roy*ship	n.
Vi"ce*ty	n.
Vi"chy wa`ter	prop. n.
Vi"ci*ate	v. t.
Vic"i*nage	n.
Vic"i*nal	a.
Vic"ine	a.
Vic"ine	n.
Vi*cin"i*ty	n.
Vi`ci*os"i*ty	n.
Vi"cious	a.
Vi*cis"si*tude	n.
Vi*cis`si*tu"di*na*ry	a.
Vi*cis`si*tu"di*nous	a.
Vi*cis"sy duck`	a.
Vi*con"ti*els	n. pl.
Vi"count	n.
Vic"tim	n.
Vic"tim*ate	v. t.
Vic"tim*ize	v. t.
Vic"tor	n.
Vic"tor	a.
Vic"tor*ess	n.
Vic*to"ri*a	prop. n.
Victoria crape	a.
Vic`tor*ine"	n.
Vic*to"ri*ous	a.
Vic*to"ri*um	n.
Vic"to*ry	n.
Vic"tress	n.
Vic"trice	n.
Vic"trix	n.
Vict"ual	n.
Vict"ual	v. t.
Vict"ual*age	n.
Vict"ual*er	n.
Vict"ual*ing	a.
Vict"uals	n. pl.
Vic"tus	n.
Vi*cu"<ntil/a	n.
Vid"a finch`	n.
Vi"de	imperative sing.
Vi*del"i*cet	adv.
videocasette	n.
videocasette recorder	n.
videotape	n.
Vi*dette"	n.
Vi*do"ni*a	n.
Vid"u*age	n.
Vid"u*al	a.
Vid`u*a"tion	n.
Vi*du"i*ty	n.
Vie	v. i.
Vie	v. t.
Vie	n.
Vi*elle"	n.
Vi*en"na paste`	a.
Vier"kleur`	n.
View	n.
View	v. t.
View"er	n.
View"i*ness	n.
View"less	a.
View"ly	a.
View"y	a.
Vif"da	n.
Vi*ges"i*mal	a.
Vi*ges`i*ma"tion	n.
Vi*ges"i*mo-quar"to	a.
Vi*ges"i*mo-quar"to	n.
Vig"il	n.
Vig"i*lance	n.
Vig"i*lan*cy	n.
Vig"i*lant	a.
Vig"i*lant*ly	adv.
Vig"i*ly	n.
Vi`gin*tiv"i*rate	n.
Vi*gnette"	n.
Vi*gnette"	v. t.
Vi*gnett"er	n.
Vi*go"ni*a	a.
Vig"or	n.
Vig"or	v. t.
Vig"or*ite	n.
Vig`o*ro"so	a. & adv.
Vig"or*ous	a.
Vi"king	n.
Vil"a*ny	n.
Vi`la*yet"	n.
Vild	a.
Vile	a.
Viled	a.
Vil"eyns	a.
Vil`i*fi*ca"tion	n.
Vil"i*fi`er	n.
Vil"i*fy	v. t.
Vil"i*pend	v. t.
Vil"i*pend"en*cy	n.
Vil"i*ty	n.
Vill	n.
Vil"la	n.
Vil"lage	n.
Vil"la*ger	n.
Vil"lage*ry	n.
Vil"lain	n.
Vil"lain	a.
Vil"lain	v. t.
Vil"lain*ous	a.
Vil"lain*y	n.
Vil"la*kin	n.
Vil"lan	n.
Vil"lan*age	n.
Vil`la*nel"	n.
Vil`la*nel"la	n.
Vil`la*nelle"	n.
Vil`la*nette"	n.
Vil"lan*ize	v. t.
Vil"lan*i`zer	n.
Vil"lan*ous	a.
Vil"lan*y	n.
Vil*lat"ic	a.
Vil"lein	n.
Vil"len*age	n.
Vil"len*ous	a.
Vil"li	n.
Vil"li*form	a.
Vil*lose"	a.
Vil*los"i*ty	n.
Vil"lous	a.
Vil"lus	n.
Vim	n.
Vi"men	n.
Vim"i*nal	a.
Vi*min"e*ous	a.
Vi*na"ceous	a.
Vin`ai*grette"	n.
Vin"ai*grous	a.
Vi*nasse"	n.
Vi*nat"i*co	n.
Vin*cen"tian	a.
Vin*cen"tian	n.
Vin`ce*tox"in	n.
Vin`ci*bil"i*ty	n.
Vin"ci*ble	a.
Vin"ci*ble*ness	n.
Vinc"ture	n.
Vin"cu*lum	n.
Vin*de"mi*al	a.
Vin*de"mi*ate	v. i.
Vin*de`mi*a"tion	n.
Vin"di*ca*ble	a.
Vin"di*cate	v. t.
Vin`di*ca"tion	n.
Vin"di*ca*tive	a.
Vin"di*ca`tor	n.
Vin"di*ca*to*ry	a.
Vin*dic"tive	a.
Vine	n.
Vi"ne*al	a.
Vine"-clad`	a.
Vined	a.
Vine"dress`er	n.
Vin"e*gar	n.
Vin"e*gar	v. t.
Vin`e*gar*ette"	n.
Vin"e*gar fly	n.
Vin"e*gar*y	a.
Vin"er	n.
Vin"er*y	n.
Vi*nette"	n.
Vin"ewed	a.
Vine"yard	n.
Vine"yard*ist	n.
Vingt` et` un"	n.
Vin"ic	a.
Vin"i*cul`ture	n.
Vin`i*fi*ca"tion	n.
Vin"newed	a.
Vin"ny	a.
Vin"o*len*cy	n.
Vin"o*lent	a.
Vin*om"e*ter	n.
Vin` or`di`naire"	a.
Vi*nos"i*ty	n.
Vi"nous	a.
Vin"quish	n.
Vint"age	n.
Vint"a*ger	n.
Vint"a*ging	n.
Vint"ner	n.
Vint"ry	n.
Vi"num	n.
Vin"y	a.
Vi"nyl	n.
Vi"ol	n.
Vi"o*la	n.
Vi"o*la	n.
Vi"o*la*ble	a.
Vi`o*la"ceous	a.
Vi`o*lan"i*line	n.
Vi`o*lan"tin	n.
Vi`o*la*quer"cit*rin	n.
Vi`o*las"cent	a.
Vi"o*late	v. t.
Vi`o*la"tion	n.
Vi"o*la*tive	a.
Vi"o*la`tor	n.
Vi"ole	n.
Vi"o*lence	n.
Vi"o*lence	v. t.
Vi"o*lent	a.
Vi"o*lent	n.
Vi"o*lent	v. t.
Vi"o*lent	v. i.
Vi"o*lent*ly	adv.
Vi`o*les"cent	a.
Vi"o*let	n.
Vi"o*let	a.
Vi"o*let-ear`	n.
Vi"o*let-tip"	n.
Vi`o*lin"	n.
Vi"o*line	n.
Vi`o*lin"ist	n.
Vi"ol*ist	n.
Vi`o*lon*cel"list	n.
Vi`o*lon*cel"lo	n.
Vi`o*lo"ne	n.
Vi"o*lous	a.
Vi`o*lu"ric	a.
VI`OXX	prop. n.
vi"per	n.
Vi`per*i"na	n. pl.
Vi"per*ine	a.
Vi"per*ish	a.
Vi"per*oid	a.
Vi`per*oi"de*a	n. pl.
Vi"per*ous	a.
Vi`ra*gin"i*an	a.
Vi`ra*gin"i*ty	n.
Vi*ra"go	n.
Vire	n.
Vir"e*lay	n.
Vi"rent	a.
Vir"e*o	n.
Vi*res"cence	a.
Vir"e*ton	n.
Vir"ga*lieu	n.
Vir"gate	a.
Vir"gate	n.
Vir"ga*ted	a.
Virge	n.
Vir"ger	n.
Vir*gil"i*an	a.
Vir"gin	n.
Vir"gin	a.
Vir"gin	v. i.
Vir"gin*al	a.
Vir"gin*al	n.
Vir"gin*al	v. i.
Vir"gin*hood	n.
Vir*gin"i*a	n.
Vir*gin"i*ty	n.
Vir"go	n.
Vir"gou*leuse	n.
Vir`gu*la"ri*an	n.
Vir"gu*late	a.
Vir"gule	n.
Vir"i*al	n.
Vir"id	a.
Vir`i*des"cence	n.
Vir`i*des"cent	a.
Vir"i*dine	n.
Vir"i*dite	n.
Vi*rid"i*ty	n.
Vir"id*ness	n.
Vi"rile	a.
Vi*ril"i*ty	n.
Vi*rip"o*tent	a.
Vir*mil"ion	n.
Vi*role"	n.
Vi*roled"	a.
Vi*rose"	a.
Vir*tu"	n.
Vir"tu*al	a.
Vir`tu*al"i*ty	n.
Vir"tu*al*ly	adv.
Vir"tu*ate	v. t.
Vir"tue	n.
Vir"tue*less	a.
Vir`tu*os"i*ty	n.
Vir`tu*o"so	n.
Vir`tu*o"so*ship	n.
Vir"tu*ous	a.
Vir"u*lence	n.
Vir"u*lent	a.
Vir"u*lent*ed	a.
Vir"u*lent*ly	adv.
Vi"rus	n.
Vis	n.
Vi"sa	n.
Vi"sa	prop. n.
Vi"sa	v. t.
Vis"age	n.
Vis"age	v. t.
Vis"aged	a.
Vis"ard	n.
Vis"ard	v. t.
Vis`-a-vis"	n.
Vis`-a-vis"	adv.
Vi*sa"yan	n.
Vis*ca"cha	n.
Vis"ce*ra	n.
Vis"cer*al	a.
Vis"cer*ate	v. t.
Vis`cer*o*skel"e*tal	a.
Vis"cid	a.
Vis*cid"i*ty	n.
Vis"cin	n.
Vis*coid"al	a.
Vis`co*sim"e*ter	n.
Vis*cos"i*ty	n.
Vis"count`	n.
Vis"count`cy	n.
Vis"count`ess	n.
Vis"count`ship	n.
Vis"cous	a.
Vis"cum	n.
Vis"cus	n.
Vise	n.
Vi*s<eacute/"	n.
Vi*s<eacute/"	v. t.
Vish"nu	n.
Vis`i*bil"i*ty	n.
Vis"i*ble	a.
Vis"i*ble speech"	n.
Vi"sion	n.
Vi"sion	v. t.
Vi"sion*al	a.
Vi"sion*a*ri*ness	n.
Vi"sion*a*ry	a.
Vi"sion*a*ry	n.
Vi"sioned	a.
Vi"sion*ist	n.
Vi"sion*less	a.
Vis"it	v. t.
Vis"it	v. i.
Vis"it	n.
Vis"it*a*ble	a.
Vis"it*ant	n.
Vis"it*ant	a.
Vis`it*a"tion	n.
Vis`it*a*to"ri*al	a.
Vi*site"	n.
Vis"it*er	n.
Vis"it*ing	a. & vb. n.
Vis"it*or	v. t.
Vis`it*o"ri*al	a.
Vi"sive	a.
Vis ma"jor	n.
Vis"no*my	n.
Vi"son	n.
Vis"or	n.
Vis"ored	a.
Vis"ta	n.
Vis"to	n.
Vis"u*al	a.
Vis"u*al*ize	v. t.
Vis"u*al*ize	v. i.
Vis"u*al*iz`er	n.
Vi*taille	n.
Vi"tal	a.
Vi"tal	n.
Vi*tal"ic	a.
Vi"tal*ism	n.
Vi`tal*ist	n.
Vi`tal*is"tic	a.
Vi*tal"i*ty	n.
Vi`tal*i*za"tion	n.
Vi"tal*ize	v. t.
Vi"tal*ly	adv.
Vi"tals	n. pl.
Vit"a*min	n.
vitamin A	n.
vitamin A1	n.
vitamin A2	n.
vitamin B	n.
vitamin B1	n.
vitamin B12	n.
vitamin B2	n.
vitamin B3	n.
vitamin B5	n.
vitamin B6	n.
vitamin Bc	n.
vitamin B complex	n.
vitamin C	n.
vitamin D	n.
vitamin E	n.
vitamin G	n.
vitamin H	n.
vitamin K	n.
vitamin K1	n.
vitamin K2	n.
vitamin K3	n.
vitamin M	n.
vitamin p	n.
Vi"ta*scope	n.
Vit"el*la*ry	a.
Vit`el*lig"e*nous	a.
Vi*tel"lin	n.
Vi*tel"line	a.
Vi*tel"lo*gene	n.
Vi*tel"lus	n.
Vi"ti*ate	v. t.
Vi`ti*a"tion	n.
Vi*tic"u*lose`	a.
Vit`i*cul"tur*al	a.
Vit"i*cul`ture	n.
Vit`i*cul"tur*ist	n.
Vit`i*li"go	n.
Vit`i*lit"i*gate	v. i.
Vit`i*lit`i*ga"tion	n.
Vi`ti*os"i*ty	n.
Vi"tious	a.
Vi"tis	prop. n.
Vi"to*e	a.
Vit"rage	n.
Vi*trel"la	n.
Vit`re-o-e*lec"tic	a.
Vit"re*ous	a.
Vit"re*ous*ness	n.
Vi*tres"cence	n.
Vi*tres"cent	a.
Vi*tres"ci*ble	a.
Vit"ric	a.
Vit"rics	n.
Vit`ri*fac"tion	n.
Vit`ri*fac"ture	n.
Vit"ri*fi`a*ble	a.
Vi*trif"i*ca*ble	a.
Vit"ri*fi*cate	v. t.
Vit`ri*fi*ca"tion	n.
Vit"ri*fied	a.
Vit"ri*form	a.
Vit"ri*fy	v. t.
Vit"ri*fy	v. t.
Vi*tri"na	n.
Vit"rine	n.
Vit"ri*ol	n.
Vit"ri*ol	v. t.
Vit"ri*o*late	v. t.
Vit"ri*o*late	a.
Vit"ri*o*late	n.
Vit"ri*o*la`ted	a.
Vit`ri*o*la"tion	n.
Vit`ri*ol"ic	a.
Vit"ri*ol*i`za*ble	a.
Vit`ri*ol*i*za"tion	n.
Vit"ri*ol*ize	v. t.
Vi*tri"o*lous	a.
Vit"rite	n.
Vit"ro-di-tri"na	n.
Vi*tru"vi*an	a.
Vit"ta	n.
Vit"tate	a.
Vit"u*line	a.
Vi*tu"per*a*ble	a.
Vi*tu"per*ate	v. t.
Vi*tu`per*a"tion	n.
Vi*tu"per*a*tive	a.
Vi*tu"per*a`tor	n.
Vi`tu*per"ri*ous	a.
Vi"va	interj.
Vi*va"ce	a. & adv.
Vi*va"cious	a.
Vi*vac"i*ty	n.
Vi`van`dier"	n.
Vi`van`di<egrave/re"	n.
Vi`vant"	n.
Vi*va"ri*um	n.
Vi"va*ry	n.
Vi"va vo"ce	n.
Vive	a.
Vive"ly	adv.
Vi"ven*cy	n.
Vi*ver"ra	prop. n.
vi*ver"rine	a.
vi"vers	n. pl.
vives	n.
Viv"i*an*ite	n.
viv"id	a.
vi*vid"i*ty	n.
vi*vif"ic	a.
Vi*vif"i*cate	v. t.
Viv`i*fi*ca"tion	n.
Viv"i*fi*ca*tive	a.
Viv"i*fy	v. t.
Vi*vip"a*ra	n. pl.
Viv`i*par"i*ty	n.
Vi*vip"a*rous	a.
Vi*vip"a*rous*ly	adv.
Vi*vip"a*rous*ness	n.
Viv"i*sect`	v. t.
Viv`i*sec"tion	n.
Viv`i*sec"tion*al	a.
Viv`i*sec"tion*ist	n.
Viv`i*sec"tor	n.
Vix"en	n.
Vix"en*ish	a.
Vix"en*ly	a.
Viz	adv.
Viz"ard	n.
Viz"ard*ed	a.
Viz*ca"cha	n.
Viz"ier	n.
Viz"ier*ate	n.
Vi*zier`-a*zem"	n.
Vi*zier"i*al	a.
Vi*zir"	n.
Viz"or	n.
Vliss*ma"ki	n.
V" moth`	n.
Vo*cab"u*la*ry	n.
. . .	n.
Vo"cal	a.
Vo"cal	n.
Vo*cal"ic	a.
Vo"cal*ism	n.
Vo"cal*ist	n.
Vo*cal"i*ty	n.
Vo`cal*i*za"tion	n.
Vo"cal*ize	v. t.
Vo"cal*ly	adv.
Vo"cal*ness	n.
Vo*ca"tion	n.
Voc"a*tive	a.
Voc"a*tive	n.
Vo*cif"er*ance	n.
Vo*cif"er*ant	a.
Vo*cif"er*ate	v. i.
Vo*cif"er*ate	v. t.
Vo*cif`er*a"tion	n.
Vo*cif"er*a`tor	n.
Vo*cif"er*ous	a.
Voc"ule	n.
Vo*da"ni*um	n.
Vod"ka	n.
Voe	n.
Vo"gle	n.
Vogue	n.
Voice	n.
Voice	v. t.
Voice	v. i.
Voiced	a.
Voice"ful	a.
Voice"less	a.
Void	a.
Void	n.
Void	v. t.
Void	v. i.
Void"a*ble	a.
Void"ance	n.
Void"ed	a.
Void"er	n.
Void"ing	n.
Void"ing	a.
Void"ness	n.
Voir dire	n.
Voi"vode	n.
Vo*la"cious	a.
Vo*la*dor"	n.
Vo*lage"	a.
Vo"lant	a.
Vo*lan"te	n.
Vol`a*p<uum/k"	n.
Vol`a*p<uum/k"ist	n.
Vo"lar	a.
Vol"a*ry	n.
Vol"a*tile	a.
Vol"a*tile	n.
Vol"a*tile*ness	n.
Vol"a*til*i`za*ble	a.
Vol`a*til*i*za"tion	n.
Vol"a*til*ize	v. t.
Vo*la"tor	n.
Vol`-au`-vent"	n.
Vol"borth*ite	n.
Vol*ca"ni*an	a.
Vol*can"ic	a.
Vol*can"ic*al*ly	adv.
Vol`can*ic"i*ty	n.
Vol*can"ic neck	n.
Vol"can*ist	n.
Vol*can"i*ty	n.
Vol`can*i*za"tion	n.
Vol"can*ize	v. t.
Vol*ca"no	n.
Vole	n.
Vole	v. i.
Vole	n.
Vol"er*y	n.
Volge	n.
Vol"i*ta*ble	a.
Vol`i*ta"tion	n.
Vo*li"tient	a.
Vo*li"tion	n.
Vo*li"tion*al	a.
Vol"i*tive	a.
Volks"lied	n.
Volks"raad`	n.
Vol"ley	n.
Vol"ley	v. t.
Vol"ley	v. i.
Vol"ley ball	a.
Vo"lost	n.
Vol"ow	v. t.
Vol"plane`	v. i.
Volt	n.
Volt	n.
Vol"ta	n.
Vol"ta-e*lec"tric	a.
Vol`ta-e`lec*trom"e*ter	n.
Vol"tage	n.
Vol*tag"ra*phy	n.
Vol*ta"ic	a.
Vol*tair"e*an	a.
Vol*tair"ism	n.
Vol"ta*ism	n.
Vol*tam"e*ter	n.
Volt*am"me`ter	n.
Volt amp<egrave/re	n.
Vol"ta*type	n.
Vol"ti	imperative.
Vol`ti*geur	n.
Volt"me`ter	n.
Voltz"ite	n.
Vo*lu"bi*late	a.
Vol`u*bil"i*ty	n.
Vol"u*ble	a.
Vol"ume	n.
Vol"umed	a.
Vol`u*me*nom"e*ter	n.
Vol`u*me*nom"e*try	n.
Vo*lu"me*scope	n.
Vo*lu"me*ter	n.
Vol`u*met"ric	a.
Vol`u*met"ric*al	a.
Vo*lu"mi*nous	a.
Vol"u*mist	n.
Vol"un*ta*ri*ly	adv.
Vol"un*ta*ri*ness	n.
Vol"un*ta*rism	n.
Vol"un*ta*ry	a.
Vol"un*ta*ry	n.
Vol"un*ta*ry*ism	n.
Vol`un*teer"	n.
Vol`un*teer"	a.
Vol`un*teer"	v. t.
Vol`un*teer"	v. i.
Vol`un*teer" na"vy	n.
Vo*lup"tu*a*ry	n.
Vo*lup"tu*a*ry	a.
Vo*lup"tu*ous	a.
Vo*lup"ty	n.
Vo*lu"ta	n.
Vol`u*ta"tion	n.
Vo*lute"	n.
Vo*lut"ed	a.
Vo*lu"tion	n.
Vol"va	n.
Vol"vox	n.
Vol"vu*lus	n.
Vol"yer	n.
Vo"mer	n.
Vo"mer*ine	a.
Vom"i*ca	n.
Vom"i*cine	n.
Vom"ic nut`	v. i.
Vom"it	v. t.
Vom"it	n.
Vom"it*ing	n.
Vo*mi"tion	n.
Vom"i*tive	a.
Vo*mi"to	n.
Vom"i*to*ry	a.
Vom"i*to*ry	n.
Vom`i*tu*ri"tion	n.
Vond*si"ra	n.
Voo"doo	n.
Voo"doo	a.
Voo"doo economics	n.
Voo"doo*ism	n.
Voor"trek`er	n.
Vo*ra"cious	a.
Vo*rac"i*ty	n.
Vo*rag"i*nous	a.
Vor"tex	n.
Vor"tex fil"a*ment	a.
Vor"ti*cel	n.
Vor`ti*cel"la	n.
Vor"ti*cose`	a.
Vor*tig"i*nous	a.
Vo"ta*ress	n.
Vo"ta*rist	n.
Vo"ta*ry	a.
Vo"ta*ry	n.
Vote	n.
Vote	v. i.
Vote	v. t.
Vot"er	n.
Vot"ing	a. & n.
Vot"ist	n.
Vo"tive	a.
Vo"tress	n.
Vouch	v. t.
Vouch	v. i.
Vouch	n.
Vouch*ee"	n.
Vouch"er	n.
Vouch"ment	n.
Vouch"or	n.
Vouch*safe"	v. t.
Vouch*safe"	v. i.
Vouch*safe"ment	n.
Vous`soir"	n.
Vow	n.
Vow	v. t.
Vow	v. i.
Vow"el	n.
Vow"el	a.
Vow"eled	a.
Vow"el*ish	a.
Vow"el*ism	n.
Vow"el*ize	v. t.
Vow"er	n.
Vow"-fel`low	n.
Vox	n.
Vox` an*gel"i*ca	n.
Voy"age	v. i.
Voy"age	v. t.
Voy"age*a*ble	a.
Voy"a*ger	n.
Voy`a`geur"	n.
Voy"ol	n.
Vrai`sem`blance"	n.
Vugg	n.
Vul"can	n.
Vul*ca"ni*an	a.
Vul*can"ic	a.
Vul`can*ic"i*ty	n.
Vul"can*ism	n.
Vul"can*ist	n.
Vul"can*ite	n.
Vul`can*i*za"tion	n.
Vul"can*ize	v. t.
Vul"can*i`zer	n.
Vul*ca"no	n.
Vul`can*ol"o*gy	n.
Vul"can pow"der	a.
Vul"gar	n.
Vul*ga"ri*an	n.
Vul"gar*ism	n.
Vul*gar"i*ty	n.
Vul`gar*i*za"tion	n.
Vul"gar*ize	v. t. & i.
Vul"gar*ly	adv.
Vul"gar*ness	n.
Vul"gate	n.
Vul"gate	a.
Vul`ner*a*bil"i*ty	n.
Vul"ner*a*ble	a.
Vul"ner*a*ble*ness	n.
Vul"ner*a*ry	a.
Vul"ner*ate	v. t.
Vul`ner*a"tion	n.
Vul"ner*ose`	a.
Vul*nif"ic	a.
Vul*nose"	a.
Vul"pes	n.
Vul"pic	a.
Vul"pi*cide	n.
Vul"pine	a.
Vul*pin"ic	a.
Vul"pin*ism	n.
Vul"pi*nite	n.
Vul"tern	n.
Vul"ture	n.
Vul"tur*ine	a.
Vul"tur*ish	a.
Vul"tur*ism	n.
Vul"tur*ous	a.
Vul"va	n.
Vul"vi*form	a.
Vul*vi"tis	n.
Vul`vo-u"ter*ine	a.
Vul`vo*vag"i*nal	a.
Vyce	n.
Vy"ing	a. & n.
