S	n.
Saan	n. pl.
Sab`a*dil"la	n.
Sa*bae"an	a. & n.
Sa*bae"an*ism	n.
Sa"bae*ism	n.
Sa"bal	n.
Sab"a*oth	n. pl.
Sab"bat	n.
Sab`ba*ta"ri*an	n.
Sab`ba*ta"ri*an	a.
Sab`ba*ta"ri*an*ism	n.
Sab"bath	n.
Sab"bath*less	a.
Sab*bat"ic	a.
Sab"ba*tism	n.
Sab"ba*ton	n.
Sa*be"an	a. & n.
Sa"be*ism	n.
Sa*bel"la	n.
Sa*bel"li*an	a.
Sa*bel"li*an	n.
Sa*bel"li*an*ism	n.
Sa*bel"loid	a.
Sa"ber	n.
Sa"ber	v. t.
Sa"ber*bill`	n.
Sa"bi*an	a.
Sa"bi*an	n.
Sa"bi*an*ism	n.
Sab"i*cu	n.
Sa"bine	a.
Sab"ine	n.
Sa"ble	n.
Sa"ble	a.
Sa"ble	v. t.
Sa`bot"	n.
Sa`bo`tage"	n.
Sa`bo"ti<egrave/re	n.
Sa"bre	n. & v.
Sa"bre*tasche`	n.
Sa*bri"na work`	a.
Sab`u*los"i*ty	n.
Sab"u*lous	a.
Sac	n.
Sac	n.
Sac	n.
Sac"a*lait	n.
Sa"car	n.
Sac*cade"	n.
Sac"cate	a.
Sac"cha*rate	n.
Sac*char"ic	a.
Sac`cha*rif"er*ous	a.
Sac*char"i*fy	v. t.
Sac`cha*ril"la	n.
Sac`cha*rim"e*ter	n.
Sac`cha*ri*met"ric*al	a.
Sac`cha*rim"e*try	n.
Sac"cha*rin	n.
Sac"cha*ri*nate	n.
Sac"cha*rine	a.
Sac"cha*rine	n.
Sac"cha*rin"ic	a.
Sac"cha*rize	v. t.
Sac"cha*roid	a.
Sac`cha*rom"e*ter	n.
Sac`cha*ro*my"ces	n.
Sac`cha*ro*my*ce"tes	n. pl.
Sac"cha*ro*nate	n.
Sac"cha*rone	n.
Sac`cha*ron"ic	a.
Sac"cha*rose`	n.
Sac"cha*rous	a.
Sac"cha*rum	n.
Sac`cho*lac"tate	n.
Sac`cho*lac"tic	a.
Sac*chol"ic	a.
Sac*chul"mate	n.
Sac*chul"mic	a.
Sac*chul"min	n.
Sac*cif"er*ous	a.
Sac"ci*form	a.
Sac`co*glos"sa	n. pl.
Sac"cu*lar	a.
Sac"cu*la`ted	a.
Sac"cule	n.
Sac`cu*lo-coch"le*ar	a.
Sac`cu*lo-u*tric"u*lar	a.
Sac"cu*lus	n.
Sac"cus	n.
Sa*cel"lum	n.
Sac`er*do"tal	a.
Sac`er*do"tal*ism	n.
Sac`er*do"tal*ly	adv.
Sach"el	n.
Sa"chem	n.
Sa"chem*dom	n.
Sa"chem*ship	n.
Sa`chet"	n.
Sa*ci"e*ty	n.
Sack	n.
Sack	n.
Sack	v. t.
Sack	n.
Sack	v. t.
Sack"age	n.
Sack"but	n.
Sack"cloth`	n.
Sack"clothed`	a.
Sack"er	n.
Sack"ful	n.
Sack"ful	a.
Sack"ing	n.
Sack"less	a.
Sack"-winged`	a.
Sacque	n.
Sa"cral	a.
Sac"ra*ment	n.
Sac"ra*ment	v. t.
Sac`ra*men"tal	a.
Sac`ra*men"tal	n.
Sac`ra*men"tal*ism	n.
Sac`ra*men"tal*ist	n.
Sac`ra*men"tal*ly	adv.
Sac`ra*men*ta"ri*an	n.
Sac`ra*men*ta"ri*an	a.
Sac`ra*men"ta*ry	a.
Sac`ra*men"ta*ry	n.
Sac"ra*ment*ize	v. i.
Sa*cra"ri*um	n.
Sa"crate	v. t.
Sa*cra"tion	n.
Sa"cre	n.
Sa"cre	v. t.
Sa"cred	a.
Sacrif"ic	a.
Sa*crif"ic*a*ble	a.
Sa*crif"ic*ant	n.
Sac"ri*fi*ca`tor	n.
Sa*crif"ic*a*to*ry	n.
Sac"ri*fice	n.
Sac"ri*fice	v. t.
Sac"ri*fice	v. i.
Sac"ri*fi`cer	n.
Sac`ri*fi"cial	a.
Sac"ri*lege	n.
Sac`ri*le"gious	a.
Sac"ri*le`gist	n.
Sac"ring	a. & n.
Sa"crist	n.
Sac"ris*tan	n.
Sac"ris*ty	n.
Sa"cro-	a.
Sa`cro*sci*at"ic	a.
Sa`cro*ver"te*bral	a.
Sa"crum	n.
Sacs	n. pl.
Sad	a.
Sad	v. t.
SAD	n.
Sad"da	n.
Sad"den	v. t.
Sad"den	v. i.
Sad"der	n.
Sad"dle	n.
Sad"dle	v. t.
Sad"dle*back`	a.
Sad"dle*back`	n.
Sad"dle-backed`	a.
Sad"dle*bags	n. pl.
Sad"dle*bow`	n.
Sad"dle*cloth`	n.
Sad"dled	a.
Sad"dler	n.
Sad"dler*y	n.
Sad"dle-shaped`	a.
Sad"dle*tree`	n.
Sad`du*ca"ic	a.
Sad"du*cee	n.
Sad"du*cee`ism	n.
Sad"du*cize	v. i.
Sadh	n.
Sad"i`ron	n.
Sad"ly	adv.
Sad"ness	n.
Sadr	n.
Saeng"er*bund`	n.
Saeng"er*fest	n.
Safe	a.
Safe	n.
Safe	v. t.
Safe"-con"duct	n.
Safe`-con*duct"	v. t.
Safe"guard`	n.
Safe"guard`	v. t.
Safe"-keep"ing	n.
Safe"ly	adv.
Safe"ness	n.
Safe"-pledge"	n.
Safe"ty	n.
Safety bicycle	v. t.
Saf"flow	n.
Saf"flow`er	n.
Saf"fron	n.
Saf"fron	a.
Saf"fron	v. t.
Saf"fron*y	a.
Saf"ra*nin	n.
Saf"ra*nine	n.
Sag	v. i.
Sag	v. t.
Sag	n.
Sa"ga	n.
Sa*ga"cious	a.
Sa*gac"i*ty	n.
Sag"a*more	n.
Sag"a*pen	n.
Sag`a*pe"num	n.
Sag"a*thy	n.
Sage	n.
Sage	a.
Sage	n.
Sage"brush`	n.
Sagebrush State	adv.
Sa*gene"	n.
Sage"ness	n.
Sag"e*nite	n.
Sag`e*nit"ic	a.
Sag"ger	n.
Sag"ging	n.
Sag"i*nate	v. t.
Sag`i*na"tion	n.
Sa*git"ta	n.
Sag"it*tal	a.
Sag`it*ta"ri*us	n.
Sag"it*ta"ry	n.
Sag"it*ta*ry	a.
Sag"it*tate	a.
Sag"it*ta`ted	a.
Sag"it*to*cyst	n.
Sa"go	n.
Sa*goin"	n.
Sa"gum	n.
Sa"gus	n.
Sa"gy	a.
Sa"hib	n.
Sa"hi*bah	n.
Sa*hid"ic	a.
Sah"lite	n.
Sa*hui"	n.
Sa"i	n.
Sai"bling	n.
Sa"ic	n.
Said	imp. & p. p.
Said	a.
Sai"ga	n.
Sai"kyr	n.
Sail	n.
Sail	v. i.
Sail	v. t.
Sail"a*ble	a.
Sail"boat`	n.
Sail"cloth`	n.
Sail"er	n.
Sail"fish	n.
Sail"ing	n.
Sail"less	a.
Sail"mak`er	n.
Sail"or	n.
Sail"y	a.
Saim	n.
Sai*mir"	n.
Sain	p. p.
Sain	v. t.
Sain"foin	n.
Saint	n.
Saint	v. t.
Saint	v. i.
Saint"dom	n.
Saint"ed	a.
Saint"ess	n.
Saint"hood	n.
Saint"ish	a.
Saint"ism	n.
Saint"like`	a.
Saint"li*ness	n.
Saint"ly	a.
Saint Nicholas	n.
Saint*ol"o*gist	n.
Saint"ship	n.
Saint`-Si*mo"ni*an	n.
Saint`-Si*mo"ni*an*ism	n.
Saint-Si"mon*ism	n.
Saith	3d pers. sing. pres.
Saithe	n.
Sai"va	n.
Sai"vism	n.
Sa*jene"	n.
Sa"jou	n.
Sake	n.
Sa"ke	n.
Sa"ker	n.
Sa"ker*et	n.
Sa"ki	n.
Sa"ki	n.
Sak"i*eh	n.
Sak"ti	n.
Sal	n.
Sal	n.
Sa*laam"	n.
Sa*laam"	v. i.
Sal`a*bil"i*ty	n.
Sal"a*ble	a.
Sa*la"cious	n.
Sa*lac"i*ty	n.
Sal"ad	n.
Sal"ad days`	n. pl.
Sal"ade	n.
Sal"ad*ing	n.
Sal`ae*ra"tus	n.
Sal"a*gane	n.
Sal"al-ber`ry	n.
Sa*lam	n.
Sal"a*man`der	n.
Sal`a*man*dri"na	n.
Sal`a*man"drine	a.
Sal`a*man"droid	a.
Sal`a*man*droi"de*a	n. pl.
Sal"am*stone`	n.
Sa*lan"ga*na	n.
Sal"a*ried	a.
Sal"a*ry	a.
Sal"a*ry	n.
Sal"a*ry	v. t.
Sale	n.
Sale	n.
Sale"a*ble	a.
Sal"eb	n.
Sal`e*bros"i*ty	n.
Sal"e*brous	a.
Sal"ep	n.
Sal`e*ra"tus	n.
Sales"man	n.
Sales" tax	n.
Sales"wom`an	n.
Sale"work`	n.
Sa"lian	a.
Sa"li*ant	a.
Sal"i*aunce	a.
Sal"ic	a.
Sal`i*ca"ceous	a.
Sal"i*cin	n.
Sal"i*cyl	n.
Sal"i*cyl`al	n.
Sal"i*cyl`ate	n.
Sal`i*cyl"ic	a.
Sal"i*cyl`ide	n.
Sal"i*cyl`ite	n.
Sal"i*cyl`ol	n.
Sa*lic"y*lous	a.
Sa"li*ence	n.
Sa"li*en*cy	n.
Sa"li*ent	a.
Sa"li*ent	a.
Sa"li*ent*ly	adv.
Sa*lif"er*ous	a.
Sal"i*fi`a*ble	a.
Sal`i*fi*ca"tion	n.
Sal"i*fy	v. t.
Sa*lig"e*nin	n.
Sal"i*got	n.
Sal*im"e*ter	n.
Sal*im"e*try	n.
Sa*li"na	n.
Sa*li"na pe"ri*od	n.
Sa"line	a.
Sa"line	n.
Sal"ine	n.
Sa*line"ness	n.
Sal`i*nif"er*ous	a.
Sa*lin"i*form	a.
Sa*lin"i*ty	n.
Sal`i*nom"e*ter	n.
Sa*lin"ous	a.
Sal"ique	a.
Sal`i*re"tin	n.
Sal`is*bu"ri*a	n.
Sal"ite	v. t.
Sa"lite	n.
Sa*li"va	n.
Sa*li"val	a.
Sal"i*vant	a.
Sal"i*vant	n.
Sal"i*va*ry	a.
Sal"i*vate	v. t.
Sal`i*va"tion	n.
Sa*li"vous	a.
Sa"lix	n.
Sal"len*ders	n. pl.
Sal"let	n.
Sal"let	n.
Sal"li*ance	n.
Sal"low	n.
Sal"low	a.
Sal"low	v. t.
Sal"low*ish	a.
Sal"low*ness	n.
Sal"ly	v. i.
Sal"ly	n.
Sal"ly Lunn"	n.
Salm	n.
Sal`ma*gun"di	n.
Sal"mi	n.
Sal"mi*ac	n.
Sal`mis"	n.
Salm"on	n.
Salm"on	a.
Sal`mo*nel"la	prop. n.
sal`mo*nel*lo"sis	n.
Salm"on*et	n.
Sal"mon*oid	a.
Sal"o*gen	n.
Sal"ol	n.
sa*lom"e*ter	n.
Sa*lom"e*try	n.
Sa`lon"	n.
Sa*loon"	n.
Sa*loop"	n.
Salp	n.
Sal"pa	n.
Sal"pi*an	n.
Sal"pi*con	n.
Sal`pin*gi"tis	n.
Sal"pinx	n.
Sal"sa*fy	n.
Sal`sa*men*ta"ri*ous	a.
Salse	n.
Sal"si*fy	n.
Sal"so-ac`id	a.
Sal`so"da	n.
Sal"so*la	n.
sal*su"gi*nous	a.
Salt	n.
Salt	a.
Salt	a.
Salt	v. t.
Salt	v. i.
Salt	n.
Sal"tant	a.
Sal`ta*rel"la	n.
Sal`ta*rel"lo	n.
Sal"tate	v. i.
Sal*ta"tion	n.
Sal`ta*to"ri*a	n. pl.
Sal`ta*to"ri*al	a.
Sal`ta*to"ri*ous	a.
Sal"ta*to"ry	a.
Salt"bush`	n.
Salt"cat`	n.
Salt"cel*lar	n.
Salt"er	n.
Salt"ern	n.
Salt"foot`	n.
Salt"-green	a.
Salt"ie	n.
Sal"tier	n.
Sal`ti*gra"dae	n. pl.
Sal"ti*grade	a.
Sal"ti*grade	n.
Sal`tim*ban"co	n.
salt"i*ness	n.
Salt"ing	n.
Sal"tire	n.
Sal"tire*wise`	adv.
Salt"ish	a.
Salt"less	a.
Salt"ly	adv.
Salt"mouth`	n.
Salt"ness	n.
Salt`pe"ter	n.
Salt`pe"trous	a.
Salt" rheum	n.
Salt"y	a.
Sa*lu"bri*ous	a.
Sa*lu"bri*ty	n.
Sa*lue"	v. t.
Sal"u*ta*ry	a.
Sal`u*ta"tion	n.
Sa*lu`ta*to"ri*an	n.
Sa*lu"ta*to*ri*ly	adv.
Sa*lu"ta*to*ry	a.
Sa*lu"ta*to*ry	n.
Sa*lute"	v. t.
Sa*lute"	n.
Sa*lut"er	n.
Sal`u*tif"er*ous	a.
Sal`u*tif"er*ous*ly	adv.
Sal`va*bil"i*ty	n.
Sal"va*ble	a.
Sal"vage	n.
Sal"vage	a. & n.
Sal*va"tion	n.
Sal*va"tion*ist	n.
Sal"va*to*ry	n.
Sal"ve	interj.
Sal"ve	v. t.
Salve	n.
Salve	v. t.
Salve	v. t. & i.
Salv"er	n.
Sal"ver	n.
Sal"ver	n.
Sal"ver-shaped`	a.
Sal"vi*a	n.
Sal*vif"ic	a.
Sal"vo	n.
Sal"vo	n.
Sal"vor	n.
Sam	adv.
SAM	n.
Sa*maj"	n.
Sa*ma"ra	n.
Sam"are	n.
Sa*mar"i*tan	a.
Sa*ma"ri*um	n.
Sam"a*roid	a.
Sa*mar"ra	n.
Sa*mar"skite	a.
Sam"bo	n.
Sam"bo	n.
Sam"boo	n.
Sam*bu"cus	n.
Sam"buke	n.
Sam"bur	n.
Same	a.
Same"li*ness	n.
Same"ness	n.
Sa*mette"	n.
Sa"mi*an	a.
Sa"mi*an	n.
Sa"mi*el	n.
Sa"mi*ot	a. & n.
Sam"i*sen	n.
Sa"mite	a.
Sam"let	n.
Sam"mi*er	n.
Sa*mo"an	a.
Sa"mo*var	n.
Sam`oy*edes"	n. pl.
Samp	n.
Sam"pan	n.
Sam"phire	n.
Sam"ple	n.
Sam"ple	v. t.
Sam"pler	n.
Sam"shoo	n.
Sam"son	n.
Sa"mu*rai`	n. pl. & sing.
San`a*bil"i*ty	n.
San"a*ble	a.
San"a*ble*ness	n.
Sa*na"tion	n.
San"a*tive	a.
San`a*to"ri*um	n.
San"a*to*ry	a.
San`be*ni"to	n.
Sance"-bell`	n.
San"cho	n.
Sancho pedro	v. t.
Sanc`ti*fi*ca"tion	n.
Sanc"ti*fied	a.
Sanc"ti*fi`er	n.
Sanc"ti*fy	v. t.
Sanc"ti*fy`ing*ly	adv.
Sanc*til"o*quent	a.
Sanc`ti*mo"ni*al	a.
Sanc`ti*mo"ni*ous	a.
Sanc"ti*mo*ny	n.
Sanc"tion	n.
Sanc"tion	v. t.
Sanc"tion*a*ry	a.
Sanc"ti*tude	n.
Sanc"ti*ty	n.
Sanc"tu*a*rize	v. t.
Sanc"tu*a*ry	n.
Sanc"tum	n.
Sanc"tus	n.
Sand	n.
Sand	v. t.
San"dal	n.
San"dal	n.
San"dal	n.
San"daled	a.
San*dal"i*form	a.
San"dal*wood	n.
San"da*rach	n.
sand"bag`	n.
sand"bag`	v.
Sand"bag`ger	n.
Sand"-blind`	a.
Sand"ed	a.
San`de*ma"ni*an	n.
San`de*ma"ni*an*ism	n.
San"der*ling	n.
San"ders	n.
San"ders-blue"	n.
San"de*ver	n.
Sand"fish`	n.
Sand"glass`	n.
Sand"hill`er	n.
Sand"i*ness	n.
Sand"ish	a.
San"di*ver	n.
San"dix	n.
sand"lot	a.
sand"lot	n.
Sand"man`	n.
Sand"neck`er	n.
Sand"pa`per	n.
Sand"pa`per	v. t.
Sand"pi`per	n.
Sand"pit`	n.
San"dre	n.
Sand"stone`	n.
Sand"wich	n.
Sand"wich	v. t.
Sand"worm`	n.
Sand"wort`	n.
Sand"y	a.
San"dyx	n.
Sane	a.
Sane"ness	n.
Sang	imp.
San"ga	n.
San`ga*ree"	n.
Sang`-froid"	n.
San"gi*ac	n.
San`graal"	n.
San*guif"er*ous	a.
San`gui*fi*ca"tion	n.
San"gui*fi`er	n.
San*guif"lu*ous	a.
San"gui*fy	v. t.
San*guig"e*nous	a.
San`gui*na"ceous	n.
San`gui*na"ri*a	n.
San"gui*na*ri*ly	adv.
San"gui*na*ri*ness	n.
San"gui*na*ry	a.
San"gui*na*ry	n.
San"guine	a.
San"guine	n.
San"guine	v. t.
San"guine*less	a.
San"guine*ly	adv.
San"guine*ness	n.
San*guin"e*ous	a.
san*guin"i*ty	n.
San"gui*niv"o*rous	a.
San*guin"o*len*cy	n.
San*guin"o*lent	a.
San"gui*suge	n.
San*guiv"o*rous	a.
San"he*drin	n.
San"he*drist	n.
San"hi*ta	n.
San"i*cle	n.
San"i*dine	n.
Sa"ni*es	n.
Sa"ni*ous	a.
San`i*ta"ri*an	a.
San`i*ta"ri*an	n.
San"i*ta*rist	n.
San`i*ta"ri*um	n.
San"i*ta*ry	a.
San`i*ta"tion	n.
San"i*ty	n.
San"jak	n.
San Jo*s<eacute/" scale	imp.
Sank"ha	n.
Sankh"ya	n.
San"nop	n.
San"nup	n.
San"ny	n.
Sans	prep.
San"scrit	n.
Sans`-cu`lotte"	n.
Sans`-cu*lot"tic	a.
Sans`-cu*lot"tism	n.
San"skrit	n.
San"skrit	a.
San*skrit"ic	a.
San"skrit*ist	n.
Sans`-sou`ci"	adv.
San"tal	n.
San`ta*la"ceous	a.
San*tal"ic	a.
San"ta*lin	n.
San"ta*lum	n.
San`tees"	n. pl.
San"ter	v. i.
San"ton	n.
San"to*nate	n.
San*ton"ic	a.
San"to*nin	n.
San"to*nin`ate	n.
San`to*nin"ic	a.
Sa"o	n.
Sap	n.
Sap	v. t.
Sap	v. i.
Sap	n.
Sap`a*dil"lo	n.
Sap"a*jo	n.
Sap"a*jou	n.
Sa*pan" wood	a.
Sap"head`	n.
Sa*phe"nous	a.
Sap"id	a.
Sa*pid"i*ty	n.
Sap"id*ness	n.
Sa"pi*ence	n.
Sa"pi*ent	a.
Sa`pi*en"tial	a.
Sa`pi*en"tious	a.
Sa"pi*ent*ize	v. t.
Sa"pi*ent*ly	adv.
Sap`in*da"ceous	a.
Sa*pin"dus	n.
Sap"less	a.
sap"ling	n.
Sap`o*dil"la	n.
Sa*pog"e*nin	n.
Sap`o*na"ceous	a.
Sap`o*nac"i*ty	n.
Sap"o*na*ry	a.
Sa*pon*i*fi`a*ble	a.
Sa*pon`i*fi*ca"tion	n.
Sa*pon"i*fi`er	n.
Sa*pon"i*fy	v. t.
Sap"o*nin	n.
Sap"o*nite	n.
Sap"o*nul	n.
Sa"por	n.
Sap`o*rif"ic	a.
Sap`o*ros"i*ty	n.
Sap"o*rous	a.
Sa*po"ta	n.
Sap`o*ta"ceous	a.
Sap*pan" wood"	n.
Sap"per	n.
Sap"phic	a.
Sap"phic	n.
Sap"phire	n.
Sap"phire	a.
Sap"phir*ine	n.
Sap"pho	n.
Sap"pi*ness	n.
Sap`po*dil"la	n.
Sap"py	a.
Sap"py	a.
Sa*proph"a*gan	n.
Sa*proph"a*gous	a.
Sap"ro*phyte	n.
Sap`ro*phyt"ic	a.
Sap"ro*phyt*ism	n.
Sap"sa*go	n.
Sap"skull`	n.
Sap`u*ca"ia	n.
Sap"wood`	n.
Sar"a*ba*ite	n.
Sar"a*band	n.
Sar"a*cen	n.
Sar`a*cen"ic	a.
Sar"a*sin	n.
Sa`ras*wa"ti	n.
Sar"casm	n.
Sar*cas"mous	a.
Sar*cas"tic	a.
Sar*cas"tic*al*ly	adv.
Sar"cel	n.
Sar"celed	a.
Sar`celle"	n.
Sarce"net	n.
Sar"cin	n.
Sar*ci"na	n.
Sar"cle	v. t.
Sar"co-	n.
Sar"co*blast	n.
Sar"co*carp	n.
Sar"co*cele	n.
Sar"co*col	n.
Sar"code	n.
Sar"co*derm	n.
Sar*cod"ic	a.
Sar"coid	a.
Sar`co*lac"tic	a.
Sar`co*lem"ma	n.
Sar"co*line	a.
Sar`co*log"ic	a.
Sar*col"o*gy	n.
Sar*co"ma	n.
Sar*com"a*tous	a.
Sar*coph"a*ga	n. pl.
Sar*coph"a*ga	n.
Sar*coph"a*gan	n.
Sar*coph"a*gous	a.
Sar*coph"a*gus	n.
Sar*coph"a*gy	n.
Sar"co*phile	n.
Sar*cop"tes	n.
Sar*cop"tid	n.
Sar`co*rham"phi	n. pl.
Sar`co*sep"tum	n.
Sar"co*sin	n.
Sar*co"sis	n.
Sar*cot"ic	a.
Sar"cous	a.
Sar`cu*la"tion	n.
Sard	n.
Sar"da*chate	n.
Sar"dan	n.
Sar"del	n.
Sar"dine	n.
Sar"dine	n.
Sar*din"i*an	a.
Sar"di*us	n.
Sar"doin	n.
Sar*do"ni*an	a.
Sar*don"ic	a.
Sar*don"ic	a.
Sar"do*nyx	n.
Sa"ree	n.
Sar*gas"so	n.
Sar*gas"sum	n.
Sar"go	n.
Sa"ri	n.
Sa*rigue"	n.
Sark	n.
Sark	v. t.
Sar"kin	n.
Sark"ing	n.
Sar"lac	n.
Sar*ma"tian	a.
Sar"ment	n.
Sar`men*ta"ceous	a.
Sar`men*tose"	a.
Sar*men"tous	a.
Sarn	n.
Sa"rong	n.
Sa"ros	n.
Sar"plar	n.
Sar"plier	n.
Sar"po	n.
Sar`ra*ce"ni*a	prop. n.
Sar"ra*sin	n.
Sar"sa	n.
Sar`sa*pa*ril"la	n.
Sar`sa*pa*ril"lin	n.
Sarse	n.
Sarse	v. t.
Sar"sen	n.
Sarse"net	n.
Sart	n.
Sar*to"ri*al	a.
Sar*to"ri*us	n.
Sa"rum use`	n.
Sash	v. t.
Sash	n.
Sash	v. t.
Sash"er*y	n.
Sash"oon	n.
Sa"sin	n.
Sas"sa*by	n.
Sas"sa*fras	n.
Sas"sa*nage	n.
Sas`sa*ra"ra	n.
Sasse	n.
Sas"sen*ach	n.
Sas"so*lin	n.
Sas"so*rol	n.
Sas"sy bark`	n.
Sas*tru"gi	imp.
Sa"tan	n.
Sa*tan"ic	a.
Sa"tan*ism	n.
Sa"tan*ist	n.
Sa`tan*oph"a*ny	n.
Satch"el	n.
Sate	v. t.
Sate	imp.
Sat*een"	n.
Sate"less	a.
Sat"el*lite	n.
Sat"el*lite	a.
Sat`el*li"tious	a.
Sath"an*as	n.
Sa"ti*ate	a.
Sa"ti*ate	v. t.
Sa`ti*a"tion	n.
Sa*ti"e*ty	n.
Sat"in	n.
Sat`i*net"	n.
Sat`i*nette"	n.
Sat"in weave	n.
Sat"in*y	a.
Sa"tion	n.
Sat"ire	n.
Sa*tir"ic	a.
Sat"ir*ist	n.
Sat"ir*ize	v. t.
Sat`is*fac"tion	n.
Sat`is*fac"tive	a.
Sat`is*fac"to*ry	a.
Sat"is*fi`a*ble	a.
Sat"is*fi`er	n.
Sat"is*fy	v. t.
Sat"is*fy	v. i.
Sat"is*fy`ing*ly	adv.
Sa"tive	a.
Sa"tle	v. t. & i.
Sa"trap	n.
Sa"trap*al	a.
Sa"trap*ess	n.
Sa*trap"ic*al	a.
Sa"trap*y	n.
Sat"su*ma ware"	a.
Sat"u*rant	a.
Sat"u*rant	n.
Sat"u*rate	v. t.
Sat"u*rate	p. a.
Sat"u*ra`ted	a.
Sat`u*ra"tion	n.
Sat"u*ra`tor	n.
Sat"ur*day	n.
Sa*tu"ri*ty	n.
Sa"turn	n.
Sat`ur*na"li*a	n. pl.
Sat`ur*na"li*an	a.
Sa*tur"ni*an	a.
Sa*tur"ni*an	n.
Sat`urn*i*cen"tric	a.
Sat"ur*nine	a.
Sat"ur*nism	n.
Sat"ur*nist	n.
Sa"tyr	n.
Sat`y*ri"a*sis	n.
Sa*tyr"ic	a.
Sa*tyr"i*on	n.
Sau"ba ant`	n.
Sauce	v. t.
Sauce	n.
Sauce"-a*lone`	n.
Sauce"box`	n.
Sauce"pan`	n.
Sau"cer	n.
Sau"ci*ly	adv.
Sau"ci*ness	n.
Sau`cis`son"	n.
Sau"cy	a.
Sauer"kraut`	n.
Sauf	a.
Sauf	conj. & prep.
Sauf"ly	adv.
Sau"ger	n.
Saugh	imp. sing.
Sauks	n. pl.
Saul	n.
Saul	n.
Sau"lie	n.
Sault	n.
Saun"ders	n.
Saun"ders-blue`	n.
Saun"ter	v. i.
Saun"ter	n.
Saun"ter*er	n.
Saur	n.
Sau"rel	n.
Sau"ri*a	n. pl.
Sau"ri*an	a.
Sau"ri*oid	a.
Sau"ro*ba*tra"chi*a	n. pl.
Sau*rog"na*thous	a.
Sau"roid	a.
Sau`roid*ich"nite	n.
Sau*rop"o*da	n. pl.
Sau*rop"si*da	n. pl.
Sau*rop`te*ryg"i*a	n. pl.
Sau*ru"rae	n. pl.
Sau"ry	n.
Sau"sage	n.
Sau"se*flem	a.
Saus"sur*ite	n.
Saut	n.
Sau`te"	p. p.
Sau`ter"	v. t.
Sau"ter	n.
Sau`te*relle	n.
Sau`terne"	n.
Sau"trie	n.
Sau`ve*garde"	n.
Sav"a*ble	a.
Sav"a*ble*ness	n.
Sa*va"ci*oun`	n.
Sav"age	a.
Sav"age	n.
Sav"age	v. t.
Sav"age*ly	adv.
Sav"age*ness	n.
Sav"age*ry	n.
Sav"a*gism	n.
Sav`a*nil"la	n.
Sa*van"na	n.
Sa`vant"	n.
Save	n.
Save	v. t.
Save	v. i.
Save	prep. <or/ conj.
Save	conj.
Save"a*ble	a.
Save"-all`	n.
Sav"e*loy	n.
Save"ly	adv.
Save"ment	n.
Sav"er	n.
Sav"in	n.
Sav"ing	a.
Sav"ing	prep. <or/ conj.
Sav"ing	n.
Sav"ing*ly	adv.
Sav"ing*ness	n.
Sav"ior	n.
Sav"ior*ess	n.
Sa"vor	n.
Sa"vor	v. i.
Sa"vor	v. t.
Sa"vor*i*ly	adv.
Sa"vor*i*ness	n.
Sa"vor*less	a.
Sa"vor*ly	a.
Sa"vor*ly	adv.
Sa"vor*ous	a.
Sa"vor*y	a.
Sa"vo*ry	n.
Sa*voy"	n.
Sav`oy*ard"	n.
Sav"vy	v. t. & i.
Sav"vy	n.
Saw	imp.
Saw	n.
Saw	n.
Saw	v. t.
Saw	v. i.
Sa*war"ra nut`	n.
Saw"bill`	n.
Saw"bones`	n.
Saw"buck`	n.
Saw"ce*flem	a.
Saw"der	n.
Saw"dust`	n.
Saw"er`	n.
Saw"fish`	n.
Saw"fly`	n.
Saw"horse`	n.
Saw"mill`	n.
Saw"neb`	n.
Saw" pal*met"to	n.
Saw"tooth`	n.
Saw"-toothed"	a.
Saw"try	n.
Saw"-whet`	n.
Saw"-wort`	n.
Saw"-wrest`	n.
Saw"yer	n.
Sax	n.
Sax"a*tile	a.
Sax"horn`	n.
Sax`i*ca"va	n.
Sax`i*ca"vid	a.
Sax`i*ca"vous	a.
Sax*ic"o*line	a.
Sax*ic"o*lous	a.
Sax*if"ra*ga	n.
Sax`i*fra*ga"ceous	a.
Sax*if"ra*gant	a.
Sax"i*frage	n.
Sax*if"ra*gous	a.
Sax"on	n.
Sax"on	a.
Sax*on"ic	a.
Sax"on*ism	n.
Sax"on*ist	n.
Sax"on*ite	n.
Sax"o*ny	n.
Saxony yarn	n.
Sax"-tu`ba	n.
Say	imp.
Say	n.
Say	v. t.
Say	n.
Say	v. t.
Say	v. i.
Say	n.
Say"er	n.
Sa*yette"	n.
Say"ing	n.
Say"man	n.
Say"mas`ter	n.
Saynd	p. p.
'Sblood	interj.
Scab	n.
Scab	v. i.
Scab"bard	n.
Scab"bard	v. t.
Scab"bard plane`	a.
Scab"bed*ness	n.
Scab"bi*ly	adv.
Scab"bi*ness	n.
Scab"ble	v. t.
Scab"by	a.
Sca"bi*es	n.
Sca"bi*ous	a.
Sca"bi*ous	n.
Scab"ling	n.
Sca*bred"i*ty	n.
Sca"brous	a.
Sca"brous*ness	n.
Scab"wort`	n.
Scad	n.
Scaf"fold	n.
Scaf"fold	v. t.
Scaf"fold*age	n.
Scaf"fold*ing	n.
Scagl"ia	n.
Scagl*io"la	n.
Sca"la	n.
Scal"a*ble	a.
Sca*lade"	n.
Sca"lar	n.
Sca*la"ri*a	n.
Sca*lar"i*form	a.
Sca"la*ry	a.
Scal"a*wag	n.
Scald	v. t.
Scald	n.
Scald	a.
Scald	n.
Scald	n.
Scald"er	n.
Scald"fish`	n.
Scald"ic	a.
Scale	n.
Scale	v. t.
Scale	n.
Scale	v. t.
Scale	v. i.
Scale	n.
Scale	v. t.
Scale	v. i.
Scale"back`	n.
Scale"beam`	n.
Scale"board`	n.
Scaled	a.
Scale"less	a.
Sca*lene"	a.
Sca*lene"	n.
Sca*le`no*he"dral	a.
Sca*le`no*he"dron	n.
Scal"er	n.
Scale"-winged`	a.
Scal"i*ness	n.
Scal"ing	a.
Scal*io"la	n.
Scall	n.
Scall	a.
Scalled	a.
Scal"lion	n.
Scal"lop	n.
Scal"lop	v. t.
Scal"loped	a.
Scal"lop*er	n.
Scal"lop*ing	n.
Scalp	n.
Scalp	n.
Scalp	v. t.
Scalp	v. i.
Scal"pel	n.
Scalper	n.
Scalp"ing	a. & n.
Scal"pri*form	a.
Scal"y	a.
Scal"y-winged`	a.
Scam"ble	v. i.
Scam"ble	v. t.
Scam"bler	n.
Scam"bling*ly	adv.
Scam"ell	n.
Sca*mil"lus	n.
Scam*mo"ni*ate	a.
Scam"mo*ny	n.
Scamp	n.
Scamp	v. t.
Scam`pa*vi"a	n.
Scam"per	v. i.
Scam"per	n.
Scam"per*er	n.
Scamp"ish	a.
Scan	v. t.
Scan"dal	n.
Scan"dal	v. t.
Scan"dal*ize	v. t.
Scan"dal*ous	a.
Scan"dal*ous*ly	adv.
Scan"dal*ous*ness	n.
Scan"da*lum mag*na"tum`	a.
Scan"di*a	n.
Scan"dic	a.
Scan`di*na"vi*an	a.
Scan"di*um	n.
Scan"sion	n.
Scan*so"res	n. pl.
Scan*so"ri*al	a.
Scant	a.
Scant	v. t.
Scant	v. i.
Scant	adv.
Scant	n.
Scant"i*ly	adv.
Scant"i*ness	n.
Scan"tle	v. i.
Scan"tle	v. t.
Scant"let	n.
Scant"ling	a.
Scant"ling	n.
Scant"ly	adv.
Scant"ness	n.
Scant"y	a.
Scape	n.
Scape	v. t. & i.
Scape	n.
Scape"gal`lows	n.
Scape"goat`	n.
Scape"grace`	n.
Scape"less	a.
Scape"ment	n.
Scape"-wheel`	n.
Sca*phan"der	n.
Scaph"ism	n.
Scaph"ite	n.
Scaph`o*ce*phal"ic	a.
Scaph`o*ceph"a*ly	n.
Scaph`o*ce"rite	n.
Sca*phog"na*thite	n.
Scaph"oid	a.
Scaph`o*lu"nar	a.
Sca*phop"o*da	n. pl.
Sca"pi*form	a.
Scap"o*lite	n.
Scap"ple	v. t.
Scap"u*la	n.
Scap"u*lar	a.
Scap"u*lar	n.
Scap"u*lar	n.
Scap"u*la*ry	a.
Scap"u*la*ry	n.
Scap"u*let	n.
Scap"u*lo-	n.
Scar	n.
Scar	v. t.
Scar	v. i.
Scar	n.
Scar	n.
Scar"ab	n.
Scar`a*bae"us	n.
Scar"a*boid	a.
Scar"a*boid	n.
Scar"a*mouch`	n.
Scarce	a.
Scarce	adv.
Scarce"ment	n.
Scarce"ness	n.
Scard	n.
Scare	v. t.
Scare	n.
Scare"crow`	n.
Scare"fire`	n.
Scarf	n.
Scarf	n.
Scarf	v. t.
Scarf	v. t.
Scarf	n.
Scarf"skin`	n.
Scar`i*fi*ca"tion	n.
Scar"i*fi*ca`tor	n.
Scar"i*fi`er	n.
Scar"i*fy	v. t.
Sca"ri*ose	a.
Scar`la*ti"na	n.
Scar"less	a.
Scar"let	n.
Scar"let	a.
Scar"let	v. t.
Scar"mage	n.
Scarn	n.
Sca"roid	a.
Scarp	n.
Scarp	n.
Scarp	v. t.
Scar"ring	n.
Scar"ry	a.
Scar"ry	a.
Sca"rus	n.
Sca"ry	n.
Scar"y	a.
Scase"ly	adv.
Scat	interj.
Scat	n.
Scat	n.
Scatch	n.
Scatch"es	n. pl.
Scate	n.
Scat"e*brous	a.
Scath	n.
Scathe	v. t.
Scath"ful	a.
Scath"less	a.
Scath"ly	a.
Scat"ter	v. t.
Scat"ter	v. i.
Scat"ter-brain`	n.
Scat"ter-brained`	a.
Scat"tered	a.
Scat"ter*good`	n.
Scat"ter*ing	a.
Scat"ter*ing	n.
Scat"ter*ing*ly	adv.
Scat"ter*ling	n.
Sca*tu"ri*ent	a.
Scat`u*rig"i*nous	a.
Scaup	n.
Scaup"er	n.
Scaur	n.
Scav"age	n.
Scav"enge	v. t.
Scav"enge	v. i.
Scav"en*ger	n.
Scav"en*ger hunt	n.
Scav"eng*ing	p. pr. & vb. n.
Sca"zon	n.
Scel"er*at	n.
Sce*les"tic	a.
Scel"et	n.
Sce"na	n.
Sce*na"ri*o	n.
Scen"a*ry	n.
Scene	n.
Scene	v. t.
Scene"ful	a.
Scene"man	n.
Scen"er*y	n.
Scene"shift`er	n.
Scen"ic	a.
Scen"o*graph	n.
Scen`o*graph"ic	a.
Sce*nog"ra*phy	n.
Scent	v. t.
Scent	v. i.
Scent	n.
Scent"ful	a.
Scent"ing*ly	adv.
Scent"less	a.
Scep"sis	n.
Scep"ter	n.
Scep"ter	v. t.
Scep`ter*el"late	a.
Scep"ter*less	a.
Scep"tic	a.
Scern	v. t.
Schade	n.
Schah	n.
Schap"pe	n.
Schat"chen	n.
Sche"di*asm	n.
Sched"ule	n.
Sched"ule	v. t.
Scheele's" green`	n.
Scheel"ite	n.
Schee"li*um	n.
Scheik	n.
Schel"ly	n.
Sche"ma	n.
Sche*mat"ic	a.
Sche"ma*tism	n.
Sche"ma*tist	n.
Sche"ma*tize	v. i.
Scheme	n.
Scheme	v. t.
Scheme	v. i.
Scheme"ful	a.
Schem"er	n.
Schem"ing	a.
Schem"ist	n.
Schene	n.
Schenk"beer`	n.
Scher"bet	n.
Scher"if	n.
Scher*zan"do	adv.
Scher"zo	n.
Sche"sis	n.
Schet"ic	a.
Schie*dam"	n.
Schil"ler	n.
Schil`ler*i*za"tion	n.
Schil"ling	n.
Schin`dy*le"sis	n.
Schir"rhus	n.
Schism	n.
Schis"ma	n.
Schis*mat"ic	a.
Schis*mat"ic	n.
Schis*mat"ic*al	a.
Schis"ma*tize	v. i.
Schism"less	a.
Schist	n.
Schis*ta"ceous	a.
Schist"ic	a.
Schis*tose"	a.
Schis*tos"i*ty	n.
Schiz"o-	n.
Schiz"o*coele	n.
Schiz`o*coe"lous	a.
Schiz`o*gen"e*sis	n.
Schiz"og*nath	n.
Schi*zog"na*thae	n. pl.
Schi*zog"na*thism	n.
Schi*zog"na*thous	a.
Schiz`o*my*ce"tes	n. pl.
Schiz`o*ne*mer"te*a	n. pl.
Schi"zont	n.
Schiz`o*pel"mous	a.
Schiz"o*phyte	n.
Schiz"o*pod	n.
Schiz"o*pod	a.
Schi*zop"o*da	n. pl.
Schiz`o*rhi"nal	a.
Schlich	n.
Schmel"ze	n.
Schnapps	n.
Schnei*de"ri*an	a.
Schnor"rer	n.
Scho*har"ie grit`	n.
Scho*lar"i*ty	n.
Schol"ar*like`	a.
Schol"ar*ly	a.
Schol"ar*ship	n.
Scho*las"tic	a.
Scho*las"tic	n.
Scho*las"tic*al	a. & n.
Scho*las"tic*al*ly	adv.
Scho*las"ti*cism	n.
Scho"li*a	n. pl.
Scho"li*ast	n.
Scho`li*as"tic	a.
Scho"li*aze	v. i.
Schol"ic*al	a.
Scho"li*on	n.
Scho"li*um	n.
Scho"ly	n.
Scho"ly	v. i. & t.
School	n.
School	n.
School	v. t.
School"book`	n.
School"boy`	n.
School"dame`	n.
School"er*y	n.
School"fel`low	n.
School"girl`	n.
School"house`	n.
School"ing	n.
School"ing	a.
School"ma'am	n.
School"maid`	n.
School"man`	n.
School"mas`ter	n.
School"mate`	n.
School"mis`tress	n.
School"room`	n.
School"ship`	n.
School"-teach`er	n.
School"ward	adv.
Schoon"er	n.
Schoon"er	n.
Schorl	n.
Schor*la"ceous	a.
Schorl"ous	a.
Schorl"y	a.
Schot"tish	n.
Schrei"bers*ite	n.
Schrode	n.
Schwann's" sheath`	n.
Schweit"zer*k<aum/"se	n.
Schwenk"feld`er	n.
Sci*ae"noid	a.
Sci"a*graph	n.
Sci`a*graph"ic*al	a.
Sci*ag"ra*phy	n.
Sci*am"a*chy	n.
Sci`a*ther"ic	a.
Sci*at"ic	a.
Sci*at"ic	n.
Sci*at"i*ca	n.
Sci*at"ic*al	a.
Sci*at"ic*al*ly	adv.
Scib"bo*leth	n.
Sci"ence	n.
Sci"ence	v. t.
sci"ence fic"tion	n.
Sci"ent	a.
Sci*en"ter	adv.
Sci*en"tial	a.
Sci`en*tif"ic	a.
Sci`en*tif"ic*al	a.
Sci`en*tif"ic*al*ly	adv.
Sci"en*tist	n.
Sci"-Fi"	n.
Scil"i*cet	adv.
Scil"la*in	n.
Scil"li*tin	n.
Scim"i*ter	n.
Scin"coid	a.
Scin*coi"de*a	n. pl.
Scin*coid"i*an	n.
Scin"iph	n.
Scink	n.
Scink	n.
Scin*til"la	n.
Scin"til*lant	a.
Scin"til*late	v. i.
Scin`til*la"tion	n.
Scin"til*lous	a.
Scin"til*lous*ly	adv.
Sci*og"ra*phy	n.
Sci"o*lism	n.
Sci"o*list	n.
Sci`o*lis"tic	a.
Sci"o*lous	a.
Sci*om"a*chy	n.
Sci"o*man`cy	n.
Sci"on	n.
Sci*op"tic	a.
Sci*op"ti*con	n.
Sci*op"tics	n.
Sci*op"tric	a.
Sci"ot	a.
Sci`o*ther"ic	a.
Sci"ous	a.
Sci`re fa"ci*as	a.
Scir*rhos"i*ty	n.
Scir"rhous	a.
Scir"rhus	n.
Scis`ci*ta"tion	n.
Scise	v. i.
Scis"sel	n.
Scis"si*ble	a.
Scis"sil	n.
Scis"sile	a.
Scis"sion	n.
Scis`si*par"i*ty	n.
Scis"sor	v. t.
Scis"sors	n. pl.
Scis"sors*bill`	n.
Scis"sors*tail`	n.
Scis"sors-tailed`	a.
Scis"sure	n.
Scit`a*min"e*ous	a.
Sci"u*rine	a.
Sci"u*roid	a.
Sci`u*ro*mor"pha	n. pl.
Sci*u"rus	n.
Sclaff	v. i.
Sclaff	v. t.
Sclaff	n.
Sclaun"dre	n.
Sclav	n.
Sclav"ic	a.
Sclav"ism	n.
Scla*vo"nian	a. & n.
Scla*von"ic	a.
Sclen"der	a.
Scler"a*go`gy	n.
Scle*re"ma	n.
Scle*ren"chy*ma	n.
Scler`en*chym"a*tous	a.
Scle*ren"chyme	n.
Scle*ri"a*sis	n.
Scle"rite	n.
Scle*ri"tis	n.
Scler"o*base	n.
Scler"o*derm	n.
Scler`o*der"ma	n.
Scler`o*der"ma*ta	n. pl.
Scler`o*der"mic	n.
Scler"o*gen	n.
Scle*rog"e*nous	a.
Scle"roid	a.
Scle*ro"ma	n.
Scle*rom"e*ter	n.
Scle*rosed"	a.
Scle*ro"sis	n.
Scle`ro*skel"e*ton	n.
Scle*ro"tal	a.
Scle*rot"ic	a.
Scle*rot"ic	n.
Scle*rot"ic	a.
Scle*rot"ic*al	a.
Scler`o*ti"tis	n.
Scle*ro"ti*um	n.
Scler"o*tome	n.
Scle"rous	a.
Scoat	v. t.
Scob"by	n.
Scob"i*form	a.
Scobs	n. sing. & pl.
Scoff	n.
Scoff	v. i.
Scoff	v. t.
Scoff"er	n.
Scoff"er*y	n.
Scoff"ing*ly	adv.
Scoke	n.
Sco*lay"	v. i.
Scold	v. i.
Scold	v. t.
Scold	n.
Scold"er	n.
Scold"ing	a. & n.
Scold"ing*ly	adv.
Scole	n.
Sco*le"ci*da	n. pl.
Scol"e*cite	n.
Sco*le`co*mor"pha	n. pl.
Sco"lex	n.
Sco*ley"	v. i.
Sco`li*o"sis	n.
Scol"i*thus	n.
Scol"lop	n. & v.
Scol`o*pa"cine	a.
Scol`o*pen"dra	n.
Scol`o*pen"drine	a.
Scol"y*tid	n.
Scom"ber	n.
Scom"ber*oid	a. & n.
Scom`bri*for"mes	n. pl.
Scom"broid	a.
Scom"fish	v. t. & i.
Scom"fit	n. & v.
Scomm	n.
Sconce	n.
Sconce	v. t.
Scon"cheon	n.
Scone	n.
Scoop	n.
Scoop	v. t.
Scoop	v. t.
Scoop"er	n.
Scoot	v. i.
Sco"pa*rin	n.
Sco"pate	a.
-scope	n.
Sco"pe*line	a.
Sco"pe*loid	a.
Sco*pif"er*ous	a.
Sco"pi*form	a.
Sco"pi*ped	n.
Scop"pet	v. t.
Scops" owl`	a.
Scop"u*la	n.
Scop"u*li*ped	n.
Scop"u*lous	a.
Scor"bute	n.
Scor*bu"tic	a.
Scor*bu"tus	n.
Scorce	n.
Scorch	v. t.
Scorch	v. i.
scorch"er	a.
Score	n.
Score	v. t.
Score	v. i.
Scor"er	n.
Sco"ri*a	n.
Sco"ri*ac	a.
Sco`ri*a"ceous	a.
Sco"rie	n.
Sco`ri*fi*ca"tion	n.
Sco"ri*fi`er	n.
Sco"ri*form	a.
Sco"ri*fy	v. t.
Sco"ri*ous	a.
Scorn	n.
Scorn	v. t.
Scorn	v. i.
Scorn"er	n.
Scorn"ful	a.
Scorn"y	a.
Scor"o*dite	n.
Scor*pae"noid	a.
Scor"pene	n.
Scor"per	n.
Scor"pi*o	n.
Scor`pi*o"de*a	n. pl.
Scor"pi*oid	a.
Scor"pi*on	n.
Scor`pi*o"nes	n. pl.
Scor`pi*o*nid"e*a	n. pl.
Scor"pi*on*wort`	n.
Scorse	n.
Scorse	v. t.
Scorse	v. i.
Scor"ta*to*ry	a.
Scot	n.
Scot	n.
Scot	n.
Scot"al	n.
Scotch	a.
Scotch	n.
Scotch	v. t.
Scotch	n.
Scotch	v. t.
Scotch	n.
Scotch"-hop`per	n.
Scotch"ing	n.
Scotch"man	n.
Scotch rite	n.
Scot"-free"	a.
Scoth	v. t.
Sco"ti*a	n.
Sco"ti*a	n.
Sco"tist	n.
Scot"o*graph	n.
Sco*to"ma	n.
Scot"o*my	n.
Sco"to*scope	n.
Scots	a.
Scots"man	n.
Scot"ter*ing	n.
Scot"ti*cism	n.
Scot"ti*cize	v. t.
Scot"tish	a.
Scot"tish ter"ri*er	n.
Scoun"drel	a.
Scoun"drel*dom	n.
Scoun"drel*ism	n.
Scour	v. t.
Scour	v. i.
Scour	n.
Scour"age	n.
Scour"er	n.
Scourge	n.
Scourge	v. t.
Scour"ger	n.
Scourse	v. t.
Scouse	n.
Scout	n.
Scout	n.
Scout	v. t.
Scout	n.
Scout	v. t.
Scout	v. i.
Scov"el	n.
Scow	n.
Scow	v. t.
Scowl	v. i.
Scowl	v. t.
Scowl	n.
Scowl"ing*ly	adv.
Scrab"bed eggs`	v. i.
Scrab"ble	v. t.
Scrab"ble	n.
Scra"ber	n.
Scraf"fle	v. i.
Scrag	n.
Scrag	v. t.
Scrag"ged	a.
Scrag"ged*ness	n.
Scrag"gi*ly	adv.
Scrag"gi*ness	n.
Scrag"gy	a.
Scrag"ly	a.
Scrag"-necked`	a.
Scram	v. i.
Scram	v. t.
Scram	n.
Scram"ble	v. i.
Scram"ble	v. t.
Scram"ble	n.
Scram"bled eggs	n.
Scram"bling	a.
Scranch	v. t.
Scrank"y	a.
Scran"nel	a.
Scran"ny	a.
Scrap	n.
Scrap"book`	n.
Scrape	v. t.
Scrape	v. i.
Scrape	n.
Scrape"pen`ny	n.
Scrap"er	n.
Scrap"ing	n.
Scrap"ing	a.
Scrap"pi*ly	adv.
Scrap"ple	n.
Scrap"py	a.
Scrat	v. t.
Scrat	v. i.
Scrat	n.
Scratch	v. t.
Scratch	v. i.
Scratch	n.
Scratch	a.
Scratch"back`	n.
Scratch"brush`	n.
Scratch" coat`	n.
Scratch" hit	n.
Scratch"ing	adv.
Scratch player	n.
Scratch"work`	n.
Scratch"y	a.
Scraw	n.
Scrawl	v. i.
Scrawl	v. t.
Scrawl	v. i.
Scrawl	n.
Scrawl"er	n.
Scraw"ny	a.
Scray	n.
Scre"a*ble	a.
Screak	v. i.
Screak	n.
Scream	v. i.
Scream	n.
Scream"er	n.
Scream"ing	a.
Scree	n.
Screech	v. i.
Screech	n.
Screech"ers	n. pl.
Screech"y	a.
Screed	n.
Screed	n.
Screen	n.
Screen	v. t.
Screen"ing	n.
Screen"ings	n. pl.
Screw	n.
Screw	v. t.
Screw	v. i.
screw"ball	n.
screw"ball	adj.
Screw"-cut`ting	a.
Screw"driv`er	n.
Screw"er	n.
Screw"ing	a. & n.
Scrib"a*ble	a.
Scri*ba"tious	a.
Scrib"bet	n.
Scrib"ble	v. t.
Scrib"ble	v. t.
Scrib"ble	v. i.
Scrib"ble	n.
Scrib"ble*ment	n.
Scrib"bler	n.
Scrib"bler	n.
Scrib"bling	n.
Scrib"bling	a.
Scrib"bling	n.
Scrib"bling*ly	adv.
Scribe	n.
Scribe	v. t.
Scribe	v. i.
Scrib"er	n.
Scrib"ism	n.
Scrid	n.
Scrig"gle	v. i.
Scrim	n.
Scri"mer	n.
Scrim"mage	n.
Scrimp	v. t.
Scrimp	a.
Scrimp	n.
Scrimp"ing	a. & n.
Scrimp"ing*ly	adv.
Scrimp"ness	n.
Scrimp"tion	n.
Scrim"shaw`	v. t.
Scrim"shaw`	n.
Scrine	n.
Scringe	v. i.
Scrip	n.
Scrip	n.
Scrip"page	n.
Script	n.
Scrip*to"ri*um	n.
Scrip"to*ry	a.
Scrip"tur*al	a.
Scrip"tur*al*ism	n.
Scrip"tur*al*ist	n.
Scrip"tur*al*ly	adv.
Scrip"tur*al*ness	n.
Scrip"ture	n.
Scrip*tu"ri*an	n.
Scrip"tur*ist	n.
Scrit	n.
Scritch	n.
Scrive"ner	n.
Scro*bic"u*la	n.
Scro*bic"u*lar	a.
Scro*bic"u*late	a.
Scrod	n.
Scrod"dled ware`	n.
Scrof"u*lide	n.
Scrof"u*lous	a.
Scrog	n.
Scrog"gy	a.
Scroll	n.
Scrolled	a.
Scroph`u*la"ri*a	n.
Scroph`u*la`ri*a"ceous	a.
Scro"tal	a.
Scro"ti*form	a.
Scro"to*cele	n.
Scro"tum	n.
Scrouge	v. t.
Scrow	n.
Scroyle	n.
Scrub	v. t.
Scrub	v. i.
Scrub	n.
Scrub	a.
Scrub"bed	a.
Scrub"ber	n.
Scrub"ber	n.
Scrub"board`	n.
Scrub"by	a.
Scrub"stone`	n.
Scruff	n.
Scruff	n.
Scrum"mage	n.
Scrump"tious	a.
Scrunch	v. t. & v. i.
Scru"ple	n.
Scru"ple	v. i.
Scru"ple	v. t.
Scru"pler	n.
Scru"pu*list	n.
Scru"pu*lize	v. t.
Scru`pu*los"i*ty	n.
Scru"pu*lous	a.
Scru"ta*ble	a.
Scru*ta"tion	n.
Scru*ta"tor	n.
Scru`tin" de liste"	n.
Scru"ti*nize	v. t.
Scru"ti*nize	v. i.
Scru"ti*ni`zer	n.
Scru"ti*nous	a.
Scru"ti*ny	n.
Scru"ti*ny	v. t.
Scru*toire"	n.
Scruze	v. t.
Scry	v. t.
Scry	n.
Scry	n.
Scud	v. i.
Scud	v. t.
Scud	n.
Scud"dle	v. i.
Scu"do	n.
Scuff	n.
Scuff	v. i.
Scuff	v. t.
Scuf"fle	v. i.
Scuf"fle	n.
Scuf"fler	n.
Scug	v. i.
Scug	n.
Sculk	n.
Scull	n.
Scull	n.
Scull	v. t.
Scull	v. i.
Scull"er	n.
Scul"ler*y	n.
Scul"lion	n.
Scul"lion	n.
Scul"lion*ly	a.
Sculp	v. t.
Scul"pin	n.
Sculp"tile	a.
Sculp"tor	n.
Sculp"tress	n.
Sculp"tur*al	a.
Sculp"ture	n.
Sculp"ture	v. t.
Sculp`tur*esque"	a.
Scum	n.
Scum	v. t.
Scum	v. i.
Scum"ber	v. i.
Scum"ber	n.
Scum"ble	v. t.
Scum"bling	n.
Scum"mer	v. i.
Scum"mer	n.
Scum"mer	n.
Scum"ming	n.
Scum"my	a.
Scun"ner	v. t.
Scun"ner	v. i.
Scun"ner	n.
Scup	n.
Scup	n.
Scup"paug	n.
Scup"per	n.
Scup"per*nong	n.
Scur	v. i.
Scurf	n.
Scurff	n.
Scurf"i*ness	n.
Scurf"y	a.
Scur"ri*er	n.
Scur"rile	a.
Scur*ril"i*ty	n.
Scur"ril*ous	a.
Scur"rit	n.
Scur"ry	v. i.
Scur"ry	n.
Scur"vi*ly	adv.
Scur"vi*ness	n.
Scur"vy	a.
Scur"vy	n.
Scut	n.
Scu"ta	n. pl.
Scu"tage	n.
Scu"tal	a.
Scu"tate	a.
Scutch	v. t.
Scutch	n.
Scutch"eon	n.
Scutch"eoned	a.
Scutch"er	n.
Scutch" grass`	n.
Scu*tel"la	n. pl.
Scu*tel"la	n.
Scu"tel*late	a.
Scu`tel*la"tion	n.
Scu*tel"li*form	a.
Scu*tel`li*plan"tar	a.
Scu*tel"lum	n.
Scu"ti*branch	a.
Scu`ti*bran"chi*a	n. pl.
Scu`ti*bran"chi*an	n.
Scu`ti*bran`chi*a"ta	n. pl.
Scu`ti*bran"chi*ate	a.
Scu*tif"er*ous	a.
Scu"ti*form	a.
Scu"ti*ger	n.
Scu"ti*ped	a.
Scut"ter	v. i.
Scut"tle	n.
Scut"tle	v. i.
Scut"tle	n.
Scut"tle	n.
Scut"tle	v. t.
scut"tle*butt`	n.
Scu"tum	n.
Scyb"a*la	n. pl.
Scye	n.
Scyle	v. t.
Scyl"la	n.
Scyl*lae"a	n.
Scyl*la"ri*an	n.
Scyl"lite	n.
Scym"e*tar	n.
Scy"pha	n.
Scy"phi*form	a.
Scy*phis"to*ma	n.
Scy`pho*bran"chi*i	n. pl.
Scy`pho*me*du"sae	n. pl.
Scy*phoph"o*ri	n. pl.
Scy"phus	n.
Scythe	n.
Scythe	v. t.
Scythed	a.
Scythe"man	n.
Scythe"stone`	n.
Scythe"whet`	n.
Scyth"i*an	a.
Scyth"i*an	n.
Scy`to*der"ma*ta	n. pl.
Sdain	v. & n.
'Sdeath	interj.
Sdeign	v. t.
Sea	n.
Sea" a"corn	n.
Sea" bar"row	n.
Sea" bean	n.
Sea" beast`	n.
Sea"board`	n.
Sea"board`	a.
Sea"board`	adv.
Sea"boat`	n. & a.
Sea"-bor"der*ing	a.
Sea"-born`	a.
Sea"bound`	a.
Sea" bow`	a.
Sea" but"ter*fly`	n.
Sea" cob`	n.
Sea" eel`	n.
Sea"far`ing	a.
Sea" feath"er	n.
Sea" gauge`	n.
Sea" gher`kin	a.
Sea" god`	a.
Sea" goose`	a.
Sea" gud"geon	n.
Sea" hare`	a.
Sea" jel"ly	n.
Sea" kale"	n.
Seal	n.
Seal	v. t.
Seal	v. i.
Sea" la"ces	a.
Sea" legs`	n.
Sealer	n.
Sea" let"ter	n.
Sea" lil"y	n.
Seam	n.
Seam	n.
Seam	v. t.
Seam	v. i.
Seam	n.
Sea"-maid`	n.
Sea"-mail`	n.
Sea"man	n.
Sea"man	n.
Sea"man*like`	a.
Sea"man*ship	n.
Sea" man"tis	n.
Sea" mat`	a.
Sea"-mell`	n.
Sea" mew`	n.
Seam"less	a.
Sea" monk`	n.
Seam"stress	n.
Seam"stress*y	n.
Sea" mud`	a.
Sean	n.
S<eacute/`ance"	n.
Sea" nee"dle	n.
Sea" on"ion	n.
Sea" ot"ter	n.
Sea" perch`	n.
Sea" pi"et	n.
Sea"poy	n.
Sea" pud"ding	n.
Sear	a.
Sear	v. t.
Sear	n.
Sea" rat`	n.
Searce	v. t.
Sear"cer	n.
Search	v. t.
Search	v. i.
Search	n.
Search"a*ble	a.
Search"a*ble*ness	n.
Search"er	n.
Search"ing	a.
Search"less	a.
Search"light`	n.
Sear"cloth`	n.
Sear"cloth	v. t.
Seared	a.
Sear"ed*ness	n.
Sea" reed`	a.
Sea" salm"on	n.
Sea"scape	n.
Sea" scor"pi*on	n.
Sea"shore`	n.
Sea"sick`	a.
Sea"sick`ness	n.
Sea"side`	n.
Sea" slat"er	n.
Sea"son	v. t.
Sea"son	v. i.
Sea"son*a*ble	a.
Sea"son*age	n.
Sea"son*al	a.
seasonal affective disorder	n.
Sea"son*er	n.
Sea"son*ing	n.
Sea"son*less	a.
Sea" spi"der	n.
Seat	v. t.
Seat	v. i.
Sea" tang`	n.
Sea" tit"ling	a.
Sea" toad`	n.
Seav`y	a.
Sea" wall`	a.
Sea"wan	n.
Sea"wand`	a.
Sea"ward	adv.
Sea"ware`	n.
Sea"weed`	n.
Sea" whip`	n.
Sea" wil"low	n.
Sea"wor`thy	a.
Sea" wrack`	a.
Se*bac"ic	a.
Se"bat	n.
Se"bate	n.
Se*bes"ten	n.
Se"bic	a.
Se*bif"er*ous	a.
Se*bip"a*rous	a.
Seb"or*rhe*a	n.
Se*ca"le	n.
Se"can*cy	n.
Se"cant	a.
Secant	n.
Sec"co	a.
Se"cede"	v. i.
Se*ced"er	n.
Se*cern"	v. t.
Se*cern"ent	a.
Se*cern"ent	n.
Se*cern"ment	n.
Se*cess"	n.
Se*ces"sion	n.
Se*ces"sion*ism	n.
Se*ces"sion*ist	n.
Seche	v. t. & i.
Se"chi*um	n.
Seck	a.
Seck"el	n.
Se"cle	n.
Se*clude	v. t.
Se*clu"sion	n.
Se*clu"sive	a.
Sec"ond	a.
Sec"ond	n.
Sec"ond	v. t.
Sec"ond*a*ri*ly	adv.
Sec"ond*a*ri*ness	n.
Sec"ond*a*ry	a.
Sec"ond*a*ry	n.
Sec"ond-class`	a.
Sec"ond*er	n.
Sec"ond*hand`	a.
Sec"ond*ly	adv.
Se*con"do	n.
Sec"ond-rate`	a.
Sec"ond-sight`	n.
Sec"ond-sight`ed	a.
Se"cre	a.
Se"cre	n.
Se"cre*cy	n.
Se"cre*ly	adv.
Se"cre*ness	n.
Se"cret	a.
Se"cret	n.
Se"cret	v. t.
Se"cret*age	n.
Sec`re*ta"ri*al	a.
Sec`re*ta"ri*at	n.
Sec"re*ta*ry	n.
Sec"re*ta*ry*ship	n.
Se*crete"	v. t.
Se*cre"tion	n.
Se"cret*ist	n.
Se`cre*ti"tious	a.
Se*cret"ive	a.
Se*cret"ive*ness	n.
Se"cret*ly	adv.
Se"cret*ness	n.
Se*cre`to-mo"to*ry	a.
Se*cre"to*ry	a.
Se"cret serv"ice	n.
Sect	n.
Sec"tant	n.
Sec*ta"ri*an	a.
Sec*ta"ri*an	n.
Sec*ta"ri*an*ism	n.
Sec*ta"ri*an*ize	v. t.
Sec"ta*rism	n.
Sec"ta*rist	n.
Sec"ta*ry	n.
Sec*ta"tor	n.
Sec"tile	a.
Sec*til"i*ty	n.
Sec"tion	n.
Sec"tion*al	a.
Sec"tion*al*ism	n.
Sec"tion*al"i*ty	n.
Sec"tion*al*ize	v. t.
Sec"tion*al*ly	adv.
Sec"tion*ize	v. t.
Sect"ism	n.
Sect"ist	n.
Sect"i*un`cle	n.
Sec"tor	n.
Sec"tor*al	a.
Sec*to"ri*al	a.
Sec"u*lar	a.
Sec"u*lar	n.
Sec"u*lar*ism	n.
Sec"u*lar*ist	n.
Sec`u*lar"i*ty	n.
Sec`u*lar*i*za"tion	n.
Sec"u*lar*ize	v. t.
Sec"u*lar*ly	adv.
Sec"u*lar*ness	n.
Se"cund	a.
Se*cun"date	v. t.
Sec`un*da"tion	n.
Sec"un*dine	n.
Se*cun`do-gen"i*ture	n.
Se*cur"a*ble	a.
Se*cure"	a.
Se*cure"	v. t.
Se*cure"ly	adv.
Se*cure"ment	n.
Se*cure"ness	n.
Se*cur"er	n.
Sec`u*rif"e*ra	n. pl.
Se*cu"ri*form	a.
Se*cu"ri*palp	n.
Se*cu"ri*ty	n.
Se*dan"	n.
Se*date"	a.
Se*da"tion	n.
Sed"a*tive	a.
Sed"a*tive	n.
Se"dent	a.
Sed"en*ta*ri*ly	adv.
Sed"en*ta*ri*ness	n.
Sed"en*ta*ry	a.
Se*de"runt	n.
Sedge	n.
Sedged	a.
Sedg"y	a.
Se*dil"i*a	n. pl.
Sed"i*ment	n.
Sed`i*men"tal	a.
Sed`i*men"ta*ry	a.
Sed`i*men*ta"tion	n.
Se*di"tion	n.
Se*di"tion*a*ry	n.
Se*di"tious	a.
Sed"litz	a.
Se*duce"	v. t.
Se*duce"ment	n.
Se*du"cer	n.
Se*du"ci*ble	a.
Se*du"cing	a.
Se*duc*tion	n.
Se*duc"tive	a.
Se*duc"tive*ly	adv.
Se*duc"tress	n.
Se*du"li*ty	n.
Sed"u*lous	a.
Se"dum	n.
See	n.
See	v. t.
See	v. i.
See"catch	n.
Seed	n.
Seed	v. i.
Seed	v. t.
Seed"box`	n.
Seed"cake`	n.
Seed"cod`	n.
Seed"er	n.
Seed`i*ness	n.
Seed"-lac`	n.
Seed"less	a.
Seed"ling	n.
Seed"lip`	n.
Seed"man	n.
Seeds"man	n.
Seed"time`	n.
Seed"y	a.
See"ing	conj.
Seek	a.
Seek	v. t.
Seek	v. i.
Seek"er	n.
Seek"-no-fur`ther	n.
Seek"-sor`row	n.
Seel	v. t.
Seel	v. i.
Seel	n.
Seel	n.
Seel"i*ly	adv.
Seel"y	a.
Seem	v. i.
Seem	v. t.
Seem"er	n.
Seem"ing	a.
Seem"ing	n.
Seem"ing*ly	adv.
Seem"ing*ness	n.
Seem"less	a.
Seem"li*ly	adv.
Seem"li*ness	n.
Seem"ly	a.
Seem"ly	adv.
Seem"ly*hed	n.
Seen	p. p.
Seen	a.
Seep	v. i.
Seep"age	n.
Seep"age	n.
Seep"y	a.
Seer	a.
Se"er	n.
Seer	n.
Seer"ess	n.
Seer"fish`	n.
Seer"hand	n.
Seer"ship	n.
Seer"suck`er	n.
Seer"wood`	n.
See"saw`	n.
See"saw`	v. i.
See"saw`	v. t.
See"saw`	a.
Seet	imp.
Seeth	imp.
Seethe	v. t.
Seethe	v. i.
Seeth"er	n.
Seg	n.
Seg	n.
Se*gar"	n.
Seg"gar	n.
Segge	n.
Seg"ment	n.
Seg"ment	v. i.
Seg*men"tal	a.
Seg`men*ta"tion	n.
Seg"ment*ed	a.
Seg"ni*tude	n.
Se"gno	n.
Se"go	n.
Seg"re*gate	a.
Seg"re*gate	v. t.
Seg"re*gate	v. i.
Seg`re*ga"tion	n.
Seiches	n. pl.
Seid	n.
Seid"litz	a.
Seigh	imp. sing.
Seign*eu"ri*al	a.
Seign"ior	n.
Seign"ior*age	n.
Seign"ior*al	a.
Seign"ior*al*ty	n.
Seign*io"ri*al	a.
Seign"ior*ize	v. t.
Seign"ior*y	n.
Seine	n.
Sein"er	n.
Sein"ing	n.
Seint	n.
Seint	n.
Sein"tu*a*ry	n.
Seir"fish`	n.
Sei"ro*spore	n.
Seise	v. t.
Sei"sin	n.
Seis"mic	a.
Seis"mo*gram	n.
Seis"mo*graph	n.
Seis`mo*graph"ic	a.
Seis*mog"ra*phy	n.
Seis`mo*log"ic*al	a.
Seis*mol"o*gy	n.
Seis*mom"e*ter	n.
Seis`mo*met"ric	a.
Seis*mom"e*try	n.
Seis"mo*scope	n.
Se"i*ty	n.
Seiz"a*ble	a.
Seize	v. t.
Seiz"er	n.
Sei"zin	n.
Seiz"ing	n.
Sei"zor	n.
Sei"zure	n.
Se"jant	a.
Se*jein"	v. t.
Se*junc"tion	n.
Se*jun"gi*ble	a.
Seke	a.
Seke	v. t. & i.
Se"kes	n.
Se*la"chi*an	n.
Se*la"chi*i	n. pl.
Sel`a*choi"de*i	n. pl.
Sel`a*chos"to*mi	n. pl.
Sel`a*gi*nel"la	n.
Se"lah	n.
Sel"couth	a.
Seld	a.
Seld	adv.
Sel"den	adv.
Sel"dom	adv.
Sel"dom	a.
Sel"dom*ness	n.
Seld"seen`	a.
Seld"shewn`	a.
Se*lect"	a.
Se*lect"	v. t.
Se*lect"ed*ly	adv.
Se*lec"tion	n.
Se*lect"ive	a.
Se*lect"man	n.
Se*lect"ness	n.
Se*lect"or	n.
Sel"e*nate	n.
Sel`en*hy"dric	a.
Se*len"ic	a.
Sel"e*nide	n.
Sel`e*nif"er*ous	a.
Se*le"ni*o-	a.
Sel"e*nite	n.
Sel"e*nite	n.
Sel`e*nit"ic	a.
Se*le"ni*um	n.
Sel`e*ni"u*ret	n.
Sel`e*ni"u*ret`ed	a.
Se*le`no*cen"tric	a.
Se*le"no*graph	n.
Sel`e*nog"ra*pher	n.
Sel`e*no*graph"ic	a.
Sel`e*nog"ra*phist	n.
Sel`e*nog"ra*phy	n.
Sel`e*nol"o*gy	n.
Sel`e*no"ni*um	n.
Self	a.
Self	n.
Self`-a*based"	a.
Self`-a*base"ment	n.
Self`-a*bas"ing	a.
Self`-ab*hor"rence	n.
Self`-ab`ne*ga"tion	n.
Self`-abuse"	n.
Self"-ac*cused"	a.
Self`-act"ing	a.
Self`-ac"tion	n.
Self`-ac"tive	a.
Self`-ac*tiv"i*ty	n.
Self`-ad*just"ing	a.
Self`-ad`mi*ra"tion	n.
Self`-af*fairs"	n. pl.
Self`-af*fright"ed	a.
Self`-ag*gran"dize*ment	n.
Self`-an*ni"hi*la`ted	a.
Self`-an*ni`hi*la"tion	n.
Self`-ap*plause"	n.
Self`-ap*ply"ing	a.
Self`-ap*prov"ing	a.
Self`-as*sert"ing	a.
Self`-as*ser"tion	n.
Self`-as*sert"ive	a.
Self`-as*sumed`	a.
Self`-as*sured`	a.
Self`-ban"ished	a.
Self"-be*got"ten	a.
Self"-born`	a.
Self`-bind"er	n.
Self`-cen"tered	a.
Self`-cen"ter*ing	a.
Self`-cen*tra"tion	n.
Self`-char"i*ty	n.
Self"-col`or	n.
Self`-col"ored	a.
Self`-com*mand"	n.
Self`-com*mune"	n.
Self`-com*mu"ni*ca*tive	a.
Self`-com*mun"ion	n.
Self`-com*pla"cen*cy	n.
Self`-com*pla"cent	a.
Self`-con*ceit"	n.
Self`-con*ceit"ed	a.
Self`-con*cern"	n.
Self`-con`dem*na"tion	n.
Self`-con"fi*dence	n.
Self`-con"fi*dent	a.
Self`-con"ju*gate	a.
Self`-con"scious	a.
Self`-con"scious*ness	n.
Self`-con*sid"er*ing	a.
Self`-con*sist"en*cy	n.
Self`-con*sist"ent	a.
Self`-con*sum"ing	a.
Self`-con*tained"	a.
Self`-con*tained" Underwater Breathing Apparatus	n.
Self`-con`tra*dic"tion	n.
Self`-con`tra*dict"o*ry	a.
Self`-con*trol"	n.
Self`-con*vict"ed	a.
Self`-con*vic"tion	n.
Self`-cre*at"ed	a.
Self`-cul"ture	n.
Self`-de*ceit"	n.
Self`-de*ceived"	a.
Self`-de*cep"tion	n.
Self`-de*fence"	n.
Self`-de*fense"	n.
Self`-de*fen"sive	a.
Self`-deg`ra*da"tion	n.
Self`-de*la"tion	n.
Self`-de*lu"sion	n.
Self`-de*ni"al	n.
Self`-de*ny"ing	a.
Self`-de*pend"ent	a.
Self`-de*pend"ing	a.
Self`-de*praved"	a.
Self`-de*stroy"er	n.
Self`-de*struc"tion	n.
Self`-de*struc"tive	a.
Self`-de*ter`mi*na"tion	n.
Self`-de*ter"min*ing	a.
Self`-de*vised"	a.
Self`-de*vot"ed	a.
Self`-de*vote"ment	n.
Self`-de*vo"tion	n.
Self`-de*vour"ing	a.
Self`-dif*fu"sive	a.
Self`-dis"ci*pline	n.
Self`-dis*trust"	n.
Self`-ed"u*ca`ted	a.
Self`-e*lect"ive	a.
Self`-en*joy"ment	n.
Self`-es*teem"	n.
Self`-es`ti*ma"tion	n.
Self`-ev"i*dence	n.
Self`-ev"i*dent	a.
Self`-ev`o*lu"tion	n.
Self`-ex`al*ta"tion	n.
Self`-ex*am"i*nant	n.
Self`-ex*am`i*na"tion	n.
Self`-ex*cite"	v. t.
Self`-ex*ist"ence	n.
Self`-ex*ist"ent	a.
self`-ex*plain"ing	a.
Self`-ex*po"sure	n.
Self`-fer`ti*li*za"tion	n.
Self`-fer"ti*lized	a.
Self`-glo"ri*ous	a.
Self`-gov"ern*ment	n.
Self`-grat`u*la"tion	n.
Self`-hard"en*ing	a.
Self`-heal"	n.
Self`-heal"ing	a.
Self`-help"	n.
Self`-help"	a.
Self`-hom"i*cide	n.
Self"hood	n.
Self`-ig"no*rance	n.
Self`-ig"no*rant	a.
Self`-im*part"ing	a.
Self`-im*por"tance	n.
Self`-im*por"tant	a.
Self`-im*posed"	a.
Self`-im*pos"ture	n.
Self`-in`dig*na"tion	n.
Self`-in*duc"tion	n.
Self`-in*dul"gence	n.
Self`-in*dul"gent	a.
Self`-in"ter*est	n.
Self`-in"ter*est*ed	a.
Self`-in`vo*lu"tion	n.
Self"ish	a.
Self"ish*ly	adv.
Self"ish*ness	n.
Self"ism	n.
Self"ist	n.
Self`-jus"ti*fi`er	n.
Self`-kin"dled	a.
Self`-know"ing	a.
Self`-knowl"edge	n.
Self"less	a.
Self"less*ness	n.
Self"-life`	n.
Self`-love`	n.
Self`-lu"mi*nous	a.
Self"-made`	a.
Self"-met`tle	n.
Self`-mo"tion	n.
Self`-moved"	a.
Self`-mov"ing	a.
Self`-mur"der	a.
Self`-mur"der*er	n.
Self`-neg*lect"ing	n.
Self"ness	n.
Self`-one"	a.
Self`-o*pin"ion	n.
Self`-o*pin"ioned	a.
Self`-o*rig"i*na`ting	a.
Self`-par`ti*al"i*ty	n.
Self`-per*plexed"	a.
Self`-pos"it*ed	a.
Self`-pos"it*ing	a.
Self"-pos*sessed"	a.
Self`-pos*ses"sion	n.
Self"-praise`	n.
Self`-pres`er*va"tion	n.
Self`-prop"a*ga`ting	a.
Self`-reg"is*ter*ing	a.
Self`-reg"u*la`ted	a.
Self`-reg"u*la*tive	a.
Self`-re*li"ance	n.
Self`-re*li"ant	a.
Self`-re*nun`ci*a"tion	n.
Self`-re*pel"len*cy	n.
Self`-re*pel"ling	a.
Self`-rep`e*ti"tion	n.
Self`-re*proach"	n.
Self`-re*proached"	a.
Self`-re*proach"ing	a.
Self`-re*proof"	n.
Self`-re*proved"	a.
Self`-re*prov"ing	a.
Self`-re*prov"ing*ly	adv.
Self`-re*pug"nant	a.
Self`-re*pul"sive	a.
Self`-re*spect"	n.
Self`-re*strained"	a.
Self`-re*straint"	n.
Self`-rev"er*ence	n.
Self`-right"eous	a.
Self`-right"eous*ness	n.
Self`-sac"ri*fice	n.
Self`-sac"ri*fi`cing	a.
Self"same	a.
Self`-sat`is*fac"tion	n.
Self`-sat"is*fied	a.
Self`-sat"is*fy`ing	a.
Self"-seek`er	n.
Self"-seek`ing	a.
Self"-seek`ing	n.
Self`-slaugh"ter	n.
Self`-start"er	n.
Self`-suf*fi"cien*cy	n.
Self`-suf*fi"cient	a.
Self`-suf*fi"cing	a.
Self`-sus*pend"ed	a.
Self`-sus*pi"cious	a.
Self"-taught`	a.
Self`-tor*ment"or	n.
Self`-tor"ture	n.
Self"-trust`	n.
Self`-uned"	a.
Self"-view`	n.
Self`-will"	n.
Self`-willed"	a.
Self`-willed"ness	n.
Self"-wor`ship	n.
Self"-wrong`	n.
Sel"ion	n.
Sel*juk"i*an	a.
Sel*juck"i*an	n.
Sell	n.
Sell	n.
Sell	n.
Sell	n.
Sell	v. t.
Sell	v. i.
Sell	n.
Sel"lan*ders	n. pl.
Sell"er	n.
Sel"ters wa"ter	n.
Sel"vage	n.
Sel"vaged	a.
Sel`va*gee"	n.
Selve	a.
Selves	n.
Se"ly	a.
Se*mae`o*stom"a*ta	n. pl.
Sem*an"tic	n. sing. <or/ pl.
Sem*an"tics	n. sing. <or/ pl.
Sem"a*phore	n.
Sem`a*phor"ic	a.
Sem`a*phor"ic*al*ly	adv.
Se*maph"o*rist	n.
Se*ma`si*ol"o*gy	n.
Se*mat"ic	a.
Sem`a*tol"o*gy	n.
Sem"a*trope	n.
Sem"bla*ble	a.
Sem"bla*ble	n.
Sem"bla*bly	adv.
Sem"blance	n.
Sem"blant	a.
Sem"blant	n.
Sem"bla*tive	a.
Sem"ble	v. i.
Sem"ble	a.
Sem"bling	n.
seme	n.
Se*m<eacute/"	a.
Se`mei*og"ra*phy	n.
Se`mei*o*log"ic*al	a.
Se`mei*ol"o*gy	n.
Se`mei*ot"ic	a.
Se`mei*ot"ics	n.
Sem"e*le	n.
Se"men	n.
Sem`e*nif"er*ous	a.
Se*mes"ter	n.
Sem"i-	a.
Sem`i*a*cid"i*fied	a.
Sem`i*ad*her"ent	a.
Sem`i*am*plex"i*caul	a.
Sem"i*an`gle	n.
Sem`i*an"nu*al	a.
Sem`i*an"nu*al*ly	adv.
Sem`i*an"nu*lar	a.
Sem`i-A"ri*an	n.
Sem"i-A"ri*an	a.
Sem`i-A"ri*an*ism	n.
Sem`i*ax"is	n.
Sem`i*bar*ba"ri*an	a.
Sem`i*bar*bar"ic	a.
Sem`i*bar"ba*rism	n.
Sem`i*bar"ba*rous	a.
Sem"i*breve`	n.
Sem"i*brief`	n.
Sem"i*bull`	n.
Sem`i*cal*ca"re*ous	a.
Sem`i*cal*cined"	a.
Sem`i*cas"trate	v. t.
Sem`i*cen*ten"ni*al	a.
Sem`i*cen*ten"ni*al	n.
Sem`i*cha*ot"ic	a.
Sem"i*cho`rus	n.
Sem`i-Chris"tian*ized	a.
Sem"i*cir`cle	n.
Sem"i*cir`cled	a.
Sem`i*cir"cu*lar	a.
Sem`i cir*cum"fer*ence	n.
Sem"i*cirque	n.
Sem"i*co`lon	n.
Sem"i*col`umn	n.
Sem`i*co*lum"nar	a.
Sem`i*com*pact"	a.
Sem`i*con"scious	a.
Sem"i*cope`	n.
Sem`i crus*ta"ceous	a.
Sem`i*crys"tal*line	a.
Sem`i*cu"bic*al	a.
Sem`i*cu"bi*um	n.
Sem`i*cy*lin"dric	a.
Sem`i*de*is"tic*al	a.
Sem`i*dem"i*qua`ver	n.
Sem`i*de*tached"	a.
Sem`i*di*am"e*ter	n.
Sem`i*di`a*pa"son	n.
Sem`i*di`a*pen"te	n.
Sem`i*di`a*pha*ne"i*ty	n.
Sem`i*di*aph"a*nous	a.
Sem`i*di`a*tes"sa*ron	n.
Sem`i-Die"sel	a.
Sem`i*di"tone`	n.
Sem`i*di*ur"nal	a.
Sem"i*dome`	n.
Sem"i*dou`ble	n.
Sem`i*dou"ble	a.
Sem"i*fa`ble	n.
Sem"i*flexed`	a.
Sem"i*flo`ret	n.
Sem`i*flos"cu*lar	a.
Sem"i*flos`cule	n.
Sem`i*flos"cu*lous	a.
Sem`i*flu"id	a.
Sem"i*form`	n.
Sem"i*formed`	a.
Sem`i*glu"tin	n.
Sem`i*his*tor"i*cal	a.
Sem`i*ho"ral	a.
Sem`i*in"du*ra`ted	a.
Sem`i*la*pid"i*fied	a.
Sem"i*lens`	n.
Sem`i*len*tic"u*lar	a.
Sem`i*lig"ne*ous	a.
Sem`i*liq"uid	a.
Sem`i*li*quid"i*ty	n.
Sem`i*log"ic*al	a.
Sem"i*lor	n.
Sem`i*lu"nar	a.
Sem`i*lu"nar	n.
Sem`i*lu"na*ry	a.
Sem`i*lu"nate	a.
Sem"i*lune`	n.
Sem"i*met`al	n.
Sem`i*me*tal"lic	a.
Sem`i*month"ly	a.
Sem`i*mute"	a.
Sem"i*mute`	n.
Sem"i*nal	a.
Sem"i*nal	n.
Sem`i*nal"i*ty	n.
Sem`i*nar"	n.
Sem`i*na"ri*an	n.
Sem"i*na*ry	n.
Sem"i*na*ry	a.
Sem"i*nate	v. t.
Sem`i*na"tion	n.
Sem"ined	a.
Sem`i*nif"er*ous	a.
Sem`i*nif"ic	a.
Sem`i*ni*fi*ca"tion	n.
Sem"i*nist	n.
Sem"i*noles	n. pl.
Sem"i*nose`	n.
Sem`i*nude"	a.
Sem"i*nymph`	n.
Sem`i*oc*ca"sion*al*ly	adv.
Sem`i*of*fi"cial	a.
Se`mi*og"ra*phy	a.
Sem"i*o`pal	n.
Sem`i*o*paque"	a.
Sem`i*or*bic"u*lar	a.
Se`mi*ot"ic	a.
Se`mi*ot"ics	n.
Sem`i*o"val	a.
Sem`i*o"vate	a.
Sem`i*ox"y*gen*a`ted	a.
Sem`i*pa"gan	a.
Sem`i*pal"mate	a.
Sem`i*pa*rab"o*la	n.
Sem"i*ped	n.
Se*mip"e*dal	a.
Sem`i-Pe*la"gi*an	n.
Sem`i-Pe*la"gi*an	a.
Sem`i-Pe*la"gi*an*ism	n.
Sem`i*pel*lu"cid	a.
Sem`i*pel`lu*cid"i*ty	n.
Sem`i*pen"ni*form	a.
Sem`i*per"ma*nent	n.
Sem`i*per*spic"u*ous	a.
Sem`i*phlo*gis"ti*ca`ted	a.
Sem"i*plume`	n.
Sem`i*pre"cious	a.
Sem"i*proof`	n.
Sem`i pu"pa	n.
Sem"i*quad`rate	n.
Sem"i*qua`ver	n.
Sem"i*quin`tile	n.
Sem`i*ra"di*al	a.
Semiradial engine	a.
Sem"i*ring`	n.
Sem`i*sav"age	a.
Sem"i*sav`age	n.
Sem`i-Sax"on	a.
Sem"i*sex"tile	n.
Sem`i*sol"id	a.
Sem"i*soun	n.
Sem`i*spher"ic	a.
Sem`i*sphe*roid"al	a.
Sem"i*steel`	n.
Sem"i*ta	n.
Sem"i*tan`gent	n.
Sem"ite	n.
Sem`i*te*rete"	a.
Sem`i*ter"tian	a.
Sem*it"ic	a.
Sem"i*tism	n.
Sem"i*tone	n.
Sem`i*ton"ic	a.
Sem`i*ton*tine"	a.
Sem"i*tran`sept	n.
Sem`i*trans*lu"cent	a.
Sem`i*trans*par"en*cy	n.
Sem`i*trans*par"ent	a.
Sem`i*ver*tic"il*late	a.
Sem"i*vif	a.
Sem`i*vit"re*ous	a.
Sem`i*vit"ri*fi*ca"tion	n.
Sem`i*vit"ri*fied	a.
Sem`i*vo"cal	a.
Sem"i*vow`el	n.
Sem`i*week"ly	a.
Sem`o*lel"la	n.
Sem`o*li"na	n.
Sem`o*li"no	n.
Se*moule"	n.
Sem`per*vi"rent	a.
Sem"per*vive	n.
Sem`per*vi"vum	n.
Sem`pi*ter"nal	a.
Sem"pi*terne	a.
Sem`pi*ter"ni*ty	n.
Sem"pre	adv.
Semp"ster	n.
Semp"stress	n.
Semp"stress*y	n.
Sem"ster	n.
Se*mun"ci*a	n.
Sen	n.
Sen	adv., prep., & conj.
Sen"a*ry	a.
Sen"ate	n.
Sen"a*tor	n.
Sen`a*to"ri*al	a.
Sen`a*to"ri*al*ly	adv.
Sen`a*to"ri*an	a.
Sen`a*to"ri*ous	a.
Sen"a*tor*ship	n.
Se*na`tus*con*sult"	n.
Send	v. t.
Send	v. i.
Send	n.
Sen"dal	n.
Send"er	n.
Sen"e*cas	n. pl.
Se*ne"ci*o	n.
Se*nec"ti*tude	n.
Sen"e*ga	n.
Sen"e*gal	n.
Sen"e*gin	n.
Se*nes"cence	n.
Se*nes"cent	a.
Sen"es*chal	n.
Sen"es*chal*ship	n.
Senge	v. t.
Sen"green	n.
Se*nhor"	n.
Se*nho"ra	n.
Se"nile	a.
Se*nil"i*ty	n.
Sen"ior	a.
Sen"ior	n.
Sen*ior"i*ty	n.
Sen"ior*ize	v. i.
Sen"ior*y	n.
Sen"na	n.
Sen"na*chy	n.
Sen"net	n.
Sen"net	n.
Sen"night	n.
Sen"nit	n.
Se*noc"u*lar	a.
Se*no"ni*an	a.
Se*<ntil/or"	n.
Se*<ntil/o"ra	n.
Se`<ntil/o*ri"ta	n.
Sens	adv.
Sen"sate	v. t.
Sen"sate	a.
Sen*sa"tion	n.
Sen*sa"tion*al	a.
Sen*sa"tion*al*ism	n.
Sen*sa"tion*al*ist	n.
Sense	n.
Sense	v. t.
Sense"ful	a.
Sense"less	a.
Sen`si*bil"i*ty	n.
Sen"si*ble	a.
Sen"si*ble	n.
Sen"si*ble*ness	n.
Sen"si*bly	adv.
Sen`si*fa"cient	a.
Sen*sif"er*ous	a.
Sen*sif"ic	a.
Sen*sif"i*ca*to*ry	a.
Sen*sig"e*nous	a.
Sens"ism	n.
Sens"ist	n.
Sen"si*tive	a.
Sen`si*tiv"i*ty	n.
Sen"si*tize	v. t.
Sen"si*ti`zer	n.
Sen`si*tom"e*ter	n.
Sen"si*to*ry	n.
Sens"ive	a.
Sen"sor	a.
Sen*so"ri*al	a.
Sen*so"ri*um	n.
Sen*so`ri-vo*li"tion*al	a.
Sen"so*ry	n.
Sen"so*ry	a.
Sen"su*al	a.
Sen"su*al*ism	n.
Sen"su*al*ist	n.
Sen`su*al*is"tic	a.
Sen`su*al"i*ty	n.
Sen`su*al*i*za"tion	n.
Sen"su*al*ize	v. t.
Sen"su*al*ly	adv.
Sen"su*al*ness	n.
Sen"su*ism	n.
Sen`su*os"i*ty	n.
Sen"su*ous	a.
Sent	v. & n.
Sent	3d pers. sing. pres.
Sent	imp. & p. p.
Sen"tence	n.
Sen"tence	v. t.
Sen"tence meth`od	n.
sen*ten"tial	a.
Sen*ten"tial*ly	adv.
Sen*ten"ti*a*rist	n.
Sen*ten"ti*ary	n.
Sen*ten`ti*os"i*ty	n.
Sen*ten"tious	a.
Sen"ter*y	n.
Sen"teur	n.
Sen"ti*ence	n.
Sen"ti*ent	a.
Sen"ti*ent	n.
Sen"ti*ent*ly	adv.
Sen"ti*ment	n.
Sen`ti*men"tal	a.
Sen`ti*men"tal*ism	n.
Sen`ti*men"tal*ist	n.
Sen`ti*men*tal"i*ty	n.
Sen`ti*men"tal*ize	v. t.
Sen`ti*men"tal*ize	v. i.
Sen`ti*men"tal*ly	adv.
Sen"tine	n.
Sen"ti*nel	n.
Sen"ti*nel	v. t.
Sen`ti*sec"tion	n.
Sen"try	n.
Sen"za	prep.
Se"pal	n.
Se"paled	a.
Sep"al*ine	a.
Se*pal"o*dy	n.
Sep"al*oid	a.
Sep"al*ous	a.
Sep`a*ra*bil"i*ty	n.
Sep"a*ra*ble	a.
Sep"a*rate	v. t.
Sep"a*rate	v. i.
Sep"a*rate	p. a.
Sep`a*rat"ic*al	a.
Sep"a*ra`ting	a.
Sep`a*ra"tion	n.
Sep"a*ra*tism	n.
Sep`a*ra*tist	n.
Sep`a*ra*tis"tic	a.
Sep"a*ra*tive	a.
Sep"a*ra`tor	n.
Sep"a*ra*to*ry	a.
Sep"a*ra*to*ry	n.
Sep`a*ra"trix	n.
Se*pawn"	n.
Sep"e*li*ble	a.
Sep`e*li"tion	n.
Se*phar"dic	a.
Se*phar"dim	n. pl.
Se"phen	n.
Se"pi*a	n.
Se"pi*a	a.
Se"pic	a.
Sep`i*da"ceous	a.
Sep"i*ment	n.
Se"pi*o*lite`	n.
Se"pi*o*stare`	n.
Se*pon"	n.
Se*pose"	v. t.
Se*pos"it	v. t.
Sep`o*si"tion	n.
Se"poy	n.
Sep*pu"ku	n.
Sep"sin	n.
Sep"sis	n.
Sept	n.
Sep*tae"mi*a	n.
Sep"tal	a.
Sep"tane	n.
Sep"tan`gle	n.
Sep*tan"gu*lar	a.
Sep*ta"ri*um	n.
Sep"tate	a.
Sep*tem"ber	n.
Sep*tem"ber*er	n.
Sep*tem"brist	n.
Sep*tem"flu*ous	a.
Sep*tem"par*tite	a.
Sep*tem"tri*oun	n.
Sep*tem"vir	n.
Sep*tem"vi*rate	n.
Sep"ten*a*ry	a.
Sep"ten*a*ry	n.
Sep"ten*ate	a.
Sep*ten"nate	n.
Sep*ten"ni*al	a.
Sep*ten"ni*al*ly	adv.
Sep*ten"tri*al	a.
Sep*ten"tri*o	n.
Sep*ten"tri*on	n.
Sep*ten"tri*on	a.
Sep*ten`tri*on*al"i*ty	n.
Sep*ten"tri*on*al*ly	adv.
Sep*ten"tri*on*ate	v. i.
Sep*tet"	n.
Sept"foil	n.
Sep"ti-	a.
Sep"tic	a.
Sep"tic	n.
Sep`ti*cae"mi*a	n.
Sep"tic*al*ly	adv.
Sep"ti*ci`dal	a.
Sep*tic"i*ty	n.
Sep`ti*fa"ri*ous	a.
Sep*tif"er*ous	a.
Sep*tif"er*ous	a.
Sep*tif"lu*ous	a.
Sep`ti*fo"li*ous	a.
Sep"ti*form	a.
Sep*tif"ra*gal	a.
Sep`ti*lat"er*al	a.
Sep*til"lion	n.
Sep"ti*mole	n.
Sep*tin"su*lar	a.
Sep"ti*syl`la*ble	n.
Sep*to"ic	a.
Sep`to*max"il*la*ry	a.
Sep`tu*a*ge*na"ri*an	n.
Sep`tu*ag"e*na*ry	a.
Sep`tu*a*ges"i*ma	n.
Sep`tu*a*ges"i*mal	a.
Sep"tu*a*gint	n.
Sep"tu*a*ry	n.
Sep"tu*late	a.
Sep"tu*lum	n.
Sep"tum	n.
Sep"tu*or	n.
Sep"tu*ple	a.
Sep"tu*ple	v. t.
Sep"ul*cher	n.
Sep"ul*cher	v. t.
Se*pul"chral	a.
Sep"ul*ture	n.
Se*qua"cious	a.
Se*qua"cious*ness	n.
Se*quac"i*ty	n.
Se"quel	n.
Se*que"la	n.
Se"quence	n.
Se"quence	v. t.
Se"quent	a.
Se"quent	n.
Se*quen"tial	a.
Se*ques"ter	v. t.
Se*ques"ter	v. i.
Se*ques"ter	n.
Se*ques"tered	a.
Se*ques"tra*ble	a.
Se*ques"tral	a.
Se*ques"trate	v. t.
Seq`ues*tra"tion	n.
Seq"ues*tra`tor	n.
Se*ques"trum	n.
Se"quin	n.
Se*quoi"a	n.
Se*quoi"ene	n.
S<eacute/`rac"	n.
Se*ragl"io	n.
Se*ra"i	n.
Ser`al*bu"men	n.
Se*rang"	n.
Se*ra"pe	n.
Ser"aph	n.
Se*raph"ic	a.
Se*raph"i*cism	n.
Ser"a*phim	n.
Ser`a*phi"na	n.
Ser"a*phine	n.
Se*ra"pis	n.
Se*ras"kier	n.
Se*ras"kier*ate	n.
Ser*bo"ni*an	a.
Sere	a.
Sere	n.
Se*rein"	n.
Ser`e*nade"	n.
Ser`e*nade"	v. t.
Ser`e*nade"	v. i.
Ser`e*nad"er	n.
Ser`e*na"ta	n.
Se*rene"	a.
Se*rene"	n.
Se*rene"	v. t.
Se*rene"ly	adv.
Se*rene"ness	n.
Se*ren"i*tude	n.
Se*ren"i*ty	n.
Serf	n.
Serf"age	n.
Serf"hood	n.
Serge	n.
Serge	n.
Ser"gean*cy	n.
Ser"geant	n.
Ser"geant*cy	n.
Ser"geant*ry	n.
Ser"geant*ship	n.
Ser"geant*y	n.
Se"ri*al	a.
Se"ri*al	n.
Se`ri*al"i*ty	n.
Se"ri*al*ly	adv.
Se"ri*ate	a.
Se`ri*a"tim	adv.
Se`ri*a"tion	n.
Se*ri"ceous	a.
Ser"i*cin	n.
Ser"i*cite	n.
Ser`ic*te"ri*um	n.
Ser"i*cul`ture	n.
Se"rie	n.
Ser`i*e"ma	n.
Se"ries	n.
Series dynamo	a.
Ser`i*graph	n.
Ser"in	n.
Ser"ine	n.
Se`ri*o-com"ic	a.
Se"ri*ous	a.
Ser"iph	n.
Ser"jeant	n.
Ser*moc"i*na`tor	n.
Ser"mon	n.
Ser"mon	v. i.
Ser"mon	v. t.
Ser`mon*eer"	n.
Ser"mon*er	n.
Ser`mon*et"	n.
Ser*mon"ic	a.
Ser"mon*ing	n.
Ser"mon*ish	a.
Ser"mon*ist	n.
Ser"mon*ize	v. i.
Ser"mon*ize	v. t.
Ser"mon*i`zer	n.
Ser"o*lin	n.
Se*ron"	n.
Se"rose`	a.
Se*ros"i*ty	n.
Se`ro*ther"a*py	n.
Ser"o*tine	n.
Se*rot"i*nous	a.
Se"rous	a.
Ser"ow	n.
Ser"pens	n.
Ser"pent	n.
Ser"pent	v. i.
Ser"pent	v. t.
Ser`pen*ta"ri*a	a.
Ser`pen*ta"ri*us	n.
Ser*pen"ti*form	a.
Ser`pen*tig"e*nous	a.
Ser"pen*tine	a.
Ser"pen*tine	n.
Ser"pen*tine	v. i.
Ser"pen*tine*ly	adv.
Ser`pen*tin"i*an	n.
Ser"pen*tin*ize	v. t.
Ser"pen*ti`nous	a.
Ser"pent*ize	v. i.
Ser"pent*ry	n.
Ser"pent-tongued`	a.
Ser"pet	n.
Ser*pette"	n.
Ser*pig"i*nous	a.
Ser*pi"go	n.
Ser"po*let	n.
Ser"pu*la	n.
Ser*pu"li*an	n.
Ser"pu*lite	n.
Serr	v. t.
Ser*ra"noid	n.
Ser"rate	a.
Ser*ra"tion	n.
Ser*ra`ti*ros"tral	a.
Ser*ra"tor	n.
Ser"ra*ture	n.
Ser"ri*ca`ted	a.
Ser"ri*corn	a.
Ser"ri*corn	n.
Ser"ried	a.
Ser*rif"e*ra	n. pl.
Ser`ri*ros"tres	n. pl.
Ser"rous	a.
Ser"ru*la	n.
Ser"rulate	a.
Ser`ru*la"tion	n.
Ser"ry	v. t.
Ser`tu*la"ri*a	n.
Ser`tu*la"ri*an	n.
Se"rum	n.
Se"rum-ther`a*py	n.
Serv"a*ble	a.
Serv"age	n.
Ser"val	n.
Ser"val*ine	a.
Serv"ant	n.
Serv"ant	v. t.
Serv"ant*ess	n.
Serv"ant*ry	n.
Serve	v. t.
Serve	v. i.
Serv"er	n.
Ser"vi*an	a.
Serv"ice	n.
Serv"ice	n.
Serv"ice*a*ble	a.
Serv"ice*age	n.
Serv"ice cap	a.
Ser`viette"	n.
Serv"ile	a.
Serv"ile	n.
Serv"ile*ly	adv.
Serv"ile*ness	n.
Ser*vil"i*ty	n.
Serv"ing	a. & n.
Serv"ite	n.
Serv"i*tor	n.
Serv"i*tor*ship	n.
Serv"i*tude	n.
Serv"i*ture	n.
Serv"i*tute	n.
Ser`vo*con*trol"	n.
Ser`vo*mech"an*ism	n.
Ser`vo-mo"tor	n.
Se"rye	n.
Ses"a*me	n.
Ses"a*moid	a.
Ses"a*moid	n.
Ses`a*moid"al	a.
Ses"ban	n.
Ses`qui-	a.
Ses`qui*al"ter	n.
Ses`qui*al"ter*al	a.
Ses`qui*al"ter*ous	a.
Ses`qui*ba"sic	a.
Ses`qui*du"pli*cate	a.
Ses`qui*ox"ide	n.
Ses*quip"e*dal	a.
Ses`qui*pe*da"li*an*ism	n.
Ses`qui*pe*dal"i*ty	n.
Ses*quip"li*cate	a.
Ses"qui*salt	n.
Ses`qui*sul"phide	n.
Ses`qui*ter"tial	a.
Ses`qui*ter"tian	a.
Ses"qui*tone	n.
Sess	v. t.
Sess	n.
Ses"sa	interj.
Ses"sile	a.
Ses"sile-eyed`	a.
Ses"sion	n.
Ses"sion*al	a.
Sess"pool`	n.
Ses"terce	n.
Ses*tet"	n.
Ses*tet"to	n.
Ses"tine	n.
Ses"tu*or	n.
Set	v. t.
Set	v. i.
Set	a.
Set	n.
Set	prop. n.
Se"ta	n.
Se*ta"ceous	a.
Set"back`	n.
Set"bolt`	n.
Set chisel	n.
Set*ee"	n.
Set"en	obs. imp. pl.
Set"e*wale	n.
Set"-fair`	n.
Set"foil`	n.
Seth	prop. n.
Seth"en	adv. & conj.
Seth"ic	a.
Se*tif"er*ous	a.
Se"ti*form	a.
Se"ti*ger	n.
Se*tig"er*ous	a.
Se"tim	n.
set"-in sleeve`	n.
Se*tip"a*rous	a.
Se"ti*reme	n.
Set"ness	n.
Set"-off`	n.
Se"ton	n.
Se*tose"	a.
Set"out`	n.
Set"-stitched`	a.
Sett	n.
Set*tee"	n.
Set*tee"	n.
Set"ter	n.
Set"ter	v. t.
Set"ter*wort`	n.
Set"ting	n.
Set`ting-up" ex"er*cise	n.
Set"tle	v. t.
Set"tle	v. i.
Set"tled*ness	n.
Set"tle*ment	n.
Set"tler	n.
Set"tling	n.
Set"-to`	n.
Set"u*la	n.
Set"ule	n.
Set"u*lose`	a.
Set"wall`	n.
Sev"en	a.
Sev"en	n.
Sev"en*fold`	a.
Sev"en*fold`	adv.
Seven"night	n.
Sev"en*score`	n. & a.
Sev"en-shoot`er	n.
Sev"en*teen`	a.
Sev"en*teen`	n.
Sev"en*teenth`	a.
Sev"en*teenth`	n.
Sev"enth	a.
Sev"enth	n.
Sev`en-thir"ties	n. pl.
Sev"enth*ly	adv.
Sev"en*ti*eth	a.
Sev"en*ti*eth	n.
Sev"en*ty	a.
Sev"en*ty	n.
Sev`en*ty-four"	n.
Sev"en-up`	n.
Sev"er	v. t.
Sev"er	v. i.
Sev"er*a*ble	a.
Sev"er*al	a.
Sev"er*al	adv.
Sev"er*al	n.
Sev`er*al"i*ty	n.
Sev"er*al*ize	v. t.
Sev"er*al*ly	adv.
Sev"er*al*ty	n.
Sev"er*ance	n.
Se*vere"	a.
Se*ver"i*ty	n.
Sev"er*y	n.
Sev`o*ca"tion	n.
S<egrave/"vres blue`	n.
Sew	v. t.
Sew	v. t.
Sew	v. i.
Sew	v. t.
Sew"age	n.
Sewe	v. i.
Sew"el	n.
Se*wel"lel	n.
Sew"en	n.
Sew"er	n.
Sew"er	n.
Sew"er	n.
Sew"er*age	n.
Sew"in	n.
Sew"ing	n.
Sew"ster	n.
Sex-	n.
Sex`a*ge*na"ri*an	n.
Sex*ag"e*na*ry	a.
Sex*ag"e*na*ry	n.
Sex`a*ges"i*ma	n.
Sex`a*ges"i*mal	a.
Sex`a*ges"i*mal	n.
Sex"an`gle	n.
Sex"an`gled	a.
Sex*an"gu*lar*ly	adv.
Sex*av"a*lent	a.
Sex*dig"it*ism	n.
Sex*dig"it*ist	n.
Sexed	a.
Sex"e*na*ry	a.
Sex*en"ni*al	a.
Sex*en"ni*al*ly	adv.
Sex"fid	a.
Sex`i*syl*lab"ic	a.
Sex"i*syl`la*ble	n.
Sex*iv"a*lent	a.
Sex"less	a.
Sex`loc"u*lar	a.
Sex"ly	a.
Sex*ra"di*ate	a.
Sext	n.
Sex"tain	n.
Sex"tans	n.
Sex"tant	n.
Sex"ta*ry	n.
Sex"ta*ry	n.
Sex*tet"	n.
Sex"teyn	n.
Sex"tic	a.
Sex"tile	a.
Sex"tile	n.
Sex*til"lion	n.
Sex"to	n.
Sex`to*dec"i*mo	a.
Sex`to*dec"imo	n.
Sex"to*let	n.
Sex"ton	n.
Sex"ton*ess	n.
Sex"ton*ry	n.
Sex"ton*ship	n.
Sex"try	n.
Sex"tu*ple	a.
Sex"u*al	a.
Sex"u*al*ist	n.
Sex`u*al"i*ty	n.
Sex"u*al*ize	v. t.
Sex"u*al*ly	adv.
Sey	imp. sing. & 2d pers. pl.
Seye	imp. pl. & p. p.
Seynd	p. p.
Seynt	n.
Sfor*zan"do	a.
Sfu*ma"to	a.
Sgraf*fi"to	a.
Shab	n.
Shab	v. t.
Shab	v. t.
Shab"bed	a.
Shab"bi*ly	adv.
Shab"bi*ness	n.
Shab"ble	n.
Shab"by	a.
Shab"rack	n.
Shack	v. t.
Shack	n.
Shack	n.
Shack"a*to*ry	n.
Shac"kle	n.
Shac"kle	n.
Shac"kle	v. t.
Shack"lock`	n.
Shack"ly	a.
Shack" up`	v. i.
Shad	n. sing. & pl.
Shad"bird`	n.
Shadd	n.
Shad"de	obs. imp.
Shad"dock	n.
Shade	n.
Shade	v. t.
Shade	v. i.
Shade"ful	a.
Shade"less	a.
Shad"er	n.
Shad"i*ly	adv.
Shad"i*ness	n.
Shad"ing	n.
Sha*doof"	n.
Shad"ow	n.
Shad"ow	v. t.
Shad"ow*i*ness	n.
Shad"ow*ing	n.
Shad"ow*ish	a.
Shad"ow*less	a.
Shad"ow*y	a.
Sha"drach	n.
Shad"-spir`it	n.
Shad"-wait`er	n.
Shad"y	a.
Shaf"fle	v. i.
Shaf"fler	n.
Sha"fi*ite	n.
Shaft	n.
Shaft"ed	a.
Shaft"ing	n.
Shaft"man	n.
Shag	n.
Shag	a.
Shag	v. t.
Shag"bark`	n.
Shage"bush`	n.
Shag"ged	a.
Shag"gi*ness	n.
Shag"gy	a.
Shag"-haired`	a.
Shag"-rag`	n.
Sha*green"	v. t.
Sha*green"	n.
Sha*green"	a.
Shah	n.
Sha*hin"	n.
Shaik	n.
Shail	v. i.
Shai"tan	n.
Shake	obs. p. p.
Shake	v. t.
Shake	v. i.
Shake	n.
Shake"down`	n.
Shake"fork`	n.
Shak"en	a.
Shak"er	n.
Shak"er*ess	n.
Shak"er*ism	n.
Shake*spear"e*an	a.
Shak"i*ness	n.
Shak"ings	n. pl.
Shak"o	n.
Shak"u*do"	n.
Shak"y	a.
Shale	n.
Shale	v. t.
Shall	v. i. & auxiliary.
Shal"li	n.
Shal"lon	n.
Shal*loon"	n.
Shal"lop	n.
Shal*lot"	n.
Shal"low	a.
Shal"low	n.
Shal"low	v. t.
Shal"low	v. i.
Shal"low-bod`ied	a.
Shal"low-brained`	a.
Shal"low-heart`ed	a.
Shal"low*ly	adv.
Shal"low*ness	n.
Shal"low-pat`ed	a.
Shal"low-waist`ed	a.
Shalm	n.
Shalt	2d per. sing.
Shal"y	a.
Sham	n.
Sham	a.
Sham	v. t.
Sham	v. i.
Sha"ma	n.
Sha"man	n.
Sha*man"ic	a.
Sha"man*ism	n.
Sha"man*ist	n.
Sham"ble	n.
Sham"ble	v. i.
Sham"bling	a.
Sham"bling	n.
Shame	n.
Shame	v. t.
Shame	v. i.
Shame"faced`	a.
Shame"fast	a.
Shame"ful	a.
Shame"less	a.
Shame"-proof`	n.
Sham"er	n.
Sham"mer	n.
Sham"my	n.
Sham"ois	n.
Sha*moy"ing	n.
Sham*poo"	v. t.
Sham*poo"	n.
Sham*poo"er	n.
Sham"rock	n.
Shan"dry*dan	n.
Shan"dy*gaff	n.
Shang`hai"	v. t.
Shang`hai"	n.
Shank	n.
Shank	n.
Shank	v. i.
Shank"beer`	n.
Shanked	a.
Shank"er	n.
Shan"ny	n.
Shan't	a.
Shan"ty	n.
Shan"ty	v. i.
Shap"a*ble	a.
Shape	v. t.
Shape	v. i.
Shape	n.
Shape"less	a.
Shape"li*ness	n.
Shape"ly	a.
Shap"er	n.
Sha"poo	n.
Shaps	n. pl.
Shard	n.
Shard	n.
Shard"-borne`	a.
Shard"ed	a.
Shard"y	a.
Share	n.
Share	n.
Share	v. t.
Share	v. i.
Share"beam`	n.
Share"bone`	n.
Share"bro`ker	n.
Share"crop`per	n.
Share"hold`er	n.
Shar"er	n.
Share"wort`	n.
Shark	n.
Shark	v. t.
Shark	v. i.
Shark"er	n.
Shark"ing	n.
Shar"ock	n.
Sharp	a.
Sharp	adv.
Sharp	n.
Sharp	v. t.
Sharp	v. i.
Sharp-cut`	a.
Sharp"en	v. t.
Sharp"en	v. i.
Sharp"er	n.
Sharp"ie	n.
Sharp"ling	n.
Sharp"ly	adv.
Sharp"ness	n.
Sharp"saw`	n.
Sharp"-set`	a.
Sharp"shoot`er	n.
Sharp"shoot`ing	n.
Sharp"-sight`ed	a.
Sharp"tail`	n.
Sharp"-wit`ted	a.
Shash	n.
Shas"ta	n.
Shasta daisy	n.
Shath"mont	n.
Shat"ter	v. t.
Shat"ter	v. i.
Shat"ter	n.
Shat"ter-brained`	a.
Shat"ter*y	a.
Shave	obs. p. p.
Shave	v. t.
Shave	v. i.
Shave	n.
Shave"ling	n.
Shav"er	n.
Shav"ing	n.
Shaw	n.
Shaw"fowl`	n.
Shawl	n.
Shawl	v. t.
Shawm	n.
Shaw`nees"	n. pl.
Shay	n.
She	pron.
Shead"ing	n.
Sheaf	n.
Sheaf	n.
Sheaf	v. t.
Sheaf	v. i.
Sheaf"y	a.
Sheal	n.
Sheal	v. t.
Sheal	v. t.
Sheal	n.
Sheal"ing	n.
Sheal"ing	n.
Shear	v. t.
Shear	n.
Shear	v. i.
Shear"bill`	n.
Sheard	n.
Shear"er	n.
Shear"ing	n.
Shear"ling	n.
Shear"man	n.
Shearn	n.
Shears	n. pl.
Shear steel	n.
Shear"wa`ter	n.
Sheat"fish`	n.
Sheath	n.
Sheath"bill`	n.
Sheathe	v. t.
Sheathed	a.
Sheath"er	n.
Sheath"fish`	n.
Sheath"ing	p. pr. & a.
Sheath"ing	n.
Sheath"less	a.
Sheath"-winged`	a.
Sheath"y	a.
She"a tree`	n.
Sheave	v. t.
Sheaved	a.
Sheb"an*der	n.
She*bang"	n.
She*been"	n.
She*chi"nah	n.
Sheck"la*ton	n.
Shed	n.
Shed	v. t.
Shed	v. i.
Shed	n.
Shed"der	n.
Shed"ding	n.
Sheel"fa	n.
Sheel"ing	n.
Sheel"y	n.
Sheen	a.
Sheen	v. i.
Sheen	n.
Sheen""ly	adv.
Sheen"y	a.
Sheep	n. sing. & pl.
Sheep"back`	n.
Sheep"ber`ry	n.
Sheep"bite`	v. i.
Sheep"bit`er	n.
Sheep"cot`	n.
Sheep"-faced`	a.
Sheep"fold`	n.
Sheep"-head`ed	a.
Sheep"hook`	n.
Sheep"ish	a.
Sheep"mas`ter	n.
Sheep"rack`	n.
Sheep's"-eye`	n.
Sheep's-foot`	n.
Sheep"shank`	n.
Sheeps"head`	n.
Sheep"-shear`er	n.
Sheep"-shear`ing	n.
Sheep"skin`	n.
Sheep"split`	n.
Sheep"y	a.
Sheer	a.
Sheer	adv.
Sheer	v. t.
Sheer	v. i.
Sheer	n.
Sheer"ly	adv.
Sheer"wa`ter	n.
Sheet	n.
Sheet	v. t.
Sheet" an"chor	v. t.
Sheet" ca"ble	n.
Sheet"ing	n.
Sheik	n.
Sheil	n.
Shek"el	n.
She*ki"nah	n.
Sheld	a.
Sheld"a*fle	n.
Sheld"fowl`	n.
Shel"drake`	n.
Shel"duck`	n.
Shelf	n.
Shelf"y	a.
Shell	n.
Shell	v. t.
Shell	v. i.
Shel"lac`	n.
Shell"ap`ple	n.
Shell"bark`	n.
Shelled	a.
Shell"er	n.
Shell"fish`	n.
Shell"ing	n.
Shell"-less	a.
Shell"proof`	a.
Shell"work`	n.
Shell"y	a.
Shel"ter	n.
Shel"ter	v. t.
Shel"ter	v. i.
Shel"ter*less	a.
Shel"ter*y	a.
Shel"tie	n.
Shelve	v. t.
Shelve	v. i.
Shelv"ing	a.
Shelv"ing	n.
Shelv"y	a.
Shem"ite	n.
Shem*it"ic	a.
Shem"i*tism	n.
Shend	v. t.
Shend"ful	a.
Shend"ship	n.
Shent	obs. 3d pers. sing. pres.
Shent	v. t.
She"ol	n.
Shep"en	n.
Shep"herd	n.
Shep"herd	v. t.
Shep"herd*ess	n.
Shep*her"di*a	n.
Shep"herd*ish	n.
Shep"herd*ism	n.
Shep"herd*ling	n.
Shep"herd*ly	a.
Shep"ster	n.
Sher"ard*ize	v. t.
Sher"bet	n.
Sherd	n.
Sher"eef	n.
Sher"i*at	n.
Sher"iff	n.
Sher"iff*al*ty	n.
Shern	n.
Sher"ris	n.
Sher"ry	n.
Sher"ry*val`lies	n. pl.
Shet	v. t. & i.
Shete	v. t. & i.
Sheth	n.
Shet"land po"ny	v. t. & i.
Shew	n.
Shew"bread`	n.
Shew"er	n.
Shewn	p. p.
Shi"ah	prop. n.
Shib"bo*leth	n.
Shi"cer	n.
Shide	n.
Shie	v. t.
Shied	imp. & p. p.
Shiel	n.
Shield	n.
Shield	v. t.
Shield"-bear`er	n.
Shield"drake`	n.
Shield"less	a.
Shield"tail`	n.
Shiel"ing	n.
Shift	v. t.
Shift	v. i.
Shift	n.
Shift"a*ble	a.
Shift"er	n.
Shift"i*ness	n.
Shift"ing	a.
Shift"ing*ly	adv.
Shift"less	a.
Shift"y	a.
Shi"ite	n.
Shi*ka"ree	n.
Shilf	n.
Shill	v. t.
Shill	v. t.
Shil*la"lah	n.
Shil"ling	n.
Shill"-I-shall`-I	adv.
Shil"ly-shal`ly	v. i.
Shil"ly-shal`ly	n.
Shi"loh	n.
Shi"ly	adv.
Shim	n.
Shim"mer	v. i.
Shim"mer	n.
Shim"mer*ing	n.
Shim"my	n.
Shin	n.
Shin	v. i.
Shin	v. t.
Shin"dle	n.
Shin"dle	v. t.
Shin"dy	n.
Shine	v. i.
Shine	v. t.
Shine	n.
Shine	a.
Shin"er	n.
Shi"ness	n.
Shin"gle	n.
Shin"gle	n.
Shin"gle	v. t.
Shin"gle	v. t.
Shin"gler	n.
Shin"gles	n.
Shin"gling	n.
Shin"gly	a.
Shin"hop`ple	n.
Shin"ing	a.
Shin"ing	n.
Shin"ing*ness	n.
Shin"ney	n.
Shin Shu	n.
Shin"plas`ter	n.
Shin"to	n.
Shin"to*ist	n.
Shin"ty	n.
Shin"y	a.
-ship	n.
Ship	n.
Ship	n.
Ship	v. t.
Ship	v. i.
Ship"board`	n.
Ship"build`er	n.
Ship"build`ing	n.
Ship"ful	n.
Ship"hold`er	n.
Ship"less	a.
Ship"let	n.
Ship"load`	n.
Ship"man	n.
Ship"mas`ter	n.
Ship"mate`	n.
Ship"ment	n.
Ship"own`er	n.
Ship"pen	n.
Ship"per	n.
Ship"ping	a.
Ship"ping	n.
Ship"ping note	n.
Ship"pon	n.
Ship railway	a.
Ship"shape`	a.
Ship"shape`	adv.
Ship"worm`	n.
Ship"wreck`	n.
Ship"wreck`	v. t.
Ship"wright`	n.
Ship"yard`	n.
Shi*raz"	n.
Shire	n.
Shire horse	v. t.
Shirk	v. i.
Shirk	n.
Shirk"er	n.
Shirk"y	a.
Shirl	a.
Shirl	n.
Shir"ley	n.
Shirr	n.
Shirred	a.
Shirt	n.
Shirt	v. t. & i.
Shirt"ing	n.
Shirt"less	a.
shirtwaist	n.
Shirt-waist suit	n.
Shit"tim	n.
Shit"tle	n.
Shit"tle	a.
Shit"tle*cock`	n.
Shit"tle*ness	n.
Shive	n.
Shiv"er	n.
Shiv"er	v. t.
Shiv"er	v. i.
Shiv"er	v. i.
Shiv"er	v. t.
Shiv"er	n.
Shiv"er*ing*ly	adv.
Shiv"er-spar`	n.
Shiv"er*y	a.
Shi*zo"ku	n. sing. & pl.
Shoad	n.
Shoad"ing	n.
Shoal	n.
Shoal	v. i.
Shoal	a.
Shoal	n.
Shoal	v. i.
Shoal	v. t.
Shoal"i*ness	n.
Shoal"ing	a.
Shoal"y	a.
Shoar	n.
Shoat	n.
Shock	n.
Shock	v. t.
Shock	v. i.
Shock	n.
Shock	v. t.
Shock	v. i.
Shock	n.
Shock	a.
Shock"dog`	n.
Shock"-head`	a.
Shock"-head`ed	a.
Shock"ing	a.
Shod	imp. & p. p.
Shod"dy	n.
Shoddy fever	a.
Shod"dy*ism	n.
Shode	n.
Shode	n.
Shoe	n.
Shoe	v. t.
Shoe"bill`	n.
Shoe"black`	n.
Shoe"fly`	n.
Shoe"horn`	n.
Shoe"horn	v. t.
Shoe"less	a.
Shoe"lace	n.
Shoe"mak`er	n.
Shoe"mak`ing	n.
Sho"er	n.
Shoe"string`	n.
Shog	n.
Shog	v. t.
Shog	v. i.
Shog"gle	v. t.
Sho"gun	n.
Sho*gun"ate	n.
Sho"la	n.
Shole	n.
Shole	n.
Shonde	n.
Shone	imp. & p. p.
Shoo	interj.
shoo-in	n.
Shook	imp.
Shook	n.
Shook	v. t.
Shoon	n.
Shoop	imp.
Shoot	n.
Shoot	v. t.
Shoot	v. i.
Shoot	n.
Shoot"er	n.
Shoot"ing	n.
Shoot"ing	a.
Shoot"y	a.
Shop	imp.
Shop	n.
Shop	v. i.
Shop"board`	n.
Shop"book`	n.
Shop"boy`	n.
Sho"pen	p. p.
Shop"girl`	n.
Shop"keep`er	n.
Shop"lift`er	n.
Shop"lift`ing	n.
Shop"like`	a.
Shop"maid`	n.
Shop"man	n.
Shop"per	n.
Shop"pish	a.
Shop"py	a.
Shop"shift`	n.
shop talk	n.
Shop"wom`an	n.
Shop"worn`	a.
Shor"age	n.
Shore	imp.
Shore	n.
Shore	n.
Shore	v. t.
Shore	n.
Shore	v. t.
Shore"less	a.
Shore"ling	n.
Shor"er	n.
Shore"ward	adv.
Shor"ing	n.
Shorl	n.
Shor"ling	n.
Shorn	p. p.
Short	a.
Short	n.
Short	adv.
Short	v. t.
Short	v. i.
Short"age	n.
Short"-breathed`	a.
Short"cake`	n.
Short" cir"cuit	v. t.
Short"clothes`	n.
Short"com`ing	n.
Short"-dat`ed	a.
Short"en	v. t.
Short"en	v. i.
Short"en*er	n.
Short"en*ing	n.
Short"hand`	n.
Short`-hand"ed	a.
Short"head`	n.
Short"horn`	a.
Short"-joint`ed	a.
Short"-lived`	a.
Short"ly	adv.
Short"ness	n.
Short"sight`ed	a.
Short"-spo`ken	a.
Short"stop`	n.
Short"-waist`ed	a.
Short"-wind`ed	a.
Short"wing`	n.
Short"-wit`ted	a.
Shor"y	a.
Sho*sho"nes	n. pl.
Shot	imp. & p. p.
Shot	a.
Shot	n.
Shot	n.
Shot	v. t.
Shot"-clog`	n.
Shote	n.
Shot"-free`	a.
Shot"-free`	a.
Shot"gun`	n.
Shot"-proof`	a.
Shots	n. pl.
Shot samples	a.
Shot"ten	n.
Shough	n.
Shough	interj.
Should	imp.
Shoul"der	n.
Shoul"der	v. t.
Shoul"der	v. i.
Shoul"dered	a.
Shoul"der-shot`ten	a.
Shout	v. i.
Shout	v. t.
Shout	n.
Shout"er	n.
Shove	v. t.
Shove	v. i.
Shove	n.
Shove	p. p.
Shove"board`	n.
Shov"el	n.
Shov"el	v. t.
Shov"el*ard	n.
Shov"el*bill`	n.
Shov"el*board`	n.
Shov"el*er	n.
Shov"el*ful	n.
Shov"el*head`	n.
Shov"el*nose`	n.
Shov"el-nosed`	a.
Shov"en	p. p.
Show	v. t.
Show	v. i.
Show	n.
Show"bread`	n.
Show"er	n.
Show"er	n.
Show"er	v. t.
Show"er	v. i.
Show"er*ful	a.
Show"er*i*ness	n.
Show"er*less	a.
Show"er*y	a.
Show"i*ly	adv.
Show"i*ness	n.
Show"ing	n.
Show"ish	a.
Show"man	n.
Shown	p. p.
Show"room`	n.
Show"y	a.
Shrag	n.
Shrag	v. t.
Shrag"ger	n.
Shram	v. t.
Shrank	imp.
Shrap	n.
Shrap"nel	a.
Shred	n.
Shred	v. t.
Shred"cook`	n.
Shred"ding	n.
Shred"dy	a.
Shred"less	a.
Shrew	a.
Shrew	n.
Shrew	v. t.
Shrewd	a.
Shrew"ish	a.
Shrew"mouse`	n.
Shriek	v. i.
Shriek	v. t.
Shriek	n.
Shriek"er	n.
Shriev"al	a.
Shriev"al*ty	n.
Shrieve	n.
Shrieve	v. t.
Shrift	n.
Shright	imp. & p. p.
Shright	n.
Shrike	n.
Shrill	a.
Shrill	n.
Shrill	v. i.
Shrill	v. t.
Shrill"-gorged`	a.
Shrill"ness	n.
Shrill"-tongued`	a.
Shril"ly	adv.
Shril"ly	a.
Shrimp	v. t.
Shrimp	n.
Shrimp"er	n.
Shrine	n.
Shrine	v. t.
Shrin"er	n.
Shrink	v. i.
Shrink	v. t.
Shrink	n.
Shrink"age	n.
Shrink"er	n.
Shrink"ing	a. & n.
Shrink"ing*ly	adv.
shrink"-pack	n.
shrink"-wrap	v. t.
shrink"-wrap	n.
Shriv"al*ty	n.
Shrive	v. t.
Shrive	v. i.
Shriv"el	v. i.
Shriv"el	v. t.
Shriv"en	p. p.
Shriv"er	n.
Shriv"ing	n.
Shroff	n.
Shroff"age	n.
Shrood	v. t.
Shrop"shire	n.
Shroud	n.
Shroud	v. t.
Shroud	v. i.
Shroud	v. t.
Shroud"ed	a.
Shroud"ing	n.
Shroud"-laid`	a.
Shroud"less	a.
Shroud"y	a.
Shrove	imp.
Shrove	v. i.
Shrove"tide`	n.
Shrov"ing	n.
Shrow	n.
Shrowd	v. t.
Shrub	n.
Shrub	n.
Shrub	v. t.
Shrub"ber*y	n.
Shrub"bi*ness	n.
Shrub"by	a.
Shrub"less	a.
Shruff	n.
Shrug	v. t.
Shrug	v. i.
shrug	n.
shrug off	v. t.
Shrunk"en	p. p. & a.
shtetl	n.
shtick	n.
Shuck	n.
Shuck	n.
Shuck	v. t.
Shuck"er	n.
Shud"der	v. i.
Shud"der	n.
Shud"der*ing*ly	adv.
Shude	n.
Shuf"fle	v. t.
Shuf"fle	v. i.
Shuf"fle	n.
Shuf"fle*board`	n.
Shuf"fle*cap`	n.
Shuf"fler	n.
Shuf"fle*wing`	n.
Shuf"fling	a.
Shuf"fling	v.
Shug	v. i.
Shu"mac	n.
Shun	v. t.
Shun"less	a.
Shunt	v. t.
Shunt	v. i.
Shunt	n.
Shunt"er	n.
Shunt"ing	p. pr. & vb. n.
Shunt valve	a.
Shut	v. t.
Shut	v. i.
Shut	a.
Shut	n.
Shute	n.
Shut"ter	n.
Shut"tered	a.
Shut"tle	n.
Shut"tle	v. i.
Shut"tle*cock`	n.
Shut"tle*cock	v. t.
Shut"tle*cork`	n.
Shut"tle*wise`	adv.
Shwan"-pan	n.
Shy	a.
Shy	v. i.
Shy	v. t.
Shy	n.
Shy"ly	adv.
Shy"ness	n.
Shy"ster	n.
Si	n.
Si*al"o*gogue	n.
Si"a*mang`	n.
Si`a*mese"	a.
Si`a*mese`	n. sing. & pl.
Sib	n.
Sib	a.
Sib"bens	n.
Si*be"ri*an	a.
Sib"i*lance	n.
Sib"i*lant	a.
Sib"i*late	v. t. & i.
Sib`i*la"tion	n.
Sib"i*la*to*ry	a.
Sib"i*lous	a.
sib"ling	n.
sib"ling	a.
Sib"yl	n.
Sib"yl*ist	n.
Sib"yl*line	a.
Sic	a.
Sic	adv.
Sic"a*more	n.
Sic"ca	n.
Sic"cate	v. t.
Sic*ca"tion	n.
Sic"ca*tive	a.
Sic*cif"ic	a.
Sic"ci*ty	n.
Sice	n.
Si"cer	n.
Sich	a.
Si*cil"i*an	a.
Si*cil"i*an	n.
Si*ci`li*a"no	n.
Si`ci`lienne"	n.
Sick	a.
Sick	n.
Sick	v. i.
Sick"-brained`	a.
Sick"en	v. t.
Sick"en	v. i.
Sick"en*ing	a.
Sick"er	v. i.
Sick"er	a.
Sick"er	adv.
Sick"er*ly	adv.
Sick"er*ness	n.
Sick"ish	a.
Sic"kle	n.
Sic"kle*bill`	n.
Sic"kled	a.
Sic"kle*man	n.
Sic"kler	n.
Sick"less	a.
Sic"kle*wort`	n.
Sick"lied	a.
Sick"li*ness	n.
Sick"ly	a.
Sick"ly	adv.
Sick"ly	v. t.
Sick"ness	n.
Si"cle	n.
Si"da	n.
Sid"dow	a.
Side	n.
Side	a.
Side	v. i.
Side	v. t.
Side"board`	n.
Side"bone`	n.
Side"-chain` the`o*ry	a.
Side"flash`	n.
Side"hill`	n.
Sideline	n.
Sideline	v. t.
Side"ling	adv.
Side"ling	a.
Side"long`	adv.
Side"long`	a.
Side"piece`	n.
Sid"er	n.
Si"der	n.
Sid"er*al	a.
Sid"er*a`ted	a.
Sid`er*a"tion	n.
Si*de"re*al	a.
Si*de"re*al*ize	v. t.
Si*de"re*ous	a.
Sid"er*ite	n.
Sid`er*o*graph"ic	a.
Sid`er*og"ra*phist	n.
Sid`er*og"ra*phy	n.
Sid"er*o*lite	n.
Sid"er*o*man`cy	n.
Sid"er*o*scope	n.
Sid`e*ro"sis	n.
Sid"er*o*stat	n.
Sid`e*rox"y*lon	n.
Side"sad`dle	n.
Side"-slip`	v. i.
Side slip	n.
Side"-tak`ing	n.
Side"track`	v. t.
Side"walk`	n.
Side"ways`	adv.
Side"-wheel`	a.
Side"wind`er	n.
Side"wise`	adv.
Sid"ing	n.
Si"dle	v. t.
Siege	n.
Siege	v. t.
Siege"work`	n.
Sie"mens-Mar`tin proc"ess	n.
Si`e*nit"ic	a.
Si*en"na	n.
Si`en*nese"	a.
Si*er"ra	n.
Si*es"ta	n.
Sieur	n.
Sie"va	n.
Sieve	n.
Si"fac	n.
Sif"fle*ment	n.
Sif"i*let	n.
Sift	v. t.
Sift"er	n.
Sig	n.
Si*gaul"ti*an	a.
Sig"ger	v. i.
Sigh	v. i.
Sigh	v. t.
Sigh	n.
Sigh"-born`	a.
Sigh"er	n.
Sigh"ing	a.
Sight	n.
Sight	v. t.
Sight	v. i.
Sight"ed	a.
Sight"ful	a.
Sight"ful*ness	n.
Sight"-hole`	n.
Sight"ing	a. & n.
Sight"less	a.
Sight"li*ness	n.
Sight"ly	a.
Sight"proof`	a.
Sight"-see`ing	a.
Sight"-see`ing	n.
Sight"-se`er	n.
Sight"-shot`	n.
Sights"man	n.
Sig"il	n.
Sig`il*la"ri*a	n. pl.
Sig`il*la"ri*a	n.
Sig`il*la"rid	n.
Sig"il*la`ted	a.
Sig"il*la*tive	a.
Si*gil"lum	n.
Sig"la	n. pl.
Sig"ma	n.
Sig"mo*dont	n.
Sig"moid	a.
Sig*moid"al*ly	adv.
Sign	n.
Sign	v. t.
Sign	v. i.
Sign"a*ble	a.
Sig"nal	n.
Sig"nal to noise" ra`ti*o	n.
Sig"nal	a.
Sig"nal	v. t.
Sig"nal*ist	n.
Sig*nal"i*ty	n.
Sig"nal*ize	v. t.
Sig"nal*ly	adv.
Sig"nal*man	n.
Sig"nal*ment	n.
Sig"nate	a.
Sig*na"tion	n.
Sig"na*to*ry	a.
Sig"na*to*ry	n.
Sig"na*ture	n.
Sig"na*ture	v. t.
Sig"na*tur`ist	n.
Sign"board`	n.
Sign"er	n.
Sig"net	n.
Sig"net*ed	a.
Sig"ni*fer	a.
Sig*nif"i*cance	n.
Sig*nif"i*cant	a.
Sig*nif"i*cant	n.
Sig*nif"i*cant*ly	adv.
Sig*nif"i*cate	n.
Sig`ni*fi*ca"tion	n.
Sig*nif"i*ca*tive	a.
Sig"ni*fi*ca`tor	n.
Sig*nif"i*ca*to*ry	a.
Sig`ni*fi*ca"vit	n.
Sig"ni*fy	v. t.
sign"ing	n.
Sign"ior	n.
Sign"ior*ize	v. t.
Sign"ior*ize	v. i.
Sign"ior*ship	n.
Sign"ior*y	n.
sign" lang`uage	n.
sign` off"	v. i.
sign` on"	v. i.
Si*gnor"	n.
Si*gno"ra	n.
Si`gno*ri"na	n.
Sign"post`	n.
Sik	a.
Sike	n.
Sike	n.
Sike	v. i.
Sike	n.
Sik"er	a. & adv.
Sikhs	n. pl.
Si"lage	n. & v.
Sile	v. t.
Sile	v. i.
Sile	n.
Sile	n.
Si"lence	n.
Si"lence	interj.
Si"lence	v. t.
Si"lenc*er	n.
Si*le"ne	n.
Si"lent	a.
Si"lent	n.
Si*len"ti*a*ry	n.
Si*len"tious	a.
Si"lent*ly	adv.
Si"lent*ness	n.
Si*le"nus	n.
Si*le"si*a	n.
Si*le"si*an	a.
Si"lex	n.
Sil`hou*ette"	n.
Sil`hou*ette"	v. t.
Sil"i*ca	n.
Sil"i*cate	n.
Sil"i*ca`ted	a.
Sil`i*ca*ti*za"tion	n.
Si*lic"e*a	n. pl.
Si*li"ceous	a.
Si*lic"ic	a.
Si*lic`i*cal*ca"re*ous	a.
Sil"i*cide	n.
Sil`i*cif"er*ous	a.
Si*lic`i*fi*ca"tion	n.
Si*lic"i*fied	a.
Si*lic"i*fy	v. t.
Si*lic"i*fy	v. i.
Sil`i*ci*oi"de*a	n. pl.
Si*li"cious	a.
Sil`i*ci*spon"gi*ae	n. pl.
Si*lic"it*ed	a.
Si*lic"i*um	n.
Si*lic"i*u*ret`ed	a.
Sil"i*cle	n.
Sil"i*co-	a.
Sil`i*co*flu"or*ide	n.
Sil`i*coi"de*a	n. pl.
Sil"i*con	n.
Sil`i*co*tung"stic	a.
Si*lic"u*la	n.
Sil"i*cule	n.
Si*lic"u*lose`	a.
Si*lig"i*nose`	a.
Sil"ing	a. & n.
Sil"i*qua	n.
Sil"ique	n.
Sil"i*qui*form	a.
Sil`i*quo"sa	n. pl.
Sil"i*quose`	a.
Silk	n.
Silk"en	a.
Silk"en	v. t.
Silk"i*ness	n.
Silk"man	n.
Silk"ness	n.
Silk"-stock`ing	a.
Silk"weed`	n.
Silk"worm`	n.
Silk"y	a.
Sill	n.
Sill	n.
Sill	n.
Sil"la*bub	n.
Sil"ler	n.
Sil"li*ly	adv.
Sil"li*man*ite	n.
Sil"li*ness	n.
Sil"lock	n.
Sil"lon	n.
Sil"ly	a.
Sil"ly*how	n.
Si"lo	n.
Silt	n.
Silt	v. t.
Silt	v. i.
Silt"y	a.
Si*lun"dum	n.
Si*lure"	n.
Si*lu"ri*an	a.
Si*lu"ri*an	n.
Si*lu"ri*dan	n.
Si*lu"roid	n.
Sil`u*roi"de*i	n. pl.
Si*lu"rus	n.
Sil"va	n.
Sil"van	a.
Sil"van	n.
Sil"van*ite	n.
Sil"vas	n. pl.
Sil"vate	n.
Sil"ver	n.
Sil"ver	a.
Sil"ver	v. t.
Sil"ver	v. i.
Sil"ver*back`	n.
Sil"ver*ber`ry	n.
Sil"ver*bill`	n.
Sil"ver*boom`	n.
Sil"ver cer*tif"i*cate	n.
Sil"ver*fish`	n.
Sil"ver-gray`	a.
Sil"ver*i*ness	n.
Sil"ver*ing	n.
Sil"ver*ite	n.
Sil"ver*ize	v. t.
Sil"ver*less	a.
Sil"ver*ling	n.
Sil"ver*ly	adv.
Sil"vern	a.
Sil"ver*sides`	n.
Sil"ver*smith`	n.
Sil"ver*spot`	n.
Silver State	n.
Sil"ver*weed`	n.
Sil"ver*y	a.
Sil"vi*cul`ture	n.
Sil"vics	n.
Si"ma	n.
Sim"a*gre	n.
Si*mar"	n.
Si`marre"	n.
Sim"i*a	n.
Sim"i*al	a.
Sim"i*an	a.
Sim"i*lar	a.
Sim"i*lar	n.
Sim`i*lar"i*ty	n.
Sim"i*lar*ly	adv.
Sim"i*lar*y	a.
Sim"i*la*tive	a.
Sim"i*le	n.
Si*mil"i*ter	n.
Si*mil"i*tude	n.
Si*mil`i*tu"di*na*ry	a.
Sim"i*lize	v. t.
Sim"i*lor	n.
Sim"i*ous	a.
Sim"i*tar	n.
Sim"mer	v. i.
Sim"mer	v. t.
Sim"nel	n.
Si*mo"ni*ac	n.
Sim`o*ni"a*cal	a.
Si*mo"ni*al	a.
Si*mo"ni*an	n.
Si*mo"ni*ous	a.
Sim"o*nist	n.
Si"mon-pure"	a.
Sim"o*ny	n.
Si*moom"	n.
Si"mous	a.
Sim"pai	n.
Sim"per	v. i.
Sim"per	n.
Sim"per*er	n.
Sim"per*ing	a. & n.
Sim"per*ing*ly	adv.
Sim"ple	a.
Sim"ple	n.
Sim"ple	v. i.
Sim"ple-heart`ed	a.
Sim"ple-mind`ed	a.
Sim"ple*ness	n.
Sim"pler	n.
Sim"pless	n.
Sim"plesse	n.
Sim"ple*ton	n.
Sim*pli"cian	n.
Sim*plic"i*ty	n.
Sim`pli*fi*ca"tion	n.
Sim"pli*fy	v. t.
Sim"plist	n.
Sim*plis"tic	a.
Sim"pli*ty	n.
Sim"plo*ce	n.
Sim"ply	adv.
Sim"u*la`cher	n.
Sim`u*la"crum	n.
Sim"u*lar	n.
Sim"u*lar	a.
Sim"u*late	a.
Sim"u*late	v. t.
Sim`u*la"tion	n.
Sim"u*la`tor	n.
Sim"u*la*to*ry	a.
Si`mul*ta*ne"i*ty	n.
Si`mul*ta"ne*ous	a.
Sim"ul*ty	n.
sim`va*stat"in	n.
Sin	adv., prep., & conj.
Sin	n.
Sin	v. i.
Si*na"ic	a.
Sin*al"bin	n.
Sin*am"ine	n.
Sin"a*pate	n.
Sin"a*pic	a.
Sin"a*pine	n.
Si*na"pis	n.
Sin"a*pis`in	n.
Sin"a*pism	n.
Sin`a*po*le"ic	a.
Si*nap"o*line	n.
Sin"ca*line	n.
Since	adv.
Since	prep.
Since	conj.
Sin*cere"	a.
Sin*cere"ly	adv.
Sin*cere"ness	n.
Sin*cer"i*ty	n.
Sinch	n.
Sinch	v. t.
Sin*cip"i*tal	a.
Sin"ci*put	n.
Sind"i	n.
Sin"don	n.
Sine	n.
Si"ne	prep.
Si"ne*cu`ral	a.
Si`ne*cure	n.
Si"ne*cure	v. t.
Si"ne*cu*rism	n.
Si"ne*cu*rist	n.
Sin"ew	n.
Sin"ew	v. t.
Sin"ewed	a.
Sin"ew*i*ness	n.
Sin"ew*ish	a.
Sin"ew*less	a.
Sin"ew*ous	a.
Sin"ew-shrunk`	a.
Sin"ew*y	a.
Sin"ful	a.
Sing	v. i.
Sing	v. t.
Singe	v. t.
Singe	n.
Sin"ger	n.
Sing"er	n.
Sing"er*ess	n.
Sin`gha*lese"	n. & a.
Sing"ing	a. & n.
Sing"ing*ly	adv.
Sin"gle	a.
Sin"gle	v. t.
Sin"gle	v. i.
Sin"gle	n.
Sin"gle-act`ing	a.
Sin"gle-breast`ed	a.
Sin"gle-foot`	n.
Sin"gle-foot`	v. i.
sin"gle-hand"ed	a.
sin"gle-hand"ed*ly	adv.
Sin"gle-heart"ed	a.
sin"gle-mind"ed	a.
sin"gle-mind"ed*ness	n.
Sin"gle*ness	n.
sin"gles	n. pl.
sin"gles	a.
Sin"gle*stick`	n.
Sin"gle-sur"faced	a.
Sin"glet	n.
Sin"gle tax`	n.
Sin"gle*tree`	n.
Sin"gly	adv.
Sing"-sing`	n.
Sing"song`	n.
Sing"song`	a.
Sing"song`	v. i.
Sing"spiel`	n.
Sing"ster	n.
Sin"gu*lar	a.
Sin"gu*lar	n.
Sin"gu*lar*ist	n.
Sin`gu*lar"i*ty	n.
Sin"gu*lar*ize	v. t.
Sin"gu*lar*ly	adv.
Sin"gult	n.
Sin*gul"tous	a.
Sin*gul"tus	n.
Sin"ic	a.
Sin"i*cal	a.
Sin"i*cism	n.
Sin"i*grin	n.
Sin"is*ter	a.
Sin"is*ter-hand"ed	a.
Sin"is*ter*ly	adv.
Sin"is*trad	adv.
Sin"is*tral	a.
Sin`is*tral"i*ty	n.
Sin"is*tral*ly	adv.
Sin"is*trin	n.
Sin`is*tror"sal	a.
Sin"is*trorse`	a.
Sin"is*trous	a.
Sin"is*trous*ly	adv.
Sink	v. i.
Sink	v. t.
Sink	n.
Sink"er	n.
Sink"ing	a. & n.
Sin"less	a.
Sin"ner	n.
Sin"ner	v. i.
Sin"ner*ess	n.
Sin"net	n.
Sin`o*log"ic*al	a.
Si*nol"o*gist	n.
Sin"o*logue	n.
Si*nol"o*gy	n.
Sin"o*per	n.
Si*no"pi*a	n.
Sin"o*pite	n.
Sin"o*ple	n.
Sin"o*ple	n.
Sinque	n.
Sins"ring	n.
Sin"ter	n.
Sin"to	n.
Sin"u*ate	a.
Sin"u*ate	v. i.
Sin"u*a`ted	a.
Sin`u*a"tion	n.
Sin"u*ose`	a.
Sin`u*os"i*ty	n.
Sin"u*ous	a.
Si`nu*pal"li*ate	a.
Si"nus	n.
Si"nus*oid	n.
Si`nus*oid"al	a.
Sio"goon	n.
Sio*goon"ate	n.
Sioux	prop. n. sing. & pl.
Sioux State	v. t.
Sip	v. i.
Sip	n.
Sip"age	n.
Sipe	v. i.
Siph"i*lis	n.
Si"phoid	n.
Si"phon	n.
Si"phon	v. t.
Si"phon*age	n.
Si"phon*al	a.
Si`pho*na"rid	n.
Si`pho*na"ta	n. pl.
Si"phon*ate	a.
Si"phon*et	n.
Si*pho"ni*a	n.
Si*pho`ni*a"ta	n. pl.
Si*phon"ic	a.
Si*phon"i*fer	n.
Si"phon*if"er*ous	a.
Si*pho"ni*um	n.
Si`pho*no*bran`chi*a"ta	n. pl.
Si`pho*no*bran"chi*ate	a.
Si`pho*nog"ly*phe	n.
Si`pho*noph"o*ra	prop. n. pl.
Si`pho*noph"o*ran	a.
Si*phon"o*phore	n.
Si`pho*nop"o*da	n. pl.
Si`pho*no*stom"a*ta	n. pl.
Si`pho*no*stom"a*tous	a.
Si`pho*nos"tome	n.
Si`pho*rhi"nal	a.
Si`pho*rhin"i*an	n.
Si"phun`cle	n.
Si"phun`cled	a.
Si*phun"cu*lar	a.
Si*phun"cu*la`ted	a.
Sip"id	a.
Sip"per	n.
Sip"pet	n.
Sip"ple	v. i.
Sip"pling	a.
Si*pun`cu*la"ce*a	n. pl.
Si*pun"cu*loid	a.
Si*pun`cu*loi"de*a	n. pl.
Si` quis"	n.
Si*ras"kier	n.
Si*ras"kier*ate	n.
Sir*bo"ni*an	a.
Sir*car"	n.
Sir*dar"	n.
Sire	n.
Sire	v. t.
Si*re"don	n.
Si"ren	n.
Si"ren	a.
Si*rene"	n.
Si*re"ni*a	n. pl.
Si*re"ni*an	n.
Si*ren"ic*al	a.
Si"ren*ize	v. i.
Si*ri"a*sis	n.
Sir"i*us	n.
Sir"keer	n.
Sir"loin`	n.
Sir"name`	n.
Si"roc	n.
Si*roc"co	n.
Sir"rah	n.
Sirt	n.
Sir"up	n.
Sir"uped	a.
Sir"up*y	a.
Sir`vente"	n.
Sis	n.
Sis	n.
Si*sal" grass`	n.
Sise	n.
Sise	n.
Sis"el	n.
Si"ser	n.
Sis"e*ra*ra	n.
Sis"kin	n.
Sis"ki*wit	n.
Sis"mo*graph	n.
Sis*mom"e*ter	n.
Siss	v. i.
Siss	n.
Sis*soo"	n.
Sist	v. t.
Sist	n.
Sis"ter	n.
Sis"ter	v. t.
Sis"ter*hood	n.
Sis"ter*ing	a.
Sis"ter-in-law`	n.
Sis"ter*ly	a.
Sis"tine	a.
Sis"tren	n. pl.
Sis"trum	a.
Sis"y*phus	n.
Sit	obs. 3d pers. sing. pres.
Sit	v. i.
Sit	v. t.
Site	n.
Sit"ed	a.
Sit"fast`	a.
Sit"fast`	n.
Sith	prep., adv., & conj.
Sith	n.
Sithe	v. i.
Sithe	n.
Sithe	v. t.
Sithed	a.
Sithe"man	n.
Sith"en	adv. & conj.
Sith"ence	adv. & conj.
Sith"then	adv. & conj.
Si*tol"o*gy	n.
Si`to*pho"bi*a	n.
Sit"ten	p. p.
Sit"ter	n.
Sit"tine	a.
Sit"ting	a.
Sit"ting	n.
Sit"u*ate	a.
Sit"u*ate	v. t.
Sit`u*a"tion	n.
Si"tus	n.
Sitz" bath`	n.
Si"van	n.
Siv`a*the"ri*um	n.
Siv"er	v. i.
Siv"vens	n.
Si"win	n.
Six	a.
Six	n.
Six"fold`	a.
Six"-foot`er	n.
Six"pence	n.
Six"pen`ny	a.
Six"score`	a. & n.
Six"-shoot`er	n.
Six"teen`	a.
Six"teen`	n.
Six*teen"mo	n.
Six"teenth`	a.
Six"teenth`	n.
Sixth	a.
Sixth	n.
Sixth"ly	adv.
Six"ti*eth	a.
Six"ti*eth	n.
Six"ty	a.
Six"ty	n.
Six`ty-fourth"	a.
Siz"a*ble	a.
Si"zar	n.
Si"zar*ship	n.
Size	n.
Size	n.
Size	v. t.
Size	n.
Size	v. t.
Size	v. i.
Sized	a.
Si"zel	n.
Siz"er	n.
Siz"i*ness	n.
Siz"ing	n.
Siz"ing	n.
Siz"y	a.
Siz"zle	v. i.
Siz"zle	n.
Siz"zling	a. & n.
Skad"dle	n.
Skad"dle	a.
Skad"don	n.
Skag	n.
Skain	n.
Skain	n.
Skains"mate`	n.
Skaith	n.
Skald	n.
Skald"ic	a.
Skall	v. t.
Skar	a.
Skart	n.
Skat	n.
Skate	n.
Skate	v. i.
Skate	n.
Skat"er	n.
Ska"tol	n.
Skayles	n.
Skean	n.
Ske*dad"dle	v. i.
Skee	n.
Skeed	n.
Skeel	n.
Skeel"duck`	n.
Skeet	n.
Skeg	n.
Skeg"ger	n.
Skein	n.
Skein	n.
Skeine	n.
Skel"der	v. t. & i.
Skel"der	n.
Skel"drake`	n.
Skel"et	n.
Skel"e*tal	a.
Skel`e*tog"e*nous	a.
Skel`e*tol"o*gy	n.
Skel"e*ton	n.
Skel"e*ton	a.
Skel"e*ton*ize	v. t.
Skel"e*ton*i`zer	n.
Skel"lum	n.
Skel"ly	v. i.
Skel"ly	n.
Skelp	n.
Skelp	v. t.
Skelp	n.
Skel"ter	v. i.
Sken	v. i.
Skene	n.
Skep	n.
Skep"tic	n.
Skep"tic	a.
Skep"ti*cism	n.
Skep"ti*cize	v. i.
Sker"ry	n.
Sketch	n.
Sketch	v. t.
Sketch	v. i.
Sketch"book`	n.
Sketch"er	n.
Sketch"i*ly	adv.
Sketch"i*ness	n.
Sketch"y	a.
Skew	adv.
Skew	a.
Skew	n.
Skew	v. i.
Skew	v. t.
Skew"bald`	a.
Skew"er	n.
Skew"er	v. t.
Ski	n.
Ski"a*graph	n.
Ski"a*scope	n.
Skid	n.
Skid	v. t.
Skid	v. i.
Skid"daw`	n.
Skid"der	n.
Skid"pan`	n.
Skid road	imp. & p. p.
Skied	imp. & p. p.
Ski"ey	a.
Skiff	n.
Skiff	v. t.
Skif"fling	n.
Skil"der	v. i.
Skil"ful	a.
Skill	n.
Skill	v. t.
Skill	v. i.
Skilled	a.
Skil"let	n.
Skill"ful	a.
Skil`li*ga*lee"	n.
Skil"ling	n.
Skil"ling	n.
Skill"-less	a.
Skilts	n. pl.
Skil"ty	n.
Skim	v. t.
Skim	v. i.
Skim	a.
Srim	n.
Skim"back`	n.
Skim"ble-scam`ble	a.
Skim"i*try	n.
Skim"mer	n.
Skim"mer*ton	n.
Skim"ming	n.
Skim"ming*ly	adv.
Skim"ming*ton	n.
Skimp	v. t.
Skimp	v. i.
Skimp	a.
Skin	n.
Skin	v. t.
Skin	v. i.
Skin"bound`	a.
Skinch	v. t. & i.
Skin"-deep`	a.
Skin"flint`	n.
Skin"ful	n.
Skink	n.
Skink	v. t.
Skink	v. i.
Skink	n.
Skink"er	n.
Skin"less	a.
Skin"ner	n.
Skin"ni*ness	n.
Skin"ny	a.
Skip	n.
Skip	v. i.
Skip	v. t.
Skip	n.
Skip"jack`	n.
Skip"per	n.
Skip"per	n.
Skip"pet	n.
Skip"ping*ly	adv.
Skirl	v. t. & i.
Skirl	n.
Skirl"cock`	n.
Skirl"crake`	n.
Skirl"ing	n.
Skirl"ing	n.
Skir"mish	v. i.
Skir"mish	n.
Skir"mish*er	n.
Skirr	v. t.
Skirr	v. i.
Skirr	n.
Skir"ret	n.
Skir"rhus	n.
Skirt	n.
Skirt	v. t.
Skirt	v. t.
Skirt"ing	n.
Skit	v. t.
Skit	n.
Skit"ter	v. t.
Skit"ter	v. i.
Skit"tish	a.
Skit"tle	a.
Skit"tle-dog`	n.
Skit"tles	n. pl.
Skit"ty	n.
Skive	n.
Skive	v. t.
Skiv"er	n.
Ski"ving	n.
Sklayre	n.
Sklere	v. t.
Skol"e*cite	n.
Skonce	n.
Skop"je	prop. n.
Skop"ster	n.
Skop*tsy"	n. pl.
Skor"o*dite	n.
Skout	n.
Sko"witz	n.
Skreen	n. & v.
Skrike	v. i. & t.
Skrike	n.
Skrim"mage	n.
Skrimp	v. t.
Skringe	v. i.
Skrite	n.
Sku"a	n.
Skue	a. & n.
Skulk	v. i.
Skulk	n.
Skulk	n.
Skulk"ing*ly	adv.
Skull	n.
Skull	n.
Skull"cap`	n.
Skull"fish`	n.
Skul"pin	n.
Skun	n. & v.
Skunk	n.
Skunk	v. t.
Skunk"ball`	n.
Skunk"head`	n.
Skunk"ish	a.
Skunk"top`	n.
Skunk"weed`	n.
Skur"ry	n. & v.
Skute	n.
Skut"ter*ud*ite	n.
Sky	n.
Sky	v. t.
Sky"-blue	a.
Skyed	a.
Skye" ter"ri*er	a.
Sky"-high`	adv. & a.
Sky"ish	a.
Sky"lark`	n.
Sky"lark"ing	n.
Sky"light`	n.
Sky"man	n.
Sky pilot	n.
sky"rock`et	v. i.
Sky"sail	n.
Sky"scrap`er	n.
Sky"ward	a. & adv.
Slab	n.
Slab	a.
Slab	n.
Slab"ber	v. i.
Slab"ber	v. t.
Slab"ber	n.
Slab"ber	n.
Slab"ber*er	n.
Slab"ber*y	a.
Slab"bi*ness	n.
Slab"bing	a.
Slab"by	a.
Slab"-sid`ed	a.
Slack	n.
Slack	n.
Slack	a.
Slack	adv.
Slack	n.
Slack	v. i.
Slack	v. t.
Slack"en	n.
Slack"ly	adv.
Slack"ness	n.
Slade	n.
Slag	n.
Slag	v. i. & t.
Slag"gy	a.
Slaie	n.
Slake	v. t.
Slake	v. i.
Slake"less	a.
Slak"in	n.
Slam	v. t.
Slam	v. i.
Slam	n.
Slam"-bang`	adv.
Slam"kin	n.
Slan"der	n.
Slan"der	v. t.
Slan"der*er	n.
Slan"der*ous	a.
Slang	imp.
Slang	n.
Slang	n.
Slang	n.
Slang	v. t.
Slang"i*ness	n.
Slan"gous	a.
Slang"-whang`er	n.
Slang"y	a.
Slank	imp. & p. p.
Slant	v. i.
Slant	v. t.
Slant	n.
Slant	a.
Slant"ing	a.
Slant"wise`	adv.
Slap	n.
Slap	v. t.
Slap	adv.
Slap"dash`	adv.
Slap"dash`	v. t.
Slape	a.
Slape"face`	n.
Slap"jack`	n.
Slap"per	n.
Slap"per	a.
Slash	v. t.
Slash	v. i.
Slash	n.
Slashed	a.
Slash"er	n.
Slash" pine"	a.
Slat	n.
Slat	v. t.
Slatch	n.
Slate	n.
Slate	v. t.
Slate	v. t.
Slate"-col`or	a.
Slat"er	n.
Slat"er	n.
Slat"ing	n.
Slatt	n.
Slat"ter	v. i.
Slat"tern	n.
Slat"tern	a.
Slat"tern	v. t.
Slat"tern*li*ness	n.
Slat"tern*ly	a.
Slat"ter*pouch`	n.
Slat"ting	n.
Slat"y	a.
Slaugh"ter	n.
Slaugh"ter	v. t.
Slaugh"ter*er	n.
Slaugh"ter*house`	n.
Slaugh"ter*man	n.
Slaugh"ter*ous	a.
Slav	n.
Slave	n.
Slave	n.
Slave	v. i.
Slave	v. t.
Slave"born`	a.
Slave"hold`er	n.
Slave"hold`ing	a.
Slave*oc"ra*cy	n.
Slav"er	n.
Slav"er	v. i.
Slav"er	v. t.
Slav"er	n.
Slav"er*er	n.
Slav"er*ing	a.
Slav"er*y	n.
Slav"ey	n.
Slav"ic	a.
Slav"ish	a.
Slav"ism	n.
Slav*oc"ra*cy	n.
Sla*vo"ni*an	a.
Sla*vo"ni*an	n.
Slav"o*phil	n.
Slaw	n.
Slaw	p. p.
Slay	v. t.
Slay"er	n.
Sla"zy	a.
Sle	v. t.
Sleave	n.
Sleave	v. t.
Sleaved	a.
Slea"zi*ness	n.
Slea"zy	a.
Sled	n.
Sled	v. t.
Sled"ding	n.
Sledge	n.
Sledge	v. i. & t.
Sledge	n.
Slee	v. t.
Sleek	a.
Sleek	adv.
Sleek	n.
Sleek	v. t.
Sleek"ly	adv.
Sleek"ness	n.
Sleek"y	a.
Sleep	imp.
Sleep	v. i.
Sleep	v. t.
Sleep	n.
Sleep"-at-noon"	n.
Sleep"-charged`	a.
Sleep"er	n.
Sleep"er	n.
Sleep"ful	a.
Sleep"i*ly	adv.
Sleep"i*ness	n.
Sleep"ing	a. & n.
Sleep"ish	a.
Sleep"less	a.
Sleep"mark`en	n.
Sleep"wak`er	n.
Sleep"wak`ing	n.
Sleep"walk`er	n.
Sleep"walk`ing	n.
Sleep"y	a.
Sleep"y*head`	n.
Sle"er	n.
Sleet	n.
Sleet	n.
Sleet	v. i.
Sleetch	n.
Sleet"i*ness	n.
Sleet"y	a.
Sleeve	n.
Sleeve	n.
Sleeve	v. t.
Sleeved	a.
Sleeve"fish`	n.
Sleeve"hand`	n.
Sleeve"less	a.
Sleid	v. t.
Sleigh	a.
Sleigh	n.
Sleigh"ing	n.
Sleight	n.
Sleight"ful	a.
Sleight"ly	adv.
Sleight"y	a.
Slen"der	a.
Slent	n. & v.
Slep	imp.
Sle*pez"	n.
Slept	imp. & p. p.
Sleuth	n.
Sleuth"hound`	n.
Slew	imp.
Slew	v. t.
Slew	n.
Slewed	a.
Slewth	n.
Sley	n.
Sley	v. t.
Slib"ber	a.
Slice	n.
Slice	v. t.
Sli"cer	n.
Slich	n.
Slick	a.
Slick	v. t.
Slick	n.
Slick	n.
Slick"en	a.
Slick"ens	n.
Slick"en*sides`	n.
Slick"er	n.
Slick"er	n.
Slick"ing	n.
Slick"ness	n.
Slid	imp. & p. p.
Slid"den	p. p.
Slid"der	v. t.
Slid"der	a.
Slide	v. t.
Slide	v. t.
Slide	n.
Slide"groat	n.
Slid"er	a.
Slid"er	n.
Slide" rule`	n.
Slide"way`	n.
Slid"ing	a.
Sli*dom"e*ter	n.
Slight	n.
Slight	v. t.
Slight	a.
Slight	v. t.
Slight	n.
Slight	adv.
Slight"en	v. t.
Slight"er	n.
Slight"ful	a.
Slight"ing	a.
Slight"ing*ly	adv.
Slight"ly	adv.
Slight"ness	n.
Slight"y	a.
Slik	a.
Slik"en*sides`	n.
Sli"ly	adv.
Slim	a.
Slime	n.
Slime	v. t.
slime mold	n.
Slim"i*ly	adv.
Slim"i*ness	n.
Slim"ly	adv.
Slim"ness	n.
Slim"sy	a.
Slim"y	a.
Sli"ness	n.
Sling	n.
Sling	v. t.
Sling	n.
Sling"er	n.
slinger ring	n.
Slink	v. t.
Slink	v. t.
Slink	a.
Slink	n.
Slink"y	a.
Slip	v. i.
Slip	v. t.
Slip	n.
Slip"board`	n.
slip carriage	n.
slip clutch	n.
Slip"coat` cheese"	n. pl.
slip-joint pliers	n.
Slip"knot`	n.
slip of the tongue	n.
Slip"-on`	n.
Slip"page	n.
Slip"per	n.
Slip"per	a.
Slip"pered	a.
Slip"per*i*ly	adv.
Slip"per*i*ness	n.
Slip"per*ness	n.
slipper orchid	n.
Slip"per*wort`	n.
Slip"per*y	a.
Slip"pi*ness	n.
Slip"py	a.
slip ring	n.
slip road	n.
Slip"shod`	a.
Slip"shoe`	n.
Slip"skin`	a.
Slip"slop`	n.
slip stitch	n.
Slip"string`	n.
Slip"thrift`	n.
Slish	n.
Slit	3d. pers. sing. pres.
Slit	v. t.
Slit	n.
slith"er	v. i.
slit"-shell`	n.
slit"ter	n.
slit"ting	a. & n.
Slive	v. i.
Slive	v. t.
sliv"er	v. t.
Sliv"er	n.
sloak"an	n.
sloam	n.
sloat	n.
Slob"ber	v. t. & i.
Slob"ber	n.
Slob"ber*er	n.
Slob"ber*y	a.
Slock	v. t.
Slock"ing	a. & n.
Sloe	n.
Slog	v. t. & i.
Slog	v. i.
Slog"ger	n.
Slo"gan	n.
slog"gy	a.
sloke	n.
sloo	n.
Sloom	n.
Sloom"y	a.
Sloop	n.
Slop	n.
Slop	v. t.
Slop	v. i.
Slop	n.
Slope	n.
Slope	a.
Slope	adv.
Slope	v. t.
Slope	v. i.
Slope"ness	n.
Slope"wise`	adv.
Slop"ing	a.
Slop"pi*ness	n.
Slop"py	a.
Slop"sell`er	n.
Slop"shop`	n.
Slop"work`	n.
Slop"y	a.
Slosh	n.
Slot	v. t.
Slot	n.
Sloth	n.
Sloth	v. i.
Sloth"ful	a.
Sloth"hound`	n.
Slot" ma*chine"	a.
Slot"ting	n.
Slouch	n.
Slouch	v. i.
Slouch	v. t.
Slouch"ing	a.
Slouch"y	a.
Slough	a.
Slough	n.
Slough	imp.
Slough	n.
Slough	v. i.
Slough	v. t.
Slough"ing	n.
Slough"y	a.
Slough"y	a.
Slov"en	n.
Slov"en*li*ness	n.
Slov"en*ly	a.
Slov"en*ly	adv.
Slov"en*ness	n.
Slov"en*ry	n.
Slow	imp.
Slow	a.
Slow	adv.
Slow	v. t.
Slow	v. i.
Slow	n.
Slow"back`	n.
Slowh	imp.
Slow"hound`	n.
Slow"ly	adv.
Slow"ness	n.
Slows	n.
Slow"-wit`ted	a.
Slow"worm`	n.
Sloyd	n.
Slub	n.
Slub	v. t.
Slub"ber	v. t.
Slub"ber	n.
Slub"ber*de*gul`lion	n.
Slub"ber*ing*ly	adv.
Slub"bing	a. & n.
Sludge	n.
Sludge acid	n.
Slud"ger	n.
Slud"y	a.
Slue	v. t.
Slue	v. i.
Slue	n.
Slug	n.
Slug	v. i.
Slug	v. t.
Slug	v. t.
Slug	v. i.
Slug"a*bed`	n.
Slug"gard	n.
Slug"gard	a.
Slug"gard*ize	v. t.
Slug"gard*y	n.
Slug"ger	n.
Slug"ging match	a.
Slug"gy	a.
Slug"-horn`	a.
Slugs	n. pl.
Slug"worm`	n.
Sluice	n.
Sluice	v. t.
Sluice"way`	n.
Slui`cy	a.
Slum	n.
Slum	v. i.
Slum"ber	v. i.
Slum"ber	v. t.
Slum"ber	n.
Slum"ber*er	n.
Slum"ber*ing*ly	adv.
Slum"ber*less	a.
Slum"ber*ous	a.
Slum"ber*y	a.
Slum"brous	a.
Slum"gum`	n.
Slum"ming	vb. n.
Slump	n.
Slump	v. t.
Slump	v. i.
Slump	n.
Slump"y	a.
Slung	imp. & p. p.
Slunk	imp. & p. p.
Slur	v. t.
Slur	n.
Slurred	a.
Slush	n.
Slush	v. t.
Slush"y	a.
Slut	n.
Slutch	n.
Slutch"y	a.
Sluth"hound`	n.
Slut"ter*y	n.
Slut"tish	a.
Sly	a.
Sly	adv.
Sly"boots`	n.
Sly"ly	adv.
Sly"ness	n.
Slype	n.
Smack	n.
Smack	n.
Smack	adv.
Smack	v. i.
Smack	v. t.
Smack	n.
Smack"ing	n.
Smack"ing	a.
Small	a.
Small	adv.
Small	n.
Small	v. t.
Small"age	n.
Small"clothes`	n. pl.
Small"ish	a.
Small"ness	n.
Small"pox`	n.
Smalls	n. pl.
Small"sword`	n.
Smal"ly	adv.
Smalt	n.
Smalt"-blue`	a.
Smalt"ine	n.
Smar"agd	n.
Sma*rag"dine	a.
Sma*rag"dite	n.
Smart	v. i.
Smart	v. t.
Smart	n.
Smart	a.
Smart"en	v. t.
Smar"tle	v. i.
Smart"ly	adv.
Smart"ness	n.
Smart"weed`	n.
Smash	v. t.
Smash	v. i.
Smash	n.
Smash"er	n.
Smatch	n.
Smatch	v. i.
Smat"ter	v. i.
Smat"ter	v. t.
Smat"ter	n.
Smat"ter*er	n.
Smat"ter*ing	n.
Smear	v. t.
Smear	n.
Smear"case`	n.
Smear" dab"	a.
Smear"y	a.
Smeath	n.
Smec"tite	n.
Smee	n.
Smeeth	v. t.
Smeeth	v. t.
Smeg"ma	n.
Smeg*mat"ic	a.
Smeir	n.
Smell	v. t.
Smell	v. i.
Smell	n.
Smell"er	n.
Smell"-feast`	n.
Smell"ing	n.
Smell"ing salts	a.
Smelt	imp. & p. p.
Smelt	n.
Smelt	v. t.
Smelt"er	n.
Smelt"er*y	n.
Smelt"ie	n.
Smelt"ing	a. & n.
Smerk	n. & v.
Smerk	a.
Smer"lin	n.
Smew	n.
Smick"er	v. i.
Smick"er	a.
Smick"er*ing	n.
Smick"et	n.
Smick"ly	adv.
Smid"dy	n.
Smift	n.
Smight	v. t.
Smil"a*cin	n.
Smi"lax	n.
Smile	v. i.
Smile	v. t.
Smile	n.
Smile"less	a.
Smil"er	n.
Smil"et	n.
Smil"ing*ly	adv.
Smil"ing*ness	n.
Smi"lo*don	n.
Smilt	v. i.
Smin*thu"rid	n.
Smirch	v. t.
Smirch	n.
Smirk	v. i.
Smirk	n.
Smirk	a.
Smirk"ing*ly	adv.
Smirk"y	a.
Smit	imp. & p. p.
Smit	3d. pers. sing. pres.
Smite	v. t.
Smite	v. i.
Smite	n.
Smit"er	n.
Smith	n.
Smith	v. t.
Smith"craft`	n.
Smith"er	n.
Smith`er*eens"	n. pl.
Smith"er*y	n.
Smith"ing	n.
Smith*so"ni*an	a.
Smith"son*ite	n.
Smith"y	n.
Smitt	n.
Smit"ten	p. p.
Smit"tle	v. t.
Smit"tle	n.
Smit"tle	a.
Smock	n.
Smock	a.
Smock	v. t.
Smock"-faced`	a.
Smock" frock`	a.
Smok"a*ble	a.
Smoke	n.
Smoke	v. i.
Smoke	v. t.
Smoke ball	v. t.
Smoke"house`	n.
Smoke"jack`	n.
Smoke"less	a.
Smoke"less pow"der	v. t.
Smok"er	n.
Smoke"stack`	n.
Smok"i*ly	adv.
Smok"i*ness	n.
Smok"ing	a. & n.
smok"ing gun`	n.
Smok"y	a.
Smol"der	v. i.
Smol"der	v. t.
Smol"der	n.
Smol"der*ing	a.
Smol"der*ing*ness	n.
Smol"dry	a.
Smolt	n.
Smooch	v. t.
Smoor	v. t.
Smooth	a.
Smooth	adv.
Smooth	n.
Smooth	v. t.
Smooth	v. i.
Smooth"bore`	a.
Smooth"-chinned`	a.
Smooth"en	v. t.
Smooth"er	n.
Smooth"ing	a. & n.
Smooth"ly	adv.
Smooth"ness	n.
Smooth"-spo`ken	a.
Smooth"-tongued`	a.
Smore	v. t.
Smor*zan"do	a.
Smote	imp. (<and/ rare p. p.)
Smo"ter*lich	a.
Smoth"er	v. t.
Smoth"er	v. i.
Smoth"er	n.
Smoth"ered mate	n.
Smoth"er*ing*ly	adv.
Smoth"er*y	a.
Smouch	v. t.
Smouch	v. t.
Smouch	n.
Smoul"der	v. i.
Smoul"dry	a.
Smudge	n.
Smudge	v. t.
Smudg"i*ness	n.
Smug	a.
Smug	v. t.
Smug"gle	v. t.
Smug"gle	v. i.
Smug"gler	n.
Smug"ly	adv.
Smug"ness	n.
Smut	n.
Smut	v. t.
Smut	v. i.
Smutch	n.
Smutch	v. t.
Smutch"in	n.
Smut"ty	a.
Smyr"ni*ot	a.
Snack	n.
Snack"et	n.
Snac"ot	n.
Snaf"fle	n.
Snaf"fle	v. t.
Snag	n.
Snag	v. t.
Snag"ged	a.
Snag"gy	a.
Snail	n.
Snail"fish`	n.
Snail"-like`	a.
Snail"-like`	adv.
Snail"-paced`	a.
'Snails	interj.
Snake	n.
Snake	v. t.
Snake	v. i.
Snake"bird`	n.
Snake"fish`	n.
Snake"head`	n.
Snake"neck`	n.
Snake"root`	n.
Snake's"-head`	n.
Snake"stone`	n.
Snake's-tongue`	n.
Snake"weed`	n.
Snake"wood`	n.
Snak"ish	a.
Snak"y	a.
Snap	v. t.
Snap	v. i.
Snap	n.
Snap	a.
Snap"drag`on	n.
Snape	v. t.
Snap"hance`	n.
Snap"head`	n.
Snap"per	n.
Snap"ping	a. & n.
Snap"pish	a.
Snap"py	a.
Snap"sack`	n.
Snap"shot`	n.
Snap"weed`	n.
Snar	v. i.
Snare	n.
Snare	v. t.
Snar"er	n.
Snarl	v. t.
Snarl	v. t.
Snarl	n.
Snarl	v. i.
Snarl	n.
Snarl"er	n.
Snarl"er	n.
Snarl"ing	a. & n.
Snar"y	a.
Snast	n.
Snatch	v. t.
Snatch	v. i.
Snatch	n.
Snatch block	n.
Snatch"ing*ly	adv.
Snath	n.
Snathe	v. t.
Snat"tock	n.
Snaw	n.
Snead	n.
Sneak	v. i.
Sneak	v. t.
Sneak	n.
Sneak"-cup`	n.
Sneak current	n.
Sneak"i*ness	n.
Sneak"ing	a.
Sneaks"by	n.
Sneak"y	n.
Sneap	v. t.
Sneap	n.
Sneath	n.
Sneb	v. t.
Sneck	v. t.
Sneck	n.
Sneck"et	n.
Sned	v. t.
Sned	n.
Sneer	v. i.
Sneer	v. t.
Sneer	n.
Sneer"er	n.
Sneer"ful	a.
Sneer"ing*ly	adv.
Sneeze	v. i.
Sneeze	n.
Sneeze"weed`	n.
Sneeze"wood`	n.
Sneeze"wort`	n.
Sneez"ing	n.
Snell	a.
Snell	n.
Snet	n.
Snet	v. t.
Snew	v. i.
Snib	v. t.
Snib	n.
Snick	n.
Snick	v. t.
Snick	n. & v. t.
Snick"er	v. i.
Snick"er	n.
Snide	a.
Sni"der ri"fle	n.
Sniff	v. i.
Sniff	v. t.
Sniff	n.
Sniff"ing	n.
Snif"fle	v. i.
Snift	v. i.
Snift	n.
Snift"ing	a. & n.
Snig	v. t.
Snig	v. i.
Snig	n.
Snig"ger	v. i.
Snig"ger	n.
Snig"gle	v. i.
Snig"gle	v. t.
Snip	v. t.
Snip	n.
Snipe	n.
Snipe	v. i.
Snipe	v. t.
Snipe"bill`	n.
Snipe"fish`	n.
Snip"pack	n.
Snip"per	n.
Snip"per-snap`er	n.
Snip"pet	n.
Snip"pet*y	a.
Snip"-snap`	n.
Snip"-snap`	a.
Snip"y	a.
Snite	n.
Snite	v. t.
Snithe	a.
Sniv"el	v. i.
Sniv"el	n.
Sniv"el*er	n.
Sniv"el*y	a.
Snob	n.
Snob"ber*y	n.
Snob"bish	a.
Snob"bish*ness	n.
Snob"bism	n.
Snob"by	a.
Snob"ling	n.
Snob*oc"ra*cy	n.
Snod	n.
Snod	a.
Snoff	n.
Snood	n.
Snood	v. t.
Snood"ed	a.
Snook	v. i.
Snook	n.
Snooze	n.
Snooze	v. i.
Snore	v. i.
Snore	n.
Snor"er	n.
Snor"ing	n.
Snort	v. i.
Snort	n.
Snort	v. t.
Snort"er	n.
Snot	n.
Snot	v. t.
Snot"ter	v. i.
Snot"ter	n.
Snot"ter*y	n.
Snot"ty	a.
Snout	n.
Snout	v. t.
Snout"y	a.
Snow	n.
Snow	n.
Snow	v. i.
Snow	v. t.
Snow"ball`	n.
Snow"ball`	v. t.
Snow"ball`	v. i.
Snow banner	n.
Snow"bird	n.
Snow"-blind`	a.
Snow"-bound`	a.
Snow"-broth`	n.
Snow"cap`	n.
Snow"-capped`	a.
Snow"drift`	n.
Snow"drop`	n.
Snow"flake`	n.
Snow"fleck`	n.
Snowl	n.
Snow"less	a.
Snow"plow`	n.
Snow"shed	n.
Snow"shoe`	n.
Snow"shoe`ing	n.
Snow"sho`er	n.
Snow"slip`	n.
Snow"storm`	n.
Snow"-white`	a.
Snow"y	a.
Snub	v. i.
Snub	v. t.
Snub	n.
Snub"-nosed`	a.
Snudge	v. i.
Snudge	n.
Snuff	n.
Snuff	v. t.
Snuff	v. t.
Snuff	v. i.
Snuff	n.
Snuff"box`	n.
Snuff"er	n.
Snuff"ers	n. pl.
Snuff"ing*ly	adv.
Snuf"fle	v. i.
Snuf"fle	n.
Snuf"fler	n.
Snuff"y	a.
Snug	a.
Snug	n.
Snug	v. i.
Snug	v. t.
Snug"ger*y	n.
Snug"gle	v. t.
Snug"ly	adv.
Snug"ness	n.
Sny	n.
Sny"ing	n.
So	adv.
So	conj.
So	interj.
Soak	v. t.
Soak	v. i.
Soak"age	n.
Soak"er	n.
Soak"ing	a.
Soak"y	a.
Soal	n.
Soal	n.
Soam	n.
Soap	n.
Soap	v. t.
Soap"ber`ry tree`	n.
Soap"i*ness	n.
Soap"root`	n.
Soap"stone`	n.
Soap"suds`	n. pl.
Soap"wort`	n.
Soap"y	a.
Soar	v. i.
Soar	n.
Soar	a.
Soar	a.
Soar"ing	a. & n.
So*a"ve	a.
So*a`ve*men"te	adv.
Sob	v. t.
Sob	v. i.
Sob	n.
Sob"bing	n.
Sober	a.
So"ber	v. t.
So"ber	v. i.
So"ber*ize	v. t. & i.
So"ber*ly	adv.
So"ber*ly	a.
So"ber-mind`ed	a.
So"ber*ness	n.
Sob"o*les	n.
Sob`o*lif"er*ous	a.
So*bran"je	n.
So*bri"e*ty	n.
So`bri`quet"	n.
Soc	n.
Soc"age	n.
Soc"a*ger	n.
So"-called`	a.
So`cia*bil"i*ty	n.
So"cia*ble	a.
So"cia*ble	n.
So"cia*ble*ness	n.
So"cia*bly	adv.
So"cial	a.
So"cial*ism	n.
So"cial*ist	n.
So"cial*ist	a.
So`ci*al"i*ty	n.
So"cial*ize	v. t.
So"cial*ly	adv.
So"cial*ness	n.
So"ci*ate	a.
So"ci*ate	n.
So"ci*ate	v. i.
So*ci`e*ta"ri*an	a.
So*ci"e*ta*ry	a.
So*ci"e*ty	n.
So*cin"i*an	a.
So*cin"i*an	n.
So*cin"i*an*ism	n.
So*cin"i*an*ize	v. t.
So`ci*o*log"ic	a.
So`ci*ol"o*gist	n.
So`ci*ol"o*gy	n.
Sock	n.
Sock	n.
Sock	v. t.
Sock away	v. t.
Sock in	v. t.
Sock*dol"a*ger	n.
Sock"et	n.
Sock"et*ed	a.
Sock"less	a.
Sock"y	a.
So"cle	n.
Soc"man	n.
Soc"man*ry	n.
Soc"ome	n.
Soc"o*trine	a.
So*crat"ic	a.
So*crat"ic*al*ly	adv.
Soc"ra*tism	n.
Soc"ra*tist	n.
Sod	n.
Sod	imp.
Sod	n.
Sod	v. t.
So"da	n.
So"da biscuit	n.
So"da bread	n.
So"da foun`tain	n.
So*da"ic	a.
So"da jerk	n.
So"da*lite	n.
So*dal"i*ty	n.
Sod*am"ide	n.
So"da wat`er	n.
So"da pop	n.
Sod"den	a.
Sod"den	v. i.
Sod"den	v. t.
Sod"den-wit`ted	a.
Sod"dy	a.
Sod"er	n. & v. t.
So"dger	n. & v. i.
So"dic	a.
So"di*o-	n.
Sodium bicarbonate	n.
Sod`om*it"ic*al	a.
Sod"om*y	n.
Soe	n.
So*ev"er	n.
Sof"fit	n.
So"fi	n.
So"fism	n.
Soft	a.
Soft	n.
Soft	adv.
Soft	interj.
Sof"ta	n.
Sof"ten	v. t.
Sof"ten	v. i.
Sof"ten*er	n.
Sof"ten*ing	a. & n.
Soft"-finned`	a.
Soft"-head`ed	a.
Soft"-heart`ed	a.
Soft"ish	a.
Soft"ling	n.
Soft"ly	adv.
Soft"ner	n.
Soft"ness	n.
Soft"-shell`	a.
Soft"-spo`ken	a.
Soft steel	n. & v. i.
Sog"gi*ness	n.
Sog"gy	a.
So*ho"	interj.
Soi`-di*sant"	a.
Soil	v. t.
Soil	n.
Soil	v. t.
Soil	n.
Soil	v. t.
Soil	v. i.
Soil	n.
Soil"i*ness	n.
Soil"less	a.
Soil pipe	n.
Soil"y	a.
Soi`ree"	n.
So"ja	n.
So"jer	n. & v. i.
So"journ	v. i.
So"journ	n.
So"journ*er	n.
So"journ*ing	n.
So"journ*ment	n.
Soke	n.
Soke"man	n.
Soke"man*ry	n.
Sok"en	n.
So"ko	n.
Sol	n.
Sol	n.
Sol	n.
Sol	n.
So"la	a.
So"la	n.
Sol"ace	n.
Sol"ace	v. t.
Sol"ace	v. i.
Sol"ace*ment	n.
So*la"cious	a.
Sol`a*na"ceous	a.
So"land	n.
So*lan"der	n.
So"lan goose`	n.
So*lan"i*cine	n.
So*lan"i*dine	n.
Sol"a*nine	n.
So*la"no	a.
So*la"num	prop. n.
So"lar	n.
So"lar	a.
So*la"ri*um	n.
So`lar*i*za"tion	n.
So"lar*ize	v. t.
So"lar*ize	v. i.
So"lar myth	a.
Sol"as	n.
So*la"ti*um	n.
Sold	imp. & p. p.
Sold	n.
Sol"dan	n.
Sol"da*nel	n.
Sol"dan*rie	n.
Sol"der	n.
Sol"der	v. t.
Sol"der*er	n.
Sol"der*ing	a. & n.
Sol"dier	n.
Sol"dier	v. i.
Sol"dier*ess	n.
Sol"dier*ing	n.
Sol"dier*like"	a.
Sol"dier*ly	a.
Sol"dier*ship	n.
Sol"dier*wood`	n.
Sol"dier*y	n.
Sol"do	n.
Sole	n.
Sole	n.
Sole	v. t.
Sole	a.
Sol"e*cism	n.
Sol"e*cist	n.
Sol`e*cis"tic	a.
Sol`e*cis"tic*al	a.
Sol`e*cis"tic*al*ly	adv.
Sol"e*cize	v. i.
Sole"ly	adv.
Sol"emn	a.
Sol"em*ness	n.
So*lem"ni*ty	n.
So*lem"ni*zate	v. t.
Sol`em*ni*za"tion	n.
Sol"em*nize	v. t.
Sol"em*nize	n.
Sol"em*ni`zer	n.
Sol"emn*ly	adv.
Sol"emn*ness	n.
So*lemp"ne	a.
So"len	n.
Sol`e*na"cean	n.
Sol`e*na"ceous	a.
Sole"ness	n.
Sole*nette"	n.
So*le`no*con"cha	n. pl.
So*le"no*don	n.
So*le`no*gas"tra	n. pl.
So*le"no*glyph	a.
So`le*nog"ly*pha	n. pl.
So"len*oid	n.
So`le*nos"to*mi	n. pl.
Sole"plate`	n.
So"ler	n.
So"lert	a.
So*ler"tious*ness	n.
Sole"ship	n.
Sole trader	v. i.
Sol`-fa"	v. t.
Sol"-fa"	n.
Sol`fa*na"ri*a	n.
Sol`fa*ta"ra	n.
Sol`feg*gia"re	v. i.
Sol*feg"gio	n.
Sol`fe*ri"no	n.
So"li	n.
So*lic"it	v. t.
So*lic"it*ant	n.
So*lic"it*ate	a.
So*lic`i*ta"tion	n.
So*lic"it*or	n.
So*lic"it*or-gen"er*al	n.
So*lic"it*ous	a.
So*lic"it*ress	n.
So*lic"i*tude	n.
Sol"id	a.
Sol"id	n.
Sol`i*da"go	n.
Sol"i*dare	n.
Sol`i*dar"i*ty	n.
Sol"i*da*ry	a.
Sol"i*date	v. t.
Sol"id-drawn`	a.
So*lid"i*fi`a*ble	a.
So*lid`i*fi*ca"tion	n.
So*lid"i*fy	v. t.
So*lid"i*fy	v. i.
Sol"id*ism	n.
Sol"id*ist	n.
So*lid"i*ty	n.
Sol"id*ly	adv.
Sol"id*ness	n.
Sol`id*un"gu*la	n. pl.
Sol`id*un"gu*lar	a.
Sol`id*un"gu*late	n.
Sol`id*un"gu*lous	a.
Sol`i*fid"i*an	n.
Sol`i*fid"i*an	a.
Sol`i*fid"i*an*ism	n.
Sol"i*form	a.
So*lif"u*gae	n. pl.
So*lil"o*quize	v. i.
So*lil"o*quy	n.
Sol"i*ped	n.
So*lip"e*dous	a.
So*lip"sism	n.
Sol`i*se"qui*ous	a.
Sol`i*taire"	n.
Sol`i*ta"ri*an	n.
Sol`i*ta*ri"e*ty	n.
Sol"i*ta*ri*ly	adv.
Sol"i*ta*ri*ness	n.
Sol"i*ta*ry	a.
Sol"i*ta*ry	n.
Sol"i*tude	n.
So*liv"a*gant	a.
So*liv"a*gous	a.
Sol"lar	n.
Sol"lar	v. t.
Sol"lein	a.
Sol*ler*et"	n.
Sol`mi*za"tion	n.
So"lo	n.
So"lo	a.
So"lo*ist	n.
Sol"o*mon	n.
Sol"o*mon's seal	n.
Solo whist	a.
Sol`pu*gid"e*a	n. pl.
Sol"stice	n.
Sol*sti"tial	a.
Sol`u*bil"i*ty	n.
Sol"u*ble	a.
Sol"u*ble*ness	n.
So"lus	masc. a.
So*lute"	a.
So*lute"	v. t.
So*lu"tion	n.
Sol"u*tive	a.
Solv`a*bil"i*ty	n.
Solv"a*ble	a.
Solv"a*ble*ness	n.
Solve	v. t.
Solve	n.
Sol"ven*cy	n.
Sol"vend	n.
Sol"vent	a.
Sol"vent	n.
Sol"ver	n.
Solv"i*ble	a.
Sol"y	adv.
So"ma	n.
So"maj"	n.
So*ma"li	n.
So*mat"ic	a.
So*mat"ic*al	a.
So*mat"ics	n.
So"ma*tist	n.
So"ma*to*cyst	n.
So`ma*tol"o*gy	n.
So"ma*tome	n.
So"ma*to*pleure	n.
So`ma*to*pleu"ric	a.
So`ma*tot"ro*pism	n.
Som"ber	a.
Som"ber	v. t.
Som"ber	n.
Som"ber*ly	adv.
Som"ber*ness	n.
Som*bre"ro	n.
Som"brous	a.
-some	a.
Some	a.
Some"bod*y	n.
Some"deal`	adv.
Some"how`	adv.
Som"er*sault	n.
Some"thing	n.
Some"thing	adv.
Some"time`	adv.
Some"time`	a.
Some"times`	adv.
Some"times`	a.
Some"what`	n.
Some"what`	adv.
Some"when`	adv.
Some"where`	adv.
Some"while`	adv.
Some"whith`er	adv.
So"mite	n.
Som`meil"	n.
Som"mer*set	n.
Som*nam"bu*lar	a.
Som*nam"bu*late	v. i. & t.
Som*nam`bu*la"tion	n.
Som*nam"bu*la`tor	n.
Som*nam"bule	n.
Som*nam"bu*lic	a.
Som*nam"bu*lism	n.
Som*nam"bu*list	n.
Som*nam`bu*lis"tic	a.
Som"ne	v. t.
Som"ner	n.
Som"ni*al	a.
Som"ni*a*tive	a.
Som"ni*a*to*ry	a.
Som*nic"u*lous	a.
Som*nif"er*ous	a.
Som*nif"ic	a.
Som*nif"u*gous	a.
Som*nil"o*quence	n.
Som*nil"o*quism	n.
Som*nil"o*quist	n.
Som*nil"o*quous	a.
Som*nil"o*quy	n.
Som*nip"a*thist	n.
Som*nip"a*thy	n.
Som"no*lence	n.
Som"no*lent	a.
som"no*lism	n.
Som*nop"a*thy	n.
Som"nour	n.
Som"on*aunce	n.
Som"on*our	n.
Somp"ne	v. t.
Somp"nour	n.
Son	n.
So"nance	n.
So"nant	a.
So*na"ta	n.
So`na*ti"na	n.
Son"cy	a.
Sond	n.
Son"de*li	n.
Son"der*class`	n.
Song	n.
Song"craft`	n.
Song"ful	a.
Song"ish	a.
Song"less	a.
Song"ster	n.
Song"stress	n.
Son"i*fer	n.
So*nif"er*ous	a.
Son`i*fi*ca"tion	n.
Son"-in-law`	n.
Son"less	a.
Son"net	n.
Son"net	v. i.
Son`net*eer"	n.
Son`net*eer"	v. i.
Son"net*er	n.
Son"net*ist	n.
Son"net*ize	v. i.
Son"nish	a.
Son"nite	n.
So*nom"e*ter	n.
So*no"ran	a.
Son`o*rif"ic	a.
So*nor"i*ty	n.
So*no"rous	a.
Son"ship	n.
Son"sy	a.
Son"tag	n.
Son"ties	n.
Soo*chong"	n.
Soo"dra	n.
Soon	adv.
Soon	a.
Soo"nee	n.
Soon"er	n.
Sooner State	adv.
Soord	n.
Soor"ma	n.
Soo*shong"	n.
Soo"soo	n.
Soot	n.
Soot	v. t.
Soot	a.
Soot"er*kin	n.
Sooth	a.; <plain>also</plain> adv.
Sooth	n.
Soothe	v. t.
Sooth"er	n.
Sooth"fast`	a.
Sooth"fast`	adv.
Sooth"ing	a. & n.
Sooth"ing*ly	adv.
Sooth"ly	adv.
Sooth"ness	n.
Sooth"say`	v. i.
Sooth"say`	n.
Sooth"say`er	n.
Sooth"say`ing	n.
Soot"i*ness	n.
Soot"ish	a.
Soot"y	a.
Soot"y	v. t.
Sop	n.
Sop	v. t.
Sope	n.
Soph	n.
Soph	n.
So"phi	n.
Soph"ic	a.
So*phime"	n.
Soph"ism	n.
Soph"ist	n.
Soph"ist*er	n.
Soph"ist*er	v. t.
So*phis"tic	a.
So*phis"ti*cate	v. t.
So*phis"ti*cate	a.
So*phis`ti*ca"tion	n.
So*phis"ti*ca`tor	n.
Soph"ist*ry	n.
Soph"o*more	n.
Soph`o*mor"ic	a.
So*pho"ra	n.
Soph"ta	n.
So"pite	v. t.
So*pi"tion	n.
So"por	n.
Sop"o*rate	v. t.
Sop`o*rif"er*ous	a.
Sop`o*rif"ic	a.
Sop`o*rif"ic	n.
Sop"o*rose`	a.
Sop"per	n.
sopping	a.
So"pra	adv.
So*pra"nist	n.
So*pra"no	n.
Sops"a*vine	n.
So"ra	n.
Sor"ance	n.
Sorb	n.
Sor"bate	n.
Sor`be*fa"cient	a.
Sorb"ent	n.
Sor"bet	n.
Sor"bic	a.
Sor"bile	a.
Sor"bin	n.
Sor"bite	n.
Sor*bi"tion	n.
Sor*bon"ic*al	a.
Sor"bon*ist	n.
Sor"cer*er	n.
Sor"cer*ess	n.
Sor"cer*ing	n.
Sor"cer*ous	a.
Sor"cer*y	n.
Sord	n.
Sor"des	n.
Sor"det	n.
Sor"did	a.
Sor*did"ly	n.
Sor"did*ly	adv.
Sor"did*ness	n.
Sor"dine	n.
Sore	a.
Sore	n.
Sore	a.
Sore	n.
Sore	adv.
So*re"di*a	n.
So*re"di*ate	a.
Sor`e*dif"er*ous	a.
So*re"di*um	n.
So"ree	n.
Sore"head`	n.
Sore"hon	n.
Sor"el	n.
Sore"ly	adv.
So*re"ma	n.
Sore"ness	n.
So"rex	n.
Sor"ghe	n.
Sor"ghum	n.
Sor"go	n.
So"ri	n.
So"ri*cine	a.
So*ri"tes	n.
So"rit"ic*al	a.
Sorn	v. i.
Sorn"er	n.
So*ro"ral	a.
So*ror"i*cide	n.
So*ro"rize	v. i.
So*ro"sis	n.
So*ro"sis	n.
Sor"rage	n.
Sor"rance	n.
Sor"rel	a.
Sor"rel	n.
Sor"rel	n.
Sor"ren"to work`	adv.
Sor"ri*ness	n.
Sor"row	n.
Sor"row	v. i.
Sor"rowed	a.
Sor"row*ful	a.
Sor"row*less	a.
Sor"ry	a.
Sors	n.
Sort	n.
Sort	n.
Sort	v. t.
Sort	v. i.
Sort"a*ble	a.
Sort"a*bly	adv.
Sort"al	a.
Sort"ance	n.
Sort"er	n.
Sor"tes	n.
Sor"tie	n.
Sor"ti*lege	n.
Sor`ti*le"gious	a.
Sor"til"e*gy	n.
Sor*ti"ta	n.
Sor*ti"tion	n.
Sort"ment	n.
So"rus	n.
Sor"we	n. & v.
Sor"we*ful	a.
So"ry	n.
SOS	a.
So"-so`	adv.
Soss	v. i.
Soss	v. t.
Soss	n.
Soss	n.
Sos`te*nu"to	a.
Sot	n.
Sot	a.
Sot	v. t.
Sot	v. i.
So`ta*de"an	a.
So*tad"ic	a.
sote	a.
so"tel	a.
so*te`ri*ol"o*gy	n.
Sothe	a.
So"thi*ac	a.
So"til*te	n.
Sot"ted	a. & p. p.
Sot"ter*y	n.
Sot"tish	a.
Sot`to vo"ce	n.
Sou*a"ri nut`	n.
Sou"bah*dar	n.
Sou`bise"	n.
Sou`brette"	n.
Sou`bri`quet"	n.
Souce	n.
Souce	v. t. & i.
Sou*chong"	n.
Sou*dan"	n.
Soud"ed	a.
Souf"fle	n.
Souf"fl<eacute/	n.
Souf`fl<eacute/"	a.
Souffl<eacute/e	n.
Sough	n.
Sough	n.
Sough	v. i.
Sought	imp. & p. p.
Souke	v. t. & i.
Soul	a.
Soul	v. i.
Soul	n.
Soul	v. t.
soul	a.
Souled	a.
Sou"li*li`	n.
soul" kiss`	n.
Soul"less	a.
Soul"less*ly	adv.
Soun	n. & v.
Sound	n.
Sound	n.
Sound	a.
Sound	adv.
Sound	n.
Sound	v. t.
Sound	v. i.
Sound	n.
Sound	n.
Sound	v. i.
Sound	v. t.
Sound"a*ble	a.
Sound"age	n.
Sound"-board`	n.
Sound"er	n.
Sound"er	n.
Sound"ing	a.
Sound"ing	n.
Sound"ing bal*loon"	n.
Sound"less	a.
Sound"less	a.
Sound"ly	adv.
Sound"ness	n.
Soune	v. t. & i.
Sounst	a.
Soup	n.
Soup	v. t.
Soup	v. t.
Soup	v. t.
Soup`<cced/on"	n.
Soupe`-mai"gre	n.
Sou"ple	n.
Soup"y	a.
Sour	a.
Sour	n.
Sour	v. t.
Sour	v. i.
Source	n.
Sour"crout`	n.
Sourde	v. i.
Sour"ing	n.
Sour"ish	a.
Sour"krout`	n.
Sour"ly	adv.
Sour"ness	n.
Sours	n.
Sour"sop`	n.
Sour"wood`	n.
Sous	n.
Souse	n.
Souse	n.
Souse	v. t.
Souse	v. i.
Souse	v. t.
Souse	n.
Souse	adv.
Soused	adj.
Sous"lik	n.
Sout	n.
Sou`tache"	n.
Sout"age	n.
Sou`tane"	n.
Sou"ter	n.
Sou"ter*ly	a.
Sou"ter*rain	n.
South	n.
South	a.
South	adv.
South	v. i.
South*cot"ti*an	n.
South"down`	a.
South"down`	n.
South`east"	n.
South`east	a.
South`east"er	n.
South`east"er	adv.
South`east"ern	a.
South`east"ward	adv.
South"er	n.
South"er*li*ness	n.
South"er*ly	a.
South"ern	a.
South"ern	n.
South"ern*er	n.
South"ern*li*ness	n.
South"ern*ly	a.
South"ern*most`	a.
South"ern*wood`	n.
South"ing	n.
South"ly	adv.
South"most`	a.
South"ness	n.
South"paw`	a.
South"paw`	n.
South"ren	a.
South"ron	n.
South"say`	v. i.
South"say`er	n.
South` south"er*ly	adv.
South"ward	a.
South"ward	n.
South"ward*ly	adv.
South`west	n.
South`west"	a.
South`west"er	n.
South`west"er*ly	a.
South`west"ern	a.
South`west"ward	adv.
Sou"ve*nance	n.
Sou`ve*nir	n.
Sov"er*eign	a.
Sov"er*eign	n.
Sov"er*eign*ize	v. i.
Sov"er*eign*ly	adv.
Sov"er*eign*ty	n.
Sov"ran	a.
Sow	v. i.
Sow	n.
Sow	v. t.
Sow	v. i.
Sow"ans	n. pl.
Sow"ar	n.
Sow"bane`	n.
Sowce	n. & v.
Sow"dan	n.
Sow"dan*esse`	n.
Sow"ens	n. pl.
Sow"er	n.
Sow"ins	n. pl.
Sowl	v. t.
Sowl	v. i.
Sown	p. p.
Sowne	v. t. & i.
Sowse	n. & v.
Sow"ter	n.
Soy	n.
Soy"bean	n.
Soy"bean oil	n.
Soyle	v. t.
Soyle	n.
Soyn"ed	a.
Soz"zle	v. t.
Soz"zle	n.
Spa	n.
Spaad	n.
Space	n.
Space	v. i.
Space	v. t.
Space age	n.
space bar	n.
space"craft	n.
Space flight	n.
Space"ful	a.
space" heat`er	n.
Space"less	a.
space"man`	n.
space"port	n.
space" probe	n.
space" shut`tle	n.
space" sick`ness	n.
space" sta`tion	n.
Space suit	n.
space-time	n.
Space travel	n.
Space walk	n.
Spa"cial	a.
Spa"cial*ly	adv.
Spa"cious	a.
Spad	n.
Spa`das`sin"	n.
Spad"dle	n.
Spade	n.
Spade	n.
Spade	v. t.
Spade"bone`	n.
Spade"fish`	n.
Spade"foot`	n.
Spade"ful	n.
Spad"er	n.
Spa*di"ceous	a.
Spa"di*cose`	a.
Spa*dille"	n.
Spa"dix	n.
Spa"do	n.
Spa*droon"	n.
Spae	v. i.
Spae"man	n.
Spae"wife`	n.
Spa*ghet"ti	n.
Spa*gyr"ic	a.
Spa*gyr"ic	n.
Spag"y*rist	n.
Spa"hi	n.
Spaid	n.
Spake	imp.
Spake"net`	n.
Spak"y	a.
Spald"ing knife`	n.
Spall	n.
Spall	n.
Spall	v. t.
Spall	v. i.
Spal"peen	n.
Spalt	n.
Spalt	a.
Spalt	v. t. & i.
Spalt"ing knife`	imp. & p. p.
Span	n.
Span	v. t.
Span	v. i.
Spa*nae"mi*a	n.
Spa*nae"mic	a.
Span"cel	n.
Span"cel	v. t.
Span"dex	prop. n.
Span"dogs`	n. pl.
Span"drel	n.
Spane	v. t.
Spang	v. t.
Spang	v. i.
Spang	n.
Spang	n.
Span"gle	n.
Span"gle	v. t.
Span"gle	v. i.
Span"gler	n.
Span"gly	a.
Span"iard	n.
Span"iel	n.
Span"iel	a.
Span"iel	v. i.
Span"iel	v. t.
Span"ish	a.
Span"ish	n.
Spank	v. t.
Spank	n.
Spank	v. i.
Spank"er	n.
Spank"er	n.
spank"ing	a.
spanking breeze	a.
span"ner	n.
span"-new`	a.
span"nish*ing	n.
span"piece	n.
span"worm`	n.
spar	n.
Spar	n.
Spar	v. t.
Spar	v. i.
Spar	n.
Spar"a*ble	n.
Spar"a*da	n.
Spar"a*drap	n.
Spar"age	n.
Spar"ble	v. t.
Spare	v. t.
Spare	v. i.
Spare	a.
Spare	n.
Spare"ful	a.
Spare"less	a.
Spare"ly	adv.
Spare"ness	n.
Spar"er	n.
Spare"rib`	n.
Sparge	v. t.
Spar`ge*fac"tion	n.
Spar"ger	n.
Spar"hawk`	n.
Spar"-hung`	a.
Spar"ing	a.
Spark	n.
Spark	n.
Spark	v. i.
Spark	v. i.
Spark coil	n.
Spark"ful	a.
Spark gap	a.
Spar"kle	n.
Spar"kle	v. i.
Spar"kle	v. t.
Spar"kle	v. t.
Spar"kler	n.
Spar"kler	n.
Spar"kler	n.
Spark"let	n.
Spark"li*ness	n.
Spar"kling	a.
Spark plug	n.
Spar"lyre`	n.
Spa"roid	a.
Spar"piece`	n.
Spar"poil	v. t.
Spar"row	n.
Spar"row*grass`	n.
Spar"row*wort`	n.
Spar"ry	a.
Sparse	a.
Sparse	v. t.
Spars"ed*ly	adv.
Sparse"ly	adv.
Sparse"ness	n.
Spar"sim	adv.
Spar"tan	a.
Spar"te*ine	n.
Spar"ter*ie	n.
Sparth	n.
Sparve	n.
Spar"y	a.
Spasm	n.
Spas*mat"ic*al	a.
Spas"mod"ic	a.
Spas*mod"ic	n.
Spas*mod"ic*al	a.
Spas"tic	a.
Spas"tic*al*ly	adv.
Spas*tic"i*ty	n.
Spat	imp.
Spat	n.
Spat	v. i. & t.
Spat	n.
Spat	v. i.
Spat	v. t.
Spat	n.
Spa*tan"goid	a.
Spat`an*goi"de*a	n. pl.
Spa*tan"gus	n.
Spatch"cock`	n.
Spate	n.
Spa"tha	n.
Spa*tha"ceous	a.
Spa"thal	a.
Spathe	n.
Spathed	a.
Spath"ic	a.
Spath"i*form	a.
Spath"ose`	a.
Spath"ose`	a.
Spath"ous	a.
Spath"u*late	a.
Spa"tial	a.
Spa"tial*ly	adv.
Spa"ti*ate	v. t.
Spat"ter	v. t.
Spat"ter	v. i.
Spat"ter*dashed`	a.
Spat"ter*dash`es	n. pl.
Spat`ter-dock`	n.
Spat"tle	n.
Spat"tle	n.
Spat"tling-pop"py	n.
Spat"u*la	n.
Spat"u*late	a.
Spauld	n.
Spav"in	n.
Spav"ined	a.
Spaw	n.
Spawl	n.
Spawl	n.
Spawl	v. i. & t.
Spawl"ing	n.
Spawn	v. t.
Spawn	v. i.
Spawn	n.
Spawn"er	n.
Spay	v. t.
Spay	n.
Spay"ad	n.
Speak	v. i.
Speak	v. t.
Speak"a*ble	a.
speak"eas`y	n.
Speak"er	n.
Speak"er*ship	n.
Speak"ing	a.
Speak"ing	n.
Spear	n.
Spear	v. t.
Spear	v. i.
Spear"er	n.
Spear"fish`	n.
Spear"head`	n.
Spear"man	n.
Spear"mint`	n.
Spear"wood`	n.
Spear"wort`	n.
Spear"y	a.
Spece	n.
Specht	n.
Spe"cial	a.
Spe"cial	n.
Spe"cial*ism	n.
Spe"cial*ist	n.
Spe`ci*al"i*ty	n.
Spe`cial*i*za"tion	n.
Spe"cial*ize	v. t.
Spe"cial*ly	adv.
Spe"cial*ty	n.
Spe"ci*e	abl.
Spe"cie	n.
Spe"cies	n. sing. & pl.
Spec"i*fi`a*ble	a.
spe*cif"ic	a.
Spe*cif"ic	n.
Spe*cif"ic*al	a.
Spe*cif"ic*al*ly	adv.
Spe*cif"ic*al*ness	n.
Spe*cif"i*cate	v. t.
spec`i*fi*ca"tion	n.
Spe*cif"ic*ness	n.
Spec"i*fy	v. t.
Spe*cil"lum	n.
Spec"i*men	n.
Spe`ci*os"i*ty	n.
Spe"cious	a.
Speck	n.
Speck	n.
Speck	v. t.
Spec"kle	n.
Spec"kle	v. t.
Spec"kled	a.
Spec"kled-bel`ly	n.
Spec"kled-bill"	n.
Spec"kled*ness	n.
Speck`sion*eer"	n.
Speckt	n.
Spec"ta*cle	n.
Spec"ta*cled	a.
Spec*tac"u*lar	a.
Spec"tant	a.
Spec*ta"tion	n.
Spec*ta"tor	n.
Spec`ta*to"ri*al	a.
Spec*ta"tor*ship	n.
Spec*ta"tress	n.
Spec"ter	n.
Spec`tion*eer"	n.
Spec"tral	a.
Spec"tral*ly	adv.
Spec"tre	n.
Spec`tro*bo*lom"e*ter	n.
Spec`tro*e*lec"tric	a.
Spec"tro*gram	n.
Spec"tro*graph	n.
Spec`tro*he"li*o*gram`	n.
Spec`tro*he"li*o*graph	n.
Spec`tro*log"ic*al	a.
Spec*trol"o*gy	n.
Spec*trom"e*ter	n.
Spec*trom"e*try	n.
Spec"tro*phone	n.
Spec`tro*pho*tom"e*ter	n.
Spec`tro*pho*tom"e*try	n.
Spec"tro*scope	n.
Spec`tro*scop"ic	a.
Spec*tros"co*pist	n.
Spec*tros"co*py	n.
Spec"trum	n.
Spec"u*lar	a.
Spec"u*late	v. i.
Spec"u*late	v. t.
Spec`u*la"tion	n.
Spec"u*la*tist	n.
Spec"u*la*tive	a.
Spec"u*la`tor	n.
Spec`u*la*to"ri*al	a.
Spec"u*la*to*ry	a.
Spec"u*list	n.
Spec"u*lum	n.
Sped	imp. & p. p.
Speece	n.
Speech	n.
Speech	v. i. & t.
Speech"ful	a.
Speech`i*fi*ca"tion	n.
Speech"i*fi`er	n.
Speech"i*fy	v. i.
Speech"i*fy`ing	n.
Speech"ing	n.
Speech"less	a.
Speech"mak`er	n.
Speed	n.
Speed	v. i.
Speed	v. t.
Speed counter	n.
Speed"ful	a.
Speed"ful*ly	adv.
Speed"i*ly	adv.
Speed"i*ness	n.
Speed"less	a.
Speed"well	n.
Speed"y	a.
Speer	n.
Speer	v. t.
Speet	v. t.
Speight	n.
Speir	v. i.
Speis`ko"balt	n.
Speiss	n.
Spek"boom	n.
Speke	v. i. & t.
Speke"house`	n.
Spel"ding	n.
Spel"i*cans	n. pl.
Spelk	n.
Spell	n.
Spell	v. t.
Spell	n.
Spell	n.
Spell	v. t.
Spell	v. i.
Spell"a*ble	a.
Spell"bind`	v. t.
Spell"bound`	a.
Spell"er	n.
Spell"ful	a.
Spell"ing	n.
Spell"ing	a.
Spell"ken	n.
Spell"work`	n.
Spelt	imp. & p. p.
Spelt	n.
Spelt	n.
Spelt	v. t. & i.
Spel"ter	n.
Spe*lunc"	n.
Spence	n.
Spen"cer	n.
Spen"cer	n.
Spen"cer	n.
Spend	v. t.
Spend	v. i.
Spen"der	n.
Spend"ing	n.
Spend"thrift`	n.
Spend"thrift	a.
Spend"thrift`y	a.
Spen*se"ri*an	a.
Spent	a.
Sper	v. t.
Spe"ra*ble	a.
Sper"a*ble	n.
Sper"age	n.
Spe"rate	a.
Spere	v. i.
Spere	n.
Sperge	n.
Sper"ling	n.
Sperm	n.
Sperm	n.
Sper`ma*ce"ti	n.
Sper"mal*ist	n.
Sper"ma*phore	n.
Sper"ma*ry	n.
Sper`ma*the"ca	n.
Sper*mat"ic	a.
Sper"mat"ic*al	a.
Sper"ma*tin	n.
Sper"ma*tism	n.
Sper*ma"ti*um	n.
Sper"ma*tize	v. i.
Sper"ma*to-	n.
Sper"ma*to*cyte	n.
Sper`ma*to*gem"ma	n.
Sper`ma*to*gen"e*sis	n.
Sper`ma*to*ge*net"ic	a.
Sper`ma*tog"e*nous	a.
Sper`ma*to*go"ni*um	n.
Sper"ma*toid	a.
Sper`ma*to"on	n.
Sper"ma*to*phore	n.
Sper`ma*toph"o*rous	a.
Sper`ma*toph"y*ta	n. pl.
Sper"ma*to"phyte`	n.
Sper`ma*tor*rhe"a	n.
Sper"ma*to*spore	n.
Sper`ma*to*zo"id	n.
Sper`ma*to*zo"oid	n.
Sper`ma*to*zo"'\'94n	n.
Sper"mic	a.
Sper*mid"i*um	n.
Sperm"ism	n.
Sperm"ist	n.
Sper"mo*blast	n.
Sper`mo*coc"cus	n.
Sper"mo*derm	n.
Sper`mo*go"ni*um	n.
Sper*mol"o*gist	n.
Sper"mo*phile	n.
Sper"mo*phore	n.
Sper*moph"y*ta	n. pl.
Sper"mo*phyte	n.
Sper`mo*phyt"ic	a.
Sper`mo*plas"ma	n.
Sper"mo*sphere	n.
Sper"mo*spore	n.
Sper"mule	n.
Sperm" whale`	n.
Sperse	v. t.
Spes"sart*ite	n.
Spet	v. t.
Spet	n.
Spetch"es	n. pl.
Spew	v. t.
Spew	v. i.
Spew	n.
Spew"er	n.
Spew"i*ness	n.
Spew"y	a.
Sphac"el	n.
Sphac"e*late	v. i.
Sphac"e*late	v. t.
Sphac"e*late	a.
Sphac`e*la"tion	n.
Sphac"e*lus	n.
Sphae*ren"chy*ma	n.
Sphae*rid"i*um	n.
Sphae"ro*spore	n.
Sphaer"u*lite	n.
Sphag*nic"o*lous	a.
Sphag"nous	a.
Sphag"num	n.
Sphal"er*ite	n.
Sphene	n.
Sphe*neth"moid	a.
Sphe*neth"moid	n.
Sphe`neth*moid"al	a.
Sphe*nis"can	n.
Sphe"no-	n.
Sphe"no*eth*moid`al	a.
Sphe"no*gram	n.
Sphe*nog"ra*pher	n.
Sphe`no*graph"ic	a.
Sphe*nog"ra*phist	n.
Sphe*nog"ra*phy	n.
Sphe"noid	a.
Sphe"noid	n.
Sphe*noid"al	a.
Sphe*not"ic	a.
Sphe*not"ic	n.
Spher"al	a.
Sphere	n.
Sphere	v. t.
Spher"ic*al	a.
Sphe*ric"i*ty	n.
Spher"i*cle	n.
Spher"ics	n.
Sphe`ro*bac*te"ri*a	n. pl.
Sphe`ro*con"ic	n.
Spher"o*graph	n.
Sphe"roid	n.
Sphe*roid"al	a.
Sphe*roid"ic	a.
Sphe`roi*dic"i*ty	n.
Sphe"ro*mere	n.
Sphe*rom"e*ter	n.
Spher`o*sid"er*ite	n.
Sphe"ro*some	n.
Spher"u*late	a.
Spher"ule	n.
Spher"u*lite	n.
Spher`u*lit"ic	a.
Spher"y	a.
Sphex	n.
Sphig*mom"e*ter	n.
Sphinc"ter	n.
Sphinc"ter	a.
Sphin"gid	n.
Sphin"gid	a.
Sphinx	n.
Sphrag"ide	n.
Sphra*gis"tics	n.
Sphri*go"sis	n.
Sphyg"mic	a.
Sphyg"mo*gram	n.
Sphyg"mo*graph	n.
Sphyg`mo*graph"ic	a.
Sphyg*mom"e*ter	n.
Sphyg"mo*phone	n.
Sphyg"mo*scope	n.
Sphy*rae"noid	a.
Spi"al	n.
Spi"ca	n.
Spi"cate	a.
Spic*ca"to	a.
Spice	n.
Spice	v. t.
Spice"bush`	n.
Spice"nut`	n.
Spi"cer*y	n.
Spice"wood`	n.
Spi*cif"er*ous	a.
Spi"ci*form	a.
Spi"ci*ly	adv.
Spi"ci*ness	n.
Spick	n.
Spick"nel	n.
Spi*cose"	a.
Spi*cos"i*ty	n.
Spi"cous	a.
Spic"u*la	n.
Spic"u*lar	a.
Spic"u*late	a.
Spic"u*late	v. t.
Spic"ule	n.
Spi*cu"li*form	a.
Spic`u*lig"e*nous	a.
Spic`u*li*spon"gi*ae	n. pl.
Spic"u*lum	n.
Spi"cy	a.
Spi"der	n.
Spi"dered	a.
Spi"der*like`	a.
Spi"der stitch	n.
Spied	imp. & p. p.
Spie"gel*ei`sen	n.
Spie"gel i`ron	n. & v.
Spight	n.
Spig"nel	n.
Spig"net	n.
Spig"ot	n.
Spi*gur"nel	n.
Spike	n.
Spike	v. t.
Spike	n.
Spike"bill`	n.
Spiked	a.
Spike"fish`	n.
Spike"let	n.
Spike"nard	n.
Spike"tail`	n.
Spik"y	a.
Spile	n.
Spile	v. t.
Spil"i*kin	n.
Spill	n.
Spill	v. t.
Spill	v. t.
Spill	v. i.
Spill"er	n.
Spil"let fish`ing	n.
Spill"way`	n.
Spilt	imp. & p. p.
Spil"ter	n.
Spilth	n.
Spin	v. t.
Spin	v. i.
Spin	n.
Spi"na bif"i*da	a.
Spin"ach	n.
spinach beet	n.
spinach blight	n.
Spi"nal	a.
Spi"nate	a.
Spin"dle	n.
Spin"dle	v. i.
Spin"dle-legged`	a.
Spin"dle*legs`	n.
Spin"dle-shanked`	a.
Spin"dle*shanks`	n.
Spin"dle-shaped`	a.
Spin"dle*tail`	n.
Spin"dle*worm`	n.
Spin"dling	a.
Spin"dly	a.
spin doctor	n.
spin drier	n.
Spin"drift	n.
Spine	n.
Spine"back`	n.
Spine"bill`	n.
Spined	a.
Spine"-finned`	a.
Spi*nel"	n.
Spin"el	n.
Spine"less	a.
Spi*nes"cence	n.
Spi*nes"cent	a.
Spin"et	n.
Spi"net	n.
Spine"tail`	n.
Spine"-tailed	a.
Spin"et*ed	a.
Spi*nif"er*ous	a.
Spin"i*fex	n.
Spin"i*form	a.
Spi*nig"er*ous	a.
Spin"i*ness	n.
Spin`i-spir"u*late	a.
Spink	n.
Spin"na*ker	n.
Spin"ner	n.
Spin"ner*et	n.
Spin"ner*ule	n.
Spin"ney	n.
Spin"ning	a. & n.
Spin"ny	n.
Spin"ny	a.
Spi*nose"	a.
Spi*nos"i*ty	n.
Spi"nous	a.
Spi*no"zism	n.
Spi*no"zist	n.
Spin"ster	n.
Spin"stress	n.
Spin"stry	n.
Spin*thar"i*scope	n.
spin the bottle	n.
spin the plate	n.
Spin"ule	n.
Spin`u*les"cent	a.
Spin"u*lose`	a.
Spin"y	a.
Spin"y	n.
Spi*o"de*a	n. pl.
Spi"ra*ble	a.
Spir"a*cle	n.
Spi*rac"u*lar	a.
Spi*rae"a	n.
Spi*rae"ic	a.
Spi"ral	a.
Spi"ral	n.
Spi*ral"i*ty	n.
Spi"ral*ly	adv.
Spi*ra`lo*zo"oid	n.
Spi"rant	n.
Spi*ran"thy	n.
Spi*ra"tion	n.
Spire	v. i.
Spire	n.
Spire	v. i.
Spire	n.
Spired	a.
Spi"ri*cle	n.
Spi"ri*fer	n.
Spi*ril"lum	n.
Spir"ing	a.
Spir"it	n.
Spir"it	v. t.
Spir"it*al*ly	adv.
Spir"it*ed	a.
Spir"it*ful	a.
Spir"it*ism	n.
Spir"it*ist	n.
Spir"it*less	a.
Spi`ri*to"so	a. & adv.
Spir"it*ous	a.
Spir"it*ous*ness	n.
Spir"it*u*al	a.
Spir"it*u*al	n.
Spir"it*u*al*ism	n.
Spir"it*u*al*ist	n.
Spir"it*u*al*ist	a.
Spir`it*u*al*is"tic	a.
Spir`it*u*al"i*ty	n.
Spir`it*u*al*i*za"tion	n.
Spir"it*u*al*ize	v. t.
Spir"it*u*al*i`zer	n.
Spir"it*u*al*ly	adv.
Spir"it*u*al-mind`ed	a.
Spir"it*u*al*ness	n.
Spir"it*u*al*ty	n.
Spi`ri`tu`elle"	a.
Spir`it*u*os"i*ty	n.
Spir"it*u*ous	a.
Spir"it*u*ous*ness	n.
Spirk"et*ing	n.
Spirl"ing	n.
Spi`ro*bac*te"ri*a	n. pl.
Spi`ro*chae"ta	n.
Spi"ro*graph	n.
Spi*rom"e*ter	n.
Spi*rom"e*try	n.
Spi"ro*scope	n.
Spi*royl"ic	a.
Spirt	v. & n.
Spir"tle	v. t.
Spir"u*la	n.
Spir"u*late	n.
Spir"y	a.
Spir"y	a.
Spiss	a.
Spis"sa*ted	a.
Spis"si*tude	n.
Spit	n.
Spit	v. t.
Spit	v. i.
Spit	v. t.
Spit	n.
Spit	v. i.
Spit"al	n.
Spit"al*house`	n.
spit"ball`	n.
Spit"box`	n.
Spitch"cock`	v. t.
Spitch"cock`	n.
Spitch"cocked`	a.
Spit" curl`	n.
Spite	v. t.
Spite"ful	a.
Spit"fire`	n.
Spit"ful	n.
Spit"ous	a.
Spit"ous*ly	adv.
Spits"cocked`	a.
Spit"ted	a.
Spit"ted	p. p.
Spit"ter	n.
Spit"ter	n.
Spit"tle	n.
Spit"tle	v. t.
Spit"tle	n.
Spit"tle	n.
Spit"tly	a.
Spit*toon"	n.
Spit"-ven"om	n.
Spitz" dog"	n.
Splanch`napoph"y*sis	n.
Splanch"nic	a.
Splanch*nog"ra*phy	n.
Splanch*nol"o*gy	n.
Splanch"no*pleure	n.
Splanch`no-skel"e*ton	n.
Splanch*not"o*my	n.
Splan"drel	n.
Splash	v. t.
Splash	v. i.
Splash	n.
Splash"board`	n.
Splash"er	n.
Splash"y	a.
Splat"ter	v. i. & t.
Splat"ter*dash`	n.
Splay	v. t.
Splay	a.
Splay	a.
Splay"foot`	n.
Splay"foot`	a.
Splay"mouth`	n.
Splay`mouthed"	a.
Spleen	n.
Spleen	v. t.
Spleened	a.
Spleen"ful	a.
Spleen"ish	a.
Spleen"less	a.
Spleen"wort`	n.
Spleen"y	a.
Spleg"et	n.
Sple*nal"gi*a	n.
Splen"cu*lus	n.
Splen"dent	a.
Splen"did	a.
Splen*did"i*ous	a.
Splen"did*ly	adv.
Splen"did*ness	n.
Splen"did*ous	a.
Splen*dif"er*ous	a.
Splen"dor	n.
Splen"drous	a.
Splen"e*tic	a.
Splen"e*tic	n.
Sple*net"ic*al	a.
Sple*net"ic*al*ly	adv.
Sple"ni*al	a.
Sple"ni*al	n.
Splen"ic	a.
Splen"ic*al	a.
Splen"ish	a.
Sple*ni"tis	n.
Splen"i*tive	a.
Sple"ni*um	n.
Sple"ni*us	n.
Splen`i*za"tion	n.
Splen"o*cele	n.
Sple*nog"ra*phy	n.
Sple"noid	a.
Sple*nol"o*gy	n.
Sple*not"o*my	n.
Splent	n.
Spleu"chan	n.
Splice	v. t.
Splice	n.
Spline	n.
Splin"ing	a.
Splint	n.
Splint	v. t.
Splin"ter	v. t.
Splin"ter	v. i.
Splin"ter	n.
Splin"ter*proof`	a.
Splin"ter*y	a.
Split	v. t.
Split	v. i.
Split	n.
Split	a.
Split dynamometer	n. pl.
Split infinitive	n.
Split"ter	n.
Split"-tongued`	a.
Split wheel	n.
Splotch"y	a.
Splurge	n.
Splurge	v. i.
Splut"ter	v. i.
Splut"ter	n.
Splut"ter*er	n.
Spod"o*man`cy	n.
Spod`o*man"tic	a.
Spod"u*mene	n.
Spof"fish	a.
Spoil	v. t.
Spoil	v. i.
Spoil	n.
Spoil"a*ble	a.
Spoil"er	n.
Spoil"five`	n.
Spoil"ful	a.
Spoils"man	n.
Spoils"mon`ger	n.
Spoke	imp.
Spoke	n.
Spoke	v. t.
Spo"ken	a.
Spoke"shave`	n.
Spokes"man	n.
Spo"li*ate	v. t. & i.
Spo`li*a"tion	n.
Spo"li*a*tive	a.
Spo"li*a`tor	n.
Spo"li*a*to*ry	a.
Spon*da"ic	a.
Spon"dee	n.
Spon*du"lics	n.
Spon"dyl	n.
Spong	n.
Sponge	n.
Sponge	v. t.
Sponge	v. i.
Sponge"let	n.
Spon"geous	a.
Spon"ger	n.
Spon"gi*ae	n. pl.
Spon"gi*da	n. pl.
Spon"gi*form	a.
Spon*gil"la	n.
Spon"gin	n.
Spon"gi*ness	n.
Spon"ging	a. & n.
Spon"gi*ole	n.
Spon"gi*o*lite	n.
Spon`gi*o*pi"lin	n.
Spon"gi*ose`	a.
Spon`gi*o*zo"a	n. pl.
Spon"go*blast	n.
Spon"goid	a.
Spon"gy	a.
Sponk	n.
Spon"sal	a.
Spon"si*ble	a.
Spon"sion	n.
Spon"sion*al	a.
Spon"son	n.
Spon"sor	n.
Spon*so"ri*al	a.
Spon"sor*ship	n.
Spon`ta*ne"i*ty	n.
Spon*ta"ne*ous	a.
Spon*toon"	n.
Spook	n.
Spool	n.
Spool	v. t.
Spool"er	n.
Spoom	v. i.
Spoon	v. i.
Spoon	n.
Spoon	v. t.
Spoon	v. i.
Spoon	v. i.
Spoon"bill`	n.
Spoon"-billed`	a.
Spoon"drift	n.
Spoon"ey	a.
Spoon"ey	n.
Spoon"flow`er	n.
Spoon"ful	n.
Spoon"i*ly	adv.
Spoon"-meat`	n.
Spoon"wood`	n.
Spoon"worm`	n.
Spoon"wort`	n.
Spoon"y	a. & n.
Spoor	n.
Spoor	v. i.
Spor"a*des	n. pl.
Spo*ra"di*al	a.
Spo*rad"ic	a.
Spo*rad"ic*al	a.
Spo*rad"ic*al*ly	adv.
Spo*ran"gi*o*phore	n.
Spo*ran"gi*um	n.
Spore	n.
Spo"rid	n.
Spo`ri*dif"er*ous	a.
Spo*rid"i*um	n.
Spo*rif"er*ous	a.
Spo`ri*fi*ca"tion	n.
Spo"ro*carp	n.
Spo"ro*cyst	n.
Spo`ro*gen"e*sis	n.
Spo*rog"o*ny	n.
Spo"ro*phore	n.
Spo`ro*phor"ic	a.
Spo"ro*phyte	n.
Spo"ro*sac	n.
Spo`ro*zo"a	n. pl.
Spo`ro*zo"id	n.
Spo`ro*zo"ite	n.
Spor"ran	n.
Sport	n.
Sport	v. i.
Sport	v. t.
Sport`a*bil"i*ty	n.
Sport"al	a.
Sport"er	n.
Sport"ful	a.
Sport"ing	a.
Sport"ing*ly	adv.
Sport"ive	a.
Sport"less	a.
Sport"ling	n.
Sports"man	n.
Sports"man*ship	n.
Spor"tu*la	n.
Spor"tu*la*ry	a.
Spor"tule	n.
Spor`u*la"tion	n.
Spor"ule	n.
Spor`u*lif"er*ous	a.
Spot	n.
Spot	v. t.
Spot	v. i.
Spot	a.
Spot cash	a.
Spot"light`	n.
Spot stroke	a.
Spot"ted*ness	n.
spot"ter	n.
spot"ti*ness	n.
Spot"ty	a.
Spous"age	n.
Spous"al	a.
Spous"al	n.
Spouse	n.
Spouse	v. t.
Spouse"-breach`	n.
Spouse"less	a.
Spous"ess	n.
Spout	v. t.
Spout	v. i.
Spout	n.
Spout"er	n.
Spout"fish`	n.
Spout"less	a.
Spout"shell`	n.
Sprack	a.
Sprad	p. p.
Sprad"de	imp.
Sprag	n.
Sprag	n.
Sprag	v. t.
Sprag	a.
Sprain	v. t.
Sprain	n.
Spraints	n. pl.
Sprang	imp.
Sprat	n.
Sprawl	v. i.
sprawl	n.
Sprawls	n. pl.
Spray	n.
Spray	n.
Spray	v. t.
Spray"board`	n.
Spray" can`	n.
Spray"er	n.
Spray" gun`	n.
Spray" paint`	n.
Spray"-paint	v. t.
Spread	v. t.
Spread	v. i.
Spread	n.
Spread	imp. & p. p.
spread"-ea`gle	a.
spread"-ea`gle	v. i.
spread"-ea`gled	a.
Spread"er	n.
Spread"ing*ly	adv.
Sprech"er*y	n.
Spree	n.
Sprenge	v. t.
Spreng"el pump`	p. p.
Sprew	n.
Spreynd	p. p.
Sprig	n.
Sprig	v. t.
Sprigged	a.
Sprig"gy	a.
Spright	n.
Spright	v. t.
Spright"ful	a.
Spright"less	a.
Spright"li*ness	n.
Spright"ly	a.
Sprig"tail`	n.
Spring	v. i.
Spring	v. t.
Spring	n.
Spring"al	n.
Spring"al	n.
Spring"board`	n.
Spring"bok`	n.
Springe	n.
Springe	v. t.
Spring"e	v. t.
Spring"er	n.
Spring"halt`	n.
Spring"head`	n.
Spring"i*ness	n.
Spring"ing	n.
Sprin"gle	n.
Spring"let	n.
Spring steel	n.
Spring"tide`	n.
Spring"time`	n.
Spring"y	a.
Sprin"kle	v. t.
Sprin"kle	v. i.
Sprin"kle	n.
Sprin"kler	n.
Sprin"kling	n.
Sprint	v. i.
Sprint	n.
Sprint"er	n.
Sprit	v. t.
Sprit	v. i.
Sprit	n.
Sprit	n.
Sprite	n.
Sprite"ful	a.
Sprit"sail	n.
Sprock"et	n.
Sprock"et wheel`	n.
Sprong	imp.
Sprout	v. i.
Sprout	v. t.
Sprout	n.
Spruce	n.
Spruce	a.
Spruce	v. t.
Spruce	v. i.
Sprue	n.
Sprug	v. t.
Sprung	imp. & p. p.
Sprung	a.
Sprunt	v. i.
Sprunt	n.
Sprunt	a.
Sprunt"ly	adv.
Spry	a.
Spud	n.
Spue	v. t. & i.
Spuil"zie	n.
Spuke	n.
Spul"ler	n.
spul"zie	n.
Spume	n.
Spume	v. i.
Spume"ous	a.
Spu*mes"cence	n.
Spu*mes"cent	a.
Spum"id	a.
Spu*mif"er*ous	a.
Spum"i*ness	n.
Spum"ous	a.
Spun	imp. & p. p.
Spunge	n.
Spunk	n.
Spunk"y	a.
Spur	n.
Spur	n.
Spur	v. t.
Spur	v. i.
Spur"gall`	n.
Spur"gall`	v. t.
Spurge	v. t.
Spurge	n.
Spurge"wort`	n.
Spur"ging	n.
Spu"ri*ous	a.
Spur"less	a.
Spur"ling	n.
Spur"ling-line`	n.
Spurn	v. t.
Spurn	v. i.
Spurn	n.
Spurn"er	n.
Spurn"-wa`ter	n.
Spurred	a.
Spur"rer	n.
Spur"rey	n.
Spur"ri*er	n.
Spur"-roy`al	n.
Spur"ry	n.
Spur"-shell`	n.
Spurt	v. i.
Spurt	v. t.
Spurt	n.
Spurt	n.
Spurt	v. i.
Spur"tle	v. t.
Spur"way`	n.
Spur"-winged`	a.
Sput	n.
Spu*ta"tion	n.
Spu"ta*tive	a.
Spute	v. t.
Sput"ter	v. i.
Sput"ter	v. t.
Sput"ter	n.
Sput"ter*er	n.
Spu"tum	n.
Spy	v. t.
Spy	v. i.
Spy	n.
Spy"boat`	n.
Spy"glass`	n.
Spy"ism	n.
Spy"nace	n.
Squab	a.
Squab	n.
Squab	adv.
Squab	v. i.
Squa*bash"	v. t.
Squab"bish	a.
Squab"ble	v. i.
Squab"ble	v. t.
Squab"ble	n.
Squab"bler	n.
Squab"by	a.
Squab"-chick`	n.
Squac"co	n.
Squad	n.
Squad	n.
Squad"ron	n.
Squad"roned	a.
Squail	v. i.
Squai"mous	a.
Squa"li	n. pl.
Squal"id	a.
Squa*lid"i*ty	n.
Squal"id*ly	adv.
Squal"id*ness	n.
Squall	n.
Squall	v. i.
Squall	n.
Squall"er	n.
Squall"y	a.
Squa"lo*don	n.
Squa"lo*dont	a.
Squa"loid	a.
Squa"lor	n.
Squam	n.
Squa"ma	n.
Squa*ma"ceous	a.
Squa*ma"ta	n. pl.
Squa"mate	a.
Squam" duck`	n.
Squa*mel"la	n.
Squa*mel"late	a.
Squa"mi*form	a.
Squa*mig"er*ous	a.
Squam"i*pen	n.
Squa"moid	a.
Squa*mo"sal	a.
Squa*mose"	a.
Squa`mo*zyg`o*mat"ic	a.
Squam"u*la	n.
Squam"u*late	a.
Squam"ule	n.
Squam"u*lose`	a.
Squan"der	v. t.
Squan"der	v. i.
Squan"der	n.
Squan"der*er	n.
Squan"der*ing*ly	adv.
Square	n.
Square	a.
Square	v. t.
Square	v. i.
Square"ly	adv.
Square"ness	n.
Squar"er	n.
Square"-rigged`	a.
Square"-toed`	a.
Square"-toes`	n.
Squar"ish	a.
Squar*rose"	a.
Squar*ro`so-den"tate	a.
Squar"rous	a.
Squar"ru*lose`	a.
Squash	n.
Squash	n.
Squash	v. t.
Squash	n.
Squash"er	n.
Squash"i*ness	n.
Squash"y	a.
Squat	n.
Squat	v. i.
Squat	v. t.
Squat	a.
Squat	n.
Squat"er*ole	n.
Squat"ter	n.
Squat"ty	a.
Squaw	n.
Squaw"ber`ry	n.
Squawk	v. i.
Squawk	n.
Squawl	v. i.
Squaw man	n.
Squaw vine	n.
Squeak	v. i.
Squeak	n.
Squeak"er	n.
Squeak"ing*ly	adv.
Squeal	v. i.
Squeal	n.
Squeal"er	n.
Squeam"ish	a.
Squeam"ous	a.
Squea"si*ness	n.
Squea"sy	a.
Squee"gee	n.
Squee"gee	v. t.
Squeegee roller	v. t.
Squeeze	v. i.
Squeeze	n.
Squeez"er	n.
Squeez"ing	n.
Squelch	v. t.
Squelch	n.
Squelch	v. i.
sque*teague"	n.
Squib	n.
Squib	v. i.
Squid	n.
Squier	n.
Squi"er*ie	n.
Squif"fy	a.
Squig"gle	v. i.
Squig"gle	v. i.
Squil"gee	n.
Squil"gee	v. t.
Squill	n.
Squil"la	n.
Squill*it"ic	a.
Squin"ance	n.
Squinch	n.
Squin"sy	n.
Squint	a.
Squint	v. i.
Squint	v. t.
Squint	n.
Squint"er	n.
Squint"-eye`	n.
Squint"-eyed`	a.
Squint`i*fe"go	a.
Squint"ing	a. & n.
Squin"y	v. i.
Squin"zey	n.
Squir	v. t.
Squir"al*ty	n.
Squir"arch	n.
Squir"arch*y	n.
Squire	n.
Squire	n.
Squire	v. t.
Squir*een"	n.
Squire"hood	n.
squire"ling	n.
Squire"ly	a. & adv.
squire"ship	n.
Squirm	v. i.
Squirr	v. t.
Squir"rel	n.
Squirt	v. t.
Squirt	v. i.
Squirt	n.
Squirt"er	n.
Squir"y	n.
squish	v. i.
squish	n.
Squitch" grass`	n.
Stab	v. t.
Stab	v. i.
Stab	n.
Sta"bat Ma"ter	n.
Stab"bing*ly	adv.
Stab culture	n.
Sta*bil"i*tate	v. t.
Sta*bil"i*ty	n.
Sta"ble	a.
Sta"ble	v. t.
Sta"ble	n.
Sta"ble	v. t.
Sta"ble	v. i.
Sta"ble*boy`	n.
Sta"ble*ness	n.
Sta"bler	n.
Sta"ble stand`	n.
Stab"lish	v. t.
Stab"lish*ment	n.
Sta"bly	adv.
Stab`u*la"tion	n.
Stac*ca"to	a.
Stack	n.
Stack	v. t.
Stack"age	n.
Stack"et	n.
Stack"-guard`	n.
Stack"ing	a. & n.
Stack"stand`	n.
Stack"yard`	n.
Stac"te	n.
Stad"dle	n.
Stad"dle	v. t.
Stade	n.
Stade	n.
Sta*dim"e*ter	n.
Sta"di*a hairs	n.
Stadt"hold`er	n.
Stadt"hold`er*ate	n.
Sta*fette"	n.
Staff	n.
Staff	n.
Staf"fi*er	n.
Staff"ish	a.
Staff"man	n.
Stag	n.
Stag	v. i.
Stag	v. t.
Stage	n.
Stage	v. t.
Stage"coach`	n.
Stage"coach`man	n.
Stage director	n.
Stage"ly	a.
Stage manager	n.
Stage"play`er	n.
Sta"ger	n.
Sta"ger*y	n.
Stage"-struck`	a.
Stag"-e`vil	n.
Stag"gard	n.
Stag"ger	v. i.
Stag"ger	v. t.
Stag"ger	n.
Stag"ger*bush`	n.
Stag"ger*ing*ly	adv.
Stag"ger*wort`	n.
Stag"-horn` cor"al	a.
Stag"hound`	n.
Sta"ging	n.
Stag"i*rite	n.
Stag"nan*cy	n.
Stag"nant	a.
Stag"nant*ly	adv.
Stag"nate	v. i.
Stag"nate	a.
Stag*na"tion	n.
Stag"worm`	n.
Sta"gy	a.
Stahl"ian	a.
Stahl"ian	n.
Stahl"ism	n.
Staid	imp. & p. p.
Staid	a.
Staid"ly	adv.
Staid"ness	n.
Stail	n.
Stain	v. t.
Stain	v. i.
Stain	n.
Stain"er	n.
Stain"less	a.
Stain"less*ly	adv.
Stair	n.
Stair"case`	n.
Stair"head`	n.
Stair"way`	n.
Staith	n.
Staith"man	n.
Stake	n.
Stake	v. t.
Stake"-driv`er	n.
Stake"head`	n.
Stake"hold`er	n.
Stak*tom"e*ter	n.
Stal	imp.
Sta*lac"tic	a.
Sta*lac"ti*form	a.
Sta*lac"tite	n.
Stal`ac*ti"tes	n.
Stal`ac*tit"ic	a.
Stal`ac*tit"i*form	a.
Sta*lag"mite	n.
Stal`ag*mit"ic	a.
Stal"der	n.
Stale	n.
Stale	a.
Stale	v. t.
Stale	v. i.
Stale	n.
Stale	n.
Stale"ly	adv.
Stale"mate`	n.
Stale"mate`	v. t.
Stale"ness	n.
Stalk	n.
Stalk	v. i.
Stalk	v. t.
Stalk	n.
Stalked	a.
Stalk"er	n.
Stalk"-eyed`	a.
Stalk"ing-horse`	n.
Stalk"less	a.
Stalk"y	a.
Stall	n.
Stall	v. t.
Stall	v. i.
Stall"age	n.
Stal*la"tion	n.
Stalled	a.
Stall"er	n.
Stall"-feed`	v. t.
Stall"ing	n.
Stal"lion	n.
Stall"man	n.
Stal"lon	n.
Stal"wart	a.
Stal"wart*ly	adv.
Stal"wart*ness	n.
Stal"worth*hood	n.
Sta"men	n.
Sta"mened	a.
Sta"min	n.
Stam"i*na	n. pl.
Stam"i*na	n. pl.
Stam"i*nal	a.
Stam"i*nate	a.
Stam"i*nate	v. t.
Sta*min"e*al	a.
Stam`i*nif"er*ous	a.
Stam"i*node	n.
Stam`i*no"di*um	n.
Stam"mel	n.
Stam"mel	n.
Stam"mel	a.
Stam"mer	v. i.
Stam"mer	v. t.
Stam"mer	n.
Stam"mer*er	n.
Stam"mer*ing	a.
Stam"mer*ing	n.
Stamp	v. t.
Stamp	v. i.
Stamp	n.
Stam*pede"	n.
Stam*pede"	v. i.
Stam*pede"	v. t.
Stamp"er	n.
Stamp"ing	a. & n.
Stance	n.
Stanch	v. t.
Stanch	v. i.
Stanch	n.
Stanch	a.
Stanch	v. t.
Stan"chel	n.
Stanch"er	n.
Stan"chion	n.
Stanch"less	a.
Stanch"ly	adv.
Stanch"ness	n.
Stand	v. i.
Stand	v. t.
Stand	n.
Stand"age	n.
Stand"ard	n.
Stand"ard	a.
Stand"ard-bred`	a.
Stand"ard*ize	v. t.
Stand"ard-wing`	n.
Stand"-by`	n.
Stand"el	n.
Stand"er	n.
St<aum/n"de*rath`	n.
Stand"er-by`	n.
Stand"er*grass`	n.
Stand"gale`	n.
Stand"ing	a.
Stand"ing	n.
Stand"ish	n.
stand"off	n.
stand"off	a.
stand*off"ish	a.
Stand"pipe`	n.
Stand"point`	n.
stands	n.
Stand"still`	n.
Stane	n.
Stang	imp.
Stang	n.
Stang	v. i.
Stan"hope	n.
Stan"iel	n.
Stan"iel*ry	n.
Stank	a.
Stank	v. i.
Stank	imp.
Stank	n.
Stan"na*ry	a.
Stan"na*ry	n.
Stan"nate	n.
Stan"nel	n.
Stan"nic	a.
Stan*nif"er*ous	a.
Stan"nine	n.
Stan"no-	n.
Stan*no"so-	a.
Stan"no*type	n.
Stan"nous	a.
Stan"num	n.
Stann"yel	n.
Stant	3d pers. sing. pres.
Stan"za	n.
Stan*za"ic	a.
Sta*pe"di*al	a.
Sta*pe"li*a	n.
Sta"pes	n.
Staph"y*line	a.
Staph`y*li"nid	n.
Staph`y*lo"ma	n.
Staph`y*lo"ma*tous	a.
Staph"y*lo*plas`ty	n.
Staph`y*lor"a*phy	n.
Staph`y*lot"o*my	n.
Sta"ple	n.
Sta"ple	a.
sta"ple	v. t.
sta"ple gun`	n.
Sta"pler	n.
Star	n.
Star	v. t.
Star	v. i.
Star"-blind`	a.
Star"board`	n.
Star"board`	a.
Star"board`	v. t.
Star"-bow`lines	n. pl.
Starch	a.
Starch	n.
Starch	v. t.
Star" cham`ber	n.
Starched	a.
Starch"ed*ness	n.
Starch"er	n.
starch"i*ness	n.
Starch"ly	adv.
Starch"ness	n.
Starch"wort`	n.
starch"y	a.
Star"craft	n.
Star"-crossed`	a.
Star drift	n.
stare	v. i.
Stare	v. t.
Stare	n.
Star"er	n.
Starf	imp.
Star"finch`	n.
Star"fish`	n.
Star"gaz`er	n.
Star"gaz`ing	n.
Star"ing*ly	adv.
Stark	a.
Stark	adv.
Stark	v. t.
Stark"ly	adv.
Stark"ness	n.
Star"less	a.
Star"light`	n.
Star"light`	a.
Star"like`	a.
Star"ling	n.
Star"lit`	a.
Star"mon`ger	n.
Starn	n.
Star"nose`	n.
Star" of Dav"id	n.
Star"os*ty	n.
Star"proof`	a.
Star"-read`	n.
Starred	a.
Star"ri*ness	n.
Star"ry	a.
Star"shine`	n.
Star"shoot`	n.
Star"-span`gled	a.
Star stereogram	n.
start	v. i.
Start	v. t.
Start	n.
Start	n.
START	n.
Start"er	n.
Start"ful	a.
Start"ful*ness	n.
Star"throat`	n.
Start"ing	a. & n.
Start"ing*ly	adv.
Start"ish	a.
Star"tle	v. i.
Star"tle	v. t.
Star"tle	n.
Star"tling*ly	adv.
Star"tlish	a.
Start"-up`	n.
Start"-up`	a.
Star*va"tion	n.
Starve	v. i.
Starve	v. t.
Starv"ed*ly	adv.
Starve"ling	n.
Starve"ling	a.
Star"wort`	n.
Stas"i*mon	n.
Sta"sis	n.
Stat"a*ble	a.
Sta"tal	a.
Sta"tant	a.
Sta*ta"ri*an	a.
Sta*ta"ri*an*ly	adv.
Sta"ta*ry	a.
State	n.
State	a.
State	v. t.
State	n.
State"craft`	n.
Stat"ed	a.
Stat"ed*ly	adv.
State"ful	a.
State"hood	n.
State"house`	n.
State"less	a.
State"li*ly	adv.
State"li*ness	n.
State"ly	a.
State"ly	adv.
State"ment	n.
State"mon`ger	n.
State` pris"on	n.
Stat"er	n.
Sta"ter	n.
State"room`	n.
States"-gen"er*al	n.
States"man	n.
States"man*like`	a.
States"man*ly	a.
States"man*ship	n.
State socialism	n.
Stath"mo*graph	n.
Stat"ic	a.
Stat"ic*al*ly	adv.
Stat"ics	n.
Stat"ing	n.
Sta"tion	n.
Sta"tion	v. t.
Sta"tion*al	a.
Sta"tion*a*ri*ness	n.
Sta"tion*a*ry	a.
Sta"tion*a*ry	n.
Sta"tion*er	n.
Sta"tion*er*y	n.
Sta"tion*er*y	a.
Sta"tism	n.
Sta"tist	n.
Sta*tis"tic	a.
Sta*tis"tic*al*ly	adv.
Stat`is*ti"cian	n.
Sta*tis"tics	n.
Stat`is*tol"o*gy	n.
Sta"tive	a.
Stat"o*blast	n.
Sta*toc"ra*cy	n.
sta"tor	n.
stats	n.
Stat"u*a	n.
Stat"u*a*ry	n.
Stat"ue	n.
Stat"ue	v. t.
Stat"ued	a.
Stat"ue*less	a.
Stat"ue*like`	a.
Stat`u*esque"	a.
Stat`u*esque"ly	adv.
Stat`u*ette"	n.
Sta*tu"mi*nate	v. t.
Stat"ure	n.
Stat"ured	a.
Sta"tus	n.
Sta"tus in` quo"	a.
Stat"u*ta*bly	adv.
Stat"ute	n.
Stat"u*to*ry	a.
Staunch	n.
Stau`ro*lit"ic	a.
Stau"ro*scope	n.
Stau"ro*tide	n.
Stave	n.
Stave	v. t.
Stave	v. i.
Staves	n.
Staves"a`cre	n.
Stave"wood`	n.
Stav"ing	n.
Staw	v. i.
Stay	n.
Stay	v. t.
Stay	v. i.
Stay	n.
Stayed	a.
Stayed"ly	adv.
Stayed"ness	n.
Stay"er	n.
Stay"lace`	n.
Stay"less	a.
Stay"mak`er	n.
Stay"nil	n.
Stay"sail`	n.
Stay"ship`	n.
Stead	n.
Stead	v. t.
Stead"fast	a.
Stead"fast*ly	adv.
Stead"fast*ness	n.
Stead"i*ly	adv.
Stead"i*ness	n.
Stead"ing	n.
Stead"y	a.
Stead"y	v. t.
Stead"y	v. i.
Steak	n.
Steal	n.
Steal	v. t.
Steal	v. i.
Steal"er	n.
Steal"ing	n.
Steal"ing*ly	adv.
Stealth	n.
Stealth"ful	a.
Stealth"i*ly	adv.
Stealth"i*ness	n.
Stealth"like`	a.
Stealth"y	a.
Steam	n.
Steam	v. i.
Steam	v. t.
Steam"boat`	n.
Steam"boat`ing	n.
Steam" en"gine	n.
Steam"i*ness	n.
Steam"ship`	n.
Steam` up"	v. t.
Steam"y	a.
Stean	n. & v.
Stean"ing	n.
Ste*ap"sin	n.
Ste"a*rate	n.
Ste*ar"ic	a.
Ste"a*rin	n.
Ste`a*rol"ic	a.
Ste"a*rone	n.
Ste`a*rop"tene	n.
Ste`ar*rhe"a	n.
Ste"a*ryl	n.
Ste"a*tite	n.
Ste`a*tit"ic	a.
Ste`a*to"ma	n.
Ste`a*tom"a*tous	a.
Ste`a*top"y*ga	n.
Ste`a*top"y*gous	a.
Sted	n.
Stee	n.
Steed	n.
Steed"less	a.
Steek	v. t.
Steel	n.
Steel	v. t.
Steel"bow` goods"	n.
Steel"er	n.
Steel"head`	n.
Steel"i*ness	n.
Steel"ing	n.
Steel"y	a.
Steel"yard	n.
Steem	v. & n.
Steem	v. & n.
Steen	n.
Steen	v. t.
Steen"bok`	n.
Steen"ing	n.
Steen"kirk`	n.
Steep	a.
Steep	v. t.
Steep	v. i.
Steep	n.
Steep	a.
Steep	n.
Steep"-down`	a.
Steep"en	v. i.
Steep"er	n.
Steep"i*ness	n.
Steep"ish	a.
Stee"ple	n.
Stee"ple*chas`ing	n.
Stee"ple-crowned`	a.
Stee"pled	a.
Steep"ly	adv.
Steep"ness	n.
Steep"-up`	a.
Steep"y	a.
Steer	n.
Steer	v. t.
Steer	v. t.
Steer	v. i.
Steer	n.
Steer	n.
Steer"a*ble	a.
Steer"age	n.
Steer"age*way`	n.
Steer"er	n.
Steer"ing	a. & n.
Steer"less	a.
Steer"ling	n.
Steers"man	n.
Steers"mate	n.
Steeve	v. i.
Steeve	v. t.
Steeve	n.
Steev"ing	n.
Steg	n.
Steg`a*nog"ra*phist	n.
Steg`a*nog"ra*phy	n.
Steg`a*noph*thal"ma*ta	n. pl.
Ste*gan"o*pod	n.
Steg`a*nop"o*des	n. pl.
Steg`a*nop"o*dous	a.
Steg*no"sis	n.
Steg*no"tic	a.
Steg`o*ceph"a*la	n. pl.
Steg`o*sau"ri*a	n. pl.
Steg`o*sau"rus	n.
Steik	v. t.
Stein	n. & v.
Stein"bock`	n.
Stein"gale	n.
Stein"ing	n.
Stein"kirk`	n.
Stein"kle	n.
Ste"la	n.
Ste"le	n.
Stele	n.
Ste"lene	a.
Stell	v. t.
Stell	n.
Stel"lar	a.
Stel"late	a.
Stel*la"tion	n.
Stelled	a.
stel"ler	n.
Stel"ler*id	n.
Stel*ler"i*da	n. pl.
Stel*ler"i*dan	n.
Stel"ler's sea" cow`	prop. n.
Stel*lif"er*ous	a.
Stel"li*form	a.
Stel"li*fy	v. t.
Stel"lion	n.
Stel"lion*ate	n.
Stel"lu*lar	a.
Stel"lu*late	a.
Stel`ma*top"o*da	n. pl.
Ste*log"ra*phy	n.
Stem	v. i.
Stem	n.
Stem	n.
Stem	v. t.
Stem	v. t.
Stem	v. i.
Stem"-clasp`ing	a.
Stem"less	a.
Stem"let	n.
Stem"ma	n.
Stem"mer	n.
Stem"mer*y	n.
Stem"my	a.
Stem"ple	n.
Stem"son	n.
Stem"-wind`er	n.
Stem"-wind`ing	a.
Stench	v. t.
Stench	n.
Stench	v. t.
Stench"y	a.
Sten"cil	n.
Sten"cil	v. t.
Sten"cil*er	n.
Sten"o*derm	n.
Sten`o*der"mine	a.
Sten"o*graph	v. t.
Sten"o*graph	n.
Ste*nog"ra*pher	n.
Sten`o*graph"ic	a.
Ste*nog"ra*phist	n.
Ste*nog"ra*phy	n.
Ste*noph"yl*lous	a.
Ste*no"sis	n.
Sten"o*stome	a.
Stent	v. t.
Stent	v. i.
Stent	n.
Stent"ing	n.
Sten"tor	n.
Sten*to"ri*an	a.
Sten"to*rin	n.
Sten*to"ri*ous	a.
Sten`to*ron"ic	a.
Sten`to*ro*phon"ic	a.
Step	v. i.
Step	v. t.
Step	n.
Step-	n.
Step"child`	n.
Step"dame`	n.
Step"daugh`ter	n.
Step"-down`	a.
Step"fa`ther	n.
Ste*pha"ni*on	n.
Steph"an*ite	n.
Steph`a*no"tis	n.
Step"lad`der	n.
Step"moth`er	n.
Step"par`ent	n.
Steppe	n.
Stepped	a.
Step"per	n.
Step"ping-stone`	n.
Step"sis`ter	n.
Step"son`	n.
Step"stone`	n.
Step"-up`	a.
-ster	n.
Ster"co*lin	n.
Ster`co*ra"ceous	a.
Ster"co*ra*nism	n.
Ster"co*ra*nist	n.
Ster`co*ra"ri*an	n.
Ster"co*ra*ry	n.
Ster"co*rate	n.
Ster`co*ra"tion	n.
Ster*co"ri*an*ism	n.
Ster"co*rin	n.
Ster"co*ry	n.
Ster*cu`li*a"ceous	a.
Stere	n.
Stere	v. t. & i.
Stere	n.
Stere	n.
Ster`el*min"tha	n. pl.
Ste"re*o-	n.
Ste`re*o-chem"ic	a.
Ste`re*o-chem"is*try	n.
Ste"re*o*chrome	n.
Ste`re*o*chro"mic	a.
Ste`re*och"ro*my	n.
Ste`re*o*e*lec"tric	a.
Ste"re*o*gram	n.
Ste"re*o*graph	n.
Ste`re*o*graph"ic	a.
Ste`re*o*graph"ic*al*ly	adv.
Ste`re*og"ra*phy	n.
Ste`re*om"e*ter	n.
Ste`re*o*met"ric	a.
Ste`re*om"e*try	n.
Ste`re*o*mon"o*scope	n.
Ste"re*o*plasm	n.
Ste`re*op"ti*con	n.
Ste"re*o*scope	n.
Ste`re*o*scop"ic	a.
Ste`re*os"co*pist	n.
Ste`re*os"co*py	n.
Ste`re*o*stat"ic	a.
Ste`re*o*tom"ic	a.
Ste`re*ot"o*my	n.
Ste"re*o*type	n.
Ste"re*o*type	v. t.
Ste"re*o*typed	a.
Ste"re*o*ty`per	n.
Ste"re*o*ty`per*y	n.
Ste`re*o*typ"ic	a.
Ste"re*o*ty`pist	n.
Ste`re*o*ty*pog"ra*pher	n.
Ste`re*o*ty*pog"ra*phy	n.
Ste"re*o*ty`py	n.
Ster`hy*drau"lic	a.
Ster"ile	a.
Ste*ril"i*ty	n.
Ster`il*i*za"tion	n.
Ster"il*ize	v. t.
Ster"il*i`zer	n.
Ster"let	n.
Ster"ling	n.
Ster"ling	n.
Ster"ling	a.
Stern	n.
Stern	a.
Stern	n.
Stern	a.
Stern"age	n.
Ster"nal	a.
Stern"berg*ite	n.
Ster"ne*bra	n.
Sterned	a.
Stern"er	n.
Stern`fore"most`	adv.
Ster"nite	n.
Stern"ly	adv.
Stern"most`	a.
Stern"ness	n.
Ster"no-	a.
Ster`no*cos"tal	a.
Ster`no*hy"oid	a.
Ster`no*mas"toid	a.
Ster`no*thy"roid	a.
Stern"post`	n.
Sterns"man	n.
Stern"son	n.
Ster"num	n.
Ster`nu*ta"tion	n.
Ster*nu"ta*tive	a.
Ster*nu"ta*to*ry	a.
Stern"way`	n.
Stern"-wheel`	a.
Stern"-wheel`er	n.
Ster*quil"i*nous	a.
Ster"re	n.
Ster"rink	n.
Ster"ro*met`al	n.
Stert	p. p.
Ster"te	p. p.
Ster*to"ri*ous	a.
Ster"to*rous	a.
Sterve	v. t. & i.
Stet	subj. 3d pers. sing.
Stet	v. t.
Steth"al	n.
Steth"o*graph	n.
Ste*thom"e*ter	n.
Steth"o*scope	n.
Steth"o*scope	v. t.
Steth`o*scop"ic	a.
Ste*thos"co*pist	n.
Ste*thos"co*py	n.
Steve	v. t.
Ste"ve*dore`	n.
Ste"ven	n.
Stew	n.
Stew	v. t.
Stew	v. i.
Stew	n.
Stew"ard	n.
Stew"ard	v. t.
Stew"ard*ess	n.
Stew"ard*ly	adv.
Stew"ard*ship	n.
Stew"art*ry	n.
Stew"ish	a.
Stew"pan`	n.
Stew"pot`	n.
Stey	n.
Sthen"ic	a.
Sti*ac*cia"to	n.
Sti"an	n.
Stib"born	a.
Stib"i*al	a.
Stib"i*al*ism	n.
Stib"i*a`ted	a.
Stib"ic	a.
Stib"i*co*nite	n.
Stib"ine	n.
Stib"i*ous	a.
Stib"i*um	n.
Stib"nite	n.
Sti*bo"ni*um	n.
Stic*ca"do	n.
Stich	n.
Stich"ic	a.
Sti*chid"i*um	n.
Stich"o*man`cy	n.
Stich`o*met"ric*al	a.
Stich*om"e*try	n.
Stich"wort`	n.
Stick	n.
Stick	v. t.
Stick	v. i.
Stick"ed	imp.
Stick"er	n.
Stick"ful	n.
Stick"i*ness	n.
Stick"ing	a. & n.
Stick"it	a.
Stick"-lac`	n.
Stic"kle	v. i.
Stic"kle	v. t.
Stic"kle	n.
Stic"kle*back`	n.
Stic"kler	n.
Stick"-seed`	n.
Stick"tail`	n.
stick"-tight`	n.
Stick"y	a.
Stid"dy	n.
Stiff	a.
Stiff"-backed`	a.
Stiff"en	v. t.
Stiff"en	v. i.
Stiff"en*er	n.
Stiff"en*ing	n.
Stiff"-heart`ed	a.
Stiff"ish	a.
Stiff"ly	adv.
Stiff"-necked`	a.
Stiff"-neck`ed*ness	n.
Stiff"ness	n.
Stiff"tail`	n.
Stiff"-tailed`	a.
Sti"fle	n.
Sti"fle	v. t.
Sti"fle	v. i.
Sti"fled	a.
Sti"fler	n.
Stig"ma	n.
Stig*ma"ri*a	n.
Stig"ma*ta	n.
Stig*mat"ic	n.
Stig*mat"ic	a.
Stig*mat"ic*al*ly	adv.
Stig"ma*tist	n.
Stig`ma*ti*za"tion	n.
Stig"ma*tize	v. t.
Stig"ma*tose`	a.
Stig"o*no*man`cy	n.
Stike	n.
Sti"lar	a.
Stil"bene	n.
Stil"bite	n.
Stile	n.
Stile	n.
Sti"let	n.
Sti*let"to	n.
Sti*let"to	v. t.
Still	a.
Still	n.
Still	adv.
Still	v. t.
Still	n.
Still	v. t.
Still	v. i.
Stil"lage	n.
Stil`la*ti"tious	a.
Stil"la*to*ry	n.
Still"birth`	n.
Still"born`	a.
Still"-burn`	v. t.
Still"-clos"ing	a.
Still"er	n.
Still"house`	n.
Still"-hunt`	n.
Stil"li*cide	n.
Stil`li*cid"i*ous	a.
Stil"li*form	a.
Still"ing	n.
Stil"lion	n.
Still" life	n.
Still"ness	n.
Still"room`	n.
Still"son wrench	n.
Still" wat*er	n.
Still" wine`	n.
Still"y	a.
Stil"ly	adv.
Stilp*nom"e*lane	n.
Stilt	n.
Stilt	v. t.
Stilt"bird`	n.
Stilt"ed	a.
Stilt"i*fy	v. t.
Stil"ton cheese"	n.
Stilt"y	a.
Stime	n.
Sti"mey	n. & v. t.
Stim"u*lant	a.
Stim"u*lant	n.
Stim"u*late	v. t.
Stim`u*la"tion	n.
Stim"u*la*tive	a.
Stim"u*la`tor	n.
Stim"u*la`tress	n.
Stim"u*lism	n.
Stim"u*lus	n.
Sting	n.
Sting	v. t.
Sting`a*ree"	n.
Sting"bull`	n.
Sting"er	n.
Sting"fish`	n.
Stin"gi*ly	adv.
Stin"gi*ness	n.
Sting"ing	a.
Sting"less	a.
Stin"go	n.
Sting ray	n.
Sting"tail`	n.
Sting"y	a.
Stin"gy	a.
Stink	v. i.
Stink	v. t.
Stink	n.
Stink"ard	n.
Stink"ball`	n.
Stink"er	n.
Stink"horn`	n.
Stink"ing	a. & n.
Stink"ing*ly	adv.
Stink"pot`	n.
Stink"stone`	n.
Stink"weed`	n.
Stink"wood`	n.
Stint	n.
Stint	v. t.
Stint	v. i.
Stint	n.
Stint"ance	n.
Stint"ed*ness	n.
Stint"er	n.
Stint"less	a.
Stipe	n.
Sti"pel	n.
Sti*pel"late	a.
Sti"pend	n.
Sti"pend	v. t.
Sti*pen`di*a"ri*an	a.
Sti*pen"di*a*ry	a.
Sti*pen"di*a*ry	n.
Sti*pen"di*ate	v. t.
Sti"pend*less	a.
Sti"pes	n.
Stip"i*tate	a.
Stip"i*ti*form	a.
Stip"ple	v. t.
Stip"ple	n.
Stip"tic	a. & n.
Stip"u*la	n.
Stip`u*la"ceous	a.
Stip"u*la*ry	a.
Stip"u*late	a.
Stip"u*late	v. i.
Stip`u*la"tion	n.
Stip`u*la"tion	n.
Stip"u*la`tor	n.
Stip"ule	n.
Stip"uled	a.
Stir	v. t.
Stir	v. i.
Stir	n.
Stir"a*bout`	n.
Stir"i*a`ted	a.
Stir"i*ous	a.
Stirk	n.
Stir"less	a.
Stirp	n.
Stir"pi*cul`ture	n.
Stirps	n.
Stir"rage	n.
Stir"rer	n.
Stir"ring	a.
Stir"rup	n.
Stirt	p. p.
Stir"te	imp.
Stitch	n.
Stitch	v. t.
Stitch	v. i.
Stitch"el	n.
Stitch"er	n.
Stitch"er*y	n.
Stitch"ing	n.
Stitch"wort`	n.
Stith	a.
Stith	n.
Stith"y	n.
Stith"y	v. t.
Stive	v. t.
Stive	v. i.
Stive	n.
Sti"ver	n.
Stives	n. pl.
Stoak	v. t.
Stoat	n.
Sto"cah	n.
Stoc*cade"	n. & v.
Stoc*ca"do	n.
Sto*chas"tic	a.
Stock	n.
Stock	v. t.
Stock	a.
Stock*ade"	n.
Stock*ade"	v. t.
Stock"-blind`	a.
Stock"bro`ker	n.
Stock"dove`	n.
Stock"er	n.
Stock"fish`	n.
Stock"hold`er	n.
Stock`i*net"	n.
Stock"ing	n.
Stock"ing	v. t.
Stock"ing*er	n.
Stock"ish	a.
Stock"job`ber	n.
Stock"job`bing	n.
Stock"man	n.
Stock"-still`	a.
Stock"work`	n.
Stock"y	a.
Stodg"y	a.
Stoech`i*ol"o*gy	n.
Sto"gie	n.
Sto"gy	a.
Sto"gy	n.
Sto"ic	n.
Sto"ic	a.
Stoi`chi*o*log"ic*al	a.
Stoi`chi*ol"o*gy	n.
Stoi`chi*o*met"ric	a.
Stoi`chi*om"e*try	n.
Sto"i*cism	n.
Sto*ic"i*ty	n.
Stoke	v. t.
Stoke	v. i.
Stoke"hold`	n.
Stoke"hole`	n.
Stok"er	n.
Sto"key	a.
Sto"la	n.
Stole	imp.
Stole	n.
Stole	n.
Stoled	a.
Stol"en	p. p.
Stol"id	a.
Sto*lid"i*ty	n.
Stol"id*ness	n.
Sto"lon	n.
Stol`o*nif"er*ous	a.
Sto"ma	n.
Stom"ach	n.
Stom"ach	v. t.
Stom"ach	v. i.
Stom"ach*al	a.
Stom"ach*al	n.
Stom"ach*er	n.
Stom"ach*ful	a.
Sto*mach"ic	a.
Sto*mach"ic	n.
Stom"ach*ing	n.
Stom"ach*less	a.
Stom"ach*ous	a.
Stom"ach*y	a.
Sto"ma*pod	n.
Sto*map"o*da	n. pl.
Sto"mate	n.
Sto*mat"ic	a.
Sto*mat"ic	n.
Stom`a*tif"er*ous	a.
Stom`a*ti"tis	n.
Stom`a*to"da	n. pl.
Stom`a*to*dae"um	n.
Stom"a*tode	a.
Stom`a*to*gas"tric	a.
Sto`ma*tol"o*gy	n.
Stom`a*to*plas"tic	a.
Stom"a*to*plas`ty	n.
Stom"a*to*pod	n.
Stom`a*top"o*da	n. pl.
Stom`a*top"o*dous	a.
Stom"a*to*scope	n.
Stom"a*tous	a.
Stom`o*dae"um	n.
Stomp	v. i.
stomping ground	n.
Stond	n.
Stond	v. i.
Stone	n.
Stone	v. t.
Stone"bird`	n.
Stone"-blind`	a.
Stone"bow`	n.
Stone"brash`	n.
Stone"brear`er	n.
Stone"buck`	n.
Stone"chat`	n.
Stone"-cold`	a.
Stone"cray`	n.
Stone"crop`	n.
Stone"cut`ter	n.
Stone"cut`ting	n.
Stone"-dead`	a.
Stone"-deaf`	a.
Stone"gall`	n.
Stone"hatch`	n.
Stone"-heart`ed	a.
Stone"henge	n.
Stone"-horse`	n.
Ston"er	n.
Stone"root`	n.
Stone"run`ner	n.
Stone"smic`kle	n.
Stone"-still`	a.
Stone"ware`	n.
Stone"weed`	n.
Stone"work`	n.
Stone"wort`	n.
Ston"i*ly	adv.
Ston"i*ness	n.
Ston"ish	a.
Stont	3d pers. sing. present
Ston"y	a.
Stood	imp. & p. p.
Stook	n.
Stook	v. t.
Stool	n.
Stool	v. i.
Stool	n.
Stool"ball`	n.
Stoom	v. t.
Stoop	n.
Stoop	n.
Stoop	n.
Stoop	v. i.
Stoop	v. t.
Stoop	n.
Stoop"er	n.
Stoop"ing	a. & n.
Stoor	v. i.
Stoor	a.
Stop	v. t.
Stop	v. i.
Stop	n.
Stop"cock`	n.
Stope	n.
Stope	v. t.
Stope	p. p.
Stop"-gap`	n.
Stop"ing	n.
Stop"less	a.
Stop order	a.
Stop"o`ver	n.
Stop"page	n.
Stopped	a.
Stop"per	n.
Stop"per	v. t.
Stop"ping	n.
Stop"ping-out`	n.
Stop"ple	n.
Stop"ple	v. t.
Stop"ship`	n.
Stor	a.
Stor"age	n.
Sto"rax	n.
Store	n.
Store	a.
Store	v. t.
Stored	a.
Store"house`	n.
Store"keep`er	n.
Stor"er	n.
Store"room`	n.
Store"ship`	n.
Sto"rey	n.
Stor"ge	n.
Sto"ri*al	a.
Sto"ried	a.
Sto"ri*er	n.
Sto"ri*fy	v. t.
Stork	n.
Stork"-billed`	a.
Storm	n.
Storm	v. t.
Storm	v. i.
Storm"-beat`	a.
Storm"cock`	n.
Storm"finch`	n.
Storm"ful	a.
Storm"glass`	n.
Storm"i*ly	adv.
Storm"i*ness	n.
Storm"ing	a. & n.
Storm"less	a.
Storm"wind`	n.
Storm"y	a.
Stor"thing	n.
Stor"ven	p. p.
Sto"ry	n.
Sto"ry	n.
Sto"ry	v. t.
Sto"ry*book`	n.
Sto"ry-tell`er	n.
Sto"ry-tell`ing	a.
Sto"ry-writ`er	n.
Stot	n.
Stote	n.
Stound	v. i.
Stound	a.
Stound	n.
Stound	n.
Stound	n.
Stoup	n.
Stour	n.
Stour	a.
Stout	a.
stout	n.
Stout"-heart`ed	a.
Stout"ish	a.
Stout"ly	adv.
Stout"ness	n.
Sto"va*in	n.
Stove	imp.
Stove	n.
Stove	v. t.
Stove"house`	n.
Stove"pipe`	n.
Sto"ver	n.
Stow	v. t.
Stow"age	n.
Stow"a*way`	n.
Stow"board	n.
Stowce	n.
Stow"ing	n.
Stowre	a.
Stowre	n.
Stra"bism	n.
Stra`bis*mom"e*ter	n.
Stra*bis"mus	n.
Stra*bot"o*my	n.
Strad"dle	v. i.
Strad"dle	v. t.
Strad"dle	n.
Strad"dling	a.
Strad`o*met"ric*al	a.
Strag"gle	v. i.
Strag"gle	n.
Strag"gler	n.
Strag"gling	a. & n.
Strag"gling*ly	adv.
Strag"u*lum	n.
Straight	a.
Straight	a.
Straight	adv.
Straight	n.
Straight	v. t.
Straight"edge`	n.
Straight"en	v. t.
Straight"en	v. t.
Straight"en*er	n.
Straight"forth`	adv.
Straight`for"ward	a.
Straight"horn`	n.
Straight"-joint`	a.
Straight"-lined`	a.
Straight"ly	adv.
Straight"ly	adv.
Straight"ness	n.
Straight"ness	n.
Straight"-out`	a.
Straight"-pight`	a.
Straight"-spo`ken	a.
Straight"way`	adv.
Straight"ways`	adv.
Straik	n.
Strain	n.
Strain	v. t.
Strain	v. i.
Strain	n.
Strain"a*ble	a.
Strain"a*bly	adv.
Strained	a.
Strain"er	n.
Strain"ing	a. & n.
Straint	n.
Strait	a.
Strait	a.
Strait	adv.
Strait	n.
Strait	v. t.
Strait"en	v. t.
Strait"-hand`ed	a.
Strait"-jack`et	n.
Strait"-laced`	a.
Strait"ly	adv.
Strait"ness	n.
Strait"-waist`coat	n.
Strake	imp.
Strake	n.
Strale	n.
Stram	v. t.
Stram	v. t.
Stram"ash	v. t.
Stram"ash	n.
Stram"a*zoun	n.
Stra*min"e*ous	a.
Stra*mo"ni*um	n.
Stram"o*ny	n.
Strand	n.
Strand	v. t.
Strand	n.
Strand	v. t.
Strand	v. i.
Strang	a.
Strange	a.
Strange	adv.
Strange	v. t.
Strange	v. i.
Strange"ly	adv.
Strange"ness	n.
Stran"ger	n.
Stran"ger	v. t.
Stran"gle	v. t.
Stran"gle	v. i.
Stran"gle*a*ble	a.
Stran"gle hold	n.
Stran"gles	n.
Stran"gu*late	a.
Stran"gu*la`ted	a.
Stran"gu*la`tion	n.
Stran*gu"ri*ous	a.
Stran"gu*ry	n.
Stra"ny	n.
Strap	n.
Strap	v. t.
Strap*pa"do	n.
Strap*pa"do	v. t.
Strap"per	n.
Strap"ping	a.
Strap"ple	v. t.
Strap"-shaped`	a.
Strap"work`	n.
Strass	n.
Stra"ta	n.
Strat"a*gem	n.
Strat`a*gem"ic*al	a.
Strat`a*rith"me*try	n.
Strat`e*get"ic	a.
Strat`e*get"ics	n.
Stra*te"gic	a.
Stra*te"gics	n.
Strat"e*gist	n.
Stra*te"gus	n.
Strat"e*gy	n.
Strath	n.
Strath"spey`	n.
Stra*tic"u*late	a.
Strat`i*fi*ca"tion	n.
Strat"i*fied	a.
Strat"i*form	a.
Strat"i*fy	v. t.
Strat`i*graph"ic	a.
Strat`i*graph"ic	a.
Stra*tig"ra*phy	n.
Stra`to-cir"rus	n.
Stra*toc"ra*cy	n.
Stra`to-cu"mu*lus	n.
Strat`o*graph"ic	a.
Stra*tog"ra*phy	n.
Stra*ton"ic	a.
Stra*tot"ic	a.
Stra"tum	n.
Stra"tus	n.
Straught	imp. & p. p.
Straught	v. t.
Straw	v. t.
Straw	n.
Straw"ber*ry	n.
Straw"board`	n.
Straw"-col`ored	a.
Straw"-cut`ter	n.
Strawed	imp. & p. p.
Straw"worm`	n.
Straw"y	a.
Stray	v. i.
Stray	v. t.
Stray	a.
Stray	n.
Stray"er	n.
Stre	n.
Streak	v. t.
Streak	n.
Streak	v. t.
Streaked	a.
Streak"y	a.
Stream	n.
Stream	v. i.
Stream	v. t.
Stream clock	n.
Stream"ful	a.
Stream gold	n.
Stream"ing	a.
Stream"ing	n.
Stream"less	a.
Stream"let	n.
Stream line	a.
stream"line	v. t.
Stream wheel	a.
Stree	n.
Streek	v. t.
Streel	v. i.
Streen	n.
Street	n.
Street"walk`er	n.
Street"ward`	n.
Street"ward	a.
Streight	a., n., & adv.
Streight"en	v. t.
Strein	v. t.
Streit	a.
Streit	a.
Streite	adv.
Strel"itz	n. sing. & pl.
Stre*litz"i*a	n.
Strene	n.
Stren"ger	compar.
Strength	n.
Strength	v. t.
Strength"en	v. t.
Strength"en	v. i.
Strength"en*er	n.
Strength"en*ing	a.
Strength"ful	a.
Strength"ing	n.
Strength"less	a.
Strength"ner	n.
Strength"y	a.
Stre*nu"i*ty	n.
Stren"u*ous	a.
Strep"ent	a.
Strep"er*ous	a.
Strep`i*to"res	n. pl.
Strep*sip"ter	n.
Strep*sip"te*ra	n. pl.
Strep*sip"ter*ous	a.
Strep`so*rhi"na	n. pl.
Strep"so*rhine	a.
Strep`to*bac*te"ri*a	n. pl.
Strep`to*coc"cus	n.
Strep`to*neu"ra	n. pl.
Strep"to*thrix	n.
Stress	n.
Stress	v. t.
Stress"ful	a.
Stretch	v. t.
Stretch	v. i.
Stretch	n.
Stretch"er	n.
Stretch"ing	a. & n.
Stret"to	n.
Strew	v. t.
Strew"ing	n.
Strew"ment	n.
Strewn	p. p.
Stri"a	n.
Stri"ate	v. t.
Stri"ate	a.
Stri*a"tion	n.
Stri*a"tum	n.
Stri"a*ture	n.
Strich	n.
Strick	n.
Strick"en	p. p. & a.
Stric"kle	n.
Stric"kler	n.
Strick"less	n.
Strict	a.
Stric"tion	n.
Strict"ly	adv.
Strict"ness	n.
Stric"ture	n.
Stric"tured	a.
Strid	n.
Stride	v. t.
Stride	v. t.
Stride	n.
Stri"dent	a.
Stri"dor	n.
Strid"u*late	v. t.
Strid`u*la"tion	n.
Strid"u*la`tor	n.
Strid"u*la*to*ry	a.
Strid"u*lous	a.
Strife	n.
Strife"ful	a.
Stri"gate	a.
Stri"ges	n. pl.
Strig"il	n.
Strig"il*lose`	a.
Stri"gine	a.
Strig"ment	n.
Stri*gose"	a.
Stri"gous	a.
Strike	v. t.
Strike	v. i.
Strike	n.
Strike"out	n.
Strik"er	n.
Strike" zone	n.
Strik"ing	a. & n.
Strik"ing	a.
Strik"le	n.
String	n.
String	v. t.
String	v. i.
String"board`	n.
String"course`	n.
Stringed	a.
Strin"gen*cy	n.
Strin"gen*do	a.
Strin"gent	a.
String"er	n.
String"halt`	n.
String"i*ness	n.
String"less	a.
String"piece`	n.
string" the`o*ry	n.
String"y	a.
Strip	v. t.
Strip	v. i.
Strip	n.
Stripe	n.
Stripe	v. t.
Striped	a.
Strip"-leaf`	n.
Strip"ling	n.
Strip"per	n.
Strip"pet	n.
Strip"ping	n.
Stri*so"res	n. pl.
Strive	v. i.
Strive	n.
Strived	p. p.
Striv"en	p. p.
Striv"er	n.
Striv"ing	a. & n.
Strix	n.
Stroam	v. i.
Stro*bi"la	n.
Strob`i*la"ceous	a.
Strob`i*la"tion	n.
Strob"ile	n.
Stro*bil"i*form	a.
Strob"i*line	a.
Strob"o*scope	n.
Stroc"kle	n.
Strode	n.
Strode	imp.
Stroke	imp.
Stroke	n.
Stroke	v. t.
Strok"er	n.
Strokes"man	n.
Strok"ing	n.
Stroll	v. i.
Stroll	n.
Stroll"er	n.
Stro"ma	n.
Stro*mat"ic	a.
Stro`ma*tol"o*gy	n.
Stromb	n.
Strom"bite	n.
Strom"boid	a.
Strom*bu"li*form	a.
Strom"bus	n.
Stro"mey`er*ite	n.
Strond	n.
Strong	a.
strong"box`	n.
Strong"hand`	n.
Strong"hold`	n.
Strong"ish	a.
Strong"ly	adv.
Strong"-mind`ed	a.
Strong"-wa`ter	n.
Stron"gy*lid	a. & n.
Stron"gy*loid	a.
Stron"ti*a	n.
Stron"ti*an	n.
Stron"ti*an*ite	n.
Stron"tic	a.
Stron*tit"ic	a.
Stron"ti*um	n.
Strook	imp.
Strook	n.
Stroot	v. t.
Strop	n.
Strop	v. t.
Strop	n.
Stro*phan"thus	n.
Stro"phe	n.
Stroph"ic	a.
Stro"phi*o*late	a.
Stro"phi*ole	n.
Stroph"u*lus	n.
Stroud	n.
Stroud"ing	n.
Strout	v. i.
Strout	v. t.
Strove	imp.
Strow	v. t.
Strowl	v. i.
Strown	p. p.
Stroy	v. i.
Struck	imp. & p. p.
Struck"en	p. p.
Struc"tur*al	a.
Struc"tur*al form"u*la	n.
Struc"tured	a.
Struc"ture*less	a.
Struc"tur*ist	n.
Strude	n.
Strug"gle	v. i.
Strug"gle	n.
Strug"gler	n.
Strull	n.
Strum	v. t. & i.
Stru"ma	n.
Stru*mat"ic	a.
Stru*mose"	a.
Stru"mous	a.
Stru"mous*ness	n.
Strum"pet	n.
Strum"pet	a.
Strum"pet	v. t.
Strum"strum	n.
Strung	imp. & p. p.
Strunt	n.
Strun"tian	n.
Struse	n.
Strut	v. t.
Strut	n.
Strut	v. t.
Strut	a.
Stru"thi*an	a.
Stru"thi*o	n.
Stru`thi*oi"de*a	n. pl.
Stru`thi*o"nes	n. pl.
Stru`thi*o"nine	a.
Stru"thi*ous	a.
Strut"ter	n.
Strut"ting	a. & n.
Struv"ite	n.
Strych"ni*a	n.
Strych"nic	a.
Strych"nine	n.
Strych"nos	n.
Stryph"nic	a.
Stub	n.
Stub	v. t.
Stub"bed	a.
Stub"bed*ness	n.
Stub"bi*ness	n.
Stub"ble	n.
Stub"bled	a.
Stub"bly	a.
Stub"born	a.
Stub"by	a.
Stuc"co	n.
Stuc"co	v. t.
Stuc"co*er	n.
Stuc"co*work`	n.
Stuck	imp. & p. p.
Stuck	n.
Stuc"kle	n.
Stuck"-up`	a.
Stud	n.
Stud	n.
Stud	v. t.
Stud"book`	n.
Stud"der*y	n.
Stud"ding	n.
Stud"ding sail`	n.
Stu"dent*ry	n.
Stu"dent*ship	n.
Stud"fish`	n.
Stud"-horse`	n.
Stud"ied	a.
Stud"ied*ly	adv.
Stud"i*er	n.
Stu"di*o	n.
Stu"di*ous	a.
Stud"y	n.
Stud"y	v. i.
Stud"y	v. t.
Stu"fa	n.
Stuff	n.
Stuff	v. t.
Stuff	v. i.
Stuff"er	n.
Stuff"i*ness	n.
Stuff"ing	n.
Stuff"y	a.
Stuke	n.
Stull	n.
Stulm	n.
Stulp	n.
Stul`ti*fi*ca"tion	n.
Stul"ti*fi`er	n.
Stul"ti*fy	v. t.
Stul*til"o*quence	n.
Stul*til"o*quent	a.
Stul*til"o*quy	n.
Stul"ty	a.
Stum	n.
Stum	v. t.
Stum"ble	v. i.
Stum"ble	v. t.
Stum"ble	n.
Stum"bler	n.
Stum"bling-block`	n.
Stum"bling*ly	adv.
Stum"bling-stone`	n.
Stump	n.
Stump	v. t.
Stump	v. i.
Stump"age	n.
Stump"er	n.
Stump"i*ness	n.
Stump"-tailed`	a.
Stump"y	a.
Stun	v. t.
Stun	n.
Stun"dist	n.
Stung	imp. & p. p.
Stunk	imp. & p. p.
Stun"ner	n.
Stun"ning	a.
Stun"sail	n.
Stunt	v. t.
Stunt	n.
Stunt	n.
Stunt"ed	a.
Stunt"ness	n.
Stu"pa	n.
Stu"pa	n.
Stupe	n.
Stupe	v. t.
Stupe	n.
Stu`pe*fa"cient	a.
Stu`pe*fac"tion	n.
Stu`pe*fac"tive	a. & n.
Stu"pe*fied	a.
Stu"pe*fied`ness	n.
Stu"pe*fi`er	n.
Stu"pe*fy	v. t.
Stu*pen"dous	a.
Stu"pe*ous	a.
Stu"pid	a.
Stu*pid"i*ty	n.
Stu"pi*fy	v. t.
Stu"por	n.
Stu*pose	a.
Stu"prate	v. t.
Stu*pra"tion	n.
Stu"prum	n.
Sturb	v. t.
Stur"di*ly	adv.
Stur"di*ness	n.
Stur"dy	a.
Stur"dy	n.
Stur"geon	n.
Stu`ri*o"nes	n. pl.
Stu`ri*o"ni*an	n.
Sturk	n.
Stur"noid	a.
Sturt	v. t.
Sturt	n.
Stur"tion	n.
Stut	v. i.
Stut"ter	v. t. & i.
Stut"ter	n.
Stut"ter*er	n.
Stut"ter*ing	n.
Stut"ter*ing	a.
Sty	n.
Sty	v. t.
Sty	v. i.
Sty	n.
Sty"an	n.
Sty"ca	n.
Sty"cer*in	n.
Stye	n.
Styg"i*al	a.
Styg"i*an	a.
Sty`la*gal*ma"ic	a.
Sty"lar	a.
Sty*las"ter	n.
Style	n.
Style	v. t.
Sty"let	n.
Sty*lif"er*ous	a.
Sty"li*form	a.
Styl"ish	a.
Styl"ist	n.
Sty*lis"tic	a.
Sty"lite	n.
Sty"lo-	n.
Sty`lo*glos"sal	a.
Sty"lo*graph	n.
Sty`lo*graph"ic	a.
Sty`lo*graph"ic*al	a.
Sty*log"ra*phy	n.
Sty`lo*hy"al	n.
Sty`lo*hy"oid	a.
Sty"loid	a.
Sty`lo*mas"toid	a.
Sty`lo*max"il*la*ry	a.
Sty*lom"e*ter	n.
Sty*lom"ma*ta	n. pl.
Sty*lom`ma*toph"o*ra	n. pl.
Sty*lom`ma*toph"o*rous	a.
Sty`lo*po"di*um	n.
Sty"lops	n.
Sty"lus	n.
Sty"mie	n.
Sty"mie	v. t.
Styph"nate	n.
Styph"nic	a.
Styp"tic	a.
Styp"tic	n.
Styp"tic*al	a.
Styp*tic"i*ty	n.
Styr"a*cin	n.
Sty"rax	n.
Sty"rol	n.
Sty"ro*lene	n.
Sty"rone	n.
Sty"ryl	n.
Stythe	n.
Styth"y	n. & v.
Styx	n.
Su`a*bil"i*ty	n.
Su"a*ble	a.
Suade	v. t.
Suad"i*ble	a.
Suage	v. t.
Su"ant	a.
Sua"si*ble	a.
Sua"sion	n.
Sua"sive	a.
Sua"so*ry	a.
Suave	a.
Suav"i*fy	v. t.
Sua*vil"o*quent	a.
Sua*vil"o*quy	n.
Suav"i*ty	n.
Sub-	n.
Sub*ac"e*tate	n.
Sub*ac"id	a.
Sub*ac"rid	a.
Sub`a*cro"mi*al	a.
Sub*act"	v. t.
Sub*ac"tion	n.
Sub`a*cute"	a.
Sub`a*dun"cate	a.
Sub*ad"vo*cate	n.
Sub`a*e"ri*al	a.
Sub*a"gen*cy	n.
Sub*a"gent	n.
Sub*ag`i*ta"tion	n.
Su"bah	n.
Su"bah*dar	n.
Su"bah*dar`y	n.
Sub*aid"	v. t.
Sub*al"mon*er	n.
Sub*al"pine	a.
Sub*al"tern	a.
Sub*al"tern	n.
Sub`al*ter"nant	n.
Sub`al*ter"nate	a.
Sub`al*ter"nate	n.
Sub*al"ter*na`ting	a.
Sub*al"ter*na`tion	n.
Sub*an"gu*lar	a.
Sub*ap"en*nine	a.
Sub*ap"ic*al	a.
Sub`a*qua"ne*ous	a.
Sub`a*quat"ic	a.
Sub`a*rach"noid	a.
Sub*arc"tic	a.
Sub*ar"cu*ate	a.
Sub`ar*ra"tion	n.
Sub`a*ryt"e*noid	a.
Sub*as"tral	a.
Sub`as*trin"gent	a.
Sub*at"om	n.
Sub*aud"	v. t.
Sub`au*di"tion	n.
Sub*ax"il*la*ry	a.
Sub*ba"sal	a.
Sub"-base`	n.
Sub"-bass`	n.
Sub*bea"dle	n.
Sub*brach"i*al	a.
Sub*brach`i*a"les	n. pl.
Sub*brach"i*an	n.
Sub"breed`	n.
Sub*bron"chi*al	a.
Sub*cal"i*ber	a.
Sub*car"bon*ate	n.
Sub*car`bon*if"er*ous	a.
Sub*car"bu*ret`ed	a.
Sub*car`ti*lag"i*nous	a.
Sub*cau"dal	a.
Sub`ce*les"tial	a.
Sub*cel"lar	n.
Sub*cen"tral	a.
Sub*chant"er	n.
Sub*cir"cu*lar	a.
Sub"class`	n.
Sub*cla"vi*an	a.
Sub`co*lum"nar	a.
Sub`com*mit"tee	n.
Sub`com*pressed"	a.
Sub*con"cave	a.
Sub`con*form"a*ble	a.
Sub*con"ic*al	a.
Sub*con`junc*ti"val	a.
Sub*con"scious	a.
Sub*con"scious*ness	n.
Sub*con`stel*la"tion	n.
Sub*con"tract	n.
Sub`con*tract"ed	a.
Sub`con*tract"or	n.
Sub*con"tra*ry	a.
Sub*con"tra*ry	n.
Sub*cor"a*coid	a.
Sub*cor"date	a.
Sub*cor"ne*ous	a.
Sub*cos"tal	a.
Sub*cos"tal	n.
Sub*cra"ni*al	a.
Sub`crus*ta"ceous	a.
Sub*crys"tal*line	a.
Sub*cul"trate	a.
Sub`cu*ta"ne*ous	a.
Sub`cu*tic"u*lar	a.
Sub`cy*lin"dric*al	a.
Sub*dea"con	n.
Sub*dea"con*ry	n.
Sub"dean`	n.
Sub*dean"er*y	n.
Sub*dec"a*nal	a.
Sub*dec"u*ple	a.
Sub*del"e*gate	n.
Sub*del"e*gate	v. t.
Sub*dent"ed	a.
Sub`de*part"ment	n.
Sub`de*pos"it	n.
Sub`der*i*so"ri*ous	a.
Sub`de*riv"a*tive	n.
Sub`di*ac"o*nate	a.
Sub`di*ac"o*nate	n.
Sub*di"al	a.
Sub*di"a*lect	n.
Sub`di*chot"o*my	n.
Sub`di*lat"ed	a.
Sub`di*ti"tious	a.
Sub`di*ver"si*fy	v. t.
Sub`di*vide"	v. t.
Sub`di*vide"	v. i.
Sub`di*vine"	a.
Sub`di*vis"i*ble	a.
Sub`di*vi"sion	n.
Sub"do*lous	a.
Sub*dom"i*nant	n.
Sub*du"a*ble	a.
Sub*du"al	n.
Sub*duce"	v. t.
Sub*duc"tion	n.
Sub*due"	v. t.
Sub*dued"	a.
Sub*due"ment	n.
Sub*du"er	n.
Sub*dul"cid	a.
Sub"du*ple	a.
Sub*du"pli*cate	a.
Sub*du"ral	a.
Sub*ed"i*tor	n.
Sub`e*lon"gate	a.
Sub*en`do*car"di*al	a.
Sub*en"dy*mal	a.
Sub*ep`i*der"mal	a.
Sub*ep`i*glot"tic	a.
Sub*ep`i*the"li*al	a.
Sub*e"qual	a.
Su"ber*ate	n.
Su*be"re*ous	a.
Su*ber"ic	a.
Su"ber*in	n.
Su"ber*ite	n.
Su`ber*i*za"tion	n.
Su"ber*ize	v. t.
Su"ber*one	n.
Su"ber*ose`	a.
Sub*e`so*phag"e*al	a.
Sub*fam"i*ly	n.
Sub*fi"brous	a.
sub*fusc"	a.
Sub*fus"cous	a.
Sub*fusk"	a.
Sub`ge*lat"i*nous	a.
Sub`ge*ner"ic	a.
Sub*ge"nus	n.
Sub*gla"cial	a.
Sub`glo*bose"	a.
Sub*glob"u*lar	a.
Sub*glos"sal	a.
Sub*glot"tic	a.
Sub`glu*ma"ceous	a.
Sub*gov"ern*or	n.
Sub*gran"u*lar	a.
Sub"group`	n.
Sub`has*ta"tion	n.
Sub`he*pat"ic	a.
Sub`horn*blend"ic	a.
Sub*hu"mer*ate	v. t.
Sub*hy"a*loid	a.
Sub`hy*oid"e*an	a.
Sub`i*ma"go	n.
Sub*in`cu*sa"tion	n.
Sub*in"dex	n.
Sub*in"di*cate	v. t.
Sub*in`di*ca"tion	n.
Sub*in`di*vid"u*al	n.
Sub`in*duce"	v. t.
Sub`in*fer"	v. t. & i.
Sub*in`feu*da"tion	n.
Sub`in*gres"sion	n.
Sub`in*tes"ti*nal	a.
Sub*in`vo*lu"tion	n.
Sub`i*ta"ne*ous	a.
Sub"i*ta*ny	a.
Su"bi*to	adv.
Sub*ja"cent	a.
Sub*ject"	a.
Sub*ject"	n.
Sub*ject"	v. t.
Sub*ject"ed	a.
Sub*jec"tion	n.
Sub"ject*ist	n.
Sub*jec"tive	a.
Sub*jec"tiv*ism	n.
Sub*jec"tiv*ist	n.
Sub`jec*tiv"i*ty	n.
Sub"ject*less	a.
Sub"ject-mat`ter	n.
Sub"ject*ness	n.
Sub*jic"i*ble	a.
Sub*join"	v. t.
Sub*join"der	n.
Sub ju"di*ce	v. t.
Sub`ju*ga"tion	n.
Sub"ju*ga`tor	n.
Sub*junc"tion	n.
Sub*junc"tive	a.
Sub*junc"tive	n.
Sub*king"dom	n.
Sub`lap*sa"ri*an	n. & a.
Sub`lap*sa"ri*an*ism	n.
Sub*lap"sa*ry	a.
Sub"late	v. t.
Sub*la"tion	n.
Sub"la*tive	a.
Sub"lease`	n.
Sub`les*see"	n.
Sub*let"	v. t.
Sub`le*va"tion	n.
Sub`li*bra"ri*an	n.
Sub`lieu*ten"ant	n.
Sub`li*ga"tion	n.
Sub*lim"a*ble	a.
Sub"li*mate	v. t.
Sub"li*mate	n.
Sub"li*mate	a.
Sub"li*ma`ted	a.
Sub"li*ma`tion	n.
Sub"li*ma*to*ry	a.
Sub"li*ma*to*ry	n.
Sub*lime"	a.
Sub*lime"	n.
Sub*lime"	v. t.
Sub*lime"	v. i.
Sub*limed"	a.
Sub*lime"ly	adv.
Sub*lime"ness	n.
Sub*lim`i*fi*ca"tion	n.
Sub*lim"i*nal	a.
Sub*lim"i*ty	n.
Sub*lin`e*a"tion	n.
Sub*lin"gua	n.
Sub*lin"gual	a.
Sub*li"tion	n.
Sub*lit"to*ral	a.
Sub*lob"u*lar	a.
Sub*lum"bar	a.
Sub*lu"nar	a.
Sub"lu*na*ry	n.
Sub`lux*a"tion	n.
Sub*mam"ma*ry	a.
Sub`ma*rine"	a.
Sub*ma*rine"	n.
Sub`ma*rine"	n.
sub`ma*rine" sand"wich	n.
Sub*mar"shal	n.
Sub*max"il*la*ry	a.
Sub*me"di*al	a.
Sub*me"di*an	a.
Sub*me"di*ant	n.
Sub*men"tal	a.
Sub*men"tum	n.
Sub*merge"	v. t.
Sub*merge"	v. i.
Sub*mer"gence	n.
Sub*merse"	a.
Sub*mersed"	a.
Sub*mer"sion	n.
Sub`me*tal"lic	a.
Sub*min"is*ter	v. t.
Sub*min"is*ter	v. i.
Sub*min"is*trant	a.
Sub*min"is*trate	v. t.
Sub*min`is*tra"tion	n.
Sub*miss"	a.
Sub*mis"sion	n.
Sub*mis"sive	a.
Sub*miss"ly	adv.
Sub*miss"ness	n.
Sub*mit"	v. t.
Sub*mit"	v. i.
Sub*mit"ter	n.
Sub*mon"ish	v. t.
Sub`mo*ni"tion	n.
Sub*mu"cous	a.
Sub*mul"ti*ple	n.
Sub*mul"ti*ple	a.
Sub*mus"cu*lar	a.
Sub`nar*cot"ic	a.
Sub*na"sal	a.
Sub*nas"cent	a.
Sub*nect"	v. t.
Sub*nex"	v. t.
Sub*nor"mal	n.
Sub`no*ta"tion	n.
Sub*no`to*chor"dal	a.
Sub*nu"vo*lar	a.
Sub`ob*scure"ly	adv.
Sub`ob*tuse"	a.
Sub`oc*cip"i*tal	a.
Sub*oc"tave	a.
Sub*oc"u*lar	a.
Sub*of"fi*cer	n.
Sub`o*per"cu*lar	a.
Sub`o*per"cu*lum	n.
Sub`or*bic"u*lar	a.
Sub*or"bit*al	a.
Sub*or"der	n.
Sub*or"di*na*cy	n.
Sub*or"di*nance	n.
Sub*or"di*na*ry	n.
Sub*or"di*nate	a.
Sub*or"di*nate	n.
Sub*or"di*nate	v. t.
Sub*or`di*na"tion	n.
Sub*or"di*na*tive	a.
Sub*orn"	v. t.
Sub`or*na"tion	n.
Sub*orn"er	n.
Sub*o"val	a.
Sub*o"vate	a.
Sub*o"va*ted	a.
Sub*ox"ide	n.
Sub`pe*dun"cu*lar	a.
Sub`pe*dun"cu*late	a.
Sub`pel*lu"cid	a.
Sub*pe"na	n. & v. t.
Sub`pen*tan"gu*lar	a.
Sub*per`i*car"di*al	a.
Sub*per`i*os"te*al	a.
Sub*per`i*to"ne*al	a.
Sub*pet"i*o*lar	a.
Sub*pleu"ral	a.
Sub*pod`o*phyl"lous	a.
Sub*poe"na	n.
Sub*poe"na	v. t.
Sub*poe"nal	a.
Sub*po"lar	a.
Sub`po*lyg"o*nal	a.
Sub`pre*hen"sile	a.
Sub*pri"or	n.
Sub*pu"bic	a.
Sub*pul"mo*na*ry	a.
Sub*pur"chas*er	n.
Sub*pyr"i*form	a.
Sub*quad"rate	a.
Sub*quad"ru*ple	a.
Sub*quin"que*fid	a.
Sub*quin"tu*ple	a.
Sub*read"er	n.
Sub*rec"tor	n.
Sub`re*li"gion	n.
Sub*rep"tion	n.
Sub`rep*ti"tious	a.
Sub*rep"tive	a.
Sub*rig"id	a.
Sub*rig"u*ous	a.
Sub"ro*gate	v. t.
Sub`ro*ga"tion	n.
Sub`ro*tund"	a.
Sub*sa"cral	a.
Sub`sa*line"	a.
Sub"salt`	n.
Sub`san*na"tion	n.
Sub*scap"u*lar	a.
Sub*scrib"a*ble	a.
Sub*scribe"	v. t.
Sub*scribe"	v. i.
Sub*scrib"er	n.
Sub"script	a.
Sub"script	n.
Sub*scrip"tion	n.
Sub*scrip"tive	a.
Sub"se*cute	v. t.
Sub*sec"u*tive	a.
Sub*sel"li*um	n.
Sub*sem"i*tone	n.
Sub*sen"si*ble	a.
Sub*sep"tu*ple	a.
Sub"se*quence	n.
Sub"se*quent	a.
Sub"se*quent*ly	adv.
Sub*se"rous	a.
Sub*serve"	v. t.
Sub*serve"	v. i.
Sub*serv"i*ence	n.
Sub*serv"i*ent	a.
Sub*serv"i*ent*ly	adv.
Sub*ses"qui-	a.
Sub*side"	v. i.
Sub*sid"ence	n.
Sub*sid"i*a*ri*ly	adv.
Sub*sid"i*a*ry	a.
Sub*sid"i*a*ry	n.
Sub"si*dize	v. t.
Sub"si*dy	n.
Sub*sign"	v. t.
Sub`sig*na"tion	n.
Sub*sil"i*cate	n.
Sub*sist"	v. i.
Sub*sist"	v. t.
Sub*sist"ence	n.
Sub*sist"ence De*part"ment	n.
Sub*sist"ent	a.
Sub*si"zar	n.
Sub"soil`	n.
Sub"soil`	v. t.
Sub*so"la*ry	a.
Sub*spe"cies	n.
Sub`sphe*noid"al	a.
Sub*spher"ic*al	a.
Sub*spi"nous	a.
Sub"stance	n.
Sub"stance	v. t.
Sub"stance*less	a.
Sub"stant	a.
Sub*stan"tial	a.
Sub*stan`ti*al"i*ty	n.
Sub*stan"tial*ize	v. t.
Sub*stan"tial*ly	adv.
Sub*stan"tial*ness	n.
Sub*stan"tials	n. pl.
Sub*stan"ti*ate	v. t.
Sub*stan`ti*a"tion	n.
Sub`stan*ti"val	a.
Sub"stan*tive	a.
Sub"stan*tive	n.
Sub"stan*tive	v. t.
Sub"stan*tive*ly	adv.
Sub"stan*tive*ness	n.
Sub"stan*tiv*ize	v. t.
Sub"stile`	n.
Sub*stit"u*ent	n.
Sub"stit"ute	n.
Sub"stit"ute	v. t.
Sub"stit"uted	a.
Sub`sti*tu"tion	n.
Sub`sti*tu"tion*al	a.
Sub`sti*tu"tion*a*ry	a.
Sub"sti*tu`tive	a.
Sub*stract"	v. t.
Sub*strac"tion	n.
Sub*stract"or	n.
Sub"strate	n.
Sub"strate	a.
Sub*strate"	v. t.
Sub*stra"tum	n.
Sub*struct"	v. t.
Sub*struc"tion	n.
Sub*struc"ture	n.
Sub*sty"lar	a.
Sub"style`	n.
Sub*sul"phate	n.
Sub*sul"phide	n.
Sub*sul"tive	a.
Sub*sul"to*ry	a.
Sub*sul"tus	n.
Sub*sum"a*ble	a.
Sub*sume"	v. t.
Sub*sump"tion	n.
Sub*sump"tive	a.
Sub*tan"gent	n.
Sub`tar*ta"re*an	a.
Sub*tec"ta*cle	n.
Sub*teg`u*la"ne*ous	a.
Sub*ten"ant	n.
Sub*tend"	v. t.
Sub*tense"	n.
Sub*tep"id	a.
Sub`te*rete"	a.
Sub*ter"flu*ent	a.
Sub"ter*fuge	n.
Sub"ter*rane	n.
Sub`ter*ra"ne*al	a.
Sub`ter*ra"ne*an	a.
Sub`ter*ran"i*ty	n.
Sub"ter*ra*ny	a.
Sub`ter*rene"	a.
Sub`ter*res"tri*al	a.
Sub`tha*lam"ic	a.
Sub"tile	a.
Sub*til"i*ate	v. t.
Sub"til*ism	n.
Sub*til"i*ty	n.
Sub`til*i*za"tion	n.
Sub"til*ize	v. t.
Sub"til*ize	v. i.
Sub"til*i`zer	n.
Sub"til*ty	n.
Sub"tle	a.
Sub"tle*ness	n.
Sub"tle*ty	n.
Sub"tly	adv.
Sub*ton"ic	a.
Sub*ton"ic	n.
Sub*tor"rid	a.
Sub*tract"	v. t.
Sub*tract"er	n.
Sub*trac"tion	n.
Sub*trac"tive	a.
Sub"tra*hend`	n.
Sub`trans*lu"cent	a.
Sub`trans*pa"rent	a.
Sub*treas"ur*er	n.
Sub*treas"ur*y	n.
Sub`tri*an"gu*lar	a.
Sub"tribe`	n.
Sub`tri*he"dral	a.
Sub*tri"ple	a.
Sub*trip"li*cate	a.
Sub*trop"ic*al	a.
Sub*trude"	v. t.
Sub`tur*ric"u*late	a.
Sub*tu"tor	n.
Sub*typ"ic*al	a.
Su"bu*late	a.
Su`bu*li*cor"nes	n. pl.
Su"bu*li*form	a.
Su"bu*li*palp`	n.
Sub`um*bo"nal	a.
Sub`um*brel"la	n.
Sub`un*da"tion	n.
Sub*un"gual	a.
Sub"urb	n.
Sub*ur"ban	a.
Sub*ur"ban	n.
Sub"urbed	a.
Sub*ur"bi*al	a.
Sub*ur`bi*ca"ri*an	a.
Sub`u*re"thral	a.
Sub*vag"i*nal	a.
Sub`va*ri"e*ty	n.
Sub*vene"	v. i.
Sub`ven*ta"ne*ous	a.
Sub*ven"tion	n.
Sub*ven"tion	v. t.
Sub*ven"tion*ize	v. t.
Sub`ven*ti"tious	a.
Sub*verse"	v. t.
Sub*ver"sion	n.
Sub*ver"sion*a*ry	a.
Sub*ver"sive	a.
Sub*vert"	v. t.
Sub*vert"	v. i.
Sub*vert"ant	a.
Sub*ver"te*bral	a.
Sub*vert"er	n.
Sub*vert"i*ble	a.
Sub*vi"tal*ized	a.
Sub*vo"cal	a. & n.
Sub"way`	n.
Sub*work"er	n.
Sub*zon"al	a.
Sub*zyg`o*mat"ic	a.
Suc"cade	n.
Suc"ce*dane	n.
Suc`ce*da"ne*ous	a.
Suc`ce*da"ne*um	n.
Suc*ceed"	v. t.
Suc*ceed"	v. i.
Suc*ceed"ant	a.
Suc*ceed"er	n.
Suc*ceed"ing	n.
Suc"cen*tor	n.
Suc*cess"	n.
Suc"ces*sa*ry	n.
Suc*cess"ful	a.
Suc*ces"sion	n.
Suc*ces"sion*al	a.
Suc*ces"sion*ist	n.
Suc*ces"sive	a.
Suc*ces"sive*ly	adv.
Suc*ces"sive*ness	n.
Suc*cess"less	a.
Suc*ces"sor	n.
Suc*cid"u*ous	a.
Suc*cif"er*ous	a.
Suc`cin*am"ate	n.
Suc`cin*am"ic	a.
Suc"ci*nate	n.
Suc*cinct"	a.
Suc*cin"ic	a.
Suc`cin*im"ide	n.
Suc"ci*nite	n.
Suc"ci*nous	a.
Suc`cin*u"rate	n.
Suc`cin*u"ric	a.
Suc"cin*yl	n.
Suc*cise"	a.
Suc*ci"sion	n.
Suc"cor	v. t.
Suc"cor	n.
Suc"cor*a*ble	a.
Suc"cor*er	n.
Suc"cor*less	a.
Suc"co*ry	n.
Suc"co*tash	n.
Suc`co*teague"	n.
Suc"cu*ba	n.
Suc"cu*bine	a.
Suc"cu*bous	a.
Suc"cu*bus	n.
Suc"cu*la	n.
Suc"cu*lence	n.
Suc"cu*lent	a.
Suc"cu*lent*ly	adv.
Suc"cu*lous	a.
Suc*cumb"	v. t.
Suc*cum"bent	a.
Suc*cur"sal	a.
Suc"cus	n.
Suc`cus*sa"tion	n.
Suc*cus"sion	n.
Suc*cus"sive	a.
Such	a.
Su`cho*spon"dy*lous	a.
Such"wise`	adv.
Suck	v. t.
Suck	v. i.
Suck	n.
Suck"an*hock	n.
Suck"a*tash	n.
Suck"en	n.
Suck"er	n.
Suck"er	v. t.
Suck"er	v. i.
Suck"er State	n.
suck face	v. i.
Suck"fish`	n.
Suck"ing	a.
Suc"kle	n.
Suc"kle	v. t.
Suc"kle	v. i.
Suc"kler	n.
Suck"ling	n.
Su"crate	n.
Su"cre	n.
Su"crose`	n.
Suc"tion	n.
Suc*to"ri*a	n. pl.
Suc*to"ri*al	a.
Suc*to"ri*an	n.
Suc*to"ri*ous	a.
Su*dam"i*na	n. pl.
Su*da"ri*um	n.
Su"da*ry	n.
Su*da"tion	n.
Su`da*to"ri*um	n.
Su"da*to*ry	a.
Su"da*to*ry	n.
Sudd	n.
Sud"den	a.
Sud"den	adv.
Sud"den	n.
Sud"den*ty	n.
Su"dor*al	a.
Su`dor*if"er*ous	a.
Su`dor*if"ic	a.
Su`dor*ip"a*rous	a.
Su"dor*ous	a.
Su"dra	n.
Suds	n. pl.
Sue	v. t.
Sue	v. i.
Suede	n.
Su"ent	a.
Su"ent*ly	adv.
Su"er	n.
Su"et	n.
Su"et*y	a.
Suf-	v. t.
Suf"fer	v. i.
Suf"fer*a*ble	a.
Suf"fer*ance	n.
Suf"fer*er	n.
Suf"fer*ing	n.
Suf"fer*ing	a.
Suf*fice"	v. i.
Suf*fice"	v. t.
Suf*fi"cience	n.
Suf*fi"cien*cy	n.
Suf*fi"cient	a.
Suf*fi"cient*ly	adv.
Suf*fi"cing	a.
Suf*fi"sance	n.
Suf*fi"sant	a.
Suf"fix	n.
Suf*fix"	v. t.
Suf*fix"ion	n.
Suf*fix"ment	n.
Suf*flam"i*nate	v. t.
Suf*flate"	v. t.
Suf*fla"tion	n.
Suf"fo*cate	a.
Suf"fo*cate	v. t.
Suf"fo*cate	v. i.
Suf"fo*ca`ting	a. & n.
Suf`fo*ca"tion	n.
Suf"fo*ca*tive	a.
Suf*fos"sion	n.
Suf"fra*gan	a.
Suf"fra*gan	n.
Suf"fra*gan*ship	n.
Suf"fra*gant	a. & n.
Suf"fra*gate	v. i. & t.
Suf"fra*ga`tor	n.
Suf"frage	n.
Suf"frage	v. t.
Suf`fra*gette"	n.
Suf*frag"i*nous	a.
Suf"fra*gist	n.
Suf*fra"go	n.
Suf"france	n.
Suf`fru*tes"cent	a.
Suf*fru"ti*cose`	a.
Suf*fru"ti*cous	a.
Suf*fu"mi*gate	v. t.
Suf*fu`mi*ga"tion	n.
Suf*fu"mige	n.
Suf*fuse"	v. t.
Suf*fu"sion	n.
Su"fi	n.
Su"fi	n.
Su"fism	n.
Sug	n.
Sug"ar	n.
Sug"ar	v. i.
Sug"ar	v. t.
Sug"ared	a.
Sug"ar-house`	n.
Sug"ar*i*ness	n.
Sug"ar*ing	n.
Sug"ar*less	a.
Sug"ar*plum`	n.
Sug"ar*y	a.
Su*ges"cent	a.
Sug*gest"	v. t.
Sug*gest"	v. i.
Sug*gest"er	n.
Sug*ges"tion	n.
Sug*gest"ive	a.
Sug*gest"ive med"i*cine	n.
Sug*gest"ress	n.
Sug"gil	v. t.
Sug"gil*late	v. t.
Sug`gil*la"tion	n.
Su"i*ci`dal	a.
Su"i*cide	n.
Su`i*cid"i*cal	a.
Su"i*ci*dism	n.
Su"i*cism	n.
Su"i gen"e*ris	n.
Su"il*line	a.
Su"ine	n.
Su"ing	n.
Su"ing*ly	adv.
Su"int	n.
Su`i*o*goths"	n. pl.
Su"ist	n.
Suit	n.
Suit	v. t.
Suit	v. i.
Suit`a*bil"i*ty	n.
Suit"a*ble	a.
Suite	n.
Suit"ing	n.
Suit"or	n.
Suit"ress	n.
Su"ji	n.
Su"la	n.
Sul"cate	a.
Sul*ca"tion	n.
Sul"ci*form	a.
Sul"cus	n.
Su"le*ah fish`	n.
Sulk	v. i.
Sulk"er	n.
Sulk"i*ly	adv.
Sulk"i*ness	n.
Sulks	n. pl.
Sulk"y	a.
Sulk"y	n.
Sull	n.
Sul"lage	n.
Sul"len	a.
Sul"len	n.
Sul"len	v. t.
Sul"le*vate	v. t.
Sul"li*age	n.
Sul"ly	v. t.
Sul"ly	v. i.
Sul"ly	n.
Sulph*ac"id	n.
Sulph*am"ate	n.
Sulph*am"ic	a.
Sulph*am"ide	n.
Sulph`a*nil"ic	a.
Sulph*an`ti*mo"nate	n.
Sulph*an`ti*mon"ic	a.
Sulph*an`ti*mo"ni*ous	a.
Sulph*an"ti*mo*nite`	n.
Sulph*ar"se*nate	n.
Sulph`ar*sen"ic	a.
Sulph`ar*se"ni*ous	a.
Sulph*ar"se*nite	n.
Sul"phate	n.
Sul*phat"ic	a.
Sul"pha*to-	n.
Sulph*au"ric	a.
Sul"phide	n.
Sul"phi*nate	n.
Sulph*in`di*got"ic	a.
Sul"phine	n.
Sul*phin"ic	a.
Sul"phi*nide	n.
Sul"phi*on	n.
Sulph*i"on*ide	n.
Sul"phite	n.
Sul"pho-	a.
Sul`pho*car"bon*ate	n.
Sul`pho*car*bon"ic	a.
Sul`pho*cy"a*nate	n.
Sul`pho*cy*an"ic	a.
Sul`pho*cy"a*nide	n.
Sul`pho*cy*an"o*gen	n.
Sul"pho*nal	n.
Sul"pho*nate	n.
Sul"phone	n.
Sul*phon"ic	a.
Sul*pho"ni*um	n.
Sul`pho*phos"phate	n.
Sul`pho*phos"phite	n.
Sul`pho*phos*phor"ic	a.
Sul`pho*phos"phor*ous	a.
Sul"pho*salt`	n.
Sul`pho*stan"nate	n.
Sul`pho*stan"nic	a.
Sul`pho*tung"state	n.
Sul`pho*tung"stic	a.
Sul`pho*vin"ic	a.
Sul"phur	n.
Sul"phu*rate	a.
Sul"phu*rate	v. t.
Sul`phu*ra"tion	n.
Sul"phu*ra`tor	n.
Sul`phur-bot"tom	n.
Sul`phu*re"i*ty	n.
Sul*phu"re*ous	a.
Sul"phu*ret	n.
Sul"phu*ret`ed	a.
Sul*phu"ric	a.
Sul"phur*ine	a.
Sul"phur*ing	n.
Sul"phur*ize	v. t.
Sul"phur*ous	a.
Sul"phur*wort`	n.
Sul"phur*y	a.
Sul"phur*yl	n.
Sul*phy"drate	n.
Sul*phy"dric	a.
Sul*pi"cian	n.
Sul"tan	n.
Sul*ta"na	n.
Sul"tan*ate	n.
Sul"tan*ess	n.
Sul*tan"ic	a.
Sul"tan-red`	a.
Sul"tan*ry	n.
Sul"tan*ship	n.
Sul"tan*y	n.
Sul"tri*ly	adv.
Sul"tri*ness	n.
Sul"try	a.
Su*lu"	n.
Sum	n.
Sum	v. t.
Su"mac	n.
Su*ma"tra leaf	a.
Sum"bul	n.
Su*me"ri*an	a.
Su*me"ri*an	n.
Sum"less	a.
Sum"ma*ri*ly	adv.
Sum"ma*rist	n.
Sum"ma*rize	v. t.
Sum"ma*ry	a.
Sum"ma*ry	n.
Sum*ma"tion	n.
Sum"mer	n.
Sum"mer	n.
Sum"mer	n.
Sum"mer	v. i.
Sum"mer	v. t.
Sum"mer-fal"low	v. t.
Sum"mer*house`	n.
Sum"mer*li*ness	n.
Sum"mer*sault	n.
Sum"mer*stir`	v. t.
Sum"mer*tide`	n.
Sum"mer*tree`	n.
Sum"mer*y	a.
Sum"mist	n.
Sum"mit	n.
Sum"mit*less	a.
Sum"mit*y	n.
Sum"mon	v. t.
Sum"mon*er	n.
Sum"mons	n.
Sum"mons	v. t.
Sum"mum bo"num	n.
Su*moom"	n.
Sump	n.
Sumph	n.
Sum"pi*tan	n.
Sump"ter	n.
Sump"ter	a.
Sump"tion	n.
Sump"tu*a*ry	a.
Sump`tu*os"i*ty	n.
Sump"tu*ous	a.
Sun	n.
Sun	n.
Sun	v. t.
Sun"beam`	n.
Sun"bird`	n.
Sun"blink`	n.
Sun"bon"net	n.
Sun"bow`	n.
Sun"burn`	v. t.
Sun"burn`	n.
Sun"-burn`er	n.
Sun"burn`ing	n.
Sun"burst`	n.
Sun"cup`	n.
Sun"dart`	n.
Sun"day	n.
Sun"day	a.
Sun"der	v. t.
Sun"der	v. i.
Sun"der	n.
Sun"der	v. t.
Sun"dew`	n.
Sun"di`al	n.
Sun"dog`	n.
Sun"down`	n.
Sun"down`er	n.
Sun"-dried`	a.
Sun"dries	n. pl.
Sun"dri*ly	adv.
Sun"drops`	n.
Sun"dry	a.
Sun"dry*man	n.
Sun"fish`	n.
Sun"flow`er	n.
Sun"flow`er State	imp. & p. p.
Sun"glass`	n.
Sun"glow`	n.
Sunk	imp. & p. p.
Sunk"en	a.
Sun"less	a.
Sun"light`	n.
Sun"like`	a.
Sun"lit`	a.
Sunn	n.
Sun"na	n.
Sun"ni*ah	n.
Sun"ni*ness	n.
Sun"nite	n.
Sun"nud	n.
Sun"ny	a.
Sun"ny	n.
Sun"proof`	a.
Sun"rise`	n.
Sun"roof`	n.
Sun"set"	n.
Sun"shade`	n.
Sun"shine`	n.
Sun"shine`	a.
Sun"shin`y	a.
Sun"squall`	n.
Sun" star`	n.
Sun"stone`	n.
Sun"stroke`	n.
Sun"-struck`	a.
Sun"up`	n.
Sun"ward	adv.
Sun"wise`	adv.
Sup	v. t.
Sup	n.
Sup	v. i.
Sup	v. t.
Su*pawn"	n.
Supe	n.
Su"per-	a.
Su"per	n.
Su"per*a*ble	a.
Su`per*a*bound"	v. i.
Su`per*a*bun"dance	n.
Su`per*a*bun"dant	a.
Su`per*a*cid"u*la`ted	a.
Su`per*add"	v. t.
Su`per*ad*di"tion	n.
Su`per*ad*ven"ient	a.
Su`per*al`i*men*ta"tion	n.
Su"per*al`tar	n.
Su`per*an*gel"ic	a.
Su`per*an"nu*ate	v. t.
Su`per*an"nu*ate	v. i.
Su`per*an`nu*a"tion	n.
Su*perb"	a.
Su*per"bi*ate	v. t.
Su`per*car"bon*ate	n.
Su`per*car"bu*ret`ed	a.
Su`per*car"go	n.
Su`per*car"pal	a.
Su`per*ce*les"tial	a.
Su`per*charge"	v. t.
Su`per*charge"	n.
Su`per*chem"ic*al	a.
Su*perch"er*y	n.
Su`per*cil"i*a*ry	a.
Su`per*cil"i*ous	a.
Su`per*cil"i*um	n.
Su`per*co*lum`ni*a"tion	n.
Su`per*con*cep"tion	n.
Su`per*con"se*quence	n.
Su`per*cres"cence	n.
Su`per*cres"cent	a.
Su`per*cre*ta"ceous	a.
Su`per*cu"ri*ous	a.
Su`per*dom"i*nant	n.
Su`per*dread"nought`	n.
Su`per*em"i*nence	n.
Su`per*em"i*nent	a.
Su`per*er"o*gant	a.
Su`per*er"o*gate	v. i.
Su`per*er`o*ga"tion	n.
Su`per*e*rog"a*tive	a.
Su`per*e*rog"a*to*ry	a.
Su`per*es*sen"tial	a.
Su`per*eth"ic*al	a.
Su`per*ex*alt"	v. t.
Su`per*ex`al*ta"tion	n.
Su`per*ex"cel*lence	n.
Su`per*ex"cel*lent	a.
Su`per*ex`ci*ta"tion	n.
Su`per*ex*cres"cence	n.
Su"per*fam`i*ly	n.
Su`per*fec`un*da"tion	n.
Su`per*fe*cun"di*ty	n.
Su`per*fe"tate	v. i.
Su`per*fe*ta"tion	n.
Su`per*fete"	v. i.
Su`per*fete"	v. t.
Su"per*fice	n.
Su`per*fi"cial	a.
Su`per*fi"cial*ist	n.
Su`per*fi`ci*al"i*ty	n.
Su`per*fi"cial*ize	v. t.
Su`per*fi"ci*a*ry	n.
Su`per*fi"ci*a*ry	a.
Su`per*fi"cies	n.
Su"per*fine	a.
Su"per*fine`ness	n.
Su`per*fin"i*cal	a.
Su*per"flu*ence	n.
Su`per*flu"i*tant	a.
Su`per*flu"i*ty	n.
Su*per"flu*ous	a.
Su"per*flux	n.
Su`per*foe*ta"tion	n.
Su`per*fo`li*a"tion	n.
Su`per*fron"tal	n.
Su`per*fuse"	a.
Su`per*heat"	v. t.
Su"per*heat`	n.
Su"per*heat`ed	n.
Su"per*hive`	n.
Su`per*hu"man	a.
Su`per*im*pose"	v. t.
Su`per*im`preg*na"tion	n.
Su`per*in*cum"bence	n.
Su`per*in*cum"bent	a.
Su`per*in*duce"	v. t.
Su`per*in*duce"ment	n.
Su`per*in*duc"tion	n.
Su`per*in*fuse"	v. t.
Su`per*in*jec"tion	n.
Su`per*in*spect"	v. t.
Su`per*in`sti*tu"tion	n.
Su`per*in`tel*lec"tu*al	a.
Su`per*in*tend"	v. t.
Su`per*in*tend"ence	n.
Su`per*in*tend"en*cy	n.
Su`per*in*tend"ent	a.
Su`per*in*tend"ent	n.
Su`per*in*tend"er	n.
Su`per*in*vest"i*ture	n.
Su*pe"ri*or	a.
Su*pe"ri*or	n.
Su*pe"ri*or*ess	n.
Su*pe`ri*or"i*ty	n.
Su*pe"ri*or*ly	adv.
Su`per*ja"cent	a.
Su`per*la"tion	n.
Su`per*la"tive	a.
Su`per*la"tive	n.
Su`per*lu*cra"tion	n.
Su`per*lu"nar	a.
Su"per*man`	n.
Su`per*ma*te"ri*al	a.
Su`per*max*il"la	n.
Su`per*max"il*la*ry	a.
Su`per*me"di*al	a.
Su`per*mun"dane	a.
Su`per*mun"di*al	a.
Su`per*nac"u*lar	a.
Su`per*nac"u*lum	adv. & n.
Su*per"nal	a.
Su`per*na"tant	a.
Su`per*na"tant	n.
Su`per*na*ta"tion	n.
Su`per*nat"u*ral	a.
Su`per*nat"u*ral*ism	n.
Su`per*nat"u*ral*ist	n.
Su`per*nat`u*ral*is"tic	a.
Su`per*nat`u*ral"i*ty	n.
Su`per*nat"u*ral*ize	v. t.
Su`per*nat"u*ral*ly	adv.
Su`per*nat"u*ral*ness	n.
Su`per*nu"mer*a*ry	a.
Su`per*nu"mer*a*ry	n.
Su`per*oc*cip"i*tal	a.
Su`per*or"der	n.
Su`per*or`di*na"tion	n.
Su`per*ox"ide	n.
Su`per*par*tic"u*lar	a.
Su`per*par"tient	a.
Su`per*phos"phate	n.
Su`per*phys"ic*al	a.
Su"per*plant`	n.
Su`per*please"	v. t.
Su"per*plus	n.
Su"per*plus`age	n.
Su`per*pol"i*tic	a.
Su`per*pon"der*ate	v. t.
Su`per*pos"a*ble	a.
Su`per*pose"	v. t.
Su`per*po*si"tion	n.
Su`per*praise"	v. t.
Su`per*pro*por"tion	n.
Su`per*pur*ga"tion	n.
Su`per*re*flec"tion	n.
Su`per*re"gal	a.
Su`per*re*ward"	v. t.
Su`per*roy"al	a.
Su`per*sa"cral	a.
Su`per*sa"li*en*cy	n.
Su`per*sa"li*ent	a.
Su`per*salt"	n.
Su`per*sat"u*rate	v. t.
Su`per*sat`u*ra"tion	n.
Su`per*scribe"	v. t.
Su"per*script	n.
Su`per*scrip"tion	n.
Su`per*sec"u*lar	a.
Su`per*sede"	v. t.
Su`per*se"de*as	n.
Su*per*se"dure	n.
Su`per*sem"i*nate	v. t.
Su`per*sem`i*na"tion	n.
Su`per*sen"si*ble	a.
Su`per*sen"si*tive	a.
Su`per*sen"su*al	a.
Su`per*sen"su*ous	a.
Su`per*serv"ice*a*ble	a.
Su`per*ses"sion	n.
Su`per*so"lar	a.
su`per*son"ic	a.
Su`per*sphe*noid"al	a.
Su`per*spi"nous	a.
Su`per*sti"tion	n.
Su`per*sti"tion*ist	n.
Su`per*sti"tious	a.
Su`per*strain"	v. t.
Su`per*stra"tum	n.
Su`per*struct"	v. t.
Su`per*struc"tion	n.
Su`per*struct"ive	a.
Su`per*struct"or	n.
Su`per*struc"ture	n.
Su`per*sub*stan"tial	a.
Su`per*sub"tle	a.
Su`per*sul"phate	n.
Su`per*sul"phu*ret`ed	a.
Su`per*sul"phur*ize	v. t.
Su"per*tax`	n.
Su`per*tem"po*ral	n.
Su`per*ter*ra"ne*an	a.
Su`per*ter*rene"	a.
Su`per*ter*res"tri*al	a.
Su`per*ton"ic	n.
Su`per*trag"ic*al	a.
Su`per*tu`ber*a"tion	n.
Su`per*va*ca"ne*ous	a.
Su`per*vene"	v. i.
Su`per*ven"ient	a.
Su`per*ven"tion	n.
Su`per*vis"al	n.
Su`per*vise"	v. t.
Su`per*vise"	n.
Su`per*vi"sion	n.
Su`per*vi"sive	a.
Su`per*vis"or	n.
Su`per*vi"so*ry	a.
Su`per*vive"	v. t.
Su`per*vo*lute"	a.
Su`pi*na"tion	n.
Su`pi*na"tor	n.
Su*pine"	a.
Su"pine	n.
Su*pin"i*ty	n.
Sup"page	n.
Sup`pal*pa"tion	n.
Sup*par`a*si*ta"tion	n.
Sup*par"a*site	v. t.
Sup*pawn"	n.
Sup`pe*da"ne*ous	a.
Sup*ped"i*tate	v. t.
Sup*ped`i*ta"tion	n.
Sup"per	n.
Sup"per	v. i.
Sup"per	v. t.
Sup"per*less	a.
Sup"ping	n.
Sup*place"	v. t.
Sup*plant"	v. t.
Sup`plan*ta"tion	n.
Sup*plan"ter	n.
Sup"ple	a.
Sup"ple	v. t.
Sup"ple	v. i.
Sup"ple-chapped`	a.
Sup"ple-jack`	n.
Sup"ple*ly	adv.
Sup"ple*ment	n.
Sup"ple*ment	v. t.
Sup`ple*men"tal	a.
Sup`ple*men*ta"tion	n.
Sup"ple*ness	n.
Sup"ple*tive	a.
Sup"ple*to*ry	n.
Sup*pli"al	n.
Sup*pli"ance	n.
Sup*pli"ance	n.
Sup"pli*ant	a.
Sup"pli*ant	n.
Sup"pli*can*cy	n.
Sup"pli*cant	a.
Sup"pli*cant	n.
Sup"pli*cat	n.
Sup"pli*cate	v. t.
Sup"pli*cate	v. i.
Sup"pli*ca`ting*ly	adv.
Sup`pli*ca"tion	n.
Sup"pli*ca`tor	n.
Sup"pli*ca*to*ry	a.
Sup*pli"er	n.
Sup*ply"	v. t.
Sup*ply"	n.
Sup*ply"	a.
Sup*ply"ant	a.
Sup*ply"ment	n.
Sup*port"	v. t.
Sup*port"	n.
Sup*port"a*ble	a.
Sup*port"ance	n.
Sup`por*ta"tion	n.
Sup*port"er	n.
Sup*port"ful	a.
Sup*port"less	a.
Sup*port"ment	n.
Sup*port"ress	n.
Sup*pos"a*ble	a.
Sup*pos"al	n.
Sup*pose"	v. t.
Sup*pose"	v. i.
Sup*pose"	n.
Sup*pose"er	n.
Sup`po*si"tion	n.
Sup`po*si"tion*al	a.
Sup*pos`i*ti"tious	a.
Sup*pos"i*tive	a.
Sup*pos"i*tive	n.
Sup*pos"i*tor	n.
Sup*pos"i*to*ry	n.
Sup*po"sure	n.
Sup*press"	v. t.
Sup*press"i*ble	a.
Sup*pres"sion	n.
Sup*press"ive	a.
Sup*press"or	n.
Sup*prise"	v. t.
Sup"pu*rant	n.
Sup"pu*rate	v. i.
Sup"pu*rate	v. t.
Sup`pu*ra"tion	n.
Sup"pu*ra*tive	a.
Sup"pu*ra*tive	n.
Sup"pu*tate	v. t.
Sup`pu*ta"tion	n.
Sup*pute"	v. t.
Su"pra	adv.
Su`pra-a*cro"mi*al	a.
Su`pra-an"gu*lar	a.
Su`pra-au*ric"u*lar	a.
Su"pra-ax"il*la*ry	a.
Su`pra*bran"chi*al	a.
Su`pra*cho"roid	a.
Su`pra*cil"i*a*ry	a.
Su`pra*clav"i*cle	n.
Su`pra*cla*vic"u*lar	a.
Su`pra*con"dy*lar	a.
Su`pra*cos"tal	a.
Su`pra*cra"ni*al	a.
Su`pra*cre*ta"ceous	a.
Su`pra*de*com"pound	a.
Su`pra-e*soph"a*gal	a.
Su`pra-eth"moid	a.
Su`pra*fo`li*a"ceous	a.
Su`pra*glot"ic	a.
Su`pra*he*pat"ic	a.
Su`pra*hy"oid	a.
Su`pra-il"i*um	n.
Su`pra*lap*sa"ri*an	n.
Su`pra*lap*sa"ri*an	a.
Su`pra*lap*sa"ri*an*ism	n.
Su`pra*lap"sa*ry	a.
Su`pra*lap"sa*ry	n.
Su`pra*lo"ral	a.
Su`pra*lu"nar	a.
Su`pra*max"il*la	n.
Su`pra*max"il*la*ry	a.
Su`pra*mun"dane	a.
Su`pra*nat"u*ral*ism	n.
Su`pra*nat"u*ral*ist	n.
Su`pra*nat"u*ral*ist	a.
Su`pra*oc*cip"i*tal	a.
Su`pra*oc"u*lar	a.
Su`pra-oe*soph"a*gal	a.
Su`pra*or"bit*al	a.
Su*prap"e*dal	a.
Su`pra*pro"test	n.
Su`pra*pu"bi*an	a.
Su`pra*re"nal	a.
Su`pra*scalp"u*lar	a.
Su`pra*sphe*noid"al	a.
Su`pra*spi"nal	a.
Su`pra*spi"nate	a.
Su`pra*sta*pe"di*al	a.
Su`pra*ster"nal	a.
Su`pra*tem"po*ral	a.
Su`pra*troch"le*ar	a.
Su`pra*vag"i*nal	a.
Su`pra*vi"sion	n.
Su`pra*vis"or	n.
Su`pra*vul"gar	a.
Su*prem"a*cy	n.
Su*preme"	a.
Su*preme"ly	adv.
Su*prem"i*ty	n.
Sur-	n.
Su`ra*dan"ni	n.
Sur`ad*di"tion	n.
Su"rah	n.
Su"ral	a.
Sur"ance	n.
Sur*an"gu*lar	a.
Sur"base`	n.
Sur"based`	a.
Sur*bate"	v. t.
Sur*beat"	v. t.
Sur*bed"	v. t.
Sur*bet"	v. t.
Sur*bet"	a.
Sur*cease"	n.
Sur*cease"	v. t.
Sur*cease"	v. i.
Sur*cease"ance	n.
Sur*charge"	v. t.
Sur*charge"	n.
Sur*charge"ment	n.
Sur*char"ger	n.
Sur"cin`gle	n.
Sur"cin`gled	a.
Sur"cle	n.
Sur"cloy	v. t.
Sur"coat`	n.
Sur"crew`	n.
Sur"cu*late	v. t.
Sur`cu*la"tion	n.
Sur"cu*lose`	a.
Surd	a.
Surd	n.
Surd"al	a.
Surd"i*ny	n.
Surd"i*ty	n.
Sure	a.
Sure	adv.
Sure"-foot`ed	a.
Sure"ly	adv.
Sure"ment	n.
Sure"ness	n.
Sures"by	n.
Sure"ti*ship	n.
Sure"ty	n.
Sure"ty	v. t.
Sure"ty*ship	n.
Surf	n.
Surf	n.
Sur"face`	n.
Sur"face	v. t.
Sur"face	v. i.
Sur"face load`ing	n.
Sur"face ten"sion	n.
Sur"feit	n.
Sur"feit	v. i.
Sur"feit	v. t.
Sur"feit*er	n.
Sur"feit-wa`ter	n.
Sur"fel	v. t.
Surf"er	n.
Surf"man	n.
Sur"foot`	a.
Surf"y	a.
Surge	n.
Surge	v. i.
Surge	v. t.
Surge"ful	a.
Surge"less	a.
Sur"gent	a.
Sur"geon	n.
Sur"geon*cy	n.
Sur"geon*ry	n.
Sur"ge*ry	n.
Sur"gi*cal	a.
Sur"gi*cal*ly	adv.
Sur"gy	a.
su"ri*cat	n.
Su`ri*nam" toad"	prop. n.
Sur`in*tend"ant	n.
Sur"li*ly	adv.
Sur"li*ness	n.
Sur"ling	n.
Sur"loin`	n.
Sur"ly	a.
Sur"mark`	n.
Sur*mis"a*ble	a.
Sur*mis"al	n.
Sur*mise"	n.
Sur*mise"	v. t.
Sur*mis"er	n.
Sur*mis"ing	a. & n.
Sur*mount"	v. t.
Sur*mount"a*ble	a.
Sur*mount"ed	a.
Sur*mount"er	n.
Sur*mul"let	n.
Sur"mu*lot	n.
Sur"name`	n.
Sur*name"	v. t.
Sur*nom"i*nal	a.
Sur*ox"i*date	v. t.
Sur*ox"ide	n.
Sur*pass"	v. t.
Sur*pass"a*ble	a.
Sur*pass"ing	a.
Sur"phul	v. t.
Sur"plice	n.
Sur"pliced	a.
Sur"plus	n.
Sur"plus	a.
Sur"plus*age	n.
Sur*pris"al	n.
Sur*prise"	n.
Sur*prise"	v. t.
Sur*prise"ment	n.
Sur*pris"er	n.
Sur*pris"ing	a.
Sur"que*dous	a.
Sur"que*dry	n.
Sur`re*bound"	v. i.
Sur`re*but"	v. i.
Sur`re*but"er	n.
Sur"rein`	v. t.
Sur`re*join"	v. i.
Sur`re*join"der	n.
Sur*ren"der	v. t.
Sur*ren"der	v. i.
Sur*ren"der	n.
Sur*ren`der*ee"	n.
Sur*ren"der*er	n.
Sur*ren`der*or"	n.
Sur*ren"dry	n.
Sur*rep"tion	n.
Sur`rep*ti"tious	a.
Sur"rey	n.
Sur"ro*gate	n.
Sur"ro*gate	v. t.
Sur"ro*gate mother	n.
Sur"ro*gate*ship	n.
Sur`ro*ga"tion	n.
Sur*round"	v. t.
Sur*round"	n.
Sur*round"ing	a.
Sur*round"ing	n.
Sur*roy"al	n.
Sur"sa*nure	n.
Sur"se*ance	n.
Sur*sol"id	n.
Sur*style"	v. t.
Sur"sum cor"da	n.
Sur*tax"	v. t.
Sur*tout"	n.
Sur"tur*brand	n.
Su`ru*cu"cu	n.
Sur*veil"lance	n.
Sur*veil"lant	n.
Sur*veil"lant	a.
Sur*vene"	v. t.
Sur"ve*nue	n.
Sur*vey"	v. t.
Sur"vey	n.
Sur*vey"al	n.
Sur*vey"ance	n.
Sur*vey"ing	n.
Sur*vey"or	n.
Sur*vey"or*ship	n.
Sur*view"	v. t.
Sur*view"	n.
Sur*vise"	v. t.
Sur*viv"al	n.
Sur*viv"ance	n.
Sur*vive"	v. t.
Sur*vive"	v. i.
Sur*viv"en*cy	n.
Sur*viv"er	n.
Sur*viv"ing	a.
Sur*viv"or	n.
Sur*viv"or*ship	n.
Sus*cep`ti*bil"i*ty	n.
Sus*cep"ti*ble	a.
Sus*cep"tion	n.
Sus*cep"tive	a.
Sus`cep*tiv"i*ty	n.
Sus*cep"tor	n.
Sus*cip"i*en*cy	n.
Sus*cip"i*ent	a.
Sus*cip"i*ent	n.
Sus`ci*ta*bil"i*ty	n.
Sus"ci*tate	v. t.
Sus`ci*ta"tion	n.
Sus"lik	n.
Sus*pect"	a.
Sus*pect"	n.
Sus*pect"	v. t.
Sus*pect"	v. i.
Sus*pect"a*ble	a.
Sus*pect"ed	a.
Sus*pect"er	n.
Sus*pect"ful	a.
Sus*pec"tion	n.
Sus*pec"tious*ness	n.
Sus*pect"less	a.
Sus*pend"	v. t.
Sus*pend"	v. i.
Sus*pend"er	n.
Sus`pen*sa"tion	n.
Sus*pense"	a.
Sus*pense"	n.
Sus*pense"ly	adv.
Sus*pen`si*bil"i*ty	n.
Sus*pen"si*ble	a.
Sus*pen"sion	n.
Sus*pen"sive	a.
Sus*pen"sor	n.
Sus`pen*so"ri*um	n.
Sus*pen"so*ry	a.
Sus*pen"so*ry	n.
Sus"pi*ca*ble	a.
Sus*pi"cien*cy	n.
Sus*pi"cion	n.
Sus*pi"cion	v. t.
Sus*pi"cious	a.
Sus*pir"al	n.
Sus`pi*ra"tion	n.
Sus*pire"	v. i.
Sus*pire"	n.
Sus*pired"	a.
Sus*tain"	v. t.
Sus*tain"	n.
Sus*tain"a*ble	a.
Sus*tained"	a.
Sus*tain"er	n.
Sus*tain"ment	n.
Sus*tal"tic	a.
Sus"te*nance	n.
Sus*ten"ta*cle	n.
Sus`ten*tac"u*lar	a.
Sus"ten*tate	v. t.
Sus`ten*ta"tion	n.
Sus"ten*ta*tive	a.
Sus*ten"tion	n.
Sus"ter	n.
Su"su	n.
Su*sur"rant	a.
Su`sur*ra"tion	n.
Su*sur"ring*ly	adv.
Su*sur"rous	a.
Su*sur"rus	n.
Su"tile	a.
Sut"ler	n.
Sut"ler*ship	n.
Sut"ling	a.
Su"tor	n.
Su"tra	n.
Sut*tee"	n.
Sut*tee"ism	n.
Sut"tle	n.
Sut"tle	v. i.
Su"tur*al	a.
Su"tur*al*ly	adv.
Su"tur*a`ted	a.
Su"ture	n.
Su"tured	a.
Su*war"row	n.
Su"ze*rain	n.
Su"ze*rain*ty	n.
Swa	adv.
Swab	v. t.
Swab	n.
Swab"ber	v. t.
Swab"ber	n.
Swad	n.
Swad"dle	n.
Swad"dle	v. t.
Swad"dle*bill`	n.
Swad"dler	n.
Swad"dling	a. & n.
Swag	v. i.
Swag	n.
Swag"-bel`lied	a.
Swag"bel`ly	n.
Swage	v. t. & i.
Swage	n.
Swage	v. t.
Swag"ger	v. i.
Swag"ger	v. t.
Swag"ger	n.
Swag"ger	n.
Swag"ger*er	n.
Swag"gie	n.
Swag"gy	a.
Swag"man	n.
Swags"man	n.
Swain	n.
Swain"ish	a.
Swain"ling	n.
Swain"mote`	n.
Swain"ship	n.
Swaip	v. i.
Swal	imp.
Swale	n.
Swale	v. i. & t.
Swale	n.
Swal"let	n.
Swal"low	n.
Swal"low	v. t.
Swal"low	v. i.
Swal"low	n.
Swal"low*er	n.
Swal"low*fish`	n.
Swal"low*tail`	n.
Swal"low-tailed`	a.
Swal"low*wort`	n.
Swam	imp.
Swamp	n.
Swamp	v. t.
Swamp	v. i.
Swamp"y	a.
Swan	n.
Swang	imp.
Swang	n.
Swan"herd`	n.
Swan"-hop`ping	n.
Swan"i*mote	n.
Swank"ie	n.
Swan"like`	a.
Swan"mark`	n.
Swan"ner*y	n.
Swan"ny	a.
Swan"pan	n.
Swan's"-down`	n.
Swan"skin`	n.
Swan"-up`ping	n.
Swap	v. t.
Swap	v. i.
Swap	n.
Swap	adv.
Swape	n.
Sward	n.
Sward	v. t. & i.
Sward"-cut`ter	n.
Sward"ed	a.
Sward"y	a.
Sware	imp.
Swarf	v. i.
Swarf	n.
Swarm	v. i.
Swarm	n.
Swarm	v. i.
Swarm	v. t.
Swarm"spore`	n.
Swart	n.
Swart	a.
Swart	v. t.
Swart"back`	n.
Swarth	a.
Swarth	n.
Swarth	n.
Swarth	n.
Swarth"i*ly	adv.
Swarth"i*ness	n.
Swarth"ness	n.
Swarth"y	a.
Swarth"y	v. t.
Swart"i*ness	n.
Swart"ish	a.
Swart"ness	n.
Swart"y	a.
Swarve	v. i.
Swash	n.
Swash	a.
Swash	v. i.
Swash	n.
Swash"buc`kler	n.
Swash"er	n.
Swash"ing	a.
Swash"way`	n.
Swash"y	a.
Swas"ti*ka	n.
Swat	imp.
Swat	v. t.
Swat	n.
Swat	n.
SWAT" team`	n.
Swatch	n.
Swate	imp.
Swath	n.
Swathe	v. t.
Swathe	n.
Swath"er	n.
Swat"te	imp.
Sway	v. t.
Sway	v. i.
Sway	n.
Sway"-backed`	a.
Sway bar	n.
Swayed	a.
Sway"ful	a.
Sway"ing	n.
Sweal	v. i.
Sweal	v. t.
Swear	v. i.
Swear	v. t.
Swear"er	n.
Swear"ing	a. & n.
Sweat	v. i.
Sweat	v. t.
Sweat	n.
Sweat"er	n.
Sweat"i*ly	adv.
Sweat"i*ness	n.
Sweat"ing	a. & n.
Sweat"y	a.
Swede	n.
Swe`den*bor"gi*an	n.
Swe`den*bor"gi*an	a.
Swe`den*bor"gi*an*ism	n.
Swed"ish	a.
Swed"ish	n.
Swee"ny	n.
Sweep	v. t.
Sweep	v. i.
Sweep	n.
Sweep"age	n.
Sweep"er	n.
Sweep"ing	a.
Sweep"ings	n. pl.
Sweep"-saw`	n.
Sweep"stake`	n.
Sweep"stakes`	n.
Sweep"wash`er	n.
Sweep"y	a.
Sweet	a.
Sweet	n.
Sweet	adv.
Sweet	v. t.
Sweet"bread`	n.
Sweet"-breast`ed	a.
Sweet"bri`er	n.
Sweet"en	v. t.
Sweet"en	v. i.
Sweet"en*er	n.
Sweet"en*ing	n.
Sweet"heart`	n.
Sweet"heart`ing	n.
Sweet"ing	n.
Sweet"ish	a.
Sweet"ly	adv.
Sweet"meat`	n.
Sweet"ness	n.
Sweet"root`	n.
Sweet"-scent`ed	a.
Sweet"-sop`	n.
Sweet"wa`ter	n.
Sweet"weed`	n.
Sweet"wood`	n.
Sweet"wort`	n.
Sweigh	n.
Swein"mote`	n.
Swell	v. i.
Swell	v. t.
Swell	n.
Swell	a.
Swell"dom	n.
Swell"fish`	n.
Swell"ing	n.
Swell"ish	a.
Swell"toad`	n.
Swelt	imp.
Swelt	v. i.
Swelt	v. t.
Swel"ter	v. i.
Swel"ter	v. t.
Swel"try	a.
Swel"ve	v. t.
Swept	imp. & p. p.
Swerd	n. & v.
Swerd	n.
Swerve	v. i.
Swerve	v. t.
Swe"ven	n.
Swich	a.
Swie*te"ni*a	n.
Swift	a.
Swift	adv.
Swift	n.
Swift"er	n.
Swift"er	v. t.
Swift"foot`	a.
Swift"foot`	n.
Swift"let	n.
Swift"ly	adv.
Swift"ness	n.
Swig	v. t.
Swig	n.
Swig	v. t.
Swill	v. t.
Swill	v. i.
Swill	n.
Swill"er	n.
Swill"ings	n. pl.
Swim	v. i.
Swim	v. t.
Swim	n.
Swim	v. i.
Swim"bel	n.
Swim"mer	n.
Swim"mer*et	n.
Swim"ming	a.
Swim"ming	n.
Swim"ming	a.
Swim"ming	n.
Swim"ming*ly	adv.
Swim"ming*ness	n.
Swinck	v. & n.
Swin"dle	v. t.
Swin"dle	n.
Swin"dler	n.
Swin"dler*y	n.
Swine	n. sing. & pl.
Swine"bread`	n.
Swine"case`	n.
Swine"cote`	n.
Swine"crue`	n.
Swine"fish`	n.
Swine"herd`	n.
Swine"pipe`	n.
Swine"-pox`	n.
Swin"er*y	n.
Swine"stone`	n.
Swine"sty`	n.
Swing	v. i.
Swing	v. t.
Swing	n.
Swing"dev`il	n.
Swinge	v. & n.
Swinge	v. t.
Swinge	n.
Swinge"buc`kler	n.
Swinge"ing	a.
Swin"gel	n.
Swing"er	n.
Swin"ger	n.
Swin"gle	v. i.
Swin"gle	v. t.
Swin"gle	n.
Swin"gle*bar`	n.
Swin"gle*tail`	n.
Swin"gle*tree`	n.
Swin"gling	a. & n.
Swing"tree`	n.
Swin"ish	a.
Swink	v. i.
Swink	v. t.
Swink	n.
Swink"er	n.
Swin"ney	n.
Swipe	n.
Swipe	v. t.
Swi"ple	n.
Swip"per	a.
Swirl	v. t. & i.
Swirl	n.
Swish	v. t.
Swish	v. i.
Swish	n.
Swiss	n. sing. & pl.
Swiss	a.
Switch	n.
Switch	v. t.
Switch	v. i.
switch"board`	n.
Switch"el	n.
switch"er*oo	n.
Switch"ing	a. & n.
Switch"ing power supply	n.
Switch"man	n.
Switch"y	a.
Swithe	adv.
Switz"er	n.
Swive	v. t.
Swiv"el	n.
Swiv"el	v. i.
Swiv"el-eyed`	a.
Swiz"zle	v. t.
Swiz"zle	n.
Swob	n. & v.
Swob"ber	n.
Swoll"en	p. p.
Swoll"en	a.
Swoln	p. p.
Swom	imp.
Swoon	v. i.
Swoon	n.
Swoon"ing	a. & n.
Swoop	v. t.
Swoop	v. i.
Swoop	n.
Swoop"stake`	n.
Swoop"stake`	adv.
Swop	v. & n.
Sword	n.
Sword"bill`	n.
Sword"ed	a.
Sword"er	n.
Sword"fish`	n.
Sword"ick	n.
Sword"ing	n.
Sword"less	a.
Sword"man	n.
Sword"play`	n.
Sword"play`er	n.
Sword"-shaped`	a.
Swords"man	n.
Swords"man*ship	n.
Sword"tail`	n.
Swore	imp.
Sworn	p. p.
Swough	n.
Swound	v. & n.
'Swounds	interj.
Swown	v. & n.
Swum	imp. & p. p.
Swung	imp. & p. p.
Swythe	adv.
Sy	imp.
Syb	a.
Syb"a*rite	n.
Syb`a*rit"ic	a.
Syb"a*rit*ism	n.
Syc"a*mine	n.
Syc"a*more	n.
Syce	n.
Sy*cee"	n.
Sych`no*car"pous	a.
Sy"cite	n.
Syc`o*cer"ic	a.
Syc`o*ce"ryl	n.
Sy"cock	n.
Sy*co"nes	n. pl.
Sy*co"ni*um	n.
Syc"o*phan*cy	n.
Syc"o*phant	n.
Syc"o*phant	v. t.
Syc"o*phant	v. i.
Syc"o*phant*cy	n.
Syc`o*phan"tic	a.
Syc"o*phant`ish	a.
Syc"o*phant*ism	n.
Syc"o*phant*ize	v. i.
Syc"o*phant*ry	n.
Sy*co"sis	n.
Syd"er*o*lite	n.
Sye	imp.
Sy"e*nite	n.
Sy`e*nit"ic	a.
Syke	n. & v.
Syk"er	a. & adv.
Syle	n.
Syl`la*ba"ri*um	n.
Syl"la*ba*ry	n.
Syl"labe	n.
Syl*lab"ic	a.
Syl*lab"ic*al*ly	adv.
Syl*lab"i*cate	v. t.
Syl*lab`i*ca"tion	n.
Syl*lab`i*fi*ca"tion	n.
Syl*lab"i*fy	v. t.
Syl"la*bism	n.
Syl"la*bist	n.
Syl"la*bize	v. t.
Syl"la*ble	n.
Syl"la*ble	v. t.
Syl"la*bub	n.
Syl"la*bus	n.
Syl*lep"sis	n.
Syl*lep"tic	a.
Syl*lid"i*an	n.
Syl"lo*gism	n.
Syl`lo*gis"tic	a.
Syl`lo*gis"tic*al*ly	adv.
Syl`lo*gi*za"tion	n.
Syl"lo*gize	v. i.
Syl"lo*gi`zer	n.
Sylph	n.
Sylph"id	n.
Sylph"ine	a.
Sylph"ish	a.
Sylph"like`	a.
Syl"va	n.
Syl"van	a.
Syl"van	n.
Syl"van	n.
Syl"van*ite	n.
Syl*va"ni*um	n.
Syl"vate	n.
Syl*vat"ic	a.
Syl*ves"tri*an	a.
Syl"vic	a.
Syl*vic"o*line	a.
Syl"vi*cul`ture	n.
Syl`vi*cul"tur*ist	n.
Syl"vine	n.
Sym-	n.
Sym"bal	n.
Sym`bi*o"sis	n.
Sym`bi*ot"ic	a.
Sym"bol	n.
Sym"bol	v. t.
Sym*bol"ic	n.
Sym*bol"ic	a.
Sym*bol"ics	n.
Sym"bol*ism	n.
Sym"bol*ist	n.
Sym`bol*is"tic	a.
Sym`bol*i*za"tion	n.
Sym"bol*ize	v. i.
Sym"bol*ize	v. t.
Sym"bol*i`zer	n.
Sym`bo*log"i*cal	a.
Sym*bol"o*gist	n.
Sym*bol"o*gy	n.
Sym*bran"chi*i	n. pl.
Sym"me*tral	a.
Sym*me"tri*an	n.
Sym*met"ric	a.
Sym*met"ric*al	a.
Sym`me*tri"cian	n.
Sym"me*trist	n.
Sym"me*trize	v. t.
Sym"me*try	n.
Sym`pa*thet"ic	a.
Sym`pa*thet"ic*al	a.
Sym`pa*thet"ic*al*ly	adv.
Sym"pa*thist	n.
Sym"pa*thize	v. i.
Sym"pa*thize	v. t.
Sym"pa*thi`zer	n.
Sym"pa*thy	n.
Sym*pet"al*ous	a.
Sym*phon"ic	a.
Sym*pho"ni*ous	a.
Sym"pho*nist	n.
Sym"pho*nize	v. i.
Sym"pho*ny	n.
Sym*phy"la	n. pl.
Sym*phys"e*al	a.
Sym`phy*se*ot"o*my	n.
Sym"phy*sis	n.
Sym`phy*sot"o*my	n.
Sym"phy*tism	n.
Sym`pi*e*som"e*ter	n.
Sym*plec"tic	a.
Sym"plo*ce	n.
Sym"pode	n.
Sym*po"di*al	a.
Sym*po"di*um	n.
Sym*po"si*ac	a.
Sym*po"si*ac	n.
Sym*po"si*arch	n.
Sym*po"si*ast	n.
Sym*po"si*on	n.
Sym*po"si*um	n.
Symp"tom	n.
Symp`tom*at"ic	a.
Symp`tom*a*tol"o*gy	n.
Syn-	n.
Syn*aer"e*sis	n.
Syn`a*gog"ic*al	a.
Syn"a*gogue	n.
Syn`a*le"pha	n.
Syn`al*lag*mat"ic	a.
Syn`al*lax"ine	a.
Syn`a*loe"pha	n.
Syn*an"gi*um	n.
Syn*an"ther*ous	a.
Syn`an*the"sis	n.
Syn*an"thous	a.
Syn*an"throse"	n.
Syn*ap"ta	n.
Syn*ap"tase	n.
Syn`ap*tic"u*la	n.
Syn"ar*chy	n.
Syn`ar*te"sis	n.
Syn`ar*thro"di*a	n.
Syn`ar*thro"sis	n.
Syn"as*try	n.
Syn*ax"is	n.
Syn"carp	n.
Syn*car"pi*um	n.
Syn*car"pous	a.
Syn*cat`e*gor`e*mat"ic	a.
Syn`chon*dro"sis	n.
Syn`chon*drot"o*my	n.
Syn`cho*re"sis	n.
Syn"chro*nal	a.
Syn"chro*nal	n.
Syn*chron"ic*al	a.
Syn"chro*nism	n.
Syn`chro*nis"tic	a.
Syn`chro*ni*za"tion	n.
Syn"chro*nize	v. i.
Syn"chro*nize	v. t.
Syn`chro*nol"o*gy	n.
Syn"chro*nous	a.
Syn"chro*ny	n.
Syn"chy*sis	n.
Syn*clas"tic	a.
Syn*cli"nal	a.
Syn*cli"nal	n.
Syn*cline"	n.
Syn*clin"ic*al	a.
Syn`cli*no"ri*um	n.
Syn"co*pal	a.
Syn"co*pate	v. t.
Syn`co*pa"tion	n.
Syn"co*pe	n.
Syn"co*pist	n.
Syn"co*pize	v. t.
Syn*cot`y*led"on*ous	a.
Syn*cret"ic	a.
Syn"cre*tism	n.
Syn"cre*tist	n.
Syn`cre*tis"tic	a.
Syn"cri*sis	n.
Syn*cy"ti*um	n.
Syn*dac"tyl	a.
Syn*dac"tyle	n.
Syn*dac*tyl"ic	a.
Syn*dac"tyl*ous	a.
Syn`des*mog"ra*phy	n.
Syn`des*mol"o*gy	n.
Syn`des*mo"sis	n.
Syn*det"ic	a.
Syn"dic	n.
Syn"dic*al	a.
Syn"dic*al*ism	n.
Syn"dic*al*ist	n.
Syn"di*cate	n.
Syn"di*cate	v. t.
Syn"di*cate	v. t.
Syn"di*cate	v. i.
Syn`di*ca"tion	n.
Syn"dro*me	n.
Syn`dy*as"mi*an	a.
Syne	adv.
Syne	conj.
Syn*ec"do*che	n.
Syn`ec*doch"ic*al	a.
Syn`ec*doch"ic*al*ly	adv.
Syn*e"chi*a	n.
Syn*ec`pho*ne"sis	n.
Syn*e"dral	a.
Syn`en*tog"na*thi	n. pl.
Syn"e*py	n.
Syn*er"e*sis	n.
Syn`er*get"ic	a.
Syn"er*gism	n.
Syn"er*gist	n.
Syn`er*gis"tic	a.
Syn"er*gy	n.
Syn"e*sis	n.
Syn`ge*ne"si*a	n. pl.
Syn`ge*ne"sian	a.
Syn*gen"e*sis	n.
Syng"na*thi	n. pl.
Syn"graph	n.
Syn`i*ze"sis	n.
Syn`neo*ro"sis	n.
Syn"o*cha	n.
Syn"o*chal	a.
Syn"o*chus	n.
Syn"o*cil	n.
Syn"od	n.
Syn"od*al	a.
Syn"od*al	n.
Syn*od"ic	a.
Syn*od"ic*al*ly	adv.
Syn"od*ist	n.
Syn*oe"cious	a.
Syn*om"o*cy	n.
Syn"o*nym	n.
Syn*on"y*ma	n. pl.
Syn*on"y*mal	a.
Syn*on"y*mal*ly	adv.
Syn"o*nyme	n.
Syn`o*nym"ic	n.
Syn`o*nym"ic	a.
Syn`o*nym"i*con	n.
Syn*on"y*mist	n.
Syn*on"y*mize	v. t.
Syn*on"y*mous	a.
Syn*on"y*my	n.
Syn*op"sis	n.
Syn*op"tic	a.
Syn*op"tic	n.
Syn*op"tist	n.
Syn*os`te*ol"o*gy	n.
Syn*os`te*o"sis	n.
Syn`os*to"sis	n.
Syn*o"vi*a	n.
Syn*o"vi*al	a.
Syn`o*vi"tis	n.
Syn*pel"mous	a.
Syn*sep"al*ous	a.
Syn*tac"tic	a.
Syn"tax	n.
Syn*tax"is	n.
Syn`te*re"sis	n.
Syn`te*ret"ic	a.
Syn`te*ret"ics	n.
Syn*ther"mal	a.
Syn"the*sis	n.
Syn"the*sist	n.
Syn"the*size	v. t.
Syn*thet"ic	a.
Syn*thet"ic*al*ly	adv.
Syn"the*tize	v. t.
Syn"to*my	n.
Syn*ton"ic	a.
Syn"to*nin	n.
Syn"to*nize	v. t.
Syn"to*niz`er	n.
Syn"to*ny	n.
Sy"pher*ing	n.
Syph"i*lide	n.
Syph"i*lis	n.
Syph`i*lit"ic	a.
Syph`i*lit"ic*al*ly	adv.
Syph`i*li*za"tion	n.
Syph"i*lize	v. t.
Syph"i*lo*derm	n.
Syph`i*lo*der"ma*tous	a.
Syph"i*loid	a.
Syph`i*lol"o*gist	n.
Syph`i*lol"o*gy	n.
Sy"phon	n.
Syr"a*cuse	n.
Sy"ren	n.
Syr"i*ac	a.
Syr"i*a*cism	n.
Syr"i*an	a.
Syr"i*an*ism	n.
Syr"i*asm	n.
Sy*rin"ga	n.
Syr"inge	n.
Syr"inge	v. t.
Sy*rin"ge*al	a.
Sy*rin"gin	n.
Sy*rin"go*coele	n.
Sy*rin"go*tome	n.
Syr`in*got"o*my	n.
Syr"inx	n.
Syr"ma	n.
Syr"phi*an	a.
Syr"phus fly`	n.
Syr"tic	a.
Syr"tis	n.
Syr"up	n.
Sys`sar*co"sis	n.
Sys*tal"tic	a.
Sys"ta*sis	n.
Sys"tem	n.
Sys`tem*at"ic	a.
Sys`tem*at"ic*al*ly	adv.
Sys"tem*a*tism	n.
Sys"tem*a*tist	n.
Sys`tem*a*ti*za"tion	n.
Sys"tem*a*tize	v. t.
Sys"tem*a*ti`zer	n.
Sys`tem*a*tol"o*gy	n.
Sys*tem"ic	a.
Sys`tem*i*za"tion	n.
Sys"tem*ize	v. t.
Sys"tem*i`zer	n.
Sys"tem*less	a.
Sys"to*le	n.
Sys*tol"ic	a.
Sys"tyle	a.
Syth	prep., adv., conj. & n.
Sythe	n.
Sy*zyg"i*al	a.
Syz"y*gy	n.
